### ISSUE TITLE
[Feature request] Default commands with a logic

### ISSUE THREAD

**Issue by italodeandra** [coollabsio/coolify#100]
When I deploy a Next.js application, it automatically adds `yarn` commands to the Default commands.

But the default should be `npm` commands:

![image](https://user-images.githubusercontent.com/19225266/141833968-1abe77f3-b06e-4a44-9def-37e77bdec07d.png)

And only use `yarn` as default commands with the existence of a `yarn.lock` file.

**Comment by andrasbacsai** [comment]
It will be released in #159

**Comment by italodeandra** [comment]
❤️
