### ISSUE TITLE
[Feature]: Build images using external agent/server

### ISSUE THREAD

**Issue by cruonline** [coollabsio/coolify#1000]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

It would be cool if we could offload the build process to another host, to avoid too much strain on coolify host.

### Why should this be worked on?

Currently, it can happen, that the build process consumes too much memory, and the stability of the host is compromised.

**Comment by andrasbacsai** [comment]
It will be available in v4.


I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
