### ISSUE TITLE
[Feature]: Postgres secure ssl connection

### ISSUE THREAD

**Issue by snimshchikov** [coollabsio/coolify#1005]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Postgres supports tls encryption, but bitnami image doesn't turn it on by default. It can easily be turned on and managed by coolify. 

How to enable: https://github.com/bitnami/containers/tree/main/bitnami/postgresql#securing-postgresql-traffic

My idea is to use main coolify domain and it's certificates (if user configured it). 
It's easy and convenient, connection string would look like `postgresql://user:pass@coolify.mydomain.com:9000/dbname`

### Why should this be worked on?

Insecure connections are bad. Coolify has an option to expose database to the internet, it shouldn't come at cost of security
https://innerjoin.bit.io/the-majority-of-postgresql-servers-on-the-internet-are-insecure-f1e5ea4b3da3

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
