### ISSUE TITLE
[Bug]: App has too many 'webhook_commit' instances

### ISSUE THREAD

**Issue by henk23** [coollabsio/coolify#1006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

I don't know how it happend, but for every commit my app is built 5 times.
First build takes around 50 seconds. Every consecutive build has a container image "found locally" and only takes 5s.

Expectation: There is only one build on a commit.

![screenshot](https://user-images.githubusercontent.com/10068060/227474090-79f0e40b-2192-4d68-8431-4900428ffa5a.png)

### Steps To Reproduce

Don't know how it happened. But I cannot get rid of the extra builds.

### Version

3.12.29

**Comment by henk23** [comment]
Found the issue:

![gitlab-webhooks](https://user-images.githubusercontent.com/10068060/235341258-e8056c38-7a75-497f-8129-e698a0741954.png)

Too many of the same GitLab webhooks are created. I think there was a problem in my browser connecting to GitLab at the time. Just deleted all but one of the webhooks.

Maybe add a check in coolify to first check for existing webhook and then skip adding another one?

**Comment by edgardoll4** [comment]
I have a problem with the implementation of a gitlab repository in coolify, the project is up and everything, but before when I made a commit to the branch that is deployed it is in coolify it autodeployed automatically, but now I don't want to do it.

I tried the URL and the result that it gives me, I tried it with two different gitlab accounts and it gives me the same error

example: https://panel.dominio.xyz./webhooks/gitlab

{
"status": 500,
"message": "Cannot read properties of null (reading 'appId')"
}

In gitlab I search the repository and go to the webhooks and I get the following:

![image](https://github.com/coollabsio/coolify/assets/32710186/bc695a48-4e2c-4dcb-b985-b63b10601dc4)

When I do the test from gitlab I get the following error

![image](https://github.com/coollabsio/coolify/assets/32710186/7db17809-22ef-40ce-9fe1-bad7e41a199a)

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
