### ISSUE TITLE
[Feature request] Ability to set custom Traefik tags

### ISSUE THREAD

**Issue by fishnux** [coollabsio/coolify#101]
Hi,

The ability to set custom Traefik tags would be awesome! My use case is to configure rate limits on incoming HTTP requests, particularly to help defend against (D)DoS attacks.

For those curious, this is the blog post I have as reference:
https://faun.pub/prevent-ddos-attacks-with-traefik-2-44fb32eeac4f

**Comment by andrasbacsai** [comment]
Hey @fishnux ,

This issue is deprecated with version 2 of Coolify. Traefik is not used anymore.
