### ISSUE TITLE
[Feature]: Preview URL via environment variables

### ISSUE THREAD

**Issue by brunos3d** [coollabsio/coolify#1016]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add the ability to retrieve the deployment URLs (including preview deployments) from environment variables. And include some more useful env vars like [Vercel System Environment Variables](https://vercel.com/docs/concepts/projects/environment-variables/system-environment-variables#system-environment-variables) or [Netlify Build env vars](https://docs.netlify.com/configure-builds/environment-variables/#netlify-configuration-variables)

### Why should this be worked on?

This support for environment variables is essential for configuring and securing modern web applications. It makes it easy to manage and deploy applications with different configurations for different environments, which is especially useful for preview environments. By using environment variables, you can keep your application code and configuration files clean and secure, while still providing the flexibility and control you need to build robust and reliable applications.

Another issue I'd like to address https://github.com/coollabsio/coolify/issues/449. It would be great to have these two feature requests working together.

Just in love with this project :heart:

**Comment by andrasbacsai** [comment]
This will be added to v4.

I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
