### ISSUE TITLE
[Task]: How to deploy applications like listmonk

### ISSUE THREAD

**Issue by nidhin077** [coollabsio/coolify#1018]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

How can we host an application like listmonk in coolify, because a temporary docker run is required to populate the data to the database. The docker up command like this 
docker-compose up -d listmonk-db && \
docker-compose run --rm listmonk-app ./listmonk --install && \
docker-compose up -d listmonk-app
https://github.com/knadh/listmonk
Please assist me if you have any information on this.

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
