### ISSUE TITLE
[Feature]: More configurability

### ISSUE THREAD

**Issue by smac89** [coollabsio/coolify#1023]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

After some struggle, I was able to get `coolify` to somewhat run within my VPS along side other apps already running there. I still don't have `HTTPS` working, even after setting my FQDN to point to a https domain. Also it doesn't look like the proxy is running either. Majority of the issues I faced was with regards to the docker sock, and the rest were minor issues that can be fixed by editing the install script.

### Why should this be worked on?

1. The biggest pain point was the **assumption of a `/var/run/docker.sock`** on the host machine. This seems to be hardcoded within coolify, so I don't even see how it can work with a remote docker host, which is an option for "Destinations":

    ![coolify-dest](https://user-images.githubusercontent.com/8305511/229258673-96b1c41b-b92c-4e8c-a629-bc7baeaa90eb.png)

    This option should be configurable, so that people who use rootless docker or have a docker server running else where can easily configure it.

2. The host address should be configurable especially given that some people may already have something like nginx running or may not want to open up their instance of coolify to the world on port 3000. My solution for this was to create a docker network and manually connect the `coolify` container to it:
    ```
    docker network create -o "com.docker.network.bridge.host_binding_ipv4"="127.7.7.7" vps_coolify_network
    docker network connect vps_coolify_network coolify
    ```

3. The use of `sudo` should be configurable. As I mentioned, docker can be run rootless, which means one doesn't need `sudo`.

**Comment by boywithkeyboard** [comment]
@andrasbacsai I've just found out about coolify and I really like it, but I think it would be cool if you could just deploy your applications to one or more other servers as it's just stupid to have coolify (the management tool) and the production code on the same machine. It also isn't really scalable. *(It would be also beneficial if the other servers wouldn't require any prior setup at all and coolify could just handle all for you with a few clicks from the main server.)*

What's your opinion on this? Would be cool if you'd implement such a feature :)

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
