### ISSUE TITLE
[Feature]: Admin - create new user from dashboard

### ISSUE THREAD

**Issue by ChronSyn** [coollabsio/coolify#1026]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

As an administrator, I would like the ability to register users to my Coolify instance without enabling public registration.

### Why should this be worked on?

At the moment, it is not possible to invite or add users on the platform without enabling public registration. For example, if multiple developers will be working on a project, I may not want to open up the registration page to them, but would instead prefer to register them directly.

This feature would prevent a scenario where a potential attacker could register an account and gain access to private projects, or to perform actions such as deleting them.

**Comment by ChronSyn** [comment]
As a note, I'm currently investigating this functionality and may have a PR available soon

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
