### ISSUE TITLE
[Bug]: Docker Pull Command Fails When Trying to Update Coolify

### ISSUE THREAD

**Issue by danieldogeanu** [coollabsio/coolify#1029]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

When I click on the update button from the Coolify dashboard, I get the following error:

```
Command failed with exit code 1: docker pull coollabsio/coolify:3.12.29
Error response from daemon: manifest for coollabsio/coolify:3.12.29 not found: 
manifest unknown: manifest unknown:
```

I assume this is because the registry for the docker images was changed, and now the command can't find it. All this because [Docker decided to delete Open Source organizations](https://blog.alexellis.io/docker-is-deleting-open-source-images/). 

My question is how do I change the registry so the `docker pull` command will work, so I can update my instance of Coolify?

![coolify-error](https://user-images.githubusercontent.com/5739197/229409292-9e46e10e-265d-4790-a47f-ec71d4f010be.png)

### Steps To Reproduce

1. Login to Coolify dashboard.
2. Click on the pink update button.

### Version

3.12.27

**Comment by andrasbacsai** [comment]
Ah right! This could be solved by manually running the installation command on your server, that will update your Coolify.

But I copied the latest version from ghcr to dockerhub, so the button should work!
