### ISSUE TITLE
[Feature]: 2FA for login

### ISSUE THREAD

**Issue by nidhin077** [coollabsio/coolify#1032]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Hi,

Will you kindly include a 2FA authentication feature for all users? For this application, the authentication functions are significantly more essential. So, concentrate on it and hope your team releases it as soon as possible.

### Why should this be worked on?

It would greatly improve security.

**Comment by rinshadka** [comment]
@vasani-arpit would like to know regarding any feature release soon to include 2fa support

**Comment by omars44** [comment]
Apparently its available in 4.0.0 beta, but it's broken, it requires pasword confirmation, and then rejects the password anyway
@rinshadka  @vasani-arpit

**Comment by andrasbacsai** [comment]
It is available in v4.

I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
