### ISSUE TITLE
[Feature]: Allow to clone from gitlab using https instead ssh

### ISSUE THREAD

**Issue by jungsid95** [coollabsio/coolify#1033]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Hi,

Currently we are using Gitlab Self Hosted behind reverse proxy. The SSH port is not open and we use HTTPS instead to clone.

Would be happy if we can clone through HTTPS instead.

### Why should this be worked on?

It would be great for server architecture like us where we dont expose SSH on our gitlab self hosted server

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
