### ISSUE TITLE
[Bug]: 404 page not found webhook github source no port

### ISSUE THREAD

**Issue by masterbater** [coollabsio/coolify#1038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

There is bug if there is no domain connected, the webhook redirection wont include the port 

### Steps To Reproduce

Save and Redirect to Github

### Version

3.12.3

**Comment by JosTheDude** [comment]
Yup, just had this issue myself.

**Comment by andrasbacsai** [comment]
Due to inactivity, I'm closing this issue. However, if the problem persists, please reopen the issue. Thanks!
