### ISSUE TITLE
[Bug]: Application logs is not working as it should.

### ISSUE THREAD

**Issue by kalabamba** [coollabsio/coolify#1039]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

When the application trigger a console.log(), the previous line is reprinted after the 2nd trigger. When i reopen to application logs it looks like it should.

### Steps To Reproduce

1. Run app.
2. Trigger a console.log().
3. Trigger a console.log() again.

 Before reload the page:
![prev](https://user-images.githubusercontent.com/12143590/231736026-181a2fa1-26cf-411a-b644-5279a068654a.JPG)

5. Reload the page.

After reload the page:
![after-reload](https://user-images.githubusercontent.com/12143590/231736603-4c16a6ee-9634-47b7-8191-9fd5d5881567.JPG)

### Version

3.12.30

**Comment by andrasbacsai** [comment]
Fixing in the next version.
