### ISSUE TITLE
[Bug]: Old tags when trying to make a service update

### ISSUE THREAD

**Issue by arswysocki** [coollabsio/coolify#1043]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

I am using the appwrite service and would like to do an upgrade to the newest version. While a container is stopped, on the tag lists there are only old tags.
<img width="1304" alt="2023-04-16 в 00 07 31" src="https://user-images.githubusercontent.com/107469954/232253176-724553de-a8cd-4c4e-b192-8af46dc9638b.png">

### Steps To Reproduce

Create a new service and try to select version 1.3.1 for Appwrite

### Version

3.12.30

**Comment by paulocoutinhox** [comment]
I have this problem too:
https://github.com/coollabsio/coolify/issues/987

**Comment by arswysocki** [comment]
@vasani-arpit @andrasbacsai , seems like the issue has been resolved and this ticket can be closed

**Comment by andrasbacsai** [comment]
I fixed it, but also adding a possibility to add custom versions as well.
![image](https://user-images.githubusercontent.com/5845193/232781941-fd366618-0d05-4c7e-b689-b05c31459b09.png)
