### ISSUE TITLE
[Bug]: Cannot read properties in jobs/deployApplication.js

### ISSUE THREAD

**Issue by doraeric** [coollabsio/coolify#1044]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

I found sometimes coolify stopped building and deploying after long running.
I don't know how to reproduce the issue, but I can give all the information I have.

I am currently using coolify in a course with about 60 students. Every student creates at least one application and one database. The server is 36 cores and has 128 GB RAM.
I noticed that sometimes coolify stopped deploying new commits, the build status is "queued", and there is an error in the log. I think the error makes scheduler stop working.
```
docker logs coolify

...
Coolify's API is listening on 0.0.0.0:3000
[001] Initializing server...
[002] Cleanup stucked builds...
[003] Cleaning up old build sources under /tmp/build-sources/...
[004] Tags and templates loaded...
Webhook for Provincial Turquoise Blackbird queued.
Webhook for midterm queued.
Webhook for midterm-website queued.
Webhook for Inadequate Azure Aphid queued.
TypeError: Cannot read properties of undefined (reading 'id')
    at /app/jobs/deployApplication.js:267:57
    at async file:///app/node_modules/.pnpm/p-map@5.5.0/node_modules/p-map/index.js:141:20
Webhook for Costly Pink Halibut queued.
Webhook for Costly Pink Halibut queued.
Webhook for Fat Orange Gazelle queued.
Webhook for Fat Orange Gazelle queued.
...
```
The corresponding code at [deployApplication.ts](https://github.com/coollabsio/coolify/blob/v3.12.27/apps/api/src/jobs/deployApplication.ts#L275)

### Steps To Reproduce

I can't tell how to reproduce.

### Version

3.12.27

**Comment by andrasbacsai** [comment]
I will add a fix in v3.12.31 soon.
