### ISSUE TITLE
[Bug]: Error when change the version of PocketBase

### ISSUE THREAD

**Issue by paulocoutinhox** [coollabsio/coolify#1047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

Hi,

When i change the version of PocketBase to a custom version and try start/deploy it, i get error:

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/395096/233126232-fc9d11af-7c05-4827-983c-cd6f87fa1ebe.png">

### Steps To Reproduce

Start with an existing version.

Stop the service.

Add custom version: "0.14.5".

Start/deploy the service.

### Version

3.12.31

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
