### ISSUE TITLE
[Bug]: Preview Deployments using the same exposed port as the main application, causing the preview to fail on-start

### ISSUE THREAD

**Issue by OG-Jons** [coollabsio/coolify#1048]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

When I try to deploy a preview, the build fails upon running the docker-compose file. The logs tell me, that it tries to use the exposed port, set by the main application itself. 
In this example, port 10004 was set in the configuration of the application itself and I get the following error message:
```
[07:50:26.826] Error: Command failed with exit code 1: docker compose --project-directory /tmp/build-sources/[redacted-username]/[redacted-project]/clgopegbc1lztagqq27yddnsb -f /tmp/build-sources/[redacted-username]/[redacted-project]/clgopegbc1lztagqq27yddnsb/docker-compose.yml up -d
Container clgop50fh00acqqagf7qrwy0u-2  Creating
Container clgop50fh00acqqagf7qrwy0u-2  Created
Container clgop50fh00acqqagf7qrwy0u-2  Starting
Error response from daemon: driver failed programming external connectivity on endpoint clgop50fh00acqqagf7qrwy0u-2 (5b97d543296d20f9c673535f9e51cd52703022a03d200c033d42b6b996166234): Bind for 0.0.0.0:10004 failed: port is already allocated
```
I've looked through the configuration tabs, with no avail. When I took a look at the source code of coolify, I noticed that when it notices, that it's a preview, it doesn't set a separate port. [deployApplication.ts#L344](https://github.com/coollabsio/coolify/blob/f3beb5d8db0c8281d9dbb7c2c123718e6d0fe0d3/apps/api/src/jobs/deployApplication.ts#L344)

### Steps To Reproduce

1. Create Web-Application linked to GitHub
2. Set exposed port (I need this in my particular system)
3. Enable MR/PR Previews
4. Create Pull Request in GitHub
5. Wait for webhook to register

### Version

3.12.30

**Comment by signalwerk** [comment]
@OG-Jons I have a similar problem; when I create from the same repository but from two different branches two servers I also get:

```
Error response from daemon: driver failed programming external connectivity on endpoint clkkwyml0002tox9tj7qf0clq-api (3a59000b7cdb7836af5cfbbedd93c68ff3181017ba34c0f7b3cc0c293a84299b): Bind for 0.0.0.0:3004 failed: port is already allocated
```

Did you find a workaround for this?

**Comment by signalwerk** [comment]
OK. I was probably thinking it wrong. I took two time the same `docker-compose.yml` that looked like this:

```yaml
version: '3'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: production
    command: node dist/main
    ports:
      - 3004:3000
```
Now, when I deploy this two times on the same coolify instance, I get a problem. I thought if the port `3000` is defined in `Configuration → Stack` I thought it's overwriting this. Hm... OK. It's probably a me-problem, but now this lead to it that I have two different docker-compose-files; `docker-compose.coolify.yml` and `docker-compose.yml` because developers need the default-port definition.
