### ISSUE TITLE
[Bug]: Invalid Host header-URL routing

### ISSUE THREAD

**Issue by nidhin077** [coollabsio/coolify#1049]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

We deployed a node application and set up a domain, when we try to call the domain, we receive the error "Invalid Host header". Please have someone look at this problem and let me know the solution as soon as possible. Additionally, I would like to know if there are any options in coolify-traefik to add a custom header and Allow-OriginList. 

### Steps To Reproduce

Deploy a radar service and configure a URL for the same. I'm attaching the radar repo link.

https://github.com/thoughtworks/build-your-own-radar

### Version

3.12.30

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
