### ISSUE TITLE
middleware "auth@docker" does not exist

### ISSUE THREAD

**Issue by HarunKilic** [coollabsio/coolify#105]
After fresh installation i get this error: 
`middleware "auth@docker" does not exist`

I am on ubuntu 20.04, installed the command `/bin/bash -c "$(curl -fsSL https://get.coollabs.io/coolify/install.sh)"` as root. 
I see this error in the traefik dashboard.

**Comment by andrasbacsai** [comment]
Hey @HarunKilic ,

You tried out the first version of Coolify. I released the next one, which is completely rewritten.
Could you please try it with the new one as well?

The new one is not using Traefik anymore.

I'm closing this issue, but please reopen it if you encounter the same error.
