### ISSUE TITLE
git cloning of private github repo with git submodule fails during application build from github

### ISSUE THREAD

**Issue by kamit-transient** [coollabsio/coolify#1050]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

I create a **Git source** to build an Application with my private GitHub repo,  Coolify builds this project perfectly well when it is standalone i.e. when it does not have any git submodules but fails to build with git submodule. 

Here are the logs:

```````
[23:39:36.910] Cloning myuser/project_name:master...
[23:39:42.239] Command failed with exit code 1: git clone -q -b master https://x-access-token:<SENSITIVE_DATA_DELETED>@github.com/myuser/project_name.git --config core.sshCommand="ssh -p 22" /tmp/build-sources/myuser/project_name/clgpft8f600099grshrix3t0g/ && cd /tmp/build-sources/myuser/projectname/clgpft8f600099grshrix3t0g && git checkout && git submodule update --init --recursive && git lfs pull && cd ..
Submodule 'project_abc' (git@github.com:myuser/project_abc.git) registered for path 'project_abc'
Cloning into '/tmp/build-sources/myuser/project_name/clgpft8f600099grshrix3t0g/project_abc'...
Host key verification failed.

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
``

### Steps To Reproduce

* Add a Github Source to coolify
* create an Application from **private github repo with git submodules**
* It will throw the previously mentioned access error.

### Version

3.12.31

**Comment by themodernpk** [comment]
+1

**Comment by dcarr45** [comment]
+1

Anybody have a suggested workaround for this? Some way to apply the Github App access token to submodules?

**Comment by andrasbacsai** [comment]
Due to inactivity, I'm closing this issue. However, if the problem persists, please reopen the issue. Thanks!

**Comment by themodernpk** [comment]
@andrasbacsai this issue is still there, we can't deploy repos with sub-modules

**Comment by maurobender** [comment]
We are also facing the same issue. The deploy job is trying to checkout submodules and it's no able to do it. Is there any workaround for this?

**Comment by kingRayhan** [comment]
![image](https://github.com/coollabsio/coolify/assets/7611746/2d36581b-1ad8-4f32-b8d3-f96ef5508581)
