### ISSUE TITLE
[Bug]: Demo, database or disk is full.

### ISSUE THREAD

**Issue by CodeMeZone** [coollabsio/coolify#1051]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

Invalid `prisma.user.create()` invocation: Error occurred during query execution: ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(SqliteFailure(Error { code: DiskFull, extended_code: 13 }, Some("database or disk is full"))) })

### Steps To Reproduce

[Sign up.](https://demo.coolify.io/register)

### Version

?

**Comment by Maaaathis** [comment]
Since just now I could register again - seems fixed
