### ISSUE TITLE
[Feature]: Bun runtime

### ISSUE THREAD

**Issue by byawitz** [coollabsio/coolify#1054]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Adding [Bun](https://bun.sh/) as a Coolify base package.

Bun is a **real fast** JavaScript runtime.

 ###  📝 Developemnt 
I can chip in and create the Bun package.

### Why should this be worked on?

Bun advantages:
- Built-in [server](https://bun.sh/docs/api/http#start-a-server-bun-serve)
- Use typescript files - no need to transpile, it happens on the fly.
- Faster loading time.
- Blazing fast request processing.
- Binary lock file.

I've created a few projects with Bun, and the process - building, testing, and producing - was fast and efficient.

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
