### ISSUE TITLE
[Bug]: Updating from 3.12.30 to 3.12.31 via UI breaks

### ISSUE THREAD

**Issue by Lissy93** [coollabsio/coolify#1056]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

N/A

### Description

This evening I noticed a new update was available, but when trying to update via the UI I seem to have broken everything 😬

Looking at it a bit further, the POST request to `/api/v1/update` seems to return a 200 all good, but after that the container dies, so all other requests land a 502, with the web page showing a 404. There's nothing to see in the Docker logs (unless there's somewhere specific I should be looking?).

Had a moment of panic, that everything was broken, but thankfully restarting the Docker container brought everything back online again. But no way to update, as this happens every time I try.

<details>
<summary>Screenshot</summary>

I don't think there's anything useful here, but this was what I can see client-side.

![screenshot](https://i.ibb.co/R9k2Whx/Screenshot-from-2023-04-28-19-35-31.png)

</details>

Questions:
1. If I run the re-run the Coolify install process to install the latest version, will my existing apps and data remain in tact? (I've got about 15 apps running in Coolify, as well as another 20 or so in normal Docker containers, so I don't want to break anything).
2. How can I view the logs from Coolify, to diagnose what may have gone wrong?
3. This got me thinking, I'd really like to backup my Coolify config and all running apps, so that if Coolify breaks, I can safely restore - any advice on how best to do this efficiently?

Thanks in advance for any help, and if there's any more info that you need- let me know :)

### Steps To Reproduce

1. Logged in via WebUI
2. Observes notification for new update (bottom left)
3. Clicks the Update icon
  - At the point, nothing on the UI seemed to happen
  - A minute or so later, the page refreshes and lands a 502
4. Neither my Coolify admin panel, nor any of my apps deployed via Coolify are available, all are returning a 404
5. Restarting the Docker container manually, fixes things - but without the update

### Version

3.12.30

**Comment by Lissy93** [comment]
It would be a nice feature if upon clicking the Update button, a confirmation modal was shown before the update began -  maybe also including short a changelog of what's new in the next version.
(I'm worried I'm going to accidentality click that nice shiny Update button again, and break everything!)

**Comment by andrasbacsai** [comment]
Due to inactivity, I'm closing this issue. However, if the problem persists, please reopen the issue. Thanks!
