### ISSUE TITLE
[Bug]: Delete remote destinations if remote server is not reachable anymore.

### ISSUE THREAD

**Issue by ivangsm** [coollabsio/coolify#1058]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

I had some applications, DB's and services using a remote destination. I had a problem with the server provider so the server is not reachable anymore.

When I tried to delete the services, apps or db's associated with that remote destination I got an error and the deletion of destination also fails because it expects to remove all the related services first.

### Steps To Reproduce

1.- Try to delete any App, service, or DB
2.- Get an error message

### Version

3.12.31

**Comment by andrasbacsai** [comment]
I will add a force deletion button on the destination page, that will cleanup everything related to the destination inside Coolify.
