### ISSUE TITLE
[Bug]: Installation steps - no matching manifest for linux/arm/v7 in the manifest list entries

### ISSUE THREAD

**Issue by adcousin** [coollabsio/coolify#1059]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

I'm using a Raspberry Pi 3 with a fresh standard Debian distribution (Just flashed it with `Raspberry Pi Imager v1.7.3`)
![image](https://user-images.githubusercontent.com/72085355/235436534-a427bf9b-fc80-47ab-9f2e-09c930c4923a.png)
When I launch `install.sh` everything goes fine until we try to `docker pull`

When running the script, the error message is the following
```
Pulling Coolify latest image (3.12.31) from ghcr.io.
Cannot find any Coolify image. Please check your internet connection. Exiting.
./install.sh exited unexpectedly with status: 1
```

So I tried to `sudo docker pull ghcr.io/coollabsio/coolify:3.12.30`, but then I get
```
3.12.30: Pulling from coollabsio/coolify
no matching manifest for linux/arm/v7 in the manifest list entries
```

Is there some other versions I can try to install coolify on my Raspberry?

Thanks and keep up the work,
Regards

### Steps To Reproduce

For the first error message, run `sudo bash ./install.sh` on a fresh Debian distribution on a Raspberry Pi 3
For the second error message, run `sudo docker pull ghcr.io/coollabsio/coolify:3.12.30` or `3.12.31`

### Version

3.12.31

**Comment by codesalatdev** [comment]
Can you post the output of `uname -m`?

**Comment by adcousin** [comment]
Hi @codesalatdev and thanks for your answer, output is `armv7l`

**Comment by codesalatdev** [comment]
> Hi @codesalatdev and thanks for your answer, output is `armv7l`
> In addition, the model of the Pi is `Raspberry Pi 3 Model B Plus Rev 1.3`
> ![image](https://user-images.githubusercontent.com/72085355/235470454-d5c04e44-8e40-4e26-b2c3-992e71ea28be.png)
> 

You seem to have installed a 32-bit OS on your 64-bit Raspberry Pi. Coolify is not built for armv7l. A Raspberry Pi 3 is ARMv8 tho, which supports 64-bit (aarch64).

See https://www.raspberrypi.com/news/raspberry-pi-os-64-bit/

**Comment by adcousin** [comment]
Thanks and apologies for the false alert.
