### ISSUE TITLE
Be able to use any public repository and deploy it

### ISSUE THREAD

**Issue by andrasbacsai** [coollabsio/coolify#106]

**Comment by Hybes** [comment]
I'm having issues with re-deploying on commit with public repos, is this an expected feature? Or somethings that's broken and should be on it's own Issue?

**Comment by andrasbacsai** [comment]
It is available in v4.

I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
