### ISSUE TITLE
[Bug]: Automatic Deployment of docker compose Application fails to build with code changes

### ISSUE THREAD

**Issue by nathanielastudillo** [coollabsio/coolify#1060]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

I have a docker-compose application running. When I push a commit to my master branch, it triggers a new deployment, but that new deployment doesn't reflect the changes in the new commit. I would expect that automatic deployments would reflect code changes.

Did some [research](https://stackoverflow.com/questions/35231362/dockerfile-and-docker-compose-not-updating-with-new-instructions) and it seems that the issue is that docker compose needs to be passed the `--no-cache` flag to trigger a proper re-build with the updated code. 

Currently, it seems like the cached containers are just re-used on each commit hook instead of being re-built.

### Steps To Reproduce

1. Create Docker Compose application
2. Push change to master branch of application
3. Re-deployment occurs 
4. No code has changed in the re-deployed container

### Version

3.12.31

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
