### ISSUE TITLE
[Bug]: Persistent storage breaks when using restart

### ISSUE THREAD

**Issue by Icety** [coollabsio/coolify#1064]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you add persistent storage to your deployment, the way of starting the instance defines how the persistent storage is set up in Docker:
Completely stopping your instance and then pressing deploy results in a docker volume on the same path as the defined path in persistent storage. 
If you use the 'Restart' method, /app gets prepended before the volume target.

### Steps To Reproduce

1. Add a persistent storage on: /app/public
2. Start your instance and inspect your docker through ssh: `docker inspect dockerId`
3. Note that the Mounts contains your new volume with target = /app/public
![image](https://user-images.githubusercontent.com/2795818/236195438-f48732ca-39e7-4efd-9bee-420a2a2d9a34.png)

4. Press the restart button in Coolify
5. Reinspect the same docker instance, the target has now become /app/app/public
![image](https://user-images.githubusercontent.com/2795818/236195918-9e91cbfd-2a21-4a0f-85cb-c91d2a3f755b.png)

### Version

3.12.31

**Comment by andrasbacsai** [comment]
Oh, nice catch! Fixing in the next version!
