### ISSUE TITLE
[Feature]:  changing database ports

### ISSUE THREAD

**Issue by lyricsdev** [coollabsio/coolify#1065]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

make a possible change external port in database image's. to make it the same with Internal port. 3306 for local docker and 3306 for exaternal connection too for example. 

### Why should this be worked on?

.

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
