### ISSUE TITLE
[Bug]: The size of the overlay2 folder is growing rapidly

### ISSUE THREAD

**Issue by nidhin077** [coollabsio/coolify#1068]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

Hi,

On one of my servers, I installed Coolify, I then tried to deploy various applications, however when I checked the disc consumption, it was excessive upon more inspection, I discovered that overlay2  is consuming more space. It may have been as a result of coolify. So if you can, please examine and inform me of the solution. 

### Steps To Reproduce

Install the coolify and try to deploy some applications. Then verify the overlay2 size

### Version

v3.12.31

**Comment by ChronSyn** [comment]
The overlay2 folder is used by Docker to store the different layers of images. The growth of it isn't exclusively an issue with Coolify as it also happens with other solutions (e.g. Portainer, but even manually deploying images and containers via the CLI).

It's feasible that Coolify might not be cleaning up unused images, but you may want to consider pruning unused images and containers: `docker system prune --all`
(Details: https://docs.docker.com/engine/reference/commandline/system_prune/)

**Comment by andrasbacsai** [comment]
I will add a bit more aggressive cleanup on the docker images/caches in the next version. 

(In v4, these automations will be more precise and alert you in your preferred notification thing (email/discord/slack/telegram...) if something is not okay with your server.)
