### ISSUE TITLE
[Bug]: Getting blank screen on coolify home page  

### ISSUE THREAD

**Issue by nidhin077** [coollabsio/coolify#1069]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

Hi,

Using [auth2proxy](https://github.com/oauth2-proxy/oauth2-proxy), we attempted to implement 2FA authentication for coolify after deploying it on our server. We followed the identical procedure, and following authentication, we were taken to a login screen. Upon successful login, the page became blank. Could you kindly examine the same and inform me of anything that has to be changed on my end? 

![image](https://github.com/coollabsio/coolify/assets/107123789/39b8b102-0895-44b4-bf75-d857c935a457)

### Steps To Reproduce

Depoly coolify and add auth2proxy for authentication, then try to login .

### Version

v3.12.31

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
