### ISSUE TITLE
[Feature]: HTTP/1 and HTTP/2 not mutually exclusive

### ISSUE THREAD

**Issue by altafan** [coollabsio/coolify#1077]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

At the moment, if I enable HTTP/2 for a service, it's not possible to reach it on HTTP/1 anymore and vice-versa.

It would be nice if enabling HTTP/2 just added the possibility to reach the service also on HTTP/2 instead of replacing HTTP/1.

### Why should this be worked on?

This way, a service that makes use of a multiplexer and supports many protocols, like for example a grpc service using grpc-gateway could be reached both via HTTP/1 and HTTP/2.

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
