### ISSUE TITLE
[Feature]: Running in RAM

### ISSUE THREAD

**Issue by Kotov584** [coollabsio/coolify#1078]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

In current version of coolify there is no option to run deployed docker in RAM and just only in 

### Why should this be worked on?

Improves safety in case of server hack
If somebody gets access to your server you can simply shutdown server and app will be lost without possibility for recovery

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
