### ISSUE TITLE
[Feature]: Deploying app without GitHub

### ISSUE THREAD

**Issue by Kotov584** [coollabsio/coolify#1079]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Sometimes deploying small apps should be done without GitHub repository

### Why should this be worked on?

In some cases you don't want to spend time by uploading your small app on GitHub and just want simply to select zip file
For example I have bot written with Python and I don't want for it to create yet another repository

**Comment by andrasbacsai** [comment]
v4 supports this.

I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
