### ISSUE TITLE
Installer stalls after Github App creation

### ISSUE THREAD

**Issue by funkybunch** [coollabsio/coolify#108]
I'm able to successfully start the installer, get the web interface, create the Github app, and get redirected back to coolify at the domain I have it running on.  But upon getting redirected, it just hangs at an empty console.

I looked at this PHP script in the installer repo: https://github.com/coollabsio/coollabs-installers/blob/main/index.php

Line 197 in that file is the last one to be rendered in the HTML source which leads me to believe there is some error I'm hitting, but I can't find the PHP logs anywhere.  There is nothing out of the ordinary output to STD_OUT:
```bash
####################################
Installer started on http://:8080
####################################

[Tue Feb  8 04:59:01 2022] PHP 8.0.7 Development Server (http://0.0.0.0:8080) started
[Tue Feb  8 04:59:40 2022] 172.17.0.1:36274 Accepted
[Tue Feb  8 04:59:40 2022] PHP Warning:  Undefined array key "QUERY_STRING" in /usr/src/app/coollabs/index.php on line 3
[Tue Feb  8 04:59:40 2022] 172.17.0.1:36274 [200]: GET /
[Tue Feb  8 04:59:40 2022] 172.17.0.1:36274 Closing
[Tue Feb  8 05:08:44 2022] 172.17.0.1:36528 Accepted
200[Tue Feb  8 05:08:49 2022] 172.17.0.1:36528 [200]: GET /?code=[github_code]&state=[email]
[Tue Feb  8 05:08:49 2022] 172.17.0.1:36528 Closing
```

And then it just hangs here forever.  Looked at some of the other installation issues created in Github and it seems its worth noting that no other docker containers have been created at this point.

The webpage I'm redirected back to from github looks like this:
<img width="727" alt="Screen Shot 2022-02-08 at 12 31 00 AM" src="https://user-images.githubusercontent.com/6365836/152925105-b26f0064-861a-4468-bec5-48d990b4cca0.png">

**Comment by andrasbacsai** [comment]
Hey @funkybunch !

You tried out the first version of Coolify. I released the next one, which is completely rewritten.
Could you please try it with the new one as well?

I'm closing this issue, but please reopen it if you encounter the same error.

**Comment by funkybunch** [comment]
@andrasbacsai thanks for the update!  I saw you were working on one but wasn't sure when it was coming out.

Installation went smoothly for the most part - would be helpful to have the option to configure the web port manually as part of installation.

**Comment by funkybunch** [comment]
See #120
