### ISSUE TITLE
[Bug]: Host Header not set correctly for Next.js 13 Route Handlers

### ISSUE THREAD

**Issue by cstrnt** [coollabsio/coolify#1080]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

https://github.com/cstrnt/coolify-host

### Description

Next.js 13 introduces the App directory. One feature includes route handlers which use the `Request` and `Response` APIs. For some reason the `Host` header is set to `localhost` when deploying the app to coolify. It works fine on Vercel

### Steps To Reproduce

1. Go to `https://demo.ngtly.com` or start locally with a different hostname
2. Click the link on the page or navigate to `https://demo.ngtly.com/test` or use cURL

The app redirects to `localhost:3000`
![Screenshot 2023-05-24 at 18 55 44](https://github.com/coollabsio/coolify/assets/20679094/e3dd3a69-6c77-48e4-996f-13f45fadcb36)

### Version

latest

**Comment by cstrnt** [comment]
Found a similar issue here: https://github.com/vercel/next.js/issues/37536

**Comment by andrasbacsai** [comment]
Due to inactivity, I'm closing this issue. However, if the problem persists, please reopen the issue. Thanks!
