### ISSUE TITLE
[Bug]: Account becomes unusable if default team is deleted.

### ISSUE THREAD

**Issue by VandrerenErik** [coollabsio/coolify#1085]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

In versions 3.12.30 and up a user who's initial Team was deleted but is still part of another team becomes unusable and the only way to restore functionality is to delete the user and register it again. We attempted to create other Teams and switch to them but nothing happens, the user account is is pretty much unusable until you recreate it.

![image](https://github.com/coollabsio/coolify/assets/54407345/43f54578-19f1-4339-968e-dbfb78d02570)

![image](https://github.com/coollabsio/coolify/assets/54407345/822c3e2b-c9f1-4641-a124-236591c6b375)

### Steps To Reproduce

Invite an user to another Team and then delete its original Team.

### Version

3.12.30^

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
