### ISSUE TITLE
[Bug]: 11ty wrong content-type

### ISSUE THREAD

**Issue by agdolla** [coollabsio/coolify#1088]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I created a 11ty project hosted on github, coolify recognizes it correctly and deploys it without any errors.
When I open the page with a browser I receive an error on the console that the server sent the wrong content-type application/octet-stream instead of application/javascript. The javascript file has the extension .mjs

<img width="1429" alt="Screenshot 2023-05-29 at 11 29 50" src="https://github.com/coollabsio/coolify/assets/1113987/28f9aae6-3340-42ef-870e-d55cfac21aa7">

<img width="715" alt="Screenshot 2023-05-29 at 11 30 23" src="https://github.com/coollabsio/coolify/assets/1113987/30e7da4c-59f5-4cff-a9af-2f4177c4ddd1">

### Steps To Reproduce

1. deploy 11ty project with a javascript file with extension .mjs
2. open the page with console

### Version

3.12.32

**Comment by andrasbacsai** [comment]
Due to inactivity, I'm closing this issue. However, if the problem persists, please reopen the issue. Thanks!
