### ISSUE TITLE
[Bug]: nextjs app cannot be deployed if pnpm-lock.yarn was created with pnpm@8

### ISSUE THREAD

**Issue by agdolla** [coollabsio/coolify#1090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

deploying nextjs app worked great, but after upgrading pnpm to 8.x.x on the dev environment deployment fails as coolify builds the docker image with pnpm@6

### Steps To Reproduce

1. upgrade pnpm to 8.x.x
2. deploment fails

### Version

3.12.32

**Comment by agdolla** [comment]
@hacknug  I use pnpm@7 and deployment works fine

**Comment by andrasbacsai** [comment]
Due to inactivity, I'm closing this issue. However, if the problem persists, please reopen the issue. Thanks!
