### ISSUE TITLE
[Feature]: Use --init in docker run

### ISSUE THREAD

**Issue by annihilatorrrr** [coollabsio/coolify#1091]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

This will ensure that there won't be a zombie process being created ?

### Why should this be worked on?

To avoid creating zombie process ?

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
