### ISSUE TITLE
[Feature]: SSH into the host or the containers from inside the UI

### ISSUE THREAD

**Issue by aghasemi** [coollabsio/coolify#1093]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

A new button/section in the Coolify Dashboard UI to allow to open a terminal into any of the deployed containers and/or the host running Coolify. 

### Why should this be worked on?

Because it will make debugging, troubleshooting issues, and monitoring a lot easier, as these can be done from the same interface, rather than opening a separate terminal in the workstation and keeping creds etc...

**Comment by unownone** [comment]
This is a really cool idea! I would love to work on this! Can anyone assign this issue to me?

**Comment by andrasbacsai** [comment]
This will be added to v4.

I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.

**Comment by aghasemi** [comment]
Thanks. Is it now possible to "migrate" a current v3 instance to v4?
