### ISSUE TITLE
[Bug]: Application Logs do not work

### ISSUE THREAD

**Issue by ecreatures** [coollabsio/coolify#1094]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

When I go to dashboard select an application and look to display the logs I have 2 choices : Following Logs and Streaming logs.
None of the 2 buttons do display any data
<img width="702" alt="Capture d’écran 2023-06-07 à 13 25 49" src="https://github.com/coollabsio/coolify/assets/216368/35b4f7a2-af94-4919-b850-1bb42d1d3650">

### Steps To Reproduce

Go to Dashboard
Click on running application
Click on Application under the Logs label

### Version

3.12.32

**Comment by andrasbacsai** [comment]
Due to inactivity, I'm closing this issue. However, if the problem persists, please reopen the issue. Thanks!
