### ISSUE TITLE
[Bug]: Disabling Alert in a browser Breaks functionality

### ISSUE THREAD

**Issue by unownone** [coollabsio/coolify#1098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

After doing actions that cause a Dialog Popup `do you want to do 'x' ?` If one checks the box that says "prevent the website from causing the popups again", this will end up breaking Dialogs and deleting and any other function that requires confirmation as no popup will be raised and it will be evaluated as false :[stackoverflow issue link](https://stackoverflow.com/questions/20078692/if-dialog-opens-in-one-browser-tab-prevent-it-from-opening-in-another).

# Solution:
Create a new Dialog Modal which is modern and responsive.

### Steps To Reproduce

1. Delete a service.
2. Delete again till the `prevent website from causing this popup again` checkbox under the dialog comes up.
3. Select it.
4. Try again deleting a service.

### Version

3.12.32

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
