### ISSUE TITLE
[Bug]: Coolify Proxy is messed up if you restart Coolify

### ISSUE THREAD

**Issue by unownone** [coollabsio/coolify#1099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

For whatever reason whenever you try to restart coolify the coolify instance either detaches from the proxy or just doesn't work properly anymore. It ends up throwing error:

`Coolify Proxy Error`
<img width="1019" alt="image" src="https://github.com/coollabsio/coolify/assets/38348296/abb4a953-1483-4cdc-8a29-a53f7486f388">

PS : I am on ARM ( ORACLE ARM SERVER )

### Steps To Reproduce

1. Go to settings, Restart Coolify
2. Coolify no more reachable through defined FQDN

### Version

3.12.32

**Comment by Eventyret** [comment]
Can confirm this is mostly the only thing holding me back from using it and moving from dokku.
It seems that the container stops and never starts again and or gets removed `coolify-proxy`

**Comment by andrasbacsai** [comment]
This is mostly because of the [Live Restore](https://docs.docker.com/config/containers/live-restore) functionality.

You can disable it manually in `/etc/docker/daemon.json` and restart Docker Engine (it could interrupt your currently running containers!)
