### ISSUE TITLE
[Bug]: SFTP does not work

### ISSUE THREAD

**Issue by wp-coin** [coollabsio/coolify#1100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

when I switch on SFTP I cannot connect to add files with the given uri, user and password with port number 9000

<img width="515" alt="Screenshot 2023-06-08 231258" src="https://github.com/coollabsio/coolify/assets/35810228/3a935b16-05fc-4448-9f05-7e98e8def740">

### Steps To Reproduce

1. login
2. go to ruining service WordPress
3. under configuration, switch on sftp

### Version

v3.12.32

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
