### ISSUE TITLE
[Feature]: service console

### ISSUE THREAD

**Issue by gladson** [coollabsio/coolify#1101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

You could add the access service to the containers console.

### Why should this be worked on?

type shell or bash...

For extra settings like customizations.

**Comment by caf-3** [comment]
There are situations where in fact, we need to access the console. For example, yesterday I needed to increase the file upload size in WordPress, I had to enter my server's terminal and run some docker commands to be able to get the desired result. But being the owner, why don't you run the commands directly from the server?

**Comment by gladson** [comment]
@caf-3 
It's true, you're right... 
But there could be a simpler way to access via the project's administrative panel, facilitating access to containers.

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
