### ISSUE TITLE
[Bug]: Error webhooks in gitlab

### ISSUE THREAD

**Issue by edgardoll4** [coollabsio/coolify#1102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

I have a problem with the implementation of a gitlab repository in coolify, the project is up and everything, but before when I made a commit to the branch that is deployed it is in coolify it autodeployed automatically, but now I don't want to do it.

I tried the URL and the result that it gives me, I tried it with two different gitlab accounts and it gives me the same error

example: https://panel.dominio.xyz./webhooks/gitlab

{
"status": 500,
"message": "Cannot read properties of null (reading 'appId')"
}

In gitlab I search the repository and go to the webhooks and I get the following:

![image](https://github.com/coollabsio/coolify/assets/32710186/686de95d-5d9d-4dfd-abe3-bd4b53e96a7b)

When I do the test from gitlab I get the following error

![image](https://github.com/coollabsio/coolify/assets/32710186/52a7e8f8-33ef-409d-a38d-e47f08578b84)

### Steps To Reproduce

In gitlab I search the repository and go to the webhooks and I get the following:

![image](https://github.com/coollabsio/coolify/assets/32710186/686de95d-5d9d-4dfd-abe3-bd4b53e96a7b)

When I do the test from gitlab I get the following error

![image](https://github.com/coollabsio/coolify/assets/32710186/52a7e8f8-33ef-409d-a38d-e47f08578b84)

### Version

3.12.32

**Comment by andrasbacsai** [comment]
Due to inactivity, I'm closing this issue. However, if the problem persists, please reopen the issue. Thanks!
