### ISSUE TITLE
[Bug] Server reboot causes conflicts V3

### ISSUE THREAD

**Issue by ikbenignace** [coollabsio/coolify#1111]
I have Running multiple instances, like a postgres db and a Nestjs backend, but for testing.

As result, none of the active services are online. I had to manually start the postgres db, also every other instance gives an application error with status degraded. Which is not good in production

**Comment by andrasbacsai** [comment]
This should not happen. Are there any error logs in those containers?

**Comment by andrasbacsai** [comment]
Due to inactivity, I'm closing this issue. However, if the problem persists, please reopen the issue. Thanks!
