### ISSUE TITLE
[Bug] Docker not found on ARM

### ISSUE THREAD

**Issue by ikbenignace** [coollabsio/coolify#1112]
I'm getting this message for the coolify image: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

**Comment by andrasbacsai** [comment]
This is for v4, right?

**Comment by ikbenignace** [comment]
Yep

**Comment by xoose** [comment]
i have the same problem 

`Container coolify  Creating
 coolify The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 Container coolify  Created
`

**Comment by Tytan-Codes** [comment]
You may have installed docker the wrong way. 

Run:

```
sudo snap remove docker # or docker.io
sudo apt update
sudo apt install docker.io -y
```

That might fix it.

**Comment by xoose** [comment]
The problem is the Image not docker 

- I use arm64

The Image map is wrong

**Comment by andrasbacsai** [comment]
It is available now!
