### ISSUE TITLE
Shows Bad Gateway

### ISSUE THREAD

**Issue by oc7opu5** [coollabsio/coolify#1113]
I am trying to deploy Typebot in Coolify. The issue I am facing is, it always shows me 'bad gatway' although the containers are running and showing healthy.

I have used the github link method and when asked choose docker compose as it showed as recommended.

Can someone help?

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
