### ISSUE TITLE
Serve both HTTP and HTTPS for the same application

### ISSUE THREAD

**Issue by RoeeJ** [coollabsio/coolify#1117]
Hi there!
I've been using coolify for a while now and the only issue I found with it so far is the ability to have an  application accept both HTTP and HTTPS connections
If I enable HTTPS (by specifying it in the FQDN field) I get 302 redirects on the HTTP endpoint
If I do not enable HTTPS I can connect to the application via HTTP but I get a 404 response from Traefik on the HTTPS endpoint
This should be as simple as having both endpoints listed for the traefik router definition, is there a way to manually change it from the UI or would this require a PR with the relevant code changes?

**Comment by RoeeJ** [comment]
I tend to disagree since changing the behavior would require code changes, I'm just wondering if it's in the "works as intended, will not fix" category or not

**Comment by andrasbacsai** [comment]
What could be the use case for this feature? I never used both for an application.

**Comment by RoeeJ** [comment]
One of our internal API servers acts both as a GraphQL server (served over HTTPS for a web frontend) and a configuration service consumed by VOIP products that only support HTTP

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
