### ISSUE TITLE
[FEATURE] Add Supabase postgres

### ISSUE THREAD

**Issue by miguelgargallo** [coollabsio/coolify#1118]
Add supabase postgres, it would be an amazing implementation as service, i am trying to deploy as an application, and it seems to be a quiet difficult/non success

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
