### ISSUE TITLE
Keycloak custom realm Frontend URL is not accessible

### ISSUE THREAD

**Issue by jenishngl** [coollabsio/coolify#1120]
I tried setting up a different subdomain for a realm i created. But seems the mappings are not proper. Maybe will raise this issue under keycloak as well. Someone might need to check this

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
