### ISSUE TITLE
Error on update

### ISSUE THREAD

**Issue by jcmaciel** [coollabsio/coolify#1122]
Hi everybody!
I have been faced to an issue about upgrade my coolify (3.12.4) to latest version.
When I try to auto update, this issue happen:
<img width="696" alt="image" src="https://github.com/coollabsio/coolify/assets/81674/b8f779b8-5ee6-4fda-9158-cfbd09a50bb1">

and, I'm trying to use the command:
wget -q https://cdn.coollabs.io/coolify/upgrade.sh \ -O upgrade.sh; sudo bash ./upgrade.sh

but without success :(
<img width="1031" alt="image" src="https://github.com/coollabsio/coolify/assets/81674/f676bb60-5cf5-48c0-a1e5-229ab09776b2">

any idea to solve that?

**Comment by andrasbacsai** [comment]
v3.12.32 is now synced to Dockerhub.

Btw, that upgrade script is for v4 beta, not for v3. :)

**Comment by jcmaciel** [comment]
Thank you @andrasbacsai
