### ISSUE TITLE
v2 on arm64

### ISSUE THREAD

**Issue by nawkht** [coollabsio/coolify#113]
Hi, I heard that the v2 will work on arm64 but the container has this error:
`standard_init_linux.go:228: exec user process caused: exec format error`

https://prnt.sc/26tgyd1

**Comment by nabeelshaikh7** [comment]
when i try to build the image for arm64 it gives me this error 
`#15 64.77 warning Error running install script for optional dependency: "/app/node_modules/cpu-features: Command failed.
#15 64.77 Exit code: 1
#15 64.77 Command: node-gyp rebuild
#15 64.77 Arguments: 
#15 64.77 Directory: /app/node_modules/cpu-features
#15 64.77 Output:
#15 64.77 gyp info it worked if it ends with ok
#15 64.77 gyp info using node-gyp@8.4.1
#15 64.77 gyp info using node@16.14.0 | linux | arm64
#15 64.77 gyp ERR! find Python 
#15 64.77 gyp ERR! find Python Python is not set from command line or npm configuration
#15 64.77 gyp ERR! find Python Python is not set from environment variable PYTHON
#15 64.77 gyp ERR! find Python checking if \"python3\" can be used
#15 64.77 gyp ERR! find Python - \"python3\" is not in PATH or produced an error
#15 64.77 gyp ERR! find Python checking if \"python\" can be used
#15 64.77 gyp ERR! find Python - \"python\" is not in PATH or produced an error
#15 64.77 gyp ERR! find Python 
#15 64.77 gyp ERR! find Python **********************************************************
#15 64.77 gyp ERR! find Python You need to install the latest version of Python.
#15 64.77 gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
#15 64.77 gyp ERR! find Python you can try one of the following options:
#15 64.77 gyp ERR! find Python - Use the switch --python=\"/path/to/pythonexecutable\"
#15 64.77 gyp ERR! find Python   (accepted by both node-gyp and npm)
#15 64.77 gyp ERR! find Python - Set the environment variable PYTHON
#15 64.77 gyp ERR! find Python - Set the npm configuration variable python:
#15 64.77 gyp ERR! find Python   npm config set python \"/path/to/pythonexecutable\"
#15 64.77 gyp ERR! find Python For more information consult the documentation at:
#15 64.77 gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
#15 64.77 gyp ERR! find Python **********************************************************
#15 64.77 gyp ERR! find Python 
#15 64.77 gyp ERR! configure error 
#15 64.77 gyp ERR! stack Error: Could not find any Python installation to use
#15 64.77 gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
#15 64.77 gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
#15 64.77 gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
#15 64.77 gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
#15 64.77 gyp ERR! stack     at exithandler (node:child_process:406:5)
#15 64.77 gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:418:5)
#15 64.77 gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
#15 64.77 gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
#15 64.77 gyp ERR! stack     at onErrorNT (node:internal/child_process:478:16)
#15 64.77 gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
#15 64.77 gyp ERR! System Linux 5.10.0-11-arm64
#15 64.77 gyp ERR! command \"/usr/local/bin/node\" \"/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
#15 64.77 gyp ERR! cwd /app/node_modules/cpu-features
#15 64.77 gyp ERR! node -v v16.14.0
#15 64.77 gyp ERR! node-gyp -v v8.4.1
#15 64.77 gyp ERR! not ok"
#15 64.77 info This module is OPTIONAL, you can safely ignore this error
#15 65.46 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
#15 65.46 error /app/node_modules/bcrypt: Command failed.
#15 65.46 Exit code: 1
#15 65.46 Command: node-pre-gyp install --fallback-to-build
#15 65.46 Arguments: 
#15 65.46 Directory: /app/node_modules/bcrypt
#15 65.46 Output:
#15 65.46 node-pre-gyp info it worked if it ends with ok
#15 65.46 node-pre-gyp info using node-pre-gyp@1.0.8
#15 65.46 node-pre-gyp info using node@16.14.0 | linux | arm64
#15 65.46 node-pre-gyp info check checked for "/app/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" (not found)
#15 65.46 node-pre-gyp http GET https://github.com/kelektiv/node.bcrypt.js/releases/download/v5.0.1/bcrypt_lib-v5.0.1-napi-v3-linux-arm64-musl.tar.gz
#15 65.46 node-pre-gyp ERR! install response status 404 Not Found on https://github.com/kelektiv/node.bcrypt.js/releases/download/v5.0.1/bcrypt_lib-v5.0.1-napi-v3-linux-arm64-musl.tar.gz 
#15 65.46 node-pre-gyp WARN Pre-built binaries not installable for bcrypt@5.0.1 and node@16.14.0 (node-v93 ABI, musl) (falling back to source compile with node-gyp) 
#15 65.46 node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/kelektiv/node.bcrypt.js/releases/download/v5.0.1/bcrypt_lib-v5.0.1-napi-v3-linux-arm64-musl.tar.gz 
#15 65.46 gyp info it worked if it ends with ok
#15 65.46 gyp info using node-gyp@8.4.1
#15 65.46 gyp info using node@16.14.0 | linux | arm64
#15 65.46 gyp info ok 
#15 65.46 gyp info it worked if it ends with ok
#15 65.46 gyp info using node-gyp@8.4.1
#15 65.46 gyp info using node@16.14.0 | linux | arm64
#15 65.46 gyp ERR! find Python 
#15 65.46 gyp ERR! find Python Python is not set from command line or npm configuration
#15 65.46 gyp ERR! find Python Python is not set from environment variable PYTHON
#15 65.46 gyp ERR! find Python checking if "python3" can be used
#15 65.46 gyp ERR! find Python - "python3" is not in PATH or produced an error
#15 65.46 gyp ERR! find Python checking if "python" can be used
#15 65.46 gyp ERR! find Python - "python" is not in PATH or produced an error
#15 65.46 gyp ERR! find Python 
#15 65.46 gyp ERR! find Python **********************************************************
#15 65.46 gyp ERR! find Python You need to install the latest version of Python.
#15 65.46 gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
#15 65.46 gyp ERR! find Python you can try one of the following options:
#15 65.46 gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
#15 65.46 gyp ERR! find Python   (accepted by both node-gyp and npm)
#15 65.46 gyp ERR! find Python - Set the environment variable PYTHON
#15 65.46 gyp ERR! find Python - Set the npm configuration variable python:
#15 65.46 gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
#15 65.46 gyp ERR! find Python For more information consult the documentation at:
#15 65.46 gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
#15 65.46 gyp ERR! find Python **********************************************************
#15 65.46 gyp ERR! find Python 
#15 65.46 gyp ERR! configure error 
#15 65.46 gyp ERR! stack Error: Could not find any Python installation to use
#15 65.46 gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
#15 65.46 gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
#15 65.46 gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
#15 65.46 gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
#15 65.46 gyp ERR! stack     at exithandler (node:child_process:406:5)
#15 65.46 gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:418:5)
#15 65.46 gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
#15 65.46 gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
#15 65.46 gyp ERR! stack     at onErrorNT (node:internal/child_process:478:16)
#15 65.46 gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
#15 65.46 gyp ERR! System Linux 5.10.0-11-arm64
#15 65.46 gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/app/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/app/node_modules/bcrypt/lib/binding/napi-v3" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
#15 65.46 gyp ERR! cwd /app/node_modules/bcrypt
#15 65.46 gyp ERR! node -v v16.14.0
#15 65.46 gyp ERR! node-gyp -v v8.4.1
#15 65.46 gyp ERR! not ok 
#15 65.46 node-pre-gyp ERR! build error 
#15 65.46 node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/app/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/app/node_modules/bcrypt/lib/binding/napi-v3 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
#15 65.46 node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/app/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
#15 65.46 node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
#15 65.46 node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
#15 65.46 node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
#15 65.46 node-pre-gyp ERR! System Linux 5.10.0-11-arm64
#15 65.46 node-pre-gyp ERR! command "/usr/local/bin/node" "/app/node_modules/bcrypt/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
#15 65.46 node-pre-gyp ERR! cwd /app/node_modules/bcrypt
#15 65.46 node-pre-gyp ERR! node -v v16.14.0
#15 65.46 node-pre-gyp ERR! node-pre-gyp -v v1.0.8
#15 65.46 node-pre-gyp ERR! not ok 
#15 65.46 Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/app/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/app/node_modules/bcrypt/lib/binding/napi-v3 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
------
executor failed running [/bin/sh -c yarn install]: exit code: 1`

**Comment by andrasbacsai** [comment]
ARM support is in beta. You can try it out! :)
