### ISSUE TITLE
Hability to add custom apps

### ISSUE THREAD

**Issue by miguelgargallo** [coollabsio/coolify#1131]
Hability to add custom apps

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.

**Comment by miguelgargallo** [comment]
Now on my Dockers I will try it! <3, I will send you feedback
