### ISSUE TITLE
Add SurrealDB with .env and hability to use another user, not "root" as root

### ISSUE THREAD

**Issue by miguelgargallo** [coollabsio/coolify#1132]
Add SurrealDB with .env and hability to use another user, not "root" as root

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
