### ISSUE TITLE
Expose multiple ports from a docker container

### ISSUE THREAD

**Issue by andersondn** [coollabsio/coolify#1146]
Hi

I'd like to know if its possible to expose multiple ports from a container? i'm using the v3 version

**Comment by Saboor-Hakimi-23** [comment]
Hi, I'm looking for the same thing, did you manged to find a solution for it?

**Comment by Geczy** [comment]
also looking for this, looks like it's not possible right now...

**Comment by andrasbacsai** [comment]
It is available only in v4.

I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
