### ISSUE TITLE
[SOLVED] - v3.12.34 has a bug - Can't build because of "secretOrPrivateKey must be an asymmetric key when using RS256" error

### ISSUE THREAD

**Issue by RicardoNeves** [coollabsio/coolify#1148]
So yesterday I ran coolify update to version 3.12.33 and during the update my network had some issues and failed. Everything seemed to be fine  except the logs of a deploy I was running that showed up some garbage.

Today I tried to run a deploy but I always get a message saying "**secretOrPrivateKey must be an asymmetric key when using RS256**" in the first 2 seconds of any service deploy.

I tried to change the prod.db file I found in /var/lib/docker/volumes/coolify-db/_data/prod.db to a later version I found in the same folder but didn't work.

I also tried to rollback to v3.12.32(I'm currently at 3.12.33) but I still get the same message when deploying.

Some guidance would be appreciated.

Thank you.

**Comment by andrasbacsai** [comment]
Hey, this is known issue. You need to follow this [guide](https://docs.coollabs.io/coolify-v3/rollsecretkey#rollback-to-old-secret-key) to rollback the database and the secret key.

If you need assistance, you can [contact me](https://docs.coollabs.io/contact).

**Comment by MaxMorais** [comment]
Hi @andrasbacsai, I'm having exact same issue, but when I try to rollback to v3.12.32, I'm getting the message 

```
Command failed with exit code 1: docker pull coollabsio/coolify:v3.12.32 Error response from daemon: manifest for coollabsio/coolify:v3.12.32 not found: manifest unknown: manifest unknown
```

**Comment by andrasbacsai** [comment]
> Hi @andrasbacsai, I'm having exact same issue, but when I try to rollback to v3.12.32, I'm getting the message
> 
> ```
> Command failed with exit code 1: docker pull coollabsio/coolify:v3.12.32 Error response from daemon: manifest for coollabsio/coolify:v3.12.32 not found: manifest unknown: manifest unknown
> ```

You need to go to v3.12.33, but I will check why 3.12.32 is not found.

**Comment by MaxMorais** [comment]
@andrasbacsai even after follow all steps, the issue persist

![image](https://github.com/coollabsio/coolify/assets/1288676/7cd8553c-8f4a-4418-8e04-426b44c3e736)

**Comment by ThallesP** [comment]
@andrasbacsai hi, is this problem related to this issue? my password databases (not newer ones) is this weird text:
![image](https://github.com/coollabsio/coolify/assets/76017384/d78ac784-c4ae-4b69-84ec-36c30518ed8e)

**Comment by andrasbacsai** [comment]
> @andrasbacsai hi, is this problem related to this issue? my password databases (not newer ones) is this weird text:
> 
> ![image](https://github.com/coollabsio/coolify/assets/76017384/d78ac784-c4ae-4b69-84ec-36c30518ed8e)
> 
> 

Yes. Please follow the guide linked above, or contact me, if you need help! 🙂

**Comment by nwesterlaken** [comment]
On 18 July I upgraded to 3.12.34 and due to issues I rolled back to 3.12.33. Everything was running alright, until I saw the error as described above when starting a new application and decided to upgrade to 3.12.36 today. Now all domains for applications and services respond with a 'bad gateway', even the web instance of Coolify. I can only log in the webUI through http on the server IP. I tried a roll back to old secret key, but this did not change anything. What could have happened and how to solve this?

**Comment by andrasbacsai** [comment]
> On 18 July I upgraded to 3.12.34 and due to issues I rolled back to 3.12.33. Everything was running alright, until I saw the error as described above when starting a new application and decided to upgrade to 3.12.36 today. Now all domains for applications and services respond with a 'bad gateway', even the web instance of Coolify. I can only log in the webUI through http on the server IP. I tried a roll back to old secret key, but this did not change anything. What could have happened and how to solve this?

I replied to your mail.

**Comment by nwesterlaken** [comment]
Have not been able to solve, since I missed my original db. So I made a backup of all containers' _data directories and have reinstalled Coolify. Rebuilding was relatively quick with the backups. I hope that future versions will make backing up even better. Thanks for your efforts, Andras.
