### ISSUE TITLE
Consider disabling the forwarding of real ip headers from the client

### ISSUE THREAD

**Issue by ThallesP** [coollabsio/coolify#1150]
Currently, Coolify's Traefik forwards the following headers:

Forwarded, X-Forwarded, X-Forwarded-*, such as X-Forwarded-For, X-Forwarded-Proto, X-Forwarded-Host, and X-Forwarded-Port.

allowing the client to pass one of that headers could lead to a security issue in the application, take an example [keycloak](https://www.keycloak.org/server/reverseproxy#_configure_the_reverse_proxy).

This will cause a breaking change, so maybe an option to activate it would be nice.

I would be interested in making a PR.

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
