### ISSUE TITLE
secretOrPrivateKey must be an asymmetric key when using RS256 error on every app

### ISSUE THREAD

**Issue by whitesidest** [coollabsio/coolify#1152]
After a surprise reboot of the server the error "secretOrPrivateKey must be an asymmetric key when using RS256" for every app build.

**Comment by NeoLee-0435748** [comment]
I have exact same issue.
All secret are broken and if someone does not have a backup for that, it may be nightmare.

**Comment by andrasbacsai** [comment]
Did you check this [issue](https://github.com/coollabsio/coolify/issues/1148)?

**Comment by whitesidest** [comment]
Thank you.  I somehow missed that.  I will give those instructions a try.

**Comment by whitesidest** [comment]
It worked!!  Thank you very much.
