### ISSUE TITLE
root@host.docker.internal Permission denied

### ISSUE THREAD

**Issue by zewas-digital** [coollabsio/coolify#1153]
I just freshly installed Coolify on our server. The installation script finished without errors and everything is up and running. But somehow Coolify can't connect to the docker host. If I push on Validate Server in the UI the error message "Server is not reachable. Reason: root@host.docker.internal Permission denied (publickey, password)" is shown.

I checked if the Coolify public key is in the authorized_keys file on the host and it is there, so why doesn't it work?

I am using Coolify v4.0.0-beta.18

**Comment by zewas-digital** [comment]
Fixed it by deleting the public key in the authorized_keys file and reinstalling Coolify

**Comment by liamdebellada** [comment]
For anyone else coming here in the future.

You should not have to reinstall Coolify. You can retrieve the public key for `localhost` under "Keys & Tokens". Just place that public key into the unreachable server's `~/.ssh/authorized_keys`.

I did this via ssh, however it should be possible to append the public key via the "Command Center" as well.
