### ISSUE TITLE
[Bug] New applications get the wrong Git Source v3

### ISSUE THREAD

**Issue by ivangsm** [coollabsio/coolify#1155]
After updating to version v3.12.33, all the applications continued to work, but the new commits didn’t update them anymore. To fix this, I took out the projects and Git Sources and added them again.

After adding the Git Sources again, I was able to add applications, but if I added more than one git source in GitHub, it always took the repos from the latest source added, regardless of which one I chose.

I tried rollback Coolify to version v3.12.32, but now I cannot add any git source or application.

**Comment by andrasbacsai** [comment]
It is probably related to [this](https://github.com/coollabsio/coolify/issues/1148).

Due to inactivity, I'm closing this issue. However, if the problem persists, please reopen the issue. Thanks!
