### ISSUE TITLE
BUG: Pyrogram userbot httpcore issue

### ISSUE THREAD

**Issue by billouetaudrey** [coollabsio/coolify#1159]
Hi,

I deploy an userbot, work fine if I deploy direcly with docker, but error when using coolify

Any idea ?

Screenshot :
https://ibb.co/VwJN0cw

Thanks

**Comment by billouetaudrey** [comment]
Or there

https://nekobin.com/qoyavejuke

**Comment by annihilatorrrr** [comment]
This isn't a coolify issue, it's your code issue with the dependencies.
Some dependencies got updated prolly.

**Comment by billouetaudrey** [comment]
> This isn't a coolify issue, it's your code issue with the dependencies. Some dependencies got updated prolly.

I think it is because no issue when using it directly with docker
Docker and Greenify are in same server

I ask for a friend ;) My own userbot are on my docker directly 

Sorry for my bad english

**Comment by annihilatorrrr** [comment]
U got it all wrong.

**Comment by billouetaudrey** [comment]
it was dnspython package issue

Fixed :)
