### ISSUE TITLE
BUG: New Version available all time

### ISSUE THREAD

**Issue by miguelgargallo** [coollabsio/coolify#1160]
Always is visible
![image](https://github.com/coollabsio/coolify/assets/5947268/b7f83f80-6a46-4756-8b2f-ac09bd827f67)

Then appears the message
![image](https://github.com/coollabsio/coolify/assets/5947268/95856389-5200-4612-b29e-e9fe4a523711)

Finally the infinit Heart
![image](https://github.com/coollabsio/coolify/assets/5947268/6a1518bb-4693-4b32-9234-39bdbf3e0153)

At the bottom says last version (check manually, i went to see it, yes.)
![image](https://github.com/coollabsio/coolify/assets/5947268/c4817cd2-3140-465b-8764-d579540d67b4)

**Comment by andrasbacsai** [comment]
This was a temporary problem.
