### ISSUE TITLE
new: problem deploying dockers

### ISSUE THREAD

**Issue by miguelgargallo** [coollabsio/coolify#1162]
I am having trouble by deploying dockers, in this case coolify/pocketbase

![image](https://github.com/coollabsio/coolify/assets/5947268/3489f990-34d4-464c-8148-9ec04a15acb5)

**Comment by codesalatdev** [comment]
@miguelgargallo v4 does not support Docker and Compose yet. They're greyed out bc it's hardcoded this way: https://github.com/coollabsio/coolify/blob/1de2c222b4611a7b9ee331f1a71f0fc8511bad94/resources/views/livewire/project/application/general.blade.php#L30

**Comment by miguelgargallo** [comment]
Thanks to know @codesalatdev!
