### ISSUE TITLE
how to update umami to version 2

### ISSUE THREAD

**Issue by jankohlbach** [coollabsio/coolify#1165]
I have umami running on version 1, but I would really like to be able to update this in some way, and best would be if coolify can provide a solution for that.
Don't like to do this manually in the container.

**Comment by jankohlbach** [comment]
using coolify version 3 btw

**Comment by andrasbacsai** [comment]
Updated the service template of Umami, so version 2 is supported. The migration should be done manually unfortunately, following [this](https://umami.is/docs/migrate-v1-v2) guide.
