### ISSUE TITLE
Getting 500 error when accessing running services

### ISSUE THREAD

**Issue by mprajescu** [coollabsio/coolify#1166]
I am getting a 500 error when I try to access running services. The ones that are stopped can be accessed and managed. 

![image](https://github.com/coollabsio/coolify/assets/18659386/880b02bd-d35b-461c-b5f2-4ddd81fe2cbd)

Steps to replicate:

1) go to dashboard 
2) click on the Service that is running 

I did try to restart the coolify server instance and the issue is persistent. 
Automatic update is turned on. 
Didn't have this problem in the past.

**Comment by jonaswesterlund** [comment]
I've started having the same issue after installing Coolify on a new server. Docker containers bound to a service disappear resulting in the service returning 500. This doesn't happen immediately and not all containers vanish (for example my Plausible-service just has the Clickhouse-container running).

**Comment by raphaelbernhart** [comment]
Same here, the issue appears after a restart of the server on my side.

**Comment by mprajescu** [comment]
Is there a way to manually fix this? I need to amend details on the services.

**Comment by raphaelbernhart** [comment]
@andrasbacsai What do you think. I think me and some other people need those services up again but it is not working at the moment. Is there a way to get the containers back up?

Thanks

**Comment by mufasilfaizal** [comment]
Same here, happened after restarting coolify from commandline. 
Any ways to fix? Appreciate your prompt attention on this matter @andrasbacsai 

Thanks

**Comment by alexisdechiara** [comment]
I have the same issue since I tried to update to the latest version, do you know if there is a possibility to run services from command line ?

**Comment by andrasbacsai** [comment]
Hey, this problem could be solved with the [followings](https://docs.coollabs.io/coolify-v3/rollsecretkey#rollback-to-old-secret-key).

Unfortunately, if anything created after the database backup date (see the docs in the link above) will be lost, due that they are encrypted with a wrong key.

If you need help, [contact me](https://docs.coollabs.io/contact).

**Comment by andrasbacsai** [comment]
This could be solved by following this [docs](https://docs.coollabs.io/coolify-v3/rollsecretkey#rollback-to-old-secret-key).

Note: Anything created between the database backup and now will be lost, due that the encryption key made some values unreadable.

If you need help, you can [contact me](https://docs.coollabs.io/contact).

**Comment by alexisdechiara** [comment]
Thank you, my services are back … but when I run a service and I try to access it via its URL, it gives me a 404 error, even if I change the sub-domain name to a new one.

**Comment by andrasbacsai** [comment]
Due to inactivity, I'm closing this issue. However, if the problem persists, please reopen the issue. Thanks!
