### ISSUE TITLE
Request to switch from 4-space tabs to 2-space indentation in TypeScript/JavaScript codebase

### ISSUE THREAD

**Issue by Geczy** [coollabsio/coolify#1167]
**Issue Description:**
As an active contributor and user of this TypeScript/JavaScript repository, I would like to propose a change in the indentation style from using 4-space tabs to 2-space indentation with no tabs. The goal of this switch is to improve code readability, maintainability, and consistency throughout the codebase.

**Why 2-space indentation?**
1. **Readability:** Smaller indentation allows for more code to fit in the same view, reducing the need for horizontal scrolling and making the codebase more accessible to developers with various screen sizes.
2. **Consistency:** Many popular JavaScript and TypeScript projects and style guides, including Airbnb, Google, and StandardJS, have adopted the 2-space indentation standard. By aligning with these standards, new contributors will feel more familiar with the codebase and can easily jump in to contribute.
3. **Editor Support:** Most modern text editors and IDEs have default settings that use 2-space indentation, which means developers using these tools will have a more seamless experience with the codebase.
4. **Git Diffs:** Smaller indentation size will result in cleaner and easier-to-read Git diffs, making code reviews more straightforward and efficient.

**Proposed Solution:**
1. Replace all existing 4-space tabs with 2-space indentation across the codebase.
2. Update the project's README and CONTRIBUTING files to reflect the new indentation style, making it clear for all contributors.

**Plan for Implementation:**
1. Create a branch specifically for the indentation changes.
2. Use automated refactoring tools to update the indentation throughout the codebase.
3. Manually review and address any potential conflicts or issues caused by the indentation changes.
4. Update the project's documentation to reflect the new indentation standard.
5. Submit a pull request with the changes for further review and discussion.

**Potential Concerns:**
1. **Backward Compatibility:** Ensure that the codebase remains backward compatible with older versions of TypeScript and JavaScript.
2. **Impact on Existing Contributors:** Address concerns from existing contributors who are accustomed to the current indentation style and provide support in transitioning to the new style.

**Additional Notes:**
I believe that adopting a 2-space indentation style aligns with the best practices and conventions followed by the broader JavaScript and TypeScript community. It will not only benefit the current contributors but also attract new contributors who are familiar with the 2-space standard. Let's discuss and reach a consensus on this change to enhance the overall development experience in this repository. Your feedback and input on this matter are highly appreciated.

Thank you for considering this proposal. Let's work together to make the codebase more readable and maintainable for all!

**Comment by maietta** [comment]
The adoption of VSCode was the wisest move I've made in software development. I encourage others to do the same.

These are non-issues in modern IDE's and general purpose code editors.

**Comment by Geczy** [comment]
@maietta why are they non issues with an editor?

**Comment by sanny-io** [comment]
> These are non-issues in modern IDE's and general purpose code editors.

That is not true.

**Comment by maietta** [comment]
I've been writing software since I was 12 years old. I'm 43 now. You do the math.

I'm fluent in 68 programming languages across many version of Windows, Linux, and macOS, not to mention DOS, TRS-80, Amiga and other systems, including VAX systems back in the day.

If it's an issue still for you, change your tooling. The world isn't going adopt one over the other. There will never be solidarity on this issue. Ever.

Like forever ever.

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.

**Comment by Geczy** [comment]
This isn’t a feature it’s a bug

**Comment by andrasbacsai** [comment]
That is true. But the whole repository changed from JS/TS to PHP, so it does not make sense anymore.

Or am I wrong?

**Comment by Geczy** [comment]
Unfortunately viewing commits still imposes gigantic white space, hindering proper rendering in the browser and ides
