### ISSUE TITLE
Nuxt 3 Start Command

### ISSUE THREAD

**Issue by KalynDavis** [coollabsio/coolify#1173]
I'm confused as I am attempting to generate a static site with Nuxt 3. What should the start command be? `npx serve`?

**Comment by hacknug** [comment]
I think it should be `nuxt preview`

**Comment by KalynDavis** [comment]
I didn't notice there was a static mode for applications. Selecting that and clearing out the start command field resolved this for me.

**Comment by JoshuaB94** [comment]
@KalynDavis and @hacknug it worked for me as well when trying to fix a deployment issue for an Astro site. I just cleared the Start Command field and checked the is this a static site box. And it worked!
