### ISSUE TITLE
[Feature] Display Pull Progress and Deployment Logs

### ISSUE THREAD

**Issue by ParsaGachkar** [coollabsio/coolify#1174]
I think having a Pull progress and Deployment Logs tab would help me a lot. I was dealing with troubleshooting of my coolify instance the error popups for docker deployment failures were dismissed too quickly. I had to keep my network tab of devtools open to analyze the errors and I didn't have a progress indicator, so I never knew that if the issue is fixed or not until it failed.

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
