### ISSUE TITLE
Not using Environment variables defined in docker-compose.yml

### ISSUE THREAD

**Issue by Kuzat** [coollabsio/coolify#1175]
I have defined some environment variable under the field `environment` in my docker-compose.yml. However, it seems like they are not used, and I had to manually copy them to the secrets tab. 

Is this how it is intended to work when deploying with docker-compose? 
Would it be possible to add a feature to use the environment variables defined in docker-compose.yml?

**Comment by ibesty** [comment]
Yeah, I had that problem too. coolify version 3.12.36

**Comment by ibesty** [comment]
> Yeah, I had that problem too. coolify version 3.12.36

Looks like it was fixed in version 3.12.37

**Comment by iron3oxide** [comment]
Can this issue be closed then?

**Comment by peaklabs-dev** [comment]
@Kuzat This has been fixed in v4.
Hardcoded environment variables are not shown in the UI (`TEST=TEST` -> not shown, as it is not needed to be changed), only those defined as variables can be set in the UI (`'TEST=${TEST}'` shown in the UI to change).
