### ISSUE TITLE
Support for repos that both contain a client and server?

### ISSUE THREAD

**Issue by 0xgeert** [coollabsio/coolify#1176]
I’m used to setting up a repo with a server (node/express) and client (vuejs). They have separate package.Json files in their respective subdirectories for building.

How would I use coolify with a repo like this?

**Comment by craigharman** [comment]
+1 for this

**Comment by Megamannen** [comment]
Support for "monorepo"

**Comment by dhpancor** [comment]
+1 for this. Support for monorepos is a **must**.

**Comment by andrasbacsai** [comment]
Monorepo support will be available in v4.

I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
