### ISSUE TITLE
Unique secrets 

### ISSUE THREAD

**Issue by thalesog** [coollabsio/coolify#118]
Hi!

I'm using v2.0.5 and having this error when try to add two secrets with same name in different applications

![image](https://user-images.githubusercontent.com/4792793/153692397-2b85417c-16bf-4e03-8cbf-b5146af2dff6.png)

Can we associate the application id with the unique constraint?

https://github.com/coollabsio/coolify/blob/2b31532d19ba8fa7a70031c60bcdbc5f6a877350/prisma/schema.prisma#L108

Maybe with this way we can fix this
```js
@@unique([name, applicationId])
```
I can help refactor if you approve this changes.

**Comment by andrasbacsai** [comment]
Nice catch! 

If you don't mind, I fixed it as I would like to redesign the secrets part a bit as well, and this was an excellent opportunity to do it! 😄 

Fixed with #119, in [v2.0.6](https://github.com/coollabsio/coolify/releases/tag/v2.0.6)
