### ISSUE TITLE
WordPress Services returns 500 Errors

### ISSUE THREAD

**Issue by mufasilfaizal** [coollabsio/coolify#1180]
Getting 500 Page error while accessing existing WP Deployments Settings. But while creating new WP services it works fine. 

Frontend Error:
<img width="1495" alt="Screenshot 2023-08-17 at 5 36 00 AM" src="https://github.com/coollabsio/coolify/assets/14259658/1b39e21c-5dd6-489e-a0a0-f997132ee852">

Console Error:
{"statusCode":401,"code":"FST_JWT_NO_AUTHORIZATION_IN_HEADER","error":"Unauthorized","message":"No Authorization was found in request.headers"}

Recently tried to restart the Coolify from Terminal, then after this happened.

**Comment by zoocityboy** [comment]
#1166

**Comment by andrasbacsai** [comment]
Hey, this problem could be solved with the [followings](https://docs.coollabs.io/coolify-v3/rollsecretkey#rollback-to-old-secret-key).

Unfortunately, if anything created after the database backup date (see the docs in the link above) will be lost, due that they are encrypted with a wrong key.

If you need help, [contact me](https://docs.coollabs.io/contact).

**Comment by andrasbacsai** [comment]
This could be solved by following this [docs](https://docs.coollabs.io/coolify-v3/rollsecretkey#rollback-to-old-secret-key).

Note: Anything created between the database backup and now will be lost, due that the encryption key made some values unreadable.

If you need help, you can [contact me](https://docs.coollabs.io/contact).
