### ISSUE TITLE
Missing documentation for customization of traefik reverse proxy

### ISSUE THREAD

**Issue by Lau-r-a** [coollabsio/coolify#1182]
It seems like currently theres no information on how to futher configurate traefik labeles e.g. in a docker-compose to allow custom TCP/HTTPS Proxy Options.

Maybe it would be helpful to document as the general information on traefik seems the require further inbuilt coolify knowledge to change this.

Generally those questions came up for me:
How do I forward a TCP Port through traefik? Am I even supposed to use docker labels? 
How do I forward a certain http(s) port of my appliccation to be available? Use labels? Using docker compose the URL field is non changeable.

**Comment by andrasbacsai** [comment]
Docs will be updated sooon
