### ISSUE TITLE
Unexpected token \u001c in JSON at position 418

### ISSUE THREAD

**Issue by mangledbottles** [coollabsio/coolify#1184]
![coolifyerror](https://github.com/coollabsio/coolify/assets/22305511/7eaaf699-e92c-40fa-8f24-6d393c2642b7)

URL: `https://{{selfhost_coolify}}/services/clf8n3erh0000n79ghjdiw4n5`

Hey, I am getting this error when I try to open Plausible Analytics in Coolify and I get this error
- I have tried restarting Coolify
- Rolling back Coolify
- Upgrading Coolify via CLI
- I'm now at the stage of going through the docker container and seeing what I can do, I've manually restarted the container for Plausible

**Note**: The instance of Plausible works perfectly, its ingesting analytics and I can view them and everything works normally other than trying to manage it in Coolify

I created another Plausible service and I can open it no problem in Coolify

Any ideas would be much appreciated! :)

**Comment by abelkuruvilla** [comment]
@mangledbottles I also just found this error after accidently upgrading coolify. Tried rollback, but the error is still there.. Happens in both my plausible and ghost cms services

**Comment by mangledbottles** [comment]
@abelkuruvilla Following this solves the issue https://github.com/coollabsio/coolify/issues/1180#issuecomment-1689644167
