### ISSUE TITLE
MongoDB does not use ssl

### ISSUE THREAD

**Issue by miguelgargallo** [coollabsio/coolify#1185]
On MongoDB when I create a DB, it shows me:

```
readPreference=primary&ssl=false
```

Am I skipping some steps? I mean, I have ssl, inside added on Settings, (I am not in beta)

**Comment by ashermyers** [comment]
SSL is not enabled by default in Coolify v3. Not sure if it's implemented in v4 but as of now no SSL support for MongoDB natively.

**Comment by miguelgargallo** [comment]
Hi @ashermyers, as far as I know, its not worth nothing to have a powerful tool like Coolify if Databases have not ssl, for example, from the Coolify/PocketBase we got ssl over the docker, should this inspire on how databases could be in v4? This way it is possible, cause at the moment, using a non ssl db, its not secure for users

**Comment by ashermyers** [comment]
This is most likely going to be a feature in v4.

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
