### ISSUE TITLE
[Bug]: (v4) Deploying private repo with Github App

### ISSUE THREAD

**Issue by JorrinKievit** [coollabsio/coolify#1188]
### Description
Trying to deploy a private repository with a GitHub App. Installed a Github App through the "Deploy: Private Repository (with GitHub Apps)". The app looks like this:
![image](https://github.com/coollabsio/coolify/assets/43169049/5a2e85a5-e6a5-4088-a6f3-20f6c76ee5df)
 
And has access to all repositories:
![image](https://github.com/coollabsio/coolify/assets/43169049/d101c5b5-548d-47b7-9cb5-d0215b2df032)

In the application, this app is also selected:
![image](https://github.com/coollabsio/coolify/assets/43169049/fbde4d4d-3f78-471b-a880-73ea909192f2)

But i am getting the following error on deployment:
![image](https://github.com/coollabsio/coolify/assets/43169049/04ce9be7-7f39-4864-85e5-2f8ac41d441c)

### Version
v4.0.0-beta.21

**Comment by JorrinKievit** [comment]
Seemed to be fixed in v4.0.0-beta.22 😄

**Comment by sohaibahsan007** [comment]
@andrasbacsai  facing the issue:

Error: Failed to get access token for smiels-server-github-dev with error: 'Expiration time' claim ('exp') must be a numeric value representing the future time at which the assertion expires

![image](https://github.com/coollabsio/coolify/assets/19934571/2a78f5ed-8f95-4297-a9f3-8db7849f27fd)
