### ISSUE TITLE
Cannot deploy nextJS project on a Digital Ocean droplet or Contabo VPS

### ISSUE THREAD

**Issue by kleenkanteen** [coollabsio/coolify#1190]
Try using coolify to download this project: https://github.com/adrianhajdin/project_next13_car_showcase/tree/main

The public directory should be `.next`. Try setting the FQDN to a subdomain of your choice, enable SSL encryption (not custom). When it is finished building, and I go to the subdomain, I either get "Internal Server Error" or "404 page not found" or "Bad Gateway." The SSL certificate seems to work as the lock icon is in the address bar. I have tried all this on a Contabo VPS as well but it says it says the site refused to connect.

**Comment by deployn** [comment]
I’m sorry, but I can’t reproduce the issue. Based on the information provided, it seems that the project doesn’t have a public directory or a static export. Additionally, the publishing directory can remain empty.

**Comment by kleenkanteen** [comment]
Right this is an old issue, fixed it since. I left the publishing directory empty now. Also the setting "Use Coolify proxy" was not turned on my default for some reason so that's why the "404 page not found" error was there.
