### ISSUE TITLE
How to hard-uninstall coolify

### ISSUE THREAD

**Issue by bahriddin** [coollabsio/coolify#1191]
Thanks for this great tool.
I want to hard remove Coolify and its all files and reinstall again because I am having some DNS issues.
I followed [this script](https://docs.coollabs.io/coolify-v3/installation#uninstall) but when I am installing again my user credentials, projects are still there. How can I hard uninstall?

I am using ver 3 on my Raspberry Pi 4B.
Regards

**Comment by andrasbacsai** [comment]
Updated the [docs](https://docs.coollabs.io/coolify-v3/installation#uninstall) with all things you need to delete to completely remove Coolify from your server.

**Comment by bahriddin** [comment]
Thanks for the answer. But it looks like you forgot to add `coolify-db` container and volume in the doc.
Otherwise, it worked like a charm ❤️

**Comment by andrasbacsai** [comment]
`coolify-db` container does not exists in v3. v3 uses SQLite. :)

**Comment by bahriddin** [comment]
I installed v4 before v3. Maybe that's why.
