### ISSUE TITLE
IPv6 Support for Install Script

### ISSUE THREAD

**Issue by funkybunch** [coollabsio/coolify#120]
Seems the install script doesn't work over an IPv6 connection - I had to proxy to an IPv4 connection to get it to work after confirming that `get.coollabs.io` doesn't have any IPv6 support.

Would it be possible to add an `AAAA` record to `get.coollabs.io` to support IPv6?

**Comment by andrasbacsai** [comment]
Great suggestion! Added an `AAAA` record for `get.coollabs.io`!
