### ISSUE TITLE
[Core]: Support BitBucket Or any host

### ISSUE THREAD

**Issue by unpseudocomplique** [coollabsio/coolify#1204]
For now only gitlab & github are supported.

To be usable i need to at least manualy deploy from any git host or bitbucket.

Maybe like clevercloud or vercel we can deploy to a git remote ?

Thank you for your work ! 💪

**Comment by 40056** [comment]
that would be also very important for us. Is there any timeline?

**Comment by andrasbacsai** [comment]
To be able to deploy from any git source is simple to add. 

Adding a fully integrated Bitbucket (or any) git provider is a bit harder (webhooks, etc.).

Which one of these is important for you, @btalin ?

**Comment by andrasbacsai** [comment]
Subissue: https://github.com/coollabsio/coolify/issues/1233

**Comment by Xadoy** [comment]
Is it possible to achieve like caprover CLI? https://caprover.com/docs/deployment-methods.html
Which actually works like Heroku.

**Comment by andrasbacsai** [comment]
> Is it possible to achieve like caprover CLI? https://caprover.com/docs/deployment-methods.html Which actually works like Heroku.

Yes, I will soon start working on Coolify's CLI.

**Comment by andrasbacsai** [comment]
You can now deploy from any git provider, public or private (with ssh-key) repositories.
