### ISSUE TITLE
[Bug]: Beta:37

### ISSUE THREAD

**Issue by jetsoms** [coollabsio/coolify#1227]
### Description

Upon installing via the bashscript and proceeding to ip:8000 and inputting user details, the following error is noted stating "attempt to read property email on null"

![image](https://github.com/coollabsio/coolify/assets/97310579/e48479d6-83a1-490a-8bdf-d4c40e50e429)

### Minimal Reproduction (if possible, example repository)

- Install via script
- Proceed to ip:8000
- Input user details
- Error appears

### Version

beta37

**Comment by andrasbacsai** [comment]
Hey, a fix is on its way. Sorry about that

**Comment by andrasbacsai** [comment]
If you face the error, upgrade to 4.0.0-beta.38 or wait for the auto-update to happen. Then:

- Clear cookies from your browser related to your instance (F12->Applications tab->Cookies->Delete coolify_session cookie).

**Comment by altsst** [comment]
possibly related to this issue: https://discord.com/channels/459365938081431553/877863871753355264/1152567319713816597
