### ISSUE TITLE
[Core] Able to deploy from any git providers

### ISSUE THREAD

**Issue by andrasbacsai** [coollabsio/coolify#1233]
No webhooks, no integration, just pure git clone.

**Comment by unpseudocomplique** [comment]
Saw that it was added in 69 👀

Got an issue, not sure if it's related to external git.

Express app is successfully running with this config (express running on 0.0.0.0:3000):

![image](https://github.com/coollabsio/coolify/assets/69119668/71e443e3-f193-4b9d-a5aa-ee4abb0d2887)

HeartBeat are working and startup logs look good.

Still got this error with no log of incoming request : 
![image](https://github.com/coollabsio/coolify/assets/69119668/8b848423-5a42-4324-ace1-d4bac0d4959a)

**Comment by unpseudocomplique** [comment]
For testing purpose, i was doing it on the same host where coolify was deployed.
I just tryed on an other host with the same config, and app is working 🤔

**Comment by andrasbacsai** [comment]
I tried to reproduce this issue, but I could not. The only problem I can think of is that the proxy could not be started on the server where Coolify is running. 

Can you reproduce it so we can investigate (over Discord)?

**Comment by Typ0genius** [comment]
How can I set a custom ssh port?
