### ISSUE TITLE
[Bug]: (v4) Source secret inputs on top of action menu

### ISSUE THREAD

**Issue by JorrinKievit** [coollabsio/coolify#1240]
### Description

The inputs on a source page like Github App have a higher z-index than the action menu.

### Minimal Reproduction (if possible, example repository)

1. Go to any existing source
2. Open action menu with "/" or clicking on the menu top left

### Exception or Error

![image](https://github.com/coollabsio/coolify/assets/43169049/f9ba4988-2082-4c4f-988f-b6133e03c8f8)

### Version

v4.0.0-beta.43

**Comment by andrasbacsai** [comment]
@chz Could you please check this? 

It is a tricky one - at least for me. For the password fields, I use absolute position in a relative parent, to place the small eye icon inside the input box.

The Magicbar (vue) component is a fixed background with a fixed-positioned menu.

**Comment by chz** [comment]
> @chz Could you please check this? 
> 
> 
> 
> It is a tricky one - at least for me. For the password fields, I use absolute position in a relative parent, to place the small eye icon inside the input box.
> 
> 
> 
> The Magicbar (vue) component is a fixed background with a fixed-positioned menu.

Yeap i will check and create PR

**Comment by chz** [comment]
@andrasbacsai also i think, Maybe we must refactor this input component to use flex approach instead relative absolute. For future we can extend more and more icons left or right.

**Comment by andrasbacsai** [comment]
> @andrasbacsai also i think, Maybe we must refactor this input component to use flex approach instead relative absolute. For future we can extend more and more icons left or right.

Yes, I'm okay with it. It was just a quick solution from me. I'm open to any improvement here.

Would you like me to open an issue for it?

**Comment by chz** [comment]
> > @andrasbacsai also i think, Maybe we must refactor this input component to use flex approach instead relative absolute. For future we can extend more and more icons left or right.
> 
> Yes, I'm okay with it. It was just a quick solution from me. I'm open to any improvement here.
> 
> Would you like me to open an issue for it?

Yeap create issue for that i will try to refactor input component
