### ISSUE TITLE
[Bug]: v4 Instance`s domain

### ISSUE THREAD

**Issue by lortonx** [coollabsio/coolify#1241]
### Description

![image](https://github.com/coollabsio/coolify/assets/13281000/89531f16-1715-4900-b1af-2063367c3bcc)

If the address is specified with https://, the browser error “Too many redirects” occurs.
But if the address is specified with http:// then there is no problem

### Minimal Reproduction (if possible, example repository)

just make yourself an address like in the screenshot, a subdomain, and start with https://

### Version

v4.0.0-beta.43 - v4.0.0-beta.44

**Comment by andrasbacsai** [comment]
Are you using Cloudflare? If yes, you need to change your SSL configurations like [this](https://www.bobmatyas.com/blog/too-many-redirects/#:~:text=If%20you%20are%20redirecting%20HTTP%20to%20HTTPS%20this,to%20send%20encrypted%20traffic%20to%20your%20web%20server.).

If not, let me know and I will investigate.

**Comment by ahmed-lotfy-dev** [comment]
i'm facing the same issue and i gone through the guide and tried full & full (strict) and even turned it not secured but nothing happened not redirecting to the coolify dashboard don't know why 
i'm on the latest v45 at this moment and it is a fresh install too hope this could be resolved

**Comment by lortonx** [comment]
I specified an SSL other than Flexible, as a result the panel and applications did not open. Regards, HTTP or HTTPS is specified in the coolify settings. Very strange results

**Comment by lortonx** [comment]
I specified an SSL other than Flexible, as a result the panel and applications did not open. Regards, HTTP or HTTPS is specified in the coolify settings. Very strange results

**Comment by lortonx** [comment]
Problem solved. I forgot to allow port 443 for cloudflare. 😳
