### ISSUE TITLE
[Bug]: (v4) Can't install Github App to Github org

### ISSUE THREAD

**Issue by ashermyers** [coollabsio/coolify#1243]
### Description

Can't install a github app on the github org level. It would also be nice to be able to use a PAT (Personal-Access-Token) to read/write from repos on coolify apps.

### Minimal Reproduction (if possible, example repository)

Sources -> (Source with the specified organization box) -> update-repositories

Then will proceed to install on a personal Github account rather than an organization.

### Version

v4.0.0-beta.43

**Comment by andrasbacsai** [comment]
I will check the issue!

You can use private repos with deploy keys. Is it not suitable for your use case?

![image](https://github.com/coollabsio/coolify/assets/5845193/23cc6cde-38c8-48a7-a740-5e312f4e5ab2)

**Comment by andrasbacsai** [comment]
I've made a new GitHub App with a GitHub organization (coollabsio), and when I open it from the Sources menu and would like to Update Repositories, it forwards me to the right GitHub App on Github.


Can you please show me with an image (or a small video) what is not working for you?

**Comment by ashermyers** [comment]
In the image, you can see it's installing the Github app to my personal account instead of the organization I specified under "Organization".
![Screenshot from 2023-09-24 15-05-22](https://github.com/coollabsio/coolify/assets/43706372/f2a12794-2c8c-4827-a133-295b3b043877)

**Comment by ashermyers** [comment]
Here is a step by step video of what i'm doing: 
[Screencast from 09-24-2023 03:08:44 PM.webm](https://github.com/coollabsio/coolify/assets/43706372/ba657098-bdd4-4371-a6c4-eeab8f747d4e)

**Comment by ashermyers** [comment]
The issue is that it should be creating a github app for the organization I specified, but instead it is installing the app to my personal account. Then when I try and deploy an application via the git source, just my personal account repos show up not the ones on my github org.

**Comment by andrasbacsai** [comment]
I saw in your video (26s) that you do not have permission to create a GitHub App on the organization.
![image](https://github.com/coollabsio/coolify/assets/5845193/8838480c-6911-4bef-8f44-c92c7b2c6d56)

**Comment by ashermyers** [comment]
Yep, that was it! Sorry!
