### ISSUE TITLE
[Bug]: Deployment with Private Repository (with deploy key) leads to error 500

### ISSUE THREAD

**Issue by renekahr** [coollabsio/coolify#1251]
### Description

When trying to add a resource using Private Repository (with deploy key), it's not possible to save the new application.

When clicking here after filling in the form:
<img width="1328" alt="Screenshot 2023-09-25 at 13 03 42" src="https://github.com/coollabsio/coolify/assets/100137712/3a460a53-11d0-47bc-beb6-2107d66451a1">

This error comes up:
<img width="580" alt="Screenshot 2023-09-25 at 13 00 33" src="https://github.com/coollabsio/coolify/assets/100137712/0aa3b051-0253-4126-b9a0-edb6b160a16c">

I'm trying an https URL from GitLab CE.

### Minimal Reproduction (if possible, example repository)
Try the following steps with a GitLab CE repository:
- Create Project
- select environment
- add resource
- select "Private Repository (with deploy key)"
- select a private key
- enter repository url and branch
- click "Save New Application"

### Version

v4.0.0-beta.45

**Comment by andrasbacsai** [comment]
Hey, thanks for the report. 

Currently, only Github is supported, but will add a feature to deploy any git repositories (#1204), but with limited integrations.

**Comment by andrasbacsai** [comment]
Since [this](https://github.com/coollabsio/coolify/releases/tag/v4.0.0-beta.69) release it is possible to deploy from any git provider, just without webhook support.
