### ISSUE TITLE
[Bug]: v3 environment variables are messed up

### ISSUE THREAD

**Issue by ChiefORZ** [coollabsio/coolify#1253]
### Description

I dont know how this happened, but somehow my running system got f*** up. All environment variables and  Build / Deploy Logs are encoded that coolify can not read it anymore. And it isn't just an display issue, the builds do not succeed on new builds.

![Coolify](https://github.com/coollabsio/coolify/assets/6916518/a44da81f-8240-422b-b450-fc3e9b889ddb)
<img width="1064" alt="image" src="https://github.com/coollabsio/coolify/assets/6916518/ec9718fe-8187-4c37-b81a-ef3b15c2003a">

Anybody got any recommendations on what i can try to debug this, before i roll back to a backup?

### Minimal Reproduction (if possible, example repository)

-

### Version

v3.12.36

**Comment by andrasbacsai** [comment]
You probably face the [following](https://github.com/coollabsio/coolify/issues/1148#issuecomment-1644142522) issue. If you need help to fix it, [contact me](https://docs.coollabs.io/contact) please.

**Comment by ChiefORZ** [comment]
@andrasbacsai this indeed was the problem. Glad i could solve if without rollback 🥳
