### ISSUE TITLE
[Bug]: docker compose project name

### ISSUE THREAD

**Issue by n1ght-hunter** [coollabsio/coolify#1254]
### Description

no docker compose project name is being set so it is using the file name which is `source` and doesn't really show what it is. 
i have something like 30 project running and this offputing.

fix is either add `-p coolify` to docker compose up or add COMPOSE_PROJECT_NAME=coolify to the env

### Minimal Reproduction (if possible, example repository)

NA

### Version

V4

**Comment by andrasbacsai** [comment]
Docker Compose support is not yet available in v4. How (or why) do you use it?

**Comment by Night-Hunter-NF** [comment]
sorry i should have explained it more this the docker compose stack name that coolify uses to deploy coolify, postgresql and redis. 
its done using this compose file.
https://github.com/coollabsio/coolify/blob/main/docker-compose.yml

**Comment by andrasbacsai** [comment]
Sorry, but I still don't get it. Can you please rephrase your problem?

By the way, composd support is available for a few days.

**Comment by n1ght-hunter** [comment]
as document in link below shows `--project-name` is used to set the project name when running a docker compose file
https://docs.docker.com/compose/reference/#command-options-overview-and-help

currently coolfiy's start script just calls 
`docker compose -d` 
which means if your call `docker compose ls` coolify will be listed as 
`source              running(3)                  /data/coolify/source/docker-compose.yml,/data/coolify/source/docker-compose.prod.yml`
because the project name was just chosen from the dir  that the compose is in which is source.
but if docker compose is called like
`docker compose -p coolify -d`
it would look like 
 `coolify              running(3)                  /data/coolify/source/docker-compose.yml,/data/coolify/source/docker-compose.prod.yml`

**Comment by n1ght-hunter** [comment]
this is for the coolify stack its self none of the things it runs

**Comment by andrasbacsai** [comment]
Due to inactivity, I'm closing this issue. However, if the problem persists, please reopen the issue. Thanks!
