### ISSUE TITLE
[Bug]: Errors in "jq" calls of installation script

### ISSUE THREAD

**Issue by DevHusariaSolutions** [coollabsio/coolify#1257]
### Description

It seems like some configuration has been missed

### Minimal Reproduction (if possible, example repository)

I use official method of installation
```curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash```
No matter I'm using Debian 10 or 11 (just upgraded, since Debian 10 hadn't "jc" package available), I gets error:

```jq: error (at /etc/docker/daemon.json.coolify:7): object ({"log-drive...) and null (null) cannot be multiplied```

Then another steps continues.

At the end I can run admin dashboard,
but when trying to connect to Docker deamon, I gets error "Permission denied".

I had to manually add such key to got through

### Exception or Error

jq: error (at /etc/docker/daemon.json.coolify:7): object ({"log-drive...) and null (null) cannot be multiplied

### Version

v4.0.0-beta.46

**Comment by andrasbacsai** [comment]
I've updated the installation script since this issue. Could you please try it again and let me know if it still does not work?
