### ISSUE TITLE
[Bug]: Install script returns "This script only supports Ubuntu and Debian for now." on fresh install of Raspbian GNU/Linux 11 (Bullseye)

### ISSUE THREAD

**Issue by silasabbott** [coollabsio/coolify#1259]
### Description

Install script does not run on the latest version of Raspbian. Seems as if the install script is incorrectly determining that Raspbian is not based on Debian, thus it fails.

### Minimal Reproduction (if possible, example repository)

1. Install Raspbian Pi OS Lite (32-bit, Bullseye)
2. Run the Coolify install script as administrator

### Exception or Error

Coolify install script returns:
```
This script only supports Ubuntu and Debian for now.
```

### Version

v4.0.0-beta.46

**Comment by andrasbacsai** [comment]
Can you please show me the output of `cat /etc/os-release`?

**Comment by silasabbott** [comment]
```
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

The image was written using the official Raspberry Pi Imager and the default options

**Comment by andrasbacsai** [comment]
Thanks! I will fix it and let you know!

**Comment by andrasbacsai** [comment]
Can you please check it again?

**Comment by silasabbott** [comment]
Great, it says it installed correctly now!

However, I can't seem to access the UI. I'm SSH'ed into the RPi from another machine, and I'm not seeing any docker containers running on my RPi. I don't recognize the IP address that the Coolify installer spit out either. Am I missing something or is this unexpected behavior?

**Comment by silasabbott** [comment]
I took another stab at this with the same machine, and now I'm getting:
```
Downloading required files from CDN...
latest: Pulling from coollabsio/coolify-helper
docker: no matching manifest for linux/arm/v8 in the manifest list entries.
See 'docker run --help'.
```
