### ISSUE TITLE
Most navigation doesn't work on inputs

### ISSUE THREAD

**Issue by sphinxc0re** [coollabsio/coolify#126]
## The problem

When using any text-based input in Coolify, it seems to be impossible to navigate.

## How to reproduce

1. Enter text into any text-based input like the "Publish Directory" in `/applications/{someId}`.
2. Try to set the text-cursor to any position that is not the end of the text.
3. Try to move the cursor with the arrow keys.
4. Try to empty the whole field using <kbd>Cmd</kbd> + <kbd>Backspace</kbd> or
5. <kbd>Ctrl</kbd> + <kbd>Backspace</kbd> for single words.

None of it works

**Comment by andrasbacsai** [comment]
Can you please show me a short video? I tried to reproduce it on Windows/Linux/Mac, with different browsers, but I could not.

Also please let me know your OS/Browser.

Thanks in advance.

**Comment by andrasbacsai** [comment]
Yes, I have a [demo instance](https://demo.coolify.io). Could you please try it if you have some free time?

**Comment by sphinxc0re** [comment]
It seems to be fixed now. At least, I cannot reproduce it anymore.
