### ISSUE TITLE
[Bug]: All Services Cannot Be Created

### ISSUE THREAD

**Issue by ashermyers** [coollabsio/coolify#1265]
### Description

Cannot create Ghost Blogging service:
![Screenshot from 2023-09-29 09-38-30](https://github.com/coollabsio/coolify/assets/43706372/3ba0c698-d091-4783-bbc5-ffe259ab877d)

### Minimal Reproduction (if possible, example repository)

Attempt to create the Ghost service.

### Exception or Error

Error: SQLSTATE[42703]: Undefined column: 7 ERROR: column "image" of relation "service_applications" does not exist LINE 1: insert into "service_applications" ("name", "image", "servic... ^ (Connection: pgsql, SQL: insert into "service_applications" ("name", "image", "service_id", "uuid", "updated_at", "created_at") values (ghost, ghost:5, 4, qwwowsw, 2023-09-29 13:37:28, 2023-09-29 13:37:28) returning "id")

### Version

v4.0.0-beta.50

**Comment by ashermyers** [comment]
Update: the service was created but I had to go back to home and navigate into the project and then it shows up. But this error should not be showing.

**Comment by ashermyers** [comment]
Update: this occurs with ALL services.

**Comment by andrasbacsai** [comment]
It looks like you used a development build of Coolify at some point, which messed up your database migrations. (Please turn it off in Settings->Enable pre-release updates)

Can you please show me the output of `docker exec coolify bash -c "php artisan migrate:status"`?

**Comment by ashermyers** [comment]
Yes, the output is as following:
`
  Migration name .............................................. Batch / Status  
  2014_10_12_000000_create_users_table ............................... [1] Ran  
  2014_10_12_100000_create_password_reset_tokens_table ............... [1] Ran  
  2014_10_12_200000_add_two_factor_columns_to_users_table ............ [1] Ran  
  2019_12_14_000001_create_personal_access_tokens_table .............. [1] Ran  
  2023_03_20_112410_create_activity_log_table ........................ [1] Ran  
  2023_03_20_112411_add_event_column_to_activity_log_table ........... [1] Ran  
  2023_03_20_112412_add_batch_uuid_column_to_activity_log_table ...... [1] Ran  
  2023_03_20_112809_create_sessions_table ............................ [1] Ran  
  2023_03_20_112811_create_teams_table ............................... [1] Ran  
  2023_03_20_112812_create_team_user_table ........................... [1] Ran  
  2023_03_20_112813_create_team_invitations_table .................... [1] Ran  
  2023_03_20_112814_create_instance_settings_table ................... [1] Ran  
  2023_03_24_140711_create_servers_table ............................. [1] Ran  
  2023_03_24_140712_create_server_settings_table ..................... [1] Ran  
  2023_03_24_140853_create_private_keys_table ........................ [1] Ran  
  2023_03_27_075351_create_projects_table ............................ [1] Ran  
  2023_03_27_075443_create_project_settings_table .................... [1] Ran  
  2023_03_27_075444_create_environments_table ........................ [1] Ran  
  2023_03_27_081716_create_applications_table ........................ [1] Ran  
  2023_03_27_081717_create_application_settings_table ................ [1] Ran  
  2023_03_27_081718_create_application_previews_table ................ [1] Ran  
  2023_03_27_083621_create_services_table ............................ [1] Ran  
  2023_03_27_085020_create_standalone_dockers_table .................. [1] Ran  
  2023_03_27_085022_create_swarm_dockers_table ....................... [1] Ran  
  2023_03_28_062150_create_kubernetes_table .......................... [1] Ran  
  2023_03_28_083723_create_github_apps_table ......................... [1] Ran  
  2023_03_28_083726_create_gitlab_apps_table ......................... [1] Ran  
  2023_04_03_111012_create_local_persistent_volumes_table ............ [1] Ran  
  2023_05_04_194548_create_environment_variables_table ............... [1] Ran  
  2023_05_17_104039_create_failed_jobs_table ......................... [1] Ran  
  2023_05_24_083426_create_application_deployment_queues_table ....... [1] Ran  
  2023_06_22_131459_move_wildcard_to_server .......................... [1] Ran  
  2023_06_23_084605_remove_wildcard_domain_from_instancesettings ..... [1] Ran  
  2023_06_23_110548_next_channel_updates ............................. [1] Ran  
  2023_06_23_114131_change_env_var_value_length ...................... [1] Ran  
  2023_06_23_114132_remove_default_redirect_from_instance_settings ... [1] Ran  
  2023_06_23_114133_use_application_deployment_queues_as_activity .... [1] Ran  
  2023_06_23_114134_add_disk_usage_percentage_to_servers ............. [1] Ran  
  2023_07_13_115117_create_subscriptions_table ....................... [1] Ran  
  2023_07_13_120719_create_webhooks_table ............................ [1] Ran  
  2023_07_13_120721_add_license_to_instance_settings ................. [1] Ran  
  2023_07_27_182013_smtp_discord_schemaless_to_normal ................ [1] Ran  
  2023_08_06_142951_add_description_field_to_applications_table ...... [1] Ran  
  2023_08_06_142952_remove_foreignId_environment_variables ........... [1] Ran  
  2023_08_06_142954_add_readonly_localpersistentvolumes .............. [1] Ran  
  2023_08_07_073651_create_s3_storages_table ......................... [1] Ran  
  2023_08_07_142950_create_standalone_postgresqls_table .............. [1] Ran  
  2023_08_08_150103_create_scheduled_database_backups_table .......... [1] Ran  
  2023_08_10_113306_create_scheduled_database_backup_executions_table  [1] Ran  
  2023_08_10_201311_add_backup_notifications_to_teams ................ [1] Ran  
  2023_08_11_190528_add_dockerfile_to_applications_table ............. [1] Ran  
  2023_08_15_095902_create_waitlists_table ........................... [1] Ran  
  2023_08_15_111125_update_users_table ............................... [1] Ran  
  2023_08_15_111126_update_servers_add_unreachable_count_table ....... [1] Ran  
  2023_08_22_071048_add_boarding_to_teams ............................ [1] Ran  
  2023_08_22_071049_update_webhooks_type ............................. [1] Ran  
  2023_08_22_071050_update_subscriptions_stripe ...................... [1] Ran  
  2023_08_22_071051_add_stripe_plan_to_subscriptions ................. [1] Ran  
  2023_08_22_071052_add_resend_as_email .............................. [1] Ran  
  2023_08_22_071053_add_resend_as_email_to_teams ..................... [1] Ran  
  2023_08_22_071054_add_stripe_reasons ............................... [1] Ran  
  2023_08_22_071055_add_discord_notifications_to_teams ............... [1] Ran  
  2023_08_22_071056_update_telegram_notifications .................... [1] Ran  
  2023_08_22_071057_add_nixpkgsarchive_to_applications ............... [1] Ran  
  2023_08_22_071058_add_nixpkgsarchive_to_applications_remove ........ [1] Ran  
  2023_08_22_071059_add_stripe_trial_ended ........................... [1] Ran  
  2023_08_22_071060_change_invitation_link_length .................... [1] Ran  
  2023_09_20_082541_update_services_table ............................ [2] Ran  
  2023_09_20_082733_create_service_databases_table ................... [2] Ran  
  2023_09_20_082737_create_service_applications_table ................ [2] Ran  
  2023_09_20_083549_update_environment_variables_table ............... [2] Ran  
  2023_09_22_185356_create_local_file_volumes_table .................. [2] Ran  
  2023_09_23_111808_update_servers_with_cloudflared .................. [2] Ran  
  2023_09_23_111809_remove_destination_from_services_table ........... [3] Ran  
  2023_09_23_111811_update_service_applications_table ................ [3] Ran  
  2023_09_23_111812_update_service_databases_table ................... [3] Ran  
  2023_09_23_111813_update_users_databases_table ..................... [4] Ran  
  2023_09_23_111814_update_local_file_volumes_table .................. [4] Ran  
  2023_09_23_111815_add_healthcheck_disable_to_apps_table ............ [5] Ran  
`

**Comment by andrasbacsai** [comment]
Yes. You used a development version. Please stop using it (turn it off in the `Settings` menu).

You need to revert some of the migrations manually. This will remove a few things (especially services) from your database!

To rollback: `docker exec coolify bash -c "php artisan migrate:rollback --step 6"`
You are removing the last 6 migrations.

The manually apply migrations: `docker exec coolify bash -c "php artisan migrate --step"`

Let me know if it works afterward.

**Comment by ashermyers** [comment]
Failed to run migrate:rollback with this error:
`   INFO  Rolling back migrations.  

  2023_09_23_111815_add_healthcheck_disable_to_apps_table .......... 13ms DONE
  2023_09_23_111814_update_local_file_volumes_table ................. 5ms DONE
  2023_09_23_111813_update_users_databases_table .................... 5ms DONE
  2023_09_23_111812_update_service_databases_table .................. 4ms FAIL

In Connection.php line 801:
                                                                               
  SQLSTATE[42703]: Undefined column: 7 ERROR:  column "exclude_from_status" o  
  f relation "service_databases" does not exist (Connection: pgsql, SQL: alte  
  r table "service_databases" drop column "exclude_from_status")               
                                                                               

In Connection.php line 580:
                                                                               
  SQLSTATE[42703]: Undefined column: 7 ERROR:  column "exclude_from_status" o  
  f relation "service_databases" does not exist                                
                                                                               
`

**Comment by raphaelbernhart** [comment]
The error is still happening for me. When adding a service application or docker compose app: [image](https://github.com/user-attachments/assets/6279120f-375c-4e9a-8c4e-5f1ec47d44e8)
