### ISSUE TITLE
[Bug]: Image not loading in Coolify for Next.js repository

### ISSUE THREAD

**Issue by deployn** [coollabsio/coolify#1267]
### Description

I have a Next.js repository that includes an image located within the assets folder. I am using next/image to load this image into my page. When I locally run `npm run build` and `npm run start`, everything works fine. However, when I deploy the application to Coolify, the image does not load. 

This issue was already present in Coolify v3, where there was a log message indicating “SSL wrong version” (or something similar). In Coolify v4, I cannot find the log (or it may no longer exist), but the problem persists.

### Minimal Reproduction (if possible, example repository)

1. Install Coolify
2. Deploy [this repository](https://github.com/deployn/coolify-test)
3. Add a domain

### Exception or Error

Error log from version 3:

```bash
Error:C0874A89BF7F0000:error:0A000010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ss...
[...] library: "SSL routines",
[...] reason: "wrong version number",
[...] code: "ERR_SSL_WRONG_VERSION_NUMBER"
[...]
```

### Version

4.0.0-beta.50

**Comment by andrasbacsai** [comment]
I could not reproduce the issue.

What configuration are you set in Coolify for this repository? Should it be a static site?

**Comment by deployn** [comment]
Not a static site. The image loads when I don't use my domain, but a http connection. With a https connection the mentioned error is there.

![configuration](https://github.com/coollabsio/coolify/assets/54767886/03cba537-a59a-40f1-a23f-4db475034750)

**Comment by andrasbacsai** [comment]
I can reproduce it now. Thanks! I will take a look.

**Comment by andrasbacsai** [comment]
It looks like it is not specific to Coolify. Can you please try to downgrade to `13.5.2` and try it?

https://github.com/vercel/next.js/issues/56038

**Comment by deployn** [comment]
Thank you, I'm sorry for the wrong report.
