### ISSUE TITLE
[Bug]: Unable to load a public repository without main branch

### ISSUE THREAD

**Issue by deployn** [coollabsio/coolify#1268]
### Description

When attempting to load a public repository that does not have a main branch, no branch can be found.
When attempting to load a private repository that does not have a main branch, the selection defaults to “main” under the source tab, even if a different branch is chosen initially. 

### Minimal Reproduction (if possible, example repository)

1. Navigate to the repository page of a public repository without a main branch.
2. [Example repository](https://github.com/deployn/coolify-test)
3. Try to deploy it.
[or]
1. Navigate to the repository page of a private repository without a main branch.
2. You can fork this [example repository](https://github.com/deployn/coolify-test)
3. The correct branch is detected.
4. Try to deploy it.
5. Click on the “source” tab.
6. Observe that the selection reverts back to “main” upon initiation.

### Exception or Error

```
Failed to get data from Public GitHub with error:
Branch not found
```

### Version

v4.0.0-beta.50

**Comment by deployn** [comment]
@maige-bot: Could you add the v4 label?

**Comment by andrasbacsai** [comment]
Thanks for the issue! It is caused by not having a `main` branch, but the older `master`. The next version will fix it!

**Comment by deployn** [comment]
I have noticed that the issue still persists in version v4.0.0-beta.53. It is still not possible to deploy a public repository without a main branch. Settings under "Source" are being ignored.
