### ISSUE TITLE
[Bug]: Unable to revert to an older commit

### ISSUE THREAD

**Issue by deployn** [coollabsio/coolify#1270]
### Description

When attempting to revert to an older commit by specifying the commit SHA under the “Source” section, the system ignores the input and reverts to the HEAD commit instead.

### Minimal Reproduction (if possible, example repository)

1. Deploy a repository
2. Click on the "Source" tab.
3. Enter a specific commit SHA in the designated field.
4. Click on "Save"
5. Click on "Advanced --> Force deploy"

Example: [This repository](https://github.com/deployn/coolify-test/commits/master), commit SHA 77ad30400804c2639c336aba78ef377ae4b819dc

#### Expected behavior
The system should revert to the specified commit based on the provided SHA.

#### Actual behavior
The system ignores the entered commit SHA and reverts to the HEAD commit instead.

### Version

v4.0.0-beta.50

**Comment by andrasbacsai** [comment]
Thanks for the report. The next release will have a fix for this.
