### ISSUE TITLE
[Bug]: Unique violation: 7 ERROR: duplicate key value violates unique constraint DETAIL: key already exist

### ISSUE THREAD

**Issue by lethanhviet** [coollabsio/coolify#1283]
### Description

When adding a FQDN to a new service, however this domain name has already been added to a service before and deleted already.
The domain key however is still saved in the database of Coolify even after service has been deleted.

### Minimal Reproduction (if possible, example repository)

Create a service with a FQDN, delete the service, and then re-create a new package with the same FQDN.

### Version

v4.0.0-beta.62

**Comment by andrasbacsai** [comment]
Can you pleas try to delete the stuck service with [this](https://coolify.io/docs/commands#delete-resource)? Does it show you that service?

**Comment by lethanhviet** [comment]
Hi,

Thank you so much. After running docker exec -ti coolify bash -c "php artisan resources:delete" and remove the service resouce, it works now.
