### ISSUE TITLE
[Bug]: Can't have multiple projects with an empty domain

### ISSUE THREAD

**Issue by watzon** [coollabsio/coolify#1294]
### Description

The domain field appears to have a unique constraint attached to it, so you can have one project with an empty domain, but not two.

### Minimal Reproduction (if possible, example repository)

Create two projects, each with no domain. The second will not save.

### Exception or Error

![image](https://github.com/coollabsio/coolify/assets/4535422/7a72ba4b-6a4d-46aa-a80a-92be248b7333)

### Version

v4.0.0-beta.69

**Comment by andrasbacsai** [comment]
Oops. It will be fixed in the upcoming version.
