### ISSUE TITLE
[Bug]: Dockerfile port expose getting bad gateway error

### ISSUE THREAD

**Issue by anderson-ipdv** [coollabsio/coolify#1301]
### Description

First of all, I'dont know if it is a bug or a misconfiguration. 
I have a docker file that expose the port 8500 I also mapped this port to 8500

When I access it using the ip address wit works fine, but with the domain I got bad gateway error.

![CleanShot 2023-10-10 at 17 15 36@2x](https://github.com/coollabsio/coolify/assets/102538149/44c7d392-dccb-429a-aecc-5488e9bda716)
![CleanShot 2023-10-10 at 17 19 29@2x](https://github.com/coollabsio/coolify/assets/102538149/f60af68d-1e75-4405-80fc-38703901c942)
![CleanShot 2023-10-10 at 17 19 44@2x](https://github.com/coollabsio/coolify/assets/102538149/01771c47-fbfb-4e2c-bbeb-80cd0635b1f8)

### Minimal Reproduction (if possible, example repository)

My docker file:

FROM adobecoldfusion/coldfusion2023:latest
EXPOSE 8500 

### Exception or Error

Bad Gateway

### Version

v4.0.0-beta.73

**Comment by andrasbacsai** [comment]
Thanks for the issue! I can reproduce it and fix it in the next version.

(Node: this ColdFusion image is starting very slow, more than 2 minutes. Until it starts, the bad gateway will be shown.)
