### ISSUE TITLE
[Bug]: Subdomains for app doesn't work, while Coolify instance domain does

### ISSUE THREAD

**Issue by DevHusariaSolutions** [coollabsio/coolify#1309]
### Description

Traefik configuration doesn't allow for subdomain usage

### Minimal Reproduction (if possible, example repository)

Let's assume we own domain **xyz.com**
If I would set up this domain in Coolify settings and add DNS record pointing to my machine IP address - everything will work.
I'm using Cloudflare and both "Full" and "Full (Strict)" modes work for me.
Then I create web service. Automatically generated domain (http slip io ) works, I can connect to that.
Then I change to **api.xyz.com** and also add new DNS record for it.
I cannot connect to service.
I gets "404 page not found" on "Full" mode and 526 on "Full (Strict)".

What I've checked as possible source of problem:
Inside /data/coolify/proxy there is acme.json file, it does contain our **xyz.com**, but not **api.xyz.com**

### Version

4.0.0 beta 96

**Comment by andrasbacsai** [comment]
I try to reproduce it.

Are you sure about the beta version?

**Comment by m4rvr** [comment]
I also get 404 when pointing an A record to the IP, generated domain works. Domain is registered with Cloudflare and has a CF pages app deployed on the root domain example.com. Latest beta (installed a few hours ago)

**Comment by DevHusariaSolutions** [comment]
I'm sure about the beta version.
I've seen some Discord posts related to similar issues already. People were pointing on CORS / 404 errors mostly, but I guess it's related to that.

I've tried manually updating acme.json. First attempt and proxy restart gave no visible change, but after night I've realized that I broke Coolify instance domain ( our xyz.com ) because of that and now I gets also 526 status for that domain, so this file need to have some impact on the case.

**Comment by m4rvr** [comment]
> I'm sure about the beta version. I've seen some Discord posts related to similar issues already. People were pointing on CORS / 404 errors mostly, but I guess it's related to that.
> 
> I've tried manually updating acme.json. First attempt and proxy restart gave no visible change, but after night I've realized that I broke Coolify instance domain ( our xyz.com ) because of that and now I gets also 526 status for that domain, so this file need to have some impact on the case.

Beta version 96 doesn't exist though 😁 Latest is 81

**Comment by andrasbacsai** [comment]
> Then I create web service.

Which service exactly? An application, or a complex service (based on a compose file), or a one-click service?

I'm trying to reproduce it, but I cannot.

**Comment by m4rvr** [comment]
@andrasbacsai My project is a pnpm monorepo, loaded from git with nixpacks (if that helps).
Is this A record correct or do I need to set it to the root in the "name" column?
![CleanShot 2023-10-13 at 10 20 50@2x](https://github.com/coollabsio/coolify/assets/6840287/025fd512-1191-4e8d-8215-58888dae28b8)

I want to point https://api.example.com to the app

**Comment by andrasbacsai** [comment]
> @andrasbacsai My project is a pnpm monorepo (nodejs api in packages/api), loaded from git with nixpacks (if that helps). Is this A record correct or do I need to set it to the root in the "name" column? ![CleanShot 2023-10-13 at 10 20 50@2x](https://user-images.githubusercontent.com/6840287/274841605-025fd512-1191-4e8d-8215-58888dae28b8.png)
> 
> I want to point https://api.example.com to the app

It looks good. 

You have two options with this configuration (orange cloud on):
1. Set http://api.example.com in Coolify and set Flexible in Cloudflare SSL/TLS configuration.
2. Set https://api.example.com in Coolify and set Full in Cloudflare SSL/TLS configuration.

Don't forget, if you change the domain in Coolify, you need to redeploy. It is not dynamically changed.

Neither work?

**Comment by m4rvr** [comment]
> > @andrasbacsai My project is a pnpm monorepo (nodejs api in packages/api), loaded from git with nixpacks (if that helps). Is this A record correct or do I need to set it to the root in the "name" column? ![CleanShot 2023-10-13 at 10 20 50@2x](https://user-images.githubusercontent.com/6840287/274841605-025fd512-1191-4e8d-8215-58888dae28b8.png)
> > I want to point https://api.example.com to the app
> 
> It looks good.
> 
> You have two options with this configuration (orange cloud on):
> 
> 1. Set http://api.example.com in Coolify and set Flexible in Cloudflare SSL/TLS configuration.
> 2. Set https://api.example.com in Coolify and set Full in Cloudflare SSL/TLS configuration.
> 
> Don't forget, if you change the domain in Coolify, you need to redeploy. It is not dynamically changed.
> 
> Neither work?

Thanks, it works now! I missed to set SSL/TLS to "Full" and probably also forgot to redeploy, lol. 🙏

**Comment by DevHusariaSolutions** [comment]
It was 69, not 96, right.
I will check such stuff.
Maybe some notification would be useful like "You changed domain, redeploy for apply change"?

**Comment by DevHusariaSolutions** [comment]
Tested correctly.

What worked:
- Cloudflare has to be set up on Strict (but not Strict (full) because it will throw 526, since letsencrypt acme is created for Coolify instance domain only)
- redeployed service after domain change

I guess it would be really good to add notification mentioned above and also maybe extend popover info showed when mouse is over domain field in settings of service.

Thanks for answers and wish You all good in this project

**Comment by AlejandroAkbal** [comment]
Thank you @DevHusariaSolutions, 

I have been trying for 3 days to deploy my website correctly but couldn't

Here are my steps if you are seeing SSL 526 errors on Cloudflare with Coolify

Restore the default proxy config, redeploy website with correct subdomain set, disable Cloudflare strict, reach the website, and then enable Cloudflare strict
