### ISSUE TITLE
[Bug]: Service, Ghost - Multiple Domains as comma separated doesn't work.

### ISSUE THREAD

**Issue by koch-crsd** [coollabsio/coolify#1311]
### Description

Setting multiple domains on the Ghost Service, it isn't reachable (Even the Service seems to start/deploy fine)...

But opening up one of the defined domains (pointing correctly to the system) gets a 404 not found...

<img width="1535" alt="Bildschirmfoto 2023-10-12 um 11 54 35" src="https://github.com/coollabsio/coolify/assets/47377645/31385b74-6308-4588-925c-5bc94b214900">

removing the second defined domain and just leaving the first one and re-start works just fine... then its reachable via the set up domain...

thanks much for clarifying/fixing :)

### Minimal Reproduction (if possible, example repository)

See description.

### Exception or Error

no error in the logs.

### Version

v4.0.0-beta.80

**Comment by andrasbacsai** [comment]
Yes, Ghost as a service does not allow to configure multiple hostnames, so it won't work.
