### ISSUE TITLE
[4.0.0] Able to backup service/docker-compose databases

### ISSUE THREAD

**Issue by andrasbacsai** [coollabsio/coolify#1316]
It should be done in the same way as currently done for Postgresql.

**Comment by andrasbacsai** [comment]
It is already available.

**Comment by abanobboles** [comment]
Hello, how is this possible. I am trying to backup my Supabase postgress db from the UI in Settings section, but I can't find a way!

Maybe you have a hint? @andrasbacsai 

thank you!
