### ISSUE TITLE
[4.0.0] Databases

### ISSUE THREAD

**Issue by andrasbacsai** [coollabsio/coolify#1319]
Able to deploy & make automated backups of the following databases:
- MongoDB
- MySQL/MariaDB
- Cassandra (will come later)

**Comment by xoose** [comment]
+ PostgreSQL

**Comment by andrasbacsai** [comment]
> + PostgreSQL

It is already in v4 + Redis.

**Comment by cfragkos** [comment]
mysql backup has this issue
`Database: default
Status: failed
Started At: 2024-01-07 00:18:15
Message: mysqldump: [Warning] Using a password on the command line interface can be insecure. mysqldump: Got error: 2002: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) when trying to connect
Size: 0 B / 0 kB / 0 MB
Location: N/A`
