### ISSUE TITLE
[Bug]: v4 update stop at beta.71

### ISSUE THREAD

**Issue by lethanhviet** [coollabsio/coolify#1325]
### Description

https://[cdn.coollabs.io/coolify/versions.json](https://cdn.coollabs.io/coolify/versions.json) is still at beta.71, is this intentional?

### Minimal Reproduction (if possible, example repository)

n/a

### Version

v4.0.0-beta.71

**Comment by andrasbacsai** [comment]
Probably that is because of some caching issues. It is currently in beta.86.

**Comment by andrasbacsai** [comment]
It was a temporary issue. If not, please reopen this.

**Comment by m4rvr** [comment]
I have the same issue, my version is stuck at `beta.69`. When running `curl -fsSL https://cdn.coollabs.io/coolify/versions.json`, it shows the `beta.69` version as latest. Running `curl` outside the server (local terminal) shows the latest `beta.88` version.

Sending `no-cache` header also doesn't work. Is there anything I can do to force load a version?

**Comment by andrasbacsai** [comment]
I purged the CDN urls manually. Can you check now? 

Also please try the original URL: https://coolcdn.b-cdn.net/coolify/versions.json

Let me know the outcome!

**Comment by m4rvr** [comment]
> I purged the CDN urls manually. Can you check now?
> 
> Also please try the original URL: https://coolcdn.b-cdn.net/coolify/versions.json
> 
> Let me know the outcome!

Same issue, both URLs still show `beta.69` as latest version when curl'ing on the server. 
@lethanhviet Do you still have the same problem?

**Comment by andrasbacsai** [comment]
> > I purged the CDN urls manually. Can you check now?
> > Also please try the original URL: https://coolcdn.b-cdn.net/coolify/versions.json
> > Let me know the outcome!
> 
> Same issue, both URLs still show `beta.69` as latest version when curl'ing on the server. @lethanhviet Do you still have the same problem?

Which server provider are you using? They probably have some kind of HTTP cache proxy configured. :/

**Comment by m4rvr** [comment]
> > > I purged the CDN urls manually. Can you check now?
> > > Also please try the original URL: https://coolcdn.b-cdn.net/coolify/versions.json
> > > Let me know the outcome!
> > 
> > 
> > Same issue, both URLs still show `beta.69` as latest version when curl'ing on the server. @lethanhviet Do you still have the same problem?
> 
> Which server provider are you using? They probably have some kind of HTTP cache proxy configured. :/

It's a CPX21 Hetzner cloud server

**Comment by andrasbacsai** [comment]
> > > > I purged the CDN urls manually. Can you check now?
> > > > Also please try the original URL: https://coolcdn.b-cdn.net/coolify/versions.json
> > > > Let me know the outcome!
> > > 
> > > 
> > > Same issue, both URLs still show `beta.69` as latest version when curl'ing on the server. @lethanhviet Do you still have the same problem?
> > 
> > 
> > Which server provider are you using? They probably have some kind of HTTP cache proxy configured. :/
> 
> It's a CPX21 Hetzner cloud server

I have the same server. Hmm.

What if you try `https://raw.githubusercontent.com/coollabsio/coolify/main/versions.json`?

**Comment by m4rvr** [comment]
> > > > > I purged the CDN urls manually. Can you check now?
> > > > > Also please try the original URL: https://coolcdn.b-cdn.net/coolify/versions.json
> > > > > Let me know the outcome!
> > > > 
> > > > 
> > > > Same issue, both URLs still show `beta.69` as latest version when curl'ing on the server. @lethanhviet Do you still have the same problem?
> > > 
> > > 
> > > Which server provider are you using? They probably have some kind of HTTP cache proxy configured. :/
> > 
> > 
> > It's a CPX21 Hetzner cloud server
> 
> I have the same server. Hmm.
> 
> What if you try `https://raw.githubusercontent.com/coollabsio/coolify/main/versions.json`?

That URL shows the correct version (beta 92) 😅

**Comment by andrasbacsai** [comment]
No. 😮
