### ISSUE TITLE
[Bug]: docker pull from custom registry failed

### ISSUE THREAD

**Issue by nowanti** [coollabsio/coolify#1328]
### Description

I have manually executed docker login on the host ahead of time, and manually tested pull to make sure that I am logged in and that the image exists.

### Minimal Reproduction (if possible, example repository)

- docker login custom registry
- deploy the service using the images in the registry

### Exception or Error

[2023-Oct-13 05:54:40.894658] sk4o40k-055432141935 Pulling
sk4o40k-055432141935 Error
Error response from daemon: pull access denied for registry.cn-shanghai.aliyuncs.com/xxx/xxx-client, repository does not exist or may require docker login: denied: requested access to the resource is denied

### Version

v4.0.0-beta.86

**Comment by andrasbacsai** [comment]
UI-based docker login is not yet available (as in v3), but I make this feature available in the next version.

If you login to a custom registry on the server for same user (root) as configured in Coolify, it will use those credentials during deployment.
