### ISSUE TITLE
[Bug]: Failed to pull image and Git

### ISSUE THREAD

**Issue by nowanti** [coollabsio/coolify#1340]
### Description

Due to some irresistible reasons, my area can not normally access ghcr.io and GitHub. So I encountered a lot of trouble in the process of using Coolify: installing, downloading the assistant image, pulling out the GitHub code
I can use the proxy to some extent, but I can't inject it into Coolify. I hope the author can provide the option of customizing the agent in these steps.
Installation: custom cURL agent, custom docking station repository
Download Container Image: custom docking Repository
Pull Git code: customize the proxy of the execution container (using the-e parameter of docker run), and support other git app (such as gitea)

### Minimal Reproduction (if possible, example repository)

- pull github codes from hosts in areas where github and ghcr cannot be accessed properly

### Exception or Error

When I pull the Docker image:
unable to pull from ghcr.io/coollabsio/coolify-helper:latest
（Temporarily resolved by setting up a dockerd agent on the host）

When I pull the Git code:
fatal: unable to access https://github.com/****/client-web.git/: Failure when receiving data from the peer

### Version

v4.0.0-beta.92

**Comment by nowanti** [comment]
> OUTPUT:
#8 648.5 warning: error: unable to download 'https://cache.nixos.org/nix-cache-info': Timeout was reached (28); retrying in 577 ms

There is an urgent need to inject agents into all aspects of deployment

**Comment by andrasbacsai** [comment]
I don't know how to solve this on my side. I cannot make it available somewhere else because what if that is blocked as well?

It would be best to use an HTTP proxy on your server to reach ghcr.io/Dockerhub/Github/Nixos/etc.

**Comment by nowanti** [comment]
> I don't know how to solve this on my side. I cannot make it available somewhere else because what if that is blocked as well?
> 
> It would be best to use an HTTP proxy on your server to reach ghcr.io/Dockerhub/Github/Nixos/etc.

I have solved the problem with docker pull by setting up a proxy for dockerd on the host.
But the pull code in the deployment phase seems to be executed in a separate container, and I can't inject proxy into it, so I need your side to provide a way for me to pass the agent.
If you create a container manually, it can be passed through environment variables, but your process of pulling the code seems impossible.
