### ISSUE TITLE
[Bug]: Postgres Is not working

### ISSUE THREAD

**Issue by scshiv29-dev** [coollabsio/coolify#1346]
### Description

I start a new postgresdb in v4 it is giving FATAL: role "root" does not exist after starting 
<img width="827" alt="image" src="https://github.com/coollabsio/coolify/assets/68141773/847828dd-d2b5-4829-84b3-8121c128efee">

### Minimal Reproduction (if possible, example repository)

Start a new instance of coolify 
Try starting a postgres container

### Version

v4

**Comment by andrasbacsai** [comment]
It is done by the healthcheck. I will fix it in the next version.

This does not prevent you from using PostgreSQL. Everything should work.

**Comment by andrasbacsai** [comment]
More info: https://stackoverflow.com/questions/60193781/postgres-with-docker-compose-gives-fatal-role-root-does-not-exist-error/60194261#60194261
