### ISSUE TITLE
[Bug]: Servers aren't being shared across teams

### ISSUE THREAD

**Issue by ashermyers** [coollabsio/coolify#1348]
### Description

Whenever I create a team and add a server to that team, other users on that team cannot access the server I created.

### Minimal Reproduction (if possible, example repository)

Create a server for a team and then login to a different team user.

### Version

v4.0.0-beta.96

**Comment by andrasbacsai** [comment]
Can you please show me an example? I cannot replicate the issue.

Have you switched to the right team? Each user has a personal team (created by default with the user) and all other teams that it created/invited to. If you log in, you are seeing the personal team, and you need to switch to the right team in the `Team` menu.

**Comment by bitnom** [comment]
> Can you please show me an example? I cannot replicate the issue.
> 
> Have you switched to the right team? Each user has a personal team (created by default with the user) and all other teams that it created/invited to. If you log in, you are seeing the personal team, and you need to switch to the right team in the `Team` menu.

I don't think that was the question being asked. Let's say I have 2 teams: `teamA` & `teamB`, and I have 1 server `server-1`. Why can't teamA and teamB both have access to server-1?
