### ISSUE TITLE
[Bug]: Uncaught TypeError: Cannot read properties of undefined (reading 'writeText')

### ISSUE THREAD

**Issue by ashermyers** [coollabsio/coolify#1349]
### Description

Uncaught TypeError: Cannot read properties of undefined (reading 'writeText') when trying to invite a user to a team and copy the invite link.

### Minimal Reproduction (if possible, example repository)

Try to invite a user to a team and copy the invite link.

### Exception or Error

Uncaught TypeError: Cannot read properties of undefined (reading 'writeText')

### Version

v4.0.0-beta.97

**Comment by andrasbacsai** [comment]
Fixing in the next version.
