### ISSUE TITLE
[Bugfix] Wrong SSL certificate issued

### ISSUE THREAD

**Issue by SaraVieira** [coollabsio/coolify#135]
After making a deployment I noticed that there was an issue with the SSL certificate as it's invalid and marked for another domain

Any way I can reissue the certificate?

<img width="1904" alt="CleanShot 2022-02-15 at 11 59 24@2x" src="https://user-images.githubusercontent.com/1051509/154048831-3199877a-6fe8-4a7c-9d16-01ca8530fd7e.png">

**Comment by andrasbacsai** [comment]
Fixed in #137 .
