### ISSUE TITLE
[Bug]: Resource limits does not work with pm2

### ISSUE THREAD

**Issue by unpseudocomplique** [coollabsio/coolify#1354]
### Description

Setup thoses limits :
![image](https://github.com/coollabsio/coolify/assets/69119668/72b52328-4d56-42a6-ae5f-f1f6aabb3e1e)

pm2 is still able to start on multiples process

![image](https://github.com/coollabsio/coolify/assets/69119668/67e2a0ca-b20b-4c6b-a778-f791eba142a1)

If i'm not wrong issue here is that we should be able to set max core usage ?

### Minimal Reproduction (if possible, example repository)

![image](https://github.com/coollabsio/coolify/assets/69119668/1b3df829-26a7-4bde-b6f5-84f5882a8d8a)
my start script 

### Version

beta 98

**Comment by andrasbacsai** [comment]
As I see, it is a known [issue](https://github.com/Unitech/pm2/issues/4347). However, the maximum CPU limit (actual CPU usage) will be limited by Docker; PM2 sees it differently.
