### ISSUE TITLE
[Bug]: Connection to mongodb

### ISSUE THREAD

**Issue by unpseudocomplique** [coollabsio/coolify#1355]
### Description

setting up initial username and password does not work when connecting from node app.

mongodb://[Initial Username]:[Initial Password]@[containerId]:27017/[Initial Database]?directConnection=true

### Minimal Reproduction (if possible, example repository)

To make it work, used studio 3t connected with Initial Username &  Initial Password working fine.

There is no Initial Database with the name filled so i have to create the db and add user with correct access policy to this db.
After that everything is looking good!

### Version

beta 98

**Comment by unpseudocomplique** [comment]
[update]
Might be related : 
![image](https://github.com/coollabsio/coolify/assets/69119668/b64cff26-feae-4412-bf31-ee16d6c7bd76)

Can't backup mongodb

**Comment by andrasbacsai** [comment]
The initial db creation is fixed in the next version.

I cannot replicate the backup issue.

**Comment by unpseudocomplique** [comment]
Ty will try later but at least i confirm that the backup now work 🤣 (maybe the issue was linked ?)

We need a download button to download the archive easily and a confirm button on the deletion to not doing shit ^^

**Comment by andrasbacsai** [comment]
Confirm button added. Dowload is still wip.

**Comment by andrasbacsai** [comment]
Added in the next version.

**Comment by unpseudocomplique** [comment]
Thanks!
