### ISSUE TITLE
[Feature request] Be able to add different secrets to PR/MR builds

### ISSUE THREAD

**Issue by andrasbacsai** [coollabsio/coolify#136]
[Discussion / use case.](https://discord.com/channels/459365938081431553/877863871753355264/943125510232375296)

Requirements:
- Be able to save secrets for PR/MR.
- Be able to read and set secrets during PR/MR webhooks.
- Secrets should be merged with the main application secrets, so you only need to set the differences for PR/MRs.

**Comment by akoenig** [comment]
Just tested it, @andrasbacsai. It works like a charm. Thanks a lot for bringing this feature to life 🚀
