### ISSUE TITLE
[Bug]: Installation Failed

### ISSUE THREAD

**Issue by sharukhkhanajm** [coollabsio/coolify#1375]
### Description

This is the error I am getting when I run the installation command on the fresh droplet.

<img width="1008" alt="image" src="https://github.com/coollabsio/coolify/assets/47321682/ab9359a6-b166-45bf-82e2-11562bc20278">

When rerunning the command a second time I get this error.

<img width="1015" alt="image" src="https://github.com/coollabsio/coolify/assets/47321682/4a04f2ae-481f-451b-bcf2-e4b3546d2c04">

### Minimal Reproduction (if possible, example repository)

Just create a new droplet and run the installation command.
I have tried it multiple times and got the same error.

### Version

4.0.0-beta.108

**Comment by sharukhkhanajm** [comment]
Update 1:
I had to install docker manually and it started working successfully.

link: https://docs.docker.com/engine/install/ubuntu/

**Comment by andrasbacsai** [comment]
What OS/Version are you using? It looks like the docker installer does not support it.

**Comment by sharukhkhanajm** [comment]
I was creating a droplet on digitalocean
OS: Ubuntu 23.10 x64


<img width="912" alt="image" src="https://github.com/coollabsio/coolify/assets/47321682/7572ebea-221d-4842-8b2e-eb5fe531652b">

**Comment by andrasbacsai** [comment]
It looks like something has changed in Ubuntu 23. I will check it.

**Comment by andrasbacsai** [comment]
I've made an update to the installation script, that it will fail properly if it cannot install Docker automatically.

Currently, 23.10 is not supported by Docker, so manual installation is required.

![image](https://github.com/coollabsio/coolify/assets/5845193/d027bfbb-d47e-47cf-9a44-07bf938bf236)
