### ISSUE TITLE
[Bug]: docker compose Environment Variables dev view is not working

### ISSUE THREAD

**Issue by Wolframko** [coollabsio/coolify#1378]
### Description

![image](https://github.com/coollabsio/coolify/assets/34187970/1fb7c6d4-80ca-43cd-9591-0ab7099734a1)
Error when trying to save env vars

### Minimal Reproduction (if possible, example repository)

Create any docker compose service, open Environment Variables in dev view and save it.

### Exception or Error

Error 500 Error: Call to undefined method App\Models\Service::environment_variables_preview()

### Version

v4.0.0-beta.108

**Comment by andrasbacsai** [comment]
Oh, nice catch! Fixing in the next version.
