### ISSUE TITLE
[Bug]: Install script fails on Ubuntu 23.10

### ISSUE THREAD

**Issue by r-o-b-b-y** [coollabsio/coolify#1379]
### Description

# Install script fails on Ubuntu 23.10 

Error Message:

```
ERROR: '24.0.2' not found amongst apt-cache madison results
The error message suggests that the Docker version '24.0.2' is not available in the repository list returned by 'apt-cache madison docker-ce'.
```

This is due to an error in `https://releases.rancher.com/install-docker/24.0.sh` - when this error happens, the coolify install script swallows it and continues.

To remedy, assuming version `24.0` for now, `wget https://releases.rancher.com/install-docker/24.0.sh` change line 88:

```diff
-VERSION="24.0.2"
+VERSION="24.0.7"
```
This `24.0.7` is discovered by running `apt-cache madison docker-ce`
which outputs
 `docker-ce | 5:24.0.7-1~ubuntu.23.10~mantic | https://download.docker.com/linux/ubuntu mantic/stable amd64 Packages`

This error is also referenced here:
https://github.com/rancher/rancher/issues/38362

### Minimal Reproduction (if possible, example repository)

To reproduce run `curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash`

### Version

4

**Comment by andrasbacsai** [comment]
Thanks for the suggestions. I'm closing this issue for now. 

If you would like to help to improve Coolify, please reopen this issue with a PR.
