### ISSUE TITLE
[Bug]: Install script doesn't check if docker installation was indeed sucessful

### ISSUE THREAD

**Issue by krsilas** [coollabsio/coolify#1382]
### Description

I found a bug while running the Coolify installation script on an IP v6 only server. (I didn't know the implications of that at that time.) The script worked fine, but the curl to "releases.rancher.com" failed because the server doesn't support IP v6. 
The install script didn't handle this error and continued like nothing happened, printing "Docker installed successfully", even though that's not true. It took me a few minutes to notice that the script failed because the output suggested that everything was fine. 
I have to admit that this case is kinda unique and a mistake on my end but I assume it could also occur through other circumstances. I can create a pull request to make the DX better.

### Minimal Reproduction (if possible, example repository)

Run the install script on a server that for some reason fails to fetch the docker install script (network issue, firewall, dns misconfiguration, ...).

### Version

v4.0.0-beta.108

**Comment by andrasbacsai** [comment]
This can be closed. The PR merged, install script was updated.
