### ISSUE TITLE
[Bug]: Auto-deploy not working in v4 on Next.js app when pushing a git commit

### ISSUE THREAD

**Issue by deadcoder0904** [coollabsio/coolify#1387]
### Description

I faced this error recently with others:

![image](https://github.com/coollabsio/coolify/assets/16436270/5aef4fd7-b261-445e-b514-e19937a21f5e)

### Minimal Reproduction (if possible, example repository)

just push a git commit on new next.js app

### Exception or Error

no errors

### Version

v4.0.0-beta.108

**Comment by andrasbacsai** [comment]
Are you using GitHub App based deployment? If yes, please go the following view and click open your GitHub app:
![image](https://github.com/coollabsio/coolify/assets/5845193/5ba132a3-c4c9-418c-9e70-4835928e62f2)

Then `App Settings`:
![image](https://github.com/coollabsio/coolify/assets/5845193/964375a8-4889-4314-9a68-f13d0ca22dd4)

Then `Advanced`:
![image](https://github.com/coollabsio/coolify/assets/5845193/358ffa6c-221e-461b-a180-ce7a4526f3ec)
And please  show me the failed webhook's `Response` tab.

**Comment by deadcoder0904** [comment]
idk if its the failed webhook but this is the latest commit that did not get auto-deployed:

![image](https://github.com/coollabsio/coolify/assets/16436270/710d1420-9465-4741-9645-d70065a7c227)

**Comment by andrasbacsai** [comment]
Hm, `not cool` means the GitHub signature is not good, which means the webhook secret is wrong.

Open your GitHub App settings (the same way as you did), and go to the `General` tab. You will see on the bottom of the page a Webhook secret part. 

You can change it there. Save the new secret somewhere, go to Coolify/Sources, and update the GitHub App source with the new webhook secret. 

(There is a small bug on the UI - it will be fixed in the next version - after you save it, they will disappear, just do a refresh)

Let me know if it worked.

**Comment by deadcoder0904** [comment]
no, it isnt fixed.

when i paste into the webhook secret field, it stores it but when i click the `save` button, it makes the webhook field empty.

**Comment by andrasbacsai** [comment]
> no, it isnt fixed.
> 
> 
> 
> when i paste into the webhook secret field, it stores it but when i click the `save` button, it makes the webhook field empty.

Yes, that is fixed in the latest version.

If you resend the webhook, will it fail again?

**Comment by deadcoder0904** [comment]
> If you resend the webhook, will it fail again?

oh you mean by pushing a new git commit.

i did try that & it worked. now its auto-deploying.

im curious, how do i update coolify to the new version?

do i have to stop the server & re-install coolify & do the whole process again or there is an update script?

**Comment by ashermyers** [comment]
It has autoupdate it it is enabled in settings.. Otherwise an update button should show on the side bar.
