### ISSUE TITLE
[Bug]: Projects and resources are not deleted when deleting server

### ISSUE THREAD

**Issue by JoseSanchez54** [coollabsio/coolify#1394]
### Description

If you have a server created (in addition to the default server) and you have projects hosted on it, you can delete the server without deleting the projects or resources, this causes the screen to be bugged with resources that no longer exist and cannot be deleted either.
![image](https://github.com/coollabsio/coolify/assets/55786662/71ab2561-84f6-44cc-93cd-c856451db981)
![image](https://github.com/coollabsio/coolify/assets/55786662/6d6fad6d-5c60-4a5f-893b-2395558617b9)

### Minimal Reproduction (if possible, example repository)

Create a new server, add any resources, delete the created server

### Version

4.0.0-110

**Comment by andrasbacsai** [comment]
It will be fixed in the next version, + all dangling resources will be cleaned up.

**Comment by JoseSanchez54** [comment]
I have updated to beta 114 but I still have problems with containers that do not exist, they are still in the list and there is no way to delete them, nor can I find a way to delete the created projects

![image](https://github.com/coollabsio/coolify/assets/55786662/c92d152a-ae5d-4420-9365-34978d6b2625)


Greetings

**Comment by andrasbacsai** [comment]
Can you try to delete it with this command?

https://coolify.io/docs/commands#delete-resource

**Comment by JoseSanchez54** [comment]
I try remove it, but i dont know how to execute this command.

I try this
![image](https://github.com/coollabsio/coolify/assets/55786662/ee9db47a-e844-4ff9-aa64-de52a9c09d97)
