### ISSUE TITLE
[Bug]: Documentation link contains PHP code for service created from template

### ISSUE THREAD

**Issue by DevHusariaSolutions** [coollabsio/coolify#1397]
### Description

Wrong PHP code injection

### Minimal Reproduction (if possible, example repository)

1. Install Minio from template
2. Mouse over "Documentation" link on sidebar menu

### Exception or Error

![image](https://github.com/coollabsio/coolify/assets/89352849/30e7f228-0602-46c6-8f2d-168f20b54227)

### Version

v4.0.0-beta.110

**Comment by andrasbacsai** [comment]
I cannot reproduce it. If you do a refresh, are you still able to see this again?
