### ISSUE TITLE
[Bug]: Bad Credentials after update in MariaDb

### ISSUE THREAD

**Issue by JoseSanchez54** [coollabsio/coolify#1399]
### Description

After updating, the databases that I had from Maria DB have stopped working, in the logs I receive the error "Access denied for user 'root'", nothing has been changed in the configuration since its creation and now I cannot recover it .
The only thing that doesn't work is the Root user, when I use the normal user everything connects perfectly.
Could it be due to a name change of the root user?

![image](https://github.com/coollabsio/coolify/assets/55786662/1abdbde0-92a1-4a11-8782-22c1a97451e0)

### Minimal Reproduction (if possible, example repository)

I created the database, updated to version v4.0.0-beta.111, a little later I realized that the projects were starting to fail due to not being able to connect to this DB, so far I have only noticed it happening in MariaDB

### Exception or Error

"Access denied for user 'root'"

### Version

v4.0.0-beta.111

**Comment by andrasbacsai** [comment]
If you check the environment variables on the container `docker exec <containername> sh -c "env | grep MARIADB"`, do you see a different value in the `MARIADB_ROOT_PASSWORD` variable than on the frontend?
