### ISSUE TITLE
Help with Python implementation

### ISSUE THREAD

**Issue by pillows** [coollabsio/coolify#14]
Hi there,

I would like to help with the progress of this project by starting off with Python support. Hopefully someone can help with the question I have but, I was wondering what is the goto command for running a Python app? For me I usually have the Python app run on app.py but, that's not the case for all projects. I would like to know what the Python equivalent for a Python app would be and if there are any additional steps. For example, in https://github.com/coollabsio/coolify/blob/main/api/packs/nodejs/index.js#L24 the run command is "yarn start"

**Comment by andrasbacsai** [comment]
Hey,

First of all, thanks for the contribution! 

I have an idea of how to support Python. As I know - but my Python knowledge is not the best - it has no equivalent like for Node. 

So I would place another field on the frontend where you can set the main python script—no better idea atm.
I will implement such a thing!

**Comment by andrasbacsai** [comment]
Basic Python support landed in #49. 🎉 I will extend it later on with different application-specific deployments, like Django.
