### ISSUE TITLE
[Bug]: Clonning shouldn't start right away resources

### ISSUE THREAD

**Issue by unpseudocomplique** [coollabsio/coolify#1401]
### Description

As in the title, if resources are started as soon as created this will start them with wrong credential / env

Best exemple is that i clone a project where a mongodb resource is present. This init the new db with db name / credentials that i don't want.

### Minimal Reproduction (if possible, example repository)

Any with db

### Version

108

**Comment by andrasbacsai** [comment]
They are not started, only the status flag is not overwritten to exit. 

I fixed this issue in the recent version.

**Comment by unpseudocomplique** [comment]
Can't change initial username / password and dB name though
