### ISSUE TITLE
[Bug]: failed to register layer: unlinkat

### ISSUE THREAD

**Issue by mateit-cloudware** [coollabsio/coolify#1402]
### Description

Hi There, 
after fireing up the install script everything is working fine till the end. 
I receive the error: 
failed to register layer: unlinkat /usr/share/doc/adduser/examples/adduser.local.conf.examples: invalid argument

The installation cant be finished and I cant access the GUI.
Can you please help? 

### Minimal Reproduction (if possible, example repository)

just copy and paste the installation script and hit enter. Nothing more. 

### Version

4.0.0-beta.112

**Comment by swissbyte** [comment]
Do you run it within an lxc container? This usually happens if your run it within an u privileged lxc co tai er on proxmox with zfs as underlaying filesystem
