### ISSUE TITLE
[Bug]: Coolify V4 Double http protocol in container for the FQDN: http://https:// (Docker Compose)

### ISSUE THREAD

**Issue by ARHAEEM** [coollabsio/coolify#1403]
### Description

i've to use https:// this option is not available in coolify v4 so i need to enter https:// the problem is it will deliver it http:// which is not secure and not acceptable by services. now i need to add "s" after http but it's not possible. i believe it's a bug and it should have an urgent quick fix.

![image](https://github.com/coollabsio/coolify/assets/63544079/9d1bc455-5639-439a-bff5-f2f975320f1b)

i created a report post on N8N Community also https://community.n8n.io/t/telegram-trigger-bad-request-invalid-webhook-url-specified/32575 after long investigating i beleive this is the error who causing my problem with n8n. and waiting your confirmation that coolify v4 bug cause the problem. thanks in advance. 
Image

Why do I think it's a bug? In the FQDN field, the example shows that we should add "http://" or "https://" but when I add the Coolify system, it adds another "http://" which causes a double "http://". When I delete the "https://" from the FQDN field and add the hostname directly, it becomes "http://hostname/..." which is not secure (https://) and there's no way to update the "http://" that is added by default from the Coolify system.

![image](https://github.com/coollabsio/coolify/assets/63544079/cce74e81-fc63-4843-8fa6-8ba1728e451c)

For now i will try to move into docker container without docker compose because it's have SSL enable to force SSL until the bug fixed.

### Minimal Reproduction (if possible, example repository)

Docker Compose

### Version

v4.0.0-beta.112

**Comment by andrasbacsai** [comment]
The one-click template had an error, which I modified yesterday.

If you do not have any data yet in N8n, please create a new one, it will be good.
If you have data, please modify the compose file manually like this:
![image](https://github.com/coollabsio/coolify/assets/5845193/a6362292-f141-41ac-a183-68da46d07b9c)
![image](https://github.com/coollabsio/coolify/assets/5845193/26969eaf-5a95-4dc8-8000-e80b739d21ef)
The second line would be different (if I'm right).

Let me know if it worked out.

**Comment by ARHAEEM** [comment]
> The one-click template had an error, which I modified yesterday.
> 
> If you do not have any data yet in N8n, please create a new one, it will be good. If you have data, please modify the compose file manually like this: ![image](https://user-images.githubusercontent.com/5845193/281367568-a6362292-f141-41ac-a183-68da46d07b9c.png) ![image](https://user-images.githubusercontent.com/5845193/281367692-26969eaf-5a95-4dc8-8000-e80b739d21ef.png) The second line would be different (if I'm right).
> 
> Let me know if it worked out.

I've updated as mentioned. still getting the http:// protocol in logs. and the N8N does not work since my cloudflare force to route in https:// (SSL)
![image](https://github.com/coollabsio/coolify/assets/63544079/b6ee189e-cd3f-44f0-8634-0ae64622f5aa)

 also, when I tried to back to follow the logs I've got this error without able to enter the logs:
![image](https://github.com/coollabsio/coolify/assets/63544079/ebbf40a2-5c43-4116-a5ba-56750f00f827)

**Comment by ARHAEEM** [comment]
Update: The problem fixed by the changes you made after seperating both urls of app and FQDN.. 
I've changed the FQDN url to https:// and the application worked like charm even the N8N Webhook problem fixed...

The only problem we got now is the 500 error page when trying to see the N8N App Logs, but for now everything in front works, thanks. 
![image](https://github.com/coollabsio/coolify/assets/63544079/9e65b324-c713-492c-9c16-bd1d37945d44)

**Comment by andrasbacsai** [comment]
> Update: The problem fixed by the changes you made after seperating both urls of app and FQDN.. 
> 
> I've changed the FQDN url to https:// and the application worked like charm even the N8N Webhook problem fixed...
> 
> 
> 
> The only problem we got now is the 500 error page when trying to see the N8N App Logs, but for now everything in front works, thanks. 
> 
> ![image](https://github.com/coollabsio/coolify/assets/63544079/9e65b324-c713-492c-9c16-bd1d37945d44)
> 
> 

This is already fixed. Update your Coolify instance pls. 🙂
