### ISSUE TITLE
[Bug]: ENV Variables have no effect on nginx.template.conf

### ISSUE THREAD

**Issue by creazy231** [coollabsio/coolify#1404]
### Description

Even if the logs display `nixpacks build --cache-key zg4kcow -o /artifacts/j0o0oc8 --env NIXPACKS_PHP_ROOT_DIR=/app/public --no-error-without-start /artifacts/j0o0oc8`, variables like `NIXPACKS_PHP_ROOT_DIR` has no effect in view of changing the `nginx.template.conf`.
The workaround I used to make it work was creating a `nginx.template.conf` inside the root of my project and replacing the if statement around `root /app;` with a fixed `root /app/public;`

### Minimal Reproduction (if possible, example repository)

Try to deploy a fresh Laravel project using Nixpacks

### Version

v4.0.0-beta.112

**Comment by andrasbacsai** [comment]
Fixed in beta.113.
