### ISSUE TITLE
[Bug]: Repository URL is getting replaced

### ISSUE THREAD

**Issue by creazy231** [coollabsio/coolify#1405]
### Description

Since I hide the SSH port of my server and use `2222` instead, I have to change the repository url to something like `git@git.my-domain.com:2222/web/my-project.git`. This works but after every build it's getting set back to `git@git.my-domain.com:web/my-project.git` which causes the next build to fail.

### Minimal Reproduction (if possible, example repository)

Change your repository URL to `git@git.my-domain.com:2222/web/my-project.git` using SSH connection and start a build.

### Version

v4.0.0-beta.112

**Comment by andrasbacsai** [comment]
Fixing in the next version.
