### ISSUE TITLE
[Bugfix] Login issue 

### ISSUE THREAD

**Issue by dondonjang** [coollabsio/coolify#141]
I was setup new server and install 
ubuntu 20 and 18 ( I tried re install OS) 

visit and ip:3000

entered email and password

but just loop in login page

if i entered change password and return error msg

but collect email and password is loop in login page

**Comment by dondonjang** [comment]
COOLIFY_APP_ID=f7b0cf49-c783-4c45-a020-94d6b20258a3

**Comment by andrasbacsai** [comment]
Hey, I found the issue in `svelte-kit-cookie-session` library I'm using for session cookies. I'm reverting it to an older version.

A new version is released `v2.0.13`, but you probably need to reinstall Coolify again. Sorry about that!
