### ISSUE TITLE
[Bug]: Getting a weird database error

### ISSUE THREAD

**Issue by ashermyers** [coollabsio/coolify#1417]
### Description

When creating ANY database, I get this startup log.. (Using azure cloud instance)

### Minimal Reproduction (if possible, example repository)

Create any database.

### Exception or Error

Database Startup Logs
####### Starting mysql-database-pw8scgk.
1 error(s) decoding:

* 'cpus' expected type 'float32', got unconvertible type 'string', value: '0'

### Version

v4.0.0-beta.116

**Comment by ashermyers** [comment]
Yes

**Comment by andrasbacsai** [comment]
Strange. Based on this [spec](https://github.com/compose-spec/compose-spec/blob/master/schema/compose-spec.json#L172) it could be string or int. Nevertheless, I've set it to int in the next version. Hopefully it will fix your issue.

**Comment by ashermyers** [comment]
Didn’t fix it.. same error.
