### ISSUE TITLE
[Bug]: Minio template is not working (404 default error of Traefik)

### ISSUE THREAD

**Issue by DevHusariaSolutions** [coollabsio/coolify#1427]
### Description

- services work fine (mapping port externally let me connect to both minio and minio console)
- no matter we use HTTP or HTTPS, generated or our own domain - 404 is thrown
- I saw in template that we are not exposing ports, but rather using "proxy" for them, what differs from rest of templates implementation
- Minio itself have env called MINIO_DOMAIN regarding to their docs, even template has it mentioned, but... no value from generated domain is passed here (I've checked env being inside container, MINIO_DOMAIN isn't defined)

What may be reason:
As I remember I had issue with setting my own domain in format "https://mydomain.com:9999/" where 9999 would be port I want to use. I was still getting 404 after redeployment, so maybe its not related to minio, but its bug in Coolify mapping port feature to domain.

If not, then:

Sadly Minio runs console anyway on random port even if we don't set envs related to that.
In past setting env MINIO_BROWSER=off would allow user to disable console, and I thought maybe it would be better to create working template with bare Minio server only first, then once it's working think about minio console as separated service or they both together.

I know You are busy, but time spent on this was still unsuccessful for me.
If You would share some docs around Coolify Template architecture, when and why use proxy etc I would be able to debug it, but currently I don't understend such architecture enough well to find out that.

### Minimal Reproduction (if possible, example repository)

Create new service from template Minio
Deploy
Open Minio console URL

### Version

v4.0.0-beta.119

**Comment by andrasbacsai** [comment]
I found the issue and will fix it! Probably need to release a new version for it as well.

**Comment by DevHusariaSolutions** [comment]
I've updated to v4.0.0-beta.123 and clean install works

**Comment by DevHusariaSolutions** [comment]
Reopening because connection issue occurs
![image](https://github.com/coollabsio/coolify/assets/89352849/29987607-9942-4650-91d4-9a911b149c13)
What I think happens is:
You generate domain with port included ( ":9000" ), but it's used as mapping domain to port.
Apparantly console service of minio gets URL with port included rather than clean just domain.

**Comment by DevHusariaSolutions** [comment]
Ok, I manually set domains without ports for:
- MINIO_BROWSER_REDIRECT_URL
- MINIO_DOMAIN
- MINIO_SERVER_URL

And I successfully navigated authorized :)

**Comment by andrasbacsai** [comment]
I found a way to make everything work. 

It is a new feature coming in beta.124 where the most important fields for shown and changeable directly from the UI. An example for MinIO:

![image](https://github.com/coollabsio/coolify/assets/5845193/51d037de-d788-4ae7-a741-f173c3efc2ea)

This configures everything as it should be.

**Comment by aybasaran10** [comment]
![image](https://github.com/coollabsio/coolify/assets/143166570/6b8529e5-9b58-4433-b11e-ef85ecd53995)

Hello, I am using it in the same exact manner as you, but the 404 page still appears.

![image](https://github.com/coollabsio/coolify/assets/143166570/82d92574-58af-4ac3-bdbb-2f4b6e11742a)
