### ISSUE TITLE
[Bug]: fatal: destination path /artifacts/j08kg00 already exists and is not an empty directory.

### ISSUE THREAD

**Issue by dkonsoftware** [coollabsio/coolify#1428]
### Description

Hi like in title. I have problem with deploy from github app source.
Can't rollback too, same error.
This is monorepo based deployment using folders feature and Nixpack.
Redeploy works for docker images.

### Minimal Reproduction (if possible, example repository)

like in description
Update: I've downgraded coolify to v116 (since it last time it worked fine) and it works for this version.

### Exception or Error

fatal: destination path /artifacts/j08kg00 already exists and is not an empty directory.

### Version

v4.0.0-beta.120

**Comment by andrasbacsai** [comment]
Hey, I reverted what is causing this issue in beta.121. It will be released soon.

**Comment by dkonsoftware** [comment]
Thanks, great job BTW one of my favourites and best PaaS platform out there, im saying this having exp in using dokku, caprover before.
