### ISSUE TITLE
[Bug]: Automatically created server name

### ISSUE THREAD

**Issue by Mikee-3000** [coollabsio/coolify#1433]
### Description

The automaticly created name for my new server is hillbilly-sex-gang-rs0k80o 
![image](https://github.com/coollabsio/coolify/assets/13318998/023f1d39-ae73-4e87-a630-84900a2afedb)

Is this by design or by accident? 

I'm not prudish, and i'm using Coolify for my personal projects, so i don't mind, I'm mostly just curious. Plus, in case this is by accident, you might want to know that someone might get a NSFW server name, possibly when showing Coolify to their product managers (to think of a horyfing scenario ) :D

### Minimal Reproduction (if possible, example repository)

Create a new server, obviously it can't be reproduced easily.

### Version

4.0.0-beta.122

**Comment by andrasbacsai** [comment]
Haha! 

I use a random name generator that could cause this. Modifying it to use only animal names with alliterations (https://github.com/nubs/random-name-generator#alliterative-names).
