### ISSUE TITLE
[Bug]: Auto Deploy from private Serf-Hosted GitLab Repo not working

### ISSUE THREAD

**Issue by creazy231** [coollabsio/coolify#1444]
### Description

Just as the title says, when I push an update to my self-hosted GitLab repository it don't triggers an redeployment. I'm using ssh connection like `git@git.my-gitlab.com:2222/user/repo.git`. Also GitLab only allowes X-Gitlab-Token Headers on Webhooks so I can't use the Coolify Webhooks to trigger it manually therewith.

### Minimal Reproduction (if possible, example repository)

Create a repository on self-hosted GitLab and try to host it using Coolify. Then push some changes.

### Exception or Error

Just as described above.

### Version

v4.0.0-beta.127

**Comment by andrasbacsai** [comment]
Yes, that is not supported yet. GitLab App based deployments are coming soon. 

But I will also try to make manual webhooks configurable for deploy key-based apps!

**Comment by creazy231** [comment]
manual configurable Webhooks would be awesome as a workaround until you got time to implement GitLab App based deployments 😍

**Comment by andrasbacsai** [comment]
I cannot try a self-hosted GitLab instance, with the official one, it works. 

Will be released in the upcoming version.
![image](https://github.com/coollabsio/coolify/assets/5845193/a8f09395-07fe-4644-b453-27aa1458de61)
