### ISSUE TITLE
[Bug]: Plausible Analytics missing from service-templates.json

### ISSUE THREAD

**Issue by dreadedhamish** [coollabsio/coolify#1448]
### Description

Plausible Analytics exists as a service: services/templates/plausibleanalytics.yaml
It is not however listed in templates/service-templates.json

Is there a reason for this?

### Minimal Reproduction (if possible, example repository)

Install. Resources > +New

### Version

v4.0.0-beta.130

**Comment by andrasbacsai** [comment]
It is not there, because of trademark issues. You can copy-paste it to the docker compose type of deployments, and it will work.

**Comment by dreadedhamish** [comment]
> It is not there, because of trademark issues. You can copy-paste it to the docker compose type of deployments, and it will work.

Thanks. Yes that's what I did in the end - it worked fine apart from a little intervention needed because of this bug: https://github.com/coollabsio/coolify/issues/1449
