### ISSUE TITLE
[Bug]: $SERVICE_BASE64_64_PLAUSIBLE and $SERVICE_PASSWORD_64_APPWRITE generating 32bit passwords

### ISSUE THREAD

**Issue by dreadedhamish** [coollabsio/coolify#1449]
### Description

When using $SERVICE_PASSWORD_64_APPWRITE a 32bit password is generated.
Likewise with $SERVICE_BASE64_64_PLAUSIBLE

Given that Plausible Analytics is currently missing from the Services menu I looked and found the yaml in /templates/compose:
https://github.com/coollabsio/coolify-community-templates/blob/main/services/templates/plausibleanalytics.yaml
This generates a password using $SERVICE_BASE64_64_PLAUSIBLE, but the resulting password in 32bits. I then tried with the function listed in the docs - $SERVICE_PASSWORD_64_APPWRITE and it likewise produced a 32bit password.

### Minimal Reproduction (if possible, example repository)

1. New compose project, add and save:

version: '3.3'
services:
  checkfor64bit:
    image: .
    environment:
      - PASSWORD1=$SERVICE_PASSWORD_64_APPWRITE
      - PASSWORD2=$SERVICE_BASE64_64_PLAUSIBLE

2. View environmental variables

### Exception or Error

In the above referenced plausibleanalytics.yaml example it throws an error on startup that an expected password needs to be 64bits.

### Version

v4.0.0-beta.130

**Comment by dreadedhamish** [comment]
> For v4, you need to use [this](https://github.com/coollabsio/coolify/blob/main/templates/compose/plausible.yaml).

Yes that's what i used, and the 64bit password generator in that is generating 32bit passwords.

**Comment by amosbastian** [comment]
I have the same problem, what's the fix? 🤔

**Comment by dreadedhamish** [comment]
> I have the same problem, what's the fix? 🤔

manually you can just generate your own, and then click the LOCK button in the GUI so it's not overwritten in the future:
`openssl rand -base64 64 | tr -d '\n' ; echo`

**Comment by dreadedhamish** [comment]
Still not fixed.

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.
