### ISSUE TITLE
Demo + screenshots + usecases for V2

### ISSUE THREAD

**Issue by leodr** [coollabsio/coolify#145]
Hey, I am very interested in V2, but there does not seem to be a demo yet, or at least I have not been able to find it. Could you create a demo (either demo server or video) for V2?

**Comment by andrasbacsai** [comment]
Hey, yeah, thanks for the suggestion. I will definitely create video/screenshots for it.

**Comment by simeydotme** [comment]
Hi @andrasbacsai  yes I just stumbled on Coolify and the whole project looks incredible and almost too-good-to-be-true, so not being able to see actual proof of the Dashboard/Product working on the HomePage feels unnerving. 

Looks like you're trending on GitHub! :)

**Comment by andrasbacsai** [comment]
Am I trending? Wow! Good to know! ( I do not see it btw )

I'm thinking of a demo instance lately, but people will surely destroy it pretty fast 😁, but 🤷‍♂️. Lets rumble!

https://demo.coolify.io/

I'll add it to the README + landing page!

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
