### ISSUE TITLE
[Bug]: S3 storage created even after failed validation

### ISSUE THREAD

**Issue by mabdullahabid** [coollabsio/coolify#1454]
### Description

I tried to create an S3 storage with CloudFlare R2. The first 5 attempts failed due to the URL already having the bucket name and the bucket name being appended to the URL again. The 6th attempt succeeded at validation. However, when I went back to the S3 Storages screen, I could see 6 storages, 5 not valid and 1 valid. The correct experience here should be that if validation fails, it should not create a storage at all.

Thoughts? Comments? Criticisms?

### Minimal Reproduction (if possible, example repository)

Create an S3 storage with incorrect credentials and then fix them and hit create again. You should have more than one on the S3 Storage list page.

### Version

v4.0.0-beta.134

**Comment by andrasbacsai** [comment]
Ah, good catch. Fixing in the next version!
