### ISSUE TITLE
[Bug]: Redirects in `next.config.js` doesn't work in Next.js 14

### ISSUE THREAD

**Issue by deadcoder0904** [coollabsio/coolify#1455]
### Description

For some reason, this isn't working on coolify:

```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  async redirects() {
    return [
      {
        source: '/google',
        destination: 'https://google.com/',
        permanent: true,
      },
    ]
  },
}

module.exports = nextConfig
```

If someone visits `example.com/google`, then they should be redirected to `google.com` bcz of that.

### Minimal Reproduction (if possible, example repository)

repo -> https://github.com/deadcoder0904/redirect-next-14/

check `next.config.js` file -> https://github.com/deadcoder0904/redirect-next-14/blob/main/next.config.js

### Exception or Error

It runs the deploy for like 3000 seconds & fails afterwards.

Otherwise, deploys run for 230 seconds only.

### Version

https://github.com/coollabsio/coolify/releases/tag/v4.0.0-beta.134

**Comment by andrasbacsai** [comment]
I cannot replicate it. 

https://github.com/coollabsio/coolify/assets/5845193/2352420d-1a02-4d10-b091-32f657cdbb8a

**Comment by deadcoder0904** [comment]
well, then something else might be the error but i promise i only changed this one line in `webpack.config.js` & before that, it deployed perfectly fine.

now, my deploy process takes 1 hour at least & says:

```bash
OUTPUT:
#1 ...

#2 [internal] load build definition from Dockerfile
[2023-Nov-15 06:03:13.727854] Oops something is not okay, are you okay? 😢
[2023-Nov-15 06:03:13.743560] App\Jobs\ApplicationDeploymentJob has timed out.
[2023-Nov-15 06:03:13.757808] Deployment failed. Removing the new version of your application.
```

is there a way to find out the error?

my original `webpack.config.js` is a bit different but i checked it with cal.com & dub.co open-source code & they have the same redirects code:

```js
const webpack = require("webpack")

/** @type {import('next').NextConfig} */
const nextConfig = {
	webpack: (config, { isServer, nextRuntime }) => {
		// Avoid AWS SDK Node.js require issue
		if (isServer && nextRuntime === "nodejs")
			config.plugins.push(new webpack.IgnorePlugin({ resourceRegExp: /^aws-crt$/ }))
		return config
	},
	redirects: async () => {
		const redirects = [
			{
				source: "/google",
				destination:
					"https://google.com/",
				permanent: true,
			},
		]
		return redirects
	},
}

module.exports = nextConfig
```

**Comment by andrasbacsai** [comment]
> well, then something else might be the error but i promise i only changed this one line in `webpack.config.js` & before that, it deployed perfectly fine.
> 
> now, my deploy process takes 1 hour at least & says:
> 
> ```shell
> OUTPUT:
> #1 ...
> 
> #2 [internal] load build definition from Dockerfile
> [2023-Nov-15 06:03:13.727854] Oops something is not okay, are you okay? 😢
> [2023-Nov-15 06:03:13.743560] App\Jobs\ApplicationDeploymentJob has timed out.
> [2023-Nov-15 06:03:13.757808] Deployment failed. Removing the new version of your application.
> ```
> 
> is there a way to find out the error?
> 
> my original `webpack.config.js` is a bit different but i checked it with cal.com & dub.co open-source code & they have the same redirects code:
> 
> ```js
> const webpack = require("webpack")
> 
> /** @type {import('next').NextConfig} */
> const nextConfig = {
> 	webpack: (config, { isServer, nextRuntime }) => {
> 		// Avoid AWS SDK Node.js require issue
> 		if (isServer && nextRuntime === "nodejs")
> 			config.plugins.push(new webpack.IgnorePlugin({ resourceRegExp: /^aws-crt$/ }))
> 		return config
> 	},
> 	redirects: async () => {
> 		const redirects = [
> 			{
> 				source: "/google",
> 				destination:
> 					"https://google.com/",
> 				permanent: true,
> 			},
> 		]
> 		return redirects
> 	},
> }
> 
> module.exports = nextConfig
> ```

The problem should be in the debug logs of Coolify. 

Can you send it here (or on Discord if it has secret stuff)?
Also, please update the example repository.

**Comment by deadcoder0904** [comment]
it was a bug in docker, not coolify. andras found it.

had to restart the server to fix it with the following command:

`sudo systemctl restart docker` :)
