### ISSUE TITLE
[Bug]: seting Service Specific Configuration

### ISSUE THREAD

**Issue by unpseudocomplique** [coollabsio/coolify#1471]
### Description

![image](https://github.com/coollabsio/coolify/assets/69119668/cb0d46ef-0415-49f6-a42d-b18992507a3d)
This error happen when i'm setting MinIO Admin Password.

### Minimal Reproduction (if possible, example repository)

Happenned when trying to setup posthog docker-compose 
https://github.com/PostHog/posthog/blob/master/docker-compose.base.yml

### Version

143

**Comment by andrasbacsai** [comment]
The next release will have a fix for this.

Note: this docker compose file has lots of default values in it that is not recommended to use in production.
