### ISSUE TITLE
[Bug]: I can't follow the next steps after installing coolify

### ISSUE THREAD

**Issue by ctwhome** [coollabsio/coolify#1475]
### Description

After installing it with `curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash` in a fresh new Ubuntu:
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
```
coolify notes:
```
-------------
OS: ubuntu 22.04
Coolify version: 4.0.0-beta.143
-------------
```

it doesn't open the the URL. it takes sometime, but in the end nothing happen in the browser

### Minimal Reproduction (if possible, example repository)

install on new fresh server

### Version

4.0.0-beta.143

**Comment by andrasbacsai** [comment]
The public IP address (determined by the installation script) might be wrong. 

After installation, Coolify should be reachable on all IPs. 

Please try to reach it on the correct interface and let me know if it does not work on any of them.
