### ISSUE TITLE
[Bug]: Can't deploy from docker image

### ISSUE THREAD

**Issue by egoist** [coollabsio/coolify#1477]
### Description

I'm directly deploying from a docker image, but at the end of deployment it always shows:

```
Pushing image to docker registry (XXX/XXX:latest).
Failed to push image to docker registry. Please check debug logs for more information.
```

I'm deploying a public image, not sure why it's trying to do a `docker push`?

### Minimal Reproduction (if possible, example repository)

Just create a project from docker image, the one I used is `qdrant/qdrant:latest`

### Version

v4.0.0-beta.145

**Comment by andrasbacsai** [comment]
Oops. Fixed in beta.146 (releasing in a few minutes)

**Comment by andrasbacsai** [comment]
Released the fix. Please update your instance (or wait for auto-update to happen in 10 minutes).
