### ISSUE TITLE
[Bug]: v4 Discord notification not working

### ISSUE THREAD

**Issue by DiiiaZoTe** [coollabsio/coolify#1487]
### Description

For v4, the Discord notification is not sending anything when I deploy the docker compose of Plausible that you provided here:
https://github.com/coollabsio/coolify/blob/main/templates/compose/plausible.yaml

This could be cause by the fact that you send a notification for each container, but discord webhook is rate limited at 3 requests/second. So if you do more than that at the same time, they may fail...

### Minimal Reproduction (if possible, example repository)

Enable the discord notification with webhook and sub to all events.
Deploy the provided docker compose.

Expected to be notified if deployment failed or not.

### Version

v4.0.0-beta.146

**Comment by DiiiaZoTe** [comment]
Seems to have been resolved by now thanks.

**Comment by andrasbacsai** [comment]
I will add a backup time of 10seconds between each tries.
