### ISSUE TITLE
[Bug]: health check rolls back “old container” while deploying medusa

### ISSUE THREAD

**Issue by JustMrMendez** [coollabsio/coolify#1489]
### Description

For some reason, the health check keeps failing, and it roll backs the container, which makes the deployment fail.
![image](https://github.com/coollabsio/coolify/assets/56850299/37669eed-8825-4c69-8d33-ce3d9d251c5a)

### Minimal Reproduction (if possible, example repository)

- Create new medusa app `pnpm dlx create-medusa-app@latest` (or use **npx**)
- save it to your own repo (you need **posgres** for your dev server)
- add your env-vars
- deploy (enabling Redis should be optional) but in case 👇🏻
uncomment this on `medusa-config.js`
```js
const modules = {
	eventBus: {
		resolve: "@medusajs/event-bus-redis",
		options: {
			redisUrl: REDIS_URL,
		},
	},
	cacheService: {
		resolve: "@medusajs/cache-redis",
		options: {
			redisUrl: REDIS_URL,
		},
	},
};
```

### Exception or Error

Health check fails, no error from medusa, there are no errors in the log

# Solution:
### Version

v4.0.0-beta.146

**Comment by EinfachHans** [comment]
disabling health check is not really a solution, is it?

**Comment by JustMrMendez** [comment]
> disabling health check is not really a solution, is it?

It kind of is, the issue if that health check default endpoint does not exist on medusa.
There is no way to have the health check automatically detect what endpoint to hit, without having to manually set it up for every deployable service.

You should be able to edit what endpoint the health check is hitting.

**Comment by atilladeniz** [comment]
any updates? this is not a solid solution it works but..

**Comment by nazimboudeffa** [comment]
I have been able to deploy the backend by doing this

![image](https://github.com/coollabsio/coolify/assets/1375686/cbb991d9-6f8c-4d1b-a70f-74b9cfbe8dd1)

**Comment by EinfachHans** [comment]
@nazimboudeffa two question:

- does the start period works for you?
- is the path really called? Do you see any logs about it? 🤔

**Comment by nazimboudeffa** [comment]
I don't understand what you mean by the start period

I don't know if the path is called but it doesn't do the healthcheck 10 times

The problem with the logs is that I have this message, if you can help me fix it

`permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/***/json": dial unix /var/run/docker.sock: connect: permission denied`

**Comment by nazimboudeffa** [comment]
So after fixing, that log problem, by doing `sudo usermod -aG docker ubuntu` where ubuntu is the sudo user of my VPS at OVHCloud

I get this in the log

`::ffff:127.0.0.1 - - [23/Apr/2024:07:05:57 +0000] "GET /health HTTP/1.1" 200 2 "-" "curl/7.81.0"`

**Comment by Abz2604** [comment]
Would you be so kind to share the dockerfile and compose file used for deploying? I cant get it to work, relatively new to both docker and coolify

**Comment by slavabez** [comment]
Had a similar issue. None of my new applications would send the healthcheck requests, failing the deployments.

Restarting the VPS worked
