### ISSUE TITLE
[Bug]: CouchDB not listed in databases

### ISSUE THREAD

**Issue by welcoMattic** [coollabsio/coolify#1491]
### Description

CouchDB is not listed in databases types constant https://github.com/coollabsio/coolify/blob/7f69eb3c2e1becbfc36d9e103ce4dc0691618e5a/bootstrap/helpers/constants.php#L4

It is planned to re-add it, as well as in v3?

### Minimal Reproduction (if possible, example repository)

Install a v4 and try to deploy a database, CouchDB is not in the list

### Version

v4.beta.146

**Comment by peaklabs-dev** [comment]
This is because CouchDB has not yet been added. Feel free to upvote the feature request here: https://github.com/coollabsio/coolify/discussions/3200
