### ISSUE TITLE
[Bug]: Build environment variables for preview deployments not working

### ISSUE THREAD

**Issue by mrhappyma** [coollabsio/coolify#1492]
### Description

The build is failing saying it doesn't have a required variable, but it is set and is marked as a build variable. Could be a caching issue since it had built before with the variable not included as a build variable.

### Minimal Reproduction (if possible, example repository)

(my steps)
- deployed an app that requires an environment variable during build time. variable was set and marked as a build variable for production but not for preview
- attempted to deploy for a PR. build failed as it didn't have the variable.
- marked variable as build variable for preview deployments
- redeployed. build still failed.

### Version

v4.0.0-beta.146

**Comment by andrasbacsai** [comment]
Ah, nice catch! Fixing in the next version!
