### ISSUE TITLE
[Bug] v4: Trying to create a Github without domain attached results in no action

### ISSUE THREAD

**Issue by mezuny** [coollabsio/coolify#1494]
### Description

When setting up a new coolify without having attached a domain yet, trying to set up a private Github repo doesn't work while the callback points to the IP. Clicking the button to continue setup results in nothing happening with no errors shown.

### Minimal Reproduction (if possible, example repository)

See description

### Exception or Error

None

### Version

v4.0.0-beta.146

**Comment by andrasbacsai** [comment]
Please try it again and let me know if it still does not work (but I think it will).
