### ISSUE TITLE
[Bug]: Setting the instance domain with a trailing / breaks many URLs

### ISSUE THREAD

**Issue by mrhappyma** [coollabsio/coolify#1495]
### Description

Setting the instance domain in settings with a trailing slash, which validates fine, causes many URLs to have a double slash and therefore be 404s. This seems to primarily affect URLs used outside the web dashboard, such as in notifications or Git app webhook URLs.

### Minimal Reproduction (if possible, example repository)

- Go to settings and set the instance domain to end with a slash
- Attempt to set up a Git app, using the set domain as the webhook endpoint. After authenticating and confirming the setup, you are redirected to `[domain]//webhooks/source/github/install`- which 404s.

### Version

v4.0.0-beta.146

**Comment by andrasbacsai** [comment]
Fixing in the next version!
