### ISSUE TITLE
[Bug]: Just go to my server and explodes

### ISSUE THREAD

**Issue by miguelgargallo** [coollabsio/coolify#1498]
### Description

![image](https://github.com/coollabsio/coolify/assets/5947268/ca3706b4-8a40-4ce9-a2ae-2185d8faf6dc)

```
Error: Attempt to read property "project" on null (View: /var/www/html/resources/views/livewire/server/delete.blade.php) (View: /var/www/html/resources/views/livewire/server/delete.blade.php) (View: /var/www/html/resources/views/livewire/server/delete.blade.php)
```

### Minimal Reproduction (if possible, example repository)

Just go to my server and explodes

### Version

147

**Comment by miguelgargallo** [comment]
@andrasbacsai

**Comment by andrasbacsai** [comment]
Can you please manually run the following command on your server: 

`docker exec -ti coolify bash -c "php artisan app:init --cleanup"`

And let me know if it solves your issue. IF not please reopen the issue.

**Comment by miguelgargallo** [comment]
![image](https://github.com/coollabsio/coolify/assets/5947268/c969e283-514c-49d8-81c3-d7f976977f3b)
Thanks bro, can you explain me what could happend to learn?

**Comment by miguelgargallo** [comment]
yep, on restart error: https://github.com/coollabsio/coolify/issues/1499 @andrasbacsai
