### ISSUE TITLE
[Bug]: "Restart" of service fails with non "/" workdir because workdir is not created

### ISSUE THREAD

**Issue by ktprograms** [coollabsio/coolify#1508]
### Description

When pressing the Restart button of a service that has a non-root Base Directory (i.e. a monorepo), the build fails with being unable to write the docker-compose.yml file.

This seems to be because the `workdir` is not created. The `mkdir` at https://github.com/coollabsio/coolify/blob/b9efc222539e601b6bb1d28098cf036b0b0bce52/app/Jobs/ApplicationDeploymentJob.php#L702 only creates the `basedir` (which seems to be needed because of #1428).

Looking at the code, it seems there are two ways to fix this:
1. Add a `mkdir -p {$this->workdir}` inside `generate_compose_file` before writing the file.
2. Clone the Git repository as a bare repository and then "unbare" it:
```sh
mkdir -p {$this->workdir}
git clone --bare $REPO {$this->basedir}/.git
git -C {$this->basedir} config --unset core.bare
git -C {$this->basedir} checkout -f
```

### Minimal Reproduction (if possible, example repository)

Source: https://github.com/ktprograms/Fullstackopen-Lessons-Exercises
Build Pack: Nixpacks
Build -> Base Directory: `/lessons/part3/`

Deploy once, then Restart (or Redeploy without making any changes to the repo or configuration)

### Exception or Error

<details><summary>Deployment Log</summary><pre>
[2023-Dec-01 00:58:34.561413] Starting deployment of ktprograms/Fullstackopen-Lessons-Exercises:main.
[2023-Dec-01 00:58:35.452445] Preparing container with helper image: ghcr.io/coollabsio/coolify-helper:latest.
[2023-Dec-01 00:58:36.783355]
COMMAND:
docker run -d --network coolify -v /:/host --name lgw40ko --rm -v /var/run/docker.sock:/var/run/docker.sock ghcr.io/coollabsio/coolify-helper:latest

OUTPUT:
                                515b6e01a7e749e70c73a54f114e357b9b841b1bf68770e018efc25cdb1acf66
[2023-Dec-01 00:58:44.143365]
COMMAND:
docker exec lgw40ko bash -c 'GIT_SSH_COMMAND="ssh -o ConnectTimeout=30 -p 22 -o Port=22 -o LogLevel=ERROR -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" git ls-remote https://github.com/ktprograms/Fullstackopen-Lessons-Exercises main'

OUTPUT:
                                3600e1266d20b80c2225b6fd994de6bf5e417483        refs/heads/main
[2023-Dec-01 00:58:44.392112] Setting base directory to /artifacts/lgw40ko/lessons/part3.
[2023-Dec-01 00:58:44.862372]
COMMAND:
docker images -q fckso0k:3600e1266d20b80c2225b6fd994de6bf5e417483 2>/dev/null

OUTPUT:
                                a0c9ed70e1ba
[2023-Dec-01 00:58:45.955083]
COMMAND:
docker exec lgw40ko bash -c 'echo 'dmVyc2lvbjogJzMuOCcKc2VydmljZXM6CiAgICBmY2tzbzBrLTAwNTgzMTg2Mjc0NjoKICAgICAgICBpbWFnZTogJ2Zja3NvMGs6MzYwMGUxMjY2ZDIwYjgwYzIyMjViNmZkOTk0ZGU2YmY1ZTQxNzQ4MycKICAgICAgICBjb250YWluZXJfbmFtZTogZmNrc28way0wMDU4MzE4NjI3NDYKICAgICAgICByZXN0YXJ0OiB1bmxlc3Mtc3RvcHBlZAogICAgICAgIGVudmlyb25tZW50OgogICAgICAgICAgICAtIFBPUlQ9MzAwMAogICAgICAgIGxhYmVsczoKICAgICAgICAgICAgLSB0cmFlZmlrLmVuYWJsZT10cnVlCiAgICAgICAgICAgIC0gJ3RyYWVmaWsuaHR0cC5yb3V0ZXJzLmh3Y3dnc2stMC1odHRwLnJ1bGU9SG9zdChgZmNrc28way4xMjcuMC4wLjEuc3NsaXAuaW9gKSAmJiBQYXRoUHJlZml4KGAvYCknCiAgICAgICAgICAgIC0gdHJhZWZpay5odHRwLnJvdXRlcnMuaHdjd2dzay0wLWh0dHAuZW50cnlQb2ludHM9aHR0cAogICAgICAgICAgICAtIHRyYWVmaWsuaHR0cC5yb3V0ZXJzLmh3Y3dnc2stMC1odHRwLm1pZGRsZXdhcmVzPWd6aXAKICAgICAgICAgICAgLSB0cmFlZmlrLmh0dHAucm91dGVycy5od2N3Z3NrLTAtaHR0cC5zZXJ2aWNlPWh3Y3dnc2stMC1odHRwCiAgICAgICAgICAgIC0gdHJhZWZpay5odHRwLnNlcnZpY2VzLmh3Y3dnc2stMC1odHRwLmxvYWRiYWxhbmNlci5zZXJ2ZXIucG9ydD0zMDAwCiAgICAgICAgICAgIC0gY29vbGlmeS5tYW5hZ2VkPXRydWUKICAgICAgICAgICAgLSBjb29saWZ5LnZlcnNpb249NC4wLjAtYmV0YS4xNDcKICAgICAgICAgICAgLSBjb29saWZ5LmFwcGxpY2F0aW9uSWQ9NAogICAgICAgICAgICAtIGNvb2xpZnkudHlwZT1hcHBsaWNhdGlvbgogICAgICAgICAgICAtIGNvb2xpZnkubmFtZT1mY2tzbzBrCiAgICAgICAgICAgIC0gY29vbGlmeS5wdWxsUmVxdWVzdElkPTAKICAgICAgICBleHBvc2U6CiAgICAgICAgICAgIC0gJzMwMDAnCiAgICAgICAgbmV0d29ya3M6CiAgICAgICAgICAgIC0gY29vbGlmeQogICAgICAgIGhlYWx0aGNoZWNrOgogICAgICAgICAgICB0ZXN0OgogICAgICAgICAgICAgICAgLSBDTUQtU0hFTEwKICAgICAgICAgICAgICAgIC0gJ2N1cmwgLXMgLVggR0VUIC1mIGh0dHA6Ly9sb2NhbGhvc3Q6MzAwMC8gPiAvZGV2L251bGwnCiAgICAgICAgICAgIGludGVydmFsOiA1cwogICAgICAgICAgICB0aW1lb3V0OiA1cwogICAgICAgICAgICByZXRyaWVzOiAxMAogICAgICAgICAgICBzdGFydF9wZXJpb2Q6IDVzCiAgICAgICAgbWVtX2xpbWl0OiAnMCcKICAgICAgICBtZW1zd2FwX2xpbWl0OiAnMCcKICAgICAgICBtZW1fc3dhcHBpbmVzczogNjAKICAgICAgICBtZW1fcmVzZXJ2YXRpb246ICcwJwogICAgICAgIGNwdXM6IDAKICAgICAgICBjcHVzZXQ6ICcwJwogICAgICAgIGNwdV9zaGFyZXM6IDEwMjQKbmV0d29ya3M6CiAgICBjb29saWZ5OgogICAgICAgIGV4dGVybmFsOiB0cnVlCiAgICAgICAgbmFtZTogY29vbGlmeQogICAgICAgIGF0dGFjaGFibGU6IHRydWUK' | base64 -d > /artifacts/lgw40ko/lessons/part3/docker-compose.yml'

OUTPUT:
                                bash: line 1: /artifacts/lgw40ko/lessons/part3/docker-compose.yml: No such file or directory</pre></details>

### Version

v4.0.0-beta.147

**Comment by ktprograms** [comment]
Yeah, I'm getting the same error as #1428 now (this is on the very first Deploy).

<details><summary>Deployment Log</summary><pre>[2023-Dec-01 15:24:44.246695] Starting deployment of ktprograms/Fullstackopen-Lessons-Exercises:main.
[2023-Dec-01 15:24:44.739804] Preparing container with helper image: ghcr.io/coollabsio/coolify-helper:latest.
[2023-Dec-01 15:24:45.456443]
COMMAND:
docker run -d --network coolify -v /:/host --name oo0c0c0 --rm -v /var/run/docker.sock:/var/run/docker.sock ghcr.io/coollabsio/coolify-helper:latest

OUTPUT:
7421d3b04422ac0f3fba575f88f1c0821fbd5c1b5f6b09cb037e5c9d44cc2824
[2023-Dec-01 15:24:50.901124]
COMMAND:
docker exec oo0c0c0 bash -c 'GIT_SSH_COMMAND="ssh -o ConnectTimeout=30 -p 22 -o Port=22 -o LogLevel=ERROR -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" git ls-remote https://github.com/ktprograms/Fullstackopen-Lessons-Exercises main'

OUTPUT:
361273a1fdce512df324e9ec1bdbc4595bceb157 refs/heads/main
[2023-Dec-01 15:24:51.045151] Setting base directory to /artifacts/oo0c0c0/lessons/part3.
[2023-Dec-01 15:24:51.627577] Configuration changed. Rebuilding image.
[2023-Dec-01 15:24:51.641472] ----------------------------------------
[2023-Dec-01 15:24:51.648987] Importing ktprograms/Fullstackopen-Lessons-Exercises:main (commit sha HEAD) to /artifacts/oo0c0c0.
[2023-Dec-01 15:24:52.133492]
COMMAND:
docker exec oo0c0c0 bash -c 'git clone -b main https://github.com/ktprograms/Fullstackopen-Lessons-Exercises /artifacts/oo0c0c0 && cd /artifacts/oo0c0c0 && git submodule update --init --recursive && cd /artifacts/oo0c0c0 && git lfs pull'

OUTPUT:
fatal: destination path '/artifacts/oo0c0c0' already exists and is not an empty directory.
[2023-Dec-01 15:24:52.332399] Oops something is not okay, are you okay? 😢
[2023-Dec-01 15:24:52.407560] fatal: destination path /artifacts/oo0c0c0 already exists and is not an empty directory.
[2023-Dec-01 15:24:52.486374] Deployment failed. Removing the new version of your application.</pre></details>

**Comment by pan-sveta** [comment]
I am getting the same error even on beta.151
