### ISSUE TITLE
[BUG] Bad Connection String on PostGresSQL

### ISSUE THREAD

**Issue by AtoLrn** [coollabsio/coolify#151]
# Problem

The Connection String in PostGresSql is wrong

You can see there is a "false" just after "postgresql://"

![image](https://user-images.githubusercontent.com/26856078/154768730-4ee06390-7732-4a15-b6e5-899913871092.png)

**Comment by andrasbacsai** [comment]
Ah, thanks! It will be fixed in the next version!
