### ISSUE TITLE
[Bug]: Localhost DNS issue

### ISSUE THREAD

**Issue by cueup** [coollabsio/coolify#1512]
### Description

Firstly @andrasbacsai thanks for creating a great tool. 

I'm struggling to get my apps working after being deployed. I deploy the app and when I try visiting http://nocodb-t84gcsk.MY_PUBLIC_IP.sslip.io/ it navigates to my router page. I've deployed three app with the same result. 

I've tried changing the public IP to 127.0.0.1 and even using localhost but no luck. Not sure what I'm missing. 

I'm running:
- coolify locally v4.0.0-beta.151
- Docker desktop 
- Windows 10 (Ubuntu 22.04 sub-system)
 

### Minimal Reproduction (if possible, example repository)

Deploy any app and try opening the application url 

### Version

4.0.0-beta.151

**Comment by andrasbacsai** [comment]
So you are starting Coolify in dev mode? I never tried to use it on a windows machine (I'm using it in WSL).

**Comment by cueup** [comment]
I'm also using WSL

**Comment by iron3oxide** [comment]
I've put coolify on a Raspberry Pi in my home network and am facing the same problem. When replacing my public IP with that of the Pi, I get a 404.

**Comment by andrasbacsai** [comment]
It is probably a network issue on your local network, so it unrelated to Coolify.

I think the community over \[discord\](https://coolify.io/discord) could help you in this problem.
