### ISSUE TITLE
[Bug] v4: docker compose with custom build context fails to build

### ISSUE THREAD

**Issue by stooit** [coollabsio/coolify#1514]
### Description

The new docker compose build pack does not seem to account for images with builds using custom dockerfiles.

The `docker compose up --build -d` command runs from `/data/coolify/applications/{id}` which only has the processed `docker-compose.yml` file, not the cloned repo.

It works on older versions (e.g output from 4.0.0-beta.147 below), as the build happens from `/artifacts/{id}`:
```
COMMAND:
docker exec yg0soc0 bash -c 'docker compose --project-directory /artifacts/yg0soc0 up --build -d'

... (builds fine)
```

### Minimal Reproduction (if possible, example repository)

Deploy using docker compose build pack with a simple docker-compose.yaml file
```
version: '3'

services:
  site:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
```

With `.dockerfiles/nginx.dockerfile`:
```
FROM nginx:stable-alpine
COPY ./nginx/default.conf /etc/nginx/conf.d/
```

### Exception or Error

```
COMMAND:
docker compose --project-directory /data/coolify/applications/okwww88 up --build -d

OUTPUT:
unable to prepare context: path "/data/coolify/applications/okwww88/dockerfiles" not found
```

### Version

4.0.0-beta.151

**Comment by andrasbacsai** [comment]
This will be fixed in the next version!
