### ISSUE TITLE
[Bug]: Docker Compose buildpack rewrites docker-compose.yml with properties that are not allowed

### ISSUE THREAD

**Issue by bohtho** [coollabsio/coolify#1521]
### Description

Using a private GitHub repo (via GitHub app) and the Docker Compose buildpack results in a rewritten/added 'volumes:' part at the bottom of the docker-compose.yml which makes the deployment fail with "volumes additional property [..] is not allowed". This was not present one or two betas ago.

### Minimal Reproduction (if possible, example repository)

Add "/var/run/docker.sock:/var/run/docker.sock" under the "volumes" part of a service, and it gets added to the root "volumes" at the bottom, which fails the deployment on account of using "/var/run/docker.sock" as a property.
<img width="1234" alt="Skjermbilde 2023-12-06 kl  00 55 56" src="https://github.com/coollabsio/coolify/assets/13752/6d6e6589-367f-4bc9-a8ac-0d43c913b863">

### Exception or Error

<img width="1398" alt="Skjermbilde 2023-12-06 kl  00 56 37" src="https://github.com/coollabsio/coolify/assets/13752/a4108520-0b97-4e30-a475-dbfb97464bf4">

### Version

v4.0.0 beta 153

**Comment by andrasbacsai** [comment]
Thanks for the report, it will be fixed in the next version.
