### ISSUE TITLE
[Bug]: "Docker Compose" modal window closes unexpectedly

### ISSUE THREAD

**Issue by AndreasFaust** [coollabsio/coolify#1522]
### Description

In a resource of type "Based on a Docker Compose", click on `Edit Compose File` a modal window opens. 
When you now edit the file, the window closes unexpectedly without saving, making working this way almost impossible.

### Minimal Reproduction (if possible, example repository)

The simple steps are described in **Description**.

### Version

v4.0.0-beta.154

**Comment by andrasbacsai** [comment]
I will release a fix for it soon.

**Comment by andrasbacsai** [comment]
> Maybe this is going too far (and needs its own feature request), but how about going all in and implementing a full IDE component?
> 
> For example, https://github.surmon.me/vue-codemirror

I will add it in the future, but it is not in priority atm. 🙂

**Comment by AndreasFaust** [comment]
Understandable — there is still a lot to do, I guess. By the way, I love your product. Keep up the good work!
