### ISSUE TITLE
[Bug]: issue while building

### ISSUE THREAD

**Issue by tboy-hacker** [coollabsio/coolify#1552]
### Description

good day love the project when i was trying to run it , it showed( PHP Warning:  require(/home/rex/Desktop/coolify-4.0.0-beta.160/vendor/autoload.php): failed to open stream: No such file or directory in /home/rex/Desktop/coolify-4.0.0-beta.160/artisan on line 18
PHP Fatal error:  require(): Failed opening required '/home/rex/Desktop/coolify-4.0.0-beta.160/vendor/autoload.php' (include_path='.:/usr/share/php') in /home/rex/Desktop/coolify-4.0.0-beta.160/artisan on line 18)

pls i will love help because i want to add to this lovely project 

### Minimal Reproduction (if possible, example repository)

php artisan serve

### Version

the latest

**Comment by andrasbacsai** [comment]
Please follow the contribution guide to setup the development version of Coolify. If you need help, please ask it on our [Discord server](https://t.co/1jXFKs9StA) in the #contribution channel.
