### ISSUE TITLE
[Bug]: Can’t add domain to service

### ISSUE THREAD

**Issue by AndreasFaust** [coollabsio/coolify#1561]
### Description

I can’t add a domain to my service. When I try this error message pops up:
<img width="449" alt="Bildschirmfoto 2023-12-20 um 20 13 32" src="https://github.com/coollabsio/coolify/assets/15075587/4f0077de-900b-4ec4-ab91-93a2adb21243">
I had the domain in another service, but I deleted it there. 

### Minimal Reproduction (if possible, example repository)

Maybe it can be reproduced by: 
1. setting up a service SERVICE 1 with a domain.
2. add another service SERVICE 2 with the same domain
3. delete the domain from SERVICE 1
4. try again to set the domain in SERVICE 2

### Version

v4.0.0-beta.169

**Comment by AndreasFaust** [comment]
Completely removing the Services, the Environment or the Project did not help.
Also choosing a different Network didn’t. The domains `https://api.elternratgeber-psychotherapie.de` and `https://elternratgeber-psychotherapie.de` seem to be blocked now from Coolify due to this SQL error.

**Comment by urtho** [comment]
To fix this you have to delete zombie services from DB.
Best to execute this command on localhost via UI:

`docker exec -t coolify-db sh -c "/usr/local/bin/psql -U coolify -c 'delete from service_applications where id not in (select id from services);'"`

**Comment by AndreasFaust** [comment]
Thank you, @urtho! I tried it but it does not work, because the service `coolify-db` does not exist. 
I use `Coolify Cloud`. Could this be the reason?

**Comment by urtho** [comment]
This works on self-hosted only.

**Comment by andrasbacsai** [comment]
I will check!

**Comment by andrasbacsai** [comment]
I think I already solved this, can you please check again @AndreasFaust ?

**Comment by AndreasFaust** [comment]
Thank you, @andrasbacsai, for taking care. Unfortunately the error still persists.

<img width="451" alt="Bildschirmfoto 2023-12-27 um 13 01 16" src="https://github.com/coollabsio/coolify/assets/15075587/7d22cf08-f3b3-47d4-843b-f1faee16c6c3">

**Comment by AndreasFaust** [comment]
@andrasbacsai, is there a shortcut for me to get around this? 
Without solving this issue, I cannot finish with the project I am working on.

**Comment by andrasbacsai** [comment]
Sorry, it was my mistake. It is deleted now, can you please check?

**Comment by AndreasFaust** [comment]
Works, thank you.
