### ISSUE TITLE
[Bug]: SERVICE_FQDN parsing error

### ISSUE THREAD

**Issue by el-garro** [coollabsio/coolify#1567]
### Description

Incorrect use of SERVICE_FQDN env var can render your service inaccesible by the coolify UI, making it imposibble to fix or even delete, my exact case was SERVICE_FQDN_WG_EASY.

### Minimal Reproduction (if possible, example repository)

Caution: Backup your db if you're not comfortable editing it by hand later

1. Create a docker compose resource
2. Set SERVICE_FQDN_FOO_BAR in the environment section of the yaml, making sure BAR is not a number (because it expects a port number)
3. Save
4. The UI can no longer access that service config

### Exception or Error

I just rolled back the DB and didn't copied it but it was something along the lines of http://FOO:BAR is not a URL in a big popup of http error 500

### Version

4.0.0-beta.172

**Comment by andrasbacsai** [comment]
I will add a fix to handle this case, but adding a `SERVICE_FQDN_FOO_BAR` was just a mistake. What was your intention?

**Comment by el-garro** [comment]
Thanks for the response. I was making a wireguard service based on wg_easy and tried use that as a FQDN, It was a mistake, and there's no problem in it throwing an error, the problem is it breaks permanently that part of UI so you can't fix or delete the resource.
