### ISSUE TITLE
[Bug]: CPU Limit is being rounded

### ISSUE THREAD

**Issue by JesterIruka** [coollabsio/coolify#1568]
### Description

Filling 0.5 or 0.25 in the Number of CPUs field results in `cpus: 0` at docker-compose.yml
Filling 1.5 or 1.75 results in `cpus: 1`

I'm checking this by running `docker exec -it ${CONTAINER} bash` and `cat docker-compose.yml`

### Minimal Reproduction (if possible, example repository)

The repository itself does not matter, but here is my dockerfile

```dockerfile
FROM node:20

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

ENV PORT=8080

CMD [ "node", "index.js" ]
```

### Version

v4.0.0-beta.172

**Comment by JesterIruka** [comment]
Maybe this line? replacing by `(float)` should solve
![image](https://github.com/coollabsio/coolify/assets/49654905/08d8f028-c938-4f49-aac9-032e4aded4e4)

**Comment by andrasbacsai** [comment]
Nice catch! I will fix it!
