### ISSUE TITLE
[Bug]: Coolify first reports deployment/build failure and then success after a while

### ISSUE THREAD

**Issue by srinisubramanian** [coollabsio/coolify#1595]
### Description

I have an angular app that is built using nixpacks via npm install and npm build.  The build takes a while and Cooliy first reports a failure.  However the build is still running and then a couple of minutes later reports a success.

Is there a build timeout or something I can tweak to get coolify/nixpacks to wait longer?

### Minimal Reproduction (if possible, example repository)

Angular 16 App Build via npm build

### Version

v4.0.0-beta.177

**Comment by srinisubramanian** [comment]
This happened today while deploying a MSSQL docker container.

As can be seen from this screenshot, already indicated as Failed but docker download is still ongoing.  Once all done and container is running, a success will also be reported.

<img width="1084" alt="image" src="https://github.com/coollabsio/coolify/assets/8343179/e5136329-7823-4692-9862-eef3339f67c7">

**Comment by techwithanirudh** [comment]
I'm having the same issue.

**Comment by andrasbacsai** [comment]
This should be fixed. If not, please reopen.
