### ISSUE TITLE
[Bug]: Install script fails on Raspbian with "no matching manifest for linux/arm/v8"

### ISSUE THREAD

**Issue by silasabbott** [coollabsio/coolify#1601]
### Description

On a fresh install of Raspbian Pi OS Lite (32-bit, Bullseye) on a Raspberry Pi 4, the docker manifest cannot be found for linux/arm/v8

### Minimal Reproduction (if possible, example repository)

1. Install Raspbian Pi OS Lite (32-bit, Bullseye)
2. Run the Coolify install script as administrator

### Exception or Error

```
-------------
Welcome to Coolify v4 beta installer!
This script will install everything for you.
(Source code: https://github.com/coollabsio/coolify/blob/main/scripts/install.sh)
-------------
OS: raspbian 11
Coolify version: 4.0.0-beta.181
-------------
Installing required packages...
-------------
Check Docker Configuration...
Docker configuration is up to date.
-------------
Downloading required files from CDN...
latest: Pulling from coollabsio/coolify-helper
docker: no matching manifest for linux/arm/v8 in the manifest list entries.
See 'docker run --help'.
```

### Version

4.0.0-beta.181

**Comment by silasabbott** [comment]
My bad—I was running a 32-bit installation of Raspbian. Problem was fixed by using a 64-bit Raspbian image instead.

Feel free to close this issue if 32-bit support is not on the roadmap.

**Comment by andrasbacsai** [comment]
32-bit is not on the roadmap, but if someone would like to contribute, I'm open to it.
