### ISSUE TITLE
[Bug]: docker-compose.yml vs docker-compose.yaml

### ISSUE THREAD

**Issue by endquote** [coollabsio/coolify#1606]
### Description

If a docker-compose project uses the filename `docker-compose.yml`, it will fail.

### Minimal Reproduction (if possible, example repository)

If I try to deploy this repo: https://github.com/plausible/hosting

I get this error: Could not load base compose file from /docker-compose.yaml

If I fork the repo and change the file extension from `yml` to `yaml`, it works.

Can coolify support all yaml file extensions?

### Version

v4.0.0-beta.182 / Resources endquote production drawing-series endquote/plausible:master-yoosk88 miami-2019 redirect shiny tdrbingo umami

**Comment by endquote** [comment]
Nevermind, I found where you can enter the compose file path.

**Comment by danielehrhardt** [comment]
https://github.com/plausible/hosting
