### ISSUE TITLE
Automatic editing of NGINX configuration files on servers with NGINX running

### ISSUE THREAD

**Issue by hazycora** [coollabsio/coolify#161]
I host some other things on my machine, so I'm using NGINX to proxy_pass my coolify domain to port 3000. However, because NGINX is running, coolify is unable to bind to port 443 for custom domains on apps. It would be very helpful if for people using coolify with NGINX coolify would add config files for custom domains rather than trying to bind to 443.

**Comment by andrasbacsai** [comment]
You can use Coolify without the automatic proxy configurations. 

Disable it in the`Destinations` menu, and then you can use your proxy, but it needs to be configured manually.

Is this what you are looking for?

**Comment by hazysu** [comment]
Yeah, I saw that it's definitely possible, but it would be neat if it was more automatic on systems using NGINX (since manually editing nginx config files kinda defeats the point of a web service which sets up things for you, in my opinion)

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
