### ISSUE TITLE
[Bug]: Project is stated as exited, when deploy is not started

### ISSUE THREAD

**Issue by techwithanirudh** [coollabsio/coolify#1611]
### Description

The project's status is said as exited, when the deploy has not even been started

### Minimal Reproduction (if possible, example repository)

Create a new resource, don't deploy yet, you see the exited status indicator

### Version

4.0.0-beta.183

**Comment by andrasbacsai** [comment]
What do you prefer to see before the initial deployment? An empty state? Or nothing? :)

**Comment by arthur-es** [comment]
Hey @andrasbacsai 

I had a similar issue...
![image](https://github.com/coollabsio/coolify/assets/37699234/e3caf304-dbd8-4d7e-a035-9a4d75f7ba5e)
<img width="1512" alt="image" src="https://github.com/coollabsio/coolify/assets/37699234/fc015c59-8a02-4232-b761-520fcd8151d9">
I kept getting the "Exited" status.
I was not able to see what caused this.
Only when I disabled Health-check I could see the error message:
![image](https://github.com/coollabsio/coolify/assets/37699234/f2ff9b99-5c71-4884-b557-0f76a9972a98)

**Comment by andrasbacsai** [comment]
This has been fixed in the latest version. If it occurs again, please reopen this issue.

**Comment by code4you2021** [comment]
+1

new linux server install the Coolify, use the command:
```shell
curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash
```

<img width="1325" alt="CleanShot 2024-02-10 at 16 58 55@2x" src="https://github.com/coollabsio/coolify/assets/83153991/911ef2f5-90d2-45a1-b0f1-8d9da1197570">
