### ISSUE TITLE
[Feature Request] Gitea as Git source

### ISSUE THREAD

**Issue by tacohitbox** [coollabsio/coolify#162]
Self explanatory. Not a must-have immediately but would be cool to have :)

**Comment by andrasbacsai** [comment]
Thanks for the PR, I will add support for Gitea for sure! 

I'm closing this as it's a duplicate of #130 . :)

**Comment by mmm8955405** [comment]
> Thanks for the PR, I will add support for Gitea for sure!
> 
> I'm closing this as it's a duplicate of #130 . :)
This is not a copy at all
