### ISSUE TITLE
[Bug]:  An exception occurred in the driver: SQLSTATE[08006] [7] could not translate host name "e40cw80" to address: Name or service not known

### ISSUE THREAD

**Issue by victorshdev** [coollabsio/coolify#1623]
### Description

While redeploying the Symfony app, I encountered the error 'could not translate host name "e40cw80" to address: Name or service not known.'

The 'e40cw80' refers to postgres:16-alpine, which is fine because the current instance is working with it.

It seems like building image and postgre are not in the same network.

The most recent successful deployment was with v4.0.0-beta.184.

P.S. One possible workaround is to enable and use the database's public connection URL.

If you need more details, please let me know. Thanks.

### Minimal Reproduction (if possible, example repository)

1. Deploy postge16 container
2. Deploy symfony php app (example: https://github.com/victorshdev/symfony-uploads-s3) with DATABASE_URL env

Error will appear.

### Exception or Error

OUTPUT:
[KO]
#13 5.780 [KO]
#13 5.780 Script cache:clear returned with error code 7
#13 5.780 !!
#13 5.780 !! In ExceptionConverter.php line 77:
#13 5.780 !!
#13 5.780 !! An exception occurred in the driver: SQLSTATE[08006] [7] could not translat
#13 5.780 !! e host name "e40cw80" to address: Name or service not known
#13 5.780 !!
#13 5.780 !!
#13 5.780 !! In Exception.php line 28:
#13 5.780 !!
#13 5.780 !! SQLSTATE[08006] [7] could not translate host name "e40cw80" to address: Nam
#13 5.780 !! e or service not known
#13 5.780 !!
#13 5.780 !!
#13 5.780 !! In Driver.php line 34:
#13 5.780 !!
#13 5.780 !! SQLSTATE[08006] [7] could not translate host name "e40cw80" to address: Nam
#13 5.780 !! e or service not known
#13 5.780 !!
#13 5.780 !!
#13 5.780 !!
#13 5.780 Script @auto-scripts was called via post-install-cmd
[2024-Jan-10 12:46:36.986347]
COMMAND:
docker exec pscc448 bash -c 'nixpacks build -c thegameplan.json --cache-key 'qcwww0o' --no-error-without-start -n qcwww0o:13a2a383d116365b8f671934f8aaf3b4bd6cf6f5 /artifacts/pscc448'

OUTPUT:
#13 ERROR: process "/bin/bash -ol pipefail -c composer install --ignore-platform-reqs" did not complete successfully: exit code: 7
[2024-Jan-10 12:46:37.042037]
COMMAND:
docker exec pscc448 bash -c 'nixpacks build -c thegameplan.json --cache-key 'qcwww0o' --no-error-without-start -n qcwww0o:13a2a383d116365b8f671934f8aaf3b4bd6cf6f5 /artifacts/pscc448'

OUTPUT:
------
> [ 9/16] RUN composer install --ignore-platform-reqs:
5.780 !!
5.780 !!
5.780 !! In Driver.php line 34:
5.780 !!
5.780 !! SQLSTATE[08006] [7] could not translate host name "e40cw80" to address: Nam
5.780 !! e or service not known
5.780 !!
5.780 !!
5.780 !!
5.780 Script @auto-scripts was called via post-install-cmd
------
[2024-Jan-10 12:46:37.049804]
COMMAND:
docker exec pscc448 bash -c 'nixpacks build -c thegameplan.json --cache-key 'qcwww0o' --no-error-without-start -n qcwww0o:13a2a383d116365b8f671934f8aaf3b4bd6cf6f5 /artifacts/pscc448'

### Version

v4.0.0-beta.185

**Comment by andrasbacsai** [comment]
Coolify used native `docker build` command (and the build process ran in host network to reach all containers) before for building nixpacks based apps, but I changed it to `nixpacks` because I found out that caching is working differently - basically not working with `docker build`.

So, now there are two ways to solve this:
1. Run database in the same network as your application, so it will be reachable with internal URL.
2. Run database in a separate network, but then you need to use the public URL.

I will add a small docs for others.
