### ISSUE TITLE
[Bug]: Error: Unable to call component method. Public method [submit] not found on component

### ISSUE THREAD

**Issue by victorshdev** [coollabsio/coolify#1624]
### Description

![Screenshot 2024-01-10 at 14 09 23](https://github.com/coollabsio/coolify/assets/131619111/aca618be-d3c9-4e4d-8704-576e10714279)

### Minimal Reproduction (if possible, example repository)

1. Click "Run" at Postgre container.
2. Click "Close" Database Startup Logs popup.

Error will appear.

Please note that container run successful. 

### Exception or Error

500

Something is not okay, are you okay?
There has been an error, we are working on it.

Error: Unable to call component method. Public method [submit] not found on component

### Version

v4.0.0-beta.185

**Comment by andrasbacsai** [comment]
It will be fixed in the next version. Thanks for reporting!
