### ISSUE TITLE
[Bug] GitHub integration not sending authorization

### ISSUE THREAD

**Issue by hazysu** [coollabsio/coolify#163]
After making my first app, which worked completely fine, I am now unable to make any new apps. When I get to the page to select a repository to use, Coolify makes the request (client side btw, I'm not sure if this is intended), and GitHub responds with:
```json
{
  "message": "Bad credentials",
  "documentation_url": "https://docs.github.com/rest"
}
```
I am willing to answer more questions about this problem if needed!

**Comment by andrasbacsai** [comment]
Ah, I thought I fixed it. A quick fix is on its way!

**Comment by andrasbacsai** [comment]
Let me know if it still does not work!

**Comment by hazysu** [comment]
This problem has been solved! Thanks!
