### ISSUE TITLE
[Bug]: nixpack wordpress

### ISSUE THREAD

**Issue by wp-coin** [coollabsio/coolify#1633]
### Description

<img width="1091" alt="Screenshot 2024-01-11 220637" src="https://github.com/coollabsio/coolify/assets/35810228/b5ed6a32-e53c-446f-a6ce-455372aa4484">

### Minimal Reproduction (if possible, example repository)

error deploying WordPress website from private GitHub repository

### Version

beta.188

**Comment by andrasbacsai** [comment]
Can you give me an example repository to reproduce the issue? Because from the screenshot, it looks like it tries to read a file that does not exists.

**Comment by andrasbacsai** [comment]
So it is solved. 👍🏻  Nice!
