### ISSUE TITLE
[Bug]: build static nginx:alpine

### ISSUE THREAD

**Issue by wp-coin** [coollabsio/coolify#1643]
### Description

after selecting build static nginx:alpine , the nginx default files are not deleted after uploading github files

<img width="845" alt="Screenshot 2024-01-11 230828" src="https://github.com/coollabsio/coolify/assets/35810228/c4eec233-84bb-48d8-bd05-1009487a7f9a">

### Minimal Reproduction (if possible, example repository)

Build Pack: static
Nginx:alpine

### Version

beta.188

**Comment by andrasbacsai** [comment]
Not sure if I understand the `uploading github files` part. Can you please explain it a bit further?
