### ISSUE TITLE
[Bug]: error logs

### ISSUE THREAD

**Issue by wp-coin** [coollabsio/coolify#1644]
### Description

we need to be able to see the error logs

### Minimal Reproduction (if possible, example repository)

<img width="1207" alt="Screenshot 2024-01-12 151423" src="https://github.com/coollabsio/coolify/assets/35810228/3ebdc978-befa-452f-86c0-955bc30eca91">

### Version

beta.190

**Comment by andrasbacsai** [comment]
You need to use `cat /var/log/nginx/error.log`.
