### ISSUE TITLE
[Bug]: website does not connect to database using https

### ISSUE THREAD

**Issue by wp-coin** [coollabsio/coolify#1645]
### Description

I have installed mariadb from the resources page but my website does not connect via https, it only connects in a non secure format http

are you using the official image from docker?
https://hub.docker.com/_/mariadb/

### Minimal Reproduction (if possible, example repository)

if I enable https it will not enable any connection to the database

### Exception or Error

enable error logs in coolify because they are not visible

### Version

beta.190

**Comment by mraf** [comment]
Hi @wp-coin is your website on Wordpress?

**Comment by andrasbacsai** [comment]
SSL TCP connections are not supported yet.
