### ISSUE TITLE
[Bug]: page loading mixed content over https

### ISSUE THREAD

**Issue by wp-coin** [coollabsio/coolify#1646]
### Description

I enabled https in the domain but my content is still loading with http

### Minimal Reproduction (if possible, example repository)

![mixed_content_-_net_pane](https://github.com/coollabsio/coolify/assets/35810228/4bc94377-14d5-409e-b88a-e53cabcb20b1)

### Version

beta.190

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming release. Please read #1650
