### ISSUE TITLE
[Bug]: Service tabs not working

### ISSUE THREAD

**Issue by lxix** [coollabsio/coolify#1647]
### Description

I've created a resource _based on docker compose_ and some tabs on the _service edit page_ won't load. Namely:  "Environment variables", "Scheduled Tasks" and "Danger zone" tabs

### Minimal Reproduction (if possible, example repository)

1. Add new resource
2. Choose "based on docker compose"
   ```
   services:
      whoami:
        image: docker.io/traefik/whoami:latest
    ```
3. Click on the gear icon of the "whoami" service block
4. See "Environment variables", "Scheduled Tasks" and "Danger zone" tabs

### Version

v4.0.0-beta.190

**Comment by andrasbacsai** [comment]
Fixing in the next version.
