### ISSUE TITLE
[Bug]: Connection to a docker Redis on server-1 from server-2 not working

### ISSUE THREAD

**Issue by srinisubramanian** [coollabsio/coolify#1648]
### Description

I have two servers server-1 and server-2 connected to coolify.  The coolify host and the two servers are all on the default coolify network.  Services on server-2 are unable to resolve/connect to services on server-1

### Minimal Reproduction (if possible, example repository)

* I have a redis service and an app-service-1 on server-1.  app-service-1 is able to connect to the redis container using the generated container id for redis
* I then setup app-service-2 on server-2.  When I now try to connect app-service-2 to redis on server-1 it fails.  All containers are on the same coolify network and IP addresses
* nsloopup on server-2 for the redis container fails to resolve
* I then tried to telnet via ip address from server-2 to server-1 redis, that also failed

Given that all services (docker containers) are running on the same network, shouldnt they be able to connect across servers without mapping ports to host?

### Exception or Error

Connectivity failure

### Version

v4.0.0-beta.190

**Comment by srinisubramanian** [comment]
Currently to get this working I mapped the redis port 6379 to the host server1 and then connect from the app-service-2 on server-2 to redis using server-1-ip:6379 and that works

**Comment by andrasbacsai** [comment]
As they are on different servers, you need to make the `redis` database available through the internet.

You can do it in the `redis` Settings by enabling `Accessible over the internet`.

![image](https://github.com/coollabsio/coolify/assets/5845193/e1587750-ebd9-4671-a68e-7783764a3b5e)

This is the same behavior what you did by mapping the redis port to the host system. Just with the `Accessible over the internet` feature, you can turn it off anytime + use custom ports easily.

**Comment by srinisubramanian** [comment]
@andrasbacsai just to confirm. Let's assume service is not redis but some other custom service. Is it that cross server communication will require port mapping to host?
