### ISSUE TITLE
[Bug]: Log Drain to Axiom not working

### ISSUE THREAD

**Issue by srinisubramanian** [coollabsio/coolify#1656]
### Description

Log drain to Axiom not working.  No logs are being sent, Axiom dataset is still empty

### Minimal Reproduction (if possible, example repository)

* in server config added Axiom key and dataset name
* axiom is configured such that the key allows both ingest and query permission to the dataset
* Since logs were not flowing, I also restarted the server but no success
* In coolify services logs view i can see the logs being displayed and refreshed

### Version

v4.0.0-beta.190

**Comment by srinisubramanian** [comment]
Hello @andrasbacsai  Any pointers on how I can get this working?  Or if its a bug that needs to be fixed

**Comment by andrasbacsai** [comment]
I could not reproduce this issue. I'm using Axios and it is working on the latest version. 

Is the API key / dataset name correct? Based on the `Forbidden` response, I think it is not.

**Comment by hkd987** [comment]
@andrasbacsai -> Draining logs under a docker swarm config to Axiom seems to be broken....

**Comment by rossanmol** [comment]
It is also broken for me. no logs reaching axiom.

**Comment by srinisubramanian** [comment]
@andrasbacsai  maybe issue need to be reopened as a couple of more users reporting that its not working as expected?

**Comment by Vahor** [comment]
Works for me with a docker image / github app and grafana. So this might only occur under docker swarm

**Comment by ekiwi111** [comment]
can confirm, v4.0.0-beta.331, draining logs to Axiom isn't working for me either
 
<img width="1078" alt="2" src="https://github.com/user-attachments/assets/ea889ceb-db74-459a-8aaf-4eff192e3234">
<img width="1107" alt="1" src="https://github.com/user-attachments/assets/0e6194a5-6fba-4980-a16f-f7dedf3367d0">

**Comment by srinisubramanian** [comment]
I tested this again with v4.0.0-beta.331.  Logs were sent once I restarted the containers.  Just updating didnt send the logs.  At least in my landscape it now works

**Comment by peaklabs-dev** [comment]
Please upgrade to the latest version of Coolify and if this is still an issue, please create a new issue with detailed reproduction steps.
