### ISSUE TITLE
[Bug]: The build pack field is required error when untouched

### ISSUE THREAD

**Issue by baptisteArno** [coollabsio/coolify#1665]
### Description

When creating a new resource, if you leave the build pack field untouch it will display the error toast: `The build pack field is required error when untouched`

### Minimal Reproduction (if possible, example repository)

https://github.com/coollabsio/coolify/assets/16015833/1e0dcd90-f82e-427b-962a-b67c73e526d6

### Version

v4.0.0-beta.198

**Comment by andrasbacsai** [comment]
It has been fixed in the latest version. Thank you for letting me know.
