### ISSUE TITLE
[Bug]: CPU Weight more info tooltip is broken

### ISSUE THREAD

**Issue by baptisteArno** [coollabsio/coolify#1666]
### Description

When trying to get more info about the `CPU Weight` input, it displays "More info here" but on click, does nothing.

### Minimal Reproduction (if possible, example repository)

https://github.com/coollabsio/coolify/assets/16015833/98feaf7a-cdcc-4727-b6d1-bd7c425c51de

### Version

v4.0.0-beta.198

**Comment by andrasbacsai** [comment]
Thanks! There is a link on the `here` texts, but I will make it more visible.
![image](https://github.com/coollabsio/coolify/assets/5845193/246ae415-f9b4-42d9-9efb-889449b1cdb1)
