### ISSUE TITLE
[Bug]: Resources disappeared in Projects

### ISSUE THREAD

**Issue by JustinBack** [coollabsio/coolify#1686]
### Description

A lot of resources disappeared from the projects today but are still running in the background. They cannot be managed anymore only via the docker cli
```
CONTAINER ID   IMAGE                                       COMMAND                  CREATED        STATUS                  PORTS                                                                                                                 NAMES
2c2fd3799ab9   mariadb:11                                  "docker-entrypoint.s…"   9 hours ago    Up 9 hours (healthy)    0.0.0.0:9002->3306/tcp, :::9002->3306/tcp                                                                             mk4gs08
6b763b510fc0   postgres:16-alpine                          "docker-entrypoint.s…"   34 hours ago   Up 34 hours (healthy)   0.0.0.0:6000->5432/tcp, :::6000->5432/tcp                                                                             ygo88g4
d95915d69695   48355b156945                                "docker-entrypoint.s…"   3 days ago     Up 3 days (healthy)     0.0.0.0:5437->5432/tcp, :::5437->5432/tcp                                                                             f8w0ksw
fc8a5980de9e   ghcr.io/coollabsio/coolify:4.0.0-beta.200   "/init"                  3 days ago     Up 3 days (healthy)     443/tcp, 8000/tcp, 9000/tcp, 0.0.0.0:8000->80/tcp, :::8000->80/tcp                                                    coolify
990512e94287   quay.io/soketi/soketi:1.6-16-alpine         "node /app/bin/serve…"   3 days ago     Up 3 days (healthy)     0.0.0.0:6001->6001/tcp, :::6001->6001/tcp                                                                             coolify-realtime
d9daab395266   postgres:15-alpine                          "docker-entrypoint.s…"   3 days ago     Up 3 days (healthy)     5432/tcp                                                                                                              coolify-db
3474ab9c199f   redis:alpine                                "docker-entrypoint.s…"   3 days ago     Up 3 days (healthy)     6379/tcp                                                                                                              coolify-redis
70276300a8f3   redis:7.2                                   "docker-entrypoint.s…"   4 days ago     Up 4 days (healthy)     0.0.0.0:6379->6379/tcp, :::6379->6379/tcp                                                                             o00so80
aec1c6093566   48355b156945                                "docker-entrypoint.s…"   4 days ago     Up 4 days (healthy)     0.0.0.0:5440->5432/tcp, :::5440->5432/tcp                                                                             ro40gw8
4361ff436ed7   3e87f8bfed4e                                "docker-entrypoint.s…"   11 days ago    Up 5 days (healthy)     0.0.0.0:3318->3306/tcp, :::3318->3306/tcp                                                                             n8sw0w4
aea354445a9f   48355b156945                                "docker-entrypoint.s…"   2 weeks ago    Up 5 days (healthy)     0.0.0.0:5438->5432/tcp, :::5438->5432/tcp                                                                             gccssks
08481c055cfe   3e87f8bfed4e                                "docker-entrypoint.s…"   2 weeks ago    Up 5 days (healthy)     0.0.0.0:3316->3306/tcp, :::3316->3306/tcp                                                                             sgwowwg
01316491dec3   3e87f8bfed4e                                "docker-entrypoint.s…"   2 weeks ago    Up 5 days (healthy)     0.0.0.0:3315->3306/tcp, :::3315->3306/tcp                                                                             msg8csc
1a0c49edf42e   c74611c2858a                                "docker-entrypoint.s…"   3 weeks ago    Up 5 days (healthy)     0.0.0.0:3312->3306/tcp, :::3312->3306/tcp                                                                             u4gwgk0
ae229f18e2f5   c74611c2858a                                "docker-entrypoint.s…"   3 weeks ago    Up 5 days (healthy)     0.0.0.0:3311->3306/tcp, :::3311->3306/tcp                                                                             jss80g0
23a76765f1c7   mariadb:10.5                                "docker-entrypoint.s…"   3 weeks ago    Up 5 days (healthy)     0.0.0.0:3309->3306/tcp, :::3309->3306/tcp                                                                             t848sgs
6f0a6f77688c   212541dc5d3d                                "docker-entrypoint.s…"   3 weeks ago    Up 5 days (healthy)     0.0.0.0:5436->5432/tcp, :::5436->5432/tcp                                                                             o4wkkcw
61762df6e319   c74611c2858a                                "docker-entrypoint.s…"   5 weeks ago    Up 5 days (healthy)     0.0.0.0:3310->3306/tcp, :::3310->3306/tcp                                                                             p804c48
6a315b2d3ecd   212541dc5d3d                                "docker-entrypoint.s…"   5 weeks ago    Up 5 days (healthy)     0.0.0.0:5433->5432/tcp, :::5433->5432/tcp                                                                             rwssgks
7c8321e67b33   c74611c2858a                                "docker-entrypoint.s…"   5 weeks ago    Up 5 days (healthy)     0.0.0.0:3307->3306/tcp, :::3307->3306/tcp                                                                             vw8gw04
775df28e598a   mariadb:10.5                                "docker-entrypoint.s…"   5 weeks ago    Up 5 days (healthy)     0.0.0.0:3308->3306/tcp, :::3308->3306/tcp                                                                             gwggo8g
fe509d271922   212541dc5d3d                                "docker-entrypoint.s…"   5 weeks ago    Up 5 days (healthy)     0.0.0.0:5435->5432/tcp, :::5435->5432/tcp                                                                             s4cwko0
5f818dd28377   traefik:v2.10                               "/entrypoint.sh --pi…"   5 weeks ago    Up 5 days (healthy)     0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp, 0.0.0.0:8080->8080/tcp, :::8080->8080/tcp   coolify-proxy
6d4588e80abb   portainer/agent:2.19.4                      "./agent"                6 weeks ago    Up 5 days               0.0.0.0:9001->9001/tcp, :::9001->9001/tcp                                                                             portainer_agent
root@internal-coolify:~#
```

### Minimal Reproduction (if possible, example repository)

N/A

### Exception or Error

Nothing in the logs 
```
 2024-01-29 12:24:00 App\Jobs\CleanupInstanceStuffsJob .............. RUNNING
  2024-01-29 12:24:00 App\Jobs\CleanupInstanceStuffsJob ......... 18.87ms DONE
  2024-01-29 12:24:00 App\Jobs\ContainerStatusJob .................... RUNNING
  2024-01-29 12:24:01 App\Jobs\ContainerStatusJob .............. 280.14ms DONE
  2024-01-29 12:24:01 App\Jobs\ServerStatusJob ....................... RUNNING
  2024-01-29 12:24:01 App\Jobs\ServerStatusJob ................. 340.28ms DONE
  2024-01-29 12:25:00 Running ['artisan' horizon:snapshot] ........ 153ms DONE
  ⇂ '/usr/bin/php8.2' 'artisan' horizon:snapshot > '/dev/null' 2>&1  
  2024-01-29 12:25:00 Running [App\Jobs\ContainerStatusJob] ......... 4ms DONE
  2024-01-29 12:25:00 Running [App\Jobs\ServerStatusJob] ............ 0ms DONE

  2024-01-29 12:25:00 App\Jobs\ContainerStatusJob .................... RUNNING
  2024-01-29 12:25:01 App\Jobs\ContainerStatusJob .............. 294.88ms DONE
  2024-01-29 12:25:01 App\Jobs\ServerStatusJob ....................... RUNNING
  2024-01-29 12:25:01 App\Jobs\ServerStatusJob ................. 327.67ms DONE
  2024-01-29 12:26:00 Running [App\Jobs\CleanupInstanceStuffsJob] ... 6ms DONE
  2024-01-29 12:26:00 Running [App\Jobs\ContainerStatusJob] ......... 0ms DONE
  2024-01-29 12:26:00 Running [App\Jobs\ServerStatusJob] ............ 0ms DONE

  2024-01-29 12:26:00 App\Jobs\CleanupInstanceStuffsJob .............. RUNNING
  2024-01-29 12:26:00 App\Jobs\CleanupInstanceStuffsJob ......... 24.80ms DONE
  2024-01-29 12:26:00 App\Jobs\ContainerStatusJob .................... RUNNING
  2024-01-29 12:26:01 App\Jobs\ContainerStatusJob .............. 300.92ms DONE
  2024-01-29 12:26:01 App\Jobs\ServerStatusJob ....................... RUNNING
  2024-01-29 12:26:01 App\Jobs\ServerStatusJob ................. 349.68ms DONE
```

### Version

v4.0.0-beta.200

**Comment by JustinBack** [comment]
Gotta note that the majority of projects are empty now

**Comment by JustinBack** [comment]
Further debugging shows me that the databases itself are not gone from the `standalone_*` tables - They all exist properly there. I tried Restarting the `coolify` container as well but that did not fix the issue.

**Comment by andrasbacsai** [comment]
That is strange. Can you please show me the db output of `SELECT id, name, environment_id, FROM standalone_postgresqls`?

**Comment by JustinBack** [comment]
Sure, here you go

![Bildschirmfoto 2024-01-30 um 12 35 04](https://github.com/coollabsio/coolify/assets/40178814/8e32dbbe-9d6e-4879-bc24-abcdb4749bcc)

**Comment by maietta** [comment]
My first time using Coolify in production starting yesterday and ran into this.

I configured a MaraDB instance and now it's not appearing, but it's there in the database. It's running. It's files were created in the /data/coolify/databases directory.

This is not a good way to start things for me.

**Comment by maietta** [comment]
Found a partial temp fix:

When I navigated to Projects > Project Name (in my case, Shared Databases), I was getting either a broken or empty list of project.

But if I created a new service, such as a WordPress website, then I went to it's configuration under the Resource Operations and re-assigned it's enviornment to one belonging to the "missing" project envirornment, then it seems to fix the issue.

After doing this, I can now navigate to my "Shared Databases" project page without issue.

Further, if I re-assign my WordPress back to it's own environment, I suddenly have this bug again where I am now able to browse my projects in the environment again.

So it seems for now, I have to keep a spare dead, non-used app assigned to that environment in addition to the one I wanted to be available in the UI-- just to make it show in the UI.

I'm not really sure what's causing this or what the issue is.

**Comment by JustinBack** [comment]
> Found a partial temp fix:
> 
> When I navigated to Projects > Project Name (in my case, Shared Databases), I was getting either a broken or empty list of project.
> 
> But if I created a new service, such as a WordPress website, then I went to it's configuration under the Resource Operations and re-assigned it's enviornment to one belonging to the "missing" project envirornment, then it seems to fix the issue.
> 
> After doing this, I can now navigate to my "Shared Databases" project page without issue.
> 
> Further, if I re-assign my WordPress back to it's own environment, I suddenly have this bug again where I am now able to browse my projects in the environment again.
> 
> So it seems for now, I have to keep a spare dead, non-used app assigned to that environment in addition to the one I wanted to be available in the UI-- just to make it show in the UI.
> 
> I'm not really sure what's causing this or what the issue is.

You can also create databases as normal and head to your server > localhost

granted they are listed with their pre-generated names there but we just changed them to recognize the dbs properly

**Comment by maietta** [comment]
Further--

I notice that my d

> > Found a partial temp fix:
> > When I navigated to Projects > Project Name (in my case, Shared Databases), I was getting either a broken or empty list of project.
> > But if I created a new service, such as a WordPress website, then I went to it's configuration under the Resource Operations and re-assigned it's enviornment to one belonging to the "missing" project envirornment, then it seems to fix the issue.
> > After doing this, I can now navigate to my "Shared Databases" project page without issue.
> > Further, if I re-assign my WordPress back to it's own environment, I suddenly have this bug again where I am now able to browse my projects in the environment again.
> > So it seems for now, I have to keep a spare dead, non-used app assigned to that environment in addition to the one I wanted to be available in the UI-- just to make it show in the UI.
> > I'm not really sure what's causing this or what the issue is.
> 
> You can also create databases as normal and head to your server > localhost
> 
> granted they are listed with their pre-generated names there but we just changed them to recognize the dbs properly
> 
> edit: See [#1686 (comment)](https://github.com/coollabsio/coolify/issues/1686#issuecomment-1914643715)

I'm not sure what "creating databases like normally" really means here.

I'm migrating from CapRover and brought over my docker volumes and now setting things up to use those existing volumes.

I simply added a fresh MariaDB instance from the UI but specified my own volume rather than one to be created and that worked. No problem there-- I can reach the database just fine.

I just can't seem to show it's existance in the UI where I expect it.

But now I also see if I browse to my server in the list, I do show this... that my 2 previous database setups do in fact show-- but listed as standalone.

Not sure if this is a problem between keyboard and chair, or this is a bug.

![image](https://github.com/coollabsio/coolify/assets/11745020/c41b8bf2-c15d-4dd2-b284-6f70712812eb)

**Comment by maietta** [comment]
Okay, interesting. I finally got this alert when browsing projects.

Running Debian 12.

![image](https://github.com/coollabsio/coolify/assets/11745020/40625542-d8df-421d-945d-a8d4827ac712)

**Comment by andrasbacsai** [comment]
Thanks to @maietta, I was able to debug the issue. Fixed in v208.

Can you please check it after you updated?

**Comment by JustinBack** [comment]
Can confirm that its fixed in 208, cheers!
