### ISSUE TITLE
[Bug]: filebrowser service template doesn't persist config

### ISSUE THREAD

**Issue by RayBB** [coollabsio/coolify#1688]
### Description

the filebrowser template is able to persist data.
This is because the docker instructions for filebrowser are outdated https://github.com/filebrowser/filebrowser/issues/2883

The file is mounted to `/database.db` instead of `/config`

It isn't as simple as pointing to  `/database.db` because docker compose will make a directory instead of a file.

I'm still investigating a fix which might include trying to change the config location in docker compose or using a different image that makes that easier (like https://github.com/hurlenko/filebrowser-docker). Could also be trying to get a change put into filebrowser repo.

Since @theh2so4 make this template I think filebrowser may have changed the defaults.

### Minimal Reproduction (if possible, example repository)

Try getting the settings for filebrowser to persist between restarts.

### Version

v4.0.0-beta.201

**Comment by andrasbacsai** [comment]
Thanks! I fixed the template by using the LinuxServer-provided image.

**Comment by RayBB** [comment]
@andrasbacsai while using the LinuxServer-provided image works to solve the config it has another problem as mentioned in https://github.com/filebrowser/filebrowser/issues/2736

It runs a `chown` on the `/srv` directory.

So if you do something a little foolish like me and have the following line in your compose file:
```
    volumes:
      - '/root:/srv'
```

Then it will bork the ability to ssh into your root user as you'll get the error:
`Authentication refused: bad ownership or modes for directory /root`

The fix for this is to run to following as root:
```
sudo chmod 700 /root
sudo chown root:root /root

sudo chmod 700 /root/.ssh
sudo chmod 600 /root/.ssh/authorized_keys
sudo chown -R root:root /root/.ssh
```

But that only lasts until the next time docker restarts your filebrowser image.

You could also simply not mount the `/root` directory but I still think running chown on the whole directory could cause other issues. So... I'm not sure if I would recommend using that image until they fixed it.

**Comment by andrasbacsai** [comment]
Okay, I fixed a few things: it uses host-based mounts, not docker volumes; creates directories, etc., and reverted the filebrowser image to the alpine (latest) tag.

To use this properly, you need to update Coolify to version 215.
