### ISSUE TITLE
[Bug]: Cannot setup domain with automated SSL-cerificate

### ISSUE THREAD

**Issue by AndreasFaust** [coollabsio/coolify#1690]
### Description

I am trying to connect a (sub-)domain to a service, but https does not work. Is there a way to manually delete it, to be able to set it up again?
Besides that, the process of domain connection in general could be improved. There is still this bug, that connected domains from a deleted service do not work anymore.
Vercel does a good job in showing, which domains are connected to a project and what their status is. 

### Minimal Reproduction (if possible, example repository)

I really don’t know,why it does not work in this case and how to reproduce it. At another environment of the project it is working just fine.

### Version

4.0.0-beta202

**Comment by andrasbacsai** [comment]
Sorry for this issue. I've made a few modifications on how domains are handled (in the cloud version, self-hosted version is not released yet).

Can you please also check if the deleted service's domain is usable again?

**Comment by andrasbacsai** [comment]
It seems that the correct container labels are missing from the deployed container. Have you restarted the container since you changed the domain?

**Comment by AndreasFaust** [comment]
It worked after restarting the service. Thank you as usual!
