### ISSUE TITLE
[Bug]: used domains validation is broken

### ISSUE THREAD

**Issue by iamEvanYT** [coollabsio/coolify#1699]
### Description

Before [v4.0.0-beta.203](https://github.com/coollabsio/coolify/pull/1691),
You can use `https://test.example.com/prod` on one resource and `https://test.example.com/testing` on the second one and `https://test.example.com` on the third resource.

After the release, it will say `Domain xxx is already in use by another resource.`
Commit https://github.com/coollabsio/coolify/pull/1691/commits/3ae95018141c1fd50b8afe53d031098a068af490 seems to be the issue.

### Minimal Reproduction (if possible, example repository)

1. Create Three Resources
2. do `https://test.example.com/prod`, `https://test.example.com/testing` and `https://test.example.com` on each project.
3. It will say `Domain xxx is already in use by another resource.`

### Exception or Error

![image](https://github.com/coollabsio/coolify/assets/47493765/85a91496-7042-457b-a4f8-8d49221e4a72)

### Version

Behavior Starting From v4.0.0-beta.203

**Comment by andrasbacsai** [comment]
I already fixed this in 204. Sorry for the issue. Let me know if 204 has the same (but I doubt).
