### ISSUE TITLE
[Bug]: UI: clicking on project leads directly to production environment

### ISSUE THREAD

**Issue by AndreasFaust** [coollabsio/coolify#1704]
### Description

This is maybe a feature, not a bug, but it used to confuse me and still feels a little annoying to me:
In the App, clicking on a Project in the Home view leads directly to the production environment of this project. But the next logical step would be the selection of environments. To go there, I need an extra click or directly go by the Projects view. 

It does not make sense from a UI standpoint, that the same semantic link has different targets in different places.

### Minimal Reproduction (if possible, example repository)

1. Log in to the app and, still in the Home view, click on a project, that has a production and staging environment. 
2. The production environment will be displayed.
3. To go to the environment selection you need to click on the name of the Project that appears next to "Ressources".

### Version

beta.205

**Comment by andrasbacsai** [comment]
The next version will include a fix for this. It will only go to the production environment if no other environments are defined.
