### ISSUE TITLE
[Bug]: Docker volumes are not cleaned when applications are deleted

### ISSUE THREAD

**Issue by pixrr** [coollabsio/coolify#1705]
### Description

I've encountered an issue regarding disk space management on my server. Despite expecting around 30GB of disk usage, I've noticed it quickly filling up to approximately 50GB without proper cleanup processes in place.

Following the documentation on automated cleanup (https://coolify.io/docs/automated-cleanup#automated-cleanup), I attempted to resolve the issue, but unfortunately, the disk space usage remains unchanged.

Upon further investigation into the root cause of the persistent disk space consumption, I discovered that Docker volumes are not being properly cleaned up after deleting applications such as n8n, Stirling PDF, etc. It seems to lack a Docker command to delete unused volumes.

Is it intentional to keep these volumes, or should they be cleaned up automatically?

### Minimal Reproduction (if possible, example repository)

Self hosted version on Ubuntu server:
- Install a new application (such as n8n, stirling pdf) from Coolify
- Delete the freshly installed application
- Check the disk space usage using the command: `sudo du -h --max-depth=1 /var 2>/dev/null`
- Additionally, check the Docker volumes disk usage with the command: `docker system df`

### Version

v4.0.0-beta.205

**Comment by andrasbacsai** [comment]
When you delete a resource in Coolify and the server is accessible, all volumes are removed. If the server is not accessible, Coolify cannot perform the cleanup. 

I tried to reproduce the problem by checking if the volumes are deleted after I delete the resource, but they are consistently removed. 

I prefer not to include 'docker volume prune' in the cleanup process as there may be other volumes that should not be automatically removed.

Can you please make a small video of:
1. Create n8n
2. `docker volume ls`
3. Delete n8n
4. `docker volume ls`

I would really appreciate it.

**Comment by pixrr** [comment]
Hello @andrasbacsai, first of all, thank you for the work you've put into Coolify.

It seems strange that when I delete the n8n resource, the volume (prefixed with identifier `joog84w`) remains on the server even after removing the application. You can verify this in the video below:

https://github.com/coollabsio/coolify/assets/26383152/8ba18600-5bc0-459b-8b62-a2c378ab4283

Here are some server details that might be potentially useful for you:

Coolify v4.0.0-beta.209
Docker CE 2.0.4
Docker compose 2.24.5
Ubuntu 22.04.1 LTS

Thank you

**Comment by andrasbacsai** [comment]
Thank you! I will fix this!
