### ISSUE TITLE
[Bug]: Multiple tags won't wrap and instead overflow

### ISSUE THREAD

**Issue by piscis** [coollabsio/coolify#1707]
### Description

If you add 10-15 Tags and the available screen size gets to small. the list of tags will overflow to the right and create a scroll container. A user has then to scroll to the right to select all available tags.

### Minimal Reproduction (if possible, example repository)

Add 10 - 15 tags for you services. Notice that the tags will not wrap and instead create a horizontal scroll container. 

![Screenshot 2024-02-04 at 13 20 38](https://github.com/coollabsio/coolify/assets/326163/ff5bc77c-bda9-419e-8d49-2bbbf2790f0b)

### Exception or Error

Tags should wrap underneath if available space gets to small.

### Version

v4.0.0-beta.205

**Comment by piscis** [comment]
please see: #1706 for a PR

**Comment by andrasbacsai** [comment]
Thank you!
