### ISSUE TITLE
[Improvement]: Make E-Mail after DB-Backup optional

### ISSUE THREAD

**Issue by AndreasFaust** [coollabsio/coolify#1726]
### Description

As the title says: it would be nice to be able not to receive an email when a database is backed up. 
It is just a less important detail, but would be great to have.

### Minimal Reproduction (if possible, example repository)

A little switch would be awesome. 

### Version

beta.213

**Comment by AngCosmin** [comment]
You can switch it off in Team → Notifications → Backup status.

It also took me a while to figure it out how can I do it 😁

<img width="595" alt="image" src="https://github.com/coollabsio/coolify/assets/8146514/5435908e-c696-439c-81e4-79551d9435ea">

**Comment by AndreasFaust** [comment]
Thank you, @AngCosmin! Great, that this is already possible!
More fine grain control over notifications (e.g. per service) still could be nice to have, though (some day in the future, after the release of v1).

**Comment by sneko** [comment]
@peaklabs-dev is there any plan to improve backup notifications? In case of a daily backups I would just need to be notified of a failing backup instead of all successful backups (when doing it for Coolify + databases... it makes a lot of noise).

**Comment by peaklabs-dev** [comment]
@sneko yes this will be improved in the future see here -> https://github.com/coollabsio/coolify/discussions/3163
