### ISSUE TITLE
[Bug]: The [public/storage] link already exists.

### ISSUE THREAD

**Issue by deployn** [coollabsio/coolify#1730]
### Description

After upgrading from beta.209 to beta.212, I wasn't able to open my Coolify dashboard anymore. The services are still running fine, but Coolify is in a restarting loop.

I can't use https://coolify.io/docs/commands, as the container is no running.

### Minimal Reproduction (if possible, example repository)

I pressed on the update icon.

### Exception or Error

```
____                             ____  _     _        _   _
/ ___|  ___ _ ____   _____ _ __  / ___|(_) __| | ___  | | | |_ __
\___ \ / _ \  __\ \ / / _ \  __| \___ \| |/ _` |/ _ \ | | | |  _ \
___) |  __/ |   \ V /  __/ |     ___) | | (_| |  __/ | |_| | |_) |
|____/ \___|_|    \_/ \___|_|    |____/|_|\__,_|\___|  \___/| .__/
                                                            |_|

Brought to you by serversideup.net
--------------------------------------------------------------------

To support Server Side Up projects visit:
https://serversideup.net/sponsor
-------------------------------------
GID/UID
-------------------------------------

User uid:    9999
User gid:    9999
-------------------------------------

🔓 SSL_MODE has been DISABLED, setting the web server to work in HTTP only...
🏃‍♂️ Checking for Laravel automations...
🔐 Linking the storage...

   INFO  Running migrations.  

  2024_02_08_112304_add_dynamic_timeout_for_deployments ............. 3ms FAIL

   ERROR  The [public/storage] link already exists.  


In Connection.php line 817:
                                                                               
  SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates u  
  nique constraint "pg_attribute_relid_attnum_index"                           
  DETAIL:  Key (attrelid, attnum)=(16512, 25) already exists. (Connection: pg  
  sql, SQL: alter table "server_settings" add column "dynamic_timeout" intege  
  r not null default '3600')                                                   
                                                                               

In Connection.php line 580:
                                                                               
  SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates u  
  nique constraint "pg_attribute_relid_attnum_index"                           
  DETAIL:  Key (attrelid, attnum)=(16512, 25) already exists.                  
                                                                               

s6-rc: warning: unable to start service db-migration: command exited 1
Horizon started successfully.
[09-Feb-2024 10:35:17] NOTICE: fpm is running, pid 104
[09-Feb-2024 10:35:17] NOTICE: ready to handle connections
[09-Feb-2024 10:35:17] NOTICE: systemd monitor interval set to 10000ms
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.

Session terminated, killing shell...
Session terminated, killing shell...[09-Feb-2024 10:35:18] NOTICE: Terminating ...
[09-Feb-2024 10:35:18] NOTICE: exiting, bye-bye!
 ...killed.
 ...killed.

```

### Version

4.0.0-beta.212

**Comment by deployn** [comment]
Downgraded to beta.209. I can open the dashboard, but this error comes up if I press on some services:

`Error: SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "tags" does not exist LINE 1: ...es"."taggable_type" as "pivot_taggable_type" from "tags" inn... ^ (Connection: pgsql, SQL: select "tags".*, "taggables"."taggable_id" as "pivot_taggable_id", "taggables"."tag_id" as "pivot_tag_id", "taggables"."taggable_type" as "pivot_taggable_type" from "tags" inner join "taggables" on "tags"."id" = "taggables"."tag_id" where "taggables"."taggable_id" in (20, 21) and "taggables"."taggable_type" = App\Models\Application)
`

**Comment by deployn** [comment]
Downgraded to beta.200. I was able to delete some applications.
Something is still wrong with my deployments. If I try to edit a environment, I get this error:

`Error: SQLSTATE[42809]: Wrong object type: 7 ERROR: "additional_destinations_pkey" is an index LINE 1: select * from "shared_environment_variables" where "shared_e... ^ (Connection: pgsql, SQL: select * from "shared_environment_variables" where "shared_environment_variables"."project_id" = 13 and "shared_environment_variables"."project_id" is not null) (View: /var/www/html/resources/views/livewire/project/edit.blade.php)`

**Comment by andrasbacsai** [comment]
It looks like the db migrations failed, and the database already has the column somehow. 

If you go inside the coolify container and execute: php artisan migration:status

If i see the output, I can help you to rollback.

**Comment by deployn** [comment]
Thanks, I formatted my server. Problem solved :)
