### ISSUE TITLE
[Improvement]: multiple database options for postgresql

### ISSUE THREAD

**Issue by lethanhviet** [coollabsio/coolify#1735]
### Description

It would be even better if postgresql has an option to create and load multiple databases.

### Minimal Reproduction (if possible, example repository)

When creating/loading a new postgresql package, on configuration, there's an option to create and load multple new databases.

### Version

v4.0.0-beta.212

**Comment by andrasbacsai** [comment]
If you mean to create more databases at once, this could be done via the API, with separate API requests.

I'm closing this issue for now. Please reopen if you meant something else.
