### ISSUE TITLE
[Bug]: --Privileged Flag Not Working on Build anymore After Install

### ISSUE THREAD

**Issue by orbitturner** [coollabsio/coolify#1739]
### Description

I am facing an issue with Coolify where the --privileged flag is not working as expected. This results in a validation error when running a docker compose command since the latest update.

And when i remove it its working great.

### Minimal Reproduction (if possible, example repository)

- Be in the latest version : ()
- Add Custom Docker Options : --privileged
- Trigger a Deploy and observe

### Exception or Error

COMMAND:
docker exec y4gg44o bash -c 'SOURCE_COMMIT=320e9a09c8e4a7e4d5210c1c4028eea57a2a36e1 docker compose --project-directory /artifacts/y4gg44o -f /artifacts/y4gg44o/docker-compose.yml up --build -d'

OUTPUT:
time="2024-02-13T14:15:51Z" level=warning msg="The \"bnHHN48\" variable is not set. Defaulting to a blank string."
time="2024-02-13T14:15:51Z" level=warning msg="The \"bnHHN48\" variable is not set. Defaulting to a blank string."
validating /artifacts/y4gg44o/docker-compose.yml: services.r0wks0s.privileged must be a boolean
[2024-Feb-13 14:15:51.447080] Oops something is not okay, are you okay? 😢
[2024-Feb-13 14:15:51.453738] time="2024-02-13T14:15:51Z" level=warning msg="The \"bnHHN48\" variable is not set. Defaulting to a blank string."
time="2024-02-13T14:15:51Z" level=warning msg="The \"bnHHN48\" variable is not set. Defaulting to a blank string."
time="2024-02-13T14:15:51Z" level=warning msg="The \"bnHHN48\" variable is not set. Defaulting to a blank string."

validating /artifacts/y4gg44o/docker-compose.yml: services.r0wks0s.privileged must be a boolean
[2024-Feb-13 14:15:51.459631] Deployment failed. Removing the new version of your application.

![image](https://github.com/coollabsio/coolify/assets/39173514/8efd2bee-0549-4902-bfcd-843187325937)
![image](https://github.com/coollabsio/coolify/assets/39173514/6eb745f8-4bec-4617-b691-5a983885cffd)

### Version

v4.0.0-beta.213

**Comment by andrasbacsai** [comment]
It is fixed with #1741
