### ISSUE TITLE
PR/MR deployments could be available with the branch.domain

### ISSUE THREAD

**Issue by andrasbacsai** [coollabsio/coolify#174]
Should be an additional configuration

**Comment by mlorthios** [comment]
Where does this feature fit in your roadmap?

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
