### ISSUE TITLE
[Bug]: Cannot install coolify

### ISSUE THREAD

**Issue by supermx1** [coollabsio/coolify#1745]
### Description

I get an error when using the auto installer on Ubuntu/Debian on Hetzner. I tried on both AMD and ARM servers.

<img width="951" alt="image" src="https://github.com/coollabsio/coolify/assets/9326922/c1853540-5514-4a28-a974-d27a8921ee4d">

### Minimal Reproduction (if possible, example repository)

Install using the auto installer on Hetzner

### Version

Latest

**Comment by ewertonls** [comment]
I also got this error today, it seems that the `${LATEST_IMAGE:latest}` isn't a valid interpolation. You can modify the `docker-compose.prod.yml` though:
1. go to `/data/coolify/source`
2. replace the `${LATEST_IMAGE:latest}` in `services.coolify.image` to `latest`: `"ghcr.io/coollabsio/coolify${LATEST_IMAGE:latest}"` -> `"ghcr.io/coollabsio/coolify:latest"`
3. now you can deploy coolify with:
```sh
docker compose --env-file /data/coolify/source/.env -f /data/coolify/source/docker-compose.yml -f /data/coolify/source/docker-compose.prod.yml up -d --pull always --remove-orphans --force-recreate
```

**Comment by supermx1** [comment]
Will try it now

**Comment by supermx1** [comment]
Will try it now

**Comment by codesalatdev** [comment]
Caused by https://github.com/coollabsio/coolify/commit/39ecff9f902b667361c36c6cebf679fb99c62e27#diff-4563fbe997bbf18c3b38ad79c596c57c3ad88361f1dccb8c4f39b429382c06d3L4 which removed a hyphen necessary for default value substitution.

**Comment by andrasbacsai** [comment]
Fixed! Sorry about it!
