### ISSUE TITLE
[Bug]: cannot remove servers from application

### ISSUE THREAD

**Issue by iamEvanYT** [coollabsio/coolify#1749]
### Description

I was playing around with Coolify, and selected a network from localhost where it was displayed as a website.
After that, I tried removing it, but it doesn't work and Coolify thought I was removing the main instance of the application,

### Minimal Reproduction (if possible, example repository)

Create a new network
Select it in servers tab in an application
Try to remove it, it doesn't work.

### Exception or Error

![image](https://github.com/coollabsio/coolify/assets/47493765/dfaf14f7-fd0a-49d1-af05-b06e9c2e3dd5)

### Version

v4.0.0-beta.218

**Comment by andrasbacsai** [comment]
Oops. You should not able to add the same server twice. Fixing in the next version (you can also be able to remove that one in v219).
