### ISSUE TITLE
[Bug]: MongoDB password is not displayed correctly.

### ISSUE THREAD

**Issue by rodyherrera** [coollabsio/coolify#1761]
### Description

For some time now I have installed Coolify on my server, with the aim of centralizing some services, one of them being a MongoDB database. I don't remember what version I had when I downloaded Coolify, but the times I entered the platform and the notification appeared that there was a new version available that I could install with a single click, I did it, I did it a couple of times so far. A couple of weeks ago, I needed the access credentials of my database, to implement it in an application, when I was surprised that I was getting a lot of strange characters in "Connection String" and "Root Password", I just didn't I could have access to my database password because the password was not loading as it should. Luckily, I already had several applications running on my server that had that password as environment variables, so I was able to access it, luckily, otherwise I would have lost in every aspect. I don't know what really happened, I assume it was when I updated Coolify.

![Screenshot from 2024-02-18 19-25-57](https://github.com/coollabsio/coolify/assets/69746956/71211e10-3518-4e5e-8109-369c6ef3cec4)

### Minimal Reproduction (if possible, example repository)

Deploy a MongoDB database in previous versions, migrate to newer versions.

### Version

v3.12.36

**Comment by andrasbacsai** [comment]
I believe you are facing this problem: https://docs.coollabs.io/coolify-v3/rollsecretkey#roll-secret-key

Let me know if you need help to revert your database.
