### ISSUE TITLE
[Bug]: Cannot use docker-compose file of Sentry

### ISSUE THREAD

**Issue by dericdesta** [coollabsio/coolify#1771]
### Description

Hi Andras,
thank you for this great project! Keep up the good work!

I want to deploy Sentry self-hosted, but unfortunately, the (quite complex) docker-compose file breaks Coolify.
I get the following error if I want to rename the docker compose location to `/docker-compose.yml` (instead of the default `/docker-compose.yaml`) and reload the compose file.
```
Error occured
Call to a member function value() on array
```

Here's Sentry's [docker-compose file](https://github.com/getsentry/self-hosted/blob/master/docker-compose.yml)

Best, Frederic

### Minimal Reproduction (if possible, example repository)

1. Deploy new docker compose stack for [Sentry](https://github.com/getsentry/self-hosted) on branch master (i.e., new resource, public repository, ..., `https://github.com/getsentry/self-hosted/tree/master` as repository URL)
2. Change docker compose location to `/docker-compose.yml`
3. Click save

### Exception or Error

Error via Popup:
```
Error occured
Call to a member function value() on array
```

### Version

v4.0.0-beta.221

**Comment by dericdesta** [comment]
Is it due to the YAML anchors and aliases? When I look at the docker compose file of, e.g., Formbricks that is included in Coolify, all the anchors and aliases (as they appear in the docker compose file provided by Formbricks) are expanded and thus removed completely.

**Comment by andrasbacsai** [comment]
The sentry compose cannot be used as-is, as it requires a prebuilt image.
