### ISSUE TITLE
[Bug]: log drain isn't sending server_name anymore

### ISSUE THREAD

**Issue by unpseudocomplique** [coollabsio/coolify#1781]
### Description

At first logs were sent to new relic with the server_name variable witch was great to filter logs but look like it's not the case anymore.
It's still working for existing servers / resource, but discovered this when added a new server and new resource.
new server created : 
![image](https://github.com/coollabsio/coolify/assets/69119668/6c5a97aa-338d-471b-b6d5-b0bba3afb026)

old still working
![image](https://github.com/coollabsio/coolify/assets/69119668/5b99d890-8d83-4e6f-a799-747955b71e64)

### Minimal Reproduction (if possible, example repository)

Just added a new server

### Version

224

**Comment by andrasbacsai** [comment]
Just checked with a newly configured log drain, and it is there for me.
![image](https://github.com/coollabsio/coolify/assets/5845193/53ccab4c-5c8e-4b93-a9cc-c0653ed34fd3)


Coolify configures it like [this](https://github.com/coollabsio/coolify/blob/main/app/Actions/Server/InstallLogDrain.php#L53):

```
[FILTER]
    Name                modify
    Match               *
    Set                 server_name {$server->name}
```

Can you please check the following file on the server `/data/coolify/log-drains/fluent-bit.conf`? 

It should have the currently running / last configured log drain configuration.

**Comment by andrasbacsai** [comment]
Please reopen if you have new information.
Due to inactivity, I'm closing this issue. However, if the problem persists, please reopen the issue. Thanks!
