### ISSUE TITLE
[Bug]: Preview deployment not taking `Dockerfile Location` into consideration

### ISSUE THREAD

**Issue by baptisteArno** [coollabsio/coolify#1782]
### Description

Whenever I try to deploy a pull request as a preview, it tries to build using the default Dockerfile I have in my repo. But I specified a custom Dockerfile location.

It works for the main deployment though.

https://www.loom.com/share/cda7ee95b0484853afe6b479da948a82

### Minimal Reproduction (if possible, example repository)

https://github.com/baptisteArno/typebot.io

### Version

v4.0.0-beta.224

**Comment by andrasbacsai** [comment]
Thanks for reporting! Will be fixed in #1783!
