### ISSUE TITLE
[Bug]: Deployment container logs not appearing in the Logs tab

### ISSUE THREAD

**Issue by baptisteArno** [coollabsio/coolify#1784]
### Description

I don't know why I can't see any deployment container logs in my Coolify dashboard:

https://www.loom.com/share/d9edd7b583914e5db97c2c73768672a4

### Minimal Reproduction (if possible, example repository)

https://github.com/baptisteArno/typebot.io/pull/1200

### Version

v4.0.0-beta.226

**Comment by andrasbacsai** [comment]
Love your reports. I wish all bug reports were this good. :)

To view pull request logs was a missing feature, but added in #1786.

**Comment by baptisteArno** [comment]
That's awesome, thank you for the swift fixes

> Love your reports. I wish all bug reports were this good. :)

Haha, I know I wish for that too, that's why I do it that way 😂
