### ISSUE TITLE
Grist

### ISSUE THREAD

**Issue by andrasbacsai** [coollabsio/coolify#179]
https://github.com/gristlabs/grist-core

**Comment by compgeniuses** [comment]
@andrasbacsai   Kindly Add and Vote for this request here: https://feedback.coolify.io/

**Comment by andrasbacsai** [comment]
Closing this one in favor of: https://feedback.coolify.io/posts/28/service-grist-spreadsheet-if-airtable-excel-and-google-sheets-had-a-baby
