### ISSUE TITLE
[Bug]: v4.0.0-beta.229 broken CSS

### ISSUE THREAD

**Issue by killa-kyle** [coollabsio/coolify#1794]
### Description

Hi, I clicked the update icon (heart) on my dashboard today and it updated to [v4.0.0-beta.229](https://github.com/coollabsio/coolify/releases/tag/v4.0.0-beta.229), but the css is completely broken. I've restarted the VPS and still seeing the issue

![dashboard v4 0 0-beta-229](https://github.com/coollabsio/coolify/assets/6319238/d285d541-f9c5-41a1-a193-1d4915f20999)

### Minimal Reproduction (if possible, example repository)

update to v4.0.0-beta.229 via the in app icon

### Version

v4.0.0-beta.229

**Comment by killa-kyle** [comment]
reverting to beta 228 with `curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash -s 4.0.0-beta.228` has fixed this issue for me

**Comment by andrasbacsai** [comment]
Please try to update to the latest version, and if it still occurs, let me know.
