### ISSUE TITLE
Support aarch64 in installer

### ISSUE THREAD

**Issue by Arsen6331** [coollabsio/coolify#18]
Running the automatic installer on my aarch64 SBC results in `Exec format error`, seemingly due to the binary downloaded by the install script being compiled for x86_64.

**Comment by andrasbacsai** [comment]
Yes, you are right. It's compiled for x86_64. You can check the messy code [here](https://github.com/coollabsio/coollabs-cli-installers). 😁

I would like to rewrite it to rust soon, as the binary is huge (nodejs is bundled in it). With rust, I could support different architectures.

**Comment by andrasbacsai** [comment]
We have a new installer. Could you please test it out on an aarch64 based system?

As I said previously, it is not written in Rust, as I said previously, because I rethought it and the installer is web-based.

**Comment by Arsen6331** [comment]
I am currently trying the installer. It seems to be trying to install docker. I already have docker installed. It should check whether the docker command exists and not install if it does.

**Comment by Arsen6331** [comment]
The installer itself does seem to be working, but the docker container is made for x86_64, causing the following error:
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
standard_init_linux.go:219: exec user process caused: exec format error
```

**Comment by dndrheadof** [comment]
yeah, same problem

**Comment by Soneji** [comment]
Hi all, I too would love to see coolify for ARM. 

I found this article which makes it quite easy to implement multi-arch builds with GitHub Actions and a tool called Docker BuildX (you should probably skip to the bit where it says "The simple way with docker buildx" -> https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

**Comment by ErSauravAdhikari** [comment]
I would love to see this feature as well.

**Comment by phiberber** [comment]
Any progress on this? I'm trying to install it in an Oracle ARM VPS:

```
Restarting docker daemon...
Installing docker-compose CLI plugin...
Found .env file of Coolify. Using it during setup.
Installing Coolify...
docker.io/coollabsio/coolify:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

**Comment by andrasbacsai** [comment]
The ARM support is in beta, you can try it out! :)
