### ISSUE TITLE
[Bug]: Error on add user to a team after remove him from same team

### ISSUE THREAD

**Issue by klawdyo** [coollabsio/coolify#1800]
### Description

Error on add user to a team after remove him from same team

### Minimal Reproduction (if possible, example repository)

I had two users in my team. 
I removed one, then I added him again using same e-mail.
He receives e-mail with invitation link but on open, the below error is shown.

### Exception or Error

![image](https://github.com/coollabsio/coolify/assets/100168/56b697b5-ff0a-45a0-9902-3f8dcfacce25)

### Version

v4.0.0-beta.230

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.

**Comment by andrasbacsai** [comment]
Can you please check with updated version? If it still occurs, please let me know.

**Comment by klawdyo** [comment]
## 1. This error is show when entering on page team/members.
![image](https://github.com/coollabsio/coolify/assets/100168/210e9e6f-27e5-44ca-8a7f-ec4b64cfd252)

## 2. I am using v4.0.0-beta.230 and update button is hidden. How can I force update?
![image](https://github.com/coollabsio/coolify/assets/100168/8d8c3522-678e-4407-8de6-cc335729de12)

## 3. I can't remove another server.
![image](https://github.com/coollabsio/coolify/assets/100168/333467c8-4d03-4f95-a5a8-5b17c7025829)


# Question

Maybe this 3 errors are related with this issue, @andrasbacsai .

**Comment by klawdyo** [comment]
A new one.
![image](https://github.com/coollabsio/coolify/assets/100168/f6948ead-ef0f-442c-ad90-b8a0758901c9)


I was validating another server and this message was shown.

**Comment by klawdyo** [comment]
And now...
![image](https://github.com/coollabsio/coolify/assets/100168/2825dc8d-4b77-4d79-8df6-5e7053cb01b9)

No one server is listed. 
The systems is working, but coolify isn't.
