### ISSUE TITLE
[Bug]: Error 500 popup when refreshing the status of a service

### ISSUE THREAD

**Issue by rastiqdev** [coollabsio/coolify#1801]
### Description

On a service, when refreshing the status, a popup with a 500 status code will appear.
The popup and the 500 status code seem to come from a request made to `https://<configured_coolify_domain>/livewire/update`.

### Minimal Reproduction (if possible, example repository)

1. Create a service (for example Uptime Kuma, it's the one I tested)
2. Start it
3. Click on the button to refresh the status

### Exception or Error

`Error: Unable to call component method. Public method [check_status] not found on component`

### Version

v4.0.0-beta.230

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.
