### ISSUE TITLE
Add SMTP/Email feature

### ISSUE THREAD

**Issue by andrasbacsai** [coollabsio/coolify#181]

**Comment by hrichiksite** [comment]
You can self-host an email server but most of the time port 25 is blocked so it would not work. A third-party email service could do the work like SendGrid, it has a pretty good free tier and other things.

**Comment by andrasbacsai** [comment]
Yes, thinking of adding both. SMTP and 3rd party email services, like SendGrid and Mailgun.

**Comment by hrichiksite** [comment]
you can give an option to self-host the email server if port 25 is not blocked for that you can check by sending a test mail to an address that you created for test like in temp-mail from that server without first installing the mail server like [mailcow](https://mailcow.email/) using a npm package I used that is https://www.npmjs.com/package/sendmail

**Comment by andrasbacsai** [comment]
It is available in v4.

I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
