### ISSUE TITLE
[Bug]: Attempting to install on AlmaLinux 8 using script, Informed unsupported despite documentation

### ISSUE THREAD

**Issue by Costigan-Stephen** [coollabsio/coolify#1810]
### Description

While attempting the command on my AlmaLinux VPS:

`[root@server ~]# curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash`

I am left with the error:

`This script only supports Debian, Redhat, Arch Linux, or SLES based operating systems for now.`

AlmaLinux is a Redhat distribution, which is confirmed by the documentation (https://coolify.io/docs/installation), which states:

### Supported OS

Debian based Linux distributions (Debian, Ubuntu, etc.)
**Redhat based Linux distributions (CentOS, Fedora, Redhat, AlmaLinux, Rocky etc.)**
SUSE based Linux distributions (SLES, SUSE, openSUSE, etc.)
Arch Linux
Raspberry Pi OS (Raspbian)

Is there any reason I can't run the script as expected?

### Minimal Reproduction (if possible, example repository)

Ran install script, had error

### Exception or Error

This script only supports Debian, Redhat, Arch Linux, or SLES based operating systems for now.

### Version

pre-install latest

**Comment by andrasbacsai** [comment]
Fixed the installation script. Please try again.

**Comment by Costigan-Stephen** [comment]
You are a scholar and a gentleman, thank you for your service

**Comment by Costigan-Stephen** [comment]
The script seems to work now, but the server connection fails for the same reason. Any advice?
