### ISSUE TITLE
[Bug]: No automatic deploys for public repository + docker compose

### ISSUE THREAD

**Issue by AlejandroAkbal** [coollabsio/coolify#1822]
### Description

Could it be because it uses the master branch? Instead of main as nowadays?

### Minimal Reproduction (if possible, example repository)

Use this repo: https://github.com/AlejandroAkbal/old.akbal.dev/tree/master

General:
![image](https://github.com/coollabsio/coolify/assets/37181533/9d9815d2-bf53-41cf-96ff-c96334a6589e)
Advanced
![image](https://github.com/coollabsio/coolify/assets/37181533/bb540449-0a31-4d67-bbec-002e211ab178)
Environment variables
![image](https://github.com/coollabsio/coolify/assets/37181533/86c50aa7-4afe-4066-8d40-92a075d1ae99)
Source
![image](https://github.com/coollabsio/coolify/assets/37181533/525c53eb-dbfe-4881-ab8b-959bbb07c7f6)

### Exception or Error

No automatic deploys when git push

### Version

v4.0.0-beta.236

**Comment by andrasbacsai** [comment]
To get automatic git deployments for public repositories, you must:

- Use it through a GitHub App.
- Or configure a manual webhook under `Webhooks` menu.
