### ISSUE TITLE
[Bug]: Can not access Resource after git Source was deleted

### ISSUE THREAD

**Issue by ChiefORZ** [coollabsio/coolify#1827]
### Description

I deleted a source, because the resource could not access the repository on github. After that i have no possibility to access the resource - it will always result in an 500 error

### Minimal Reproduction (if possible, example repository)

Create a **resource** with a github resource connected to it. Go to **sources** and delete the git source that you just selected for the resource. Go back to the resources and try to click on it

### Exception or Error

```
Error: Attempt to read property "name" on null (View: /var/www/html/resources/views/livewire/project/application/source.blade.php) (View: /var/www/html/resources/views/livewire/project/application/source.blade.php)
```

### Version

4.0.0-beta.236

**Comment by ChiefORZ** [comment]
oh i think a created an resource with **Private Repository (with deploy key)** - i did not see the other option **Private Repository (with GitHub App)** - thats why i had to enter the url to the repository manually and it could never access it...
side question: do i have a possibility to access the database to remove this resource somehow? because now i get an duplicate key error when trying to add another resource with the same Domain

**Comment by andrasbacsai** [comment]
Oh, I will fix this.

Until then, you can SSH into your server (where Coolify is running) and execute this command: https://coolify.io/docs/commands#delete-service
