### ISSUE TITLE
[Bug]: postgres database is unreachable locally

### ISSUE THREAD

**Issue by treboryx** [coollabsio/coolify#1837]
### Description

A new postgres database is unreachable on the local network and you must do the following manually:

`docker network connect <network name> <docker name>`

This is potentially an issue with other containers too?

### Minimal Reproduction (if possible, example repository)

Just create a new database and try to connect to it from your application

### Version

v4.0.0-beta.236

**Comment by andrasbacsai** [comment]
What do you mean by "local network"?

If you create a database, for example, in the default Docker network called `coolify`, only applications in the same network could reach that database.

If you make the database public, it can be reached from anywhere.

**Comment by ytsdv** [comment]
Same issue here with the pocketbase service, selecting a network in the new resource wizard doesn't automatically add pocketbase to it. Only solution seems to be the workaround from the discord thread.

**Comment by nasrulgunawan** [comment]
I am facing the same issue. I have two applications running on the same network (coolify). One application can connect to the PostgreSQL internally, but the other application cannot connect, showing the error `could not translate host name "postgres-container-name" to address: Name or service not known`.

I have tested on self-hosted and cloud

**Comment by hserranome** [comment]
Same here. No way to connect to a database from another resource other than making it publicly available.

**Comment by x032205** [comment]
Same issue but with Redis.

**Comment by andrasbacsai** [comment]
This is already solved. Let me know if it still does not work.

**Comment by baatten** [comment]
I can into this problem. I can't connect to the db unless I use public address. I don't know how to solve this. I tried to use the simplest form of coolify I could. tried to delete both the web app (node) and the Postgres db but I can't connect locally. How can I solve this?

**Comment by andrasbacsai** [comment]
I will check it again. As I tested, it was working.

**Comment by baatten** [comment]
> I ran into this problem. I can't connect to the db unless I use public address. I don't know how to solve this. I tried to use the simplest form of coolify I could. tried to delete both the web app (node) and the Postgres db but I can't connect locally. How can I solve this?

Our issues were due to a limitation of using nixpack. as told by @andrasbacsai nixpack is not supporting containerisation. We will start to use docker build instead. Thanks again for directions Andras :-)

**Comment by stefnba** [comment]
I have the same issue but not with posgres but with a FastAPI docker compose application. The postgres was automatically added to network "coolify" but not the FastAPI app. 

After manually running `docker network connect coolify app-qgsk8so-081040975032`, it now works.

**Comment by jhonmolano09** [comment]
> I have the same issue but not with posgres but with a FastAPI docker compose application. The postgres was automatically added to network "coolify" but not the FastAPI app.
> 
> After manually running `docker network connect coolify app-qgsk8so-081040975032`, it now works.

Same problem here, when deploying Docker compose apps
