### ISSUE TITLE
[Bug]: Typo in Docker-Compose File causes UI Bug

### ISSUE THREAD

**Issue by garytube** [coollabsio/coolify#1838]
### Description

I made a typo in my Docker Compose file, and now I can't edit the file anymore. Every 4 seconds, Coolify tries to validate the file and calls https://xxxdev/livewire/update, which in turn renders a large overlay that prevents me from editing the file.

<img width="949" alt="image" src="https://github.com/coollabsio/coolify/assets/3823504/15c9aa12-1984-4b70-b731-29c40444be8d">

You need to click the outside of the overlay and be very fast and edit your compose file

<img width="544" alt="image" src="https://github.com/coollabsio/coolify/assets/3823504/75c15594-1215-4d31-b2c7-2f6f132946fa">

### Minimal Reproduction (if possible, example repository)

1. Create a new Resource - Based on a Docker-Compose File
2. Edit Compose file and make it invalid (I <3 yml )
3. pop-up should appear every 4 secs

### Version

236

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.
