### ISSUE TITLE
Doesn't recognize my private repository until I explicitly set the ssh:// protocol

### ISSUE THREAD

**Issue by misaelvillaverde** [coollabsio/coolify#1839]
### Description

I wan't able to deploy my private repository project.

### Minimal Reproduction (if possible, example repository)

The documentation: https://coolify.io/docs/git-providers/github/integration#with-deploy-keys, specifies that it is required to send the git route with the ssh protocol aka `git@github.com/...`, instead of https.

That doesn't work and throws the error: `git@github.com/...` does not appear to be a git repository.

To fix the issue I had to: `ssh://git@github.com/...`

I think this should be stated on the documentation.

### Exception or Error

`git@github.com/...` does not appear to be a git repository.

### Version

v4.0.0-beta.236

**Comment by andrasbacsai** [comment]
Oh, that is a typo in the docs. Fixing.

`git@github.com/coollabsio/coolify-examples.git` -> wrong
`git@github.com:coollabsio/coolify-examples.git` -> working, see the `:` difference.
