### ISSUE TITLE
[Bug]: Supabase Service Minio Create Bucket Unhealthy

### ISSUE THREAD

**Issue by ejscheepers** [coollabsio/coolify#1850]
### Description

When you create new Supabase Instance, one Minio Create Bucket Container is unhealthy. Cannot store sql queries and some other errors which might be related. 

![IMG_2634](https://github.com/coollabsio/coolify/assets/52255287/e5cf7503-fb9f-43c6-adec-50afb759f22f)

### Minimal Reproduction (if possible, example repository)

Add Supabase service on Hetzner Arm Server. 

### Version

V4.0.0 Beta.239

**Comment by andrasbacsai** [comment]
That is normal as its purpose is to create the bucket, that's all. After that point, it will exit.

However, I pushed a fix to the Supabase service that will fix a few issues related to real-time events and Minio.
