### ISSUE TITLE
Cannot deploy a service on the demo site

### ISSUE THREAD

**Issue by faierbol** [coollabsio/coolify#186]
Hi,

i have tried to play around a little bit with the application. Overall looks and feels really cool (like the name :D )
I have deployed a vscode server service, on the console it looks like is running but the page http://vscode-test.coolify.io/ gives a 404 error:
This site can’t be reached

**Comment by andrasbacsai** [comment]
Hey,

I've just added an option to use a random subdomain under`*.demo.coolify.io` . Please recreate your service and it will be good!
