### ISSUE TITLE
[Bug]: Could not load base compose file from /docker-compose.yml

### ISSUE THREAD

**Issue by komali2** [coollabsio/coolify#1865]
### Description

For a "Docker Compose" buildpack project, I'm unable to load / parse my `docker-compose.yml` or `docker-compose.prod.yml` files. If I input either of their location, then click "Reload Compose File," I get the error "Could not load base compose file from /docker-compose.yml" or "Could not load base compose file from /docker-compose.prod.yml". 

### Minimal Reproduction (if possible, example repository)

Create an environment with a resource of a public repository, and use this repository: https://codeberg.org/508_dev/game-remix-guesser-backend

In `Build` config area, try to set the docker compose file as either of the ones in the public repo above. `docker-compose.prod.yml` or `docker-compose.yml`. 

Observe the error. 

### Exception or Error

Could not load base compose file from /docker-compose.yml

### Version

v4.0.0-beta.236

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.

**Comment by craigharman** [comment]
This still seems to be a problem? (I'm using a private repo, but have the same issue as above)

**Comment by komali2** [comment]
Oh wow I forgot i made this issue way back when, I'm still having this issue on the latest version: https://github.com/coollabsio/coolify/issues/2962

**Comment by Judaemon** [comment]
Encountered the same issue, which was resolved by changing the file extension from .yml to .yaml.

**Comment by 1day2die** [comment]
ah this is still ongoing. oh man...

**Comment by craigharman** [comment]
@andrasbacsai any update on this one?
