### ISSUE TITLE
Container Healthcheck issue

### ISSUE THREAD

**Issue by sharukhkhanajm** [coollabsio/coolify#1867]
### Description

Hey i am using digitalocean droplet and every time i deploy my app it throws this error

```
OUTPUT:
"starting"
[2024-Mar-20 03:51:50.624769] Attempt 1 of 10 | Healthcheck status: "starting"
[2024-Mar-20 03:51:55.722333]
COMMAND:
docker inspect --format='{{json .State.Health.Status}}' a0kkcwk-034707305162

OUTPUT:
"unhealthy"
[2024-Mar-20 03:51:55.734183] Attempt 2 of 10 | Healthcheck status: "unhealthy"
[2024-Mar-20 03:51:55.803961] Removing old containers.
[2024-Mar-20 03:51:55.835095] New container is not healthy, rolling back to the old container.
[2024-Mar-20 03:51:56.818985] Rolling update completed.
```

if i go Configuration -> Healthchecks and disable it it works.

### Minimal Reproduction (if possible, example repository)

N/A

### Version

v4.0.0-beta.239

**Comment by sharukhkhanajm** [comment]
Update 1:
The issue seems to be fixed after I have deployed my application.

so I first disabled the Healthchecks from the settings and deployed the application successfully then again enabled the Healthchecks setting and redeployed it and it worked.

**Comment by andrasbacsai** [comment]
If it happens again, I will investigate further, but as it is solved, I am closing this now.

**Comment by warflash** [comment]
@andrasbacsai Just letting you know we also ran into this bug today. The workaround "works" but is pretty irritating when just getting started

**Comment by nirvaaha** [comment]
Still doesn't work

**Comment by SirFreddie** [comment]
Same here, disabling the healthcheck works fine.

**Comment by SirFreddie** [comment]
I'm getting the same healthcheck issue. Disabling it seems to be a workaround.

**Comment by ari-party** [comment]
I only tested this solution with Next.js but it might work with others.

Setting the `--hostname` option to `0.0.0.0` on the [Next.js CLI](https://nextjs.org/docs/pages/api-reference/next-cli#production) fixes it
You can also set the `HOSTNAME` env var to `0.0.0.0` if you use the standalone server.

I'm sure this will fix it for many other services as well.

**Comment by swizzmagik** [comment]
+1

> I only tested this solution with Next.js but it might work with others.
> 
> Setting the `--hostname` option to `0.0.0.0` on the [Next.js CLI](https://nextjs.org/docs/pages/api-reference/next-cli#production) fixes it You can also set the `HOSTNAME` env var to `0.0.0.0` if you use the standalone server.
> 
> I'm sure this will fix it for many other services as well.

how do you set this in coolify?

**Comment by ari-party** [comment]
> +1
> 
> > I only tested this solution with Next.js but it might work with others.
> > 
> > Setting the `--hostname` option to `0.0.0.0` on the [Next.js CLI](https://nextjs.org/docs/pages/api-reference/next-cli#production) fixes it You can also set the `HOSTNAME` env var to `0.0.0.0` if you use the standalone server.
> > 
> > I'm sure this will fix it for many other services as well.
> 
> how do you set this in coolify?

Environmental variables -> Preview/Prod -> HOSTNAME

**Comment by x-mass** [comment]
Setting manual healthcheck solved the issue for me. Project -> configuration -> healthchecks.
In both cases logs contain: 
```
[2024-Jul-27 18:23:48.426442] Custom healthcheck found, skipping default healthcheck. 
[2024-Jul-27 18:23:48.428796] Waiting for healthcheck to pass on the new container. 
[2024-Jul-27 18:23:48.430916] Healthcheck URL (inside the container): GET: [http://localhost:80/](http://localhost/) 
[2024-Jul-27 18:23:48.433176] Waiting for the start period (30 seconds) before starting healthcheck.
```
Coolify healthcheck:
<img width="762" alt="image" src="https://github.com/user-attachments/assets/98fd6fd3-2945-4835-b210-5311713edb08">

Dockerfile healthcheck: 
```
HEALTHCHECK --interval=1m --timeout=10s --start-period=30s --retries=3 \
  CMD curl -f http://localhost:80 || exit 1
```
