### ISSUE TITLE
[Bug]: PR deployment: when using a build server, the new docker image is not pulled

### ISSUE THREAD

**Issue by baptisteArno** [coollabsio/coolify#1872]
### Description

I have a PR already deployed (using a build server). When I push new commits and try to deploy the same PR again, it seems the image is not updated.

My guess is that because it's the same image tag name, it won't be pulled again. Am I correct?

### Minimal Reproduction (if possible, example repository)

https://github.com/baptisteArno/typebot.io/pull/1200

### Version

v4.0.0-beta.239

**Comment by baptisteArno** [comment]
I confirm that if I delete the docker image between each PR deployments, it then work.

**Comment by andrasbacsai** [comment]
A bit late, but it will be fixed in the next version.
