### ISSUE TITLE
[Bug]: Git + Docker Compose Buildpack not following port redirection correctly

### ISSUE THREAD

**Issue by AndrewBastin** [coollabsio/coolify#1873]
### Description

When deploying from a Git repo with a Docker Compose buildpack, when setting Docker Compose Service FQDN, the domain is respected but the port mapping given in the text field (for e.g `bla.test.local:3080`) is not respected.

When deploying directly with a Docker Compose, it creates a Service Stack (with its own UI) and that doesn't have the problem when I give the service a domain.

### Minimal Reproduction (if possible, example repository)

Will update with an example reproduction when possible and/or if required.

### Exception or Error

None that I know about, but one notable thing is that the Traefik dashboard doesn't show an HTTP Routers entry for the service deployed from Docker Compose buildpack against a git repo.

### Version

v4.0.0-beta.240

**Comment by allanbraunV** [comment]
Hey @AndrewBastin, can you share how do you solve this problem?
