### ISSUE TITLE
[Bug]: Backups for Supabase postgres container

### ISSUE THREAD

**Issue by hamanuha** [coollabsio/coolify#1875]
### Description

Backups are not enabled for the Supabase postgres container.
I think this can be integrated relatively easy.
I can work on a PR if you can give me a hint where to start.

### Minimal Reproduction (if possible, example repository)

In cloud version create Supabase service from template.

### Version

v4.0.0-beta.240

**Comment by abanobboles** [comment]
I wrote this script:

backup to S3
and only 14 backups on disk:

```
#!/bin/bash


DATE=$(date +%Y%m%d%H%M)
BACKUP_DIR="/root/backup_db"
DB_USER="supabase_admin"
DB_NAME="supabase"
S3_BUCKET="backup"
R2_ENDPOINT="https://xxxxxxxxxxxxxx.r2.cloudflarestorage.com/backup"


docker exec supabase-db-n4sww80 pg_dump -U $DB_USER $DB_NAME > $BACKUP_DIR/backup_db-$DATE.sql


aws s3 cp $BACKUP_DIR/backup_db-$DATE.sql s3://$S3_BUCKET/backup_db-$DATE.sql --endpoint-url=$R2_ENDPOINT


find $BACKUP_DIR -type f -name "*.sql" -printf "%T+ %p\n" | sort -r | tail -n +15 | awk '{ print $2 }' | xargs rm -f
```

**Comment by hamanuha** [comment]
Thanks, but it would be great if this could be implemented in coolify - like the backup option for standalone postgres.

**Comment by sillvva** [comment]
> This will be in the upcoming version. Supabase uses a different postgresql (fork), that is why it was not available.

There doesn't seem to be a way to restore the backup via the UI. Just a download and delete button

**Comment by moby3012** [comment]
Hey andrasbacsai,

first of all - thank you for your incredible work!

For me it looks like the backup functionality for supabase is indeed implemented but it is not possible to get it running for me.

after you've set up a backup job for the supabase postgres container it queues the job and crashes almost immediately with the following error:

Database: postgres
Status: failed
Started At: 2024-07-08 13:14:35
Message: pg_dump: error: query failed: ERROR: permission denied for schema _analytics pg_dump: detail: Query was: LOCK TABLE _analytics.schema_migrations IN ACCESS SHARE MODE
Size: 0 B / 0 kB / 0 MB
Location: N/A

**Comment by alexsandercdm** [comment]
Hey everyone, same issue here, it returns ‘permission denied for schema _analytics’ and I can’t perform the backup of this database instance.
