### ISSUE TITLE
hosting Static Site Generators

### ISSUE THREAD

**Issue by Nico-L** [coollabsio/coolify#188]
Hello,

I am quite pleased to have found coolify, this may help me host small web sites currently hosted at Netlify.

 I am mainly using SSG, in particular [11ty](https://www.11ty.dev/) or [astro.build](https://astro.build/).

I tried to setup a application to the demo instance for an astro app. I linked it to the github repo and launched the app. The issue is that since there is no start command, 'yarn run' throws an error. I tried to add 'yarn build' to the start command but then the application still repeats the build command in a loop.

What I am expecting is that the application build once and then the statics files are served from the published directory. And of course, it should rebuild the site every time a change is pushed to the repo.

Am I missing something?  How can I setup the application?
Thanks

**Comment by andrasbacsai** [comment]
Hey,

All SSG's are supported, but they do not have their own buildpack - yet. 
A buildpack just defines the basic commands, publish directories, and some custom build steps - if necessary.

For 11ty and Astro, you need to choose the `Static` template, as the final app will be static (SSG). 
Set the install/build command (`yarn install` and `yarn build`) and the publish directory to `dist`.

**Comment by andrasbacsai** [comment]
I will add these buildPacks to the next release.

**Comment by Nico-L** [comment]
Great! Thanks!
