### ISSUE TITLE
[Bug ?]: Updates unavailable after 4 days. Is it a bug? 

### ISSUE THREAD

**Issue by klawdyo** [coollabsio/coolify#1881]
### Description

Updates released 4 days ago
![image](https://github.com/coollabsio/coolify/assets/100168/0b45d14e-a9ae-4656-a635-68bd9fecb005)

But unavailable to me
![image](https://github.com/coollabsio/coolify/assets/100168/9d857a2f-16bb-4237-8fec-37a6d1060c8d)

How can I force?

### Minimal Reproduction (if possible, example repository)

My version is 239 and updates to 241 isn't available. I need fix that environment variables with `$`. My payments are broken after migrate one of my systems to coolify. 
The payment token has the pattern: `$asd09a8d0a98dd8adasdasd7a9sd7asda==`. Only `==` is arriving in my api.

### Version

4-beta-239

**Comment by andrasbacsai** [comment]
It is not a bug. I would like to wrap up the UI updates before releasing the new version.

Usually I release asap, but now it's an exception.

**Comment by klawdyo** [comment]
OK. Thank you!
