### ISSUE TITLE
[Bug]: cannot save environment variables in developer mode

### ISSUE THREAD

**Issue by Markus-Ende** [coollabsio/coolify#1882]
### Description

After updating from beta.239 to beta.241, I get an error when trying to save environment variables in development mode, I get the error message below. An very similar error was thrown when loading a docker compose yaml.

Seems like a broken db migration?

### Minimal Reproduction (if possible, example repository)

1. Go to environment variables
2. enter developer view
3. try to add multiple variables 

### Exception or Error

Error: SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "is_multiline" of relation "environment_variables" violates not-null constraint DETAIL: Failing row contains (196, POSTGRES_USER, ......, f, t, 7, 2024-03-22 13:11:41, 2024-03-22 13:11:41, null, null, null, null, null, null, f, null, 4.0.0-beta.239). (Connection: pgsql, SQL: insert into "environment_variables" ("key", "value", "is_build_time", "is_multiline", "application_id", "is_preview", "updated_at", "created_at") values (POSTGRES_USER, ..., 0, ?, 7, 1, 2024-03-22 13:11:41, 2024-03-22 13:11:41) returning "id")

### Version

v4.0.0-beta.241

**Comment by Markus-Ende** [comment]
update: I get the same error, when trying to deploy

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.

**Comment by extronics** [comment]
@andrasbacsai i'm still getting this exact error on beta.255 when loading a `docker-compose.yml` with environment variables like `VARIABLE=${VARIABLE}`

**Comment by noximo** [comment]
Same here. Setting all variables as multiline helps, though I had to do it several times, not all checkbox changes got saved I guess.

**Comment by andrasbacsai** [comment]
I try to replicate the issue, but I cannot. 

Can you make a small video of the whole process (from adding the app to the error)?

**Comment by andrasbacsai** [comment]
I can reproduce now! Fixing in the next version (🤞)

**Comment by andrasbacsai** [comment]
Please confirm that it works now!

**Comment by extronics** [comment]
Loading a docker-compose.yml now works as in it creates the environment variables without complaining. They are, however, not exposed to the actual containers. When i run `env` in a running container, all the environment variables are blank. This might however be a different issue ..
