### ISSUE TITLE
[Bug]: Saving the setting "instance's domain" doesn't show error message in case of a problem

### ISSUE THREAD

**Issue by etranger7** [coollabsio/coolify#1885]
### Description

Any URL I enter into the **"Instance's Domain"** field gets saved and in case of an error, the UI doesn't show the error message like it used to in the previous versions.
It erroneously displays a green check mark.
It should only display this checkmark if obtaining a certificate is successfull.

### Minimal Reproduction (if possible, example repository)

- Install a fresh instance.
- Go to Settings > General
- Enter any random URL in "Instance's Domain" field
- Hit "Save"

### Exception or Error

No errors and that's part of the problem. I should be getting one when I'm entering a domain I don't own.

### Version

v4.0.0-beta.239

**Comment by andrasbacsai** [comment]
Can you please check it again? If the issue still persists, please reopen this issue. Thanks!

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.

**Comment by etranger7** [comment]
Thank you!
