### ISSUE TITLE
[Bug]: UI Error (Dark mode) Environment Variables always light mode

### ISSUE THREAD

**Issue by Cizzl** [coollabsio/coolify#1894]
### Description

Im using [v4.0.0-beta.244](https://github.com/coollabsio/coolify/releases/v4.0.0-beta.244). The dark mode has a bug in Environment Variables.

### Minimal Reproduction (if possible, example repository)

When I go to Environment Variables its always light mode, doesnt matter if I force dark mode or have system as default.

![Screenshot 2024-03-26 132224](https://github.com/coollabsio/coolify/assets/35262437/60b2448d-1603-4346-b129-81c3ae543fc8)

### Version

v4.0.0-beta.244

**Comment by andrasbacsai** [comment]
It is fixed in #1893 (releasing soon).
