### ISSUE TITLE
[Bug]: Duplicate notification on Telegram

### ISSUE THREAD

**Issue by marcosviniciuscl** [coollabsio/coolify#1896]
### Description

When the instance is updated, Telegram notifies the same information twice.

### Minimal Reproduction (if possible, example repository)

When the instance is updated.
![image](https://github.com/coollabsio/coolify/assets/14579288/e4b734c7-4c4e-43a4-b136-9da22280e4a0)

### Version

4.0.0-beta.245

**Comment by baptisteArno** [comment]
Yes also have this

**Comment by marcosviniciuscl** [comment]
@baptisteArno Did you manage to find a solution for this?

**Comment by baptisteArno** [comment]
No, but that's not critical for me 😄

**Comment by the-ebdm** [comment]
I'm getting this with Discord too

**Comment by the-ebdm** [comment]
Okay, it looks like it happens when the update fails. Manually updating it has fixed the issue. I wonder if that means a check needs to be done to see if the update completed successfully before triggering the notification? Or perhaps an update failed notif?

**Comment by Emahhh** [comment]
I'm also getting a lot of notifications on Telegram, even though it seems that the instance has been updated successfully.

![image](https://github.com/coollabsio/coolify/assets/27818313/b3fe8653-0f49-412e-8e59-d3e3bc367d02)
![image](https://github.com/coollabsio/coolify/assets/27818313/5a8eaa4a-704e-41e2-8e4a-1ad3aaf6aeb8)

**Comment by peaklabs-dev** [comment]
Please upgrade to the latest version of v4 and retest if this issue persists as we made a few fixes.
