### ISSUE TITLE
[Bug]: use the resend service as a mail agent get error 500

### ISSUE THREAD

**Issue by sawa-ko** [coollabsio/coolify#1897]
### Description

When configuring resend as an agent for sending emails, with its corresponding api key and enabling its function, when trying to use it you get a 500 error.

### Minimal Reproduction (if possible, example repository)

1. Configure Resend api key and enabled it
2. Try to send the reset password mail

### Exception or Error

![image](https://github.com/coollabsio/coolify/assets/56084970/54c9b20c-e255-4481-8576-1912b9df10d0)

### Version

v4.0.0-beta.245

**Comment by andrasbacsai** [comment]
Are those filled? 


![image](https://github.com/coollabsio/coolify/assets/5845193/24152ab2-7571-425e-8540-ea7984ff28da)

I will add a validation to the UI, so you could not save the resend/smtp credentials without filling those two.

**Comment by sawa-ko** [comment]
@andrasbacsai Yes, it seems that it works now, but resend tells me that I'm in test mode, how do I change that?

**Comment by andrasbacsai** [comment]
> @andrasbacsai Yes, it seems that it works now, but resend tells me that I'm in test mode, how do I change that?

Not sure in that, sorry.
