### ISSUE TITLE
Add Rust or Dockerfile support

### ISSUE THREAD

**Issue by pepoviola** [coollabsio/coolify#19]
Hi @andrasbacsai, first let me say thanks for the awesome work!! 🙌 🙌 

I wonder if I can help you to add `rust` support or if make sense add support for `Dockerfile`s allowing the users to manage the desire container instead of use a buildpacks. If make sense for this project I can try to add support for those and send you a pr.

Again, thanks for the awesome work!!

**Comment by andrasbacsai** [comment]
Hey,

Thank you very much! It really boosts my motivation. 😁

I'm thinking of adding custom `Dockerfile` support, as it opens a lot of opportunities and adds lots of bugs. 😄 
But in parallel with this, I would like to keep the controlled `Dockerfile` as well, as most people do not like to fill them manually.

I'll add some thought later on today or tomorrow. (I may implement it today night - after my kids are sleeping 😅)

**Comment by andrasbacsai** [comment]
I've released a new [version](https://github.com/coollabsio/coolify/releases/tag/v1.0.4), which includes the custom `Dockerfile` feature!

I keep this open for adding the controlled `rust` version.

**Comment by pepoviola** [comment]
Hi @andrasbacsai, I saw the release 🎉🙌 . I can help with the rust version 🦀

**Comment by pepoviola** [comment]
Hi @andrasbacsai, closing here since support for rust already landed in `next` branch, thanks!!
