### ISSUE TITLE
hetzner cloud integration

### ISSUE THREAD

**Issue by faierbol** [coollabsio/coolify#190]
Hi @andrasbacsai hetzner cloud integration will be a nice feature as well :)

**Comment by kris-re** [comment]
Isn't this possible with the upcoming **Remote Docker Engine** destination?

**Comment by andrasbacsai** [comment]
No, `RDE` only connects to remote docker engines, but this request is to create a Hetzner server programmatically from Coolify, for example.

**Comment by zek** [comment]
I'm using docker-machine to create on-demand cloud server for my docker swarm cluster. It's very easy and supports so many providers. However it's deprecated there're only the forks such as gitlab's. So I'm not sure if using docker-machine would be a smart decision. 

What about something like Ansible, Terraform?

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
