### ISSUE TITLE
[Bug]: Light theme deployment logs color

### ISSUE THREAD

**Issue by baptisteArno** [coollabsio/coolify#1902]
### Description

Gray color not accessible and red color not the best for debug logs:

![CleanShot 2024-03-27 at 10 12 03](https://github.com/coollabsio/coolify/assets/16015833/69b164c3-662c-414a-b6b3-fe0ccdaf7ffb)

### Minimal Reproduction (if possible, example repository)

-

### Version

v4.0.0-beta.245

**Comment by andrasbacsai** [comment]
Oh haha, thanks!
This will be fixed in the upcoming version.
