### ISSUE TITLE
[Bug]: Environment variables with `$`

### ISSUE THREAD

**Issue by klawdyo** [coollabsio/coolify#1918]
### This is my environment variable starting with `$`

![image](https://github.com/coollabsio/coolify/assets/100168/67054559-de2a-4cec-8fa6-5fd0117c12b7)

### This is how that value arrives in my code. Just `==`
![image](https://github.com/coollabsio/coolify/assets/100168/b7c2c091-8b9c-4cbf-b65b-ffa96f5be257)

After many redeployments, even after updating coolify, the error still remains. My financial gateway has been down for 15 days since I migrated my Google Cloud API to Coolify.
How can I resolve this? I've been waiting for the bugs related to environment variables to be resolved for several days, but I've updated now and the error is the same.

### Version

v4.0.0-beta.248

**Comment by klawdyo** [comment]
![image](https://github.com/coollabsio/coolify/assets/100168/ebec1fcf-dae6-4412-ac49-92cb261e611e)

**Comment by AspireOne** [comment]
For anyone that needs a solution right now, since I failed to rectify it via Coolify environmental variables, I pre-processed the variable like so:

```js
function unescapeJsonString(possiblyEscapedJsonString) {
  let correctedString = possiblyEscapedJsonString;

  // Check and conditionally remove leading and trailing single quotes
  if (correctedString.startsWith("'") && correctedString.endsWith("'")) {
    correctedString = correctedString.slice(1, -1);
  }

  // Replace escaped double quotes with actual double quotes only if needed
  if (correctedString.includes('\\"')) {
    correctedString = correctedString.replace(/\\"/g, '"');
  }

  // Replace escaped newlines with actual newline characters only if needed
  if (correctedString.includes("\\\\n")) {
    correctedString = correctedString.replace(/\\\\n/g, "\\n");
  }

  // Attempt to parse the corrected string into a JSON object
  try {
    return JSON.parse(correctedString);
  } catch (error) {
    throw new Error(`Error un-escaping JSON string: ${error}`);
  }
}
```

**Comment by andrasbacsai** [comment]
There has been an update on the environment variable parsing part a few versions before.

I guess your environment variable was created before that. 

**Try to delete the environment variable from Coolify's UI and recreate it.**

(I would not like to break existing environment variables by the fix, so I decided that environment variables created before the fix would stay as-is, but newly created environment variables have the fix.)

**Comment by klawdyo** [comment]
> There has been an update on the environment variable parsing part a few versions before.
> 
> I guess your environment variable was created before that. 
> 
> **Try to delete the environment variable from Coolify's UI,recreate it and restart your application.**
> 
> (I would not like to break existing environment variables by the fix, so I decided that environment variables created before the fix would stay as-is, but newly created environment variables have the fix.)

I created a new variable with a value started with `$`, restarted a container after that and then, run `env` on command screen.  Same error.

**Comment by andrasbacsai** [comment]
Ah, I found the issue. 
This will be fixed in the upcoming version.

**Comment by eden-lane** [comment]
Sorry, I still can't pass build-time variables to my docker-compose file. What could be the problem?

1. I've added a variable using coolify UI

![CleanShot 2024-04-14 at 18 47 27@2x](https://github.com/coollabsio/coolify/assets/2963477/2cc58105-6e18-4186-a01b-58732ffd9e22)

2. I've added env var to my docker-compose file:
![CleanShot 2024-04-14 at 18 48 33@2x](https://github.com/coollabsio/coolify/assets/2963477/1f425ffd-36ff-4e09-bd58-4c78bf51ce00)

3. I've added env var to my Dockerfile:
![CleanShot 2024-04-14 at 18 49 07@2x](https://github.com/coollabsio/coolify/assets/2963477/6bd0f9c9-0b80-4079-9163-6744d54892ea)

**Comment by ton77v** [comment]
> Sorry, I still can't pass build-time variables to my docker-compose file. What could be the problem? Just installed coolify, so I shouldn't have the previous version bug.
> 
>     1. I've added a variable using coolify UI
> 
> 
> ![CleanShot 2024-04-14 at 18 47 27@2x](https://private-user-images.githubusercontent.com/2963477/322289253-2cc58105-6e18-4186-a01b-58732ffd9e22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NDc3MDUsIm5iZiI6MTcxNDU0NzQwNSwicGF0aCI6Ii8yOTYzNDc3LzMyMjI4OTI1My0yY2M1ODEwNS02ZTE4LTQxODYtYTAxYi01ODczMmZmZDllMjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDFUMDcxMDA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDMwZWZlYzI1YTZkYzc1ZGRlMmM0NGFiNjdhN2QzZWQyMjg5N2IwMGY3MjhmOGEyNzg4MzhiMDk4M2E4ZTQ1MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tStjj59IyAbLZGK7wIJrcR1fNG644vaarPUXlbj1CY8)
> 
>     2. I've added env var to my docker-compose file:
>        ![CleanShot 2024-04-14 at 18 48 33@2x](https://private-user-images.githubusercontent.com/2963477/322289313-1f425ffd-36ff-4e09-bd58-4c78bf51ce00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NDc3MDUsIm5iZiI6MTcxNDU0NzQwNSwicGF0aCI6Ii8yOTYzNDc3LzMyMjI4OTMxMy0xZjQyNWZmZC0zNmZmLTRlMDktYmQ1OC00Yzc4YmY1MWNlMDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDFUMDcxMDA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWU4ODlhZDM4NWRiM2M3MmJiN2MzYTIyYTk3YzRlNGVkM2Y5N2I5YWJmOTRkMTllZGU3OWI1ODUxYzI1YjkxZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.e-hsFmseLVJWUmZJTJGOzICa6XiCqRpvrZqFqiG9ZzQ)
> 
>     3. I've added env var to my Dockerfile:
>        ![CleanShot 2024-04-14 at 18 49 07@2x](https://private-user-images.githubusercontent.com/2963477/322289347-6bd0f9c9-0b80-4079-9163-6744d54892ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NDc3MDUsIm5iZiI6MTcxNDU0NzQwNSwicGF0aCI6Ii8yOTYzNDc3LzMyMjI4OTM0Ny02YmQwZjljOS0wYjgwLTQwNzktOTE2My02NzQ0ZDU0ODkyZWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDFUMDcxMDA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGY4NWI3Yjg1YTEzNmM4MDEzYWVkOTYyYmJmNTQ3ZmQzZWNhOGViM2MyNTY3MDY4YzlmNTEzNjgzMGU3YjMwZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3NtdXTAJxDPalidD3Ai8_IIlRx3Z1D2-e-9g6RvCkIM)

You should also add it as build argument for Dockerfile e.g.
```
    build:
      dockerfile: .
      args:
        VAR: ${VAR:?VAR not set}
```

And in Dockerfile:
```
ARG VAR

# use directly as $VAR or promote to env variable like so:
ENV VAR $VAR

```
