### ISSUE TITLE
Error when creating a new Github App

### ISSUE THREAD

**Issue by faierbol** [coollabsio/coolify#192]
Hello, 

Trying to create a new GitHub App on the demo instance i receive the bellow error:

What‽
Your browser did something unexpected. Please try again. If the error continues, try disabling all browser extensions.

Tried on 3 different browsers with the same results:
Brave
Chrome
Edge

OS:
Windows 11

**Comment by andrasbacsai** [comment]
I just created a new GitHub App, and it works as expected. Which phase do you get this error?

Here is what the flow looks like:

1. Redirected to Github
2. Sets an app name on Github
3. Redirected back to demo coolify instance

**Comment by faierbol** [comment]
On the 1st step. at the redirect pop up i get the error:
What‽
Your browser did something unexpected. Please try again. If the error continues, try disabling all browser extensions.

**Comment by andrasbacsai** [comment]
Not sure what the problem is, but it is not related to Coolify IMO. Also, I cannot replicate it. 

Can you please try it in incognito mode as well?

**Comment by faierbol** [comment]
i have tried your suggestion but unfortunately i am no longer able to login into my test account > email: george.boncea@gmail.com

**Comment by faierbol** [comment]
Error:
Wrong password or email address.

I am using a dummy password which is quite easy to remember and its also saved in the browser credentials

**Comment by andrasbacsai** [comment]
I've reinstalled the demo server as there were tons of users/stuff created on it and it became overloaded.

You probably need to register again.

**Comment by faierbol** [comment]
HI, i have tried it already yesterday because i thought at the same thing that the db was cleared or smth but it seems that registering on the site is disabled:
Registration disabled by administrator.

**Comment by andrasbacsai** [comment]
Haha, fixed.

**Comment by faierbol** [comment]
this is the redirect link https://github.com/organizations/ielo/settings/apps/new?state=cl06m7ev2356430onv5snnhliw

**Comment by faierbol** [comment]
i just tried on my mac pro macOS 12 Monterey on safari and brave and also in incognito with the same results :/

**Comment by faierbol** [comment]
Ookay, so the issue is the following:
When setting up Git Source > GitHub.com i wanted to use my organization, removing the organization worked.

What i am doing wrong here?

**Comment by faierbol** [comment]
pfff, sometimes i am soooo stupid :))))
I have entered the wrong org name, instead of ielo i just entered the correct one ielo-ro and it worked :)
Sorry but it was my mistake :/

**Comment by andrasbacsai** [comment]
Haha, sh*t happens! 😅 I'm glad it's solved because I had no idea why it was failing 😁

**Comment by faierbol** [comment]
Classic customer mistake = problems in the application scenario, and this time i was on the customer side :))))
