### ISSUE TITLE
[Bug]: missing image in docs

### ISSUE THREAD

**Issue by ImLunaHey** [coollabsio/coolify#1921]
### Description

An image in the docs is missing
<img width="709" alt="Screenshot 2024-03-29 at 12 46 42 pm" src="https://github.com/coollabsio/coolify/assets/105922175/4e6ca252-db3e-4c9c-bf1c-037ea90e8510">

### Minimal Reproduction (if possible, example repository)

goto https://coolify.io/docs/knowledge-base/cloudflare/tunnels#automated and scroll to step 7

### Version

N/A

**Comment by amerkestijn** [comment]
Pull request has been submitted to fix this.

**Comment by andrasbacsai** [comment]
PR merged. Thank you!
