### ISSUE TITLE
[Bug]: "Error too many requests" pop-down from clicking the upgrade button too many times shows template strings instead of time

### ISSUE THREAD

**Issue by komali2** [coollabsio/coolify#1923]
### Description

If you spam click the "update" button in the bottom-left when there's a new version available, a pop-down modal will display indicating when you can click the button again, however, no time is displayed. 

This may be fixed in a newer version, I'm not sure, I clicked the button too many times and can't upgrade, lol. 

### Minimal Reproduction (if possible, example repository)

Be running an older version of coolify, e.g. v4.0.0-beta.236.

Click the pink/red up-arrow button in the bottom left corner (tooltip: "New version available").

Click it again.

Click more.

Eventually, a modal will drop down from the top. 

### Exception or Error

![2024-03-29-185819_811x335_scrot](https://github.com/coollabsio/coolify/assets/8533113/9208998c-e082-41d0-941a-7ea0341baf5f)

### Version

v4.0.0-beta.236

**Comment by andrasbacsai** [comment]
The template literal already fixed, but I will add a fine tune to the upgrade process in the next version.
