### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by cabaalexander** [coollabsio/coolify#1927]
### Description

Github is timing out

### Minimal Reproduction (if possible, example repository)

After 5 days github is not reachable from coolify
![image](https://github.com/coollabsio/coolify/assets/12496574/ddd046e2-f55c-4e08-bd0a-aa1fa76b1a3f)

### Version

v4.0.0-beta.248

**Comment by maietta** [comment]
You should log into your server and see if you can manually resolve the hostname for https://api.github.com/.

Could be your server's DNS provider isn't able to resolve the hostname.

**Comment by cabaalexander** [comment]
My server running all docker images has DNS access to github 👇. The server it is pointing (10.0.0.37) is a `pihole` server.
![image](https://github.com/coollabsio/coolify/assets/12496574/cf15f1b4-d295-47c9-a75f-1211fde78d91)

The one container I see is having some connections issues is `coolify`:
![image](https://github.com/coollabsio/coolify/assets/12496574/391e6eb8-9fa4-481d-a82a-c73f64a6b2e1)

**Comment by cabaalexander** [comment]
It seems all my containers cannot resolve domain names 🤔

**Comment by maietta** [comment]
Then it's not an issue with Coolify.

Did you restart your server?

**Comment by cabaalexander** [comment]
Yeah not a coolify thing. I did restart my server a couple of times and still the containers does not have access to the internet. Something must be wrong with docker a docker network.

A basic command to create a container and install curl is failing me on my server but it works fine on my machine, example:

Server:
```
docker run --rm -it alpine apk add curl && sh

fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/main/aarch64/APKINDEX.tar.gz
WARNING: updating and opening https://dl-cdn.alpinelinux.org/alpine/v3.19/main: temporary error (try again later)
fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/community/aarch64/APKINDEX.tar.gz
WARNING: updating and opening https://dl-cdn.alpinelinux.org/alpine/v3.19/community: temporary error (try again later)
ERROR: unable to select packages:
  curl (no such package):
    required by: world[curl]
```

my machine:
```
docker run --rm -it alpine apk add curl && sh
fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/community/aarch64/APKINDEX.tar.gz
(1/8) Installing ca-certificates (20240226-r0)
(2/8) Installing brotli-libs (1.1.0-r1)
(3/8) Installing c-ares (1.27.0-r0)
(4/8) Installing libunistring (1.1-r2)
(5/8) Installing libidn2 (2.3.4-r4)
(6/8) Installing nghttp2-libs (1.58.0-r0)
(7/8) Installing libcurl (8.5.0-r0)
(8/8) Installing curl (8.5.0-r0)
Executing busybox-1.36.1-r15.trigger
Executing ca-certificates-20240226-r0.trigger
OK: 13 MiB in 23 packages
sh-3.2$
```

I'm still trying to figure out why my containers suddenly don't have internet. 😔

**Comment by cabaalexander** [comment]
Oh man ! Thank you ! @maietta 

So my issue was this, I have a pihole setup on my server and I'm using that pihole server as my default DNS server on my router so all the devices on my network uses pihole including the server.

Since the server ip is 10.0.0.37 and the pihole DNS port is running on the same server as a container (10.0.0.37:53), the router was looping its same IP not going to the internet to resolve the names. (This is my theory 😅 )

And to fix it, I just set a static DNS that is not pihole (1.1.1.1) and this fixes the connection issues with all the containers.

Thank you very much for coming to the rescue today @maietta 💪

**Comment by cabaalexander** [comment]
I think this is solved now 😬
