### ISSUE TITLE
[Bug]: Lesser privileged users should not be able to modify name of Team.

### ISSUE THREAD

**Issue by maietta** [coollabsio/coolify#1929]
### Description

A lesser privileged user should not be able to modify the name of a team that is not their own.

If a user is assigned role "member", they are able to modify the name of the parent team they were assigned to.

They can also change their own team name, but don't know if that's expected behavior.

### Minimal Reproduction (if possible, example repository)

Create a new user and assign role as "member".

Sign in as that user in incognito, then visit Teams page. They are free to change the name of the team.

### Version

v4.0.0-beta.248

**Comment by andrasbacsai** [comment]
The role-based authoriztions will be refactored soon, but I will add this to the next version.
