### ISSUE TITLE
[Bug]: "Create a new Application" fails (500)

### ISSUE THREAD

**Issue by luckydonald** [coollabsio/coolify#1931]
### Description

Connecting with Github does not work.

### Minimal Reproduction (if possible, example repository)

1. http://example.com:8000/project/abcd/production/new?type=private-gh-app&destination=xyz&server_id=0

2. <img width="601" alt="Screenshot 2024-04-02 at 17 44 37" src="https://github.com/coollabsio/coolify/assets/2737108/37b3f4d0-4e97-439d-b424-83eb9903132c">
   Click <kbd>Add New GitHub App</kbd>
   
  

### Exception or Error

<img width="1289" alt="Screenshot 2024-04-02 at 17 46 32" src="https://github.com/coollabsio/coolify/assets/2737108/4b49d19f-7b08-43dd-a30b-11963becbdec">

### Version

v4.0.0-beta.248

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.
