### ISSUE TITLE
[Bug]: Add multiple domains separated by comma only adds the first one to traefik

### ISSUE THREAD

**Issue by cabaalexander** [coollabsio/coolify#1932]
### Description

When you create a service and add multiple domains it only adds correctly the first domain, and the second does not work and it does not appear in traefik routers/services.

![image](https://github.com/coollabsio/coolify/assets/12496574/e696df1a-b27a-46a5-b8c2-24eee07f4996)

### Minimal Reproduction (if possible, example repository)

Try to add two domains to a resource (docker) like this example:
```
https://code.example.com:8443, https://run-code.example.com:11010
```

The first domains is for exposing the container's main service, code server in this example.

The second domain is for exposing any web server created inside that container at any point.

### Version

v4.0.0-beta.248

**Comment by andrasbacsai** [comment]
The problem occurs if you have a space between your domains. Please try it like this:
`https://code.example.com:8443,https://run-code.example.com:11010`

This will be fixed in the upcoming version, so this workaround is not needed.
