### ISSUE TITLE
[Bug]: The user is not completely removed from the system

### ISSUE THREAD

**Issue by leonovk** [coollabsio/coolify#1935]
### Description

The user is not deleted after being removed from the root command; he remains able to log into the system. He simply remains on his team without rights.

PS. Registration disabled

### Minimal Reproduction (if possible, example repository)

1) Invited a member to the root team
2) Member accepted the invitation and registered
3) Remove a member from a root team
4) The member still has the opportunity to log in to coolify, but only to his team

### Version

v4.0.0-beta.249

**Comment by andrasbacsai** [comment]
Every user has their own dedicated team upon registration. This also applies when a completely new user is invited to join a team.

What would be your preferred process for this?

I would think a view for the root user (or people on the root team) that will allow you to delete instance users would be enough. Or?

**Comment by leonovk** [comment]
Yes, I think it's a great idea to give the user root to remove other users from the system

**Comment by leonovk** [comment]
thanks for the feature
