### ISSUE TITLE
[Bug]: When deleting a metube from the list of projects, the resource is not deleted

### ISSUE THREAD

**Issue by leonovk** [coollabsio/coolify#1937]
### Description

When you remove metube from the list of projects, the resource remains active. I even went to the commands section and executed a manual command to stop the container with it, but the resource was still active. It won't let me delete the server
![Снимок экрана от 2024-04-05 18-13-34](https://github.com/coollabsio/coolify/assets/71232234/b67a19af-34a8-47ea-965d-8fff82275f15)

### Minimal Reproduction (if possible, example repository)

I added a new project in which I deployed a metube from the list of suggested resources. I pressed the deploy button without changing the default settings. Then I deleted the resource as well as the project itself.

### Version

v4.0.0-beta.249

**Comment by leonovk** [comment]
![Снимок экрана от 2024-04-05 18-25-29](https://github.com/coollabsio/coolify/assets/71232234/fb46031f-987c-452d-b5d3-b3a336d07470)

**Comment by leonovk** [comment]
I added a new project from Metube and deleted it, this solved my problem, the extra resource was also deleted and I was able to delete the server.

**Comment by andrasbacsai** [comment]
I tried to reproduce it, but I could not. I will investigate.

**Comment by leonovk** [comment]
Perhaps some kind of floating bug, after that I deployed metube several times on different servers and everything was fine

**Comment by lleleux** [comment]
Same problem for me, but with the weblate app (coolify cloud).
My VPS has not enough RAM, so it failed multiple times to reach server. Maybe an inconsistent state after that ?
But the problem now is that I cannot delete the resource...

**Comment by andrasbacsai** [comment]
This has been already solved.
