### ISSUE TITLE
[Bug]: docker compose does not work for subdirectories.

### ISSUE THREAD

**Issue by luckydonald** [coollabsio/coolify#1939]
### Description

It is not possible to select a custom path for the docker compose file, other than the root folder.
This is with git repositories, both private (GH) or public.

I've provided a minimal test repo below.

### Minimal Reproduction (if possible, example repository)

1. Add docker-compose from public url, with `docker-compose.yml` on the root dir
   - e.g. branch `rootfolder` of https://github.com/luckydonald/coolify-docker-compose-test/tree/rootfolder
2. change **Docker Compose Location** to `/docker-compose.yml` (removing the `a` in `.yaml`) 
2. Works ✅ 

----
1. Add docker-compose from public url, with `docker-compose.yml` in a sub-folder
   - e.g. branch `subfolder` of https://github.com/luckydonald/coolify-docker-compose-test/tree/subfolder
2. change **Docker Compose Location** to `/docker-compose.yml` (removing the `a` in `.yaml`)
3. set base directory to `/subfolder` or `/subfolder/` as it would make sense
4. it fails :x:

<img width="903" alt="Screenshot 2024-04-06 at 03 30 00" src="https://github.com/coollabsio/coolify/assets/2737108/1a03aa99-2aae-4a3d-866d-989445055c89">

> Could not load base compose file from /subfolder/docker-compose.yml

### Exception or Error

Could not load base compose file from /subfolder/docker-compose.yml

### Version

v4.0.0-beta.251

**Comment by luckydonald** [comment]
The current workaround is to create a branch per project, but that's not how monorepos should work, lol.

**Comment by andrasbacsai** [comment]
I cannot reproduce the issue. You save your configuration after you set point 2 and 3, right?

https://github.com/coollabsio/coolify/assets/5845193/4c6530f0-14db-458f-9616-25f6c53220d0

**Comment by luckydonald** [comment]
A few more issues I've noticed:
1. the color of the GitHub app (0:16) is not following the theme.
2. It forgets the build pack setting (docker-compose) I've selected (0:33) and I have to set it again (0:50)
3. it won't keep the field for the yaml name (2:02)

**Comment by agusmdev** [comment]
I'm having the same issue, trying to deploy Signoz

**Comment by luckydonald** [comment]
Might be related to #1805 as well.

**Comment by andrasbacsai** [comment]
These are fixed already.
