### ISSUE TITLE
[Bug]: Docker image registry is lower cased

### ISSUE THREAD

**Issue by ZhengYuTay** [coollabsio/coolify#1940]
### Description

I was trying the custom docker registry and I was using a private registry with upper case tagging, but when deploying, it convert everything to lower case and the image pulling failed. 

example:
Registry tag: `test-1QWE`, would be converted to `test-1qwe` and would cause image pulling to failed.

I think the fix would be just respect the user's input and make it case sensitive when pulling image.

### Minimal Reproduction (if possible, example repository)

<img width="880" alt="image" src="https://github.com/coollabsio/coolify/assets/32449414/b4b544c9-c707-45be-b48c-9cd8c9db40f2">

![image](https://github.com/coollabsio/coolify/assets/32449414/42800cf4-a227-44fc-9604-6f5bdd94f173)

Expected it to do `nginx:tEST` when pulling image

### Version

v4.0.0-beta.251

**Comment by luckydonald** [comment]
Is that a problem with the docker registry or coolify?

**Comment by ZhengYuTay** [comment]
> Is that a problem with the docker registry or coolify?

It's the way coolify pull image. Added a screenshot example.

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.
