### ISSUE TITLE
[Bug]: Permission Denied Error when Creating Resource

### ISSUE THREAD

**Issue by Armadillidiid** [coollabsio/coolify#1945]
### Description

After provisioning a server, I'm encountering the following error when I try to create a resource:

```bash
mkdir: cannot create directory ‘/data/coolify/proxy’: Permission denied
```

The user is a member of the sudo group with passwordless sudo privileges, yet the `mkdir` command was not executed with sudo, which is unusual. Root login via SSH is disabled for security reasons. I think it's important to debug why the `mkdir` command is not running with the necessary permissions. 

 ### Expected behavior 
 User should be able to successfully create the directory.

### Minimal Reproduction (if possible, example repository)

1. Provision server successfully 
2. Create resource (e.g postgres db)
3. ERROR!

### Version

v4.0.0-beta.251

**Comment by andrasbacsai** [comment]
So, you are trying to use Coolify with a non-root user, right?

**Comment by Armadillidiid** [comment]
Yes

**Comment by Armadillidiid** [comment]
To provide more context, I included the current server as an additional server to my Coolify setup. However, I didn't install Coolify on the newly provisioned server. I assumed that adding a server through the UI would handle the necessary preparation. Is this the issue? Do I need to install Coolify on every server?
