### ISSUE TITLE
[Bug]: wildcard certificate documentation correct?

### ISSUE THREAD

**Issue by perler** [coollabsio/coolify#1951]
### Description

here: https://coolify.io/docs/knowledge-base/traefik/wildcard-certificates you give as an example this traefik configurarion:

`- '--certificatesresolvers.letsencrypt.acme.httpchallenge=true'
      - '--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http'
      - '--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=hetzner'
      - '--certificatesresolvers.letsencrypt.acme.dnschallenge.delaybeforecheck=0'
      - `
is this correct? in the first two lines you enable httpchallenge in the last two lines you provide options for dnschallenge?

### Minimal Reproduction (if possible, example repository)

I tried to adapt this for use with cloudflare but I am not able to get it to work:

`environment:
      - CF_DNS_API_TOKEN=**************`
...
`- '--certificatesresolvers.letsencrypt.acme.dnschallenge=true'
      - '--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare'
      - '--certificatesresolvers.letsencrypt.acme.dnschallenge.delaybeforecheck=0'
      - '--certificatesresolvers.letsencrypt.acme.storage=/traefik/acme.json'`
IMO this should work but doesn't?

### Version

v4.0.0-beta.251

**Comment by Yelmuf** [comment]
Have you tried using `CLOUDFLARE_EMAIL` and `CLOUDFLARE_API_KEY` env vars instead? I got logs from Traefik looking for these.

**Comment by andrasbacsai** [comment]
I've tested and it is working well. I've added a small tip to the docs, that each dns provider needs different environment variables.

<img src="https://uploads.linear.app/0fa98b19-e5f3-418f-abaf-f6d47b6f525f/9efce79e-71b0-4fc2-bb66-b39a76377a63/006aa5f1-c445-4568-ba7f-bb4a85f5deac?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzBmYTk4YjE5LWU1ZjMtNDE4Zi1hYmFmLWY2ZDQ3YjZmNTI1Zi85ZWZjZTc5ZS03MWIwLTRmYzItYmI2Ni1iMzlhNzYzNzdhNjMvMDA2YWE1ZjEtYzQ0NS00NTY4LWJhN2YtYmI0YTg1ZjVkZWFjIiwiaWF0IjoxNzE0NDgyNzkwLCJleHAiOjMzMjg1MDQyNzkwfQ.B5I8ICCfb2oNHv2WFX_sMAP1Oxi_wP6ZIj2qduqK0xU " alt="image.png" width="789" height="281" />
