### ISSUE TITLE
[Bug]: backup is too big, unable to download

### ISSUE THREAD

**Issue by iamEvanYT** [coollabsio/coolify#1961]
### Description

The backup file is too big, and it failed to download.
![image](https://github.com/coollabsio/coolify/assets/47493765/579ac75e-b5c2-4be4-a6ba-3f00ce7fbe44)

### Minimal Reproduction (if possible, example repository)

1. Create a mongodb
2. Add a lot of data
3. Backup
4. Download

### Exception or Error

Error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 121638912 bytes)

### Version

v4.0.0-beta.254

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.
