### ISSUE TITLE
[Bug]: Can't see resources navbar (logs, variables, ...)  after v4.0.0-beta.256

### ISSUE THREAD

**Issue by lucasdidur** [coollabsio/coolify#1975]
### Description

When I open my resource, the page shows the content then go black

### Minimal Reproduction (if possible, example repository)

Open resource logs

### Exception or Error

![image](https://github.com/coollabsio/coolify/assets/123916/57056328-617e-40c9-b0a3-5f41643f4a49)

### Version

v4.0.0-beta.256

**Comment by w3cj** [comment]
This is related to the recent feature to allow tabs.

I have a PR open that will fix this: #1972

**Comment by lucasdidur** [comment]
@w3cj Do you know when this will come out? I can't manage anything

**Comment by andrasbacsai** [comment]
It is fixed in beta.257. Can you please check it?

**Comment by nikolouzos** [comment]
Same here:
`Uncaught Snapshot missing on Livewire component with id: RmywQieRZe8VD4tv5y4R`

**Comment by w3cj** [comment]
I no longer see the error and my logs are loading.

What kind of resource is this happening for you on?

**Comment by lucasdidur** [comment]
I'm using Appwrite

**Comment by nikolouzos** [comment]
For me it's Docker Compose - only the Service Stack screen is loading.

**Comment by w3cj** [comment]
I tried spinning up an Appwrite instance and I see a similar error in the console and the logs do not load:

`Uncaught Snapshot missing on Livewire component with id: vHtN2vNg2pDSDB3s808p`

**Comment by w3cj** [comment]
@andrasbacsai I think I found the fix. Can you check? https://github.com/coollabsio/coolify/pull/1979

Looks like this specifically effects resources that are of type Service.

**Comment by andrasbacsai** [comment]
Yeah, I missed one wire:key element in the loop. Thanks @w3cj for making a PR so fast.

@lucasdidur Can you please check with v258?

![Screenshot from 2024-04-12 23-17-39](https://github.com/coollabsio/coolify/assets/5845193/5e6fb310-089f-49a0-9e9b-16d6145da866)
