### ISSUE TITLE
[Bug]: Env string variables containing a double ($$) gets one $ removed

### ISSUE THREAD

**Issue by vnguyen42** [coollabsio/coolify#1991]
### Description

When an env variable is defined as a string and it contains two $ (like "@_String$$"), one of the $ will get removed at run time.

![env_setup](https://github.com/coollabsio/coolify/assets/16151212/b568c4d0-2370-4f2e-847a-44b2e965f28c)
![output_wrong_var](https://github.com/coollabsio/coolify/assets/16151212/23db4592-25f5-4629-99f2-565ede660aaf)

### Minimal Reproduction (if possible, example repository)

**Steps to reproduce:**
- Define an env variable as something like : String$$
- Deploy (in my case a JS app using process.env)
- Log => The variable now has only one "$", for example: String$

### Version

v4.0.0-beta.258

**Comment by andrasbacsai** [comment]
The upcoming version will address this issue by introducing a new variable option called 'Is Literal?'. 

This option will allow the $ sign to be escaped, ensuring that it is used literally even if it appears in the values with some characters after it by default, as explained [here](https://docs.docker.com/compose/environment-variables/env-file/#syntax).
