### ISSUE TITLE
[Bug]: Docker-compose deployments from repositories don't work if they need additional files

### ISSUE THREAD

**Issue by shantanugoel** [coollabsio/coolify#1996]
### Description

Same as in issue #1805 
If you make a source from a repository and use Docker Compose build pack, it does not copy any files from the repository to the application folder besides docker-compose file.
Using Beta 258
Looks like there were some fixes done in Beta 233, but that only started creating the directories referred to in the docker-compose file. It does not actually copy the files in the repository to the applications folder.

### Minimal Reproduction (if possible, example repository)

Create new resource
Choose Public Repository
Repository URL: https://github.com/authelia/authelia/
Use the following in general config:
a. Build Pack: Docker compose
b. Raw Compose Deployment: True (Though I've tried that this behavior remains same even for raw compose deployment being false)
c. Base Directory: /examples/compose/local/
d. Docker Compose Location: /docker-compose.yml
Go to the install location on disk: /data/coolify/applications/{YOUR_FOLDER}
See that only README and docker-compose.yml exists, not any other configuration needed. After beta 233, it creates the additional folders (e.g. traefik and authelia) in the application folder, but does not copy the files inside them from the source repository.

### Version

v4.0.0-beta258

**Comment by nikolouzos** [comment]
I don't see a `docker-compose.yml` in the repository linked. Have you tried using their Docker image or running the Dockerfile instead? 

The volumes inside docker-compose are persistent data that are created from the image itself, it wouldn't be there unless the image has run and created data. If you need to copy files from the repository to the created image, that should happen in the Dockerfile.

**Comment by piotrprzybytniewski** [comment]
+1, tried to use a metadata/migrations directory from a Hasura repository and it only creates an empty folder, it never transfers the files from the directory itself :((

**Comment by shantanugoel** [comment]
@nikolouzos the docker-compose.yml is at https://github.com/authelia/authelia/tree/master/examples/compose/local as referenced in the base directory configuration in the original bug report. The docker-compose file is copied appropriately to the destination.
I've also tried this with the docker-compose.yml being in the root of the repository as well and thus the base directory being `/` with the same result.

**Comment by piotrprzybytniewski** [comment]
A temporary workaround for docker-compose with Coolify bug, where it doesn't copy the volume directory files, only creates an empty folder as for the version v4.0.0-beta.265 and you need some directories moved into the container:

1. ssh into your VPS
2. git clone your private repository into some folder, e.g. `/home/hasura` in my case
3. map this root path in your docker-compose.yml in the volumes section of the service to mount the host (server) directory into the container
4. success, after rebuild your container has those directories and files available and app in my case Hasura does run correctly with files like migrations, metadata  from the repository :)

```
services:
   ...
    volumes:
      - /home/hasura/metadata:/hasura-metadata
      - /home/hasura/migrations:/hasura-migrations
```

**Comment by mcosti** [comment]
+1 on this issue

My docker-compose files are mounting the contents of the git repository on the root of the Docker image itself (to allow for no docker rebuilds if not needed)

**Comment by peyloride** [comment]
+1 on this one and this simply makes coolify unusable for me. Because, I have an rails app with docker-compose.yml file on root folder. Deploying to another VPS or local works; but when deploying to coolify using docker-compose; it simply doesn't copy the files from the repo.

**Comment by michael-at-boost** [comment]
+1 for please fix this.
Also +1 for you can work around it with a Dockerfile.
I'm running a build step in a composer container which starts by doing a `COPY . /app` to bring in all files from git.
Then the `CMD` for that service runs first and copies the files into a dir which is mounted on all containers.
Now the files exist as if we'd brought them in directly from the git repo and mounted. It's not ideal but it works.

**Comment by jamielife** [comment]
Also having this issue

**Comment by mmirca** [comment]
So glad to have found this issue, I was going over the docs and configs again and again with no success.

I think it would be really helpful to show a disclaimer in the docs. Letting the users know that the files are not automatically copied and they need to implement their own strategy for now.

Also thinking about an intuitive solution for this scenario. How about automatically copying the files for the first deployment and adding a checkbox in the persistent storage tab that allows the user to mark what should be overwrittable?

By default it would not be checked to avoid losing important data.

**Comment by zanzlender** [comment]
Another use-case from my side. 

I want to add a new Resource to my project - [Glances](https://nicolargo.github.io/glances/) for monitoring using their [docker-compose](https://github.com/nicolargo/glances/tree/develop/docker-compose). I go to My project > New Resource > Docker compose.

The problem is that the docker-compose file requires a `glances.conf` config file to work at all, and ideally a Dockerfile (although it can do without it). However, there is no way to include the config file somewhere. 

One possible solution would be to create my own separate repo just for to have the docker-compose and config file, but that's too much of a hassle to be a long-term solution.

**Comment by johnpccd** [comment]
+1

**Comment by martmalo** [comment]
+1

**Comment by replete** [comment]
This has been driving me mad all day, thought I'd see if this was a known bug.

I set up a docker-compose git app project, and the issue is that the app folder `/data/coolify/applications/abcdef/` never gets the files from git. The only files that make it there come from the image.

This is definitely happening in `v4.0.0-beta.306`, I've spent hours today trying to figure out what's going on

**Comment by michael-at-boost** [comment]
Hope this gets added/fixed soon. Until then, to expand on the fix, here's demo repo with a "copy" service that moves files from the git repo, into an image, then mounts them on all services, as if Coolify had brought everything in from git. 

https://github.com/boostmetrica/coolify-count-and-mount-demo

**Comment by replete** [comment]
If there are environment variables that contain the path to the artifact folder (containing the git files), we might be able to use Custom Build Command to copy this over, for a simpler workaround:
![Screenshot 2024-07-02 at 21 15 19](https://github.com/coollabsio/coolify/assets/812139/1edffe61-7fc8-4ce1-8b8d-be996be9745d)
![Screenshot 2024-07-02 at 21 17 06](https://github.com/coollabsio/coolify/assets/812139/49f4180a-7fc3-4887-a3b5-e17af220f75e)

Maybe something like
`cp -r /artifacts/"${ARTIFACT_ID}/foldername" . && docker compose build` ?

I'm not sure where the git contents exist at this point. Any ideas?

**Comment by michael-at-boost** [comment]
Nice idea. Looks like it would be /artifacts/"${ARTIFACT_ID}/${GIT_REPO_NAME}"
Not suggesting those vars exist, but that would be the format.
https://github.com/coollabsio/coolify/blob/e9158b7305bb9253fe75a0e76ef34af62f75199b/app/Models/Application.php#L685:L695

**Comment by Lucasnribeiro** [comment]
> Hope this gets added/fixed soon. Until then, to expand on the fix, here's demo repo with a "copy" service that moves files from the git repo, into an image, then mounts them on all services, as if Coolify had brought everything in from git.
> 
> https://github.com/boostmetrica/coolify-count-and-mount-demo

yep, that's the quickest solution.

**Comment by ValerioMeschi** [comment]
+1 this is a must have - isn't there something to be done with pre-deploy commands ?

**Comment by OlegWock** [comment]
This is very frustrating issue. For me this is huge block and a critical feature to have.

I'd very appreciate at least some message, so me and other users won't spend hours trying to understand what's wrong. Especially taking into consideration that volume is still present in docker-compose file after Coolify's processing, i.e. I'd expect it to work if it's still there

**Comment by replete** [comment]
> If there are environment variables that contain the path to the artifact folder (containing the git files? Is that right.. the folder disappears and I can't check), we might be able to use Custom Build Command to copy this over, for a simpler workaround: ![Screenshot 2024-07-02 at 21 15 19](https://private-user-images.githubusercontent.com/812139/345187619-1edffe61-7fc8-4ce1-8b8d-be996be9745d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MDMzOTMsIm5iZiI6MTcyMDYwMzA5MywicGF0aCI6Ii84MTIxMzkvMzQ1MTg3NjE5LTFlZGZmZTYxLTdmYzgtNGNlMS04YjhkLWJlOTk2YmU5NzQ1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQwOTE4MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYTYwODJjMjUxM2RhY2Y3NWNmMWY5NzViZGU4ZjczNWEyNjU3NGM2ODc5MjMxY2Q5MTI1ZmViM2EwYmNiNGRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SLzWxc_1KHgKsoGEHM23DloH31VsVUI2EZaBuXABwYA)
> 
> Maybe something like `cp -r /artifacts/"${ARTIFACT_ID}/foldername" . && docker compose build` ?
> 
> I'm not sure where the git contents exist at this point. Any ideas?

I've been trying to find a command we can use here to achieve this, but can't find the location of the temporary git artifact folder on the filesystem.
I've run `inotifywait -m -r -e access,modify,create,delete ./ --format '%w%f %e' >> /home/user/inotify_output.txt` on both host and coolify container to watch the filesystem and `/artifacts/` doesn't seem to exist. Does anyone know where `/artifacts/$UUID` is created? If we can access it, we can probably do what we want in a custom build command

**Comment by replete** [comment]
Thanks @lnnrtngl, I can't test this right now, but maybe something like this would work:

```
docker exec $(docker ps --filter ancestor=ghcr.io/coolabsio/coolify-helper:latest --format "{{.ID}}" | head -n 1) cp -r ./app /artifacts/${ARTIFACT_ID}/${GIT_REPO_NAME} && docker compose build` 
```

Or maybe not, I'm guessing the helper isn't available then... will try later

**Comment by lorenzomigliorero** [comment]
+1 This is blocking my Verdaccio deployment, as it needs the config file https://github.com/verdaccio/verdaccio/tree/master/docker-examples/v4/docker-local-storage-volume

**Comment by carbontwelve** [comment]
This is still broken as of [v4.0.0-beta.315](https://github.com/coollabsio/coolify/releases/tag/v4.0.0-beta.315). The entire git project content should be available at time of running docker compose.

**Comment by andrasbacsai** [comment]
Checking this!

**Comment by andrasbacsai** [comment]
I will add a new flag to the build phase. This will copy the `Base Directory` content from git to the deployment directory before deploying your application.

![image](https://github.com/user-attachments/assets/03a4e0bc-e0cf-44ee-b6d3-1ccf603765e5)

**Comment by replete** [comment]
Going to test this as soon as the update lands. Thanks for fixing this

**Comment by goulartf** [comment]
@andrasbacsai When I selected the new option to keep the files, I got the following error:

`[2024-Jul-19 22:18:51.092462] Starting deployment of splendid-sardine-sccww40 to localhost.
[2024-Jul-19 22:18:51.337747] Preparing container with helper image: ghcr.io/coollabsio/coolify-helper:latest.
[2024-Jul-19 22:18:56.207443] ----------------------------------------
[2024-Jul-19 22:18:56.212857] Importing (commit sha HEAD) to /artifacts/lggswcw.
[2024-Jul-19 22:19:05.633228] Pulling & building required images.
[2024-Jul-19 22:19:06.004280] Removing old containers.
[2024-Jul-19 22:19:06.353648] Starting new application.
[2024-Jul-19 22:19:08.006655] rm:

[2024-Jul-19 22:19:08.015507] refusing to remove '.' or '..' directory: skipping '/data/coolify/applications/sccww40/.'
rm: refusing to remove '.' or '..' directory: skipping '/data/coolify/applications/sccww40/..'

[2024-Jul-19 22:19:08.419927] rm: refusing to remove '.' or '..' directory: skipping '/data/coolify/applications/sccww40/.'
rm: refusing to remove '.' or '..' directory: skipping '/data/coolify/applications/sccww40/..'
`

**Comment by replete** [comment]
I've tested this yesterday and it's working well. I think there's a slight race condition somewhere though as sometimes a deployment following a webhook fails, but then redeploying again works. If I can reproduce this again I'll make a report, but it's definitely working as expected. Thanks

**Comment by BvdMerwe** [comment]
> @andrasbacsai When I selected the new option to keep the files, I got the following error:
> 
> `[2024-Jul-19 22:18:51.092462] Starting deployment of splendid-sardine-sccww40 to localhost. [2024-Jul-19 22:18:51.337747] Preparing container with helper image: ghcr.io/coollabsio/coolify-helper:latest. [2024-Jul-19 22:18:56.207443] ---------------------------------------- [2024-Jul-19 22:18:56.212857] Importing (commit sha HEAD) to /artifacts/lggswcw. [2024-Jul-19 22:19:05.633228] Pulling & building required images. [2024-Jul-19 22:19:06.004280] Removing old containers. [2024-Jul-19 22:19:06.353648] Starting new application. [2024-Jul-19 22:19:08.006655] rm:
> 
> [2024-Jul-19 22:19:08.015507] refusing to remove '.' or '..' directory: skipping '/data/coolify/applications/sccww40/.' rm: refusing to remove '.' or '..' directory: skipping '/data/coolify/applications/sccww40/..'
> 
> [2024-Jul-19 22:19:08.419927] rm: refusing to remove '.' or '..' directory: skipping '/data/coolify/applications/sccww40/.' rm: refusing to remove '.' or '..' directory: skipping '/data/coolify/applications/sccww40/..' `

I am also experiencing this. The container deploys as normal, but it reports that it failed.
![Screenshot 2024-07-21 at 11 57 21](https://github.com/user-attachments/assets/6378eba2-8ad6-4f27-af4a-ec42811432c2)

**Comment by Desarso** [comment]
I get the same issue, most likely a scripting problem where it is trying to delete "." and ".." in the folder of the project.

**Comment by replete** [comment]
![Screenshot 2024-07-22 at 00 23 23](https://github.com/user-attachments/assets/2bbd62c8-8c41-46ac-8cd1-54da0da09de2)

Having real problems with this, race conditions and cleanup.

I think enough of us want this feature to ask: How much can do we need to chip in to get this focused on for a day to fix the bugs? Keeps breaking on prod for me

```
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/data/coolify/applications/xxxxxxx/nginx.prod.conf" to rootfs at "/etc/nginx/nginx.conf": mount /data/coolify/applications/xxxxxxx/nginx.prod.conf:/etc/nginx/nginx.conf (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```
