### ISSUE TITLE
[Bug]: S3 Storage config does not allow deep buckets

### ISSUE THREAD

**Issue by codingmatty** [coollabsio/coolify#1997]
### Description

When trying to setup an S3 Store, I'm trying to direct it to a deep bucket like `app-name/database-backups`, but it looks like the input is being encoded, so validation attempts to hit `app-name%2Fdatabase-backups`.

### Minimal Reproduction (if possible, example repository)

1. Go to Teams -> S3 Storages (Also this was really hard to find)
2. Input relevant information, but in the `bucket` input try to use a deep bucket
3. Notice the validation shows that its trying to hit the wrong url

### Exception or Error

```
Reason: Error executing "ListObjectsV2" on "https://s3.us-east-1.amazonaws.com/app-name%2Fdatabase-backups?list-type=2&prefix=&delimiter=%2F"; AWS HTTP error: Client error: `GET https://s3.us-east-1.amazonaws.com/app-name%2Fdatabase-backups?list-type=2&prefix=&delimiter=%2F` resulted in a `403 Forbidden` response:
```

### Version

4.0.0-beta.258

**Comment by peaklabs-dev** [comment]
I do not think a s3 bucket name can contain a `/` What you want is to specify a folder in the bucket correct?

**Comment by codingmatty** [comment]
Yes, technically its a folder within a bucket, but it should be as simple as just not encoding the `/` character:

```
https://s3.us-east-1.amazonaws.com/app-name/database-backups
```

**Comment by peaklabs-dev** [comment]
I agree that having the ability to set the folder in an input would be great. This is why I created an improvement request: https://github.com/coollabsio/coolify/discussions/3988 Since issues are only for bugs and this is more of an improvement since it has not been implemented yet, I will close this issue.
