### ISSUE TITLE
[Bug]: Laravel 11 Nixpacks can not resolve postgres host

### ISSUE THREAD

**Issue by danielschnee** [coollabsio/coolify#2001]
### Description

When i try to deploy my Laravel 11 application with nixpacks and add adding all Env Variables according to the [documentation](https://coolify.io/docs/resources/laravel), i get the following error:

![image](https://github.com/coollabsio/coolify/assets/62013481/7421cdef-3938-47f7-b548-1e148671aa7b)

Both are on the same instance and the same network according to the ui.

### Minimal Reproduction (if possible, example repository)

Create a standalone postgres database and connect it to a laravel 11 application.

### Exception or Error

See the image above.

### Version

v4.0.0-beta.258

**Comment by andrasbacsai** [comment]
This has been already fixed and working with the new Nixpacks build process.
