### ISSUE TITLE
[Bug]: Docker cache doesn't work?

### ISSUE THREAD

**Issue by TheM1Stery** [coollabsio/coolify#2003]
### Description

My app is a simple rust web server(axum). My Dockerfile utilizes docker caching(via cargo-chef) to reduce compilation times of rust(which are notoriously slow). 
After each deployment the images used inside the dockerfile are downloaded again and the compilation begins anew(making cargo-chef useless). 

I also checked the cache by doing back-to-back(2 min diff) commits(like changing stuff in strings lol) and to my surprise docker used the cache.

Does this have to do anything with Automated Cleanups(https://coolify.io/docs/knowledge-base/server/automated-cleanup)? Probably not, cause my disk space is plenty for now

Docker cache works locally on my machine

### Minimal Reproduction (if possible, example repository)

This is the Dockerfile that i was using:
```dockerfile
FROM rust:1.76 as toolchain
RUN cargo install cargo-chef --locked
RUN cargo install sqlx-cli --no-default-features --features sqlite
WORKDIR /app

FROM toolchain as planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json


FROM toolchain as builder
COPY --from=planner /app/recipe.json recipe.json
RUN cargo chef cook --release --recipe-path recipe.json
COPY . .
# check query macros
ENV DATABASE_URL=sqlite:db.sqlite
RUN sqlx database create
RUN sqlx migrate run
RUN cargo build --release

FROM debian:bookworm-slim as runtime
WORKDIR /app
ENV SERVER_ADDRESS=0.0.0.0
ENV SERVER_PORT=8000
COPY --from=builder /app/target/release/axum-web-test /app/axum-web-test
EXPOSE 8000
ENTRYPOINT [ "/app/axum-web-test" ]
```

 I probably could reduce the compilation time by removing `cargo-chef` and `sqlx-cli` and by creating a docker image that already has both of them but i don't that's the best solution? It would render `cargo-chef` useless for this usecase if the image's cache is wiped?

### Exception or Error

Docker cache doesn't work, the image is recreated from scratch after each commit making the build time large

### Version

v4.0.0-beta.258

**Comment by andrasbacsai** [comment]
I tried to replicate, but I could not.

Can you please make an example public repository (with axum + sqlite)?

**Comment by TheM1Stery** [comment]
> I tried to replicate, but I could not.
> 
> Can you please make an example public repository (with axum + sqlite)?

Hello! Thanks for looking into this issue.

Here is the repository: https://github.com/TheM1Stery/rust-web-site

As you can see from these deployments:
![image](https://github.com/coollabsio/coolify/assets/87154668/bf0524cc-b8ab-435c-856c-daa483bce439)
the build time is super long.

Looking at the logs, i can see from the logs the images used inside the dockerfile are downloaded every time? And the compilation starts from scratch everytime:
[coolify-logs.txt](https://github.com/coollabsio/coolify/files/15130024/coolify-logs.txt)
Sorry for bad formatting in logs(it copied it like that lol)

**Comment by andrasbacsai** [comment]
It should be something on your server, as on my side, it uses cache.
![image](https://github.com/coollabsio/coolify/assets/5845193/e43b983c-c955-476b-bea4-3faf3b8b6fc6)
![image](https://github.com/coollabsio/coolify/assets/5845193/557e2db7-54a1-418d-9d49-47ef1bb4e29a)

The cleanup process checks the disk usage every two minutes, and if the threshold is above the set limit for the server, it cleans up the build cache.

![image](https://github.com/coollabsio/coolify/assets/5845193/a752ada8-4338-4a3e-93ed-04576ae81b38)

**Comment by TheM1Stery** [comment]
> It should be something on your server, as on my side, it uses cache. ![image](https://private-user-images.githubusercontent.com/5845193/325987160-e43b983c-c955-476b-bea4-3faf3b8b6fc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMzc5MjgsIm5iZiI6MTcxNDEzNzYyOCwicGF0aCI6Ii81ODQ1MTkzLzMyNTk4NzE2MC1lNDNiOTgzYy1jOTU1LTQ3NmItYmVhNC0zZmFmM2I4YjZmYzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjZUMTMyMDI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWRhYjAxNzgwMWZkNjYwMGViOTAyYWM0MzZmYmFmODRjNWUxMzk0ZmNiMGRmMmM5MTA2NWE0NjhkNjc5MzdiZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ySlfJwvBHYL_hxhtSu-h_gfw9ooqZFacYjEo2-dnHW4) ![image](https://private-user-images.githubusercontent.com/5845193/325986797-557e2db7-54a1-418d-9d49-47ef1bb4e29a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMzc5MjgsIm5iZiI6MTcxNDEzNzYyOCwicGF0aCI6Ii81ODQ1MTkzLzMyNTk4Njc5Ny01NTdlMmRiNy01NGExLTQxOGQtOWQ0OS00N2VmMWJiNGUyOWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjZUMTMyMDI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWYxYjgwOGRiZDY5YjFlZjY3NDRkZWZlMmMzZjc1NmM4MjdlZTAyOGJiMzZhOWUyZDQyMGZmOTVlMGE5NTYwNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1hTVuZE35lsnwuV4uyWEDWjlIkwqQR-Zrx3CYoRYGCM)
> 
> The cleanup process checks the disk usage every two minutes, and if the threshold is above the set limit for the server, it cleans up the build cache.
> 
> ![image](https://private-user-images.githubusercontent.com/5845193/325987831-a752ada8-4338-4a3e-93ed-04576ae81b38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMzc5MjgsIm5iZiI6MTcxNDEzNzYyOCwicGF0aCI6Ii81ODQ1MTkzLzMyNTk4NzgzMS1hNzUyYWRhOC00MzM4LTRhM2UtOTNlZC0wNDU3NmFlODFiMzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjZUMTMyMDI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzFmNzNjNjExMGI0NzJmYzc3OWQ0NGYyNGM1Y2EzYmNlZDljYWFmZTFjYjU4MWIzNjVhZTAyMTg3NzY0ZmUyYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ueFcXfr-u_9CMDhcQClzuMY1BppLyDMmFU8ncLnHIj8)

Strange, i even created a new vps from Hetzner using different OSes(Debian and Ubuntu 22.04) and still had the same issue. I'll try with a new server again then. Still, thanks for looking into this issue.

The cache only worked for me when i did the commit minutes after the last one.

**Comment by TheM1Stery** [comment]
![image](https://github.com/coollabsio/coolify/assets/87154668/e8995cfb-c7e9-44b0-aed0-9f946e9eded3)

I checked again. The cache only works minutes after the last build. After, i push another commit, the image is built from scratch again. I'll test this again in another new server in Hetzner, but i don't think it will make a difference

**Comment by TheM1Stery** [comment]
I tried with a brand new server(Fedora 40 this time), the same issue persists. New deployments don't use the cache from previous deployments. The rust and debian images used inside the dockerfile are downloaded again and the compilation begins from scratch.

**Comment by crisog** [comment]
> I tried with a brand new server(Fedora 40 this time), the same issue persists. New deployments don't use the cache from previous deployments. The rust and debian images used inside the dockerfile are downloaded again and the compilation begins from scratch. Sorry for bothering

I've been having the same problem, within 2-3 minutes cache works perfectly. After longer than that, it starts from scratch.

**Comment by AlejandroAkbal** [comment]
My deployments have never used cache either
![Screenshot_20240531-103701](https://github.com/coollabsio/coolify/assets/37181533/ca214715-2c98-4f1d-9d80-7407841e1d0b)

**Comment by TheM1Stery** [comment]
@andrasbacsai 
I still have the same issue. I peeked at the code.
Could the --pull flag at this line invalidate cache?
https://github.com/coollabsio/coolify/blob/66b0e04cc67691275fc712e1117df86fef4aa3ad/app/Jobs/ApplicationDeploymentJob.php#L1819

**Comment by TheM1Stery** [comment]
It looks like caching works now? I do not know what caused the fix but it works for me right now. Will monitor it further but if it continues to work, this issue can be closed.

**Comment by TheM1Stery** [comment]
It seems to work for me, even after a lot of commits. I'm closing the issue.

Thanks for Coolify @andrasbacsai !
