### ISSUE TITLE
[Bug]: Creating a supabase resource fails

### ISSUE THREAD

**Issue by Vickysomtee** [coollabsio/coolify#2007]
### Description

I tried updating the image for supabase resource and redeploying from coolify dashboard but it kept failing. I checked the logs and found

`Saved configuration files to /data/coolify/services/bks8k0w.
Creating Docker network.
Starting service.
Pulling images.
validating /data/coolify/services/bks8k0w/docker-compose.yml: services.realtime-dev Additional property supabase-realtime is not allowed`

I decided to start a fresh supabase resource but I got the error.

I checked the compose file for supabase resource and I saw [this here](https://github.com/coollabsio/coolify/blob/dc7f56b7aa9b1519f417c6424d5990ca87cfdf24/templates/compose/supabase.yaml#L955)

My guess is yaml is splits `realtime-dev.supabase-realtime` and reads the second item as a another property

### Minimal Reproduction (if possible, example repository)

Try creating a new supabase resource on coolify 

### Version

v4.0.0-beta.258

**Comment by actraiser** [comment]
This was already reported #1966 and @andrasbacsai merged a fixed version for next release. You can also check the other issue where there is a solution what to remove from the faulty docker-compose.yml to make it work.

Greets
-act
