### ISSUE TITLE
[Bug]: bash: line 21: syntax error near unexpected token `('

### ISSUE THREAD

**Issue by victorshdev** [coollabsio/coolify#2009]
### Description

Issue related to:

TRUSTED_HOSTS='^(some\.domain|anotherdomain\.com)$'

### Minimal Reproduction (if possible, example repository)

APP_ENV=dev
POSTGRES_USER=app
TRUSTED_HOSTS='^(some\.domain|anotherdomain\.com)$'

### Exception or Error

[2024-Apr-17 12:36:29.861323] bash: line 21: syntax error near unexpected token `('
[2024-Apr-17 12:36:29.933654] Oops something is not okay, are you okay? 😢
[2024-Apr-17 12:36:29.940253] bash: line 21: syntax error near unexpected token `('
[2024-Apr-17 12:36:29.945712] Deployment failed. Removing the new version of your application.

### Version

v4.0.0-beta.260

**Comment by andrasbacsai** [comment]
I cannot reproduce the issue. Can you please show me the exact envs (in developer view)?

**Comment by victorshdev** [comment]
@andrasbacsai 

It reproduces the issue even without environments.

![Screenshot 2024-04-17 at 15 16 56](https://github.com/coollabsio/coolify/assets/131619111/21c5a236-7259-4732-9843-9ccd6d1b52e1)


I created a minimal repository: [[link to repository]](https://github.com/victorshdev/env-issue/tree/main).

**Comment by andrasbacsai** [comment]
Thanks, I was able to reproduce it and have fixed it. I will be shipping the fix soon.
