### ISSUE TITLE
[Bug]: .env-coolify is not created.

### ISSUE THREAD

**Issue by HarleySalas** [coollabsio/coolify#2019]
### Description

`.env-coolify` file is not created, despite having many environment variables in Coolify, which have been working for months.

### Minimal Reproduction (if possible, example repository)

I cannot share the repo.

It is simply a git repo deployment, with Docker, being built from a Dockerfile. I cd'd in to the VPS and sure enough, there is no `.env-coolify` file.

Everything was working fine for months now. An automated deploy got pushed today and suddenly, boom.

### Exception or Error

```
[2024-Apr-17 17:21:18.368731] Oops something is not okay, are you okay? 😢
[2024-Apr-17 17:21:18.372249] Failed to load /data/coolify/applications/bc00os0/.env-coolify: open /data/coolify/applications/bc00os0/.env-coolify: no such file or directory
[2024-Apr-17 17:21:18.375803] Deployment failed. Removing the new version of your application.
```

### Version

beta.263

**Comment by andrasbacsai** [comment]
I will revert those changes until further investigation.

**Comment by andrasbacsai** [comment]
I reverted in v264, can you please check now?

**Comment by HarleySalas** [comment]
> I reverted in v264, can you please check now?

Hey, thank you for the revert. I apologize for the slow response.

I see my coolify dashboard is on `v264` now. I pressed "Update" on one of my environmental variables and then pressed "Deploy" on the top right of my project. It went through the usual build process, but still I'm getting this error:

```
[2024-Apr-18 08:33:27.858676] Image pushed to docker registry.
[2024-Apr-18 08:33:29.505087] ----------------------------------------
[2024-Apr-18 08:33:29.509852] Rolling update started.
[2024-Apr-18 08:33:30.035849]

[COMMAND] SOURCE_COMMIT=d22090cc4d415b3e3362d96ffd45140267b09da6 docker compose --project-directory /data/coolify/applications/bc00os0 -f /data/coolify/applications/bc00os0/docker-compose.yml up --build -d
[OUTPUT]
Failed to load /data/coolify/applications/bc00os0/.env: open /data/coolify/applications/bc00os0/.env: no such file or directory

[2024-Apr-18 08:33:30.168744] Oops something is not okay, are you okay? 😢
[2024-Apr-18 08:33:30.177471] Failed to load /data/coolify/applications/bc00os0/.env: open /data/coolify/applications/bc00os0/.env: no such file or directory
[2024-Apr-18 08:33:30.194918] Deployment failed. Removing the new version of your application.
```


Is there anything I should be doing to try and ensure that it pushes the variables? I pressed update on one, thinking that perhaps that would ensure that it'd try to create the file again. Let me know if there is any sort of troubleshooting that I can do.

**Comment by andrasbacsai** [comment]
What build pack do you use?

**Comment by HarleySalas** [comment]
> What build pack do you use?

Dockerfile

If it matters, it should be known that I also have a build server and a self-hosted docker registry for it.

**Comment by andrasbacsai** [comment]
Is there an `env_file` option in your compose file on the server `/data/coolify/applications/bc00os0/docker-compose.yml`?

The .env file is only not created if you do not have any environment variables set.

**Comment by HarleySalas** [comment]
from the docker-compsoe.yml file on the server:
![image](https://github.com/coollabsio/coolify/assets/38236585/c056de8a-086c-42cb-83d6-c99dcb68ac8b)

So yes, it does have an `env_file` set. I have not changed anything related to environment variables, dockerfile, etc for months now and it was working up until very recently. Do you know why it would set the `env_file` here? There is no .env file in the project, except for a `.env.example` in the repository.

My Dockerfile itself has no mention of any `.env`.

I'm completely unsure why it indicates the `env_file` here.

There is a `docker-compose.yml` file in my project, but my buildpack is set to `Dockerfile`, not `Docker Compose`, so it should be ignoring the `docker-compose.yml` file completely, right?

Again just want to emphasize, I have changed **nothing** about my deployment. It **was** working without any issues, for months. So, I believe *something* has to have changed.

**Comment by andrasbacsai** [comment]
Yes, there was a small change that will allow further environment variable functions (like interpolation and literal envs).

The `.env` file is generated on the fly by Coolify, based on what you set in environment variables on the UI. But it should only include the `env_file` option if you have environment variables.

**Comment by andrasbacsai** [comment]
Is it possible to give me access to the server where Coolify is running on? It would help me to debug (as I cannot reproduce).

If yes, please contact me in private: https://coolify.io/docs/contact

**Comment by HarleySalas** [comment]
I wrote you on telegram; let me know if you prefer a different contact method

**Comment by andrasbacsai** [comment]
Found the issue. fix is coming in the next version.

**Comment by nahtnam** [comment]
@andrasbacsai  I'm having this same issue still:

```
[2024-Apr-21 20:48:51.262860] tee: /data/coolify/applications/qg8wc88/.env: No such file or directory

[2024-Apr-21 20:48:51.294783] Oops something is not okay, are you okay? 😢

[2024-Apr-21 20:48:51.296282] tee: /data/coolify/applications/qg8wc88/.env: No such file or directory

[2024-Apr-21 20:48:51.297781] Deployment failed. Removing the new version of your application.
```

Using a build server, I have some env vars set (build) and version [v4.0.0-beta.265](https://github.com/coollabsio/coolify/releases/tag/v4.0.0-beta.265)

**Comment by HarleySalas** [comment]
> Found the issue. fix is coming in the next version.

I believe now, build env's are no longer sent to build servers in 265?
