### ISSUE TITLE
[Bug]: Cannot open an Resource

### ISSUE THREAD

**Issue by Lucas-Gruber** [coollabsio/coolify#2031]
### Description

Yesterday i noticed a bug because when i click on an resource nothing happens and then i get a "504 Gateway Time-out"-error from nginx.

### Minimal Reproduction (if possible, example repository)

1. Create an directus-stack Ressource from the build-in template with psql. 
2. Try to click on it in the coolify dashboard

### Exception or Error

From Coolify-Container Logs:
```bash
2024/04/18 20:40:59 [error] 185#185: *1038 upstream timed out (110: Unknown error) while reading response header from upstream, client: 10.1.40.17, server: _, request: "GET /project/s0w8g8s/development/service/xs0o8ck HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "10.1.1.7:8000", referrer: "http://10.1.1.7:8000/project/s0w8g8s/development"
```

### Version

v4.0.0-beta.212

**Comment by andrasbacsai** [comment]
Could you please update your instance first to the latest version? If the problem still occurs, reopen this issue.

(the latest version is v265)

**Comment by Lucas-Gruber** [comment]
I cannot update Coolify because the button in the web interface is greyed out and i dont find any way in the docs to update it via the console.
