### ISSUE TITLE
[Bug]: Update Basic Auth instructions in docs

### ISSUE THREAD

**Issue by Flowko** [coollabsio/coolify#2032]
### Description

since https://github.com/coollabsio/coolify/releases/tag/v4.0.0-beta.262 was released, my envirment stopped working, took me some time to figure it out, but found that its due to the double dollar signs i had in my labels, updating them to be single dollar signs fixed it, better to update the docs as well so people can use the working version from now on, Thanks

https://coolify.io/docs/knowledge-base/traefik/basic-auth

### Minimal Reproduction (if possible, example repository)

Follow the Basic Auth instruction at https://coolify.io/docs/knowledge-base/traefik/basic-auth

### Version

v4.0.0-beta.265

**Comment by andrasbacsai** [comment]
Thank you! I have updated the docs!

**Comment by bartosjiri** [comment]
I'm having the opposite issue in v4.0.0-beta.274.

Using the example label from the current [basic auth documentation](https://coolify.io/docs/knowledge-base/traefik/basic-auth)
(`traefik.http.middlewares.custom-auth.basicauth.users=test:$2y$12$ci.4U63YX83CwkyUrjqxAucnmi2xXOIlEF6T/KdP9824f1Rf1iyNG`) results in an issue with the following message in logs:
```
time="2024-05-03T22:05:50Z" level=warning msg="The \"ci\" variable is not set. Defaulting to a blank string."
```

Escaping/doubling all `$` characters in the label works as expected - as opposed to the issue above.
