### ISSUE TITLE
Unable to install v2, docker.service failed because the control process exited with error code.

### ISSUE THREAD

**Issue by jdbrice** [coollabsio/coolify#204]
I've been using v1 and wanted to try out v2. 
when I run
```
/bin/bash -c "$(curl -fsSL https://get.coollabs.io/coolify/install.sh)"
```

I get:
```
Welcome to Coolify installer! 


This script will install all the required packages and services to run Coolify.
If you want to install Coolify on a different OS, please open an issue on Github to get supported version.


To see what I'm doing, please check: https://github.com/coollabsio/get.coollabs.io/blob/main/static/coolify/install.sh


Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
```

if I run dockerd I see that the error is:
```
Error starting cluster component: --live-restore daemon configuration is incompatible with swarm mode 
```

I tried editing `/etc/docker/daemon.json` to set `live-restore` to false, but it looks like that gets overwritten in the install - so no help.

Even if I am willing to nuke my existing docker setup, how can I clean things up enough to install v2?

Thanks and looking forward to all the coming updates

**Comment by andrasbacsai** [comment]
I see you are trying to install Coolify on a docker swarm. Coolify _should_ work on docker swarm, but it does not use anything from swarm services. I'll update the installation script to solve this case.

Until then, you just need to leave the swarm with: `docker swarm leave` command.

**Comment by jdbrice** [comment]
Thanks for the info. I wasn't intentionally running as part of a swarm so that didn't occur to me. 
I ended up removing containers / volumes, uninstalling docker and reinstalling. After that the v2 installer worked fine.

Unfortunately I did that before I saw your response, so I cannot test your suggestion directly.
Thanks though, v2 looks much more flexible so far.

**Comment by andrasbacsai** [comment]
Added a small check to the installation script that specifies what to do in case of a docker swarm found.

**Comment by SaadBazaz** [comment]
Facing the same problem. The fix was:
```
docker swarm leave
```
