### ISSUE TITLE
[Bug]: Auto Deploy not working after switching repository

### ISSUE THREAD

**Issue by deployn** [coollabsio/coolify#2042]
### Description

When you switch a service's source repository after initial deployment, the Auto Deploy feature stops working even though it remains activated in the settings.

**Expected behavior:**
After switching the source repository, pushing changes to the new repo should continue to trigger automatic builds and deploys, as long as Auto Deploy remains enabled.

**Actual behavior:**
Pushing changes to the new repository does not trigger any builds or deploys. The Auto Deploy functionality seems to break after changing the source repo post-deployment.

### Minimal Reproduction (if possible, example repository)

1. Deploy a service with a GitHub repository
2. Ensure the Auto Deploy feature is activated in the Advanced settings
3. Push a change to the repository (a new build is triggered as expected)
4. Change the Repository to a different one in the Source settings
5. Verify the Auto Deploy feature is still activated in the Advanced settings
6. Push something to the repository (nothing happens)
7. Push a change to the new repository (nothing happens, no new build is triggered)

### Exception or Error

The Github Apps Advanced settings page displays no errors under "Recent Deliveries" after pushing to the new repository, but the response is:

`Nothing to do. No applications found with branch 'main'.`

The branch was 'main' in the old repo and the new repo.

### Version

4.0.0-beta.265

**Comment by andrasbacsai** [comment]
This is an edge case. The repository is identified by its ID (from GitHub API). Changing the repository does not change the saved ID.

I won't fix this issue, as changing the repository should be done by making a new application, not by changing the source tab.

I will make the repository input box readonly, so you could only change the branch and the commit sha.

**Comment by yannicka** [comment]
> This is an edge case. The repository is identified by its ID (from GitHub API). Changing the repository does not change the saved ID.
> 
> I won't fix this issue, as changing the repository should be done by making a new application, not by changing the source tab.
> 
> I will make the repository input box readonly, so you could only change the branch and the commit sha.

Why this choice? I think it would be interesting to be able to change the source. For example, if I migrate from GitHub to GitLab (or any other platform), this would allow me to change only one configuration.

**Comment by maisen20** [comment]
I use Gitea and have changed the owner of a repository to a company and now Coolify can no longer access the repo because the link is no longer up to date. 

Maybe it would be helpful to add a copy function to Coolify so that you can also copy the settings and especially the environment variables.
