### ISSUE TITLE
[Bug]: Discord invite is expired

### ISSUE THREAD

**Issue by alessandro-newzoo** [coollabsio/coolify#2043]
### Description

Hello,
I wanted to ask for help, but any discord invites I could find are expired:

- https://coolify.io/ - Header and Footer
- https://coolify.io/docs/contact
- When creating a new issue

### Minimal Reproduction (if possible, example repository)

n/a

### Version

n/a

**Comment by andrasbacsai** [comment]
It is not expired: https://coolify.io/discord

**Comment by alessandro-newzoo** [comment]
weird, I was getting the poop illustration saying it was invalid/expired. Seems to work now... sorry about that!
