### ISSUE TITLE
[Bug]: Validating dns failed, error message only

### ISSUE THREAD

**Issue by rathod-sahaab** [coollabsio/coolify#2044]
### Description

Value is saved but getting this error,

```
Validating DNS (https://server.abhay.rs) failed.

Make sure you have added the DNS records correctly.
```

### Minimal Reproduction (if possible, example repository)

Just setting the domain fails even though IP is correct in DNS setting I am able to ssh with server.abhay.rs

### Version

v4.0.0-beta.265

**Comment by rathod-sahaab** [comment]
Disable validation now works, just validation fails error message pops up, setting is good

**Comment by johnpyp** [comment]
This issue shouldn't be closed just because there's a workaround
