### ISSUE TITLE
[Bug]: Preview deployments are failing with "Argument #2 ($context) must be of type array"

### ISSUE THREAD

**Issue by Rei-x** [coollabsio/coolify#2048]
### Description

Preview deployments no longer work, I checked it on two independent coolify instances and two different apps (in both of them it worked earlier). Normal deployments work as usual.

### Minimal Reproduction (if possible, example repository)

Try to deploy pull request from here:
https://github.com/Rei-x/portfolio

### Exception or Error

```
[2024-Apr-21 10:24:37.696170] If you need further customization, please check the documentation of Nixpacks: https://nixpacks.com/docs/providers/node 
[2024-Apr-21 10:24:38.499767] Oops something is not okay, are you okay? 😢
[2024-Apr-21 10:24:38.501409] Illuminate\Log\LogManager::info(): Argument #2 ($context) must be of type array, string given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 355
[2024-Apr-21 10:24:38.504878] Deployment failed. Removing the new version of your application.
```

### Version

v4.0.0-beta.265

**Comment by ton77v** [comment]
Got the same error with Preview Deployments for Resource that deploys without issues

**Comment by sscarduzio** [comment]
This is a blocker fo us as well. Any ETA about this?

**Comment by 3alpha** [comment]
Same error here as well.

**Comment by ch4r-ch4r** [comment]
+1 same error here

**Comment by ck-euan** [comment]
Same issue here, it seems to have been introduced in [v4.0.0-beta.265](https://github.com/coollabsio/coolify/releases/tag/v4.0.0-beta.265) or [v4.0.0-beta.264](https://github.com/coollabsio/coolify/releases/tag/v4.0.0-beta.264) as it was working fine until these

**Comment by sscarduzio** [comment]
after this is fixed I will definitely disable the auto-update feature. Not sure even how to downgrade?

**Comment by P3ntest** [comment]
+1 same is happening to me. Anyone know how to downgrade?

**Comment by Rei-x** [comment]
You can run this on your coolify server to temporarily fix this issue (it will work until your container is removed)
```
docker exec -it coolify /bin/bash -c "curl https://patch-diff.githubusercontent.com/raw/coollabsio/coolify/pull/2056.patch | git apply -v"
```

It will apply a patch from this pull request: https://github.com/coollabsio/coolify/pull/2056

**Comment by mcnaveen** [comment]
Oh man! Just came across this issue!

**Comment by sscarduzio** [comment]
> We purchased the Cloud version but this is a main blocker for our use case. Can we fix this on priority? Thanks.
We are in the same situation. But zero response so far: tried here on GH, later in Discord. It's been 3 days without acknowledgement, sadly 😞

**Comment by andrasbacsai** [comment]
Sorry for the late answer. Fix is coming soon.

**Comment by andrasbacsai** [comment]
Released.
