### ISSUE TITLE
[Bug]: Can't start backup import in any database

### ISSUE THREAD

**Issue by Rei-x** [coollabsio/coolify#2049]
### Description

I can't click "Checkmark" and "X" button when importing a backup to database (I checked this on mariadb and postgres, chrome and firefox). There are some errors in console

### Minimal Reproduction (if possible, example repository)

Try to import a backup to postgres database, then try to click on any button - it doesn't work.

### Exception or Error

![image](https://github.com/coollabsio/coolify/assets/38581479/570225ee-d056-4734-82ea-b26cb22becb2)

### Version

v4.0.0-beta.265

**Comment by n3storm** [comment]
I verified this is error is happening.

ReferenceError: Dropzone is not defined

Asset is properly loaded 
https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.9.3/dropzone.min.js

**Comment by Deveopix** [comment]
For anyone having this, you can keep refreshing the page until you no longer see the error on the console, and then it will work.

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.
