### ISSUE TITLE
[Bug]: n8n Docker Compose template: double quotes around the time zones cause "Invalid timezone"

### ISSUE THREAD

**Issue by alessandro-newzoo** [coollabsio/coolify#2050]
### Description

When setting up a Schedule trigger in n8n, it was erroring out saying "Invalid timezone".
I then removed the double quotes around the time zones and now it works perfectly.

```diff
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    environment:
      - SERVICE_FQDN_N8N_5678
      - 'N8N_EDITOR_BASE_URL=${SERVICE_FQDN_N8N}'
      - 'WEBHOOK_URL=${SERVICE_FQDN_N8N}'
      - 'N8N_HOST=${SERVICE_URL_N8N}'
-      - 'GENERIC_TIMEZONE="Europe/Berlin"'
-      - 'TZ="Europe/Berlin"'
+     - GENERIC_TIMEZONE=Europe/Berlin
+     - TZ=Europe/Berlin
  ```

### Minimal Reproduction (if possible, example repository)

n/a

### Version

v4.0.0-beta.265

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.
