### ISSUE TITLE
[Bug]: Can't choose server for new destination

### ISSUE THREAD

**Issue by Markus-Ende** [coollabsio/coolify#2059]
### Description

When creating a new destination, the user should be able to choose the server. Right now, it always creates the destination on localhost.

### Minimal Reproduction (if possible, example repository)

1. Go to Destinations and click Add
![image](https://github.com/coollabsio/coolify/assets/19502754/d7542309-49af-4135-a5f9-fa4211942f88)
2. Save Destination & check it in the list
![image](https://github.com/coollabsio/coolify/assets/19502754/35795e8f-7e72-4642-bfee-76704055a8c3)

There is no way to change server from localhost to another server.

### Version

v4.0.0-beta.265

**Comment by andrasbacsai** [comment]
Oh, nice catch!

Fixing in the next version!

**Comment by przemyslawidzczak** [comment]
I think we can reopen this one. I've got exactly the same issue in v4.0.0-beta.323
