### ISSUE TITLE
[Bug]: Multi level subdomain is not supported

### ISSUE THREAD

**Issue by mcnaveen** [coollabsio/coolify#2063]
### Description

Let's say your Coolify instance is hosted on a subdomain and if the incoming preview deployment kicks in, Coolify will auto-provision the domain name based on the PR number, I guess? 

In that case, 2nd level subdomain will throw SSL errors.

![image](https://github.com/coollabsio/coolify/assets/8493007/0999e4ac-86aa-4278-a059-61f4affa3064)

### Minimal Reproduction (if possible, example repository)

Setup Coolify on a subdomain and try preview deployment

### Exception or Error

![image](https://github.com/coollabsio/coolify/assets/8493007/55284101-c1d1-4691-a7df-5337e98f3b09)

### Version

4.0.0-beta.266

**Comment by andrasbacsai** [comment]
I believe you are using Cloudflare (orange cloud turned on). Second-level subdomain certificates are not supported by default on the free tier, only in the paid tier, with manually created (advanced) certificates.
