### ISSUE TITLE
[Bug]:  ENV variables not available in docker compose Post-deployment Command

### ISSUE THREAD

**Issue by allanbraunV** [coollabsio/coolify#2064]
### Description

I'm trying to use an env variable in a docker compose Post-deployment Command, to set up an env file inside the container, I'm using the following command:
`echo $CACHE_CREDENTIALS; echo $CACHE_CREDENTIALS > config/cache_credentials.env`
But looks like the variable CACHE_CREDENTIALS it's not available inside the shell, so the command outputs an empty string.
I configured the variable like this:
![image](https://github.com/coollabsio/coolify/assets/148153449/4abc7f8e-e196-4164-a553-4f7cbb45175a)

### Minimal Reproduction (if possible, example repository)

Config a env variable with docker compose deployment type.
Create a Post-deployment Command that tries to echo this variable.

### Version

v4.0.0-beta.266

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.
