### ISSUE TITLE
[Bug]: PORT and HOST are added to .env automatically

### ISSUE THREAD

**Issue by jimhuds** [coollabsio/coolify#2070]
### Description

In Odoo, the variables PORT and HOST are referring to the database. It seems like Coolify has recently started adding PORT and HOST by default to the end of .env, breaking Odoo deployments.

### Minimal Reproduction (if possible, example repository)

See above

### Version

v4.0.0-beta.266

**Comment by andrasbacsai** [comment]
Are you deploying it as an application? That will override the value.

**Comment by jimhuds** [comment]
Yeah from 'existing docker image'. I don't think it used to override the value? We have quite a few other apps hosted too which are split out using docker image application+database. Is there any way this could be a toggle or something?

I manually removed the lines from .env and started Odoo outside of Coolify for now, but worried if I update/redeploy our other services the same issue may happen.

**Comment by andrasbacsai** [comment]
I will add a toggle.

(Also added odoo as a one-click service, releasing with the next version).

**Comment by jimhuds** [comment]
Great, thank you!

**Comment by andrasbacsai** [comment]
Ah, there is a bug in the code. I have already implemented the ability to overwrite it simply by adding a `HOST` or `PORT` variable through the UI. It will be fixed in the next version.
