### ISSUE TITLE
[Bug]: Invalid environment variables automatically injected

### ISSUE THREAD

**Issue by zhouzi** [coollabsio/coolify#2077]
### Description

Deployments of Plausible (using a docker-compose.yml) started failing with the following error:

> failed to read /data/coolify/services/g4sg8g8/.env: line 1: unexpected character "$" in variable name "$SERVICE_BASE64_64_PLAUSIBLE="

Every time I restart the container it duplicates the existing variables to empty ones with a name starting with $.

Seems related to #2075 #2070 and the last release #2076

### Minimal Reproduction (if possible, example repository)

https://github.com/coollabsio/coolify/assets/2291025/ab54da76-fb13-4a4f-93f5-a4b6c0703417

### Exception or Error

> failed to read /data/coolify/services/g4sg8g8/.env: line 1: unexpected character "$" in variable name "$SERVICE_BASE64_64_PLAUSIBLE="

### Version

v4.0.0-beta.268

**Comment by galacoder** [comment]
I noticed the same issue after installing Directus with the Postgres service. Now, whenever I attempt to deploy or redeploy, I encounter the same error message. I've tried removing all the services in /data/coolify/services, yet the problem persists.

**Comment by andrasbacsai** [comment]
Reverted what I've changed in v269.
