### ISSUE TITLE
[Bug]: Error while trying to download DB Backup

### ISSUE THREAD

**Issue by gianluca1606** [coollabsio/coolify#2079]
### Description

Somehow i am not able to download any instance back up files. I have coolify running for almost 10 days, but i always get the same error message, after a new browser tab is opened, this error message shows up.

`// 20240426223827
// https://mydomain.xyz/download/backup/12

{
  "message": "Attempt to read property \"id\" on null"
}` 

### Minimal Reproduction (if possible, example repository)

I could not reproduce it, like i said i have this error since the very first day where basically nothing was configured in my coolify project.

### Exception or Error

{
  "message": "Attempt to read property \"id\" on null"
}

### Version

v4.0.0-beta.269

**Comment by andrasbacsai** [comment]
I will add a small fix to the next version that will show more detailed errors.
