### ISSUE TITLE
cannot build nodejs app in v2

### ISSUE THREAD

**Issue by jdbrice** [coollabsio/coolify#208]
I have an application that worked fine with v1, but now cannot build with v2. See details in screenshots attached. Seems, simple enough but maybe I'm doing something wrong?
Build fails, cannot find package.json:
<img width="912" alt="Screen Shot 2022-03-02 at 17 31 17 " src="https://user-images.githubusercontent.com/6765220/156461121-1f37ef5f-ccb2-4c62-a27d-c5d57a3dc9f3.png">

Here are the app details:
<img width="978" alt="Screen Shot 2022-03-02 at 17 31 03 " src="https://user-images.githubusercontent.com/6765220/156461080-6e637ab0-5bd0-4d3c-b44b-672469009824.png">

You can see the (public) repo here:
https://github.com/jdbrice/rootmd-server

**Comment by andrasbacsai** [comment]
A quick fix is to remove the `base directory` and `publish directory` settings, so they should be empty. 

I will add a small check in the next version for this case. I think I had such thing in v1, but it was not migrated to v2.
