### ISSUE TITLE
[Bug]: cannot manage current active project settings

### ISSUE THREAD

**Issue by moshechaikin** [coollabsio/coolify#2080]
### Description

When selecting the production environment on a project, it doesn't show settings anymore - all that's visible is a resources page and "search for name, fqdn...". Project appears to be working normally but can't view settings/logs, etc.

The only way I've figured out how to access project settings is to go to the sources tab and click on the project under it's resource.

### Minimal Reproduction (if possible, example repository)

Using a current active project, select on it's production environment

### Version

v4.0.0-beta.269

**Comment by andrasbacsai** [comment]
Can you please paste a few images so I could understand the problem better?

**Comment by moshechaikin** [comment]
This is when clicking on a project in the project tab, and then clicking the production environment:
<img width="1265" alt="image" src="https://github.com/coollabsio/coolify/assets/6878298/90257d03-d203-41e1-b627-14436456c58a">
(searching for my app does nothing)

The only way I can manage my project settings is by navigating to the Sources tab, clicking on my Git source, and selecting my project under Resources:
<img width="1050" alt="image" src="https://github.com/coollabsio/coolify/assets/6878298/02eca3de-61b2-4989-98fe-e0853b281194">

**Comment by andrasbacsai** [comment]
Can you please also check if there is an error in the browser's console log?

**Comment by moshechaikin** [comment]
`TypeError: undefined is not an object (evaluating 'O.after')
  (anonymous function) - module.esm.js:558`
`Retrieving "b5x-stateful-inline-icon" flag errored: timed out - falling back
  (anonymous function) - injected.js:4:473751`

**Comment by moshechaikin** [comment]
Removing and adding new project resolves this issue
