### ISSUE TITLE
bug: backups not working after update 

### ISSUE THREAD

**Issue by iamEvanYT** [coollabsio/coolify#2081]
### Description

Backups always fail.

### Minimal Reproduction (if possible, example repository)

Create an MongoDB backup in Coolify.

### Exception or Error

DatabaseBackupJob failed with: Cannot assign null to property App\Notifications\Database\BackupSuccess::$database_name of type string

DatabaseBackupJob failed with: Cannot assign null to property App\Notifications\Database\BackupFailed::$database_name of type string

### Version

v4.0.0-beta.268

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.
