### ISSUE TITLE
[Bug]: sending email notification (or test mail) with Resend API doesn't work after update

### ISSUE THREAD

**Issue by jsmits** [coollabsio/coolify#2082]
### Description

Since the upgrade to v4.0.0-beta.269 email sending through the Resend API doesn't work anymore on my machine. Got no email confirmation for database backups, for example. Nor does test email sending work anymore.

### Minimal Reproduction (if possible, example repository)

Configure system-wide transaction email to use the Resend API. Then send a test email in Notifications. Doesn't work anymore, at least not on my machine.

### Version

v4.0.0-beta.269

**Comment by actraiser** [comment]
Can not confirm - just checked and received an email after successful auto deploy via resend.  Coolify [v4.0.0-beta.269]

Maybe, make sure it is enabled

![Bildschirmfoto 2024-04-27 um 11 35 22](https://github.com/coollabsio/coolify/assets/5455/6a5202c4-390c-4d87-bda7-6d09c9bbff84)


Greets
-act

**Comment by jsmits** [comment]
Thanks for checking. Yes, it's enabled. Was working fine until yesterday. Didn't change any email-related settings.

**Comment by actraiser** [comment]
Did  you check https://resend.com/emails if emails were actually received by their API? 

![Bildschirmfoto 2024-04-27 um 11 56 59](https://github.com/coollabsio/coolify/assets/5455/18f5098e-f865-43da-aa2c-7ae46a954577)

I had the situation once that an Email was in status "Delayed" and thus not received by the email client.

Greets
-act

**Comment by jsmits** [comment]
I'm using the Resend API, not their SMTP endpoint. I can try that, but the API worked fine before. Mails indeed didn't show up in my https://resend.com/emails either. Sending a mail using the Python SDK worked.

**Comment by jsmits** [comment]
I tried SMTP instead and that indeed just works fine. I guess I stick to that then, at least for now. Thanks for your help.

**Comment by ahamedzoha** [comment]
I can confirm that I have the same case. For test notification email, I can see that no emails were sent from resend. 
<img width="1105" alt="image" src="https://github.com/coollabsio/coolify/assets/13367662/5a6bc04a-158e-4899-ba23-133be29c9798">

**Comment by andrasbacsai** [comment]
This has been resolved since v310.
