### ISSUE TITLE
[Docs]: NodeJS nixpacks build gets stuck, Coolify unresponsive - add hint for beginners?

### ISSUE THREAD

**Issue by mandrasch** [coollabsio/coolify#2088]
### Description

Hi, I'm experimenting with Coolify - awesome project!

I ran into the following problem multiple times - therefore I thought its best I report it. 

My best educated guess is that the Coolify just runs out of memory because my VPS hasn't got enough. 🤷 So I guess it's not a Coolify bug per se and I should just upgrade my VPS? 

But for beginners (like me) it would a cool addition to have some information about it in the docs - maybe in a section called "Troubleshooting"?

My setup:
- VPS: Hetzner CPX11, vCPU: 2 (AMD), RAM: 2 GB
- 2 PHP projects with 1 mysql db each
- 1 SvelteKit (NodeJS) project

It seems that Coolify get's stuck on "npm ci" (via nixpacks), at least that's what I see last in the logs before Coolify becomes unresponsive. SSH connection to the server is still possible.

<img width="699" alt="Bildschirmfoto 2024-04-27 um 18 46 52" src="https://github.com/coollabsio/coolify/assets/777278/649f62c9-4664-45b8-a5ee-e1d9a42f7786">

<img width="1408" alt="Bildschirmfoto 2024-04-27 um 18 53 20" src="https://github.com/coollabsio/coolify/assets/777278/a5200f68-be65-40e9-8515-2086388a7a57">

Restarting the server does not always help, in my latest tries the deployment gets stuck again.

Only if I stop one php project + one database, builds are possible again.

### Minimal Reproduction (if possible, example repository)

VPS: Hetzner CPX11 vCPU 2 AMD RAM 2 GB

1. Add 1 php project (laravel) + 2 mysql dbs, 1 sveltekit (nodejs) project
1. Add new project with public GitHub repository https://github.com/mandrasch/ddev-craftcms-vite 
1. Switch port to 80
1. Disable health checks
1. Run Deploy --> nixpacks tries composer install (successful), but get's stuck at `npm ci` and Coolify will become unresponsive

(For SvelteKit I documented my steps here:
https://dev.to/mandrasch/deploy-sveltekit-with-ssr-on-coolify-hetzner-vps-24c5)

### Exception or Error

Full deployment log: https://gist.github.com/mandrasch/4896095a5f9fc1f75bd575896926db1b

<img width="867" alt="image" src="https://github.com/coollabsio/coolify/assets/777278/c4c7c121-cf23-4853-97d1-39a4b2b22a95">

<img width="1358" alt="Bildschirmfoto 2024-04-27 um 18 39 40" src="https://github.com/coollabsio/coolify/assets/777278/07cede69-f662-42ca-8997-7b6cca415139">

<img width="822" alt="image" src="https://github.com/coollabsio/coolify/assets/777278/a4097c7c-d0ae-4a2e-8b21-e57f7fca868f">

### Version

v4.0.0-beta.269

Happy to provide more data. Thanks very much for providing Coolify as Open Source! 🙏 

Please feel free to close this if irrelevant / not the right place for this. Cheers!

**Comment by mandrasch** [comment]
Thanks very much for checking and the detailed response @andrasbacsai, very much appreciated!

**Comment by mandrasch** [comment]
For anyone interested in this:

I decided to try the swap option. 

Swap is disabled by default on Hetzner VPS (see: [reddit discussion])(https://www.reddit.com/r/hetzner/comments/125hqf4/why_comes_the_default_linux_image_without_swap/))

I followed this guide (for ubuntu) and added 6GB swap space (since I only had 17G left on my small VPS) https://www.digitalocean.com/community/tutorial-collections/how-to-add-swap-space. 

<img width="805" alt="image" src="https://github.com/coollabsio/coolify/assets/777278/d830b364-c4f4-4e61-8418-e0fe44f2a58c">

Multiple builds seem to work fine now. 🎉

**Comment by FraserTooth** [comment]
Just chiming in to say, had the same issue on a small 2GB Hetzner instance. Adding the swap space sorted it out 👍

**Comment by mandrasch** [comment]
> Just chiming in to say, had the same issue on a small 2GB Hetzner instance. Adding the swap space sorted it out 👍 cheers @mandrasch! 🍻

Great to hear that, thanks for feedback! 🎉
