### ISSUE TITLE
Secrets / Environment variables for services

### ISSUE THREAD

**Issue by jdbrice** [coollabsio/coolify#209]
I am testing out the vaultwarden service and the hardening guide mentions several options that can be controlled via ENV variables. But I dont see any way to control secrets / ENV variables on services yet. I looked at issues etc. and didnt see it so I thought to open this.

Side note, I am not sure how 'services' differ from just running a custom Docker image, but I have not taken that approach yet. Maybe going that route would allow secrets using the existing feature.
Thanks

**Comment by andrasbacsai** [comment]
That is a good idea!

**Comment by andrasbacsai** [comment]
I really like this idea (no idea why I did not think of it before 😁), so I quickly implemented it. Will be available shortly.
