### ISSUE TITLE
[Improvement]: Show description on server keys cards

### ISSUE THREAD

**Issue by klawdyo** [coollabsio/coolify#2093]
### Description

If I have many keys, it can be difficult to find the correct ones without descriptions. 

### Minimal Reproduction (if possible, example repository)

![image](https://github.com/coollabsio/coolify/assets/100168/1438d425-15ab-4414-a34b-9a6c827eefdf)

### Version

4.0.0-beta.265

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.
