### ISSUE TITLE
[Bug]: n8n status running (unhealthy)

### ISSUE THREAD

**Issue by IRediTOTO** [coollabsio/coolify#2104]
### Description

Hello, I am trying to install n8n but it not working well. Can you please help me check it? I tried many way but look like it not work.

### Minimal Reproduction (if possible, example repository)

I don't know how to reproduce it. Here is some screenshots
![image](https://github.com/coollabsio/coolify/assets/15695252/86c708b4-8504-43ec-9259-d8af72d3ca3b)

Here is the log
![image](https://github.com/coollabsio/coolify/assets/15695252/da659627-061c-455b-b56d-7be221653593)

Here env inside docker
```
DB_POSTGRESDB_USER=0z83pfZQ6WQGuoCV
N8N_HOST=n8n-pw8sk84.tkgiare.com
DB_TYPE=postgresdb
NODE_VERSION=18.19.1
HOSTNAME=5c9de97a4d55
YARN_VERSION=1.22.19
SHLVL=1
DB_POSTGRESDB_PORT=5432
HOME=/home/node
DB_POSTGRESDB_DATABASE=n8n
NODE_ICU_DATA=/usr/local/lib/node_modules/full-icu
GENERIC_TIMEZONE=Europe/Berlin
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
SERVICE_FQDN_N8N_5678=https://n8n-pw8sk84.tkgiare.com:5678
SHELL=/bin/sh
N8N_RELEASE_TYPE=stable
PWD=/home/node
WEBHOOK_URL=https://n8n-pw8sk84.tkgiare.com
N8N_EDITOR_BASE_URL=https://n8n-pw8sk84.tkgiare.com
DB_POSTGRESDB_PASSWORD=UtIsC4KWyoRcguPS6s8O9imfrMKQInU4
DB_POSTGRESDB_SCHEMA=public
TZ=Europe/Berlin
NODE_ENV=production
DB_POSTGRESDB_HOST=postgresql
N8N_VERSION=1.38.2
```

### Version

v4.0.0-beta.271

**Comment by gkibria** [comment]
Hi, same thing here. when try to visit, the following msg:

`404 page not found`

**Comment by fcpauldiaz** [comment]
could this be related to #2073 ?

**Comment by john-afolabi** [comment]
> could this be related to #2073 ?

If it related, I had some with healthcheck not running because I was using alpine as the base image and there was no curl installed. I use the healthcheck outside the docker image and this only came up on the latest version (v4.0.0-beta.271).

**Comment by lego-sharat** [comment]
I was facing the same issue, i made two changes in the docker compose.yml.
instead of localhost use 127.0.0.1
bind the port but i don't think that does anything
` ports:
      - '5678:5678'
    healthcheck:
      test:
        - CMD-SHELL
        - 'wget -qO- http://127.0.0.1:5678/'`

**Comment by lego-sharat** [comment]
I think the issue can be verified by executing the wget command on the container from the execute command section
Also I am not seeing the healthcheck ui, i believe that is because the healthcheck is being done based on docker healthcheck. 
This is my first day using coolify so could be totally wrong about all things :D

**Comment by pushad** [comment]
> Hi, same thing here. when try to visit, the following msg:
> 
> `404 page not found`
For those getting 404 and wondering why you cannot access n8n, its due to healthcheck failing. In my case changing it to 127.0.0.1 allows me to access n8n again.

**Comment by GeorgeNance** [comment]
Same issue here. Wget inside the container doesn't exist.

```
[COMMAND] docker inspect --format='{{json .State.Health.Status}}' ngkgcc8-153359868832
[OUTPUT] "starting"  
[2024-May-21 15:34:50.846913]

[COMMAND] docker inspect --format='{{json .State.Health.Log}}' ngkgcc8-153359868832
[OUTPUT] [{"Start":"2024-05-21T15:34:29.84040601Z","End":"2024-05-21T15:34:29.955666544Z","ExitCode":1,"Output":"/bin/sh: 1: wget: not found\n"},{"Start":"2024-05-21T15:34:34.960016774Z","End":"2024-05-21T15:34:35.060940428Z","ExitCode":1,"Output":"/bin/sh: 1: wget: not found\n"},{"Start":"2024-05-21T15:34:40.065515946Z","End":"2024-05-21T15:34:40.166334183Z","ExitCode":1,"Output":"/bin/sh: 1: wget: not found\n"},{"Start":"2024-05-21T15:34:45.169709751Z","End":"2024-05-21T15:34:45.29051727Z","ExitCode":1,"Output":"/bin/sh: 1: wget: not found\n"},{"Start":"2024-05-21T15:34:50.295815317Z","End":"2024-05-21T15:34:50.419374948Z","ExitCode":1,"Output":"/bin/sh: 1: wget: not found\n"}]  
[2024-May-21 15:34:50.849970] Attempt 9 of 10 | Healthcheck status: "starting"
[2024-May-21 15:34:50.856968] Healthcheck logs: /bin/sh: 1: wget: not found | Return code: 1
[2024-May-21 15:34:55.960714]

[COMMAND] docker inspect --format='{{json .State.Health.Status}}' ngkgcc8-153359868832
[OUTPUT] "unhealthy"  
[2024-May-21 15:34:56.054879]

[COMMAND] docker inspect --format='{{json .State.Health.Log}}' ngkgcc8-153359868832
[OUTPUT] [{"Start":"2024-05-21T15:34:34.960016774Z","End":"2024-05-21T15:34:35.060940428Z","ExitCode":1,"Output":"/bin/sh: 1: wget: not found\n"},{"Start":"2024-05-21T15:34:40.065515946Z","End":"2024-05-21T15:34:40.166334183Z","ExitCode":1,"Output":"/bin/sh: 1: wget: not found\n"},{"Start":"2024-05-21T15:34:45.169709751Z","End":"2024-05-21T15:34:45.29051727Z","ExitCode":1,"Output":"/bin/sh: 1: wget: not found\n"},{"Start":"2024-05-21T15:34:50.295815317Z","End":"2024-05-21T15:34:50.419374948Z","ExitCode":1,"Output":"/bin/sh: 1: wget: not found\n"},{"Start":"2024-05-21T15:34:55.423010837Z","End":"2024-05-21T15:34:55.542787818Z","ExitCode":1,"Output":"/bin/sh: 1: wget: not found\n"}]  
[2024-May-21 15:34:56.058278] Attempt 10 of 10 | Healthcheck status: "unhealthy"
[2024-May-21 15:34:56.061511] Healthcheck logs: /bin/sh: 1: wget: not found | Return code: 1
[2024-May-21 15:34:56.063506] Removing old containers.
[2024-May-21 15:34:56.065402] New container is not healthy, rolling back to the old container.
```

**Comment by ChrisvanChip** [comment]
Having the same issue as GeorgeNance, `wget: not found`. After disabling healthcheck, the container works perfectly fine and deploys as expected.

**Comment by andrasbacsai** [comment]
N8N has been already fixed since.

I also added wget/curl to nixpacks setup phase, so it should have installed, but unfortunately for example Rust nixpacks deployments does not include wget/curl in the start phase as it starts differently than others.
