### ISSUE TITLE
[bug]: deleting backup cron job doesn't delete backups

### ISSUE THREAD

**Issue by iamEvanYT** [coollabsio/coolify#2108]
### Description

When I delete a Scheduled Backup, it does not delete the backup files on the server.

### Minimal Reproduction (if possible, example repository)

1. Create a backup
2. Delete the Scheduled Button using the Delete button shown below
![image](https://github.com/coollabsio/coolify/assets/47493765/4fbb6100-f1a4-4af2-b19d-2ea7a5e03ab8)
3. Go check inside the directory that the backup was created in
4. The backup will still be there.

### Version

v4.0.0-beta.271

**Comment by peaklabs-dev** [comment]
This issue has been fixed in the latest version.
