### ISSUE TITLE
[Bug]: install script installs old beta version 270, not current 271 beta version

### ISSUE THREAD

**Issue by maximilianschmid** [coollabsio/coolify#2109]
### Description

Install script 

`curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash`

installs beta 270, not current beta 271

Auto-Update does not work in 270, but I cannot install on a new server 271. So I'm stuck with a non working coolify which I cannot update. beta.271 would contain the fixes necessary, but is not reachable…

### Minimal Reproduction (if possible, example repository)

run `curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash`

### Version

270

**Comment by actraiser** [comment]
Not sure if recommended, but after installation, you can manually run the upgrade script on the server, it will fetch the latest beta. That's what I did so 270 was upgraded to 271.

```
/data/coolify/source/upgrade.sh
```

Greets
-act

**Comment by maximilianschmid** [comment]
@actraiser thx, that worked!
