### ISSUE TITLE
docker limit error

### ISSUE THREAD

**Issue by dondonjang** [coollabsio/coolify#211]
```
15:56:05.293  Failed to deploy!
15:56:05.294  Reason: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

Is this your problem?

**Comment by andrasbacsai** [comment]
No, not related to Coolify, but I already have an idea to prevent such thing. Docker Hub has limitations.

**Comment by dondonjang** [comment]
@andrasbacsai ok thanks
As you know, I didn't set up a docker

**Comment by dondonjang** [comment]
@andrasbacsai 
Isn't there another problem?
I've never request many PULL
and I tried to log in to the docker, but the same error occurred.

<img width="322" alt="스크린샷 2022-03-05 오후 12 05 12" src="https://user-images.githubusercontent.com/46506126/156865409-275f9954-cd36-4d78-8e68-84d43bcec714.png">
<img width="1144" alt="스크린샷 2022-03-05 오후 12 05 23" src="https://user-images.githubusercontent.com/46506126/156865413-784f31c6-cd79-43a6-b4b2-9199fcf5332f.png">

**Comment by dondonjang** [comment]
<img width="912" alt="스크린샷 2022-03-05 오후 12 28 32" src="https://user-images.githubusercontent.com/46506126/156866020-e0e91902-c4c4-491b-94a3-42bdd52e02ec.png">

I paid docker hub 
but it is return same error

**Comment by dondonjang** [comment]
I tried on ssh it it working...

```
root@cool:~# docker pull node
Using default tag: latest
latest: Pulling from library/node
e4d61adff207: Pull complete 
4ff1945c672b: Pull complete 
ff5b10aec998: Pull complete 
12de8c754e45: Pull complete 
ada1762e7602: Pull complete 
6d1aaa85aab9: Pull complete 
a238e70d0a8a: Extracting [===============================================>   ]  42.21MB/44.23MB
a9d886ece6c9: Download complete 
a213b9afda04: Download complete 
```

**Comment by andrasbacsai** [comment]
Yeah, because the host is in a different context than Coolify. That means you need to add your docker credentials in Coolify’s container with: 

docker exec -ti coolify docker login

This is just a workaround, and the credentials will be lost during updates of Coolify.

I will solve this problem, probably in the next version - not sure yet.

**Comment by dondonjang** [comment]
Thank you for your answer.

First of all, I solved this problem by erasing the server and reinstalling it.
I'm very interested in this project.
