### ISSUE TITLE
[Bug]: install script fails silently

### ISSUE THREAD

**Issue by dantrevino** [coollabsio/coolify#2111]
### Description

Installing to a Digital Ocean droplet.  Running the script fails silently after showing the `Installing required packages...` line.

```
curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash
-------------
Welcome to Coolify v4 beta installer!
This script will install everything for you.
(Source code: https://github.com/coollabsio/coolify/blob/main/scripts/install.sh)

-------------
OS: ubuntu 23.10
Coolify version: 4.0.0-beta.271
-------------
Installing required packages...
```

### Minimal Reproduction (if possible, example repository)

1. log into droplet
2. run script

### Exception or Error

None.

### Version

4.0.0-beta.271

**Comment by aaaltonen** [comment]
Having same problem.

`Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy`

**Comment by Valeriucoding** [comment]
I get the same issue

```
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:          11
Codename:     bullseye

Docker version 24.0.7, build afdd53b
```

**Comment by aaaltonen** [comment]
> ### Description
> Installing to a Digital Ocean droplet. Running the script fails silently after showing the `Installing required packages...` line.
> 
> ```
> curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash
> -------------
> Welcome to Coolify v4 beta installer!
> This script will install everything for you.
> (Source code: https://github.com/coollabsio/coolify/blob/main/scripts/install.sh)
> 
> -------------
> OS: ubuntu 23.10
> Coolify version: 4.0.0-beta.271
> -------------
> Installing required packages...
> ```
> 
> ### Minimal Reproduction (if possible, example repository)
> 1. log into droplet
> 2. run script
> 
> ### Exception or Error
> None.
> 
> ### Version
> 4.0.0-beta.271



> I get the same issue
> 
> ```
> Distributor ID: Debian
> Description:    Debian GNU/Linux 11 (bullseye)
> Release:          11
> Codename:     bullseye
> 
> Docker version 24.0.7, build afdd53b
> ```

Added PR to fix this.
[](https://github.com/coollabsio/coolify/pull/2402)

**Comment by andrasbacsai** [comment]
> I fixed install.sh and made pull request to fix this. #2402

Closed this PR, as I have implemented the error handling in a different way.

Can you please try to execute the installation script again?

**Comment by Catalan-1ap** [comment]
> > I fixed install.sh and made pull request to fix this. #2402
> 
> Closed this PR, as I have implemented the error handling in a different way.
> 
> Can you please try to execute the installation script again?

Upon startup, I encountered the following error: "E: The repository 'https://packagecloud.io/Keymetrics/pm2/debian bullseye Release' does not have a Release file."

```
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

Docker version 25.0.4, build 1a576c5
```

**Comment by andrasbacsai** [comment]
I'm closing this issue for now.

**Comment by martijnmichel** [comment]
same issue as @Catalan-1ap 
`
curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash
-------------
Welcome to Coolify v4 beta installer!
This script will install everything for you.
(Source code: https://github.com/coollabsio/coolify/blob/main/scripts/install.sh )

-------------
OS: ubuntu 22.04
Coolify version: 4.0.0-beta.319
-------------
Installing required packages...

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

E: The repository 'https://packagecloud.io/Keymetrics/pm2/ubuntu jammy Release' does not have a Release file.
`
