### ISSUE TITLE
[Bug]: Docker compose file not loading when using non-root user in remote server

### ISSUE THREAD

**Issue by maurobender** [coollabsio/coolify#2113]
### Description

Trying to configure an application with Docker compose in Coolify has been really challenging and frustrating.

I've a project with a several docker compose configuration files that work ok in my local computer but when trying to select them from the Coolify instance I'm constantly getting the error `Could not load base compose file from /docker-compose.yaml` and getting the `Docker Compose Location` setting back to its original default.

There is no any extra information about why that error is happening, if the file was not found or was any errors parsing it. 

I expend a couple of hours trying different file names, and different docker-compose file configuration but without any proper error logs it was imposible to find the error with my docker files.

Then I tried with a new rails project, a clean Dockerfile and docker-compose.yaml file and the error was the same.

I think docker-compose support is kind of broken in this last version.

I'm running the Coolify version v4.0.0-beta.271.

What is strange is that I've another instance with Coolify that is also now in `v4.0.0-beta.271` but in that instance since I've install the project a week ago with docker-compose this project is now working. If a try to configure the same project with the same docker-compose.yml file in the brand new instance it does not work :/.

### Minimal Reproduction (if possible, example repository)

- Install v4.0.0-beta.271 of Coolify in brand new server.
- Create a project and use this repository as source: https://github.com/maurobender/test-coolify-rails and selecting a remote server.
- Try to select docker compose configuration.

The repository contains:
1. Brand new rails app.
2. Dockerfile
3. docker-compose.yaml file.

### Exception or Error

There is not much information about what is happening, the error is `Could not load base compose file from /docker-compose.yaml`.

### Version

v4.0.0-beta.271

**Comment by dyne9** [comment]
I also got the same problem.
YAML::parse() method via Symphony. 
it does not seem to be working properly.
I want try to modify it, but I've never participated in open source before, 
so I'm not sure how to participate. 😅

**Comment by maurobender** [comment]
Upon further research I found the problem was using a non-root user (experimental) when connecting to the remote server. Using the root user fixed the issue.

**Comment by mcosti** [comment]
I'm encountering the same issue

**Comment by Sarorn123** [comment]
me too

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.

**Comment by truejacobjones** [comment]
Hi @andrasbacsai, I have encountered this same bug in beta 297, has this been regressed?

**Comment by andrasbacsai** [comment]
I will check, but it was hard to reproduce it.

**Comment by prplx** [comment]
@andrasbacsai, beta 306, docker-compose.yaml file at root of a public repo, the issue is still there
<img width="412" alt="Screenshot 2024-07-03 at 15 40 33" src="https://github.com/coollabsio/coolify/assets/2864594/a3e43915-5c35-41e2-aa5d-1349f9b2d19c">

**Comment by felipeyousoro** [comment]
I'm trying to deploy using the Compose functionality and the issue seems to persist. For more context, the Coolify instance is on another server and I'm using a VPN to access it

* I tried for both public and private repositories, both had the same problem
* Out of curiosity, also tried deploying a `Dockerfile` to see if it was something related to my repo or permissions, but it worked. So, I guess this is related to Compose

![image](https://github.com/coollabsio/coolify/assets/42080804/12b660df-ce73-4bfb-a9b8-d62cbcda7c0e)

**Comment by mclrc** [comment]
we are having the same issue, `v4.0.0-beta3.13.3` accessing on a remote server. tried renaming the files to the defaults, not using overrides, etc., still does not find it. there is a dockerfile in the same directory as the compose file for the main service, and that is found and built without issues.

**Comment by madjsmail** [comment]
same 

![image](https://github.com/user-attachments/assets/44f25118-ddc6-4d40-83fb-27148d00332b)

**Comment by peaklabs-dev** [comment]
Could you please provide more detailed reproduction steps for this issue after you have upgraded to the latest version of v4? This will help us investigate and resolve the issue.
