### ISSUE TITLE
LOGIN CREDENTIALS ?

### ISSUE THREAD

**Issue by elabdi** [coollabsio/coolify#212]
**### hey guys I've spent hours to find the login details but no success? I'm missing something!**

**Comment by mattfletcher** [comment]
On initial install? You just make them up. The "login" form is effectively a register form on first use.

**Comment by andrasbacsai** [comment]
The login page has a `register` button, that allows you to register a user. The first user will be the root owner of the instance and the further registrations are disabled by default. You need to enable it manually in the `Settings` menu.

**Comment by elabdi** [comment]
> On initial install? You just make them up. The "login" form is effectively a register form on first use.

thank you i thought there is an admin panel.

**Comment by elabdi** [comment]
> The login page has a `register` button, that allows you to register a user. The first user will be the root owner of the instance and the further registrations are disabled by default. You need to enable it manually in the `Settings` menu.

thank you so much for your support.

**Comment by Jordan-Hall** [comment]
> egister a user. The first user will be the root owner of the

When i've just done that it says you cant sign up as its disabled. But not created an account yet

**Comment by Jordan-Hall** [comment]
> 

What would the user be though. I've not even able to sign up
