### ISSUE TITLE
[Bug]: SOURCE_COMMIT doesn't work as expected for Preview Deployments

### ISSUE THREAD

**Issue by ton77v** [coollabsio/coolify#2126]
### Description

Environment variable SOURCE_COMMIT should contain the commit hash for the git-based resources: https://coolify.io/docs/knowledge-base/environment-variables#predefined-variables

However, for the Preview Deployments it's always "HEAD". Tried with Nixpacks & Docker Compose

### Minimal Reproduction (if possible, example repository)

1. Add a GitHub repo
2. Configure the repo-based resource and add e.g. `echo "SOURCE_COMMIT=$SOURCE_COMMIT"` for example as post-build command
3. Enable Preview Deployments, create PR and push there.

Alternatively, just execute `printenv` in "Command" menu for any container with PR branch deployed

You'll see:
```
SOURCE_COMMIT=HEAD
```

### Exception or Error

Also, the deployment logs for Docker Compose deployments (Preview Deployments only) would be like:
```
[COMMAND] docker exec XXXXXX bash -c 'SOURCE_COMMIT=HEAD docker compose --project-directory /artifacts/XXXXXX -f /artifacts/XXXXXX/docker-compose.yaml build'
```

### Version

v4.0.0-beta.271

**Comment by sscarduzio** [comment]
We are blocked on this too!

**Comment by ton77v** [comment]
> We are blocked on this too! @ton77v is this on SaaS Coolify? Or self-hosted?

Yeah this issue breaks the PR deployments totally 

I've faced this at self-hosted going to get into the cloud after it will be fixed

**Comment by sscarduzio** [comment]
Any luck with this one? @andrasbacsai

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.
