### ISSUE TITLE
[Bug]: Coolify / docs / api / authentication 404, linked to by webhooks config toolitip

### ISSUE THREAD

**Issue by komali2** [coollabsio/coolify#2130]
### Description

The "deploy webhook" tooltip instructions links to a broken page. 

### Minimal Reproduction (if possible, example repository)

On a coolify deployment, go to a project so you can see the config page. Click "webhooks" to see webhooks config. Note the "Deploy Webhook (auth required) line has a tooltip that indicates you should go to https://coolify.io/docs/api/authentication to learn more. Navigate to link. 

### Exception or Error

404

### Version

v4.0.0-beta.236

**Comment by andrasbacsai** [comment]
Hey, the latest version has the fix. You are using a very old one.
