### ISSUE TITLE
[Bug]: Enabling Server Firewall rules stalls UI loading the env variables e.g. in Supabase resource 

### ISSUE THREAD

**Issue by actraiser** [coollabsio/coolify#2143]
### Description

When i enable my server's firewall inbound rules to only let pass 80, 443 and 22, then loading the Supabase resource of my project in the Coolify dashboard takes like 20 seconds to load (all my other resources load instantly).  This must have something to do with how Coolify loads/evaluates the Environment Variables of that Resource upon clicking on it.

I wonder if Coolify ui is trying to evaluate the env vars for SMTP_PORT or PG_PORT which are internal ports but not reachable from the outside when Firewall is active.  

Anyway, once the Supabase resource section is loaded it works fine unless i click on "Developer View" for the environment variables in which case i again have to wait 20 seconds or so before the view shows up. Disabling the Firewall rules make environment variables appear instantly again.

Or did i miss a port that must be enabled for Coolify other than 80, 443 and 22?

Greets
-act

### Minimal Reproduction (if possible, example repository)

install supabase resource (maybe any other docker-compose based stack is affected too)
Enable Firewall on your Server to only let pass 22,80,443
In the Coolify dashboard, access the Supabase resource in your project

### Version

v4.0.0-beta.274

**Comment by luckycreationsindia** [comment]
Hey,

How did you enable server firewall? If I'm not wrong all ports are managed with ip tables which is managed by coolify docker. You cannot use ufw or any apps to manage firewall. Maybe I'm missing something here.

**Comment by actraiser** [comment]
I am using Hetzner as server host. They provide an interface to configure inbound rules to the owned server - so its not actually configured on the server itself but a layer above with Hetzner.

![CleanShot 2024-05-04 at 10 48 47](https://github.com/coollabsio/coolify/assets/5455/2ab37238-4d03-4b14-8387-36da026ef5ca)

Greets
-act
