### ISSUE TITLE
Healthcheck problem

### ISSUE THREAD

**Issue by hamedyosefian** [coollabsio/coolify#2146]
### Description

I am getting healthcheck problem and after build apllication retry to helth check and raise failed .. this problem for all application after update to new coolify .. how to rollback to prev version?

### Minimal Reproduction (if possible, example repository)

I am getting healthcheck problem and after build apllication retry to helth check and raise failed .. this problem for all application after update to new coolify .. how to rollback to prev version?

### Version

v4.0.0-beta.274

**Comment by fcpauldiaz** [comment]
This looks related to #2073, if you are using dockerfile based app, installing curl will solve the problem

**Comment by hamedyosefian** [comment]
> This looks related to #2073, if you are using dockerfile based app, installing curl will solve the problem

still not work
you added on dockerfile ?
how to do that ?

**Comment by fcpauldiaz** [comment]
> still not work you added on dockerfile ? how to do that ?

```
RUN apt-get update && apt-get install -y curl
```
