### ISSUE TITLE
SSL not working for sub domains?

### ISSUE THREAD

**Issue by csulit** [coollabsio/coolify#215]
https://coolify.ezerhr.com <- main

node and docker app

https://nextjs.ezerhr.com
https://api.ezerhr.com
https://noriel.ezerhr.com

I register 1st before using them.

**Comment by andrasbacsai** [comment]
I've checked DNS for these domains, but they are not configured. Did you configure it properly in DigitalOcean's dashboard? 

(I see you are using their nameserver)

**Comment by csulit** [comment]
Yean I configured using A record will try again.

**Comment by csulit** [comment]
> I've checked DNS for these domains, but they are not configured. Did you configure it properly in DigitalOcean's dashboard?
> 
> (I see you are using their nameserver)

Still getting invalid https error.

Steps I perform.

1. Create a vps
2. Add public ip to A record
3. Update vps
4. Install coolify
5. Add fqdn https://cooljoe.ezerhr.com

**Comment by itsakt** [comment]
I'm facing similar issue. Coolify generates selfsigned certificates.

**Comment by heygambo** [comment]
same here
