### ISSUE TITLE
[Bug]: DNS validation fails

### ISSUE THREAD

**Issue by maximilianschmid** [coollabsio/coolify#2151]
### Description

DNS validation always fails although DNS correctly configured and propagated. Fails for united-domains.de nameserver as well as other.

### Minimal Reproduction (if possible, example repository)

Go to Settings -> configuration -> General. Set the domain which has configured *.xx.domain.io wildcard subdomain as well. 
Click on save -> validation error. Tried two different domains with two different nameserver providers, always shows this error:

Validating DNS (https://xx.domain.io) failed.<br><br>Make sure you have added the DNS records correctly.<br><br>Check this <a target='_blank' class='underline dark:text-white' href='https://coolify.io/docs/knowledge-base/dns-configuration'>documentation</a> for further help.

 

### Exception or Error

Validating DNS (https://xx.domain.io) failed.<br><br>Make sure you have added the DNS records correctly.<br><br>Check this <a target='_blank' class='underline dark:text-white' href='https://coolify.io/docs/knowledge-base/dns-configuration'>documentation</a> for further help.

### Version

v4.0.0-beta.274

**Comment by fcpauldiaz** [comment]
DNS are out of scope, but is your DNS resolving to the server ip ?

**Comment by maximilianschmid** [comment]
@fcpauldiaz yes, DNS A record is resolving to the server ip. And the wildcard subdomain A record too.

**Comment by andrasbacsai** [comment]
I found the error, fixing in the next version!
