### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Lopfi** [coollabsio/coolify#2157]
### Description

When using multiple volumes the Storages tab only allows to edit one of the volumes and locks the other input fields
![image](https://github.com/coollabsio/coolify/assets/60221354/5bd39cb3-7b36-4c1c-a30e-929c5c35df38)

I was able to edit some of the volumes after changing the compose file but only ever one at a time and the others were locked.

### Minimal Reproduction (if possible, example repository)

Start up a jellyfin from the templates

### Version

v4.0.0-beta.274

**Comment by andrasbacsai** [comment]
The storage part has been changed since. You need to edit volumes in the your docker compose file for docker compose based deployments.
