### ISSUE TITLE
[Bug]: When I clicked the "Add New Resource" button, it was always slow to load and 504 appeared frequently

### ISSUE THREAD

**Issue by hubingkang** [coollabsio/coolify#2170]
### Description

![image](https://github.com/coollabsio/coolify/assets/43019786/0b35fc98-c44b-4aaf-9c39-9f9b302f8185)

### Minimal Reproduction (if possible, example repository)

When I clicked the "Add New Resource" button, it was always slow to load and 504 appeared frequently

### Version

v4.0.0-bate.276

**Comment by calebro-xyz** [comment]
1. How many resources do you have in your coolify instance?
2. what are the specs of your Server?

The 504 is likely because the server cannot complete the requests because it is overloaded.

**Comment by hubingkang** [comment]
> 1. How many resources do you have in your coolify instance?
> 2. what are the specs of your Server?
> 
> The 504 is likely because the server cannot complete the requests because it is overloaded.

@calebro-xyz 

My Server
-2 CPUs
-4 GBs memory

My server has only started one Docker container, which is running Coolify, without any other instances being used.

There is no resource limit set for coolify instance in docker

**Comment by john-afolabi** [comment]
Also check your available storage space. I mostly get these issues when my storage is running low and `docker system prune -af` helps free up some space.

**Comment by hubingkang** [comment]
I have enough storage space

**Comment by hubingkang** [comment]
![image](https://github.com/coollabsio/coolify/assets/43019786/51339f5d-85de-48f8-bd9e-90f82db212f6)

**Comment by calebro-xyz** [comment]
Try installing [Glances](https://github.com/nicolargo/glances) to see how your server resources are being used.

**Comment by geeknonerd** [comment]
I am also encountering the same issue; I suspect it's due to the network connection being unable to reach the Coolify server.

**Comment by geeknonerd** [comment]
Always getting a 504 error; currently using the latest version.

**Comment by tuoxiansp** [comment]
This issue appears to be related to network factors: I've experienced the same problem with servers in Mainland China, whereas the server set up in Tokyo operates perfectly fine.

**Comment by andrasbacsai** [comment]
I have received reports that the network connection to outside (GitHub, or any CDN) in Mainland China is very unstable and slow.

I'm not sure how to fix this as it applies to any software that has files hosted outside of Mainland China.
