### ISSUE TITLE
[Bug]: Can't download coolify-db backup { message: "Team not found." }

### ISSUE THREAD

**Issue by dmiric** [coollabsio/coolify#2177]
### Description

When I try to download coolify database backup all I get is:

{
message: "Team not found."
}

I checked files on the server and backup files seem to be ok.

### Minimal Reproduction (if possible, example repository)

Click Download button here:
http://coo.com/settings#backup

### Version

4.0.0-beta.276

**Comment by andrasbacsai** [comment]
This occurs if you are not logged in to your Coolify instance. Are you logged in or just accessing the download link directly?

Can you please show me a short video about it?

**Comment by andrasbacsai** [comment]
This has been already fixed.
