### ISSUE TITLE
[Bug]: Unable to connect to Postgres database in any SSL mode

### ISSUE THREAD

**Issue by aritraroy** [coollabsio/coolify#2181]
### Description

I have hosted a postgres DB using Coolify. 

1. I am able to connect to the DB in SSL mode as  "PREFERRED" or "DISABLED"
2. Not able to connect using any other modes like "ALLOW", "VERIFY-CA", "VERIFY-FULL".

What I have tried so far - 

1. I have tried to generate the a self signed certificate (which is not recommended btw), but I am unable to use these certificates as there is no way to edit the docker compose file for this Postgres container in Coolify dashboard. If I SSH into the server and manually edit the docker compose file in the "coolify" directory, the file always gets reset if I restart the instance.

2. I also tried to use Certbot to generate Let's Encrypt certificates, but I am unable to use these certificates with this database as there is no way in Coolify to configure these certificates (neither in the dashboard nor manually).

3. I also tried to enable SSL for Postgres using Trafeik but as I could find that it is only possible in Trafeik v3 and and Coolify uses Trafeik v2.X.

**Is there any way to enable secure connection to Postgres DB hosted using Coolify?** The databases I am hosting have sensitive data and it would be necessary to enable SSL connection with this database.

### Minimal Reproduction (if possible, example repository)

Already explained in the previous section. Happy to add any more information if needed.

### Version

v4.0.0-beta.276

**Comment by aritraroy** [comment]
@andrasbacsai Sorry to tag you. What are your thoughts on this issue?

Is it possible to be done somehow or it needs to be incorporated as a feature in Coolify itself?

**Comment by FaureAlexis** [comment]
same issue here

**Comment by techydad05** [comment]
me too :(

**Comment by sneko** [comment]
It seems related to https://github.com/coollabsio/coolify/issues/1869.

I'm interested by SSL too :)
