### ISSUE TITLE
[Bug]: unable to run a dragonfly database

### ISSUE THREAD

**Issue by chikof** [coollabsio/coolify#2185]
### Description

When I try to run the dragonfly db created by Coolify I get the following error:
```
Starting dragonfly-database-r0kgso0.
Pulling docker.dragonflydb.io/dragonflydb/dragonfly image.
services.vwswc04.ulimits.memlock must be a integer
```

### Minimal Reproduction (if possible, example repository)

1. Create a new resource
2. Select Dragongly database
3. Run the database

### Version

v4.0.0-beta.277

**Comment by andrasbacsai** [comment]
Oh, I just tested in ARM server (you are using that as well, right?) and it only happens there.

**Comment by peaklabs-dev** [comment]
@chikof Can you please update to the latest version and recheck as this should be fixed? Thank you.

**Comment by chikof** [comment]
> @chikof Can you please update to the latest version and recheck as this should be fixed? Thank you.

Version: [v4.0.0-beta.331](https://github.com/coollabsio/coolify/releases/tag/v4.0.0-beta.331)
![image](https://github.com/user-attachments/assets/cc7fa996-a864-40aa-a877-ceb67eb4fe50)
