### ISSUE TITLE
[Bug]: Preview option on ghost does not work

### ISSUE THREAD

**Issue by scshiv29-dev** [coollabsio/coolify#2187]
### Description

So the preview options of ghost do not work, be it signup/signin / the post/ website preview nothing . it stays in loading state
https://jam.dev/c/7513d6d7-d92f-4097-bc59-2ee00caf48af

### Minimal Reproduction (if possible, example repository)

Start a ghost instance and try customizing it

### Version

v4.0.0-beta.277

**Comment by scshiv29-dev** [comment]
![image](https://github.com/coollabsio/coolify/assets/68141773/32b11e99-d0d3-4951-a025-a45263cfd4a0)


So I did some troubleshooting and realized that if I add https:// domain in the environment variable for GHOST the app doesn't render due to too many redirects and if I use http:// then the above issue and other issues are there care to look into this @andrasbacsai  please?

**Comment by peaklabs-dev** [comment]
@scshiv29-dev Do you use Cloudflare? if so check this: https://coolify.io/docs/knowledge-base/faq#too-many-redirections

**Comment by peaklabs-dev** [comment]
Due to inactivity, we're closing this issue.
