### ISSUE TITLE
[Bug]: SSL S3 Client Handshake Failure after updating to new version

### ISSUE THREAD

**Issue by hamedyosefian** [coollabsio/coolify#2188]
### Description

After updating to the latest version of coolify, I'm experiencing issues connecting to my MinIO instance using the S3 client. Prior to the update, everything was working as expected. However, after the update, I'm receiving a "Handshake failure. Unable to negotiate an acceptable set of security parameters" error when trying to connect.

Please help me or solution to reverting to previous versions of coolify

### Minimal Reproduction (if possible, example repository)

Listing directory failed. (Amazon S3)

Handshake failure. Unable to negotiate an acceptable set of security parameters. Please contact your web hosting service provider for assistance.

### Version

v4.0.0-beta.277

**Comment by hamedyosefian** [comment]
> I've added a document on how to downgrade: https://coolify.io/docs/downgrade
> 
> Can you please try to downgrade and let me know if it works after that? I did not modify anything related to MinIO.

I downgraded but the problem still persists
It's very weird and I don't know where the problem is
Because when I use CDN Cloudflare, it has a problem and it gives the message "Handshake failure. Unable to negotiate an acceptable set of security parameters", but it works fine with other CDNs that I use and there is no such problem.

**Comment by hamedyosefian** [comment]
> I've added a document on how to downgrade: https://coolify.io/docs/downgrade
> 
> Can you please try to downgrade and let me know if it works after that? I did not modify anything related to MinIO.

now i remove that minio and install new minio that worked 
I don't know what happened that it happened like this

**Comment by peaklabs-dev** [comment]
Since the issue has been resolved, I am closing this. If you encounter something similar, please reopen or create a new issue.
