### ISSUE TITLE
[Bug]: Package jq not found on CentOS 7

### ISSUE THREAD

**Issue by CassianoD2** [coollabsio/coolify#2209]
### Description

The system stop the installation on start because of the package "jq" on dnf install CENTOS 7.
After debugging the install script i founded the package who cause the error of stopping the installation.

The package who cause the error it's the "**jq**" package.

### Minimal Reproduction (if possible, example repository)

Just trying to install Coolify on a clean CentOS 7

The part who make the error occurs it's:

Line 84 of the install script:
`dnf install -y curl wget git jq >/dev/null 2>&1`

I need to execute "**yum install epel-release**" before running with success the installation.

### Exception or Error

Don't has a exception error, i need to debug line by line to identify the error.

### Version

4

**Comment by maietta** [comment]
I don't think a special condition should be made for supporting an OS that is dead shortly.

![image](https://github.com/coollabsio/coolify/assets/11745020/7a792708-b21b-4b37-b785-5aa4559148b9)

**Comment by andrasbacsai** [comment]
I agree with @maietta. It will be out of support soon, and as it has a workaround (execute `yum install epel-release`), it does not make sense to fix this.
