### ISSUE TITLE
[Bug]: Unable to deploy service due to commit hash being to long

### ISSUE THREAD

**Issue by hkd987** [coollabsio/coolify#2221]
### Description

Recently a service has stopped being able to deploy due to what looks like an internal coolify issue with the commit hash length. 

<img width="1029" alt="Screenshot 2024-05-16 at 6 57 15 AM" src="https://github.com/coollabsio/coolify/assets/6254949/ab08c791-66e8-4fbb-81fe-f0676c59456c">

### Minimal Reproduction (if possible, example repository)

See above image

### Exception or Error

See above imge

### Version

v4.0.0-beta.279

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.
