### ISSUE TITLE
[Bug]: Environment variables get sorted, causing issues

### ISSUE THREAD

**Issue by ngregrichardson** [coollabsio/coolify#2227]
### Description

When adding environment variables to a resource, even when adding them in Developer View, the environment variables get sorted. While it is nice to display them, I find that it causes problems when some of them depend on one another. For example, if I put:

```
DB_USER=abcdefg
DB_URL=somethingsomething:$DB_USER
```

this will get turned into

```
DB_URL=somethingsomething:
DB_USER=abcdefg
```

when I actually deploy it to the server.

Please let me know if I'm missing a better way to do this! Love Coolify so so much!

### Minimal Reproduction (if possible, example repository)

1. Create resource
2. Add
```
DB_USER=abcdefg
DB_URL=somethingsomething:$DB_USER
```
3. Execute the `env` command in the resource once it is deployed, see that it has
```
DB_URL=somethingsomething:
```

### Version

v4.0.0-beta.280

**Comment by andrasbacsai** [comment]
I will add a option to sort alphabetically (default) 
![image](https://github.com/coollabsio/coolify/assets/5845193/ce5b3dac-b104-4559-b5fa-56e80e5bbb3f)
or by creation
![image](https://github.com/coollabsio/coolify/assets/5845193/1a3f2bd4-9274-4179-b2f6-5fd55168985b)

**Comment by ThomasKirst** [comment]
> Is it possible that this checkbox/function has been removed again? Unfortunately, I don't see an option to switch off the default sorting.

Same, I don´t see the option and it breaks my deployment.
My postgres / database env vars are also partly dependent.
The alphabetic re-ordering breaks it.
