### ISSUE TITLE
[Bug]: after new update directus gives unhealthy and url not working it gives 404 page not found

### ISSUE THREAD

**Issue by bllfoad** [coollabsio/coolify#2228]
### Description

after new update directus gives unhealthy no mater i do ! and service not working it gives 404 page not found
tried new instance new ip new domain same result tried another service same result tried fresh instal same result
![image](https://github.com/coollabsio/coolify/assets/100096228/22af3bd6-c7b2-40c0-b16c-bd99fd4522e6)
![Screenshot 2024-05-17 051639](https://github.com/coollabsio/coolify/assets/100096228/c3e060a3-374b-4e8f-84f1-09310404301a)

### Minimal Reproduction (if possible, example repository)

after new update directus gives unhealthy no mater i do ! and service not working it gives 404 page not found

### Version

v4.0.0-beta.280

**Comment by andrasbacsai** [comment]
It looks like some of the images resolve to IPv6 for `localhost` and not `127.0.0.1`. It will be fixed in the next version by changing the health check from `localhost` to `127.0.0.1`.

**Comment by bllfoad** [comment]
thanks a lot ! @andrasbacsai
