### ISSUE TITLE
Bug: Docker networks not disconnected from coolify-proxy

### ISSUE THREAD

**Issue by andrasbacsai** [coollabsio/coolify#2235]

**Comment by JasonDevTech** [comment]
This is still an issue with the latest coolify version - beta 299 where I will now run into the issue of `Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network`. I had to go into the network and manually disconnect all ghost containers of deleted applications/services then delete the network to get this error to go away. Might also want to consider creating a bigger pool for networks considering you'll hit the limit at ~20 or so networks created.

**Comment by JuanxCursed** [comment]
Same issue here, any updates guys?

**Comment by JuanxCursed** [comment]
I managed to make work using `docker network prune` to clean up unused networks, but that is temporary

**Comment by peaklabs-dev** [comment]
Will be fixed once this is completed: https://github.com/coollabsio/coolify/pull/3024
