### ISSUE TITLE
[Bug]: Postgres containers unable to reach via internal connection string

### ISSUE THREAD

**Issue by 0pilatos0** [coollabsio/coolify#2237]
### Description

i have been trying to setup my postgres database connection to my next application, but whenever i build the application i keep getting the error that the database could not be reached, it seems there is some sort of issue with the docker networks going on underneath.

### Minimal Reproduction (if possible, example repository)

once i enable the public url + select a port i can acces the container with the application 

postgres://postgres:censored@f8oss08:5432/postgres.   DOES Not work
postgres://postgres:censored@<real-ip>:5434/postgres.   WORKS

this happens on for example a super basic t3 project with the default postgresql database

### Version

v4.0.0-beta.283

**Comment by ylyra** [comment]
@0pilatos0 how did you fixed? tks

**Comment by 0pilatos0** [comment]
@ylyra Its not an issue within coolify

its because next requires a database connection during build time it tries to connect to the database which is not possible with internal connection strings yet as the docker context is not yet available.

docker internal url's only work from running containers towards running containers. (seems by design, by the docker team)

the workaround for now is 
a: disable ssg in nexts (not really a option in most cases)
b: use a public url with a strong password :D
