### ISSUE TITLE
[Bug]: the location of the Docker Compose file cannot be specified

### ISSUE THREAD

**Issue by Yurgeman** [coollabsio/coolify#2239]
### Description

when creating a New Resource from Git (build pack - Docker Compose), it is not possible to specify the location of the Docker Compose file

watch the video: 

https://github.com/coollabsio/coolify/assets/7249668/b9836fd2-d208-4f1d-a5ce-05f649514a9a

### Minimal Reproduction (if possible, example repository)

1. click New resource
2. Select Public Repository 
3. add  https://github.com/taigaio/taiga-docker  or use  main branch
4. select build pack - Docker Compose
5. change `docker-compose.yaml` to `docker-compose.yml` ([docker-compose.yml](https://github.com/taigaio/taiga-docker/blob/main/docker-compose.yml))
6. see error

### Exception or Error

Error messages:
**Docker Compose file not found at: /docker-compose.yaml**
or 
**Mapping values are not allowed in multi-line blocks at line 4 (near "&default-back-environment").**

### Version

v4.0.0-beta.283

**Comment by craigharman** [comment]
Same for me, been happening for months. Anything that can be done about this as it means I can't use docker-compose deployments. Any work arounds or quick fixes?

**Comment by jvdboog** [comment]
My docker-compose file has the .yaml extension and even then it's not working... Is there any workaround for this?

**Comment by andrasbacsai** [comment]
I found the issue. Are you using a non-root user, right, @jvdboog?
