### ISSUE TITLE
[Bug]:  Unhealthy Django Container

### ISSUE THREAD

**Issue by brightkan** [coollabsio/coolify#2241]
### Description

The health check is glitchy (it shows unhealthy container).  It shows unhealthy for previously healthy deployment. The service from the container works well

### Minimal Reproduction (if possible, example repository)

Nixpacks, Django 4.2 with python 3.8.  A project is deployed with those tools available on coolify self-hosted version [v4.0.0-beta.283](https://github.com/coollabsio/coolify/releases/tag/v4.0.0-beta.283).

### Exception or Error

Container unhealthy

### Version

v4.0.0-beta.283

**Comment by andrasbacsai** [comment]
Can you please check with v284? I fixed an issue related to healthchecking.

**Comment by brightkan** [comment]
Thank you. Works as expected
