### ISSUE TITLE
[Bug]: application with Nixpacks and pnpm v9+

### ISSUE THREAD

**Issue by gBusato** [coollabsio/coolify#2250]
### Description

Hey guys, 

I was having some trouble deploying a NextJS application using Nixpacks and pnpm v9.1.0 as package manager. 

The typical error while deploying was happening during the pnpm install : 

`ERR_PNPM_NO_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is absent`

After some research, I found out that currently ( 2024/05/20 ) Nixpack doesn't support pnpm v9.0+ and only v8.0. 

One of the solution is to downgrad your pnpm version, but I couldn't due to some other projects running on pnpm v9.0. 

Well I did found a solution [on this github post](https://github.com/railwayapp/nixpacks/issues/1091#issuecomment-2109028614). 

Here are the steps to make it work : 

1. Create a [Nixpacks configuration file](https://nixpacks.com/docs/configuration/file) at the root of your projet
2. Add the following code inside the file
```
providers = ["node"]

[phases.install]
cmds = ["npm install -g corepack", "corepack enable", "corepack prepare pnpm@9.1.0 --activate", "pnpm install"]
```
3. deploy and enjoy

With the Nixpacks file forcing the install of pnpm v9.1 it should work. Also replace version 9.1.0 with your current running version at the time you are looking at the solution 

I hope it will helps some of you ! Have fun and happy coding

### Minimal Reproduction (if possible, example repository)

Having any node js project and pnpm v9.0+ has current package manager and a pnpm-lock.yaml file with `lockfileVersion: '9.0'` or higher

### Exception or Error

`ERR_PNPM_NO_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is absent
`

### Version

v4.0.0

**Comment by fcpauldiaz** [comment]
I fixed this by adding this to the package.json 

```
"packageManager": "pnpm@9.1.1"
```

**Comment by GifCo** [comment]
> I fixed this by adding this to the package.json
> 
> ```
> "packageManager": "pnpm@9.1.1"
> ```

THanks for this! Worked for me. 

This is beyond ridiculous that this is not in the doc's and or automated.

**Comment by andrasbacsai** [comment]
Closing this as it is a configuration for Nixpacks, not Coolify.

**Comment by ardiansyaherwin** [comment]
> > I fixed this by adding this to the package.json
> > ```
> > "packageManager": "pnpm@9.1.1"
> > ```
> 
> THanks for this! Worked for me.
> 
> This is beyond ridiculous that this is not in the doc's and or automated.

did you also success build it? once I've added the packageManager to package.json, the install runs smoothly, but not with the build. 
it says ```ERROR: failed to solve: process "/bin/bash -ol pipefail -c pnpm run build" did not complete successfully: exit code: 1```

**Comment by jpainam** [comment]
Hey, I have added
```
"packageManger": "pnpm@9.7.1"
```
in my `package.json`, but still have this error 
```ts
#12 [stage-0 8/12] RUN --mount=type=cache,id=r8c84so-/root/npm,target=/root/.npm npm i
#12 0.849 npm ERR! code EUNSUPPORTEDPROTOCOL
#12 0.853 npm ERR! Unsupported URL Type "catalog:": catalog:react18
```
in a Monorepo. `catalog` was recently introduced.

**Comment by hacknug** [comment]
> Hey, I have added
> 
> ```
> "packageManger": "pnpm@9.7.1"
> ```
> 
> in my `package.json`, but still have this error
> 
> ```ts
> #12 [stage-0 8/12] RUN --mount=type=cache,id=r8c84so-/root/npm,target=/root/.npm npm i
> #12 0.849 npm ERR! code EUNSUPPORTEDPROTOCOL
> #12 0.853 npm ERR! Unsupported URL Type "catalog:": catalog:react18
> ```
> 
> in a Monorepo. `catalog` was recently introduced. Looks like support was added to `nixpacks` 3 days ago [railwayapp/nixpacks#1172](https://github.com/railwayapp/nixpacks/pull/1172).

You might need to add a `nixpacks.toml` to your project root for now with this inside:

```toml
# buildImage = 'ghcr.io/railwayapp/nixpacks:ubuntu-1707782610'

[phases.install]
cmds = ['npm install -g corepack', 'corepack enable', 'corepack prepare pnpm@9.7.1 --activate', 'pnpm install']
```

I left a line commented just to show how to change the build image used by nixpacks in case you want to manually specify a different one from the one used by coolify (that's probably how you could test the newest changes upstream if I'm not mistaken).

**Comment by jpainam** [comment]
Hi @hacknug  I solved this by adding a `Start Command` `cd apps/nextjs && pnpm start`

**Comment by hacknug** [comment]
> @hacknug do we have to do anything to make nixpacks use the `nixpacks.toml` file for config ? it just doesnt seem to work for me when i set it in the folder #3324

It works out of the box for me when adding `nixpacks.toml` to the root of my project/repo. Maybe you're building your project on a children directory?

**Comment by Flowko** [comment]
i have a monorepo setup, i do go into the children app to build, i do that from the main package.json file i have at the top, so it should as well read from nixpacks config i have at the top, weird thing is, i tried dokploy and it worked fine there. so not sure how it got broken for me, one other thing

**Comment by hacknug** [comment]
No idea then. Sorry…
