### ISSUE TITLE
[Bug]: Proxy doesn't always pick up changes in the configuration

### ISSUE THREAD

**Issue by ton77v** [coollabsio/coolify#2253]
### Description

I've created a new resource in a repo-based project, probably with some configuration issue like wrong port specified. The first deployment failed. I did a few changes, the deployment succeeded. 

However in the browser the resource URL was "404 page not found" plus the certificate error.

After I deleted the resource and created it again, this time with everything set correctly, it worked just fine.

### Minimal Reproduction (if possible, example repository)

I could not reproduce this, hopefully someone will add more information.

### Exception or Error

404 page not found

### Version

v4.0.0-beta.284

**Comment by peaklabs-dev** [comment]
@ton77v Can you please update to the latest version and recheck and if possible provide more detailed reproduction steps? Thank you.

**Comment by ton77v** [comment]
> @ton77v Can you please update to the latest version and recheck and if possible provide more detailed reproduction steps? Thank you.

I haven't seen this issue for a while so let's close the issue for now thanks!
