### ISSUE TITLE
[Bug]: A resource XXX has been stopped unexpectedly notification on restart/redeploy from UI

### ISSUE THREAD

**Issue by ton77v** [coollabsio/coolify#2254]
### Description

 Coolify cloud.

Every time I restart or re-deploy resource to apply the configuration change, all the team gets
"Coolify: A resource has been stopped unexpectedly on XXX" email saying that "A resource XXX has been stopped unexpectedly... "

It's also triggered by a deployment on a Webhook, and (if I remember correctly) for repo-based resources this happens after automatic re-deployments on new commits (i.e. Auto Deploy feature)

Although these are absolutely legitimate reasons to stop. While the email definitely doesn't sound so 😀

### Minimal Reproduction (if possible, example repository)

1. Add a resource
2. Notifications: subscribe to all the events
3. Re-deploy or restart

### Exception or Error

A resource has been stopped unexpectedly

### Version

v4.0.0-beta.284

**Comment by andrasbacsai** [comment]
This is already solved in the latest version. Closing
