### ISSUE TITLE
[Bug]: Cant have longer command in Pre/Post Deployment commands

### ISSUE THREAD

**Issue by Flowko** [coollabsio/coolify#2267]
### Description

in my nodejs app im using puppeteer, and i need to have a version of chromium for it to work, so i need to install a command before it starts the deployment, the command im trying to run 

`sudo apt-get update && apt-get install -y ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libcups2 libdbus-1-3 libdrm2 libgbm1 libnspr4 libnss3 libx11-xcb1 libxcomposite1 libxdamage1 libxext6 libxfixes3 libxrandr2 xdg-utils wget --no-install-recommends`

![Screenshot 2024-05-22 at 10 03 46 AM](https://github.com/coollabsio/coolify/assets/35883748/08c23cf6-6e14-4c62-9508-9b91f88c6fed)

### Minimal Reproduction (if possible, example repository)

- add `sudo apt-get update && apt-get install -y ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libcups2 libdbus-1-3 libdrm2 libgbm1 libnspr4 libnss3 libx11-xcb1 libxcomposite1 libxdamage1 libxext6 libxfixes3 libxrandr2 xdg-utils wget --no-install-recommends` to Pre-deployment Command

### Exception or Error

SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(255) (Connection: pgsql, SQL: update "applications" set "install_command" = pnpm install --force, "build_command" = pnpm dash build, "start_command" = pnpm dash start, "pre_deployment_command" = sudo apt install -y gconf-service libgbm-dev libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget, "updated_at" = 2024-05-22 09:00:29 where "id" = 9)

### Version

v4.0.0-beta.285

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.

**Comment by Flowko** [comment]
thank you
