### ISSUE TITLE
Integrate no log options for Plausible Clikhouse

### ISSUE THREAD

**Issue by LittleBigFrog** [coollabsio/coolify#227]
Clickhouse have performance issues on small ram machines, as described here:
https://github.com/plausible/analytics/issues/301
https://theorangeone.net/posts/calming-down-clickhouse/

@RealOrangeOne allows to disable excessive logs:
https://github.com/plausible/hosting/tree/master/clickhouse

is there a way to integrate these settings?

**Comment by RealOrangeOne** [comment]
https://github.com/coollabsio/coolify/blob/1281a0f7e46a74beb689252776f6862a09c20f80/src/routes/services/%5Bid%5D/plausibleanalytics/start.json.ts#L83-L106

**Comment by andrasbacsai** [comment]
These are integrated. Are you having some problem on small ram machine?

**Comment by andrasbacsai** [comment]
Due to inactivity, I'm closing this issue. However, if the problem persists, please reopen the issue. Thanks!

**Comment by akoenig** [comment]
@andrasbacsai I can confirm high spikes in CPU utilization when it comes to the clickhouse server. I checked the `/etc/clickhouse-server/config.xml` within the container and can confirm that the changes above are not in there.
