### ISSUE TITLE
Redeploy button on phones provokes missclick and loose all data

### ISSUE THREAD

**Issue by miguelgargallo** [coollabsio/coolify#2273]
### Description

Redeploy button on phones provokes missclick and loose all data

![IMG_7014](https://github.com/coollabsio/coolify/assets/5947268/3ac07977-f835-428a-a866-f2df6ee2c3b5)

### Minimal Reproduction (if possible, example repository)

Missclick

### Version

v4.0.0-beta.285

**Comment by andrasbacsai** [comment]
What do you mean by provokes? What is the problem?

**Comment by andrasbacsai** [comment]
Thanks for the suggestions. I'm closing this issue for now. 

If you would like to help to improve Coolify, please reopen this issue with a PR.
