### ISSUE TITLE
[Bug]: Supabase edge function is unhealthy because Deno can't respond.

### ISSUE THREAD

**Issue by samuelteixeiras** [coollabsio/coolify#2274]
### Description

Supabase edge function is unhealthy because Deno can't respond.
The error is described here: https://github.com/denoland/deno/issues/14579

**Solution:**
Use `https://thingproxy.freeboard.io/fetch/` to proxy deno calls example. 
https://thingproxy.freeboard.io/fetch/https://deno.land/std@0.131.0/http/server.ts

### Minimal Reproduction (if possible, example repository)

Using the template without any changes, using the `https://www.hetzner.com/` as VPS provider

### Exception or Error

Connection reset by peer (os error 104) 

### Version

v4.0.0-beta.285

**Comment by peaklabs-dev** [comment]
I have refactored the Supabase template a lot. Could you please try again if this error still occurs with the following template: https://github.com/coollabsio/coolify/blob/next/templates/compose/supabase.yaml (copy the compose file into the docker compose deploy type)
