### ISSUE TITLE
[Bug]: Erroneous/Unnecessary PermitRootLogin warning during installation

### ISSUE THREAD

**Issue by pReya** [coollabsio/coolify#2277]
### Description

During the installation process I get the following error:

```
###############################################################################
WARNING: PermitRootLogin is not enabled in /etc/ssh/sshd_config.
It is set to yes
no. Should be prohibit-password, yes or without-password.

Please make sure it is set, otherwise Coolify cannot connect to the host system.

(Currently we only support root user to login via SSH, this will be changed in the future.)
###############################################################################
```

However, the PermitRootLogin is set to `yes` (confirmed via manual testing and running `sshd -T|grep permitrootlogin`.

### Minimal Reproduction (if possible, example repository)

1. Run `curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash` as root

### Version

4.0.0-beta.285

**Comment by peaklabs-dev** [comment]
I am unable to reproduce this issue, please upgrade to the latest version of Coolify v4 and try again, and if this is still an issue, feel free to reopen this issue or create a new one.
