### ISSUE TITLE
[Bug]: libstdc++.so.6 ImportError in Django Container Shell on self-hosted Coolify

### ISSUE THREAD

**Issue by brightkan** [coollabsio/coolify#2285]
### Description

When running the `/opt/venv/bin/python /app/manage.py <django_management_command>` command in the container shell or scheduled tasks, it fails with an ImportError. This issue does not occur when running the same command via the UI, where it works as expected. The error indicates that libstdc++.so.6 cannot be found, suggesting it might not be installed or added to the container properly. The issue prevents any efforts to add custom Django management commands in ***Coolify Scheduled Tasks***.

### Minimal Reproduction (if possible, example repository)

1. Deploy a stack using:
- v4.0.0-beta.285
- Django 4.2
- Python 3.10
- Nixpacks
Access the container shell using the name provided in the UI, in my case, it is something like "u44cogw-132156335844". using `docker exec -it <container_name> bash`
Run the command: `/opt/venv/bin/python /app/manage.py <django_management_command>`
Observe the `ImportError`

### Exception or Error

ImportError: libstdc++.so.6: cannot open shared object file: No such file or directory

### Version

v4.0.0-beta.285

**Comment by andrasbacsai** [comment]
There will be a few fixes in the upcoming version for scheduled tasks that could potentially solve this.

**Comment by peaklabs-dev** [comment]
@brightkan Please upgrade to the latest version of v4 and retest if this issue persists. Please let me know if this issue can be closed?

**Comment by brightkan** [comment]
@peaklabs-dev Thank you for the work well done. Issue resolved! Please go ahead and close this issue.
