### ISSUE TITLE
[Bug]: service [Logto] doesn't work

### ISSUE THREAD

**Issue by Haiananan** [coollabsio/coolify#2289]
### Description

My Logto service used to work fine, but it stopped working after I updated to [beta.285](https://github.com/coollabsio/coolify/releases/tag/v4.0.0-beta.285).

The logto log shows:
```
2024-05-24T11:09:23.570624040Z bQkcLKc7ED5HWwek   <-- GET /
2024-05-24T11:09:23.606054971Z bQkcLKc7ED5HWwek   --> GET / 302 45ms 123b
2024-05-24T11:09:28.760436670Z BHjuT-0aSHc7LzDu   <-- GET /
2024-05-24T11:09:28.808030397Z BHjuT-0aSHc7LzDu   --> GET / 302 47ms 123b
2024-05-24T11:09:33.960437927Z 8iHr3M3xu0BQpk6O   <-- GET /
2024-05-24T11:09:33.999334100Z 8iHr3M3xu0BQpk6O   --> GET / 302 38ms 123b
2024-05-24T11:09:39.129469795Z hc4D_yACE62VGhoD   <-- GET /
2024 -05 -24 T11 :09 :39 .169680489 Z hc4D_yACE62VGhoD-->GET/30242 ms123 b 
    wjIWQ44C Q8Ho_b42<--GET/
    wjIWQ44C Q8Ho_b42-->GET/3066 ms123 b 
```

The pg log shows:
```
FATAL：database "gmscrsuZOEVOnazB" does not exist.
FATAL：database "gmscrsuZOEVOnazB" does not exist.
FATAL：database "gmscrsuZOEVOnaz B" does not exist.
...more...
```       
I have tried reinstalling and updating, but it didn't work.
Can anyone tell me why?

### Minimal Reproduction (if possible, example repository)

```
services:
  logto:
    image: 'svhd/logto:${TAG-latest}'
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint:
      - sh
      - '-c'
      - 'npm run cli db seed -- --swe && npm start'
    environment:
      - TRUST_PROXY_HEADER=1
      - 'DB_URL=postgres://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@postgres:5432/${POSTGRES_DB:-logto}'
      - ENDPOINT=$LOGTO_ENDPOINT
      - ADMIN_ENDPOINT=$LOGTO_ADMIN_ENDPOINT
    healthcheck:
      test:
        - CMD
        - wget
        - '-q'
        - '--spider'
        - 'http://127.0.0.1:3002'
      interval: 5s
      timeout: 20s
      retries: 10
  postgres:
    image: 'postgres:14-alpine'
    user: postgres
    environment:
      POSTGRES_USER: '${SERVICE_USER_POSTGRES}'
      POSTGRES_PASSWORD: '${SERVICE_PASSWORD_POSTGRES}'
      POSTGRES_DB: '${POSTGRES_DB:-logto}'
    volumes:
      - 'logto-postgres-data:/var/lib/postgresql/data'
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-U'
        - $SERVICE_USER_POSTGRES
      interval: 5s
      timeout: 20s
      retries: 10
```

### Version

v4.0.0-beta.285

**Comment by johngrimsey** [comment]
I can't get Logto to work at all, following the default procedure. I always get SSL certificate invalid, and its the default Traefik cert. I have other compose services installed fine with my wildcard domain setup via SSL. Logto just refuses - not sure if its the same issue.

**Comment by Haiananan** [comment]
> I can't get Logto to work at all, following the default procedure. I always get SSL certificate invalid, and its the default Traefik cert. I have other compose services installed fine with my wildcard domain setup via SSL. Logto just refuses - not sure if its the same issue.

Yes, each visit will be redirected by SSL. This is a big problem, I need to use Logto as my application permission verification, and I urgently need a solution. I also tried running docker and postgres separately, but the result was the same. It should be an SSL-related issue.

**Comment by johngrimsey** [comment]
Can confirm @Haiananan default install also gives me the DB error, though I suspect this is logto issue not coolify

**Comment by Haiananan** [comment]
> Can confirm @Haiananan default install also gives me the DB error, though I suspect this is logto issue not coolify

find the problem: turn off the logto healthcheck, and everything ok

**Comment by johngrimsey** [comment]
Thanks @Haiananan that worked 👍

**Comment by johngrimsey** [comment]
To anybody else experiencing this:
* Add the Logto service via Coolify UI
* Edit the docker compose configuration (click the button)
* Remove the `healthcheck:` section of yaml from the `logto` service definition

**Comment by andrasbacsai** [comment]
It will be fixed in the next version.

**Comment by andrewbellucci** [comment]
I'm still getting the error mentioned.
<img width="453" alt="Screenshot 2024-06-04 at 12 19 26 PM" src="https://github.com/coollabsio/coolify/assets/62807636/b8fade8a-c206-4697-a80c-90126be7da49">

**Comment by andrewbellucci** [comment]
```
    healthcheck:
      test:
        - CMD-SHELL
        - sh
        - '-c'
        - 'pg_isready -U ${SERVICE_USER_POSTGRES} -d ${POSTGRES_DB:-logto}'
```
The above should fix the issue @andrasbacsai
