### ISSUE TITLE
[Bug]: nixpacks build fails: invalid argument

### ISSUE THREAD

**Issue by ton77v** [coollabsio/coolify#2292]
### Description

My Next.js app (repo-based resource, nixpacks) that was deploying fine with versions v4.0.0-beta.284 and earlier stopped working with a newer version. During the deployment:
```
[COMMAND] docker exec ... bash -c 'nixpacks build -c /artifacts/thegameplan.json --cache-key '...' --no-error-without-start -n ...:... /artifacts/XXX'
[OUTPUT]
Dockerfile:9
--------------------
7 | COPY .nixpacks/nixpkgs-....nix .nixpacks/nixpkgs-....nix
8 | RUN nix-env -if .nixpacks/nixpkgs-....nix && nix-collect-garbage -d
9 | >>> RUN sudo apt-get update && sudo apt-get install -y --no-install-recommends libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libgbm1 libasound2 libpangocairo-1.0-0 libxss1 libgtk-3-0 libxshmfence1 libglu1
10 |
11 | ARG CI NIXPACKS_METADATA NODE_ENV NPM_CONFIG_PRODUCTION NPM_TOKEN SOURCE_COMMIT
--------------------
ERROR: failed to solve: failed to prepare XXX as YYY: invalid argument
```

Pls note the line #11 with docker build ARGs; that's a wrong syntax indeed.

I've tried to deploy locally using the same nixpacks.toml, all went through without issues with nixpacks 1.21.3

### Minimal Reproduction (if possible, example repository)

I've also tried to deploy a simplest possible Next.js app created by "create-next-app". Example repo:
https://github.com/ton77v/next_js_app

Even this one fails, although a bit differently:
```
[COMMAND] docker exec ... bash -c 'nixpacks build -c /artifacts/thegameplan.json --cache-key '...' --no-error-without-start -n ...:... /artifacts/...'
[OUTPUT]
Dockerfile:19
--------------------
17 | # install phase
18 | ENV NIXPACKS_PATH /app/node_modules/.bin:$NIXPACKS_PATH
19 | >>> COPY . /app/.
20 | RUN --mount=type=cache,id=...-/root/npm,target=/root/.npm npm ci
21 |
--------------------
ERROR: failed to solve: failed to prepare XXX as YYY: invalid argument
```

### Exception or Error

ERROR: failed to solve: failed to prepare XXX as YYY: invalid argument

### Version

v4.0.0-beta.285

**Comment by andrasbacsai** [comment]
I'm trying to reproduce the issue, but when I simply deploy `[ton77v/next_js_app](https://github.com/ton77v/next_js_app)` it just works.

<img src="https://uploads.linear.app/0fa98b19-e5f3-418f-abaf-f6d47b6f525f/e5aedce3-5ae9-4f87-aeb6-83eaf3ef0dcf/ae0c6aca-81bc-4d20-b3d7-0e8793d1c2b0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzBmYTk4YjE5LWU1ZjMtNDE4Zi1hYmFmLWY2ZDQ3YjZmNTI1Zi9lNWFlZGNlMy01YWU5LTRmODctYWViNi04M2VhZjNlZjBkY2YvYWUwYzZhY2EtODFiYy00ZDIwLWIzZDctMGU4NzkzZDFjMmIwIiwiaWF0IjoxNzE2ODA0OTk3LCJleHAiOjMzMjg3MzY0OTk3fQ.ZbUChcpjs4I2H-v9s2RhWDL6DkrspNUwWpG4VlG6zBE " alt="image.png" width="600" height="225" />

 Do you have any environment variables set or anything other that the defaults?

**Comment by ton77v** [comment]
> I'm trying to reproduce the issue, but when I simply deploy `(https://github.com/ton77v/next_js_app)` it just works.
> 
> <img alt="image.png" width="600" height="225" src="https://camo.githubusercontent.com/ac9b4479887b23b92e79f15e60e0d603d6b8565101c6f3bde7630b6ef8852ed1/68747470733a2f2f75706c6f6164732e6c696e6561722e6170702f30666139386231392d653566332d343138662d616261662d6636643437623666353235662f65356165646365332d356165392d346638372d616562362d3833656166336566306463662f61653063366163612d383162632d346432302d623364372d3065383739336431633262303f7369676e61747572653d65794a68624763694f694a49557a49314e694973496e523563434936496b705856434a392e65794a775958526f496a6f694c7a426d59546b34596a45354c5755315a6a4d744e4445345a693168596d466d4c5759325a445133596a5a6d4e5449315a69396c4e57466c5a474e6c4d793031595755354c54526d4f446374595756694e6930344d3256685a6a4e6c5a6a426b5932597659575577597a5a68593245744f444669597930305a4449774c57497a5a4463744d4755344e7a6b7a5a44466a4d6d49774969776961574630496a6f784e7a45324f4441304f546b334c434a6c654841694f6a4d7a4d6a67334d7a59304f546b3366512e5a6255436863706a73344932482d76397332526857444c36446b7273704e557757704734566c47367a424520">
> 
> Do you have any environment variables set or anything other than the defaults?



> I'm trying to reproduce the issue, but when I simply deploy `(https://github.com/ton77v/next_js_app)` it just works.
> 
> <img alt="image.png" width="600" height="225" src="https://camo.githubusercontent.com/ac9b4479887b23b92e79f15e60e0d603d6b8565101c6f3bde7630b6ef8852ed1/68747470733a2f2f75706c6f6164732e6c696e6561722e6170702f30666139386231392d653566332d343138662d616261662d6636643437623666353235662f65356165646365332d356165392d346638372d616562362d3833656166336566306463662f61653063366163612d383162632d346432302d623364372d3065383739336431633262303f7369676e61747572653d65794a68624763694f694a49557a49314e694973496e523563434936496b705856434a392e65794a775958526f496a6f694c7a426d59546b34596a45354c5755315a6a4d744e4445345a693168596d466d4c5759325a445133596a5a6d4e5449315a69396c4e57466c5a474e6c4d793031595755354c54526d4f446374595756694e6930344d3256685a6a4e6c5a6a426b5932597659575577597a5a68593245744f444669597930305a4449774c57497a5a4463744d4755344e7a6b7a5a44466a4d6d49774969776961574630496a6f784e7a45324f4441304f546b334c434a6c654841694f6a4d7a4d6a67334d7a59304f546b3366512e5a6255436863706a73344932482d76397332526857444c36446b7273704e557757704734566c47367a424520">
> 
> Do you have any environment variables set or anything other than the defaults?

Yes, I have the environment variables including one required for the build stage.

Although since you can deploy the test project without issues, I assume the issue may be related to my VM.

**Comment by andrasbacsai** [comment]
I tried to deploy on ARM & AMD based systems, but same, it works.

**Comment by pax-k** [comment]
Same

```
root@524b2b62a4e2:/home# nixpacks build --name dan-app react-redux-realworld-example-app/

╔════════ Nixpacks v1.24.0 ═══════╗
║ setup      │ nodejs_18, npm-9_x ║
║─────────────────────────────────║
║ install    │ npm i              ║
║─────────────────────────────────║
║ build      │ npm run build      ║
║─────────────────────────────────║
║ start      │ npm run start      ║
╚═════════════════════════════════╝

[+] Building 1.5s (9/14)                                                                                                                        docker:default
 => [internal] load build definition from Dockerfile                                                                                                      0.0s
 => => transferring dockerfile: 977B                                                                                                                      0.0s
 => [internal] load metadata for ghcr.io/railwayapp/nixpacks:ubuntu-1716249803                                                                            0.2s
 => [internal] load .dockerignore                                                                                                                         0.0s
 => => transferring context: 2B                                                                                                                           0.0s
 => [internal] load build context                                                                                                                         0.0s
 => => transferring context: 769.73kB                                                                                                                     0.0s
 => [stage-0  1/10] FROM ghcr.io/railwayapp/nixpacks:ubuntu-1716249803@sha256:5ef4d2021c418fcaabb56cea5ea9e24a5fdedfe27f58062d9689214dfed45c46            0.0s
 => CACHED [stage-0  2/10] WORKDIR /app/                                                                                                                  0.0s
 => CACHED [stage-0  3/10] COPY .nixpacks/nixpkgs-bf446f08bff6814b569265bef8374cfdd3d8f0e0.nix .nixpacks/nixpkgs-bf446f08bff6814b569265bef8374cfdd3d8f0e  0.0s
 => CACHED [stage-0  4/10] RUN nix-env -if .nixpacks/nixpkgs-bf446f08bff6814b569265bef8374cfdd3d8f0e0.nix && nix-collect-garbage -d                       0.0s
 => ERROR [stage-0  5/10] COPY . /app/.                                                                                                                   1.2s
------
 > [stage-0  5/10] COPY . /app/.:
------
Dockerfile:19
--------------------
  17 |     # install phase
  18 |     ENV NIXPACKS_PATH /app/node_modules/.bin:$NIXPACKS_PATH
  19 | >>> COPY . /app/.
  20 |     RUN --mount=type=cache,id=867G5jhyMq0-/root/npm,target=/root/.npm npm i
  21 |
--------------------
ERROR: failed to solve: failed to prepare wrk9yhuhntx6ke4gf4c64wqos as 8ynk2xj3i5ndbx6e3zca3xu6b: invalid argument
Error: Docker build failed
root@524b2b62a4e2:/home# ^C
root@524b2b62a4e2:/home# ll
total 16
drwxr-xr-x 1 root root 4096 May 29 12:36 ./
drwxr-xr-x 1 root root 4096 May 29 12:33 ../
drwxr-xr-x 2 root root 4096 May 29 12:36 .nixpacks/
drwxr-xr-x 5 root root 4096 May 29 12:34 react-redux-realworld-example-app/
root@524b2b62a4e2:/home#
```

**Comment by andrasbacsai** [comment]
I'm updating nixpacks to the latest version, because it still looks like a nixpacks bug.

**Comment by andrasbacsai** [comment]
If it is not solved, let me know please.
