### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by andrasbacsai** [coollabsio/coolify#2298]
Currently, `/command-center` executes one command at a time on the server.

We need a fully functioning terminal instead of that. 

It should be reusable on other parts of the UI as well, for example by opening a terminal to a specific docker container (like `WordPress`) to edit files.

**Comment by paoloricciuti** [comment]
I don't think I have the energy and time to fully work on this but I guess sharing ideas is a form of contributing too:

You can use `XTerm.js` which is a fully featured implementation of a terminal in JavaScript.

Here's the docs for it

https://xtermjs.org/docs/

I have a bit of experience in it (not too much) so if anybody need help feel free to contact me here or anywhere else (obviously no part of the bounty required lol, just here to help)

**Comment by raikasdev** [comment]
I'd be interested in working on this, but I'll have to dig more into how Coolify technically works before I'll attempt this if someone that already knows the bells and whistles wants to try. I write PHP for work but haven't used Laravel before.

I have experience of similar implementations with Xterm as I have created the [ohjelmoi.fi development environment](https://v3.ohjelmoi.fi/playground)'s interactive terminal with it.

**Comment by muhammedaksam** [comment]
Very nice idea.

**Comment by Thanzex** [comment]
I'd like to contribute too, I'm switching to Coolify and this feature would be very helpful indeed.

I did take a peek at how other tools are implementing this feature, [Portainer](https://github.com/portainer/portainer) takes a fairly simple approach, which is to simply proxy all requests to the Docker api.
There's a little bit of logic in the frontend to send and receive via a websocket and setup the session, on the backend it checks if the session has been terminated via command or hotkey.

The frontend calls a `.../docker/containers/{hash}/exec` endpoint which gets proxied by the backend to the Docker API, converted to a WS session and then the rest is handled by Xterm.

I'm not an expert of Laravel and in this time I haven't been able to find how to implement this, but if the reverse-proxy aspect cannot be easily implemented I would guess a simple forward of the websocket messages could be the solution, even reusing the existing infrastructure that handles the logs

**Comment by LEstradioto** [comment]
/attempt #2298

Followed your ideas, xterm.js and @Thanzex approach.

I've attempted to implement WebSockets in PHP, but it turned out to be more challenging than expected. I then switched to using Node.js with XTerm and pty, which has been working well. I like the architecture, but I think @andrasbacsai should review it to assess any potential security risks, as I'm not fully aware of them.

https://github.com/coollabsio/coolify/assets/22579355/f717a407-6c3d-4167-88e6-fabdd1d2cbf3

Currently, the terminal only appends to a server, but I don't see any issues with extending this functionality to containers as well.

Later on, I'll post the wip branch here

**Comment by Thijmen** [comment]
Wow @LEstradioto, that looks very promising! I know my fair share of Laravel and security, feel free to whip up a draft PR and I will take a look and address possible concerns. 

How do you feel about that? Happy to help!

**Comment by LEstradioto** [comment]
I would really appreciate it! Here's the PR #2586.

I'm still getting used to Laravel, but this draft works. I think a review would really help !

**Comment by jerch** [comment]
@LEstradioto On a sidenote - you dont have to use websockets with xterm.js, you can also use good old request-response cycling with ajax/fetch long-polling. While it not be as performant as with websockets (con), it would also inherit security mechs of you normal site setup (pro).

**Comment by LEstradioto** [comment]
Oh yeah. Nice to know. That PR have some good additional observations too. But terminal worked nicely

**Comment by LEstradioto** [comment]
Its still open. But, Ive open a PR #2586 and awaiting @andrasbacsai position on this

I think, the challenge right now is to re-use services that exists without adding a new service. Ive added a nodejs websocket to work with the xterm.js terminal.

Do you have any suggestions on this? Or, If you want to take a shot, no problem for me at all

**Comment by andrasbacsai** [comment]
> Its still open. But, Ive open a PR #2586 and awaiting @andrasbacsai position on this
> 
> I think, the challenge right now is to re-use services that exists without adding a new service. Ive added a nodejs websocket to work with the xterm.js terminal.
> 
> Do you have any suggestions on this? Or, If you want to take a shot, no problem for me at all

I will test it with the current implementation (node) and if it works and does not take up too much resource, then I will merge it.

**Comment by AliShaatani** [comment]
guys thank you brilliant work, please make this terminal comes to live, cuz there is a lot of cases when we want to use vim/nano, which is impossible with the current versions

**Comment by LEstradioto** [comment]
The [PR](https://github.com/coollabsio/coolify/pull/2586) is concluded, waiting @andrasbacsai on a new review.
Just a bump here. 

Terminal process runs within Soketi service, so no more extra container
About security concerns Ive added authentication on Websocket using verifyClient option to authenticate user on Laravel

So its pretty much done!

**Comment by emjayess** [comment]
I have only just scanned the comments here, and lightly glanced over additional remarks in the PR, and I wonder has anyone considered or already attempted to do this using [Laravel Reverb](https://laravel.com/docs/master/reverb)?.. seems if that could fit the bill for websockets, it would alleviate the need for an extra container and soketi dependency (if I'm following along well enough).

**Comment by LEstradioto** [comment]
Hi @emjayess. I dont know Reverb well enough, it just seems the same as Pusher.

Problem is that we need to use `node-pty` as pseudo-terminal. If we use PHP we must create that lib from the ground, to be compatible/synced with `xterm.js`

Another one, is creating a long running process inside a Laravel Event. Ive tried and failed, perhaps its possible, but even with this we need a pseudo-terminal then, meaning, need somethin similar to `node-pty`

**Comment by jerch** [comment]
Hmm I just checked PHP corelibs  and indeed - seems PHP has no support for spawning PTYs. Thats a bummer, it means that any PHP-related solution needs to be a native/C module. Bad.

[Here](https://github.com/ammarfaizi2/TeaOpenPTY) is such a lib for PHP, idk whether it is any good or bad in quality/maintenance.

Idk your tech stack, is writing/maitaining your own C module within your goals or far overstretched?

**Comment by LEstradioto** [comment]
Hi @jerch ! Great work! 👍 I saw TeaOpenPTY during my research, but C modules were out of my comfort zone. Your solution is much more elegant.

Quick question: Is there a way to reconnect to an existing process/PTY across requests? I tried using Symfony/Laravel Process to start a PTY, it worked, but couldn't figure out how to reattach on subsequent requests. Any thoughts on this?

**Comment by LEstradioto** [comment]
Yep yep, two big PHP Laravel challenges. Well, @andrasbacsai should evaluate this 👀

**Comment by blinkinglight** [comment]
https://www.supertechcrew.com/wetty-browser-ssh-terminal/ or maybe https://github.com/yudai/gotty ?

**Comment by LEstradioto** [comment]
I've seen those libraries as well. They were definitely inspirational for that PR, which essentially has the same logic as well, but adapted to Coolify's ssh. However, they still requires websocket and `node-pty`

**Comment by LEstradioto** [comment]
Here's what I'm thinking for next steps (and a summary for future suggestions):

1. I'll finish the PR to adapt the Dockerfile. This should serve as a good starting point for version 1.

For a future version of Terminal, we could consider:
2. Rewriting node-pty in PHP (would require expertise in both C and PHP)
3. Replacing node websocket with PHP equivalent

This would be a challenge but real fun!

(Apologies to issue followers - this seems to evolved into more of a discussion than a typical issue)

**Comment by blinkinglight** [comment]
https://github.com/coollabsio/coolify/discussions/3362

**Comment by jerch** [comment]
> For a future version of Terminal, we could consider:
> 
>     2. Rewriting node-pty in PHP (would require expertise in both C and PHP)
>     3. Replacing node websocket with PHP equivalent

Well if you are really up for your own low level impl, I can help you with the C part. But I'd need some guidance with your process/thread model in coolify, esp. where to put a long living PTY (must survive a request/response cycles).

**Comment by andrasbacsai** [comment]
Any further iteration / feature will be handled in a different issue.

**Comment by andrasbacsai** [comment]
Please also do the Algora reward @cloudgakkai, @muhammedaksam, @saint

**Comment by DeVoresyah** [comment]
> Please also do the Algora reward @CloudGakkai, @muhammedaksam, @saint

will be process by 25th this month from our side.

**Comment by LEstradioto** [comment]
Thank you!

**Comment by DeVoresyah** [comment]
hi @LEstradioto @andrasbacsai , idk why on my Algora account there is no "Reward" button that usually used to send the reward

<img width="806" alt="image" src="https://github.com/user-attachments/assets/4ef79bfc-c02d-4e91-85ea-020ddb920a6e">

**Comment by muhammedaksam** [comment]
> Please also do the Algora reward @CloudGakkai, @muhammedaksam, @saint

I am still trying to pay but it won't let me process.

**Comment by DeVoresyah** [comment]
> > Please also do the Algora reward @CloudGakkai, @muhammedaksam, @saint
> 
> I am still trying to pay but it won't let me process.

I think Algora has an issue, I also cannot process because the "Reward" button didn't appear

**Comment by LEstradioto** [comment]
No problem, guys! I've sent an email to them. Let's wait a bit.

**Comment by DeVoresyah** [comment]
is there any updates on this? the Reward button still won't appear on my side

**Comment by algora-pbc** [comment]
Hey @DeVoresyah @muhammedaksam :wave:  sorry about the reward button not showing

We have resolved the issue now, the bounties can be paid out from your dashboard once you log in

**Comment by DeVoresyah** [comment]
Thanks @algora-pbc
