### ISSUE TITLE
[Bug]:  Volume mounts on nixpacks container do not work.

### ISSUE THREAD

**Issue by brightkan** [coollabsio/coolify#2302]
### Description

The volume mount no longer works. Any attempt to add volume yields the error: The file storage path field must be a string. (and 2 more errors

### Minimal Reproduction (if possible, example repository)

- Nixpacks
- Add a volume mount only

### Exception or Error

The file storage path field must be a string. (and 2 more errors

### Version

v4.0.0-beta.287

**Comment by andrasbacsai** [comment]
Fixed in v288.
