### ISSUE TITLE
[Bug]: Clouflare Tunnel ERR_SSL_VERSION_OR_CIPHER_MISMATCH

### ISSUE THREAD

**Issue by danielehrhardt** [coollabsio/coolify#2308]
### Description

If i use the Coudflare Proxy and use a Coolify Server i get ERR_SSL_VERSION_OR_CIPHER_MISMATCH. 

### Minimal Reproduction (if possible, example repository)

Setup a HTTPS Server in Coolify for example with Node and set the IP in Cloudflare with Proxy enabled. 

### Version

v4.0.0-beta.288

**Comment by liontariai** [comment]
Maybe this helps:

![grafik](https://github.com/coollabsio/coolify/assets/157399222/7bb0499c-ca99-465b-a09e-5a367bdfca05)
https://billyle.dev/posts/self-hosting-your-website-with-coolify-v4-a-step-by-step-guide
