### ISSUE TITLE
Feature Request: Add Service from Docker Image

### ISSUE THREAD

**Issue by planecore** [coollabsio/coolify#231]
I'd like to add a service from a Docker Hub image or from a Dockerfile.

It would help to deploy any public service we want immediately and easily!

**Comment by jugglingjsons** [comment]
@planecore take a look here -> https://github.com/coollabsio/documentation/pull/6
Simple services can already be deployed as custom applications - not sure if that's what you were after though.

**Comment by themarkwill** [comment]
@planecore now is possible you create a application with a Dockerfile, you need only add a docker file of configuration in your repository, and start de deploy!
More about it https://docs.coollabs.io/coolify/applications/#supported-applications

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
