### ISSUE TITLE
[Bug]:  MySQL backup cannot be created

### ISSUE THREAD

**Issue by fcpauldiaz** [coollabsio/coolify#2314]
### Description

backup command cannot access database using default db and mysql native password 

config here:

![Screenshot 2024-05-29 at 11 51 30 AM](https://github.com/coollabsio/coolify/assets/4523284/e575a798-48d6-4014-b95b-adc2967a5d9b)

![Screenshot 2024-05-29 at 11 52 03 AM](https://github.com/coollabsio/coolify/assets/4523284/7a92dfb3-b22f-4910-aae3-2e4a44dde4a7)

### Minimal Reproduction (if possible, example repository)

1.  create new database service, select mysql
2. deploy and enable backups.

### Exception or Error

Database: default
Status: failed
Started At: 2024-05-29 17:45:16
Message: mysqldump: [Warning] Using a password on the command line interface can be insecure. mysqldump: Got error: 1045: Access denied for user 'root'@'localhost' (using password: YES) when trying to connect
Size: 0 B / 0 kB / 0 MB
Location: N/A

### Version

v4.0.0-beta.288

**Comment by andrasbacsai** [comment]
It is probably caused that you changed the root password in the database. In the next version, you can update these passwords on the UI, so it automations (like backups) will work.

**Comment by andrasbacsai** [comment]
Also add a small hint.

<img src="https://uploads.linear.app/0fa98b19-e5f3-418f-abaf-f6d47b6f525f/4e5ffb92-2232-44c6-bd10-1a61ffa90331/ae702403-6f38-4f7c-b4d8-9537c980c82c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzBmYTk4YjE5LWU1ZjMtNDE4Zi1hYmFmLWY2ZDQ3YjZmNTI1Zi80ZTVmZmI5Mi0yMjMyLTQ0YzYtYmQxMC0xYTYxZmZhOTAzMzEvYWU3MDI0MDMtNmYzOC00ZjdjLWI0ZDgtOTUzN2M5ODBjODJjIiwiaWF0IjoxNzE3NTgwNTk1LCJleHAiOjMzMjg4MTQwNTk1fQ.5rgQhJ8-fe29W2mkTiz1hAhNjFsirN5gXiVfVKv8Cpo " alt="image.png" width="712" height="96" />

**Comment by fcpauldiaz** [comment]
I didn't changed the root password but I will try to update it in the UI

**Comment by fcpauldiaz** [comment]
I can execute this command inside the docker only using the ip address of the server but it doesn't work if use localhost as the host, since the mysqldump also uses localhost it doesn't connect. @andrasbacsai 

```
mysql -u root -p rootpassword -h ipaddress
```

using the name of the docker also works as a host
```
mysq -u rooot -p rootpassword -h ucg0woo
````

but this doesn't work

```
mysql -u root -p rootpassword -h localhost
```
