### ISSUE TITLE
[Bug]: InstanceAutoUpdateJob failed: Already on latest version

### ISSUE THREAD

**Issue by goldo** [coollabsio/coolify#2319]
### Description

since today, I got this notification message every 10 mins
```
InstanceAutoUpdateJob failed: Already on latest version
```

### Minimal Reproduction (if possible, example repository)

basic coolify setup, 1 domain name, nothing fancy, 1 app

![Screenshot 2024-05-30 at 15 54 11](https://github.com/coollabsio/coolify/assets/518930/a0e69007-7c18-4ddf-8613-806219efc7a5)

### Exception or Error

`InstanceAutoUpdateJob failed: Already on latest version`

### Version

v4.0.0-beta.291

**Comment by andrasbacsai** [comment]
It is fixed in v292.

If you cannot update, you can do two things:
1. Enable autoupdate and wait (or manually update when it is enabled).
2. Execute the installation script from terminal. This will update your instance.
