### ISSUE TITLE
[Bug]: Auto update is disabled when trying to manually update

### ISSUE THREAD

**Issue by ck-euan** [coollabsio/coolify#2321]
### Description

Auto update is disabled on my Coolify server so I usually update manually.

However, since upgrading from 4.0.0-beta.288 -> 4.0.0-beta.290 successfully, the update button no longer works.

I get this toast message and the update screen hangs

<img width="599" alt="image" src="https://github.com/coollabsio/coolify/assets/147141389/548ff905-d62a-4256-a1d2-8efa64490222">

### Minimal Reproduction (if possible, example repository)

1. Disable auto update
2. Try to manually update
3. Observe the error

### Version

4.0.0-beta.290

**Comment by leonovk** [comment]
I have a completely similar situation

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.

**Comment by andrasbacsai** [comment]
If you cannot update, you can do two things:
1. Enable autoupdate and wait (or manually update when it is enabled).
2. Execute the installation script from terminal. This will update your instance.
