### ISSUE TITLE
[Bug]: many notification for InstanceAutoUpdateJob failed: Already on latest version

### ISSUE THREAD

**Issue by jacopobonomi** [coollabsio/coolify#2322]
### Description

I am currently receiving notifications (in Telegram) every 10 minutes with the message: "InstanceAutoUpdateJob failed: Already on latest version." Since the system is already updated, these frequent notifications seem unnecessary and could potentially be minimized.

Would it be possible to adjust the notification settings so that this particular alert is only sent when there are actionable updates or issues? 
Alternatively, could we consider commenting out or modifying the line of code, attach on bottom, that triggers this alert under these conditions?
[Line of code incriminated](https://github.com/coollabsio/coolify/blob/main/app/Actions/Server/UpdateCoolify.php#L46)

### Minimal Reproduction (if possible, example repository)

Install latest version of coolfy and connect with a Telegram bot, maybe with all notification channels.

### Version

v4.0.0-beta.291

**Comment by 0xtlt** [comment]
Same thing here
https://x.com/0xtlt/status/1796191054258921878

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.

**Comment by andrasbacsai** [comment]
If you cannot update, you can do two things:
1. Enable autoupdate and wait (or manually update when it is enabled).
2. Execute the installation script from terminal. This will update your instance.
