### ISSUE TITLE
Coolify Redis Connection Failure: Temporary Name Resolution Error, I can't enter in coolify

### ISSUE THREAD

**Issue by August7337** [coollabsio/coolify#2331]
### Description

Encountered a persistent issue with Coolify where the application fails to connect to Redis, resulting in the error: "php_network_getaddresses: getaddrinfo for coolify-redis failed: Temporary failure in name resolution." This problem arises after deploying the app with Docker and using Coolify for orchestration. Additionally, the Coolify container enters a restart loop following a server reboot, exacerbating the connectivity issue and rendering the application inaccessible.

### Minimal Reproduction (if possible, example repository)

create a docker compose on coolify and put `docker build -t q080scg-laravel:latest .` on custome build commande

### Exception or Error

When trying to access Coolify befor restarting, the following error message is displayed:

`Something is not okay, are you okay?
There has been an error, we are working on it.

Error: php_network_getaddresses: getaddrinfo for coolify-redis failed: Temporary failure in name resolution`

After rebooting the server, the Coolify container enters a continuous restart loop. Here are the relevant logs:

`--------------------------------------------------------------------
____                             ____  _     _        _   _
/ ___|  ___ _ ____   _____ _ __  / ___|(_) __| | ___  | | | |_ __
\___ \ / _ \  __\ \ / / _ \  __| \___ \| |/ _` |/ _ \ | | | |  _ \
 ___) |  __/ |   \ V /  __/ |     ___) | | (_| |  __/ | |_| | |_) |
|____/ \___|_|    \_/ \___|_|    |____/|_|\__,_|\___|  \___/| .__/
                                                            |_|

Brought to you by serversideup.net
--------------------------------------------------------------------

To support Server Side Up projects visit:
https://serversideup.net/sponsor
-------------------------------------
GID/UID
-------------------------------------

User uid:    9999
User gid:    9999
-------------------------------------

🔓 SSL_MODE has been DISABLED, setting the web server to work in HTTP only...
🏃‍♂️ Checking for Laravel automations...
🔐 Linking the storage...

   ERROR  The [public/storage] link already exists.

[30-May-2024 20:31:47] NOTICE: fpm is running, pid 100
[30-May-2024 20:31:47] NOTICE: ready to handle connections
[30-May-2024 20:31:47] NOTICE: systemd monitor interval set to 10000ms

In PhpRedisConnector.php line 159:

  php_network_getaddresses: getaddrinfo for coolify-redis failed: Temporary f
  ailure in name resolution

In PhpRedisConnector.php line 159:

  Redis::connect(): php_network_getaddresses: getaddrinfo for coolify-redis f
  ailed: Temporary failure in name resolution

s6-rc: warning: unable to start service db-migration: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.
[30-May-2024 20:31:49] NOTICE: Terminating ...
[30-May-2024 20:31:49] NOTICE: exiting, bye-bye!
`

### Version

coolify:4.0.0-beta.291

**Comment by peaklabs-dev** [comment]
As this is quite old I assume it has probably been fixed if not please provide an example repository as I am unable to reproduce this issue. Also please upgrade to the latest version of Coolify v4 and try again, and if this is still an issue, feel free to reopen this issue or create a new one.
