### ISSUE TITLE
[Bug]: Preview deployments broken for docker-compose setups

### ISSUE THREAD

**Issue by Tahul** [coollabsio/coolify#2336]
### Description

I get these error messages when deploying a preview deployment for a Docker Compose setup

It used to work when I didn't exposed an URL for more than one service, but since I exposed my API as well as my frontend, it now throws this error for preview deployments.

### Minimal Reproduction (if possible, example repository)

I suppose this happens on any Docker Compose setups that exposes more than 1 FQDN?

### Exception or Error

```
[2024-Jun-01 01:54:42.602290] Oops something is not okay, are you okay? 😢

[2024-Jun-01 01:54:42.607173] Array to string conversion
```

Also it seem to have broke this field in the UI (also throwing `Array to string conversion` in console):

![CleanShot 2024-06-01 at 04 02 01@2x](https://github.com/coollabsio/coolify/assets/1385263/d1925367-7937-4638-ac9e-542b6940c2ae)

It also prevents me from removing the preview deployment, same error message when clicking on `Delete`

### Version

v4.beta.291 (cloud)

**Comment by Tahul** [comment]
As #2330 seem to mention `docker-compose` related issues, I guess it might help?

**Comment by andrasbacsai** [comment]
Can you please recheck with the latest version?

**Comment by andrasbacsai** [comment]
I also will add a few fixes to the preview deployments in the next version.

**Comment by Tahul** [comment]
I did not had time yet to try it @andrasbacsai ; sorry!

Do you still need it?

**Comment by andrasbacsai** [comment]
After the next release yes.

**Comment by scflode** [comment]
I just installed the `v4.0.0-beta.297` manually and still get the here mentioned `Array to string conversion` errors on preview deployment and when trying to delete a preview deployment manually.
