### ISSUE TITLE
[Bug]: Post-deployment Command Causes Application to Stop on Error

### ISSUE THREAD

**Issue by hamedyosefian** [coollabsio/coolify#2342]
### Description

My application requires running a post-deployment command to initiate a worker for certain tasks. When I manually execute this command in the command section after the application build, everything works fine. However, when I add this command to the post-deployment field, the command runs successfully and the worker starts. The issue arises when the worker encounters any error, which causes the entire application to terminate and stop running.

I suspect the problem is that the post-deployment command runs in the same terminal as the application. If the post-deployment command could run in a new terminal, this issue might be avoided.

### Minimal Reproduction (if possible, example repository)

	1.	Build the application.
	2.	Manually run the post-deployment command in the command section to start the worker.
	3.	Add the same command to the post-deployment field.
	4.	Deploy the application and observe that any error in the worker causes the entire application to stop.

### Version

v4.0.0-beta.291

**Comment by hamedyosefian** [comment]
@andrasbacsai 
this sample command for my application :
/bin/sh -c "node apps/dashboard/.next/server/datasource-loader.js"

**Comment by andrasbacsai** [comment]
Thank you! I can confirm the bug!

**Comment by andrasbacsai** [comment]
The next version will have this fixed. The deployment status will be failed, but the new app version will still remain. It won't rollback to the older app version.

**Comment by hamedyosefian** [comment]
Thanks for fixing the bug! 🛠️ Your attention to the feedback is golden! 🌟
