### ISSUE TITLE
[Bug]: SSL connection timeout

### ISSUE THREAD

**Issue by denisavitski** [coollabsio/coolify#2345]
### Description

I can’t deploy the site from github using any of the suggested methods(public repository, github app, deploy key). At one of the steps one way or another I get an error related to curl: 

_cURL error 28: SSL connection timeout (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api.github.com/repos/coollabsio/coolify-examples/branches/master_

![Снимок экрана 2024-06-03 в 17 36 06](https://github.com/coollabsio/coolify/assets/142801021/a1699041-31a5-470b-824f-3aba99f7d07e)

![Снимок экрана 2024-06-03 в 17 34 15](https://github.com/coollabsio/coolify/assets/142801021/ed213824-6bec-4bdb-b51e-edfe14a5bd57)

This error has already [been discussed](https://discord.com/channels/459365938081431553/1217554007778791636/1217554007778791636), but there is no solution there.

### Minimal Reproduction (if possible, example repository)

I just used the automatic installation as written in the docs.

### Version

v4.0.0-beta.293

**Comment by kefniark** [comment]
Getting exactly the same issue, in my case directly trying to deploy a public repository from github
> cURL error 28: SSL connection timeout (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api.github.com/repos/kefniark/mango/branches/master

## Environment
* Ubuntu container freshly installed with `Ubuntu 22.04.4 LTS`
* Coolify fresh install through `curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash`
* Version: v4.0.0-beta.293

**Comment by takeerdevs** [comment]
Well, this is weird.. 
`[2024-Jun-04 08:43:05.922148]

[COMMAND] docker run -d --network coolify --name xos0cws --rm -v /var/run/docker.sock:/var/run/docker.sock ghcr.io/coollabsio/coolify-helper:latest
[OUTPUT] Unable to find image 'ghcr.io/coollabsio/coolify-helper:latest' locally  
[2024-Jun-04 08:43:55.946646]

[COMMAND] docker run -d --network coolify --name xos0cws --rm -v /var/run/docker.sock:/var/run/docker.sock ghcr.io/coollabsio/coolify-helper:latest
[OUTPUT] docker: Error response from daemon: Get "[https://ghcr.io/v2/":](https://ghcr.io/v2/) dial tcp: lookup ghcr.io on 127.0.0.53:53: read udp 127.0.0.1:48193->127.0.0.53:53: i/o timeout. See 'docker run --help'. 
[2024-Jun-04 08:43:58.023848] Oops something is not okay, are you okay? 😢  
[2024-Jun-04 08:43:58.026132] Unable to find image 'ghcr.io/coollabsio/coolify-helper:latest' locally docker: Error response from daemon: Get "[https://ghcr.io/v2/":](https://ghcr.io/v2/) dial tcp: lookup ghcr.io on 127.0.0.53:53: read udp 127.0.0.1:48193->127.0.0.53:53: i/o timeout. See 'docker run --help'. 
[2024-Jun-04 08:43:58.028072] Deployment failed. Removing the new version of your application.`

**Comment by kefniark** [comment]
Ok I found out, in my case it was a networking issue because of MTU.
The network is using a VNET with MTU 1450 but docker/coolify didn't detect it properly and created all the network with MTU 1500. So the networking is kinda unstable

To fix it
1. Set docker `/etc/docker/daemon.json` and add the following
```json
  "mtu": 1450,
  "default-network-opts": {
    "bridge": {
      "com.docker.network.driver.mtu": "1450"
    },
  },
```
2. Sadly the above configuration only apply at network creation, so all the networks already created by coolify are misconfigured. So going through https://coolify.io/docs/uninstall
Cleanup the containers and the networks (but keep the volumes)
3. Re-run `curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash`
All the network should be recreated with the right mtu this time

Now it's working properly

**Comment by andrasbacsai** [comment]
This is not related to Coolify, but a network configuration on your server / hosting provider. 

Detecting it is out of scope at the moment.
