### ISSUE TITLE
[Feature]: Plane Template

### ISSUE THREAD

**Issue by DeVoresyah** [coollabsio/coolify#2354]
### Description

I want a template for [Plane](https://plane.so/) merged into this Coolify repo.
Suppose you can get a Plane template working and merged I consider that the bounty is complete.

### Minimal Reproduction (if possible, example repository)

n/a

### Version

n/a

**Comment by SaadBazaz** [comment]
/attempt #2354

I've made a rough docker-compose which can get Plane up and running, but it's not part of Coolify's official templates yet. I'll try to turn that into something which works.

**Comment by DeVoresyah** [comment]
> /attempt #2354
> 
> I've made a rough docker-compose which can get Plane up and running, but it's not part of Coolify's official templates yet. I'll try to turn that into something which works.
> 
> Options
> * [
>           Cancel my attempt
>         ](https://console.algora.io/api/bounties/clx0slqrk000cla09o9jl1fgs/cancel-attempt)

awesome, please create a PR for that~! don't forget to include /claim on body PR

**Comment by SaadBazaz** [comment]
@DeVoresyah  Done!

**Comment by MrAlexand0r** [comment]
/attempt https://github.com/coollabsio/coolify/issues/2354

The last pull request has been stale for over a month, so I started working on my own service template.
Will create a PR once I finished testing

**Comment by andrasbacsai** [comment]
@DeVoresyah After publishing v314 (when this issue is closed), could you please add the bounty prize to @MrAlexand0r ?

**Comment by DeVoresyah** [comment]
> @DeVoresyah After publishing v314 (when this issue is closed), could you please add the bounty prize to @MrAlexand0r ?

sure as always~!

**Comment by DeVoresyah** [comment]
just want to inform @MrAlexand0r , that the bounty will be sent at the end of the month. I need to wait for approval from the finance.
