### ISSUE TITLE
[Bug]: When activating proxy an error on docker-compose is issued

### ISSUE THREAD

**Issue by Hugo0Vaz** [coollabsio/coolify#2357]
### Description

When trying to enable the proxy the following error log is outputed:

"Creating required Docker Compose file.
Pulling docker image.
docker: 'compose' is not a docker command.
See 'docker --help'"

![image](https://github.com/coollabsio/coolify/assets/5963279/13f5462c-77eb-4a4d-a5de-bdc723a71c08)

### Minimal Reproduction (if possible, example repository)

Just try to enable the proxy

### Exception or Error

Creating required Docker Compose file.
Pulling docker image.
docker: 'compose' is not a docker command.
See 'docker --help'

### Version

v4.0.0-beta.294

**Comment by andrasbacsai** [comment]
It looks like your server has docker preinstalled (probably from [snap](https://snapcraft.io/)), am I right?

**Comment by Hugo0Vaz** [comment]
Well, probably, not quite shure. I just nuked the VPS and did a fresh install of everything, and it is working just right.
