### ISSUE TITLE
[Bug]: Preview Deployment containers are not removed after merging the PR

### ISSUE THREAD

**Issue by ton77v** [coollabsio/coolify#2358]
### Description

After the PR is merged, the container keeps running. AFAIR it was working properly in 28X versions 

### Minimal Reproduction (if possible, example repository)

1. Add a repo-based resource; in my use case it's using Nixpacks deployment
2. Configure auto PR deployments in "Advanced" Configuration
3. Create PR in your repo
4. Merge into main
5. Either run
```
docker ps
```
- or go to the Configuration: Preview Deployments

And you'll see that the one you've closed is still running

### Version

v4.0.0-beta.294

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.
