### ISSUE TITLE
[Bug]: Supabase Minio Bucket Unhealthy - Supabase dashboard unable to create bucket

### ISSUE THREAD

**Issue by chemistry-rocks** [coollabsio/coolify#2360]
### Description

<img width="645" alt="minio create" src="https://github.com/coollabsio/coolify/assets/171797264/acff221d-11ba-4c9a-bbc1-6ba5bc643005">
<img width="264" alt="storage-not-load" src="https://github.com/coollabsio/coolify/assets/171797264/a51aee5c-7dfa-45ee-8f3f-b094dd07bb9d">
<img width="547" alt="create-bucket-1" src="https://github.com/coollabsio/coolify/assets/171797264/3a914e04-b782-4143-9144-dd5f2d3fa211">
<img width="359" alt="create-bucket-2-error" src="https://github.com/coollabsio/coolify/assets/171797264/faac01de-cb95-4a4a-b8b3-1f0ebb7482b1">

### Minimal Reproduction (if possible, example repository)

1. Launch supabase service, localhost, default settings. All services created properly except miniocreate bucket which exited. 
2. Log into supabase dashboard with credentials, navigate to Storage on left navbar.
3. Continous Loading of buckets
4. Try to create bucket
5. Bucket fetch error

Coolify [v4.0.0-beta.294]

### Version

v4.0.0-beta.294

**Comment by RealmKnight** [comment]
I have the same issue except I get the error "Failed to create bucket: headers must have required property 'authorization' "

Any resolution yet?

I am on;
VERSION 
v4.0.0-beta.323

**Comment by develdj** [comment]
Maybe the problem comes from the fact that request must be made via https, as for the minio instance, previously I was pointing to Supabase locally via http from a Cloudflare tunnel, then set https in Cloudflare zero auth and instantly all it works fine ... hope to be readable sorry for English

**Comment by VonderVuflya** [comment]
Perhaps the solution suggested by Theo in Tech will help you, namely
Use the latest minio image for v1

<img width="511" alt="image" src="https://github.com/user-attachments/assets/16e88748-9a62-44fd-8ca1-284551603cdb">


Links to actual images (04/10/2024)
minio/minio
[RELEASE.2024-10-02T17-50-41Z-cpuv1](https://hub.docker.com/layers/minio/minio/RELEASE.2024-10-02T17-50-41Z-cpuv1/images/sha256-ba435d3a45fb63d31f3b6101fa663827d5050c19bd99c5700fa8a7436a353628?context=explore)

minio/mc
[RELEASE.2024-10-02T08-27-28Z-cpuv1](https://hub.docker.com/layers/minio/mc/RELEASE.2024-10-02T08-27-28Z-cpuv1/images/sha256-d81460ca33c873f1371bb8c88542de0c42bc335ebf0a26a7482d2dcba1133789?context=explore)

That's the way it is
<img width="706" alt="image" src="https://github.com/user-attachments/assets/1cd74b2e-b462-4b3e-8e60-0a5be6670f19">

Here's a moment in the video detailing how to do it
https://youtu.be/NlBsJuUndws?si=rYtc9-q9iXCn0Xrx&t=1318

**Comment by RealmKnight** [comment]
> Maybe the problem comes from the fact that request must be made via https, as for the minio instance, previously I was pointing to Supabase locally via http from a Cloudflare tunnel, then set https in Cloudflare zero auth and instantly all it works fine ... hope to be readable sorry for English

This was the case in my situation, once I was both serving https in coolify and through the cloudflare tunnel everything worked as expected.

**Comment by gitgudchannel** [comment]
I have the same issue but I don't use cloudflare tunnels, any idea what I could change in the config to make minio createbucket work somehow? I use a subdomain for my supabase instance like `supabase.domain.com` and https is enabled already but I still get the issue described in the OP.

**Comment by theodufort** [comment]
> Perhaps the solution suggested by Theo in Tech will help you, namely Use the latest minio image for v1
> 
> <img alt="image" width="511" src="https://private-user-images.githubusercontent.com/17604053/373677872-16e88748-9a62-44fd-8ca1-284551603cdb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyNTg1NzYsIm5iZiI6MTcyODI1ODI3NiwicGF0aCI6Ii8xNzYwNDA1My8zNzM2Nzc4NzItMTZlODg3NDgtOWE2Mi00NGZkLThjYTEtMjg0NTUxNjAzY2RiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDIzNDQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0YTE1MjcyMzM5YTc2MmQ1YjVlOTUzZjllNmM5ZjRlM2I5Y2NlNWQ5ODE5MDBlNGZlNDE0MjE3YzM4Mjk2NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Hx2Np9yaaTWRYa-Mulevjj1wnL6xvJqstTJn_DCJlug">
> Links to actual images (04/10/2024) minio/minio [RELEASE.2024-10-02T17-50-41Z-cpuv1](https://hub.docker.com/layers/minio/minio/RELEASE.2024-10-02T17-50-41Z-cpuv1/images/sha256-ba435d3a45fb63d31f3b6101fa663827d5050c19bd99c5700fa8a7436a353628?context=explore)
> 
> minio/mc [RELEASE.2024-10-02T08-27-28Z-cpuv1](https://hub.docker.com/layers/minio/mc/RELEASE.2024-10-02T08-27-28Z-cpuv1/images/sha256-d81460ca33c873f1371bb8c88542de0c42bc335ebf0a26a7482d2dcba1133789?context=explore)
> 
> That's the way it is <img alt="image" width="706" src="https://private-user-images.githubusercontent.com/17604053/373678334-1cd74b2e-b462-4b3e-8e60-0a5be6670f19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyNTg1NzYsIm5iZiI6MTcyODI1ODI3NiwicGF0aCI6Ii8xNzYwNDA1My8zNzM2NzgzMzQtMWNkNzRiMmUtYjQ2Mi00YjNlLThlNjAtMGE1YmU2NjcwZjE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDIzNDQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1MmRlYjkxMjQ5YzI1NTRlODNkZDlhMGRiNzYwYjdlZjczZmVkNWZiNjAzYjY1YjM0NmEyYTU3MjA5M2RkY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rks7n_i0dctuMc7T3Y0FOXmhvB2BEX8MtdPEHaxSGkY">
> 
> Here's a moment in the video detailing how to do it https://youtu.be/NlBsJuUndws?si=rYtc9-q9iXCn0Xrx&t=1318

Theo responding here, thanks for the reference btw.
As soon as there is a fix, Ill create another video on that.

**Comment by develdj** [comment]
> I have the same issue but I don't use cloudflare tunnels, any idea what I could change in the config to make minio createbucket work somehow? I use a subdomain for my supabase instance like `supabase.domain.com` and https is enabled already but I still get the issue described in the OP.

do you use different reverse proxy? such as nginx or equivalent? maybe something must be checked also there (I mean http -> https)

**Comment by sampopide** [comment]
To resolve this issue, follow these steps:
Create a separate Minio instance using Coolify.
Log in to your Coolify instance and change the region name in the settings. For example, set it to "eu-south".
Create a bucket named "supabase" and obtain the secret key.
Create a Supabase instance from the template.
Edit the Docker file to remove all image names containing "minio".
Modify your storage settings to use the external Minio instance.
Update the entire storage section in the Docker Compose file to match the provided screenshot.
I've attached a sample configuration screenshot for reference. Please ensure you edit the complete storage section to match these settings
![supabase-setting](https://github.com/user-attachments/assets/ead805cf-270f-488b-86b5-43f509b944c7)

**Comment by josipledic** [comment]
@sampopide thank you I will try this. It worked with cloudflare tunnels for me but it's too complicated of a setup for my usecase so I disabled it again. And yes I also saw some people skip over the problem on youtube 😄

**Comment by peaklabs-dev** [comment]
The createbuckets `exit` status is normal as it is only needed once in the initial startup. Please try if this error still persists with the new refactored compose file here: https://github.com/coollabsio/coolify/blob/next/templates/compose/supabase.yaml.

**Comment by tannerhladek** [comment]
This may be out of scope, but is additional configuration required to view buckets in the Supabase dashboard? I’ve noticed some tutorials mention using the Minio dashboard to set policies and permissions, but it seems like that shouldn’t be necessary just to spin up a single bucket and allow other Supabase containers (like the storage container) to access it.

**Comment by RealmKnight** [comment]
> This may be out of scope, but is additional configuration required to view buckets in the Supabase dashboard? I’ve noticed some tutorials mention using the Minio dashboard to set policies and permissions, but it seems like that shouldn’t be necessary just to spin up a single bucket and allow other Supabase containers (like the storage container) to access it.

No this is all done at once now, you can create multiple buckets once it is up and running. The new docker compose fixed all issues for me
