### ISSUE TITLE
[Bug]: Failed to Recognize Reference

### ISSUE THREAD

**Issue by volfadar** [coollabsio/coolify#2362]
### Description

i use docker-compose way for deploying Mautic, the templates is come from this repo
https://github.com/mautic/docker-mautic/blob/6ebb1d6a2751fbb029d1e5ebb6c9ae076f55d47f/examples/basic/docker-compose.yml#L4

i think there's no problem with their config, but Coolify seems failed to recognize the reference of "*mautic-volumes" which is already highlighted in the link above (line 4)

![image](https://github.com/coollabsio/coolify/assets/44869940/f3da14fa-a716-408a-888e-ce7ebdc4e1be)

### Minimal Reproduction (if possible, example repository)

stated above

### Exception or Error

Reference "mautic-volumes" does not exist at line 6 (near "volumes: *mautic-volumes").

### Version

Latest - v4.0.0-beta.294

**Comment by andrasbacsai** [comment]
This is a tricky issue because I parse the compose file with a normal YAML parser, but that is invalid in the YAML world, but valid in the Docker world.

**Comment by volfadar** [comment]
> This is a tricky issue. Docker compose is not a standard yaml file, so to be able to parse it, I need some kind of special docker/yaml parser, which is not available anywhere.

thanks @andrasbacsai, so simply, just hard code that to every references instead making reference, right? 

![image](https://github.com/coollabsio/coolify/assets/44869940/0fb180c6-c7d3-45ef-a1e9-79fc65be7fc3)
one more question, should i uncheck this checkbox?

**Comment by andrasbacsai** [comment]
Well, you can delete the double `$` and left the checkbox active, or uncheck and leave the compose file like that.

**Comment by marcodack** [comment]
Hey there, thanks for sharing this resolution! I had the same problem with Coolify. Now this error is not displayed anymore but when deploying my mautic_web container is staying with the "waiting" mention. See below the logs message. 
![image](https://github.com/coollabsio/coolify/assets/118285935/a6639a22-c9b7-42de-846b-51eebded33ad)

**Comment by peaklabs-dev** [comment]
Mautic 5 is now available as a one-click service. As this is an edge case for volume mounts, we will not support it for the time being.
