### ISSUE TITLE
[Bug]: Docker not detected on localhost validation

### ISSUE THREAD

**Issue by Costigan-Stephen** [coollabsio/coolify#2363]
### Description

While attempting to _Validate Server & Install Docker Engine_ on a fresh install of coolify, I am met with the following error:

```
Server is reachable: ✔
Supported OS type: ✘
Server OS type is not supported. Please install Docker manually before continuing.
```

Typing `docker -v` informs me that I am running `Docker version 26.1.3, build b72abbb`, furthermore, Coolify itself is running on docker, so the error is confusing.

The current list of docker running containers is as follows:
```
CONTAINER ID   IMAGE                                       COMMAND                  CREATED        STATUS                  PORTS                                                                NAMES
b0dd6119d17f   ghcr.io/coollabsio/coolify:4.0.0-beta.294   "/init"                  28 hours ago   Up 28 hours (healthy)   443/tcp, 8000/tcp, 9000/tcp, 0.0.0.0:8000->80/tcp, :::8000->80/tcp   coolify
06532d2fcfa9   postgres:15-alpine                          "docker-entrypoint.s…"   28 hours ago   Up 28 hours (healthy)   5432/tcp                                                             coolify-db
31e35cec518a   quay.io/soketi/soketi:1.6-16-alpine         "node /app/bin/serve…"   28 hours ago   Up 28 hours (healthy)   0.0.0.0:6001->6001/tcp, :::6001->6001/tcp                            coolify-realtime
38be5327d47f   redis:alpine                                "docker-entrypoint.s…"   28 hours ago   Up 28 hours (healthy)   6379/tcp                                                             coolify-redis
```

If the issue is regarding my Operating System, I am currently running `Linux Almalinux 8 X86 64 Gen2 V1`, your documentation informs that AlmaLinux is supported (under Redhat), so I don't think that is it.

It should also be noted that the Validate & Configure output informs me that the _Server is reachable_. The localhost server settings are as follows:
```
Name               localhost
IP Address/Domain  host.docker.internal
User               root
Port               2222
```

System:
```
Operating System     Linux Almalinux 8 X86 64 Gen2 V1
Memory               6GB
CPU                  4
```

### Minimal Reproduction (if possible, example repository)

Attempting to validate the localhost server on freshly installed coolify

### Exception or Error

Supported OS type: ✘
Server OS type is not supported. Please install Docker manually before continuing.

### Version

v4.0.0-beta.294

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.

**Comment by Costigan-Stephen** [comment]
You are a scholar and a gentleman!
