### ISSUE TITLE
[Bug]: Gitlab merge request "merge" does not remove preview deployment.

### ISSUE THREAD

**Issue by sthyx** [coollabsio/coolify#2367]
### Description

If a merge request in Gitlab is CLOSED, the preview deployment will propertly be removed.
If a merge request in Gitlab is MERGED, the preview deployment is not removed.

The error message for the webhook is
`
[{"application":"xyz","status":"failed","message":"No action found. Contact us for debugging."}]
`
Seems that this error is because the webhook POST contains
`"action": "merge"` instead of `"action": "close"`

Action "merge" should be handled like action "close"

### Minimal Reproduction (if possible, example repository)

Open MR in Gitlab, see preview deployment in coolify
Merge MR in Gitlab instead of closing it, see preview deployment in coolify not going away

### Version

v4.0.0-beta.294

**Comment by andrasbacsai** [comment]
It will be fixed in the upcoming version!
