### ISSUE TITLE
Coolify Proxy blocks traffic from other internal VLANs on same network

### ISSUE THREAD

**Issue by SpuriousGer** [coollabsio/coolify#2369]
### Description

I'm encountering an issue with my Coolify instance. When I try to access it from a different VLAN on the same network, I cannot reach it. 

However, it's accessible from outside networks, such as my employer's network.I think the problem might be related to traefik. When I try to stop the proxy and then start it again, it does not restart.I'm almost certain the problem lies with Coolify, as I've checked other potential issues.

It usually works for a bit of time but then stops working. It's weird and I've had it happen twice. Restarting the proxy crashes the proxy and it no longer starts up.

P.S. willing to offer a bounty for this issue to be fixed. I desperately want coolify to work but this makes it impossible.

### Minimal Reproduction (if possible, example repository)

I have coolify installed. I'm running it on a server with IP addresses 10.10.10.101 and I'm trying to access it from 192.168.168.20
I have it open to the public on ports 80 and 443.
I'm running unifi equipment. 

To reproduce you would need a similar setup.

### Version

V4 Beta 294

**Comment by SpuriousGer** [comment]
We have not been able to reproduce for a third time. We keep trying, but at the moment, it works again (but had to set it up from scratch again).

**Comment by mlmetzner** [comment]
Did anybody resolve this?
