### ISSUE TITLE
[Bug]: Coolify automatic rollbacks on old deployments

### ISSUE THREAD

**Issue by gabinfinity** [coollabsio/coolify#2370]
### Description

Hey guys. I recently started using Coolify in my projects and it's really wonderful.

However, I am facing a VERY annoying problem.

For some unknown reason, Coolify is rolling back my website.
It is always rolling back to the same specific deployment.
Another very strange thing is that this occurs even without me making any new commits. It just decides to go back to an old deployment. 

I can only return to the current commit by restarting the container a few times. And after a few hours, even without making any new commits, it simply rolls back again on its own

### Minimal Reproduction (if possible, example repository)

You just need to have multiple projects and when you commit anything, all of them will rollback

### Version

v4.0.0-beta.294

**Comment by andrasbacsai** [comment]
Hey, this would be pretty hard to reproduce. Can you please [contact](https://coolify.io/docs/contact) me for further investigation?

**Comment by andrasbacsai** [comment]
I'm closing this issue now. If it still occurs, please let me know.
