### ISSUE TITLE
[Bug]: non-www redirection to www does not work with traefik

### ISSUE THREAD

**Issue by MalteBoehm** [coollabsio/coolify#2372]
### Description

Hey guys i copied the traefik configs for the redirection but it always ends up with delivering on both ways:

traefik.enable=true
traefik.http.middlewares.gzip.compress=true
traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
traefik.http.routers.http-0-swgw8cw.entryPoints=http
traefik.http.routers.http-0-swgw8cw.middlewares=redirect-to-https
traefik.http.routers.http-0-swgw8cw.rule=Host(`www.seeve.de`) && PathPrefix(`/`)
traefik.http.routers.http-0-swgw8cw.service=http-0-swgw8cw
traefik.http.routers.http-1-swgw8cw.entryPoints=http
traefik.http.routers.http-1-swgw8cw.middlewares=redirect-to-https
traefik.http.routers.http-1-swgw8cw.rule=Host(`seeve.de`) && PathPrefix(`/`)
traefik.http.routers.http-1-swgw8cw.service=http-1-swgw8cw
traefik.http.routers.https-0-swgw8cw.entryPoints=https
traefik.http.routers.https-0-swgw8cw.middlewares=gzip
traefik.http.routers.https-0-swgw8cw.rule=Host(`www.seeve.de`) && PathPrefix(`/`)
traefik.http.routers.https-0-swgw8cw.service=https-0-swgw8cw
traefik.http.routers.https-0-swgw8cw.tls.certresolver=letsencrypt
traefik.http.routers.https-0-swgw8cw.tls=true
traefik.http.routers.https-1-swgw8cw.entryPoints=https
traefik.http.routers.https-1-swgw8cw.middlewares=gzip
traefik.http.routers.https-1-swgw8cw.rule=Host(`seeve.de`) && PathPrefix(`/`)
traefik.http.routers.https-1-swgw8cw.service=https-1-swgw8cw
traefik.http.routers.https-1-swgw8cw.tls.certresolver=letsencrypt
traefik.http.routers.https-1-swgw8cw.tls=true
traefik.http.services.http-0-swgw8cw.loadbalancer.server.port=8080
traefik.http.services.http-1-swgw8cw.loadbalancer.server.port=8080
traefik.http.services.https-0-swgw8cw.loadbalancer.server.port=8080
traefik.http.services.https-1-swgw8cw.loadbalancer.server.port=8080
caddy_0.encode=zstd gzip
caddy_0.handle_path.0_reverse_proxy={{upstreams 8080}}
caddy_0.handle_path=/*
caddy_0.header=-Server
caddy_0.try_files={path} /index.html /index.php
caddy_0=https://www.seeve.de

caddy_1.redir=https://www.seeve.de{uri}
caddy_1=https://seeve.de

caddy_ingress_network=coolify

Has anyone a idea whats going wrong there?

### Minimal Reproduction (if possible, example repository)

Use the config above

### Version

4.0.0-beta.294

**Comment by hamedyosefian** [comment]
@andrasbacsai Adding this feature to the application would be very popular and beneficial. Some CDN and DNS servers do not handle this well, so including an option to address this issue would be very helpful.

**Comment by MalteBoehm** [comment]
I use hetzner as a dns and host. I wonder how anyone else solved it? Seems to be common :)

**Comment by LEstradioto** [comment]
I use these labels to redirect http to https and non-www to www, hope this helps

```
# change xxxxxx to your server hash as its automatically generated

traefik.enable=true
traefik.http.middlewares.gzip.compress=true
traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
traefik.http.middlewares.redirect-to-www.redirectregex.regex=^(http|https)://(?:www\.)?(.+)
traefik.http.middlewares.redirect-to-www.redirectregex.replacement=$${1}://www.$${2}
traefik.http.middlewares.redirect-to-www.redirectregex.permanent=true
traefik.http.routers.http-0-xxxxxx.entryPoints=http
traefik.http.routers.http-0-xxxxxx.middlewares=gzip,redirect-to-www
traefik.http.routers.http-0-xxxxxx.rule=Host(`domain.com`) && PathPrefix(`/`)
traefik.http.routers.http-0-xxxxxx.service=http-0-xxxxxx
traefik.http.routers.http-1-xxxxxx.entryPoints=http
traefik.http.routers.http-1-xxxxxx.middlewares=redirect-to-https,redirect-to-www
traefik.http.routers.http-1-xxxxxx.rule=Host(`domain.com`) && PathPrefix(`/`)
traefik.http.routers.http-1-xxxxxx.service=http-1-xxxxxx
traefik.http.routers.http-2-xxxxxx.entryPoints=http
traefik.http.routers.http-2-xxxxxx.middlewares=gzip,redirect-to-https
traefik.http.routers.http-2-xxxxxx.rule=Host(`www.domain.com`) && PathPrefix(`/`)
traefik.http.routers.http-2-xxxxxx.service=http-2-xxxxxx
traefik.http.routers.http-3-xxxxxx.entryPoints=http
traefik.http.routers.http-3-xxxxxx.middlewares=redirect-to-https
traefik.http.routers.http-3-xxxxxx.rule=Host(`www.domain.com`) && PathPrefix(`/`)
traefik.http.routers.http-3-xxxxxx.service=http-3-xxxxxx
traefik.http.routers.https-1-xxxxxx.entryPoints=https
traefik.http.routers.https-1-xxxxxx.middlewares=gzip,redirect-to-www
traefik.http.routers.https-1-xxxxxx.rule=Host(`domain.com`) && PathPrefix(`/`)
traefik.http.routers.https-1-xxxxxx.service=https-1-xxxxxx
traefik.http.routers.https-1-xxxxxx.tls.certresolver=letsencrypt
traefik.http.routers.https-1-xxxxxx.tls=true
traefik.http.routers.https-3-xxxxxx.entryPoints=https
traefik.http.routers.https-3-xxxxxx.middlewares=gzip
traefik.http.routers.https-3-xxxxxx.rule=Host(`www.domain.com`) && PathPrefix(`/`)
traefik.http.routers.https-3-xxxxxx.service=https-3-xxxxxx
traefik.http.routers.https-3-xxxxxx.tls.certresolver=letsencrypt
traefik.http.routers.https-3-xxxxxx.tls=true
traefik.http.services.http-0-xxxxxx.loadbalancer.server.port=80
traefik.http.services.http-1-xxxxxx.loadbalancer.server.port=80
traefik.http.services.http-2-xxxxxx.loadbalancer.server.port=80
traefik.http.services.http-3-xxxxxx.loadbalancer.server.port=80
traefik.http.services.https-1-xxxxxx.loadbalancer.server.port=80
traefik.http.services.https-3-xxxxxx.loadbalancer.server.port=80
```


Escape special characters in labels?, must be DISABLED

![image](https://github.com/coollabsio/coolify/assets/22579355/c1bc2de4-f5b1-48b1-95b6-c28b73d21f84)

**Comment by MalteBoehm** [comment]
Awesame, thank you so much!
