### ISSUE TITLE
[Bug]: ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by 0xtlt** [coollabsio/coolify#2373]
### Description

If "Force Https" is disabled, both http and https will works, if "Force Https" is enabled, both will return infinite redirection resulting with ERR_TOO_MANY_REDIRECTS error by browsers

### Minimal Reproduction (if possible, example repository)

I just setup 2 servers for my needs:
- 1 main
- 1 secondary

I deployed my project on the secondary server, pointed my domain A @ DNS with Cloudflare to my secondary server, setup the domain and getting the infinite redirections, but not if I disable "force HTTPS"

I'm using the cloudflare DNS settings "Proxied"

I made this minimal reproduction repository: https://github.com/0xtlt/Coolify-ERR_TOO_MANY_REDIRECTS

### Version

v4.0.0-beta.294

**Comment by andrasbacsai** [comment]
Can you please check if this helps with your issue: https://coolify.io/docs/knowledge-base/faq#too-many-redirections?

**Comment by 0xtlt** [comment]
Was that, thank you @andrasbacsai!
