### ISSUE TITLE
[Bug]: Install script automatically exits the installation

### ISSUE THREAD

**Issue by KuaterCraft** [coollabsio/coolify#2384]
### Description

I opened up my terminal, paste and entered the install script `curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash` 

![image](https://github.com/coollabsio/coolify/assets/97666546/07d16295-64f7-4e36-98c9-d5dc4f81318c)

It just stops automatically i have no idea why.

I first tried installing v4 its not working then installed v3 of coolify it worked perfectly fine! 

![image](https://github.com/coollabsio/coolify/assets/97666546/ed66c7c7-bdcc-4edf-8649-23f48cb44e08)

then i uninstalled it as per the docs then i tried installing v4 and its still not working

### Minimal Reproduction (if possible, example repository)

1. Copy the installation script 
2. Paste in terminal and hit enter

*it automatically stops the installation and exits*

### Version

v4.0.0-beta.294 Latest

**Comment by rortan134** [comment]
How did you solve this

**Comment by KuaterCraft** [comment]
it got fixed automatically after like 3 days ;-;
