### ISSUE TITLE
[Bug]: Horrible response times becuse of script loading

### ISSUE THREAD

**Issue by hvuhsg** [coollabsio/coolify#2396]
### Description

I have tried self-hosting and the admin panel was very very slow, I checked the overall server performance but it was not the issue.
debugging the issue with the devtools in firefox I found out that every page request loaded a script (jsQuilting/server/jsDict_utf8.js)
and the page was not rendered until the request for the script failed (NS_ERROR_NET_RESET) after blocking the request all the pages loaded much! faster from 20 second of page load to normal load times.

### Minimal Reproduction (if possible, example repository)

Sorry I don't know what to put here

### Exception or Error

NS_ERROR_NET_RESET

### Version

v4.0.0-beta.294

**Comment by Thijmen** [comment]
There's not much to go on from here; is there a HAR file you can share to debug this?

**Comment by peaklabs-dev** [comment]
I am unable to reproduce this issue, please upgrade to the latest version of Coolify v4 and try again, and if this is still an issue, feel free to reopen this issue or create a new one. It would also be helpful if you could provide more details about the script that is causing the issue as we do not have a script with that name and I also could not reproduce this slowness anywhere.
