### ISSUE TITLE
[Bug]: Overwriting id_rsa without updating id_rsa.pub

### ISSUE THREAD

**Issue by hareldev** [coollabsio/coolify#2398]
### Description

When using Private repository in remote server, Coolify will replace your remote `/root/.ssh/id_rsa` file with the one configured in the admin panel.
However, it will not update `/root/.ssh/id_rsa.pub`, which cause any private repo to not load.

### Minimal Reproduction (if possible, example repository)

* Create a new server, with it's own ssh keys (`/root/.ssh/id_rsa` and `/root/.ssh/id_rsa.pub`)
* Create a private repo, for example with the content of [coolify-examples](https://github.com/coollabsio/coolify-examples/tree/main).
* Add the new server to your Coolify installation
* Add new resource to this remote server, and select `Private Repository`
* The repository will not be available, and `/root/.ssh/id_rsa*` will show mismatching files:
```
root@my-remote-server01:/tmp# ll /root/.ssh/id_rsa*
-rw------- 1 root root 1701 Jun  8 18:52 /root/.ssh/id_rsa
-rw-r--r-- 1 root root  401 Jun  8 18:27 /root/.ssh/id_rsa.pub
```
Notice the time differences..
When trying to `git clone` any private repo, error is:
```
root@my-remote-server01:/tmp# git clone --depth 1 git@gitlab.com:my-name/private-repo.git
Cloning into 'private-repo'...
identity_sign: private key /root/.ssh/id_rsa contents do not match public
git@gitlab.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

### Version

v4.0.0-beta.294

**Comment by brunogrcsada** [comment]
In the meantime I would recommend setting up a [GitHub app source ](https://coolify.io/docs/knowledge-base/git/github/integration#with-github-app-recommended) and re-creating the project resource with the app attached as the source, which holds its own key pair.

I have been encountering a few issues though with deploy keys as well in v4.0.0-beta.297

**Comment by hareldev** [comment]
Thanks for the suggestion! I'm actually working with private GitLab repositories.

A solution that worked for me so far was:
* Deleting all private keys on coolify, keeping only one
* Creating the public key file `/root/.ssh/id_rsa.pub` manually

This way, coolify will not overwrite it, keeping the files mismatched.

**Comment by peaklabs-dev** [comment]
I am not sure I understand what you are trying to do. You add a new server to Coolify with its own SSH key (the one you previously saved or created in Coolify). Then you add another private key as a Gitlab deployment key to the SSH keys tab in Coolify. And then what doesn't work?
