### ISSUE TITLE
[Bug]: Google OAuth automatically registers new users even if registration is disabled

### ISSUE THREAD

**Issue by aritraroy** [coollabsio/coolify#2399]
### Description

I have enabled Google Oauth option to login using Google. I have also kept the "Registrations Allowed" settings as unticked so that no new users can register.

But when a new user logs in using the Google Oauth sign-in, a new user is automatically created which is not expected as the "Registrations Allowed" settings is turned off.

### Minimal Reproduction (if possible, example repository)

1. Enable Google OAuth in Settings page.
2. Un-tick "Registrations Allowed" in settings page.
3. Login via Google Auth using a new email address that is not not registered with Coolify.
4. You will see that a new user account gets created using this email address.

### Version

v4.0.0-beta.294

**Comment by Thijmen** [comment]
Also reported on Discord; https://discord.com/channels/459365938081431553/1249644145450942464/1249644145450942464

**Comment by addvanced** [comment]
As @Thijmen mentioned, I noticed this bug today as well, but for GitHub OAuth.
So it seems to be a general problem for OAuth Authorization that it doesn't really catch the "is registration allowed" bool in the code, and creates the user anyway.

**Comment by Thijmen** [comment]
I will try to look at it this afternoon - no promises though! If I can find the bug, I'll open a PR.

**Comment by addvanced** [comment]
I have proposed a fix for this problem here: #2590

**Comment by pksorensen** [comment]
I get a nginx forbidden when callback is hit, what are you guys using for callback url? 
![image](https://github.com/user-attachments/assets/4c825d2f-daab-41dd-9c6f-8f163fe76898)

**Comment by aritraroy** [comment]
I use this for callback URL - `https://coolify.mydomain.com/auth/google/callback`.
