### ISSUE TITLE
Docker installation fails

### ISSUE THREAD

**Issue by ilovefreesw** [coollabsio/coolify#24]
![image](https://user-images.githubusercontent.com/77317006/113674137-7b8e7200-96d7-11eb-9544-bf6426a75e98.png)

OS: Windowsfx (based on ubuntu 20.04.4 LTS)

Also cant install the script with sudo

![image](https://user-images.githubusercontent.com/77317006/113676205-cad5a200-96d9-11eb-8119-1a6605d0cc1b.png)

**Comment by andrasbacsai** [comment]
Hey, I never heard of Windowsfx. It looks like the Docker package repository does not have a package for this operating system. Not sure what can I do about it atm. 

If you could help me to figure out what packages needed for Docker to run on Windowsfx, I will update the installation script.

**Comment by ilovefreesw** [comment]
I just followed [this thread](this thread) and instructions on [Docker website](https://docs.docker.com/engine/install/ubuntu/) to install it manually.

**Comment by andrasbacsai** [comment]
Ah, I see, so it's not 20.04, right? 

I plan to add more operating systems, but it's not the most important thing atm.
