### ISSUE TITLE
[Bug]: Self hosted TLDR installation doesn't start containers 

### ISSUE THREAD

**Issue by Dogacel** [coollabsio/coolify#2417]
### Description

It seems like the `install.sh` script doesn't start the containers. Even though my setup said visit `<external_ip>:8000` to get started, I couldn't. So I dig deep and found out there is actually no step that spins up the docker-compose containers such as,

```
docker compose --env-file /data/coolify/source/.env -f /data/coolify/source/docker-compose.yml -f /data/coolify/source/docker-compose.prod.yml up -d --pull always --remove-orphans --force-recreate
```

inside the `install.sh` file.

### Minimal Reproduction (if possible, example repository)

Just follow the TLDR steps from a clean machine.

```
curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash 
```

### Version

N/A

**Comment by Dogacel** [comment]
Second look, I believe my device did not have enough memory (8 GB). The SSH became unresponsive and device shut down after initial setup and or during compose command.

For reference I use raspberry pi 5.

**Comment by Dogacel** [comment]
> I literally ran the command yesterday (after you opened the ticket) and it did work. Which OS are you running?

I am using Raspbian. The behavior I am seeing is inconsistent. During my first time setup my device crashed. Then I consecutively run the same setup script after restarting and it said "running" but there was no docker container. After trying to run the docker compose command manually, my device froze and crashed again.

One possibility is maybe the disk size is not enough in my Raspberry Pi. What is the base disk usage for first time installation?

**Comment by addonion** [comment]
I have the same issue with Ubuntu

**Comment by peaklabs-dev** [comment]
@addonion and @Dogacel Is this still happening? For me everything is working fine with the script. Could you if possible provide more detailed reproduction steps? Thank you.
