### ISSUE TITLE
[Bug]: letsencrypt certificate fails to renew (maybe rate limiting?)

### ISSUE THREAD

**Issue by Blochergroup** [coollabsio/coolify#2420]
### Description

I have a few svelte apps running and just one of the domains is able to obtain a ssl certificate (the first one I used) all the others fail to get a certificate

### Minimal Reproduction (if possible, example repository)

-

### Exception or Error

 unable to generate a certificate for the domains [zxgcx0w.78.47.xxx.xxx.sslip.io]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited 

024-06-09T16:07:38.062067361Z time="2024-06-09T16:07:38Z" level=error msg="Error renewing certificate from LE: {n8gsc0c.78.47.106.223.sslip.io []}" providerName=letsencrypt.acme ACME CA="https://acme-v02.api.letsencrypt.org/directory" error="error: one or more domains had a problem:\n[n8gsc0c.78.47.xxx.xxx.sslip.io] acme: error: 400 :: urn:ietf:params:acme:error:connection :: 78.47.xxx.xxx: Fetching http://nxxscx.78.47.xxx.xxx.sslip.io/.well-known/acme-challenge/Qya_aAt4SxxxxskoLo4fHMW_x379HIMRxX8kzEPo: Connection refused\n"

### Version

v4.0.0-beta.294

**Comment by peaklabs-dev** [comment]
This can be a problem with the `sslip.io` domain (they have a lets encrypt rate limit of 3000 in comparison to 50 a week of a personal domain but this could still be too low in some cases), please use your own domain to avoid being rate limited.
