### ISSUE TITLE
[Bug]: Coolify allows access through IP_ADDRESS:PORT, even though port is closed 

### ISSUE THREAD

**Issue by zanzlender** [coollabsio/coolify#2427]
### Description

I have been playing with Coolify and came across this issue, which I can't figure out.

I opened ports 22, 6001, 8000 as per the docs.

I installed Coolify and managed to get acces with MY_IP_ADDR:8000.

I configured access through **coolify.myapp.xyz**, which worked.

After that I wanted to only allow access through coolify.myapp.xyz, so I disabled the port with `ufw deny 8000`. However, even after rebooting both my server and coolify, I can still access the dashboard through MY_IP_ADDR:8000.

Now, I'm not sure if this is a Coolify issue, or my lack of knowledge with Docker, but it's weird nonetheless.

### Minimal Reproduction (if possible, example repository)

Ubuntu 22.04 VPS on HiVelocity.

Open ports with: `ufw allow 6001`, `ufw allow 8000`, `ufw allow 22`

Run Coolify script, configure domain.

Close port 8000 for direct access with `ufw`

### Version

v4.0.0-beta.294

**Comment by myselfolli** [comment]
The docker port bindings ignore ufw, so if you deny port 8000 using ufw, but docker exposes it, it will still be reachable.

**Comment by CodeArtificial** [comment]
I tried to fixed the problem chaifeng/ufw-docker, but ufw closes both IP_ADDRESS:PORT and coolify.mydomain.xyz. Could anyone share how to fix the problem?

**Comment by zanzlender** [comment]
> I tried to fixed the problem with chaifeng/ufw-docker, but ufw closes both IP_ADDRESS:PORT and coolify.mydomain.xyz. Could anyone share how to fix the problem?

Try to open all ports you neee before you start installing it

**Comment by zanzlender** [comment]
> The docker port bindings ignore ufw, so if you deny port 8000 using ufw, but docker exposes it, it will still be reachable.

Bless you 🙌

**Comment by jimhuds** [comment]
> I tried to fixed the problem with chaifeng/ufw-docker, but ufw closes both IP_ADDRESS:PORT and coolify.mydomain.xyz. Could anyone share how to fix the problem?

Did you do ufw-docker allow coolify-proxy?

**Comment by CodeArtificial** [comment]
Thank you, jimhuds! `ufw-docker allow coolify-proxy` solved the problem!

**Comment by maisen20** [comment]
Are you sure that port 8000 is then really not accessible from outside? after a system reboot, coolify seems to reopen port 8000 again for me.
It works for me with port 443, but port 8000 is always open. ufw and the settings according to https://github.com/chaifeng/ufw-docker have no effect on port 8000.

**Comment by n-mcnally** [comment]
> Did you do ufw-docker allow coolify-proxy?

Thank you! Had to reboot after installation and run this command again before it worked but no issues since.

**Comment by SamiNassim** [comment]
> > I tried to fixed the problem with chaifeng/ufw-docker, but ufw closes both IP_ADDRESS:PORT and coolify.mydomain.xyz. Could anyone share how to fix the problem?
> 
> Did you do ufw-docker allow coolify-proxy?

I have to run this command each reboot or I can't access my domain.
Is that the intended behavior ?

**Comment by gulivan** [comment]
> > > I tried to fixed the problem with chaifeng/ufw-docker, but ufw closes both IP_ADDRESS:PORT and coolify.mydomain.xyz. Could anyone share how to fix the problem?
> > 
> > 
> > Did you do ufw-docker allow coolify-proxy?
> 
> I have to run this command each reboot or I can't access my domain. Is that the intended behavior ?

you may add this line to your crontab:

`@reboot sleep 15 &&  /usr/local/bin/ufw-docker allow coolify-proxy`

This solved the issue for me

**Comment by bitsByB** [comment]
> The docker port bindings ignore ufw, so if you deny port 8000 using ufw, but docker exposes it, it will still be reachable.

Has anyone found a solution other than a cron job?
https://www.baeldung.com/linux/docker-container-published-port-ignoring-ufw-rules
