### ISSUE TITLE
[Bug]: Invalid Supabase link

### ISSUE THREAD

**Issue by davisuga** [coollabsio/coolify#2431]
### Description

I'm trying to deploy supabase but the link given (http://supabasekong-blablabla.ipaddress.sslip.io/) returns ERR_EMPTY_RESPONSE.

Environment info:
```
                          ./+o+-       ubuntu@instance-20230722-1315
                  yyyyy- -yyyyyy+      OS: Ubuntu 22.04 jammy
               ://+//////-yyyyyyo      Kernel: aarch64 Linux 6.5.0-1023-oracle
           .++ .:/++++++/-.+sss/`      Uptime: 17h 47m
         .:++o:  /++++++++/:--:/-      Packages: 819
        o:+o+:++.`..```.-/oo+++++/     Shell: bash 5.1.16
       .:+o:+o/.          `+sssoo+/    Disk: 32G / 46G (71%)
  .++/+:+oo+o:`             /sssooo.   CPU: 4x ARM Neoverse-N1
 /+++//+:`oo+o               /::--:.   GPU:
 \+/+o+++`o++o               ++////.   RAM: 2578MiB / 23981MiB
  .++.o+++oo+:`             /dddhhh.
       .+.o+oo:.          `oddhhhh+
        \+.++o+o``-````.:ohdhhhhh+
         `:o+++ `ohhhhhhhhyo++os:
           .o:`.syhhhhhhh/.oo++o`
               /osyyyyyyo++ooo+++/
                   ````` +oo+++o\:
                          `oo++.
```

### Minimal Reproduction (if possible, example repository)

1) Install Coolify
2) Add a resource
3) Select superbase
4) Deploy
5) Click on the link given in the Links button

### Version

v4.0.0-beta.294

**Comment by peaklabs-dev** [comment]
We have updated and refactored the Supabase template quite a bit for the next update, this should now work with this new compose file https://github.com/coollabsio/coolify/blob/next/templates/compose/supabase.yaml please let me know if this is still an issue.
