### ISSUE TITLE
[Bug]: Executed Tasks are not shown in descending order of execution

### ISSUE THREAD

**Issue by luisrudge** [coollabsio/coolify#2432]
### Description

I don't think it's ordered at all, so it just comes based on the id or index or I don't know 😅

### Minimal Reproduction (if possible, example repository)

- Setup execution tasks
- let a few of them run

### Exception or Error

tasks are not ordered by date of execution

<img width="1188" alt="image" src="https://github.com/coollabsio/coolify/assets/941075/1fb75746-843e-44ce-9b83-11f829e261ca">

### Version

v4.0.0-beta.296

**Comment by peaklabs-dev** [comment]
This issue should be resolved in the latest version. If you're still experiencing this issue, please reopen or create a new issue with updated details.
