### ISSUE TITLE
[Bug]: COOLIFY_FQDN and COOLIFY_URL mixed up

### ISSUE THREAD

**Issue by scflode** [coollabsio/coolify#2443]
### Description

It looks like that these two predefined variables are meant to be the other way around:

```
SOURCE_COMMIT=f4da7f19ea6bc9d014fe57763fa9c55a270e750e
COOLIFY_FQDN=http://ag7r8oo.127.0.0.1.sslip.io
COOLIFY_URL=ag7r8oo.127.0.0.1.sslip.io
COOLIFY_BRANCH=main
```

The FQDN I expect to not have the transport protocol prepended.

### Minimal Reproduction (if possible, example repository)

This happens with any custom deployments as far as I can tell.

### Version

v4.0.0-beta.294

**Comment by ayntk-ai** [comment]
Steps to fix:
- [ ] Switch FQDM to be actually just the domain like so: domain.com
- [ ]  Switch URL to be the URL with the protocol like so: https://domain.com/
-> Currently it is the other way around, which is quite confusing.
A list of things that need to be fixed:
- [ ]  Auto-generated magic: https://coolify.io/docs/knowledge-base/add-a-service -> Switch URL and FQDN
- [ ]  Compose files for service need to be adjusted (autogenrate logic)
- [ ] UI setting of the Domain needs to change form env variabel FQDN to URL
- [ ]  Predefined environment variables -> https://coolify.io/docs/knowledge-base/environment-variables#coolify-fqdn -> Here also FQDN needs to be switch with URLs --> URLs gives back all URLs with HTTPs or HTTP with the protocol and the FQDN only the domain with the TLD (eg. .com, .net, .io...)

**Comment by andrasbacsai** [comment]
I do not want to make switch them up (to not cause breaking changes), so I will introduce 2 new envs: `COOLIFY_DOMAIN_URL` and `COOLIFY_DOMAIN_FQDN`.

![image](https://github.com/user-attachments/assets/f0a96a50-1c22-4100-821a-a4b3aa740ea1)
