### ISSUE TITLE
[Bug]: Docker Compose file not found when it's located in a subdirectory

### ISSUE THREAD

**Issue by Pima-Dev** [coollabsio/coolify#2444]
### Description

Docker Compose file could not be found when a Base Directory is specified

### Not working example (because of the base directory)
https://github.com/coollabsio/coolify-examples/tree/main
Base Directory : /docker-compose-test
Docker Compose Location : /docker-compose.yaml

### Working example (no base directory)
https://github.com/hagopj13/node-express-boilerplate/blob/master
Base Directory : /
Docker Compose Location : /docker-compose.yml

### Exception or Error

Docker Compose file not found at: /docker-compose-test/docker-compose.yaml
Check if you used the right extension (.yaml or .yml) in the compose file name.

### Version

v4.0.0-beta.294

**Comment by incon** [comment]
Having the same issue

**Comment by Pima-Dev** [comment]
I was using Git v2.25.1. I upgraded to v2.45.2, and it solved the problem. I think the new Git version fixed the git sparse-checkout/git read-tree issue because, in the old version, the Docker Compose file was never cloned correctly in the subdirectory.
