### ISSUE TITLE
[Bug]: Install Script Proceeds To Install v4.0.0-beta.294

### ISSUE THREAD

**Issue by muhammedaksam** [coollabsio/coolify#2459]
### Description

I just run `curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash ` and it started to install 294.

https://cdn.coollabs.io/coolify/versions.json
```json
{
    "coolify": {
        "v4": {
            "version": "4.0.0-beta.294"
        },
        "sentinel": {
            "version": "0.0.4"
        }
    }
}
```

```
Welcome to Coolify v4 beta installer!
This script will install everything for you.
(Source code: https://github.com/coollabsio/coolify/blob/main/scripts/install.sh )

-------------
OS: ubuntu 22.04
Coolify version: 4.0.0-beta.294
-------------
Installing required packages...
``` 

### Minimal Reproduction (if possible, example repository)

 `curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash `

### Version

4.0.0-beta.294

**Comment by enesbala5** [comment]
Workaround - Update script to install beta 297:

curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash -s 4.0.0-beta.297

**Comment by JorenRothman** [comment]
Found the bug, the following file needs updating,
https://cdn.coollabs.io/coolify/versions.json

In the repo the file is updated correctly

**Comment by andrasbacsai** [comment]
https://github.com/coollabsio/coolify/issues/2475#issuecomment-2162625725

**Comment by mbeaudru** [comment]
@andrasbacsai I just did the command and it didn't worked, installed again the v294

**Comment by peaklabs-dev** [comment]
@mbeaudru I added a readme to clarify this: https://github.com/coollabsio/coolify/blob/main/RELEASE.md
