### ISSUE TITLE
Ruby / Rails support

### ISSUE THREAD

**Issue by cmer** [coollabsio/coolify#246]
Including support for other processes such as Sidekiq

**Comment by MarcosNBJ** [comment]
Working on it! 😁

**Comment by themarkwill** [comment]
You can vote in this feature on https://feedback.coolify.io/posts/73/buildpack-ruby-rails

**Comment by natsumi** [comment]
any update on this? would be awesome to support Rails

**Comment by andrasbacsai** [comment]
It is supported in v4.


I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
