### ISSUE TITLE
[Bug]: Impossible to deploy certain repos ending with domain names (ex. github.io)

### ISSUE THREAD

**Issue by bforbiggy** [coollabsio/coolify#2462]
### Description

It is impossible to deploy a repository from a url that contains a domain at the end. This is because coolify automatically "cleans" urls, converting https://github.com/bforbiggy/bforbiggy.github.io into https://github.com/bforbiggy/bforbiggy. 

### Minimal Reproduction (if possible, example repository)

Step 1: Deploy a git repository ending in a domain (https://github.com/bforbiggy/bforbiggy.github.io)
Step 2: Watch as coolify forcibly changes the repository url

### Version

v4.0.0-beta.294

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.
