### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by mbeaudru** [coollabsio/coolify#2485]
### Description

PR preview deployments don't get cleaned / removed when the pull requests are merged / closed

I got a memory usage alert and noticed that 8 nextJS apps were still running, investigating I observed that most of them are related to preview environments that weren't deleted by coolify after my PRs have been merged / closed

### Minimal Reproduction (if possible, example repository)

Open multiple PRs with a deployed NextJS repo app with preview environments enabled, close the PR and check if preview  instances remain running on docker (docker ps or check logs in coolify)

### Version

v4.0.0-beta.294

**Comment by andrasbacsai** [comment]
Can you please retry with v297? There was a fix related to this.

If it still does not work, please reopen the issue.

**Comment by Djemai-Samy** [comment]
I'm currently using: v4.0.0-beta.306, and I'm having the same issue.
