### ISSUE TITLE
[Improvement]: Refactor Log Page

### ISSUE THREAD

**Issue by peaklabs-dev** [coollabsio/coolify#2503]
### Description

The log page is amazing, but I think it could benefit from some tweaks.

### Minimal Reproduction (if possible, example repository)

Things I think would really help the logs page:

- [ ] add a search bar so we can search the logs
- [x] Add a wrap lines checkbox so that log lines are automatically wrapped.
- [x] A download button to download the whole log file.

### Version

-

**Comment by ayntk-ai** [comment]
Fixes one of the tasks: https://github.com/coollabsio/coolify/pull/2598
