### ISSUE TITLE
[Bug]: It is not possible to add more environment variables or volumes to a service in the UI

### ISSUE THREAD

**Issue by peaklabs-dev** [coollabsio/coolify#2504]
### Description

When I install a WordPress service and want to add more environment variables then the add environment variables button is missing (yes developer view is available) but there is no way to add more variables in the UI as it is normally available.
There is also no button to add more volumes for a WordPress installation.

### Minimal Reproduction (if possible, example repository)

1. Install WordPress service check the tabs:
- Add environment variables is missing here:
![image](https://github.com/coollabsio/coolify/assets/122374094/834eea7d-bf16-4fe9-9f03-f6ca000fbcd0)
- Add volume button is missing:
![image](https://github.com/coollabsio/coolify/assets/122374094/41c0bd5d-fe08-4334-8751-b108c6315e37)

--> this happens on a lot of services also ghost and so on (but when using a custom compose file it does not happen)

### Version

v4.0.0-beta.294

**Comment by ayntk-ai** [comment]
Will the same be possible for volumes, so I can set variables and then set volumes in the UI, or will volumes only work in the docker compose file?

**Comment by andrasbacsai** [comment]
for services, it will only work on the compose file at the moment.

**Comment by ayntk-ai** [comment]
Great. If it is possible through the UI, I would love to see it in the future.

**Comment by ayntk-ai** [comment]
@andrasbacsai I think for volumes the UI option is not available but for env variables this is added. If for volumes the UI couls be used aswell in servicea I woul love to see that. Is that also possible?
