### ISSUE TITLE
[Bug]: Top level deployment state does not match the one reported in details

### ISSUE THREAD

**Issue by kwmlodozeniec** [coollabsio/coolify#2507]
### Description

When you look at a running deployment the top level status seems to always be `Exited` even when the deployment is still running.
![bug](https://github.com/coollabsio/coolify/assets/1453791/0fcc87b7-4772-43b6-8799-b91b5508e03a)

### Minimal Reproduction (if possible, example repository)

Launch a build and visit the deployment page.

### Exception or Error

The status should match

### Version

v4.0.0-beta.294

**Comment by peaklabs-dev** [comment]
The reason for this is that it is not the deployment state, it is the overall application state/container state that is exited/not running at the time of the first deployment. So I think this is working the right way. Let me know if you think this should work another way?

**Comment by kwmlodozeniec** [comment]
Right, I did't not take it that way but it makes sense, thanks for clarifying.
