### ISSUE TITLE
[Bug]: Supabase servide doesn't allow to change kong port or run in localhost

### ISSUE THREAD

**Issue by DiegoBM** [coollabsio/coolify#2515]
### Description

While trying to test coolify with Supabase, installing on the same localhost (I know it's not recommended but it should be doable), if yu try to edit the Kong port 8000, Coolify won't allow you to do it, the host changes all right after saving, but the port will always be reverted to port 8000 which conflics with Coolify.

This works fine with the Appwrite service for example

### Minimal Reproduction (if possible, example repository)

* Setup a brand new server (in my case ubuntu server 24.04 LTS)
* Install docker
* Get Coolify up and running following the instructions in the website
* Setup coolify to install in localhost (no other settings)
* Create a new project
* Add a new resource, of type Supabase Service
* Change KONG port to 9000

If I manually edit the compose file to get the KONG_HTTP_PORT and configure the environment variables manually to set the KONG_HTTP_PORT=9000and some other settings like the external urls, then I can manage to make it work in localhost

### Exception or Error

No error, port gets reverted back to 8000 after saving

### Version

v4.0.0-beta.294

**Comment by ray-bun** [comment]
Where do you add the KONG_HTTP_PORT? I'm getting
`
Kong Error
Invalid authentication credentials.`

**Comment by DiegoBM** [comment]
If you click "Edit  Compose File", I add it for the supabase-kong service, adding a "ports section":
```yaml
services:
  supabase-kong:
    image: 'kong:2.8.1'
      .....
    ports:
      - '${KONG_HTTP_PORT}:8000/tcp'
    environment:
      .....
```
