### ISSUE TITLE
[Bug]:  Not getting latest version upgrades

### ISSUE THREAD

**Issue by marke-dev** [coollabsio/coolify#2516]
### Description

Currently stuck on v4.0.0-beta.294. 

Seeing 297 is released

### Minimal Reproduction (if possible, example repository)

stuck on 294 from tag in nav.  

My setting has auto updates switched.

Switched on and off and back on and saved but still nothing.

Tried manual upgrade from docs : curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash

Nothing changed

### Version

v4.0.0-beta.294.

**Comment by marcoleong** [comment]
It seems the json file in the CDN is not updating. https://cdn.coollabs.io/coolify/versions.json

**Comment by JorenRothman** [comment]
For now, you can use the following command to update to the current latest version

` curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash -s 4.0.0-beta.297`

**Comment by andrasbacsai** [comment]
> For now, you can use the following command to update to the current latest version
> 
> ` curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash -s 4.0.0-beta.297`

Never use this, if you 100% sure.

It was not updated on purpose (it is updated now).
