### ISSUE TITLE
[Bug]: SOURCE_COMMIT env var doesn't work after deployment

### ISSUE THREAD

**Issue by ton77v** [coollabsio/coolify#2517]
### Description

It seems this got broken in one of the most recent releases:
SOURCE_COMMIT is now empty once the deployment is ready

Although according to the deployment logs, it's available during the process

### Minimal Reproduction (if possible, example repository)

1. Add repo-based resource (Nixpacks)
2. Deploy 
3. Go to the "Command"
4. `echo $SOURCE_COMMIT`
5. Output will be empty

### Version

v4.0.0-beta.297

**Comment by peaklabs-dev** [comment]
This issue has been fixed in the latest version.
