### ISSUE TITLE
[Bug]: Database loses public visibility after restart

### ISSUE THREAD

**Issue by klawdyo** [coollabsio/coolify#2527]
### Description

Hello everybody.
I have noticed that whenever I restart a database, it loses public visibility.

### Minimal Reproduction (if possible, example repository)

1) From a postgres or mysql database with public visibility enabled.
2) Restart it.
3) Sometimes the public visibility button still shows as activated, but you cannot access the bank from your machine. Sometimes I need to uncheck the "make public" option and then recheck it to get access back. Sometimes I leave the page thinking everything is ok, and when I come back, it is unchecked. In both cases, public access is disabled regardless of what the checkbox shows.

### Version

v4.0.0-beta.294

**Comment by andrasbacsai** [comment]
Making the database private by default is a good thing from a security perspective.

In the next version, I will fix the UI so that it shows the exact status of the proxy. If you stop it, it will notify you that it is disabled and also uncheck the checkbox.
