### ISSUE TITLE
[Improvement]: Show commit message in webhook deployments

### ISSUE THREAD

**Issue by klawdyo** [coollabsio/coolify#2528]
### Description

The commit message only appears in manual deployments. Deploy messages received via webbook are not appearing in the list.
![image](https://github.com/coollabsio/coolify/assets/100168/c16a6da9-6579-41ab-b6a0-e50c173491bd)

### Minimal Reproduction (if possible, example repository)

Open deployments tab on any service.

### Version

v4.0.0-beta.294

**Comment by andrasbacsai** [comment]
Ah, nice catch. It was just not visible in the UI. In the next version it will be.
