### ISSUE TITLE
[Bug]: too many notification for `Instance updated from 4.0.0-beta.294 -> 4.0.0-beta.297` while already on the latest version

### ISSUE THREAD

**Issue by ksaitor** [coollabsio/coolify#2530]
### Description

an already updated server keeps sending notifications to Discord:

`Instance updated from 4.0.0-beta.294 -> 4.0.0-beta.297`

<img width="459" alt="Screenshot 2024-06-13 at 21 53 36" src="https://github.com/coollabsio/coolify/assets/936436/bcbde19c-f258-42a6-a40e-fc1993fee96c">

### Minimal Reproduction (if possible, example repository)

n/a

### Version

v4.0.0-beta.294

**Comment by Thijmen** [comment]
This should be fixed in the next release (https://github.com/coollabsio/coolify/pull/2469 IIRC).

**Comment by andrasbacsai** [comment]
Yes, from 297+ you won't face this issue 🤞
