### ISSUE TITLE
[Bug]: Control socket host.docker.internal_22_root: Permission denied

### ISSUE THREAD

**Issue by JorrinKievit** [coollabsio/coolify#2532]
### Description

I have not used my coolify instance for a month or so, and when I logged in today I encountered the following error:
![image](https://github.com/coollabsio/coolify/assets/43169049/bbda46ff-bac0-4303-b391-f642f38cb49b)

I have a feeling this is an issue within my VPS, but I would have no idea how to fix it. Feel free to close it if it is unrelated 😄 

### Minimal Reproduction (if possible, example repository)

I am not able to reproduce the error, a clean install works fine.

### Exception or Error

```
Control socket connect(/var/www/html/storage/app/ssh/mux/host.docker.internal_22_root): Permission denied
unix_listener: cannot bind to path /var/www/html/storage/app/ssh/mux/host.docker.internal_22_root.4F3t6ORDpJDrekQe: Permission denied
```

### Version

v4.0.0-beta.297

**Comment by andrasbacsai** [comment]
Can you please check if there is enough space (`df -m`) on your server and also show me the output of the following command: `find /data/coolify/ssh -type d -ls`

**Comment by JorrinKievit** [comment]
Also had some issues out of the blue with SSL certificates no longer being generated. Ended up being a permission error on the acme.json file. Giving that file the right file permissions again (chmod 600) also fixed this issue. Thanks for the response anyway 😄
