### ISSUE TITLE
Treafik support

### ISSUE THREAD

**Issue by welcoMattic** [coollabsio/coolify#254]
I'd like to run Coolify behind traefik, but as I can see you only support HAProxy for now?

**Comment by andrasbacsai** [comment]
For now, yes, but making available for Traefik is not a huge effort, so it will be added later on. Not sure when.

**Comment by TheNoim** [comment]
The repo references traefik multiple times now. What is the current state?

**Comment by andrasbacsai** [comment]
Traefik is supported. 
You can even integrate Coolify with your own Traefik as well. Check this blog post: https://beaussan.io/blog/coolify-into-existing-traefik

**Comment by gregfr** [comment]
Nice blog post, but I cannot find anything about HOW it's done? especially regarding installing Coolify without its own Traefik instance...
