### ISSUE TITLE
[Bug]: Destinations, preview deployments, images are not deleted once a stack/ container is deleted

### ISSUE THREAD

**Issue by peaklabs-dev** [coollabsio/coolify#2546]
Reproduction:

1. Create a Service container (that gets a network automatically).
2. Delete Container

Things that are not properly deleted:

- [x] Destinations/ Networks -> still exist after deletion
- [x] preview deployments -> still exist after container deletion
- [x] images -> after service/ container is deleted all associated images should be deleted as they are now unused (is done periodically via cleanup but that is not the best solution)

v4.0.0-beta.320

**Comment by ayntk-ai** [comment]
Same for preview deployments:
They are deleted from the Coolify dashboard, but the containers are still running on the server.
