### ISSUE TITLE
[Bug]: version `GLIBC_2.38' not found (required by /nix/store/...)

### ISSUE THREAD

**Issue by ngosky** [coollabsio/coolify#2550]
### Description

I'm running a Next.js application in Coolify using the Nixpacks Build Pack. For some reason, many packages are unable to run inside the container, all erroring out with something along the lines of ``version `GLIBC_2.38' not found (required by /nix/store/...)``.

The errors arise when I try to execute custom commands either from the Command tab (when deplyment has succeeded) or from a nixpacks.toml configuration file (during the deployment).

### Minimal Reproduction (if possible, example repository)

- Run a Coolify instance on a `Linux 5.15.0-112-generic aarch64` server with `Ubuntu 22.04.4 LTS`.
- Create an application resource for a Next.js project and set the Build Pack to Nixpacks.

### Exception or Error

Some examples:
```
wget: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /nix/store/kyzz16xc27lr7l0qgdpqmgvm9bm4pjvr-util-linux-minimal-2.40.1-lib/lib/libuuid.so.1)
```
```
apt: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /nix/store/66qm2gvcb3img7faxli0jv10dahg61qa-gcc-13.2.0-lib/lib/libstdc++.so.6)
apt: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.36' not found (required by /nix/store/66qm2gvcb3img7faxli0jv10dahg61qa-gcc-13.2.0-lib/lib/libstdc++.so.6)
```

For context:
- Nixpacks chooses to run the container with the following build image: `'ghcr.io/railwayapp/nixpacks:ubuntu-1716249803'`

### Version

v4.0.0-beta.294

**Comment by ngosky** [comment]
Tried switching to debian through `NIXPACKS_DEBIAN=1`, but the error persists:
```
/usr/bin/firefox-nightly: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /nix/store/66qm2gvcb3img7faxli0jv10dahg61qa-gcc-13.2.0-lib/lib/libstdc++.so.6)
/usr/bin/firefox-nightly: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /nix/store/66qm2gvcb3img7faxli0jv10dahg61qa-gcc-13.2.0-lib/lib/libstdc++.so.6)
/usr/bin/firefox-nightly: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /nix/store/66qm2gvcb3img7faxli0jv10dahg61qa-gcc-13.2.0-lib/lib/libstdc++.so.6)
/usr/bin/firefox-nightly: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.36' not found (required by /nix/store/66qm2gvcb3img7faxli0jv10dahg61qa-gcc-13.2.0-lib/lib/libstdc++.so.6)
/usr/bin/firefox-nightly: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /nix/store/66qm2gvcb3img7faxli0jv10dahg61qa-gcc-13.2.0-lib/lib/libstdc++.so.6)
/usr/bin/firefox-nightly: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.35' not found (required by /nix/store/66qm2gvcb3img7faxli0jv10dahg61qa-gcc-13.2.0-lib/lib/libgcc_s.so.1)
/usr/bin/firefox-nightly: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /nix/store/66qm2gvcb3img7faxli0jv10dahg61qa-gcc-13.2.0-lib/lib/libgcc_s.so.1)
```

**Comment by ngosky** [comment]
Ended up configuring my own Dockerfile and switching my Build Pack from Nixpacks to Dockerfile in order to have more fine-grained control over what was happening. As far as I can tell, the Nixpacks build image seems to have been out of sync with some package or dependency, which caused a GLIBC mismatch. Closing, as this bug doesn't seem to pertain to Coolify.

**Comment by m1daz** [comment]
> Ended up configuring my own Dockerfile and switching my Build Pack from Nixpacks to Dockerfile in order to have more fine-grained control over what was happening. As far as I can tell, the Nixpacks build image seems to have been out of sync with some package or dependency, which caused a GLIBC mismatch. Closing, as this bug doesn't seem to pertain to Coolify.

Could you please comment on this dockerfile? I do need this for my own project at the moment to run puppeteer.

**Comment by ngosky** [comment]
Here is the Dockerfile I ended up using: [gist](https://gist.github.com/ngosky/3b1645790db405b60412f94eb98ae9cf)

Notes:
- In order to fix the GLIBC mismatch I ended up using ubuntu:noble as the base image, which seemed to fix any GLIBC related errors.
- The Dockerfile also includes instructions to install a snapless, arm64 supported version of chromium, which was necessary for me to get puppeteer working on my server.

**Comment by m1daz** [comment]
Thank you for that, I was spending 2 whole days on this issue.

For my personal situation, I had a NextJS server with a backend worker that was ran with simple npx tsx watch for simplicity. I couldn't get puppeteer to work on this no matter what. 

I settled on splitting the "concurrently 'npm:start' 'npm:worker'" so that the base nixpack project would run ONLY the nextjs server, and the custom docker file with support for puppeteer would run the background worker. 

Now they "work", how well, I don't know.
