### ISSUE TITLE
[Bug]: Docker compose project creation states "Duplicate entry found. Please use a different name."

### ISSUE THREAD

**Issue by scflode** [coollabsio/coolify#2561]
### Description

When deleting a docker compose based resource and trying to recreate the same an error message stating "Duplicate entry found. Please use a different name." appears. After that "a" resource appears. But when trying to deploy there is the error message `Error: SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "service_applications_fqdn_unique"`.

Not sure how to completely remove an existing docker compose stack.

### Minimal Reproduction (if possible, example repository)

* Create a docker compose resource
* Delete it (maybe need to deploy first)
* Try to recreate the resource with the same docker compose file contents

### Version

v4.0.0-beta.297

**Comment by scflode** [comment]
Maybe a mistake was to not force cleanup containers?

**Comment by scflode** [comment]
A thing I noticed upon more testing:

The "Duplicate entry found. Please use a different name." message does create the resource / stack every time. Had just some fun cleaning up 🧽 😊

It could also be that my usage of `SERVICE_FQDN_SERVICE_NAME` is wrong or causing the issues.

**Comment by scflode** [comment]
Next error happens when trying to edit the docker compose definition: "The docker compose field is required."

**Comment by peaklabs-dev** [comment]
This issue should be resolved in the latest version. If you're still experiencing this issue, please reopen or create a new issue with updated details.
