### ISSUE TITLE
[Bug]: Static Site Deploy shows Nginx default page instead

### ISSUE THREAD

**Issue by samuelail** [coollabsio/coolify#2562]
### Description

I have deployed a static site successfully but upon visiting the url, I am greeted with a Welcome to nginx! page instead. No clue as to why this is happening / how to resolve.

### Minimal Reproduction (if possible, example repository)

Deployed a static site  using nginx:alpine

### Version

v4.0.0-beta.297

**Comment by Thijmen** [comment]
Do you have an example repository of what you deployed?

**Comment by samuelail** [comment]
Just tried again using different settings and it works fine. I think it may just have been the wrong deployment settings that I used. Closing this.
