### ISSUE TITLE
[Bug]: Unreadable recent executions in light theme

### ISSUE THREAD

**Issue by leonovk** [coollabsio/coolify#2565]
### Description

On a light theme, scheduled task recent executions are not readable
![Снимок экрана от 2024-06-15 23-16-17](https://github.com/coollabsio/coolify/assets/71232234/d6bba7df-79d5-418b-a32c-b4b5149ae299)

### Minimal Reproduction (if possible, example repository)

- enable light theme.
- go to the Scheduled Task section.

### Version

v4.0.0-beta.297

**Comment by peaklabs-dev** [comment]
This issue has been fixed in the latest version.
