### ISSUE TITLE
[Bug]: 500 error on Glitchtip Template

### ISSUE THREAD

**Issue by data-diego** [coollabsio/coolify#2566]
### Description

Hi!

When generating a new glitchtip instance from the templates I got this 500 error

`sql
Error: SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "service_applications_fqdn_unique" DETAIL: Key (fqdn)=(https://glitchtip-esg48wk.mywebsite.com:8080/) already exists. (Connection: pgsql, SQL: update "service_applications" set "fqdn" = https://glitchtip-esg48wk.mywebsite.com:8080/, "updated_at" = 2024-06-16 02:28:33 where "id" = 45)
`

And it happens with every autogenerated id, I don't have another glitchtip instance running

### Minimal Reproduction (if possible, example repository)

> v4.0.0-beta.297 > New project > new resource > glitchtip instance

### Version

v4.0.0-beta.297

**Comment by data-diego** [comment]
Same behavior as

#2561

with the
> Next error happens when trying to edit the docker compose definition: "The docker compose field is required."

and all

**Comment by LcsH0s** [comment]
did you find any work around for this issue?

**Comment by Aft1n** [comment]
Still this error with GlitchTip instance persists

**Comment by guillaumeklaus** [comment]
Found a workaround : https://github.com/coollabsio/coolify/issues/2743#issuecomment-2254246331

**Comment by tconroy** [comment]
Trying to do the workaround mentioned above-- however, I'm unable to save the docker-compose? When I try to change it I get error The docker compose field is required. and it seems the change doesn't stick

**Comment by LordSalmon** [comment]
The issue still persists. Any updates on this?
