### ISSUE TITLE
[Bug]: Can not change instance settings

### ISSUE THREAD

**Issue by snorrwe** [coollabsio/coolify#2569]
### Description

I installed a self-hosted Coolify instance via the script in https://coolify.io/self-hosted .
```
curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash 
```

Then I proceeded to uninstall Coolify.

```sh
docker ps -a -q | xargs docker stop
docker system prune -af --volumes
sudo rm -rf /data/coolify
```

I then reinstalled Coolify with the same script as before.
Most things work as expected, but I can not change the settings of the Coolify instance itself, such as the domain.

I didn't check if they worked before uninstalling, but I assume that I messed up the uninstall somehow?

Any help is appreciated.

### Minimal Reproduction (if possible, example repository)

```
curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash 

docker ps -a -q | xargs docker stop
docker system prune -af --volumes
sudo rm -rf /data/coolify

curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash 
```

Try to change instance settings such as domain.

### Exception or Error

```
No query results for model [App\Models\Server] 0
```

### Version

v4.0.0-beta.297

**Comment by sedathuysal** [comment]
I had the same error. I checked the domain names that were the same as the Instance's Domain and fixed the error.
Don't give same url any server or project. 
Checked settings;
-Projects>Domains
-Server>Wildcard Domains

**Comment by kybercore** [comment]
Same issue here. I've had this on two different hosts now, completely different network. I somehow managed to fix it on the first one but I forgot how I did it. I remember it took way too long to figure out but was super simple in the end, maybe I can figure it out

**Comment by kybercore** [comment]
Do you have your DNS on Cloudflare?

**Comment by snorrwe** [comment]
> Do you have your DNS on Cloudflare?

Yes

**Comment by ozzestrophic** [comment]
Have anyone figured it out? I'm facing the same issue

**Comment by ozzestrophic** [comment]
I had the same issue, rebooting my VPS solved it.

**Comment by snorrwe** [comment]
> I had the same issue, rebooting my VPS solved it.

Rebooting solved it for me as well! Thanks

**Comment by peaklabs-dev** [comment]
This should be fixed. Rebooting after uninstalling can always help. I still recommend using a fresh VPS if you want a clean reinstall of Coolify. You can also follow this doc https://coolify.io/docs/uninstall to completely remove Coolify (this should not require a reboot).
