### ISSUE TITLE
[Bug]: /bin/bash: -c: option requires an argument (NodeJS API deployment)

### ISSUE THREAD

**Issue by SpuriousGer** [coollabsio/coolify#2579]
### Description

![image](https://github.com/coollabsio/coolify/assets/24923457/5e2ca566-d2a1-4257-9a97-4ac43bea465a)

I receive the error:
`[Bug]: /bin/bash: -c: option requires an argument`

### Minimal Reproduction (if possible, example repository)

This happens on any NodeJS private repository that is deployed using SSH.

### Exception or Error

/bin/bash: -c: option requires an argument
/bin/bash: -c: option requires an argument
/bin/bash: -c: option requires an argument
/bin/bash: -c: option requires an argument
/bin/bash: -c: option requires an argument
/bin/bash: -c: option requires an argument
/bin/bash: -c: option requires an argument
/bin/bash: -c: option requires an argument
/bin/bash: -c: option requires an argument
/bin/bash: -c: option requires an argument
/bin/bash: -c: option requires an argument

### Version

v4.0.0-beta.297

**Comment by SpuriousGer** [comment]
This aggressive restarting of apps is extremely annoying. Is there a good reason to do this? I am a bit frustrated with Coolify because essentially nothing ever works. Maybe I am too dumb, but I have a NodeJS app that runs locally, but somehow nixpacks destroys everything. If I wanted to run containers, I am not sure I needed the overhead of Coolify.

**Comment by daniel7912** [comment]
Hi @SpuriousGer I'm also getting this error - did you find a way to fix it?

**Comment by nikki-tyagi** [comment]
Facing Same issue
