### ISSUE TITLE
Next.js environment variables not accessible during buildtime

### ISSUE THREAD

**Issue by pascalstockert** [coollabsio/coolify#258]
After migrating [my existing next.js project](https://github.com/pascalstockert/notion-blog) over to my own instance of Coolify, everything works fine. However, upon running the buildstep for my project, the incremental site generation panics at the API-call to Notion (which I use as a headless CMS) with the following log:

![image](https://user-images.githubusercontent.com/29748149/161156788-fe996405-e886-4a7c-bcb5-2dae47485e0d.png)

I've checked my secrets multiple times now, both keys and values, also re-adding them to the project without success. I've made sure to always set the "needed during buildtime" toggle as well, as can be seen here: 

![image](https://user-images.githubusercontent.com/29748149/161157021-b37d34c0-0275-4874-b6aa-745cab3a0f49.png)

I've built the project locally with the same secrets, it works fine there. My project expects the secrets to be passed in via `process.env` as can be seen in my [clients.helper.js](https://github.com/pascalstockert/notion-blog/blob/5006f063dd99a05a46ef63a06c3f95fa7c9f69cc/helpers/clients.helper.js).

Am I wrong in the assumption that Coolify passes the secrets in through `process.env`?

**Comment by andrasbacsai** [comment]
Nice catch! Found the issue. A fix will be released soon.

**Comment by pascalstockert** [comment]
Amazing work! I'll go check it out later during the day, thanks a lot!

**Comment by andrasbacsai** [comment]
Let me know if it still does not work!
