### ISSUE TITLE
[Bug]: DockerCleanupJob failed

### ISSUE THREAD

**Issue by ksaitor** [coollabsio/coolify#2580]
### Description

Getting spammed by these notifications 

![Screenshot 2024-06-17 at 19 05 39](https://github.com/coollabsio/coolify/assets/936436/42029a7d-e7d2-429d-9307-f1679af461ad)

### Minimal Reproduction (if possible, example repository)

n/a

### Version

v4.0.0-beta.297

**Comment by peaklabs-dev** [comment]
This issue should be resolved in the latest version. If you're still experiencing this issue, please reopen or create a new issue with updated details.
