### ISSUE TITLE
Freeze

### ISSUE THREAD

**Issue by moshetanzer** [coollabsio/coolify#2584]
### Description

Hi,

 I installed coolifyio on my vps. Got plenty of resources. All works well until I click on add resource and am taken to the add resource page. As soon as I click anything there the entire GUI and server freezes. And takes a few minutes until I can retry.  But am totally unable to add any resources. 

### Minimal Reproduction (if possible, example repository)

Just install cooling ui automatically on either Debian 12 or Ubuntu 24. 

### Exception or Error

WARNING: Realtime Error?!
Coolify could not connect to its real-time service.
This will cause unusual problems on the UI if not fixed!

Please ensure that you have opened the [required ports](https://coolify.io/docs/knowledge-base/server/firewall), check the related [documentation](https://coolify.io/docs/knowledge-base/cloudflare/tunnels) or get help on [Discord](https://coollabs.io/discord).

### Version

Latest

**Comment by Thijmen** [comment]
What are you adding and what are your server specs?

**Comment by moshetanzer** [comment]
As soon as i try anything. 4 cpu, 4gb ram, 50gb memory

**Comment by Thijmen** [comment]
What are you adding? It helps if you provide as much as information as possible. You mention 4GB RAM and 50GB memory, but I assume the 50GB is your disk space?

**Comment by moshetanzer** [comment]
yip 50gb disk space. When i interact with anything on that page - the entire server becomes unresponsive.

**Comment by Thijmen** [comment]
So you install it on the server, and you go to the Coolify web panel and it freezes?

**Comment by moshetanzer** [comment]
nope no error in network tab.

**Comment by moshetanzer** [comment]
Thanks for your help. Turns out after many hours that even though firewall was disabled - service provider had a top level firewall that was triggered 😤 brrr

**Comment by yusef-ho** [comment]
same issue here.
i post in the issues of infisical repo as well
https://github.com/Infisical/infisical/issues/2193

it seesm always happened after queue task completed
<img width="1552" alt="Screen_Shot_2024-08-02_at_12_50_46_PM" src="https://github.com/user-attachments/assets/776d016d-fe39-4356-bd74-4bf35543d23f">
<img width="776" alt="Screen_Shot_2024-08-02_at_12_50_24_PM" src="https://github.com/user-attachments/assets/b17cecba-b4e5-4683-80a6-c376282f3db3">

<img width="1552" alt="Screen_Shot_2024-08-04_at_9_36_34_AM" src="https://github.com/user-attachments/assets/f0a1cbba-fb0d-49b3-8dc7-10d6b057d062">
<img width="790" alt="Screen_Shot_2024-08-04_at_9_37_02_AM" src="https://github.com/user-attachments/assets/a801bb1c-9a83-49da-b896-a6497302faa8">

**Comment by xanderim** [comment]
> ### Exception or Error
> WARNING: Realtime Error?! Coolify could not connect to its real-time service. This will cause unusual problems on the UI if not fixed!
> 
> Please ensure that you have opened the [required ports](https://coolify.io/docs/knowledge-base/server/firewall), check the related [documentation](https://coolify.io/docs/knowledge-base/cloudflare/tunnels) or get help on [Discord](https://coollabs.io/discord).
> 
> ### Version
> Latest

I faced the same error today  while upgrading from v316 to v323. It froze the whole system (3 vcpu 10gb ram)
