### ISSUE TITLE
[Bug]: Getting spammed with notifications for DockerCleanupJob failed and ServerStatusJob failed every minute

### ISSUE THREAD

**Issue by ck-euan** [coollabsio/coolify#2587]
### Description

After pushing a successful deployment I am now getting spammed with notifications every minute. I am using the discord webhook notifications.

<img width="1094" alt="image" src="https://github.com/coollabsio/coolify/assets/147141389/ec84c22b-31c4-4af4-8d78-b38f2bdc11a0">

### Minimal Reproduction (if possible, example repository)

I just pushed a new deployment and then started getting spammed.

### Exception or Error

<img width="1097" alt="image" src="https://github.com/coollabsio/coolify/assets/147141389/1dfc67ca-299d-40ec-8952-a72efb6f8827">

### Version

v4.0.0-beta.297

**Comment by ck-euan** [comment]
Update: disabling then reenabling the discord notifications solved the issue. Just not sure what caused it

**Comment by ck-euan** [comment]
Just started happening again, also started just after a few successful deployments

**Comment by ksaitor** [comment]
same as https://github.com/coollabsio/coolify/issues/2580

**Comment by ksaitor** [comment]
keeps happening 
![image](https://github.com/coollabsio/coolify/assets/936436/27b6b979-ed09-4382-8d04-1bbbd67505a7)

**Comment by Nonolanlan1007** [comment]
Same problem every 10 minutes
![image](https://github.com/coollabsio/coolify/assets/84439677/00b4d279-743e-4e5d-a09a-e9961738caed)
