### ISSUE TITLE
Detect sveltekit repos

### ISSUE THREAD

**Issue by jesperordrup** [coollabsio/coolify#259]
Hi!

I just tested a few sveltekit repos. They are detected as svelte and then configured with static buildpack. Since sveltekit uses adapters for building to different enviroments (which you know all about since coolify is sveltekit 😄 ) it would be cool if we checked svelte.config.js for which adapter is used. If 

     import adapter from '@sveltejs/adapter-node';

 then select nodejs or a sveltekit buildpack.

Or maybe just stay with package.json detection but detect sveltekit and select nodejs or a sveltekit buildpack.

Coolify is awesome

**Comment by andrasbacsai** [comment]
For now, since #264, NodeJs is chosen by default for SvelteKit, but I will add SvelteKit build pack and custom scanner for these kinds of frameworks!
