### ISSUE TITLE
Can't open /dev/fd/63 on installation

### ISSUE THREAD

**Issue by icebob** [coollabsio/coolify#26]
Hi,

when I tried to install with sudo I've got the `Can't open /dev/fd/63` error message.

![image](https://user-images.githubusercontent.com/306521/113856025-fec7ca80-97a0-11eb-8de4-67430b2272d2.png)

Environment: Ubuntu 20.04

**Comment by andrasbacsai** [comment]
Hey,

Uh, yeah. It's because of [this](https://askubuntu.com/questions/1086617/dev-fd-63-no-such-file-or-directory).
I've updated the installation scripts and the landing page. You need to install Coolify differently from now on.

`/bin/bash -c "$(curl -fsSL https://get.coollabs.io/install.sh)"`

or with normal user:

`sudo /bin/bash -c "$(curl -fsSL https://get.coollabs.io/install.sh)"`

Let me know if it works now.

**Comment by icebob** [comment]
Not yet, but the problem that I've tried on a fresh Ubuntu 21.04 but it seems docker is not available for 21.04 yet.

**Comment by andrasbacsai** [comment]
Yeah, Ubuntu 20 is the latest supported by Docker, so I would not like to support later versions yet.

See: https://docs.docker.com/engine/install/ubuntu/

**Comment by icebob** [comment]
Yeah I know. I close it because the script started, so the problem is solved.

**Comment by icebob** [comment]
I know you don't support 21.04 but already Docker works on 21.04, so I thought try it again. Now it looks almost work but at "Github Private key" if I press ENTER, it exits to the shell.

![image](https://user-images.githubusercontent.com/306521/114720008-eb37d900-9d37-11eb-90ce-2b4af77e70a9.png)

**Comment by louis-eyond** [comment]
I am getting the same thing on 20.04, fresh VM.  Tried running the installation script again and getting stuck at the same place.

? Github Private key (you need to generate it by clicking on 'Generate private k
ey' button): Press <enter> to launch your preferred editor.root@localhost:~#

**Comment by andrasbacsai** [comment]
I do not understand this part: `copied the file over to the root directory`. What exactly did you copy? The private key?

Also, could you please re-run the installation script with debug mode? (second option in the installation menu)

**Comment by louis-eyond** [comment]
Hi, thanks for taking a look.  Yes, I placed the .pem license file generated in the Github "Generate private key" step into the /root/ folder...  I saw in another post that the expected response might  be "received file", though I was unable to get that to happen.  I ran the normal installer a few times, and also ran it in Debug mode.  Unfortunately, Debug didn't give any more information -- it just kicks you out to the prompt at this stage and doesn't continue the install.

I see that you have re-working the installation process at the top of the Projects queue, so I was happy to wait for the new installer to be released.   However, if you want me to try something else with the current script, I am happy to test it.

**Comment by andrasbacsai** [comment]
The new installer is in production! Give it a try, and let me know if it works now!

**Comment by louis-eyond** [comment]
The installation completed and got to the Login via Github page.  However, then I hit the error:
{"error":"Operation `settings.findOne()` buffering timed out after 10000ms"}

It looked like Mongo wasn't started after the install completed.  I restarted the system and all is good...  Just wanted to let you know about this part at the end in case others ran into it.  I also did a fresh install on a fresh Ubuntu 20.04 VM, and can confirm that the same error happened again in that environment as well.  Thanks again.

**Comment by andrasbacsai** [comment]
Hmm. I've tested several times with a fresh installation, but this problem never occurred. I will take a look into this problem asap. Thanks for reporting!

**Comment by andrasbacsai** [comment]
I just did a fresh installation, and it worked. Hmm. Do you have any specific detail, like cloud provider, cpu/memory, etc?

**Comment by andrasbacsai** [comment]
Due to inactivity, I'm closing this issue. However, if the problem persists, please reopen the issue. Thanks!
