### ISSUE TITLE
Service suggetion: rabbitmq

### ISSUE THREAD

**Issue by jesperordrup** [coollabsio/coolify#260]
https://www.rabbitmq.com/

**Comment by compgeniuses** [comment]
i think MQTT is also cool for the same. as an independent solution
@jesperordrup   Kindly Add and Vote for this request here: https://feedback.coolify.io/

**Comment by andrasbacsai** [comment]
Closing this one in favor of: https://feedback.coolify.io/posts/70/service-rabbitmq
