### ISSUE TITLE
[Bug]: Traefik proxy breaks when adding a prefix

### ISSUE THREAD

**Issue by alexandrucancescu** [coollabsio/coolify#2603]
### Description

Path prefix doesn't work when using Traefik as reverse proxy, and it breaks the whole app if the option _Strip Prefixes_ is also enabled (by default). The reverse proxy will stop responding to any request to the app. Disabling _Strip Prefixes_ option or switching to Caddy fixes the issue. Also tried editing _Container Labels_ but this field is rewritten with generated options when saving.

### Minimal Reproduction (if possible, example repository)

1. Add domain to a Coolify application using a prefix and with _Strip Prefixes_ options checked. For example: `http://co44ock.ip.ip.sslip.io/prefix`
2. Coolify will generate the following container labels:

```
traefik.enable=true

traefik.http.middlewares.gzip.compress=true

traefik.http.middlewares.http-0-co44ock-stripprefix.stripprefix.prefixes=/prefix

traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https

traefik.http.routers.http-0-co44ock.entryPoints=http

traefik.http.routers.http-0-co44ock.middlewares=https-0-co44ock-stripprefix,gzip

traefik.http.routers.http-0-co44ock.rule=Host(`co44ock.ip.ip.sslip.io`) && PathPrefix(`/prefix`)

traefik.http.routers.http-0-co44ock.service=http-0-co44ock

traefik.http.services.http-0-co44ock.loadbalancer.server.port=3000

caddy_0.encode=zstd gzip

caddy_0.handle_path.0_reverse_proxy={{upstreams 3000}}

caddy_0.handle_path=/prefix*

caddy_0.header=-Server

caddy_0.try_files={path} /index.html /index.php

caddy_0=http://co44ock.ip.ip.sslip.io

caddy_ingress_network=coolify
```

4. All request to the application/domain will result in a **404 page not found**, including the **prefix** in the requested URL and to paths that are surely defined in the application server and should not return **404**

Replacing the proxy with Caddy fixes the issue and also disabling the _Strip Prefix_ option

### Exception or Error

Traefik server outputs this error to the logs when making requests:

`2024-06-19T20:53:51.622924401Z time="2024-06-19T20:53:51Z" level=error msg="middleware \"https-0-co44ock-stripprefix@docker\" does not exist" routerName=http-0-co44ock@docker entryPointName=http` 

### Version

v4.0.0-beta.297

**Comment by Thijmen** [comment]
Can you indent your labels better so it's more easily to see what it actually is?

**Comment by alexandrucancescu** [comment]
@Thijmen Done, sorry about that

**Comment by Thijmen** [comment]
I doubt this is a 900.000 $ bounty?
