### ISSUE TITLE
[Improvement]: Add code editor to the Dockerfile and Docker Composer UI

### ISSUE THREAD

**Issue by ayntk-ai** [coollabsio/coolify#2607]
### Description

Right now, we can view the docker file or compose file, but there is no code highlighting or proper code formatting.

### Minimal Reproduction (if possible, example repository)

- [x] Add a code editor to dockerfiles and docker compose yml fiels to have proper highlighting and code formatting

-> Maybe Monaco editor can be used: https://github.com/microsoft/monaco-editor 

### Version

-

**Comment by andrasbacsai** [comment]
@ayntk-ai, can you please reward @MMTE ? thanks!

**Comment by ayntk-ai** [comment]
It is @DeVoresyah bounty not mine.

**Comment by DeVoresyah** [comment]
paid, please check @MMTE
