### ISSUE TITLE
[Bug]: docker: 'compose' is not a docker command.

### ISSUE THREAD

**Issue by Manubi** [coollabsio/coolify#2611]
### Description

Just installed coolify on an aws ec2 instance, but somehow the proxy will not start and throws this error: docker: 'compose' is not a docker command.

### Minimal Reproduction (if possible, example repository)

Install coolify v4 beta 297
install Docker version 25.0.3
install Docker Compose version v2.27.2
![CleanShot 2024-06-20 at 19 20 07@2x](https://github.com/coollabsio/coolify/assets/20935138/88fb1e23-5e18-4ce8-ac1d-625656585479)

### Exception or Error

error: docker: 'compose' is not a docker command.

### Version

v4 beta 297

**Comment by Thijmen** [comment]
Perhaps the install script should be improved, to check if the `docker compose` call works.

**Comment by Manubi** [comment]
Any suggestions how i should debug it? :)

**Comment by Thijmen** [comment]
@Manubi Yes, reinstall docker in a way that `docker compose` just works fine.

**Comment by Manubi** [comment]
I changed from the Amazon linux to ubuntu and it works.... guess just stay with the stuff that works. :)

**Comment by Thijmen** [comment]
Can you close the issue? That will help clean up the big list a bit. Unfortunately, it seems maintainer does not have time to manage all issues (@Manubi )
