### ISSUE TITLE
[Bug]: Preview deployments are showing an old version of the app

### ISSUE THREAD

**Issue by mbeaudru** [coollabsio/coolify#2614]
### Description

When creating a new PR, coolify creates a preview deployment for it. But if I push commits afterwards, then it re-deploys and rebuilds the app, but I still see the old version and not the new one.

- nextjs app on a github repository
- preview deployments activated, path is `preview-mywebsite.com`

### Minimal Reproduction (if possible, example repository)

I don't have exact steps to reproduce, but here is what I tried:

- change the domain name for preview env
- kill all deployments, load PR list and re-deploy the PR
- force deploy with cache clearing

No matter what, I'm not seing the updates on my app. I cleared my browser cache, open devtools & disable cache in network tab, the app hosted on preview-mywebsite.com really is the old one

### Exception or Error

Checking the build logs:

- commit used to build is correct ✅ 
- **build ends with:**

`[COMMAND] docker exec XXX bash -c 'SOURCE_COMMIT=XXX COOLIFY_FQDN=preview-mywebsite.com COOLIFY_URL=preview-mywebsite.com COOLIFY_BRANCH=main docker compose --project-directory /artifacts/XXX -f /artifacts/XXX/docker-compose.yml up --build -d'`

**I wonder is `COOLIFY_BRANCH` is not right for some reason**

### Version

v4.0.0-beta.297

**Comment by mbeaudru** [comment]
Actually, deployment starts with:

`Starting pull request (#17) deployment of <repo-owner>/<repo-name>:main`

Clearly indicates that it's building the PR from **main** 😅  so there's definitely an issue

**Comment by andrasbacsai** [comment]
That is fine. These parts are important:

<img src="https://uploads.linear.app/0fa98b19-e5f3-418f-abaf-f6d47b6f525f/99564d0a-3f73-4d6a-ac80-3089dbdff924/578c980f-2339-46d4-b83c-e9e49809bdbc?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzBmYTk4YjE5LWU1ZjMtNDE4Zi1hYmFmLWY2ZDQ3YjZmNTI1Zi85OTU2NGQwYS0zZjczLTRkNmEtYWM4MC0zMDg5ZGJkZmY5MjQvNTc4Yzk4MGYtMjMzOS00NmQ0LWI4M2MtZTllNDk4MDliZGJjIiwiaWF0IjoxNzE4OTc1MDI4LCJleHAiOjMzMjg5NTM1MDI4fQ.F8DqIyzS93V3ZVhtH0B49zogjOYSV8Ic6p26IL1XTWc " alt="image.png" width="1022" height="383" />

I fixed a few issues in the latest (unreleased) version, so lets wait for the release and test it afterwards.
