### ISSUE TITLE
Coolify can't auto setup domain with nginx 

### ISSUE THREAD

**Issue by raniaamina** [coollabsio/coolify#262]
Hi, i'm so sorry if it's very silly question.

This is my first time using coolify. I try running it on my server that also run Nginx. Am i still need to set up each domain in nginx for each apps that i build manually or there are an easy way to do it? I use Nginx to run some service and site, btw.

Hope some one get my point 😅.
Thanks :")

**Comment by andrasbacsai** [comment]
Hey, there is no silly question. :) 

Coolify has its own proxy, and generates all configuration automatically. At the moment, it cannot be integrated automatically with other proxies, but you can disable Coolify's proxy, but then you need to configure nginx for all your applications manually.

I do not think it will be integrated with Nginx in the near future.

**Comment by raniaamina** [comment]
Hmm okay. Thank you for your answer.
So, I'm going to make some scripts to do this. The nginx setup is sometimes a tedious part of my workflow haha

Once again, thank you.

**Comment by raniaamina** [comment]
Ah, btw @andrasbacsai 
How to publish docker port in coolify? I try to deploy just static site that contain only plain html (with some css and js of course) in coolify? But i can't access it outside since the docker port not publised after deployment complete in coolify. It also happen to other nodejs apps, i think. Also, in static site deployment can we choose custom port like in nodejs apps, instead of 80?

thanks in advance :")
