### ISSUE TITLE
[Bug]: Environment Variables are not being applied to n8n service docker-compose.yml file

### ISSUE THREAD

**Issue by salomaoparkour** [coollabsio/coolify#2622]
# Description

Event after defining the environment variables, they don't apply to my docker-compose-yml file.

# Minimal Reproduction

1. I've installed n8n using the Coolify UI, didn't change anything except the domain.

2. Defined the variable GENERIC_TIMEZONE to "America/Sao_Paulo".
3. Pressed the button "Pull Latest Images & Restart"
4. Nothing changed in my docker-compose.yml, but it did change in my .env file

## docker-compose.yml
![image](https://github.com/coollabsio/coolify/assets/890826/810a8a87-c1ed-4db5-8c94-fa0e9ace3d1d)

## .env
![image](https://github.com/coollabsio/coolify/assets/890826/1c61f857-716e-4604-b154-78d496d59ac2)

## Coolify
![image](https://github.com/coollabsio/coolify/assets/890826/25554f75-b049-4fc3-a92a-063386743eb7)

### Version

v4.0.0-beta.297

**Comment by andrasbacsai** [comment]
At the moment, this is a normal behaviour. In the next version it will be fixed. By default, it will use the hardcoded variable (like with `GENERIC_TIMEZONE` in your example), but if you add an env variable through the UI, it will be overwritten in the final compose file.


![image](https://github.com/coollabsio/coolify/assets/5845193/4c55c1a9-e864-46d3-8b0b-12d977a9c880)

Raw compose file:
![image](https://github.com/coollabsio/coolify/assets/5845193/97e859e6-46c4-409f-b41a-95761334958e)

Deployable compose file (Coolify magic applied):
![image](https://github.com/coollabsio/coolify/assets/5845193/09280e0d-7f71-4ea3-9019-87ee3ef5f6b0)
