### ISSUE TITLE
[Bug]: Custom Labels in "Container Labels" Field are overwritten on save

### ISSUE THREAD

**Issue by oocastor** [coollabsio/coolify#2627]
### Description

Custom Labels in "Container Labels" Field are overwritten on save.

I also checked this behaviour on version 277 and had no problems there.

### Minimal Reproduction (if possible, example repository)

1. Create a (static site) project/resource
2. Deploy it
3. Add something to the "Container Labels" Field
4. Save your configuration

_-- you should see that your inputs have been overwritten --_

### Exception or Error

_No Error_

### Version

v4.0.0-beta.297

**Comment by opestro** [comment]
i have the same problem i think , when i add some rules to container labels , it reset auto. when i click at save button

**Comment by MeDoTarek73** [comment]
I have the Same Problem on the lates release, once i click on save button labels is removed

**Comment by stonediggity** [comment]
Same problem here on latest release. I saw there's a [PR](https://github.com/coollabsio/coolify/pull/2553) here that is meant to have resolved?

**Comment by andrasbacsai** [comment]
Yes, it will fix it. I will release the new version tomorrow or latest on Tuesday.

**Comment by andrasbacsai** [comment]
As someone on stream noticed me that it is still an issue, I will add a new option to make labels readonly (for Coolify).

As you update your domains, or change some conf that needs to recreate labels, Coolify won't update your labels if you set readonly to true. You need to manually update the labels.

<img src="https://uploads.linear.app/0fa98b19-e5f3-418f-abaf-f6d47b6f525f/88893ffe-2b12-415b-941b-ecb2232c0c51/fb94425d-d0cf-4efd-9342-d46f127c3839?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzBmYTk4YjE5LWU1ZjMtNDE4Zi1hYmFmLWY2ZDQ3YjZmNTI1Zi84ODg5M2ZmZS0yYjEyLTQxNWItOTQxYi1lY2IyMjMyYzBjNTEvZmI5NDQyNWQtZDBjZi00ZWZkLTkzNDItZDQ2ZjEyN2MzODM5IiwiaWF0IjoxNzIxMjIwNjg5LCJleHAiOjMzMjkxNzgwNjg5fQ.sLzfMwEHeVvf9iaYipZmFqVpdb9YJVS2LYuMHKngqQE " alt="image.png" width="855" height="542" />
