### ISSUE TITLE
Paste .env file content (making coolify even cooler)

### ISSUE THREAD

**Issue by jesperordrup** [coollabsio/coolify#263]
Here is a general thing that I love to address, make UI even better. Generally speaking UI helps a lot when it comes to configuring complicated setups. But they also get in the way and sometimes its the smallest things that does the trick. For instance, configuring env variables.

![image](https://user-images.githubusercontent.com/3120151/161259159-1fdf5777-804e-4880-b4c7-2bc5050abc2e.png)

While it makes complete sense it still is a tedious work to update this. Consider the flow. You probably already have an .env file (at least I hope you do) and now you need to put all the values into this. It would actually be easier to enter all if we could paste the content of the file instead and leave it at that. 

Or even better, paste in the .env and parse it to fields. 
Even allow to repeat and update existing.

Step two allow to enable / disable visability for build time

**Comment by SaraVieira** [comment]
I can work on this @andrasbacsai 

Is that okay with you?

**Comment by andrasbacsai** [comment]
Sure! Thank you! 🙏

I imagine it as a simple textarea and with a function that parses and adds it as secrets.

**Comment by jesperordrup** [comment]
If I remember correct, the current UI does not allow for changing visibility for build on previously added rows. If so, then I suggest allowing to change that at any time.
