### ISSUE TITLE
[Bug]: Penpot SERVICE_FQDN_FRONTEND environmental variable has a trailing slash

### ISSUE THREAD

**Issue by HarleySalas** [coollabsio/coolify#2634]
### Description

With the Penpot service install, it adds a trailing slash to the `SERVICE_FQDN_FRONTEND` and technically, that is a url, not FQDN.I see this pattern a lot with services; the variables are stated as an "FQDN," but an FQDN is simply a host and address, like "example.com" or "sub.example.com," not the `https://` prefix, nor a trailing `/`.

### Minimal Reproduction (if possible, example repository)

Just do a one click install of Penpot

### Exception or Error

The issue is that for the emails penpot sends, it uses the FQDN to construct it's callback urls and it adds it's own trailing slash, as it expects a FQDN. The result is that we end up with not found pages, instead of getting the correct callback.
![image](https://github.com/coollabsio/coolify/assets/38236585/24226891-2205-4816-adfd-f63a90363687)

This is the sort of url that comes out, note the two forward slashes after `.com//`
`https://penpot.mydomain.com//#/auth/recovery?token=(redacted)`

### Version

297

**Comment by HarleySalas** [comment]
`https://twenty.mywebsite.com//graphql` also broke my twenty crm, which is live and being used :(

**Comment by GunniBusch** [comment]
yes needs to be fixed asap

**Comment by carbontwelve** [comment]
Just noticed this today `SERVICE_URL_APPWRITE` is expected to generate something like `appwrite-vgsco4o.example.com` instead it generates with trailing slash `appwrite-vgsco4o.example.com/`

**Comment by cabaalexander** [comment]
👀
