### ISSUE TITLE
[Bug]: Unable to specify Redis AOF

### ISSUE THREAD

**Issue by ladderschool** [coollabsio/coolify#2637]
### Description

When creating a Redis resource from Coolify the docker-compose.yaml sets the following command:
```
    "Args": [
            "redis-server",
            "/usr/local/etc/redis/redis.conf",
            "--requirepass",
            "<password>",
            "--appendonly",
            "yes"
        ],
```

The problem is that it adds --appendonly yes after the redis.conf is read. This means, if you set "appendonly no" in your redis.conf it will have no effect. Essentially, the DX suffers because you can't control if you want persistence or not. You must **always** have persistence. This is not necessary and I recommend removing the --apendonly yes to the redis-server startup in the docker compose file. Allow the developer to choose if they want AOF by using the redis.conf. Equally, it would be beneficial if the developer could set the --requirepass value, there is also a setting in the redis.conf for this. Overall, I suggest redis.conf > startup arguments for a better DX.

### Minimal Reproduction (if possible, example repository)

Go to your Coolify server and create a new Redis resource. Try to use appendonly no in your redis.conf and delete the appendonlydir. Restart the Redis and watch how it recreates the appendonlydir and neglects your appendonly no configuration in the redis.conf

### Exception or Error

N/A

### Version

v4.0.0-beta.297

**Comment by peaklabs-dev** [comment]
@ladderschool I am implementing this. Is the following behavior what you are looking for?
- If there is a redis.conf with --requirepass, --requirepass form the redis.conf will be used.
- If there is no --requirepass in redis.conf, but there is a redis.conf, then add --requirepass.
- No redis.conf: --requirepass is used.
- If there is a redis.conf do not add --appendonly

**Comment by ladderschool** [comment]
Sorry for the late reply, I've been busy with work.

That's exactly what I would expect, yes!

**Comment by peaklabs-dev** [comment]
This has been implemented and will be available in an upcoming release. Thank you for your patience.
