### ISSUE TITLE
[Bug]: Filebrowser template is broken

### ISSUE THREAD

**Issue by ershisan99** [coollabsio/coolify#2641]
### Description

When using `filebrowser/filebrowser:latest` docker image and the default config I'm getting **404 not found** independent of the domain I use. 
Using `filebrowser/filebrowser:v2.28.0-amd64-s6` instead solves the issue for now, but that feels like a workaround.

### Minimal Reproduction (if possible, example repository)

1. Create a new filebrowser resource with the default configuration
2. Observe the issue

### Exception or Error

No errors are logged, everything looks fine.
Some observations:
1. Changing healthcheck port from 8080 to 80 somehow makes it return 502 Bad Gateway
2. Executing `curl -f 127.0.0.1:80` in "Execute Command" menu returns what seems like correct html for filebrowser

### Version

v4.0.0-beta.297

**Comment by iamEvanYT** [comment]
@ershisan99 try this docker-compose.
https://github.com/iamEvanYT/coolify-stuff/blob/main/composes/filebrowser.yaml

**Comment by developomp** [comment]
changing `SERVICE_FQDN_FILEBROWSER` to `SERVICE_FQDN_FILEBROWSER_80` fixed the issue for me.

```diff
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    environment:
-      - SERVICE_FQDN_FILEBROWSER
+      - SERVICE_FQDN_FILEBROWSER_80

...
```
