### ISSUE TITLE
[Bug]: Error: Docker build failed

### ISSUE THREAD

**Issue by samuelail** [coollabsio/coolify#2647]
### Description

Not sure what happened but I'm no longer able to deploy new versions of my app and I can't seem to figure out why. Hoping someone could see & tell me what I'm missing.

### Minimal Reproduction (if possible, example repository)

- Please look at the error logs below. 

### Exception or Error

[2024-Jun-24 04:33:45.254998] Oops something is not okay, are you okay? 😢

[2024-Jun-24 04:33:45.258566] #0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 1.10kB 0.0s done
#1 DONE 0.0s

#2 [internal] load metadata for ghcr.io/railwayapp/nixpacks:ubuntu-1716249803
#2 DONE 0.2s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [stage-0 1/11] FROM ghcr.io/railwayapp/nixpacks:ubuntu-1716249803@sha256:5ef4d2021c418fcaabb56cea5ea9e24a5fdedfe27f58062d9689214dfed45c46
#4 DONE 0.0s

#5 [internal] load build context
#5 transferring context: 926.38kB 0.1s done
#5 DONE 0.1s

#6 [stage-0 2/11] WORKDIR /app/
#6 CACHED

#7 [stage-0 3/11] COPY .nixpacks/nixpkgs-bdd2f439c62aa0b8aa97f5c784a965c23f968fe6.nix .nixpacks/nixpkgs-bdd2f439c62aa0b8aa97f5c784a965c23f968fe6.nix
#7 CACHED

#8 [stage-0 4/11] RUN nix-env -if .nixpacks/nixpkgs-bdd2f439c62aa0b8aa97f5c784a965c23f968fe6.nix && nix-collect-garbage -d
#8 CACHED

#9 [stage-0 5/11] RUN sudo apt-get update && sudo apt-get install -y --no-install-recommends curl wget
#9 CACHED

#10 [stage-0 6/11] COPY . /app/.
#10 DONE 0.1s

#11 [stage-0 7/11] RUN --mount=type=cache,id=hkswcwk-/root/npm,target=/root/.npm npm ci
#11 1.326 npm WARN config production Use `--omit=dev` instead.
#11 4.425 npm ERR! code EUSAGE
#11 4.431 npm ERR!
#11 4.431 npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
#11 4.432 npm ERR!
#11 4.432 npm ERR! Invalid: lock file's typescript@5.5.2 does not satisfy typescript@4.9.5
#11 4.432 npm ERR!
#11 4.433 npm ERR! Clean install a project
#11 4.433 npm ERR!
#11 4.433 npm ERR! Usage:
#11 4.433 npm ERR! npm ci
#11 4.433 npm ERR!
#11 4.433 npm ERR! Options:
#11 4.433 npm ERR! [--install-strategy <hoisted|nested|shallow|linked>] [--legacy-bundling]
#11 4.433 npm ERR! [--global-style] [--omit <dev|optional|peer> [--omit <dev|optional|peer> ...]]
#11 4.433 npm ERR! [--include <prod|dev|optional|peer> [--include <prod|dev|optional|peer> ...]]
#11 4.433 npm ERR! [--strict-peer-deps] [--foreground-scripts] [--ignore-scripts] [--no-audit]
#11 4.433 npm ERR! [--no-bin-links] [--no-fund] [--dry-run]
#11 4.433 npm ERR! [-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]
#11 4.433 npm ERR! [-ws|--workspaces] [--include-workspace-root] [--install-links]
#11 4.433 npm ERR!
#11 4.433 npm ERR! aliases: clean-install, ic, install-clean, isntall-clean
#11 4.433 npm ERR!
#11 4.433 npm ERR! Run "npm help ci" for more info
#11 4.435
#11 4.435 npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-06-24T04_33_41_874Z-debug-0.log
#11 ERROR: process "/bin/bash -ol pipefail -c npm ci" did not complete successfully: exit code: 1
------
> [stage-0 7/11] RUN --mount=type=cache,id=hkswcwk-/root/npm,target=/root/.npm npm ci:
4.433 npm ERR! [--strict-peer-deps] [--foreground-scripts] [--ignore-scripts] [--no-audit]
4.433 npm ERR! [--no-bin-links] [--no-fund] [--dry-run]
4.433 npm ERR! [-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]
4.433 npm ERR! [-ws|--workspaces] [--include-workspace-root] [--install-links]
4.433 npm ERR!
4.433 npm ERR! aliases: clean-install, ic, install-clean, isntall-clean
4.433 npm ERR!
4.433 npm ERR! Run "npm help ci" for more info
4.435
4.435 npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-06-24T04_33_41_874Z-debug-0.log
------
Dockerfile:20
--------------------
18 | ENV NIXPACKS_PATH /app/node_modules/.bin:$NIXPACKS_PATH
19 | COPY . /app/.
20 | >>> RUN --mount=type=cache,id=hkswcwk-/root/npm,target=/root/.npm npm ci
21 |
22 | # build phase
--------------------
ERROR: failed to solve: process "/bin/bash -ol pipefail -c npm ci" did not complete successfully: exit code: 1
Error: Docker build failed

[2024-Jun-24 04:33:45.261899] Deployment failed. Removing the new version of your application.

### Version

v4.0.0-beta.297

**Comment by zairigimad** [comment]
how did you fixed it ?

**Comment by shachar-langer** [comment]
I encountered a similar issue. I ran `npm install` and redeployed the app using the updated `package-lock.json`
