### ISSUE TITLE
Build webhooks

### ISSUE THREAD

**Issue by bobvanoorschot** [coollabsio/coolify#265]
It would be nice if you can create custom build webhooks. That you could rebuild an application from a CMS.

**Comment by tanc** [comment]
Yes exactly, in testing Coolify this is the most obvious omission. I have decoupled Nuxt generated (static) frontends that are fed with content from Strapi backends. In Strapi the editors can trigger a build by hitting a button which calls a webhook url and triggers the build (currently building on Github actions).

I imagine this is a reasonable common scenario and it would be great to have a solution within Coolify.

**Comment by narduin** [comment]
I have the exact same use case and this is the only thing preventing me from using coolify in production for clients.
I have yet to find a workaround until internal webhooks are available 😅

**Comment by oberbayer** [comment]
+1 on that. @narduin Have you found a workaround? I'm curious because I currently have no idea how to auto-update my ElderJS-Website when content on Directus CMS changes...

**Comment by narduin** [comment]
@oberbayer thanks a lot for sharing this, I had not found any slolution and will test yours soon :)

**Comment by themarkwill** [comment]
> 
@oberbayer I hade Create a GitHub actions, for you can execute a deploy from a GitHub actions, You can help me in my GitHub action or test? 
https://github.com/marketplace/actions/coolify-application-deploy
https://github.com/themarkwill/coolify-actions

In this case you not need change your story of commit for execute a deploy!

**Comment by fd6130** [comment]
I need some hooks for my projects too especially after deployment success and in the middle of deployment, because every new project i deploy i need to upload some private files and new env.

Without hook I have no idea how to use this to deploy php application.

**Comment by tanc** [comment]
Just to update people watching this issue, the developer said the following today [on Discord](https://discord.com/channels/459365938081431553/1039459860967866389/1056181042106597376):

> webhooks will come very soon. I’m migrating the codebase to tRPC, so the frontend API calls will be separated from the API (way better DX). It would take a week to finish. After that, I will focus on making a reliable REST API for remote calling (that includes custom webhooks), so everyone can integrate Coolify into their current workflows. I have a LOT of things coming from January - let’s say I would like to go all-in on Coolify.
