### ISSUE TITLE
[Bug]: The second server tries to obtain a Let's Encrypt certificate, similar to the Coolify server (manager), when the instance's domain is set.

### ISSUE THREAD

**Issue by maisen20** [coollabsio/coolify#2650]
### Description

On the Coolify server (where only the Coolify instance is operated), a domain is defined under 'Instance's Domain' (co.example.com). When I set up a second server and run applications on it, everything seems to work fine (one application uses for example test.example.com).

Unfortunately, the second server also tries to obtain a certificate for the Instance Domain (co.example.com). However, this doesn't work because both servers have different IP addresses, and the Instance Domain only points to the Coolify server (manager).

Thus, I quickly reached the certificate limit of Let's Encrypt, and the second server was therefore blocked from making new certificate requests. 

### Minimal Reproduction (if possible, example repository)

Create the following example domains and assign them to the servers:

- co.example.com points to the IP of the Coolify main instance.
- test.example.com points to the IP of Server 2 with the example application.

In Coolify, under Settings, set the Instance Domain to co.example.com.

It may be necessary to restart both servers. However, the second server always tries to obtain a certificate for co.example.com, which is not possible because this domain does not point to the second server.

### Version

v4.0.0-beta.297

**Comment by scflode** [comment]
I encounter a similar one leading to https://letsencrypt.org/docs/too-many-registrations-for-this-ip/ which means the other server is blocked. Will see how it looks like in ~3hrs but suspect the problem to reoccur.

**Comment by KobyW** [comment]
I noticed this as well - Guessing it's due to the instance name persisting to other server's dynamic proxy configs.

This can be observed by going to **Servers > Other-server > Proxy > Dynamic Configurations > File: coolify.yaml** (contains certresolver for coolify's instance's set domain)

**Comment by maisen20** [comment]
> I noticed this as well - Guessing it's due to the instance name persisting to other server's dynamic proxy configs.
> 
> This can be observed by going to **Servers > Other-server > Proxy > Dynamic Configurations > File: coolify.yaml** (contains certresolver for coolify's instance's set domain)
> 
> #### Version
> v4.0.0-beta.306

Exactly, and even if you modify or comment out all lines in this file, everything will be reactivated upon a proxy restart (the coolify.yml file gets rewritten).

**Comment by sthyx** [comment]
Same observation here. Second server is unable to obtain certificate (takes domain from main server). The second server should take the domain from the "Wildcard Domain" field.

**Comment by SanderVreeken** [comment]
Has a solution been found for this issue? I'm attempting to deploy a second server using the same public IP address. I've opened port 22 so that the main server can access the second one, but I'm unable to get it working. I expected the second server to adopt the configuration from the first one, but it seems this is not the case, as it has its own proxy settings.

**Comment by KobyW** [comment]
Made a simple addition to `/app/Models/Server.php` to ignore creating `coolify.yaml` if the server isn't the local instance. Fixed the issue on my development build. 

PR #2760

**Comment by shashank-sharma** [comment]
Have been facing the same issue as well, trying to connect my Raspberry Pi with coolify running on the cloud, but it keeps on picking the same domain name which I defined on coolify instance, and refresh overrides every time in raspberrypi. Ideally, there has to be an option for domain name

Is there any workaround for this?

**Comment by KobyW** [comment]
> Have been facing the same issue as well, trying to connect my Raspberry Pi with coolify running on the cloud, but it keeps on picking the same domain name which I defined on coolify instance, and refresh overrides every time in raspberrypi. Ideally, there has to be an option for domain name
> 
> Is there any workaround for this?

A current workaround is to remove the instance domain from Coolify settings, then restart the remote server's proxy. You can set the domain back in settings after the remote proxy is up.

Hopefully #2760 can be looked at soon, it seemed to resolve it for me.
