### ISSUE TITLE
[Bug]: Nixpacks deploy issue

### ISSUE THREAD

**Issue by mkowalickiiai** [coollabsio/coolify#2652]
### Description

When you are trying to deploy a nodejs app, you are getting an error of docker-credential-desktop.exe
`

### Minimal Reproduction (if possible, example repository)

- create a new user
- try to create a new project from repo
- config as Nixpacks image
- deploy

### Exception or Error

```
ERROR: error getting credentials - err: exec: "docker-credential-desktop.exe": executable file not found in $PATH, out: 
------
 > [internal] load metadata for ghcr.io/railwayapp/nixpacks:ubuntu-1716249803:
------
Dockerfile:1
--------------------
   1 | >>> FROM ghcr.io/railwayapp/nixpacks:ubuntu-1716249803
   2 |     
   3 |     ENTRYPOINT ["/bin/bash", "-l", "-c"]```

### Version

4

**Comment by andrasbacsai** [comment]
Do you have an example repository for this? It should be related to your repo / nixpacks configurations.

**Comment by peaklabs-dev** [comment]
Due to inactivity, we're closing this issue.
