### ISSUE TITLE
[Bug]: Problem deploying using Docker Compose. Container not created or started.

### ISSUE THREAD

**Issue by jakedhamilton** [coollabsio/coolify#2666]
### Description

I can no longer deploy using Docker Compose. When adding the script and selecting deploy, the container isn't creating and I am getting the output **Non-string key in services.postgis.environment: 0** instead in the Service Start-up logs. I also used to be able to select the server, and deploy to a standalone docker container (the options no longer exist).

### Minimal Reproduction (if possible, example repository)

- Go into your project
- Select add a New Resource
- Select Docker Compose
- There used to be more options after this but now it goes straight to adding the script
- Add your compose file - in my case I want to add a postgis database (script below)
- Select deploy

Log output:
<img width="685" alt="Screenshot 2024-06-24 at 17 45 48" src="https://github.com/coollabsio/coolify/assets/85233396/0b853921-30dc-4a34-aedf-be377f14d9b6">

**Docker Compose file**

services:
  postgis:
    image: postgis/postgis
    container_name: postgis-container
    restart: always
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: example
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgis:/var/lib/postgresql/data

### Version

v4.0.0-beta.300

**Comment by jakedhamilton** [comment]
I've checked and this wasn't an issue in v4.0.0-beta.297

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.

**Comment by andrasbacsai** [comment]
It should be fixed in v302.
