### ISSUE TITLE
Layout application log 

### ISSUE THREAD

**Issue by danieldocki** [coollabsio/coolify#267]
<img width="1596" alt="Screen Shot 2022-04-01 at 13 45 09" src="https://user-images.githubusercontent.com/10542/161308651-95da8c26-8336-41e3-aa51-9ce0d7480e40.png">

**Comment by SaraVieira** [comment]
Hey

Can you share the page you where in and your screen size?

**Comment by danieldocki** [comment]
> Hey
> 
> Can you share the page you where in and your screen size?


page path > applications/cl1hyg4be934600omj7bo6ud6q/logs
screen size > 1916 x 976

**Comment by SaraVieira** [comment]
I cant seem to repdroduce that, would it be okay for you to copy the logs you have? it seems to be some CSS thing :/
