### ISSUE TITLE
[Bug]: Supabase template broken in 4.0.0b302

### ISSUE THREAD

**Issue by olsoda** [coollabsio/coolify#2671]
### Description

fresh install of Coolify, trying to spin up a Supabase instance from the template. default settings on everything:

`Saved configuration files to /data/coolify/services/zcg0okw.
Creating Docker network.
Starting service.
Pulling images.
Non-string key in services.imgproxy.environment: 0`

Might add that seems like Supabase hasn't worked correctly for a bit now in general (including port problems as indicated in other issue reports)

### Minimal Reproduction (if possible, example repository)

New resource -> Supabase -> Deploy

### Version

4.0.0-beta.302

**Comment by slowlydev** [comment]
I am getting a similar error while trying to deploy a minio resource.

```
Saved configuration files to /data/coolify/services/f8ssgc8.
Creating Docker network.
Starting service.
Pulling images.
Non-string key in services.minio.environment: 0
```
