### ISSUE TITLE
[Bug]: Script editor on Docker Compose File not creating variables correctly

### ISSUE THREAD

**Issue by jakedhamilton** [coollabsio/coolify#2676]
### Description

When creating a database using Docker Compose, the environment variables are not getting displayed correctly, causing connection errors.

For example, when deploying the docker compose file below, the environment variables are getting saved as

POSTGRES_PASSWORD=example=example
POSTGRES_DB=example=example
POSTGRES_USER=example=example

**Docker Compose File in editor**
<img width="577" alt="Screenshot 2024-06-25 at 09 17 42" src="https://github.com/coollabsio/coolify/assets/85233396/bafb3a0f-e9f6-4f7e-af1e-0dc828ea8148">

### Minimal Reproduction (if possible, example repository)

- Create Docker Compose File
- Type and Save
- Deploy
- Checked variables in cli using 'docker exec container-name env'

### Version

v4.0.0-beta.304

**Comment by andrasbacsai** [comment]
It will be fixed in the next version. I implemented a new parsing method.
