### ISSUE TITLE
[Improvement]: Add code editor for compose files also to the services popup

### ISSUE THREAD

**Issue by ayntk-ai** [coollabsio/coolify#2683]
### Description

There is a popup in services where we can view the compose file:
![image](https://github.com/coollabsio/coolify/assets/122374094/3e80a36f-95d1-4297-99ae-208b1d02fec2)

### Minimal Reproduction (if possible, example repository)

Add the code editor added here: https://github.com/coollabsio/coolify/issues/2607 also tho the popup for services.

### Version

v4.0.0-beta.306

**Comment by andrasbacsai** [comment]
This is already added in the next version.

**Comment by ayntk-ai** [comment]
Wow amazing work. Thank you so much keep it up.
