### ISSUE TITLE
[Bug]: Missing logo in features section

### ISSUE THREAD

**Issue by SaadVakharia** [coollabsio/coolify#2694]
### Description

![image](https://github.com/coollabsio/coolify/assets/88484358/e91259da-aadf-40bf-8ada-300f7ffa8377)
I don't think it is intentional and I also don't know to fix it.

https://coolify.io/docs/introduction

### Minimal Reproduction (if possible, example repository)

Provide a icon for that.

### Version

v4.0.0-beta.306

**Comment by marinofranz** [comment]
I've opened coollabsio/documentation-coolify#30 and will resolve this issue 🙂
