### ISSUE TITLE
[Bug]: Prisma needs to perform transactions, which requires your MongoDB server to be run as a replica set. https://pris.ly/d/mongodb-replica-set

### ISSUE THREAD

**Issue by thegrtnx** [coollabsio/coolify#2699]
### Description

[Nest] 901783  - 06/27/2024, 2:15:45 AM   ERROR [ExceptionsHandler] 
Invalid this.prisma.user.create() invocation in
/home/dell/Documents/programming/nestjs/invest-ai/stock-invest/src/auth/auth.service.ts:43:41

  40 
  41 const hashedPassword = await bcrypt.hash(registerUser.password, 10);
  42 
→ 43 const user = await this.prisma.user.create(
Prisma needs to perform transactions, which requires your MongoDB server to be run as a replica set. https://pris.ly/d/mongodb-replica-set

### Minimal Reproduction (if possible, example repository)

1. Create a mongodb resource and try connecting it using nestjs

### Version

v4.0.0-beta.306

**Comment by Nonolanlan1007** [comment]
This problem doesn't come from coolify, but from the configuration of your mongodb server.

**Comment by thegrtnx** [comment]
The mongodb server is on my coolify.

**Comment by DeVoresyah** [comment]
how to solve this issue if we deployed MongoDB on coolify? @thegrtnx @Nonolanlan1007

**Comment by thegrtnx** [comment]
I couldnt fix it.. I had to use postrgres as my db. @DeVoresyah

**Comment by Nonolanlan1007** [comment]
You need to configure your mongodb instance as a member of a replication set : https://www.mongodb.com/docs/manual/tutorial/convert-standalone-to-replica-set/

**Comment by thegrtnx** [comment]
Thank you @Nonolanlan1007 ... do you mind do a video on how this can be configured on coolify?
Will be so much appreciated.

**Comment by Nonolanlan1007** [comment]
There is no differences if you use coolify or not…

**Comment by peaklabs-dev** [comment]
Please move to this [discussion](https://github.com/coollabsio/coolify/discussions/3862) for this as replicas are not yet supported.
