### ISSUE TITLE
[Bug]: FQDM and URL environment variables and autogenerate magic are switched up

### ISSUE THREAD

**Issue by ayntk-ai** [coollabsio/coolify#2702]
### Description

Coolify used the logic of FQDM for the whole URL like: http://appwrite-vgsco4o.example.com/ and for the URL it is appwrite-vgsco4o.example.com --> This is wrong because the URL is the FQDM and a FQDM has no http or any other protocol. It should be the other way around

### Minimal Reproduction (if possible, example repository)

- [ ] Switch FQDM to be actually just the domain like so: domain.com
- [ ] Switch URL to be the URL with the protocol like so: https://domain.com
-> Currently it is the other way around, which is quite confusing.
A list of things that need to be fixed:
- [ ] Auto-generated magic: https://coolify.io/docs/knowledge-base/add-a-service -> Switch URL and FQDN
- [ ] Compose files for service need to be adjusted (autogenrate logic)
- [ ] Predefined environment variables -> https://coolify.io/docs/knowledge-base/environment-variables#coolify-fqdn -> Here also FQDN needs to be switch with URLs --> URLs gives back all URLs with HTTPs or HTTP with the protocol and the FQDN only the domain with the TLD (eg. .com, .net, .io...)

### Version

v4.0.0-beta.306

**Comment by scflode** [comment]
See #2443

**Comment by ayntk-ai** [comment]
Duplicated
