### ISSUE TITLE
[Bug]: If an environment variable is changed to hardcoded, the UI variable is not removed.

### ISSUE THREAD

**Issue by peaklabs-dev** [coollabsio/coolify#2703]
### Minimal Reproduction (if possible, example repository)

For example, if we change the variable: `WORDPRESS_DB_NAME=$WORDPRESS_DB_NAME` to `WORDPRESS_DB_NAME=wordpress` form a variable we can set in the UI to a hardcoded value, the variable will not be removed in the UI:
![image](https://github.com/coollabsio/coolify/assets/122374094/6f4419f7-fd67-40f8-8c36-0166e6972e80)
-> Even after changing the variable to a hardcoded value, the environment variable remains in the UI even though it is no longer needed. I would expect this variable to be removed after a redeploy.

### Version

v4.0.0-beta.306

**Comment by Mortalife** [comment]
Same issue as is preventing supabase from running as described in: https://github.com/coollabsio/coolify/issues/2696
