### ISSUE TITLE
[Bug]: Build perfromance with dockerfiles and npm/yarn packages is very slow

### ISSUE THREAD

**Issue by peaklabs-dev** [coollabsio/coolify#2711]
### Description

See this thread for more details: https://discord.com/channels/459365938081431553/1227670703562559499 

### Minimal Reproduction (if possible, example repository)

Currently, building docker images or installing yarn/npm packages is very slow. Even the simplest packages can take up to 10 minutes on server specs 2cores and 4gb of ram even on better specs this can be a problem.

### Version

v4.0.0-beta.306

**Comment by brightkan** [comment]
I have a similar issue. In my case, it takes 1 full hour for Django and python to build.

**Comment by ltshv** [comment]
yeah, in my case git clone is too slow and it breaks connection with 8 err

**Comment by ari-party** [comment]
I don't experience the listed issues but I do notice that pnpm does not cache my dependencies.
My Dockerfile `pnpm install` command is the same as listed on the [pnpm wiki](https://pnpm.io/docker#example-1-build-a-bundle-in-a-docker-container)

**Comment by peaklabs-dev** [comment]
This is probably nixpacks related, and for caching dependencies I added a feature request: https://github.com/coollabsio/coolify/discussions/3610.
