### ISSUE TITLE
[Bug]: environment variables broken on 306, works on 296

### ISSUE THREAD

**Issue by Geczy** [coollabsio/coolify#2713]
### Description

constant degraded service, and unable to connect to db because incorrect password

### Minimal Reproduction (if possible, example repository)

try creating a new docker service with this yaml file pasted https://github.com/coollabsio/coolify/blob/next/templates/compose/supabase.yaml

### Version

306

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.
