### ISSUE TITLE
docker-compose run?

### ISSUE THREAD

**Issue by AlcoholicCoder** [coollabsio/coolify#2727]
### Description

Is there any way to run interactive shell with `docker-compose run -it xxx`?
I want to add login details for `tdlib`(Telegram Database Library) using interactive shell to store session in a `volume` specified in `docker-compose.yaml`.

I am using `server2` for my project. Coolify host is on a `server1`.

Looks like `server2` doesn't even have docker-compose installed.
When I `cd` into `/data/coolify/applications/{projectid}` it only contains `docker-compose.yaml` file but none of my source code is there.

### Minimal Reproduction (if possible, example repository)

`None`

### Exception or Error

`None`

### Version

v4.0.0-beta.306

**Comment by largeant** [comment]
I'm not certain it's the solution but did you try "docker compose" without the "-"?

**Comment by ari-party** [comment]
`Application > Command`?

**Comment by sukhcha-in** [comment]
Looks like you want to run specific container with `-it` and a specific `volume`.
Coolify will automatically build image for you based on your configuration.
Run `docker images` on your target server and find the image name you want to use.
Run `docker run -it -v {myvolume:/myvolume} {image_name}`

**Comment by AlcoholicCoder** [comment]
> Looks like you want to run specific container with `-it` and a specific `volume`. Coolify will automatically build image for you based on your configuration. Run `docker images` on your target server and find the image name you want to use. Run `docker run -it -v {myvolume:/myvolume} {image_name}`

Thank you. it worked!
