### ISSUE TITLE
[Feature]: Docmost Template

### ISSUE THREAD

**Issue by DeVoresyah** [coollabsio/coolify#2732]
### Description

I want a template for [Docmost](https://github.com/docmost/docmost) merged into this Coolify repo.
Suppose you can get a Docmost template working and merged I consider that the bounty is complete.

### Minimal Reproduction (if possible, example repository)

n/a

### Version

n/a

**Comment by alfinauzikri** [comment]
Please check my work @DeVoresyah at https://github.com/coollabsio/coolify/pull/2747

Thank you..

**Comment by DeVoresyah** [comment]
> Please check my work @DeVoresyah at #2747
> 
> Thank you..

you need to attempt first, the bounty is not detected

**Comment by DeVoresyah** [comment]
@ayntk-ai can you check this?

**Comment by alfinauzikri** [comment]
I already did attempt on the bounty @DeVoresyah

**Comment by ayntk-ai** [comment]
@DeVoresyah What do I need to check?

**Comment by DeVoresyah** [comment]
> @DeVoresyah What do I need to check?

test his template/pr

**Comment by ayntk-ai** [comment]
@DeVoresyah Looks good to me, have to wait for the maintainer to merge to fully say that it is working.

**Comment by DeVoresyah** [comment]
> @DeVoresyah Looks good to me, have to wait for the maintainer to merge to fully say that it is working.

yes, now just wait, @andrasbacsai can you take look on this / merge this PR ?

**Comment by andrasbacsai** [comment]
@DeVoresyah in v314, this will be released. Please send the bounty to @alfinauzikri when this is merged.

**Comment by alfinauzikri** [comment]
Thank you @andrasbacsai

**Comment by DeVoresyah** [comment]
> @DeVoresyah in v314, this will be released. Please send the bounty to @alfinauzikri when this is merged.

sure, as always~!

**Comment by DeVoresyah** [comment]
just want to inform @alfinauzikri  , that the bounty will be sent at the end of the month. I need to wait for approval from the finance.

**Comment by alfinauzikri** [comment]
Okay, that's fine @DeVoresyah .

Thank you..

**Comment by alfinauzikri** [comment]
Thank you @DeVoresyah :)
