### ISSUE TITLE
[Bug]: Can't setup coolify backup

### ISSUE THREAD

**Issue by Bechma** [coollabsio/coolify#2738]
### Description

I want to keep a backup of coolify instance, so I tried to add backup but I got an error after adding an automatic backup:

### Minimal Reproduction (if possible, example repository)

1. Fresh install coolify
2. Add a new server
3. Add a postgres database resource into coolify.
4. Go to settings, and try to add an "Instance Backup"

### Exception or Error

![image](https://github.com/coollabsio/coolify/assets/19294519/ad2dd427-bcc9-4874-8248-f87e9c75d545)

![image](https://github.com/coollabsio/coolify/assets/19294519/27370703-1b47-4ee2-8ca2-304ade07dea9)
Error: Cannot assign array to property App\Livewire\Project\Database\BackupEdit::$backup of type ?App\Models\ScheduledDatabaseBackup (View: /var/www/html/resources/views/livewire/settings/backup.blade.php)

### Version

v4.0.0-beta.306

**Comment by floberlin** [comment]
same issue here. i am no longer able to access the settings page. is there a quick fix for this?

**Comment by peaklabs-dev** [comment]
This issue should be resolved in the latest version. If you're still experiencing this issue, please reopen or create a new issue with updated details.
