### ISSUE TITLE
[Bug]: When creating a project that just has dragonflydb as a resource the resource doesn't show 

### ISSUE THREAD

**Issue by AnzeKop** [coollabsio/coolify#2740]
### Description

When making a new project and selecting dragonflydb as the only source it doesn't end up showing in the actual sources index.

If you add any other deployment alongside it then it does show the dragonfly deployment as well but standadlone it shows nothing - the inidividual /database/*** url still works, just doesn't show up on the index

### Minimal Reproduction (if possible, example repository)

Just create a new project and only use dragonflydb as the resource

### Version

v4.0.0-beta.306

**Comment by peaklabs-dev** [comment]
This issue has been fixed in the latest version.
