### ISSUE TITLE
[Bug]: Log output not displayed correctly

### ISSUE THREAD

**Issue by chris-si** [coollabsio/coolify#2744]
### Description

Hello,

I'd would be nice if the log view would correctly color the log output of services.

NestJS by default has different colors for different log levels so you can easily differentiate them but coolify doesn't seem to parse/display the log output correctly as only the raw text is displayed completely uncolored (also ';5;3m' is normally not displayed in the logs):

```
[Nest] 1  - 07/04/2024, 6:37:39 AM   ERROR ;5;3m[Main] This should be a red message
[Nest] 1  - 07/04/2024, 6:37:39 AM    WARN ;5;3m[Main] This should be a yellow message
[Nest] 1  - 07/04/2024, 6:37:39 AM     LOG ;5;3m[Main] This should be a green message
[Nest] 1  - 07/04/2024, 6:37:39 AM   DEBUG ;5;3m[Main] This should be a pink message
```
As a reference, this is what it should look like:
<img width="586" alt="image" src="https://github.com/coollabsio/coolify/assets/24972677/321f7148-d993-46d8-a396-463bea4af350">

### Minimal Reproduction (if possible, example repository)

1. Deploy [this repo](https://github.com/chris-si/nestjs-starter-logs) via public repo and use the Dockerfile option as build pack.
2. Take a look at the coolify service logs.

### Version

v4.0.0-beta.306

**Comment by peaklabs-dev** [comment]
This is more of a feature request as it has not been implemented yet. We will track the improvement of logs including color in this discussion: https://github.com/coollabsio/coolify/discussions/2618
