### ISSUE TITLE
[Bug]: Restart always triggers full redeployment on environment variable change

### ISSUE THREAD

**Issue by chris-si** [coollabsio/coolify#2745]
### Description

I have a service which is deployed via a Dockerfile.
If I add or change an environment variable (which is not a build variable!) and I click restart, the whole build is executed again even if a simple container restart would be sufficient.

### Minimal Reproduction (if possible, example repository)

1. Deploy [this repo](https://github.com/chris-si/nestjs-starter-logs) via public repo and use the Dockerfile option as build pack.
2. Add or change an arbitrary environment variable
3. Restart the service (the restart will trigger a redeployment though it is not necessary)

### Version

v4.0.0-beta.306

**Comment by chris-si** [comment]
But why even have build variables then? From my understanding those (with checked 'Build Variable' checkbox)  would be explicitly available during build time but not the other environment variables. At least I hope so, because I have environment variables which I don't want to be available during build time.

**Comment by alexzvn** [comment]
okay after some quick test, here is what i found:
| Environment | Present in build | Present in runtime |
| --- | --- | --- |
| Build var | ✅ | ✅ |
| Default var | ❌ | ✅ |

Turn out by checking `Build Variable`, coolify will tell docker build with your variables.

**Comment by chris-si** [comment]
Okay, that's good :) And kind of what i expected...
But it still makes a complete rebuild more or less unnecessary if only a 'normal' environment variable is added/modified/deleted.

**Comment by peaklabs-dev** [comment]
Yes this is true, currently the container is always rebuilt, we need a restart button that does not trigger a rebuild as this is not yet implemented and more of an improvement, please move tracking and discussion to the following GitHub discussions: https://github.com/coollabsio/coolify/discussions/3560
