### ISSUE TITLE
[Bug]: Delete server without validation

### ISSUE THREAD

**Issue by pReya** [coollabsio/coolify#2750]
### Description

I can't delete a server, which i accidentally added, because it seems that it needs to be validated before it can be deleted. I can't do either of those things, so the server is stuck in limbo :(

I think the delete option should be available, even when validation is still outstanding.

### Minimal Reproduction (if possible, example repository)

- Add server that's not working
- Try to delete server without succesfull validation

### Version

v4.0.0-beta.306

**Comment by CodeGeek04** [comment]
It does delete without validation, you just have to skin onboarding and you cal find all servers/delete them.

**Comment by pReya** [comment]
> It does delete without validation, you just have to skip onboarding and you can find all servers/delete them.

How? The delete button does not appear on unvalidated server (see screenshots – one shows a validated server, one shows an unvalidated server)

<img width="1082" alt="Screenshot 2024-07-06 at 22 14 40" src="https://github.com/coollabsio/coolify/assets/4677417/d91eeb32-f217-4c92-aae7-55fc429026c2">
<img width="1091" alt="Screenshot 2024-07-06 at 22 14 18" src="https://github.com/coollabsio/coolify/assets/4677417/c7307b15-0651-46f5-b26f-5bbe8cb8f8da">

**Comment by Xiloe** [comment]
Looking at your screenshot I can see that:
<img width="407" alt="image" src="https://github.com/coollabsio/coolify/assets/51050533/e54fa79f-9e04-4756-b3ca-92a988a8f83c">

You might have some random ressource on that server somehow, try to check if you have one, if you do you need to stop & delete them, then you should be able to delete the server, you shouldn't need to delete the environments though

**Comment by pReya** [comment]
> Looking at your screenshot I can see that: <img alt="image" width="407" src="https://private-user-images.githubusercontent.com/51050533/346795446-e54fa79f-9e04-4756-b3ca-92a988a8f83c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MDUwNjQsIm5iZiI6MTcyMDUwNDc2NCwicGF0aCI6Ii81MTA1MDUzMy8zNDY3OTU0NDYtZTU0ZmE3OWYtOWUwNC00NzU2LWIzY2EtOTJhOTg4YThmODNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDA1NTkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4Y2ZhMzZhMzQ4NmEwNmUxMjAyNTZkMjMyY2RiNDczMzQ2M2NjNmNmYjljNDlkODgyNDBkYzdmYjIyNjU5Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GE-yUbfYUXIidmSewKxFCtIpnjY1L2H4rHqPC6tPyEU">
> 
> You might have some random ressource on that server somehow, try to check if you have one, if you do you need to stop & delete them, then you should be able to delete the server, you shouldn't need to delete the environments though

This is the screenshot of the validated server. The other screenshot shows the unvalidated server (you'll see there's no delete option).

**Comment by pReya** [comment]
Sorry for the late response. I'm not entirely sure how I got to this state. I set up Coolify and then somehow did not finish the initial setup. When I came back to it, a couple of weeks later, I guess I manually added a new server, without the "Server 0" working properly, because I was under the assumption I can just delete it later.

**Comment by peaklabs-dev** [comment]
Please delete all resources on the server, you need to delete the Postgres DB that is on the server for the delete button to work on your remote server or in your case the afterwards added localhost server. If there is a resource, such as a DB in your case, the server cannot be deleted. You can move the DB to another server if you cannot delete the DB. If this does not work please reopen this issue.
