### ISSUE TITLE
[Bug]: Cancelling a deployment don't work when the "Build Server" is used.

### ISSUE THREAD

**Issue by yellowflx** [coollabsio/coolify#2761]
### Description

I have 3 servers (localhost = coolify instance, production, build).
Also have the resource on the "build" server from Github repo using Dockerfile as a Build Pack.
After the deployment has started, if the "Build server" is in use, it will not cancel by pressing the "Cancel" button.
When build is finished deploy also will happen.

### Minimal Reproduction (if possible, example repository)

1. Add server to be used as "Build Server"
2. Create Resource on different server using Dockerfile as a Build Pack
3. Check "Use a Build Server? (experimental)" under "Build" section
4. Start a Deployment
5. Click the "Cancel" button
6. Wait for build to end

When"Cancel" clicked:
![image](https://github.com/coollabsio/coolify/assets/63840433/4f31a332-0bd0-46cb-aeb4-17674669bf10)

After some time:
![image](https://github.com/coollabsio/coolify/assets/63840433/f1794c2d-66cc-4654-9567-305d8ced523a)

### Version

v4.0.0-beta.297

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.
