### ISSUE TITLE
[suggestion] automatically assign FQDN to applications on creation

### ISSUE THREAD

**Issue by dgc1980** [coollabsio/coolify#278]
settings page to define base FQDN for application e.g.   `coolify.mydomain.com` have this setup as a wildcard domain with your provider

option to specify http or https by default

application name gets autogenerated, in this case `Sacred Crimson Tapir`

automatically assign application name to `https://sacred-crimson-tapir.coolify.mydomain.com` 

if application name gets change, automatically update the automatic FQDN to  the new name

**Comment by sphinxc0re** [comment]
IMHO it doesn't even have to be the domain on which coolify is installed. There should just be a setting named "Wildcard domain" or something. On setting it, the wildcard cert could be requested from LetsEncrypt.
