### ISSUE TITLE
Coolify randomly crashes RaspberryPi 4B+

### ISSUE THREAD

**Issue by moshechaikin** [coollabsio/coolify#2781]
### Description

Coolify crashing raspberry pi randomly 

### Minimal Reproduction (if possible, example repository)

Coolify running on a RaspberryPi 4b+ with 2GB RAM, with swap added via the swap file. 

Running a fairly simple nodejs app with resource limits set on my project, and the entire system randomly crashes. I have cloudflared running and that also goes down entirely. A restart of the system only fixes things temporarily. 

### Version

4.0.0-beta.306

**Comment by wadedesign** [comment]
i run RaspberryPi cluster for the extra servers - i don't think your RaspberryPi is strong enough.

**Comment by moshechaikin** [comment]
> i run RaspberryPi cluster for the extra servers - i don't think your RaspberryPi is strong enough. 

Is this due to a lack of RAM or CPU power? What rpi(s) are you using?

**Comment by wadedesign** [comment]
> > i run RaspberryPi cluster for the extra servers - i don't think your RaspberryPi is strong enough. 
> 
> Is this due to a lack of RAM or CPU power? What rpi(s) are you using?

So I use 3 rpi(5) - so it could be the lack of ram, as you have 4 cores in a pi, so definitely would get more rpi's with better ram, at most 4GB for each pi

**Comment by moshechaikin** [comment]
> > > i run RaspberryPi cluster for the extra servers - i don't think your RaspberryPi is strong enough. 
> > 
> > Is this due to a lack of RAM or CPU power? What rpi(s) are you using?
> 
> So I use 3 rpi(5) - so it could be the lack of ram, as you have 4 cores in a pi, so definitely would get more rpi's with better ram, at most 4GB for each pi 

Weird because I've added 5gb of swap, I'd think that'd solve it. Under normal use, my rpi seems to be only using 50% of RAM.

**Comment by wadedesign** [comment]
> > > > i run RaspberryPi cluster for the extra servers - i don't think your RaspberryPi is strong enough. 
> > > 
> > > Is this due to a lack of RAM or CPU power? What rpi(s) are you using?
> > 
> > So I use 3 rpi(5) - so it could be the lack of ram, as you have 4 cores in a pi, so definitely would get more rpi's with better ram, at most 4GB for each pi 
> 
> Weird because I've added 5gb of swap, I'd think that'd solve it. Under normal use, my rpi seems to be only using 50% of RAM. 

So swap memory is slow compared to actual ram, so even tho only 50% is used, swap under heavy loads or close to it can decrease performance, and using swap, could max out your cpus would cause it to crash and such.  You ever htop in, and watch the cpus?

**Comment by moshechaikin** [comment]
> > > > > i run RaspberryPi cluster for the extra servers - i don't think your RaspberryPi is strong enough. 
> > > > 
> > > > Is this due to a lack of RAM or CPU power? What rpi(s) are you using?
> > > 
> > > So I use 3 rpi(5) - so it could be the lack of ram, as you have 4 cores in a pi, so definitely would get more rpi's with better ram, at most 4GB for each pi 
> > 
> > Weird because I've added 5gb of swap, I'd think that'd solve it. Under normal use, my rpi seems to be only using 50% of RAM. 
> 
> So swap memory is slow compared to actual ram, so even tho only 50% is used, swap under heavy loads or close to it can decrease performance, and using swap, could max out your cpus would cause it to crash and such.  You ever htop in, and watch the cpus? 

Yes, I have. The CPUs spiked when deploying, but were stable afterwards. But coolify still randomly crashes my rpi entirely, even rendering cloudflared useless.

**Comment by justserdar** [comment]
I'm using a RPi 5 and a RPi 4, both Pi's work perfect 24/7 with coolify, I also have a w2 which is arguably worse/unusable. The RPi5/4 are 8gb ram models. Note that both are out of heap memory after installing a second project* on them. As local dev area's its amazing.

*I mainly run full stack Nuxt projects running server side on the hosts (rpi).

**Comment by peaklabs-dev** [comment]
I think this problem occurs because SD cards are unstable or you are pushing your CPU too much with swap space. I have added some helpful debugging steps to the docs which will be available soon.
