### ISSUE TITLE
Safety concerns regarding addition of Glances

### ISSUE THREAD

**Issue by noahstreller** [coollabsio/coolify#2790]
### Description

Recently, "Glances" (not to be confused with "Glance") was added to the Coolify resource templates. However, I believe that verbose system monitoring information should not be exposed to the public. I see that there is a sslip.io domain bound to it by default, thus I assume that it's "supposed" to be public.

I also don't know about a feature that allows us to protect deployments using Coolify authorization (that would be a really nice feature by the way).

Should I be wrong, don't hesitate to correct me :)

### Minimal Reproduction (if possible, example repository)

1. Add Glances as a resource 
2. Deploy using the default configuration 
3. Everyone can access the exposed information

### Version

v4.0.0-beta.307

**Comment by LEstradioto** [comment]
Ive just glanced 😄 on the Glances docs and found [this](https://glances.readthedocs.io/en/latest/docker.html#how-to-protect-your-dockerized-server-or-web-server-with-a-login-password)

It seems to require additional manual steps only. Indeed would be nice if Coolify had a built-in thing

Or could use proxy to allow only your IP to a specific service, like using Traefik [IPAllowlist](https://doc.traefik.io/traefik/middlewares/http/ipallowlist/), but this would need more effort on the docker-compose with manual adding labels and testing

**Comment by noahstreller** [comment]
@LEstradioto Thanks for your answer! 

I did see this in the docs too, however it requires a secret file in the docker compose or access to the working directory.

![image](https://github.com/user-attachments/assets/47c4a8da-1ee4-4dda-98df-05c4df450042)

I am unaware of Coolifys support for docker compose setups which require an additional environment (except with git, but you don't want to save your password in git right?). If you know a way to deploy docker compose setups which are not standalone, please let me know!

![image](https://github.com/user-attachments/assets/4a409867-7044-4eec-9e05-0395df06bec4)

**Comment by LEstradioto** [comment]
no, I mean, you could setup manually:
- install Glances
- ssh into your server
- runs that docker setup stuff `glances -s password`
- copy the password to a folder in your server
- then finally, stop Glances service, Edit docker compose and add those `secret` lines

Probably tricky to point the right path but should work

**Comment by peaklabs-dev** [comment]
I would just use basic auth in front of Glances or do it like LEstradioto said.
