### ISSUE TITLE
Error while building production bundle

### ISSUE THREAD

**Issue by Shamaani** [coollabsio/coolify#28]
First of all, thanks for a great project! 
I get this error while installing. 
The website gives 404.

 
![Screenshot 2021-04-10 at 12 13 43](https://user-images.githubusercontent.com/26260515/114264924-76dafe00-99f6-11eb-9ad6-7a6318e04014.png)

**Comment by andrasbacsai** [comment]
Thank you for trying it out!

The line with the `Killed` looks like there was not enough memory to run the `pnpm build` command. 

How much memory does the server have?

**Comment by Shamaani** [comment]
That was the problem, thank You! I had the cheapest Digital Ocean server - 1GB memory and 25gb SSD. Updated it to 2gb memory and 50gb ssd.

**Comment by andrasbacsai** [comment]
I'll think about what I can do about it. 🙂

**Comment by andrasbacsai** [comment]
The current stack does not allow publishing a prebuild docker image of Coolify, which allows skipping the building process (which needs memory). So I close this for now. 

I will add this detail to the upcoming documentation.
