### ISSUE TITLE
[Bug]: Container labels contain Traefik ones even if the Server proxy is Caddy

### ISSUE THREAD

**Issue by lorenzomigliorero** [coollabsio/coolify#2801]
### Description

I have one server with Caddy as a proxy, but all my resources (no matter the build pack) contain labels for both Traefik and Caddy. Only the caddy ones should be generated. I'm unsure how tricky it is to solve, but it'd be a nice addition.

### Minimal Reproduction (if possible, example repository)

- Create a server using Caddy as a proxy
- Create a new resource, no matter the build-pack
- The Container Labels includes both Traefik and Caddy

<img width="759" alt="Screenshot 2024-07-11 at 20 16 25" src="https://github.com/coollabsio/coolify/assets/4406419/e4b1b149-bbb0-410d-8598-705253110714">

### Version

v4.0.0-beta.307

**Comment by JuanxCursed** [comment]
+1 same issue here (getting error 502)

**Comment by picocodes** [comment]
I also get error 502 when I deploy a Node JS app. Healthcheck is working fine.

I'm using Caddy.

The option to switch back to Traefik is disabled so I can't test on Traefik.

**Comment by JuanxCursed** [comment]
This setup has quite unexpected behavior.
I have three applications (Nuxt using SSR with `node .output/server/index.mjs`). 
Two of these applications work perfectly, and just one is causing issues. 
*All three have the exact same setup.*
This one is causing issues and doesn't work either with Static build + Nginx or with Node.

THE ONLY difference between them is the proxy port (each one has a unique available port) and the subdomain. 

Did you guys make some progress within this subject?

**Comment by peaklabs-dev** [comment]
This has been addressed and if you want you can generate labels only for the specific proxy you are using, the only downside to this is that you will have to manually regenerate the labels for each source if you switch proxies and have this option enabled. Note that there is no harm in having both traffic and caddy labels, it is just not as clean as just having one.
The option is under Server > Proxy and then:
<img width="406" alt="image" src="https://github.com/user-attachments/assets/1e091e13-f5ce-463c-9a09-5b2f08de04b9">
