### ISSUE TITLE
[Bug]: Default Redirect 404 doesn't redirect on HTTPS

### ISSUE THREAD

**Issue by Xiloe** [coollabsio/coolify#2815]
### Description

The `Default Redirect 404` option doesn't work on HTTPS, only http.

![image](https://github.com/user-attachments/assets/9d15cbe5-8697-4f27-8bbf-b44ca3f8c5a2)

![image](https://github.com/user-attachments/assets/fe4947fe-d4d2-4fcf-8c20-3be43cb9e494)

it does redirect fine on http

### Minimal Reproduction (if possible, example repository)

1. Set up the Default Redirect 404
2. Try a random subdomain with https

### Exception or Error

N/A

### Version

v4.0.0-beta.309

**Comment by stefanofusai** [comment]
I've had the same issue for a while, I'm currently on v4.0.0-beta.319
The redirect works fine only if I set my Cloudflare SSL rule to Flexible
All other Cloudflare SSL rules, including Strict (which is what I'm using), will show the default 404 page

<img width="371" alt="image" src="https://github.com/user-attachments/assets/973c55a6-5960-483d-9b81-c93f72bffafd">
<img width="349" alt="image" src="https://github.com/user-attachments/assets/6b850a2d-503c-433f-b289-22f9cbd197e4">

**Comment by andrasbacsai** [comment]
Are you using Traefik v2 or v3?

**Comment by stefanofusai** [comment]
> Are you using Traefik v2 or v3?

I'm using Hosted Coolify with Traefik v2.10 (I'm unsure how to upgrade to v3)

**Comment by Xiloe** [comment]
> Are you using Traefik v2 or v3?

didn't touch traefik at all, I don't even know how I'd get that info from coolify, so I guess whatever the default is

**Comment by peaklabs-dev** [comment]
This can be fixed by upgrading traffic. You can follow this guide at https://github.com/coollabsio/coolify/discussions/3044#discussioncomment-10914266 to do so - **Be aware that all resources will be offline shortly until the proxy is restarted.**
