### ISSUE TITLE
[Bug]: Regular ssh timeouts during deployments

### ISSUE THREAD

**Issue by kyelewis** [coollabsio/coolify#2834]
### Description

When deploying, there are regular SSH timeouts to github.com.

Sometimes the deployments will succeed with no issues multiple times in a row, sometimes they will fail multiple times in a row.

Fetching from github from the host OS never fails, nor does it take an extended period of time.

Not quite sure how to troubleshoot this one.

### Minimal Reproduction (if possible, example repository)

- Create a project
- Deploy

### Exception or Error

[2024-Jul-15 00:38:02.831207]

[COMMAND] docker run -d --network coolify --name jk8ssgs --rm -v /var/run/docker.sock:/var/run/docker.sock ghcr.io/coollabsio/coolify-helper:latest
[OUTPUT]
02dd8465df62bbd3f0c075679ba70d70f0f8c20749fc437cb5b6c491a4e68c02

[2024-Jul-15 00:38:35.588271]

[COMMAND] docker exec jk8ssgs bash -c 'GIT_SSH_COMMAND="ssh -o ConnectTimeout=30 -p 22 -o Port=22 -o LogLevel=ERROR -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i /root/.ssh/id_rsa" git ls-remote git@github.com:org-replaced/package-name-replaced/widgets.git main'
[OUTPUT]
ssh: connect to host github.com port 22: Operation timed out

[2024-Jul-15 00:38:35.595987]

[COMMAND] docker exec jk8ssgs bash -c 'GIT_SSH_COMMAND="ssh -o ConnectTimeout=30 -p 22 -o Port=22 -o LogLevel=ERROR -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i /root/.ssh/id_rsa" git ls-remote git@github.com:org-replaced/package-name-replaced.git main'
[OUTPUT]
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

[2024-Jul-15 00:38:35.753725] Oops something is not okay, are you okay? 😢

[2024-Jul-15 00:38:35.758529] ssh: connect to host github.com port 22: Operation timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

[2024-Jul-15 00:38:35.763590] Deployment failed. Removing the new version of your application.

### Version

4.0.0-beta.313

**Comment by peaklabs-dev** [comment]
Can you please update to the latest version of Coolify and recheck and if possible provide more detailed reproduction steps? Thank you.

**Comment by peaklabs-dev** [comment]
Due to inactivity, we're closing this issue.
