### ISSUE TITLE
[Bug]: Docker Compose deployments broken from latest Coolify update

### ISSUE THREAD

**Issue by maamokun** [coollabsio/coolify#2841]
### Description

When attempting to deploy a Docker Compose app on my newly updated Coolify instance (v4.0.0-beta.314), I get the error "unknown flag: --policy". I'm guessing this has something to do with the new "Add pull policy to always to docker compose based deployments" part of the update. When restarting a previously deployed Docker Compose app on my instance, it fails with the same error. This new pull policy isn't covered in the documentation, so I don't know if this is a bug or a problem on my end.

### Minimal Reproduction (if possible, example repository)

Deploy any Docker COmpose on the latest Coolify version, or attempt to restart a previously deployed app from an older version

### Exception or Error

**Attempt to deploy a new app**
```
Saved configuration files to /data/coolify/services/acs884g.
Creating Docker network.
Starting service.
Pulling images.
unknown flag: --policy
```

**Attempt to restart a previously working app**
![画像_2024-07-16_005302593](https://github.com/user-attachments/assets/51557615-d201-4a87-9d1d-222489ead594)

### Version

v4.0.0-beta.314

**Comment by maamokun** [comment]
UPDATE: I was able to fix this after updating Docker Compose on the affected node. I think it would be useful to write this somewhere in the update documentation.

Sorry for the inconvenience!

**Comment by carbontwelve** [comment]
Do you know what version of Docker Compose you updated from and to?

**Comment by maamokun** [comment]
It was from v2.21.0 to v2.28.1.

**Comment by Lodimup** [comment]
I have fresh installed coolify yesterday. It probably auto updated to coolify:4.0.0-beta.314. Now I have the same problem.

**Comment by maamokun** [comment]
I think that it would be a better idea to have this compose policy be optional, or be able to have a custom start command for starting the compose containers.

**Comment by honeyhead** [comment]
same error

**Comment by jugglingjsons** [comment]
I was in the same shoes after updating from v3 to v4.
What I did to resolve was updating docker compose, depending on how it was installed you will need to do different things to make it work but here's one approach:
1. ssh into your server
2. `which docker compose`
3. cd into the resulting directory
4. pull new compose ` curl -SL https://github.com/docker/compose/releases/download/v2.28.1/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose` - adjust the version for your platform
5. verify you have actually updated it `./docker-compose version` or `docker compose version` - preferably both
6. enjoy running deployments again

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.
