### ISSUE TITLE
[Bug]: Error thrown when deploying tags

### ISSUE THREAD

**Issue by hugocxl** [coollabsio/coolify#2843]
### Description

When trying to deploy projects using tags (in the "Tags" section), an error is thrown.

### Minimal Reproduction (if possible, example repository)

1. Navigate to the "Tags" section
2. Select any tag for any of the projects
3. Click "Redeploy All" 

=> An error is thrown

<img width="999" alt="Screenshot 2024-07-15 at 19 39 40" src="https://github.com/user-attachments/assets/64afbe54-2f61-4bd2-9506-09d81ef00eb4">

### Exception or Error

Error: Class "App\Http\Controllers\Api\Deploy" not found

### Version

v4.0.0-beta.314

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.

**Comment by hugocxl** [comment]
Thanks @andrasbacsai! and thank you for this amazing product too 🙏
