### ISSUE TITLE
[Bug]: Cannot define domain for service when deploying with docker-compose option

### ISSUE THREAD

**Issue by mehonja** [coollabsio/coolify#2845]
### Description

After or before deploying with docker-compose i am unable to set a domain, generated or custom.

### Minimal Reproduction (if possible, example repository)

- Have an docker-compose file with 2 services
- Create a deployment using the docker-compose option
- After or before the deployment add the domain
- Click save, then reload
- The domain is gone and not accessible 

### Version

v4.0.0-beta.314

**Comment by peaklabs-dev** [comment]
Please provide me with the sample compose file so I can better reproduce this.

**Comment by tesar27** [comment]
Same problem
