### ISSUE TITLE
Centos compatibility

### ISSUE THREAD

**Issue by elperi** [coollabsio/coolify#285]
It will be great to install Coolify on CentOS. Now it is not possible.

**Comment by dgc1980** [comment]
I tested on a fresh install of CentOS 8 and had to the following to install it, I will see if I can debug the issue to be pushed into the installation script

`yum install -y wget`

`wget https://get.coollabs.io/coolify/install.sh`

`cat install.sh | bash /dev/stdin -y`

fails, need to manually start docker then start the install script again

`systemctl start docker`

`cat install.sh | bash /dev/stdin -y`

**Comment by dgc1980** [comment]
update, ok the docker engine just needs to be started after being installed via the install script, this should fix the issue with installing on CentOS 8

**Comment by dgc1980** [comment]
changes to the installation script as follows will allow installation via CentOS 8 without error

```
# Check docker version
if [ ! -x "$(command -v docker)" ]; then
    if [ $YES -eq 1 ]; then
        echo "Installing Docker..."
        sh -c "$(curl --silent -fsSL https://get.docker.com)"
        systemctl restart docker
    else
        while true; do
            read -p "Docker Engine not found, should I install it automatically? [Yy/Nn] " yn
            case $yn in
            [Yy]*)
                echo "Installing Docker..."
                sh -c "$(curl --silent -fsSL https://get.docker.com)"
                systemctl restart docker
                break
                ;;
            [Nn]*)
                echo "Please install docker manually and update it to the latest, but at least to $DOCKER_MAJOR.$DOCKER_MINOR"
                exit 0
                ;;
            *) echo "Please answer Y or N." ;;
            esac
        done
    fi
fi
```

note the included `systemctl restart docker` after both installation of docker

**Comment by elperi** [comment]
Great. It works.

**Comment by andrasbacsai** [comment]
Added these changes to the official script.
