### ISSUE TITLE
[Bug]:  Coolify Link not opening after installation on rasberry pi 4b

### ISSUE THREAD

**Issue by SarikAnwar01** [coollabsio/coolify#2850]
### Minimal Reproduction (if possible, example repository)

it gives link but the link dont work 

### Version

OS: debian 12 Coolify version: 4.0.0-beta.314

**Comment by sayinmehmet47** [comment]
I face the same issue, i installed the coolify to my helzner machine successfully  and it gave me a link.

Congratulations! Your Coolify instance is ready to use.

Please visit http://5.78.xx.xxx:8000 to get started.

But when i click it does not open it , i gave access to it but still not reachable 

sudo ufw enable
sudo ufw allow 8000/tcp

**Comment by luccabassoli** [comment]
Is port 8000 open for connection? I had this problem, in the company where I used the doors were closed, I had to open them

**Comment by d3lac** [comment]
I have the exact same issue. Uninstall ufw and restarted my machine to make coolify work.

**Comment by peaklabs-dev** [comment]
For Rasberry PI in local network you need to access it over Private IP, so I will add Private IP output to the installer to simplify Rasberry PI installation. Ofc on a cloud server you need to set up firewall rules according to the docs.
