### ISSUE TITLE
[Bug]: Plane Service can not upload images

### ISSUE THREAD

**Issue by action-simon** [coollabsio/coolify#2860]
### Description

When you try to upload images, for example in an issue description, I can see my uploaded image for a split-second with a loading spinner, and then it disappears. Default install, nothing has been modified.

### Minimal Reproduction (if possible, example repository)

- Add the Plane Service
- Create an Account
- Create a project
- Create an issue
- Press / and select Image
- It will appear for a split second
- Gone

### Version

v4.0.0-beta.315

**Comment by andrasbacsai** [comment]
I can confirm this issue. It is some configuration related to Plane.

Anyone would like to look into this?

**Comment by action-simon** [comment]
Api logs, some credentials are missing in the configuration?

`2024-07-19T08:17:18.001511700Z ERROR 2024-07-19 08:17:18,001 exception_logger 117 130997557816120 Unable to locate credentials`
`2024-07-19T08:17:18.026212368Z ERROR 2024-07-19 08:17:18,025 log 117 130997562059576 Internal Server Error: /api/workspaces/xxx/file-assets/`
`2024-07-19T08:17:18.026971598Z xxx.xxx.xxx.xxx:xxxxx - "POST /api/workspaces/xxx/file-assets/ HTTP/1.1" 500`

**Comment by MrAlexand0r** [comment]
Probably something wrong with the Minio Instance, I can look into it when I find the time. 😃

**Comment by MrAlexand0r** [comment]
Until the pull request https://github.com/coollabsio/coolify/pull/2903 is merged and released you can fix it yourself by setting the AWS env properties to the minio admin user and then restart the service.
`` 
    - AWS_ACCESS_KEY_ID=<minio admin user>
    - AWS_SECRET_ACCESS_KEY=<minio admin password>
```

**Comment by graphiostudio** [comment]
Hi @MrAlexand0r thanks for this. It's working on uploading like your screenshot but it doesn't show the images uploaded.  There's still a GET error. Do you have this issue?
![image](https://github.com/user-attachments/assets/f090bf14-2041-4a18-b26c-66c8a9116ad5)

**Comment by andrasbacsai** [comment]
> Hi @MrAlexand0r thanks for this. It's working on uploading like your screenshot but it doesn't show the images uploaded. There's still a GET error. Do you have this issue? ![image](https://private-user-images.githubusercontent.com/88828443/350883524-f090bf14-2041-4a18-b26c-66c8a9116ad5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2Mzc2MDQsIm5iZiI6MTcyMTYzNzMwNCwicGF0aCI6Ii84ODgyODQ0My8zNTA4ODM1MjQtZjA5MGJmMTQtMjA0MS00YTE4LWIyNmMtNjZjOGE5MTE2YWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDA4MzUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5NTVkMmJhOWU3YmNhYmVjNjg4NTgxNjA0YTMxMTY0NzA5MjIzZjU5NjEwMDUyOGY5ODk2MjNmMDQzMjQ3NDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N54WNkOa5WWGJQs3obMq8rZPoFvaCvVSesugiNSRa08)

Yes, it is still happens. Some environment variables are not set (for NextJS, so the UI?). Unsure.

**Comment by MrAlexand0r** [comment]
> Hi @MrAlexand0r thanks for this. It's working on uploading like your screenshot but it doesn't show the images uploaded. There's still a GET error. Do you have this issue? ![image](https://private-user-images.githubusercontent.com/88828443/350883524-f090bf14-2041-4a18-b26c-66c8a9116ad5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MzkxMTQsIm5iZiI6MTcyMTYzODgxNCwicGF0aCI6Ii84ODgyODQ0My8zNTA4ODM1MjQtZjA5MGJmMTQtMjA0MS00YTE4LWIyNmMtNjZjOGE5MTE2YWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDA5MDAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyYTE4YTg2MWMwYWE1Njg3ZmVmZGFkYWNmNjFmMzI0MjIxMTE2NGUyMmIwYWQxZDljMWZjYTg0OWU5OWQ5ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y9aFtYKxh1k1IXohvpT2egomvVvVvI0-JZ-VKxQMjNQ)

You are right, that was an oversight on my part, 
While plane is now able to access the minio instance for uploading the data, it uses the wrong URI for fetching the data.
I will look into it and check if I can do something about it

**Comment by dev-mantas** [comment]
I found this whilst looking into it, https://github.com/makeplane/plane/issues/2661, I set the 

`  api:
    environment:
      - 'WEB_URL="CHANGE"'
  `
  
 This updates the URL prefix for images.
 
 However its 404 not found I think there is some adjust that might need to be made in the nginx conf
 
Thats what it says in their .env.example file in source code
 `
# AWS Settings
AWS_REGION=""
AWS_ACCESS_KEY_ID="access-key"
AWS_SECRET_ACCESS_KEY="secret-key"
AWS_S3_ENDPOINT_URL="http://plane-minio:9000"
# Changing this requires change in the nginx.conf for uploads if using minio setup
AWS_S3_BUCKET_NAME="uploads"
# Maximum file upload limit
FILE_SIZE_LIMIT=5242880`

**Comment by dev-mantas** [comment]
I did some research into this and found this [https://github.com/makeplane/plane/issues/2661](url),
Need to change
`  api:
    environment:
      - 'WEB_URL=urlhere'`
 In the compose file and this changes the prefix of the image routes.
However this just points to 404
I found this in the .env.example on Plane source

`# AWS Settings
AWS_REGION=""
AWS_ACCESS_KEY_ID="access-key"
AWS_SECRET_ACCESS_KEY="secret-key"
AWS_S3_ENDPOINT_URL="http://plane-minio:9000"
# Changing this requires change in the nginx.conf for uploads if using minio setup
AWS_S3_BUCKET_NAME="uploads"
# Maximum file upload limit
FILE_SIZE_LIMIT=5242880`

If we change the access point need to also update the nginx.conf? Not sure how to continue from there.

**Comment by andrasbacsai** [comment]
Thank you. I found the issue. It was a missing env variable in the `proxy` service in Plane. Now image uploads will work!

**Comment by action-simon** [comment]
Hello, I can confirm it's working with the updated file!

**Comment by jocubeit** [comment]
What do we need to do for an existing running service - I don't want to lose all the issues and projects history and start again?

**Comment by action-simon** [comment]
> What do we need to do for an existing running service - I don't want to lose all the issues and projects history and start again?

You can copy paste the file https://github.com/coollabsio/coolify/blob/next/templates/compose/plane.yaml by clicking on edit compose file. Possibly you have to modiy your environment variables, I have no idea if they are being updated by saving the new compose file, as I added the missing aws variables manually before.

**Comment by dev-mantas** [comment]
@action-simon 

I asked Andras about when the template is updated if the service automatically updates and he said no.

@jocubeit You can change the variables in the docker-compose file yourself manually.

`x-app-env:
  environment:
    - 'WEB_URL=${SERVICE_FQDN_PLANE}'
    - 'DEBUG=${DEBUG:-0}'
    - 'CORS_ALLOWED_ORIGINS=${SERVICE_FQDN_PLANE}'
    `

 `    environment:
      - SERVICE_FQDN_PLANE
      - FILE_SIZE_LIMIT=${FILE_SIZE_LIMIT:-5242880}
      - BUCKET_NAME=${BUCKET_NAME:-uploads}
     `


   `- APP_BASE_URL=${SERVICE_FQDN_PLANE}`

**Comment by action-simon** [comment]
> @action-simon
> 
> I asked Andras about when the template is updated if the service automatically updates and he said no.

Makes sense, as it could break things if you automatically update projects. However I am not sure if you are talking about a Coolify Upgrade or editing the compose file as I did, I can see the missing entries like BUCKET_NAME have been added by doing that.

![image](https://github.com/user-attachments/assets/6b5f960f-1364-40c4-9d6b-c0ec01c7a5ae)

**Comment by jocubeit** [comment]
Thanks @dev-mantas and @action-simon. Much appreciated.
