### ISSUE TITLE
[Bug]: Validation failed with Create (Private - Deploy Key)

### ISSUE THREAD

**Issue by cheskoxd** [coollabsio/coolify#2872]
### Description

I was trying to create a new Application with the API [Using a private deploy key](https://coolify.io/docs/api-reference/applications/create-private--deploy-key) but I keep getting the same error message about the `private_key_uuid` when trying to create the application.

I see that is required [here](https://github.com/coollabsio/coolify/blob/c37398af7287bf7502bc5802b718a94bd58e925d/app/Http/Controllers/Api/ApplicationsController.php#L318), but I couldn't find anything else

### Minimal Reproduction (if possible, example repository)

0. Get Private Key from my server
1. Get the Server UUID with [endpoint ](https://coolify.io/docs/api-reference/servers/list)
2. Get the Project UUID with [endpoint ](https://coolify.io/docs/api-reference/projects/list)
3. Create a new Enviroment called "production"

The final body is:
```json 
{
    "project_uuid": "oc44kwg",
    "environment_name": "production",
    "server_uuid": "fgg8w0g",
    "git_branch": "main",
    "git_repository": "git@github.com:myrepo.git",
    "ports_exposes": "3000",
    "build_pack": "dockerfile",
    "name": "test123"
}
```
Send a post request to [applications/private-deploy-key](https://coolify.io/docs/api-reference/applications/create-private--deploy-key) with the Authentication Header

### Exception or Error

If I leave the private_key_uuid
```json
 {
    "message": "Validation failed.",
    "errors": {
        "private_key_uuid": [
            "This field is not allowed."
        ]
    }
}
```
if I remove the private_key_uuid
```json 
{
    "message": "Validation failed.",
    "errors": {
        "private_key_uuid": [
            "This field is required."
        ]
    }
}
```

### Version

v4.0.0-beta.315

**Comment by mtkgeek** [comment]
Already fixed. Same as #2874

**Comment by andrasbacsai** [comment]
Yes, it should be fixed. Re-open it if not.
