### ISSUE TITLE
[Bug]: Bind directory volume in a docker compose resource incorrectly shows up as a file mount

### ISSUE THREAD

**Issue by ebrearley** [coollabsio/coolify#2873]
### Description

Bind volumes in a new docker compose resource show up as a file mount in the Storages tab.

Given this shouldn't be a file, it is very tempting to click on "Convert to directory". Doing so will remove the directory and all of it's contents, and recreate a new one with the permissions that Coolify is running in, which is root. The user will loose all data in the mapped directory. Something that happened to me yesterday.

If you refresh page while on the Storages tab, the mount is shown correctly as a directory mount. 

Screen recording of reproducing this scenario:
https://github.com/user-attachments/assets/073451e7-45c9-4ebc-9461-f5f14bc9794b

### Minimal Reproduction (if possible, example repository)

1. create a directory on the host with some test content
```
$ mkdir /mount-test
$ touch /mount-test/test.txt
```

2. create a simple docker-compose resource with a service that binds the host directory to the container. I used this `docker-compose.yaml`:
```
services:
  nginx:
    image: nginx
    volumes:
      - /mount-test:/mount-test
```
 
3. before starting the container, review storages by clicking on the Storages tab.

### Exception or Error

See that the directory mount is listed as a file mount.

### Version

v4.0.0-beta.315

**Comment by andrasbacsai** [comment]
The next version will have a fix for this. Coolify already detects if a path is a dir or file, just not set it properly. In the next version it will.

**Comment by ulysse-lacour** [comment]
I have the same problem, should we just ignore the warnings and not convert it to directory within storage ?
Making coolify erase and change permissions on a directory seems to break the permissions and prevent things like Duplicati to access access some folders.
