### ISSUE TITLE
[Bug]: API endpoint for deploying applications via github deploy key doesn't work

### ISSUE THREAD

**Issue by mtkgeek** [coollabsio/coolify#2874]
### Description

When you use the defined schema it returns
`{"message":"Validation failed.","errors":{"private_key_uuid":["This field is not allowed."]}}  `
removing this field returns `{"message":"Validation failed.","errors":{"private_key_uuid":["This field is required."]}}`

Plus the destination_uuid and server_uuid seem to only accept the same value.

### Minimal Reproduction (if possible, example repository)

send a request to the `applications/private-deploy-key` endpoint

### Version

v4.0.0-beta.315

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.
