### ISSUE TITLE
feature: setting up deploys using tags

### ISSUE THREAD

**Issue by jesperordrup** [coollabsio/coolify#288]
Would be very useful if we could control how to deploy more. Examples:

    All commits tagged with test-yyyymmdd or live-yyyymmdd are deployed to the respective environment using github actions

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
