### ISSUE TITLE
Create a health check.

### ISSUE THREAD

**Issue by matheusfenolio** [coollabsio/coolify#289]
Create a health check that could restar the application in case it goes down. 

Awesome project!

**Comment by Yurgeman** [comment]
You can use the uptime kuma service. And set up notifications in the messenger

<img width="1669" alt="Снимок экрана 2022-04-06 в 17 17 49" src="https://user-images.githubusercontent.com/7249668/161996049-1f278a38-5d90-439c-b822-ef7905c6799b.png">

**Comment by matheusfenolio** [comment]
@Yurgeman Thanks for suggesting it! I've being using Uptime Kuma which is an incredible one, but I want to restart automatically my application pod if my health check receives something wrong. e.g. Expose `/health` endpoint in my container and make Coolify call it each 10 seconds. If it receives something different from `200`, then restart the pod. I don't know if Coolify has something to integrate with Kuma, would be awesome as well.

**Comment by Flexicon** [comment]
Ditto on this one.

I think this could easily be solved once the Kubernetes destination is implemented since that has health checks baked in.

**Comment by andrasbacsai** [comment]
It is available in v4.

I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
