### ISSUE TITLE
[Bug]: Volumes erased on deployment when Preserve Repository is flagged

### ISSUE THREAD

**Issue by lorenzomigliorero** [coollabsio/coolify#2897]
### Description

I was testing the new _Preserve Repository During Deployment is flagged_, and I noticed this bug.
When this flag is active, the volumes get erased when a new deployment is triggered.
I wasn't sure if it was a Coolify or Verdaccio bug, but I could reproduce the issues with different repos, and on my local machine, the volume content persists across deployments.

### Minimal Reproduction (if possible, example repository)

- Create a new Public Repository resource
  - **Repo URL**: https://bitbucket.org/lorenzomigliorero/docker-compose-git-issue
  - **Build Pack**: docker compose
  - **Docker Compose Location**: /docker-compose.yml
- Load docker compose _(sometimes it fails first, and then it works the second time, maybe related?)_
- Flag _Preserve Repository During Deployment_
- Deploy
- SSH Into the server, and check the content of the storage folder `ls /data/coolify/applications/{UUID}/storage`
- Click Redeploy
- The storage folder is now empty `ls /data/coolify/applications/{UUID}/storage` 

UPDATE:

Sometimes, the second deployment didn't cancel the volumes, but the third, yes. There are probably some race conditions involved here.

### Version

317

### Cloud?

- [ ] Yes
- [X] No

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.

Also:
As Coolify cannot determine if a volume mount from the host (if it does not exists) is a dir or file and you do not use the special `content` [property](https://coolify.io/docs/knowledge-base/add-a-service#create-a-file-with-content) in the compose file, it will create a directory by default.
