### ISSUE TITLE
[Bug]: Resource limit error

### ISSUE THREAD

**Issue by mtkgeek** [coollabsio/coolify#2900]
### Description

When you try deploying a github app that uses a dockerfile as build type, setting the `limits_cpus`  and `limits_memory` results in the error below. Setting only the `limits_cpus` works so I'm guessing the `limits_memory` is the problem. I don't think this is an API only problem though.

### Minimal Reproduction (if possible, example repository)

<img width="736" alt="Screenshot 2024-07-21 at 09 31 59" src="https://github.com/user-attachments/assets/0d6e0521-9aee-4285-a365-8354a13959a0">

### Exception or Error

<img width="931" alt="Screenshot 2024-07-21 at 09 31 39" src="https://github.com/user-attachments/assets/9b5372ad-ce74-4af5-8faa-9eda1e5fc170">

### Version

v4.0.0-beta.317

### Cloud?

- [ ] Yes
- [X] No

**Comment by andrasbacsai** [comment]
The minimum limit is 6MB as it writes. I have made a few updates on this view, so it will help you how to set these values:
![image](https://github.com/user-attachments/assets/a9756dd7-0d43-4889-8dc8-41c390304cad)

**Comment by mtkgeek** [comment]
Thanks. The alphabet was what i was missing.
