### ISSUE TITLE
[Bug]: Preview deployments not being removed

### ISSUE THREAD

**Issue by martmalo** [coollabsio/coolify#2901]
### Description

After multiple pull requests in my repo, coolify has created preview deployments as expected. Afterwards when pull request is merged/closed, preview deployment is still available and visible by running `docker ps` on server, but not shown in preview deployment section. This is causing errors for main deployment of the resource.

![image](https://github.com/user-attachments/assets/641da17f-5380-471f-8b20-2a322df8511f)
![image](https://github.com/user-attachments/assets/dc5c8324-b8b9-4b30-8060-085294e00eab)

### Minimal Reproduction (if possible, example repository)

Repository contains docker-compose.yml with Dockerfile from which docker image is being built. Repository is connected to github with github app.
Example of docker-compose (i have excluded coolify labels and everything else):
```
services:
  webapp:
    build:
      context: .
      args:
        ...
    environment:
        ...
```

![image](https://github.com/user-attachments/assets/d976584a-4e76-4ce2-9383-f94324cbe9de)

### Version

v4.0.0-beta.317

### Cloud?

- [ ] Yes
- [X] No

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.
