### ISSUE TITLE
[Bug]: Coolify - Supabase Service Error - 500 Something is not okay, are you okay?

### ISSUE THREAD

**Issue by henryobiaraije** [coollabsio/coolify#2905]
### Description

![image](https://github.com/user-attachments/assets/971272cc-bacb-4b81-b58f-b8f58075cb43)

I keep getting this error when I try to add a supabase service on Coolify. This happens both when I self-host coolify and when I host in coolify.io after subscribing.

Other services seem to work well as I've tried Postgres and it worked fine.

### Minimal Reproduction (if possible, example repository)

Select a project on Coolify
- Click on Add New Resource
- Select supabase

### Exception or Error

500

Something is not okay, are you okay?
There has been an error, we are working on it.

Error: The string `http://supabasekong:-http` is no valid url.

### Version

v4.0.0-beta.317

### Cloud?

- [X] Yes
- [ ] No

**Comment by andrasbacsai** [comment]
It is fixed on the cloud / self-hosted version.

**Comment by henryobiaraije** [comment]
This happens on both cloud and self-hosted versions.

**Comment by ExecutiveStride** [comment]
I'm getting this too - all of a sudden. I did a new install about 12 hours ago and it worked and now 

500

Something is not okay, are you okay?
There has been an error, we are working on it.

Error: bash: line 52: unexpected EOF while looking for matching `''

**Comment by iojanis** [comment]
Same, installed just now.

**Comment by aybasaran** [comment]
Hello, Any update guys?

**Comment by Jona630** [comment]
It happened when updating a nextjs app (self hosted)

**Comment by JuanxCursed** [comment]
Getting the same issue here with specific resource looks like some values is set wrong and is causing to crash it with 500
![image](https://github.com/user-attachments/assets/5d459433-63b4-4002-bc78-2240a691d633)

**Comment by JanikHalder** [comment]
Have the same issues

**Comment by JuanxCursed** [comment]
I finally found solution for my case, founded on the logs (through ssh connection) that pho memory was exhausted when livewire request happens, increasing de memory limit fix it to me, but I don't this this is something permanent

**Comment by peaklabs-dev** [comment]
The Supabase template will have some fixes in the next release which should also fix this.
