### ISSUE TITLE
[Bug]: rm: refusing to remove '.' or '..' 

### ISSUE THREAD

**Issue by Desarso** [coollabsio/coolify#2908]
### Description

Error when deploying docker-compose.yaml project. I have Preserve Repository During Deployment selected. The dockercompose depends on dockerfiles withing the project, and I must copy all the project files from the root of the git repo into one of the containers.  This is done this way: 
go_app:
    build:
      context: .  # Set context to the root of the application directory
      dockerfile: docker/app/dockerfile
    container_name: go_app
    volumes:
      - .:/app/
    ports:
      - "8259:3200"
    depends_on:
      - mongodb
      - valkey

### Minimal Reproduction (if possible, example repository)

The error seems to be that the automated script is trying to delete "." and ".." withing the project folder not sure though. It makes my deployments fail. 

### Exception or Error

[2024-Jul-22 05:06:02.541934] rm: refusing to remove '.' or '..' directory: skipping '/data/coolify/applications/w88cggs/.'
rm: refusing to remove '.' or '..' directory: skipping '/data/coolify/applications/w88cggs/..'

[2024-Jul-22 05:06:02.955405] rm: refusing to remove '.' or '..' directory: skipping '/data/coolify/applications/w88cggs/.'
rm: refusing to remove '.' or '..' directory: skipping '/data/coolify/applications/w88cggs/..'

### Version

v4.0.0-beta.317

### Cloud?

- [ ] Yes
- [X] No

**Comment by Desarso** [comment]
https://github.com/coollabsio/coolify/issues/1996#issuecomment-2242276130

Here is the same issue from a closed bug recently posted.

**Comment by Desarso** [comment]
https://github.com/coollabsio/coolify/issues/1996#issuecomment-2241550352

Here is the same issue from a closed bug recently posted.

**Comment by Hannes221** [comment]
I am encountering the same problem when selecting to preserve the repository during deployment

**Comment by andrasbacsai** [comment]
I have made updates in the latest released version, could you please check if it still happens?

**Comment by Hannes221** [comment]
My coolify instance isn't reachable anymore. There seems to be a problem with the Redis configuration.

**Comment by Hannes221** [comment]
Could be related to the latest release, but I am not quite sure

**Comment by Hannes221** [comment]
I am getting a different error now, but it seems be also related to the preservation of repository during deployment:

[COMMAND] docker network connect ek40sok coolify-proxy || true
[OUTPUT] Error response from daemon: endpoint with name coolify-proxy already exists in network ek40sok  
[2024-Jul-24 17:41:41.980496] cannot overwrite directory "/data/coolify/applications/ek40sok/datasource.yml" with non-directory "/data/coolify/applications/ek40sok"  
[2024-Jul-24 17:41:42.366783] cannot overwrite directory "/data/coolify/applications/ek40sok/datasource.yml" with non-directory "/data/coolify/applications/ek40sok"

**Comment by peaklabs-dev** [comment]
@Hannes221 This will be fixed in the next version.
