### ISSUE TITLE
[Bug]: Not copy resource for container 

### ISSUE THREAD

**Issue by rickafds** [coollabsio/coolify#2914]
### Description

I have the container deployed with keycloak, but the volumes in the docker-compose.yml not copy para container 

`  volumes:
      - ./theme/keywind:/opt/bitnami/keycloak/themes/keywind
      - ./certs/keycloak.pem:/opt/bitnami/keycloak/certs/fullchain.pem
      - ./certs/privkey.pem:/opt/bitnami/keycloak/certs/privkey.pem`

### Minimal Reproduction (if possible, example repository)

`version: "3.9"
services:
  keycloak:
    image: bitnami/keycloak:21.0.2
    ports:
      - "8081:8080"
    restart: unless-stopped
    volumes:
      - ./theme/keywind:/opt/bitnami/keycloak/themes/keywind
      - ./certs/keycloak.pem:/opt/bitnami/keycloak/certs/fullchain.pem
      - ./certs/privkey.pem:/opt/bitnami/keycloak/certs/privkey.pem`

### Exception or Error

folder empty 

### Version

v4.0.0-beta.317

### Cloud?

- [ ] Yes
- [X] No

**Comment by peaklabs-dev** [comment]
That the folders are empty is correct, because you would have to add data to them manually. There is now a fixed keylock template available if you upgrade to the latest version.
