### ISSUE TITLE
[Bug]: Update application endpoint always returns "not found"

### ISSUE THREAD

**Issue by mtkgeek** [coollabsio/coolify#2917]
### Description

The update application endpoint always return the same "not found" message. Same data, works on different endpoints. 

### Minimal Reproduction (if possible, example repository)

Try updating an application using the api
<img width="899" alt="Screenshot 2024-07-22 at 21 07 16" src="https://github.com/user-attachments/assets/4433cfd9-a017-4aed-8890-6cc56ef4ff7f">

### Exception or Error

{
  "message": "Not found.",
  "docs": "https://coolify.io/docs"
}

### Version

v4.0.0-beta.317

### Cloud?

- [ ] Yes
- [X] No

**Comment by andrasbacsai** [comment]
I see the problem. The docs was wrong (sorry), but updated now: https://coolify.io/docs/api-reference/applications/update
