### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by klawdyo** [coollabsio/coolify#2919]
### Description

Hello everybody.
I would like to report 2 possible bugs:

### Minimal Reproduction (if possible, example repository)

![image](https://github.com/user-attachments/assets/ee9c7513-56e9-495b-893e-89230a8a1bbf)

1) When the `proxy` is restarted or stopped and then started, the services that are in it do not start again.
It's happened to me 3 times. Some error happens, my memory gives 100% or my CPU gives 100% and the proxy restarts. No service returns.
I also think that in these cases there should not be a deployment, just starting the service that is already there.

2) In the list of resources, all services are showing the correct status, except mysql. MySQL continues to display information that it is working but it is not. When I access the resource page, it shows the deploy button, but in the listing the label is green.

### Version

v4.0.0-beta.306

### Cloud?

- [ ] Yes
- [X] No

**Comment by andrasbacsai** [comment]
What do you mean by "the services that are in it do not start again."? Which services are you referring to?

**Comment by klawdyo** [comment]
All containers, including database, APIs, etc. The only service that works again after this reboot is coolify itself and coolify-db. The rest have the “stopped” status.

**Comment by fcpauldiaz** [comment]
Fresh install of coolify 319. Cannot start proxy. @andrasbacsai 

![Screenshot 2024-07-30 at 12 08 04 PM](https://github.com/user-attachments/assets/4ef775e2-ae9b-4225-a68f-521884c9729e)

**Comment by peaklabs-dev** [comment]
This issue should be resolved in the latest version as we refactored a lot of code related to this. If you're still experiencing this issue, please reopen or create a new issue with updated details.
