### ISSUE TITLE
[Bug]: Unclear How to / Unable to: Update Coolify

### ISSUE THREAD

**Issue by komali2** [coollabsio/coolify#2920]
### Description

I have a notification that my coolify instance is out of date in the bottom-left corner:

![2024-07-23-131738_222x398_scrot](https://github.com/user-attachments/assets/fcea32e0-7329-400f-ba78-d410dff1f0ad)

I click it. Nothing seems to happen. If I open the console, I can see a regular message in the web console saying

`It's alive. Waiting for server to be dead...`

I'm not sure what I should do - should I be taking a server down? 

### Minimal Reproduction (if possible, example repository)

1. Be on version `v4.0.0-beta.236`
2. Click update

### Version

v4.0.0-beta.236

### Cloud?

- [ ] Yes
- [X] No

**Comment by Paarth-K** [comment]
<img width="894" alt="image" src="https://github.com/user-attachments/assets/f104e25f-20aa-48b5-a0fe-04c0bf4b86e0">

**Comment by komali2** [comment]
Worked perfectly! Thanks.
