### ISSUE TITLE
[Bug]: DatabaseBackupJob fail

### ISSUE THREAD

**Issue by Nonolanlan1007** [coollabsio/coolify#2930]
### Description

Database backups fail with the following error : 
![image](https://github.com/user-attachments/assets/06e3aa14-5711-473c-9536-9e3cc7c2d327)
Manual database work as expected.

### Minimal Reproduction (if possible, example repository)

Create a backup job on a mongodb or postgresql database

### Exception or Error

If you need logs, let me know 👀 

### Version

v4.0.0-beta.318

### Cloud?

- [ ] Yes
- [X] No

**Comment by Nonolanlan1007** [comment]
New error now:
![image](https://github.com/user-attachments/assets/8258abbb-7b60-44c1-bd43-3e3aad8f21d3)

**Comment by Nonolanlan1007** [comment]
Performing a manual upgrade solve the issue. I think it happen after an automatic upgrade 🤔

**Comment by Nonolanlan1007** [comment]
Issue happen again, so upgrade dies not solve it :/

**Comment by Nonolanlan1007** [comment]
Error happen again after upgrading to v4.0.0-beta.320

![image](https://github.com/user-attachments/assets/0ec0e463-5032-4af2-a215-71658a761a53)

**Comment by Nonolanlan1007** [comment]
Same i v3.0.0-beta.322

**Comment by Nonolanlan1007** [comment]
@andrasbacsai (sorry for the mention, but I can't reopen the issue and I don't know if you're enabled all notifications)

**Comment by Nonolanlan1007** [comment]
Upgraded to v4.0.0-beta.331 and error still occurs.

**Comment by peaklabs-dev** [comment]
This error needs to be fixed somehow:
```
PullHelperImageJob failed with: Error response from daemon: toomanyrequests: retry-after: 244.706µs, allowed: 44000/minute
PullHelperImageJob failed with: Error response from daemon: toomanyrequests: retry-after: 385.552µs, allowed: 44000/minute
```

**Comment by peaklabs-dev** [comment]
Closing in favor of the new issue: https://github.com/coollabsio/coolify/issues/3395
