### ISSUE TITLE
[Bug]: Supabase is not working.

### ISSUE THREAD

**Issue by fabioallexandr3** [coollabsio/coolify#2938]
### Description

I am using Supabase, and until yesterday it was working perfectly. However, today I tried to deploy a new instance, and it no longer works.

### Minimal Reproduction (if possible, example repository)

https://github.com/user-attachments/assets/90d2ea0c-27da-4125-98d4-cf515c6d0ed5

### Exception or Error

Saved configuration files to /data/coolify/services/hwgk4wo.
Creating Docker network.
Starting service.
Pulling images.
 supabase-edge-functions Pulling 
 supabase-kong Pulling 
 supabase-vector Pulling 
 supabase-meta Pulling 
 realtime-dev Pulling 
 minio-createbucket Pulling 
 supabase-storage Pulling 
 supabase-minio Pulling 
 supabase-analytics Pulling 
 supabase-auth Pulling 
 supabase-rest Pulling 
 supabase-db Pulling 
 supabase-studio Pulling 
 imgproxy Pulling 
 supabase-analytics Pulled 
 supabase-minio Pulled 
 supabase-studio Pulled 
 supabase-vector Pulled 
 supabase-storage Pulled 
 supabase-kong Pulled 
 imgproxy Pulled 
 supabase-rest Pulled 
 supabase-meta Pulled 
 supabase-db Pulled 
 supabase-auth Pulled 
 minio-createbucket Pulled 
 realtime-dev Pulled 
 supabase-edge-functions Pulled 
Starting containers.
 Volume "hwgk4wo_supabase-db-data"  Creating
 Volume "hwgk4wo_supabase-db-data"  Created
 Volume "hwgk4wo_supabase-db-config"  Creating
 Volume "hwgk4wo_supabase-db-config"  Created
 Container supabase-vector-hwgk4wo  Creating
 Container imgproxy-hwgk4wo  Creating
 Container supabase-minio-hwgk4wo  Creating
 Container supabase-minio-hwgk4wo  Created
 Container supabase-vector-hwgk4wo  Created
 Container minio-createbucket-hwgk4wo  Creating
 Container supabase-db-hwgk4wo  Creating
 Container imgproxy-hwgk4wo  Created
 Container minio-createbucket-hwgk4wo  Created
 Container supabase-db-hwgk4wo  Created
 Container supabase-analytics-hwgk4wo  Creating
 Container supabase-analytics-hwgk4wo  Created
 Container realtime-dev-hwgk4wo  Creating
 Container supabase-studio-hwgk4wo  Creating
 Container supabase-edge-functions-hwgk4wo  Creating
 Container supabase-rest-hwgk4wo  Creating
 Container supabase-auth-hwgk4wo  Creating
 Container supabase-kong-hwgk4wo  Creating
 Container supabase-meta-hwgk4wo  Creating
Error response from daemon: invalid mount config for type "bind": stat /data/coolify/services/hwgk4wo/volumes/functions/main/index.ts: not a directory

### Version

v4.0.0-beta.318

### Cloud?

- [x] Yes
- [x] No

**Comment by lolcatswag** [comment]
same for me!

**Comment by ramyvictor** [comment]
@fabioallexandr3 
Try converting empty content storages into a directory. The issue is that they are defined as filed.
In your case... this file path needs to be converted to a directory
![image](https://github.com/user-attachments/assets/33c429c3-4193-40b0-891f-e606fbd7dfb2)

**Comment by itskush** [comment]
> @fabioallexandr3 Try converting empty content storages into a directory. The issue is that they are defined as filed. In your case... this file path needs to be converted to a directory ![image](https://private-user-images.githubusercontent.com/24825069/352055833-33c429c3-4193-40b0-891f-e606fbd7dfb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MDA3NzUsIm5iZiI6MTcyMTkwMDQ3NSwicGF0aCI6Ii8yNDgyNTA2OS8zNTIwNTU4MzMtMzNjNDI5YzMtNDE5My00MGIwLTg5MWYtZTYwNmZiZDdkZmIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDA5NDExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4NzNmYzdhZWJiMmE4Yjc2M2I5MzgzMzUwYWU0MzljN2UzZmFhNGY1MDk0MDE2YTcyNDhmYjgxOWE2NDk2MDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S-E3Gu2j_9J_lHamZkJapJVoRDcKZ9B1Fp7xwM4zDCo)

I tried that and it still doesn't work

**Comment by NoCapCbas** [comment]
having the same issue currently

**Comment by itskush** [comment]
> having the same issue currently forced the cleanup, then implemented all empty storages to a directory mount and was able to deploy

Awesome!
Yeah had to covert those to directories
![image](https://github.com/user-attachments/assets/0612488e-7321-4436-833e-e385d87fa112)
then the deploy was successful

**Comment by fabioallexandr3** [comment]
> > tendo o mesmo problema atualmente forçou a limpeza, então implementou todos os armazenamentos vazios em uma montagem de diretório e foi capaz de implantar
> 
> Incrível! Sim, tive que convertê-los para diretórios, então a implantação foi bem-sucedida ![imagem](https://private-user-images.githubusercontent.com/27741218/352081243-0612488e-7321-4436-833e-e385d87fa112.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MDc1MTUsIm5iZiI6MTcyMTkwNzIxNSwicGF0aCI6Ii8yNzc0MTIxOC8zNTIwODEyNDMtMDYxMjQ4OGUtNzMyMS00NDM2LTgzM2UtZTM4NWQ4N2ZhMTEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDExMzMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNTA1MmQyZjdiNjFiYmRiNjljYjQwNmMxYWE2M2M5MDlhZTIzNThjMDkzMDM5ODY0NzAxNDI2ZDEyMTI3NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JDyhCrmAojvApnMV9oZjOxDmR2ooSVjcWAolCAYmLl8)


It worked for me as well. I had to change all the empty "File Mount" to "Convert to Directory" and force the cleanup of the containers.

Sucess!
