### ISSUE TITLE
[Bug]: Error 500 deploying Appwrite

### ISSUE THREAD

**Issue by syedkhairi** [coollabsio/coolify#2942]
### Description

Selected Appwrite on the services list, clicked deploy, error 500.

### Minimal Reproduction (if possible, example repository)

1. Create new resource
2. From Services list, select Appwrite
3. Click deploy without changing anything of the defaults, not even the url/domain

### Exception or Error

Error: SQLSTATE[22P05]: Untranslatable character: 7 ERROR: unsupported Unicode escape sequence DETAIL: \u0000 cannot be converted to text. CONTEXT: JSON data, line 1: ...tput\\\\ConsoleOutput))\n#26 {main}\n\"} \n\u0000... (Connection: pgsql, SQL: select * from "activity_log" where "properties"->>'type_uuid' = b48sg0c order by "created_at" desc limit 1)

### Version

v4.0.0-beta.318

### Cloud?

- [X] Yes
- [ ] No

**Comment by andrasbacsai** [comment]
It is patched in the cloud, and the next release will have a fix.
