### ISSUE TITLE
[Bug]: When using two shared variables in one field only first is substituted

### ISSUE THREAD

**Issue by vitalybaev** [coollabsio/coolify#2947]
### Description

I'm using Mailpit for email testing and found the following problem:

Mailpit [allows](https://mailpit.axllent.org/docs/configuration/smtp/) you to provide username/password for SMTP as environment variable like `MP_SMTP_AUTH="username:password"`.

I create two separated shared variables `MAILPIT_USER` and `MAILPIT_PASSWORD`. In Laravel I use them accordingly, but when I put `{{environment:MAILPIT_USER}}:{{environment.MAILPIT_PASSWORD}}` I got exactly the same result as just `{{environment:MAILPIT_USER}}`.

### Minimal Reproduction (if possible, example repository)

1. Create two shared variables, for example for environment:
   * `MAILPIT_USER` with value `test_user`
   * `MAILPIT_PASSWORD` with value `12345`
2. Create any project and create environment variable with any name with the following content:
    `{{environment.MAILPIT_USER}}:{{environment:MAILPIT_PASSWORD}}`

I expect value of the final variable as `test_user:12345` but get just `test_user`

### Version

v4.0.0-beta.318

### Cloud?

- [ ] Yes
- [X] No

**Comment by vitalybaev** [comment]
I found the place when it occurs and think I can fix it on my own, but seen that you added Live-stream label to it.

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.
