### ISSUE TITLE
Make creating services - add descriptions 

### ISSUE THREAD

**Issue by jesperordrup** [coollabsio/coolify#295]
Make it clear which services are available.

# When adding a service you are presented with:

![image](https://user-images.githubusercontent.com/3120151/161906553-d0a9d1b7-3255-4856-9a2c-01b2bcda327d.png)

For instance, is "Ghoist" this https://github.com/TryGhost/Ghost ?

Consider adding

1. Description
2. Links to homepage  and repo

# Add a bit more info about what service is being configured in the flow will help

For many reasons you can be interupted or someone else is working on the team adding features. Or maybe just to confirm for you what you're doing.

![image](https://user-images.githubusercontent.com/3120151/161907175-1cd6518a-01e9-4f25-ba04-af5149a2e337.png)

![image](https://user-images.githubusercontent.com/3120151/161907208-d59d9c89-514b-4ffe-a610-9980fe9cb14d.png)

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
