### ISSUE TITLE
[Bug]: EDITED: Supabase Setup not working - only 3 services starting

### ISSUE THREAD

**Issue by maksp-glitch** [coollabsio/coolify#2950]
### Description

Hello, 

I wanted to deploy supabase to the localhost where coolify is running on. I didnt make any edits on the compose file or the basic setup. Just as it came I hit deploy. 

### Minimal Reproduction (if possible, example repository)

The default setup of supabase in coolify was used. No edits in env-var or the compose file. 

### Exception or Error

Only IMGProxy, DB are starting, MinIO starts unhealthy and rest of the services doesnt start at all. 

```
Starting containers.
 Volume "oco04sk_supabase-db-data"  Creating
 Volume "oco04sk_supabase-db-data"  Created
 Volume "oco04sk_supabase-db-config"  Creating
 Volume "oco04sk_supabase-db-config"  Created
 Container supabase-vector-oco04sk  Creating
 Container supabase-minio-oco04sk  Creating
 Container imgproxy-oco04sk  Creating
 Container imgproxy-oco04sk  Created
 Container supabase-vector-oco04sk  Created
 Container supabase-db-oco04sk  Creating
 Container supabase-minio-oco04sk  Created
 Container minio-createbucket-oco04sk  Creating
 Container minio-createbucket-oco04sk  Created
 Container supabase-db-oco04sk  Created
 Container supabase-analytics-oco04sk  Creating
 Container supabase-analytics-oco04sk  Created
 Container realtime-dev-oco04sk  Creating
 Container supabase-studio-oco04sk  Creating
 Container supabase-rest-oco04sk  Creating
 Container supabase-meta-oco04sk  Creating
 Container supabase-auth-oco04sk  Creating
 Container supabase-kong-oco04sk  Creating
 Container supabase-edge-functions-oco04sk  Creating
Error response from daemon: invalid mount config for type "bind": stat /data/coolify/services/oco04sk/volumes/functions/main/index.ts: not a directory
```

MinIO Errors: 
```
FATAL Unable to initialize backend: Unable to write to the backend
      > Please ensure MinIO binary has write permissions for the backend
      HINT:
        Drives are not directories, MinIO erasure coding needs directories
FATAL Unable to initialize backend: Unable to write to the backend
      > Please ensure MinIO binary has write permissions for the backend
      HINT:
        Drives are not directories, MinIO erasure coding needs directories
FATAL Unable to initialize backend: Unable to write to the backend
      > Please ensure MinIO binary has write permissions for the backend
      HINT:
        Drives are not directories, MinIO erasure coding needs directories
```

### Version

v4.0.0-beta.318

### Cloud?

- [ ] Yes
- [X] No

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.

**Comment by maksp-glitch** [comment]
@andrasbacsai I found another issue regarding Supabase. Seems like MinIO doesnt have write permissions: 


```
FATAL Unable to initialize backend: Unable to write to the backend
      > Please ensure MinIO binary has write permissions for the backend
      HINT:
        Drives are not directories, MinIO erasure coding needs directories
FATAL Unable to initialize backend: Unable to write to the backend
      > Please ensure MinIO binary has write permissions for the backend
      HINT:
        Drives are not directories, MinIO erasure coding needs directories
FATAL Unable to initialize backend: Unable to write to the backend
      > Please ensure MinIO binary has write permissions for the backend
      HINT:
        Drives are not directories, MinIO erasure coding needs directories
```

**Comment by Skeyelab** [comment]
> This will be fixed in the upcoming version.

Is there a work around?

**Comment by andrasbacsai** [comment]
> > This will be fixed in the upcoming version.
> 
> 
> 
> Is there a work around?

It should be fixed in the released version.

**Comment by andrasbacsai** [comment]
> @andrasbacsai I found another issue regarding Supabase. Seems like MinIO doesnt have write permissions: 
> 
> 
> 
> 
> 
> ```
> 
> FATAL Unable to initialize backend: Unable to write to the backend
> 
>       > Please ensure MinIO binary has write permissions for the backend
> 
>       HINT:
> 
>         Drives are not directories, MinIO erasure coding needs directories
> 
> FATAL Unable to initialize backend: Unable to write to the backend
> 
>       > Please ensure MinIO binary has write permissions for the backend
> 
>       HINT:
> 
>         Drives are not directories, MinIO erasure coding needs directories
> 
> FATAL Unable to initialize backend: Unable to write to the backend
> 
>       > Please ensure MinIO binary has write permissions for the backend
> 
>       HINT:
> 
>         Drives are not directories, MinIO erasure coding needs directories
> 
> ```

Can you please open a separate issue for this?
