### ISSUE TITLE
Add shm-size docker option

### ISSUE THREAD

**Issue by andrasbacsai** [coollabsio/coolify#2963]

**Comment by SrAnthony** [comment]
I got the "PG::DiskFull: ERROR:  could not resize shared memory segment "/PostgreSQL.726751546" to 4194304 bytes: No space left on device" error.

Couldn't find an option to set the shm-size on coolify, so I set it on the docker config inside the machine:
```bash
nano /etc/docker/daemon.json
```
added
```json
{
   ...
  "default-shm-size" : "4G"
}
```

To make sure it worked, I restarted the server and ran:
```bash
docker exec <container id> df -h | grep shm
# shm                       4.0G      5.9M      4.0G   0% /dev/shm
```
