### ISSUE TITLE
[Bug]: error in environment variables

### ISSUE THREAD

**Issue by edgardoll4** [coollabsio/coolify#2979]
### Description

When I create a new application and place the variables, they are placed correctly, but when I update the page they appear as if they have been changed and they take the values ​​of the variables of the same name (the variables) from another application that is already running and also takes those values ​​from another application that has environment variables with the same name.

I have tried several times and I get the same error, but if the variable has a different name than other variables from the other applications, it does not change the value alone.

### Minimal Reproduction (if possible, example repository)

![Screenshot 2024-07-30 190523](https://github.com/user-attachments/assets/1d5af3af-6948-4a2a-b167-30277cc285fa)

### Version

v4.0.0-beta.319

### Cloud?

- [ ] Yes
- [X] No

**Comment by andrasbacsai** [comment]
I cannot reproduce it. Can you please make a small video that shows this error? Please do not use real secrets in it.

**Comment by peaklabs-dev** [comment]
Due to inactivity, we're closing this issue.
