### ISSUE TITLE
[Bug]: Plausible File (Docs) doesn't work anymore

### ISSUE THREAD

**Issue by ingokpp** [coollabsio/coolify#2985]
### Description

There are [docs for setting up Plausible Analytics](https://coolify.io/docs/resources/services/plausible#what-is-plausible-analytics) which refer to a [file](https://raw.githubusercontent.com/coollabsio/coolify/main/templates/compose/plausible.yaml) that doesn't work anymore.

Also I would love to have Plausible available in the 1 Click Service list.

### Minimal Reproduction (if possible, example repository)

Try setting up plausible using the file provided in coolify docs.

### Version

v4.0.0-beta.319

### Cloud?

- [ ] Yes
- [X] No

**Comment by vojtech-cerveny** [comment]
Hey, I was facing same issue, I was able to fix that - 
1. Generate new base64 strings 
    * `openssl rand -base64 48` for `SERVICE_BASE64_64_PLAUSIBLE` + 
    * `openssl rand -base64 32` for `SERVICE_BASE64_TOTP`
4. And also I updated to latest version `v2.1.1` in dockerfile  
5. Deploy and wait some time - also check your logs, you should not see any error.

**Comment by andrasbacsai** [comment]
Fixed the template in the next version.

@vojtech-cerveny workaround should work as well.
