### ISSUE TITLE
[Bug]: Scheduled task error

### ISSUE THREAD

**Issue by picocodes** [coollabsio/coolify#2986]
### Minimal Reproduction (if possible, example repository)

Create a new scheduled task and add a command that use a slash, e.g:-

```bash
/bin/bash /path/to/your/update_geoip.sh
```

### Exception or Error

500

Something is not okay, are you okay?
There has been an error, we are working on it.

Error: Missing required parameters for [Route: project.service.scheduled-tasks] [URI: project/{project_uuid}/{environment_name}/service/{service_uuid}/tasks/{task_uuid}] [Missing parameters: project_uuid, environment_name, service_uuid]. (View: /var/www/html/resources/views/livewire/project/shared/scheduled-task/all.blade.php)

### Version

v4.0.0-beta.319

### Cloud?

- [ ] Yes
- [X] No

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.
