### ISSUE TITLE
Not able to set a match-any subdomain

### ISSUE THREAD

**Issue by yashkolambekar** [coollabsio/coolify#2988]
### Description

I am trying to set a match-any subdomain so that any subdomain request will be redirected for my deployment which will look something like this `*.example.com` but it does not work!

What I want to do in simple words is,
aaa.example.com
123.example.com
xyz.example.com
And all possible subdomains should redirect to the deployed service/container

### Minimal Reproduction (if possible, example repository)

Set the url to `https://*.your-domain.com`

### Exception or Error

404 page not found

### Version

v4.0.0-beta.319

### Cloud?

- [ ] Yes
- [X] No

**Comment by andrasbacsai** [comment]
Please try to use this docs to setup a wildcard SSL and wildcard redirects: https://coolify.io/docs/knowledge-base/traefik/wildcard-certificates

If it does not work, please reopen this issue.
