### ISSUE TITLE
[Bug]: logout causes infinity alert loop "This page has expired. Would you like to refresh the page?"

### ISSUE THREAD

**Issue by mustafaabobakr** [coollabsio/coolify#2991]
### Description

When I logged out from Coolify with `Instance's Domain` 

the dashboard kept showing: 
1. an alert 
```
This page has expired.
Would you like to refresh the page?
```
![image](https://github.com/user-attachments/assets/f503678c-6610-43fc-8079-b7a9dba82b54)

2. this popup/modal
![image](https://github.com/user-attachments/assets/b880f3e0-8331-4bf5-8bcf-62979ee1dd2e)

### Minimal Reproduction (if possible, example repository)

1. added `Instance's Domain` 
2. Log out
3. This kept happening, even if I close and reopen in another browser!
4. Only solution was to change the `Instance's Domain` sub-domain.

https://github.com/user-attachments/assets/3eb0f8d8-2803-4e4c-b3b8-d41d11e8c7c2

### Version

v4.0.0-beta.319

### Cloud?

- [ ] Yes
- [X] No

**Comment by andrasbacsai** [comment]
I cannot reproduce it. Can you please send me an [email](https://coolify.io/docs/contact) with an invitation link to your instance, so I can take a look?

**Comment by Bl0ckS0lid** [comment]
Hi!

I have the same problem. I updated from 306 to 319 with the CLI installing .sh and now I'm getting the same error.
I cannot start new services and handling the old ones gives the same error.

I have restarted proxy, emptied browser cookies but have not found a fix yet. Pls inform if you get it sorted.

**Comment by peaklabs-dev** [comment]
I am unable to reproduce this issue, please upgrade to the latest version of Coolify v4 and try again, and if this is still an issue, feel free to reopen this issue or create a new one.

**Comment by louisjrdev** [comment]
I am also running into this exact issue, running on the latest 4.0.0-beta.360
