### ISSUE TITLE
[Bug]: cannot access "scheduled tasks" after I created one

### ISSUE THREAD

**Issue by moby3012** [coollabsio/coolify#2996]
### Description

I created a scheduled task to manually create a database backup for supabase daily and now I am getting error 500

### Minimal Reproduction (if possible, example repository)

1. create a fresh supabase instance
2. go to scheduled tasks
3. try creating a task such as:
name: example
command: PGPASSWORD=mysupersecretpassword pg_dump -h 127.0.0.1 -U supabase_admin -d postgres --exclude-schema=_analytics --clean --if-exists --no-owner --no-acl --format=plain | gzip > /tmp/backup-latest.sql.gz
cron: daily

save

then we get:

https://mycoolifyurl.com/project/xxx/production/service/xxx#scheduled-tasks

500
Something is not okay, are you okay?

There has been an error, we are working on it.
Error: Missing required parameters for [Route: project.service.scheduled-tasks] [URI: project/{project_uuid}/{environment_name}/service/{service_uuid}/tasks/{task_uuid}] [Missing parameters: project_uuid, environment_name, service_uuid]. (View: /var/www/html/resources/views/livewire/project/shared/scheduled-task/all.blade.php) 

### Exception or Error

500
Something is not okay, are you okay?

There has been an error, we are working on it.
Error: Missing required parameters for [Route: project.service.scheduled-tasks] [URI: project/{project_uuid}/{environment_name}/service/{service_uuid}/tasks/{task_uuid}] [Missing parameters: project_uuid, environment_name, service_uuid]. (View: /var/www/html/resources/views/livewire/project/shared/scheduled-task/all.blade.php) 

### Version

v4.0.0-beta.319

### Cloud?

- [ ] Yes
- [X] No

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.
