### ISSUE TITLE
Cloudflare dns 

### ISSUE THREAD

**Issue by nabeelshaikh7** [coollabsio/coolify#300]
Automatic dns record add by using cloudflare api and allow the use of cloudflare proxy

**Comment by compgeniuses** [comment]
what about if, the same tool thats used by acme sh, is also used to automate DNS of other platforms as well. not only cloudflare, i think it would work much better.

**Comment by ThallesP** [comment]
as a workaround, for now, you can generate an Origin Server certificate in Cloudflare (which is only valid between Cloudflare and your server) and it's valid for 15 years, then Cloudflare handles the rest for the browsers.

**Comment by yatagasaru** [comment]
> as a workaround, for now, you can generate an Origin Server certificate in Cloudflare (which is only valid between Cloudflare and your server) and it's valid for 15 years, then Cloudflare handles the rest for the browsers.

how can I do this ? I've tried to generate origin cert  and use full SSL/TLS encryption mode in cloudflare. 
If I access my coolify instance via `https://coolify.mydomain.com`, cloudflare shows invalid SSL handshake
