### ISSUE TITLE
[Bug]: Restarting a Postgres service causes "Found orphan containers" error overlay

### ISSUE THREAD

**Issue by predragnikolic** [coollabsio/coolify#3007]
### Description

<img width="1394" alt="Screenshot 2024-08-06 at 18 11 52" src="https://github.com/user-attachments/assets/fb3eeda3-4c05-4a6f-a222-49fffb2ab427">

### Minimal Reproduction (if possible, example repository)

1. Create a Postgres service.
2. Restart the postgres service.
3. Tada, see the error popup after 3second.

I can press escape, to hide the error popup, but it will come back after 5seconds.
The only way I know how to hide the popup is to delete the Postgres resource.

### Exception or Error

Error: ucwc044-proxy Pulling ucwc044-proxy Pulled time="2024-08-06T16:14:04Z" level=warning msg="Found orphan containers ([nockw84-proxy coolify-proxy]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up." Container ucwc044-proxy Creating Container ucwc044-proxy Created Container ucwc044-proxy Starting Error response from daemon: driver failed programming external connectivity on endpoint ucwc044-proxy (ec85a35f8bf96cba537623fdcc0c35228f52b39b097cb0b433c6444cfee7f824): Bind for 0.0.0.0:5432 failed: port is already allocated

### Version

v4.0.0-beta.319

### Cloud?

- [ ] Yes
- [X] No

**Comment by andrasbacsai** [comment]
You are mapping the port 5432 to the host system, where 5432 is already used by another process (probably another postgresql instance).

This behaviour could be improved by checking the port usage before starting the db, but that is an improvement, not a bug.
