### ISSUE TITLE
[Bug]:  Traefik proxy configuration file content doesn't always load correctly

### ISSUE THREAD

**Issue by nuxwin** [coollabsio/coolify#3020]
### Description

From the Coolify UI, we can normaly edit the Traefik proxy configuration file (for each server). The UI fails to load the conffile content via the UI due to JS error (see below). This problem isn't occuring on every requests :

![Capture d’écran 2024-08-07 à 15 50 54](https://github.com/user-attachments/assets/ed1d7606-01cd-45c4-be56-faeca0ab2ed9)

### Minimal Reproduction (if possible, example repository)

Go to the proxy tab for a server. Reload the page until you get the JS error. When the error occurs, you can see

```
Configuration file
    Start typing here
```

in place of the textarea making possible to edit the configuration.

### Exception or Error

![Capture d’écran 2024-08-07 à 15 51 40](https://github.com/user-attachments/assets/9309669f-ed40-4936-8c41-d15607a71ef3)

### Version

4.0.0-beta.302 (next image)

### Cloud?

- [ ] Yes
- [X] No

**Comment by peaklabs-dev** [comment]
@nuxwin Can you please update to the latest version and recheck and if possible provide more detailed reproduction steps? Thank you.

**Comment by nuxwin** [comment]
@peaklabs-dev Sure, I'll do soon.
