### ISSUE TITLE
[Bug]: Unsaved Preview Environment Variables get discarded when saving "production" variables in developer mode

### ISSUE THREAD

**Issue by cngJo** [coollabsio/coolify#3022]
### Description

When editing, both the main environment variables and those for the preview environments in developer mode at the same time and click on the "save" button on one of them, the other one will be reset. 

Maybe it would be a simple fix to consolidate the save buttons for both textareas into one button, which then saves both. Not sure tho if there are any UX reasons behind the current split.

### Minimal Reproduction (if possible, example repository)

1. Add variables to both "production" and the preview environment
2. Press "safe" on the "production" variables
![before-safe](https://github.com/user-attachments/assets/9fb34772-dcdd-4aff-bae8-91b2544f6f15)
3. after the page reload, the preview variables will be reset
![image](https://github.com/user-attachments/assets/54ec4d0d-2021-4a39-bb38-e8307dd6ae91)

NOTE: I Noticed it happens the other way around as well, saving the Preview ENV Variables will reset the unsafed production variables. 

### Version

v4.0.0-beta.319

### Cloud?

- [ ] Yes
- [X] No

**Comment by ayntk-ai** [comment]
This will be fixed in one of the next updates via this PR: https://github.com/coollabsio/coolify/pull/3062
