### ISSUE TITLE
[Bug]: docker: 'compose' is not a docker command.

### ISSUE THREAD

**Issue by PVUL** [coollabsio/coolify#3026]
### Description

On a fresh install of Coolify (v4.0.0-beta.319) on Hetzner Cloud (Ubuntu 24.04 LTS), when I try to deploy a service from the resource page, like supabase, vaultwarden, nextcloud, etc. I get the same error:

```
Saved configuration files to /data/coolify/services/...
Creating Docker network.
Starting service.
Pulling images.
docker: 'compose' is not a docker command.
See 'docker --help'
```

Coolify version: 4.0.0-beta.319
OS: Ubuntu 24.04 LTS
Host: Hetzner Cloud

Screenshot:
<img width="466" alt="Screenshot 2024-08-07 at 10 51 04 PM" src="https://github.com/user-attachments/assets/a010aad8-bc29-476a-aed7-9b2b905aceea">

### Minimal Reproduction (if possible, example repository)

1. Install latest version of Coolify (4.0.0-beta.319) on Ubuntu 24.04: `curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash`
2. From Coolify dashboard add new project, add resource, select any service (supabase), and attempt to deploy.
3. See deploy logs.

### Exception or Error

Error: `docker: 'compose' is not a docker command.`

### Version

v4.0.0-beta.319

### Cloud?

- [ ] Yes
- [X] No

**Comment by PVUL** [comment]
I did see this closed issue https://github.com/coollabsio/coolify/issues/2611 - but it seems that issue was related to an incompatible OS, so I don't believe it is related to the issue I am seeing.

**Comment by beejaz** [comment]
@PVUL Whats the output of these commands?

```
docker -v
docker compose version
```

**Comment by lesimoes** [comment]
I handled this issue after install docker-compose v2 on my ubuntu server

```bash
sudo apt-get install docker-compose-v2
```
