### ISSUE TITLE
Deploy Laravel

### ISSUE THREAD

**Issue by kingRayhan** [coollabsio/coolify#303]
I tried to deploy laravel app using coolify. In my project I have `composer.json` and also there have not `package.json`. When I click next, it recommended my application buildpack as Node. When I manually select PHP and start building, it shows in logs that composer packages are not installing.

Any idea how do I achieve this?

![image](https://user-images.githubusercontent.com/7611746/162093182-7cf0906c-2eda-4055-99b7-61cb3e8a6ae3.png)

**Comment by andrasbacsai** [comment]
The next version will contain composer support in PHP buildpack, but also will add Laravel in some upcoming releases.

**Comment by andrasbacsai** [comment]
It is happening in the next release!
