### ISSUE TITLE
[Bug]: Scheduled event runs not visible

### ISSUE THREAD

**Issue by picocodes** [coollabsio/coolify#3036]
### Description

![noptin-com-Scheduled-Tasks-Coolify](https://github.com/user-attachments/assets/edd1ef94-8a96-4af2-be99-76734c13f9f2)

### Minimal Reproduction (if possible, example repository)

Try viewing the logs for any scheduled events

### Version

v4.0.0-beta.323

### Cloud?

- [ ] Yes
- [X] No

**Comment by peaklabs-dev** [comment]
This will be fixed in one of the next versions, with this PR: https://github.com/coollabsio/coolify/pull/3063

**Comment by picocodes** [comment]
Thanks @peaklabs-dev
