### ISSUE TITLE
[Bug]: Storage setting modal should be scrollable

### ISSUE THREAD

**Issue by picocodes** [coollabsio/coolify#3038]
### Description

![dockerfile-Configuration-Coolify](https://github.com/user-attachments/assets/1d2dbe4c-003f-4c53-9839-17fd1db8f5d1)

### Minimal Reproduction (if possible, example repository)

Currently I have to open my browser's console and hide the first 2 forms so that I can fill the Directory mount form. 

### Version

v4.0.0-beta.323

### Cloud?

- [ ] Yes
- [X] No

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.

**Comment by picocodes** [comment]
Thanks @andrasbacsai 💪
