### ISSUE TITLE
Add Hoppscotch service.

### ISSUE THREAD

**Issue by matheusfenolio** [coollabsio/coolify#304]
Add [Hoppscotch](https://hoppscotch.io/) as an available service to deploy.

**Comment by compgeniuses** [comment]
you should have added that its github is here: https://github.com/hoppscotch/hoppscotch

**Comment by compgeniuses** [comment]
@matheusfenolio Kindly Add and Vote for this request here: https://feedback.coolify.io/

**Comment by andrasbacsai** [comment]
Closing this one in favor of: https://feedback.coolify.io/posts/68/service-hoppscotch
