### ISSUE TITLE
[Bug]: Swarm Mode - Couldn't see traefik (proxy) service logs through the Coolify UI

### ISSUE THREAD

**Issue by nuxwin** [coollabsio/coolify#3045]
### Description

When in Swarm mode, the UI don't find the **traefik** service logs. This is because the wrong name is used in the command: **coolify-proxy** instead of **coolify-proxy_traefik**.

Indeed, when using the Swarm mode, you create the stack with the name **coolify-proxy**. However, the traefik service name, inside the stack is composed of the stack name and the service name itself, not just the stack name, which doesn't make a sense as in a stack, you could have more than one service. The service name is the one defined in the docker compose configuration file (traefik).

Right now, we get the following error in the UI:
```
no such task or service: coolify-proxy
```

More info:

```shell
root@srv02:/# docker stack ls
NAME            SERVICES
coolify-proxy   1
root@srv02:/# docker service ls
ID             NAME                    MODE         REPLICAS   IMAGE          PORTS
kooru79b52e9   coolify-proxy_traefik   replicated   1/1        traefik:v3.1   *:80->80/tcp, *:443->443/tcp, *:8080->8080/tcp
root@srv02:/# 
```

The wrong and the right way : 

```shell
root@srv02:/# docker service logs coolify-proxy # OUPSSSS
no such task or service: coolify-proxy
root@srv02:/# 
root@srv02:/# docker service logs -fn0 coolify-proxy_traefik # BETTER
root@srv02:/# 
```

Thank you.

### Minimal Reproduction

Try to look at logs for the proxy (traefik) when in Swarm mode.

### Exception or Error

```shell
no such task or service: coolify-proxy
```

### Version

4.0.0-beta.323

### Cloud?

- [ ] Yes
- [X] No

![Capture d’écran 2024-08-10 à 07 31 25](https://github.com/user-attachments/assets/dae38651-acc5-4ad2-a2b5-c2f59cb11883)

**Comment by peaklabs-dev** [comment]
Please upgrade to the latest version of v4 and retest if this issue persists. If it does, kindly reopen this issue or create a new updated issue.
