### ISSUE TITLE
[Bug]: Github Webhook not working with Github App

### ISSUE THREAD

**Issue by yashkolambekar** [coollabsio/coolify#3047]
### Description

The auto deploy using github app is not working and neither the webhooks are working as no way to set the secret is provided

![Screenshot from 2024-08-10 20-19-09](https://github.com/user-attachments/assets/828351ea-f992-40df-a984-8bc66ce5f4cf)
It clearly says that I am using Official Github App

![image](https://github.com/user-attachments/assets/458e33ea-058a-492b-87a0-733e388bfa75)
But when github pings it, it says unauthenticated

### Minimal Reproduction (if possible, example repository)

Import private repo using a Github app
Add the Webhook url to github repo
Push a commit

### Exception or Error

Unauthorised

### Version

v4.0.0-beta.323

### Cloud?

- [ ] Yes
- [X] No

**Comment by andrasbacsai** [comment]
If you are using the GitHub app, you do not need to set the webhook URL. It is handled by Coolify + GitHub.

Please remove the Webhook URL from the GitHub repository and check your GitHub App's webhook settings (`Recent deliveries` page).
