### ISSUE TITLE
Directus Support

### ISSUE THREAD

**Issue by osbulbul** [coollabsio/coolify#305]
It would be great to add Directus as a service. It helps to create API quickly with beatiful UI.

**Comment by compgeniuses** [comment]
@osbulbul  Kindly Add and Vote for this request here: https://feedback.coolify.io/

**Comment by osbulbul** [comment]
@compgeniuses done :) https://feedback.coolify.io/posts/14/service-directus

**Comment by andrasbacsai** [comment]
Closing this one in favor of: https://feedback.coolify.io/posts/14/service-directus
