### ISSUE TITLE
[Bug]: Default QWEB Template not working Odoo 17

### ISSUE THREAD

**Issue by LexiconAlex** [coollabsio/coolify#3057]
### Description

I am experiencing an issue with the default QWEB templates in Odoo 17. When attempting to send an offer or invoice, the system fails, and the QWEB template does not render correctly.

### Minimal Reproduction (if possible, example repository)

1. Install Odoo 17.
2. Go to the Sales or Invoicing module.
3. Create a new offer or invoice.
4. Attempt to send the offer or invoice via email.
5. Observe the error related to the QWEB template rendering.

### Version

v4.0.0-beta.323

### Cloud?

- [ ] Yes
- [X] No

**Comment by LEstradioto** [comment]
Couldnt reproduce here. Whats the error looks like? Doesnt seem to be a Coolify problem

**Comment by andrasbacsai** [comment]
Odoo probably need SMTP configuration for sending emails. That is not set by default.
