### ISSUE TITLE
[Bug]: Coolify Application Create Error by API

### ISSUE THREAD

**Issue by janithmadu** [coollabsio/coolify#3064]
### Description

I'm facing the error now when I try to create an application using API, I will attach the error and passing data can you please help me?

### Minimal Reproduction (if possible, example repository)

![1](https://github.com/user-attachments/assets/1e7eb76c-8006-4177-ace5-b3bd65568af5)

### Version

v4.0.0-beta.323

### Cloud?

- [ ] Yes
- [X] No

**Comment by andrasbacsai** [comment]
The docs had a typo (it is [fixed](https://coolify.io/docs/api-reference/applications/create-private--gh-app)).

The real endpoint is `https://app.coolify.io/api/v1/applications/private-github-app` and not `.../private-gh-app`.
