### ISSUE TITLE
[Bug]: Openapi specs wrong path

### ISSUE THREAD

**Issue by LaurenceJJones** [coollabsio/coolify#3067]
### Minimal Reproduction (if possible, example repository)

Just code issues for OpenAPI generation the route used does not match one generated by the documentation

https://github.com/coollabsio/coolify/blob/69fc4c7f525100c9291b75f4b9f31f92b285bf14/routes/api.php#L74

https://github.com/coollabsio/coolify/blob/69fc4c7f525100c9291b75f4b9f31f92b285bf14/app/Http/Controllers/Api/ApplicationsController.php#L204

### Version

v4.0.0-beta.322

### Cloud?

- [ ] Yes
- [ ] No

**Comment by andrasbacsai** [comment]
Thank you, it is updated on the docs (and in the codebase as well).
