### ISSUE TITLE
[Bug]: backup db error mongo:4.2

### ISSUE THREAD

**Issue by aboire** [coollabsio/coolify#3071]
### Description

backup not done for mongo:4.2

### Minimal Reproduction (if possible, example repository)

create mongo db with mongo image:4.2

### Exception or Error

error parsing command line options: illegal argument combination: cannot specify --authenticationDatabase and --uri 

### Version

v4.0.0-beta.323

### Cloud?

- [ ] Yes
- [X] No

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.
