### ISSUE TITLE
[Bug]: Slow cloning over SSH (243KB)

### ISSUE THREAD

**Issue by alessiodam** [coollabsio/coolify#3073]
### Description

Cloning a tiny repo (243KB) takes around 4 minutes.

### Minimal Reproduction (if possible, example repository)

Clone a repo of size 243KB over SSH.

### Exception or Error

None. It's just slow.

### Version

v4.0.0-beta.323

### Cloud?

- [ ] Yes
- [X] No

**Comment by ayntk-ai** [comment]
Could you please provide a repo URL.
What do you mean cloning over SSH? Did zoy deploy the repo via the Girhub type?

**Comment by tkbstudios** [comment]
I cannot provide a repo URL. It is an internal repository deployed with SSH (using a private key)

**Comment by andrasbacsai** [comment]
Which git provider are you using?

**Comment by tkbstudios** [comment]
I'm using Forgejo 8.

**Comment by alessiodam** [comment]
There's absolutely nothing wrong with my connection. Using a bond of 4 ports which each have 2.5 gigabit ethernet connected.
The server is also running inside a VM and I'm cloning locally over IP address, closing this issue won't fix it :/

**Comment by andrasbacsai** [comment]
We could fix it, if we know that it is related to Coolify itself, but as you are the only one affected by this, and we have no idea how to replicate, we cannot fix it.

Is it still not working on that VM?

**Comment by alessiodam** [comment]
Idk, updating it fixed it but still unknown cause. Strange issue that got fixed on its own I guess. I've reinstalled it and it works fine.
