### ISSUE TITLE
[Bug]: Log drain not draining

### ISSUE THREAD

**Issue by rossanmol** [coollabsio/coolify#3078]
### Description

Hi,

I have configured log drain with both axiom and new relic. None of them however are receiving logs as I would expect.

### Minimal Reproduction (if possible, example repository)

1. Setup a basic server/resource in coolify (both self hosted and cloud)
2. Select your server, then Drain Logs
3. Configure Axiom via API key and dataset name

### Exception or Error

none

### Version

v4.0.0-beta.323

### Cloud?

- [X] Yes
- [ ] No

**Comment by andrasbacsai** [comment]
You cannot use both in the same time. You can only use one of the log drain endpoints at once.

I've tested Axiom now and it works for me. 

Did you enable to drain logs for the specific resource?
![image](https://github.com/user-attachments/assets/a4255006-1b33-4a83-a9dc-c932d4599ddd)

**Comment by rossanmol** [comment]
Ok, I completely missed this option. It isn't even mentioned in docs. I will try it out quick.

**Comment by Hussein-Ali-Hassan** [comment]
@rossanmol yes 100%, I was struggling 3 days to make it work with axiom until i found the solution here that i should check the checkbox in the project advanced settings. Not mentioned in the docs unfortunately

**Comment by andrasbacsai** [comment]
I have updated the docs: https://coolify.io/docs/knowledge-base/drain-logs
