### ISSUE TITLE
[Bug]: Telegram Bot notifications not working

### ISSUE THREAD

**Issue by yashkolambekar** [coollabsio/coolify#3084]
### Description

Telegram Bot notifications not working

### Minimal Reproduction (if possible, example repository)

Go to /notifications/telegram and add the telegram bot api token and chat id

### Exception or Error

success popup comes but nothing being sent to the chat

### Version

v4.0.0-beta.323

### Cloud?

- [ ] Yes
- [X] No

**Comment by mlmetzner** [comment]
i have managed to enabled them but the dashboard gets unresponsive and needs to be refeteched. turning the notifications off fixes the problem

**Comment by andrasbacsai** [comment]
@yashkolambekar Did you try to send a Test Notification?

**Comment by eddienubes** [comment]
@yashkolambekar 
Makes sure to include "-" sign to have something like `-4504503876`.
Test notification worked for me.

**Comment by VitalyKolesnikov** [comment]
Also not working for me. Test notification works and I receive it well, but nothing is being sent on app redeploy for example (I turned on all notification types in settings).
v4.0.0-beta.323

**Comment by yashkolambekar** [comment]
Well, for me only the auto deploy notifications are working and the backup notifications every night at 0000 hours
My apps are deployed from the github app source, just to be more clear.

**Comment by eguenou** [comment]
It was working until I enable topics in Telegram.
