### ISSUE TITLE
[Bug]: Cannot backup Plane db since its password protected

### ISSUE THREAD

**Issue by felixrydberg** [coollabsio/coolify#3091]
### Description

When trying to setup backups for Plane DB service (postgres:15.5-alpine) in a Plane one click setup the backup will fail with the error: 
```
Message: Password: pg_dump: error: connection to server at "plane-db" (172.27.0.3), port 5432 failed: fe_sendauth: no password supplied
```

We will need a way to backup password protected dbs since the password is there and saved in the Variables along with the username.

While doing this it would be lovely if we could have a way to upload a dump / backup to a "stacked" postgres instance like we are able to with the Single item postgres.

Im not sure if this is a feature request or more along the line of a bug, If Im doing anything wrong tell me and Ill do my best to correct it :)

### Minimal Reproduction (if possible, example repository)

Setup a Plane resource and then go to:
- Service Stack
- Find Plane DB under Services and click Settings
- In the menu on the left you will find Backups, click there
- Add a Scheduled Backup and then press Backup now

### Exception or Error

![image](https://github.com/user-attachments/assets/c87aedde-73bf-435e-a1e8-2639efb8f93b)

### Version

v4.0.0-beta.323

### Cloud?

- [ ] Yes
- [X] No

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.
