### ISSUE TITLE
[Bug]: Transactional emails not working

### ISSUE THREAD

**Issue by moshetanzer** [coollabsio/coolify#3098]
### Description

Hey,

Hope you are well.

How can I debug why transactional email arent being sent?

Could it be that it treats $ as a variable in password?

### Minimal Reproduction (if possible, example repository)

coolify

### Version

323

### Cloud?

- [ ] Yes
- [X] No

**Comment by andrasbacsai** [comment]
Do you have an example? Please add more reproduction steps.

**Comment by moshetanzer** [comment]
Example is password with a $ sign in it doesn’t work.

**Comment by moshetanzer** [comment]
Hi @andrasbacsai ,

Emails are not being sent!! Tested with resend and other smtp settings.

**Comment by andrasbacsai** [comment]
Exactly. You need to have a SMTP or 3rd party service to have transactional emails.

**Comment by moshetanzer** [comment]
😆 - are you joking @andrasbacsai - the bug is that it does not except many SSL certificates and doesn't show the error message....
