### ISSUE TITLE
[Bug]: Always failed on health check 10/10

### ISSUE THREAD

**Issue by ardiansyaherwin** [coollabsio/coolify#3101]
### Description

Hi,
My project is using PayloadCMS, it's a NextJS CMS framework. The build is succeed.
the error happens on the 10th health check. 
While in the middle of healthchecking, I frequently check the app frontpage it works well, but then when the healtchecking 10th fails, the app also broken.

Not sure how to explain it more, here's the log:
```
[2024-Aug-16 01:00:22.119947] Attempt 10 of 10 | Healthcheck status: "unhealthy"
[2024-Aug-16 01:00:22.123775] Healthcheck logs: (no logs) | Return code: 1
[2024-Aug-16 01:00:22.125893] ----------------------------------------
[2024-Aug-16 01:00:22.128220] Container logs:
[2024-Aug-16 01:00:22.228035] > my-app@1.0.0 start /app
> cross-env NODE_OPTIONS=--no-deprecation next start

▲ Next.js 15.0.0-canary.104
- Local: http://localhost:3000/

✓ Starting...
✓ Ready in 491ms
[2024-Aug-16 01:00:22.233098] ----------------------------------------
[2024-Aug-16 01:00:22.236228] Removing old containers.
[2024-Aug-16 01:00:22.238872] New container is not healthy, rolling back to the old container.
```

and here's my health checks config:
<img width="767" alt="Screenshot 2024-08-16 at 08 04 34" src="https://github.com/user-attachments/assets/3dab3cd4-6650-4c90-a137-542aadd43aa2">

### Minimal Reproduction (if possible, example repository)

- just a fresh payloadCMS without any customization
- I use pnpm 9.1.2, so I had to add packagemanager override to package.json

### Version

v4.0.0-beta.323

### Cloud?

- [ ] Yes
- [X] No

**Comment by andrasbacsai** [comment]
Can you try out with `http` and `not https`?

**Comment by CelestialLemon** [comment]
I'm also facing a similar issue. I am not able to view my app on the generated domain. The build is successful and if I navigate to the app using VPS ip address and port number I can see its running. If I do `curl http://localhost:3000` using a ssh session its giving proper response. But the health check keeps failing for the application. Its the same even if health checks are disabled.

Unlike OP I'm not able to view my app for some time before the health check fails. Its just 502 Bad gateway all the time. Not sure if both issues are similar or different. I'm new to coolify and self hosting and I followed online tutorials for setting it up, maybe I'm doing something wrong.

I'll post some config screenshots below. 

![image](https://github.com/user-attachments/assets/3150379c-9175-4359-bd53-d9c8cf14e1b2)
![image](https://github.com/user-attachments/assets/70a370be-1e39-47c9-83a0-e653210da963)
![image](https://github.com/user-attachments/assets/15948e18-aca2-450d-8acf-784aa80a2ab5)

**Comment by djsisson** [comment]
@CelestialLemon you're mapping port 3000 on host to port 80 in container?? can you try removing the port mappings just leave it as port 3000 exposed assuming your app is running on port 3000

**Comment by CelestialLemon** [comment]
No I'm using nginx to serve the app which by default runs on 80. Anyways I still tried what you suggested and it did not work. It also made the app not accessible via ip-address+port @djsisson

**Comment by djsisson** [comment]
if youre running on port 80 then just put expose 80 and leave port mapping blank

**Comment by CelestialLemon** [comment]
This works. Thanks a lot @djsisson. So to do here what I wanted to do I can set port exposes as 80 and port mapping as 3000:80. Tried it and it works. Thanks again.
