### ISSUE TITLE
Bug when adding more than one Persistent Storage in any app

### ISSUE THREAD

**Issue by vinicioslc** [coollabsio/coolify#311]
Hi ! 

First of all, this project its amazing, i really apreciate him.

Second, found a bug, 
when i add more than one persistent storage.

![image](https://user-images.githubusercontent.com/10997022/162302815-1478146a-80d0-4b5f-bace-2a0ca7d964d6.png)

When i have some time i will try dive in the code, could tell me where i need check to bebug errors.

**Comment by andrasbacsai** [comment]
Oh, nice catch. It will be fixed in the next version!
