### ISSUE TITLE
TYPO3 Support

### ISSUE THREAD

**Issue by KartoffelToby** [coollabsio/coolify#312]
A TYPO3 Support as a Service would be nice.

Is there a contrib way to add new Services?

**Comment by vasani-arpit** [comment]
@andrasbacsai add new service label 

This could be helpful in development https://github.com/martin-helmich/docker-typo3

**Comment by andrasbacsai** [comment]
Closing this one in favor of: https://feedback.coolify.io/posts/67/service-typo3
