### ISSUE TITLE
Shopware Support

### ISSUE THREAD

**Issue by KartoffelToby** [coollabsio/coolify#313]
A Service with Shopware CE

**Comment by vasani-arpit** [comment]
@andrasbacsai Please add new service label 

project: https://github.com/shopware/platform

**Comment by compgeniuses** [comment]
@KartoffelToby   Kindly Add and Vote for this request here: https://feedback.coolify.io/

**Comment by andrasbacsai** [comment]
Closing this one in favor of: https://feedback.coolify.io/posts/66/service-shopware

**Comment by nyxb** [comment]
is it correct that the link is dead or can only internal people vote?
