### ISSUE TITLE
Minimum requirement to host Coolify

### ISSUE THREAD

**Issue by devshahrukhkhan** [coollabsio/coolify#316]
Question: 

Hi, first of all, I have to say you are doing an amazing job and this is a really great product :)

Here is my question what is the minimum requirement of Coolify for testing purposes I am using the base plan of DigitalOcean(1 vCPU
1 GB / 25 GB Disk) would it be sufficient to run Coolify?

**Comment by andrasbacsai** [comment]
Hey. Thanks! 🙂

Here are the requirements: https://docs.coollabs.io/coolify/installation#minimum-requirements-for-coolify

Basically, for Coolify, not much is needed, but if you would like to host applications, you probably need at least 2 CPUs, as Coolify will build your apps.

Other resources (services/databases) also need more memory. 

So it depends on what you would like to use it for. 😃
