### ISSUE TITLE
[Bug]: Unable to Identify github_app_uuid for Deploying Private Repository via Coolify API

### ISSUE THREAD

**Issue by ssoronid** [coollabsio/coolify#3209]
### Description

I'm trying to deploy a private GitHub repository using the Coolify API on a self-hosted setup. The goal is to automate the deployment process through our front-end app, allowing Coolify to deploy instances on demand with unique environment variables for each.

### Minimal Reproduction (if possible, example repository)

Set up a self-hosted Coolify instance.
Create a Team.
Create an Api Key.
Create a GitHub app manually into Coolify resources.
Attempt to use the API endpoint /api/v1/applications/private-github-app to deploy the repository using different IDs (ID, installation ID, client ID).

### Exception or Error

"message": "GitHub App not found"

### Version

v4.0.0-beta.323

### Cloud?

- [ ] Yes
- [X] No

**Comment by ssoronid** [comment]
> The Github App related endpoints are still missing from the API.

My usecase demands some kind of deployment with custom envs via front end on X service and i cant find a workaround to deploy them and monitor it at coolify better than this.

In last instance is there a way i can contribute on this with PRs or donations ?

**Comment by peaklabs-dev** [comment]
I hope this is now working.

Github App related endpoints will be implemented in the API soon.
