### ISSUE TITLE
[Bug]: Two ghost installations clash and crashes Traefik

### ISSUE THREAD

**Issue by AlejandroAkbal** [coollabsio/coolify#3224]
### Description

Hi, some months ago I was able to put Ghost on a subdirectory of another website in Coolify

Let's say I have
- Website A (Laravel)
- Website B (Ghost)

I could have B inside A on a subdirectory like `example/blog`

But now it seems like requests are not redirected to website B, it shows 404 of website A

### Minimal Reproduction (if possible, example repository)

1. Create a website of any kind
2. Create a ghost website
3. Set the URL to something like https://example.com:2368/blog
4. It does not work :(

### Version

 v4.0.0-beta.323

### Cloud?

- [ ] Yes
- [X] No

**Comment by AlejandroAkbal** [comment]
Basically this commit allowed ghost on subdirector
https://github.com/coollabsio/coolify/commit/543f983e41f594483d54fb2f769234ebf1e2863d

**Comment by AlejandroAkbal** [comment]
Basically this commit allowed ghost on subdirectory @andrasbacsai 
https://github.com/coollabsio/coolify/commit/543f983e41f594483d54fb2f769234ebf1e2863d

**Comment by AlejandroAkbal** [comment]
Okay, the issue is having multiple ghost services, the `traefik.http.middlewares.redir-ghost` middleware is clashing with other projects, because it's duplicated

Please fix it @andrasbacsai by making them unique based on the project name

**Comment by peaklabs-dev** [comment]
I added a fix in v364 please try again now and let me know if it works.

**Comment by AlejandroAkbal** [comment]
It works, thanks a lot <3
