### ISSUE TITLE
[Bug]: When deployment fails cant even load the main page

### ISSUE THREAD

**Issue by omerzirh** [coollabsio/coolify#3225]
### Description

When deployment fails somehow. It keeps infinite loop when i try to access cloud via ip/domain.

I can access after 1 hour or more

### Minimal Reproduction (if possible, example repository)

create a bug in your code which will cause build fail (in my case react app)
click deploy
after it failed try to reach cloud

### Exception or Error

Gateway Timeout

### Version

latest( i cant see because still loading :D)

### Cloud?

- [X] Yes
- [ ] No

**Comment by peaklabs-dev** [comment]
I am unable to reproduce this issue, please upgrade to the latest version of Coolify and try again, and if this is still an issue, please feel free to reopen this issue and provide a repository URL so we can reproduce this issue.
