### ISSUE TITLE
[Bug]: COOLIFY environment variables not defined when doing preview deployment

### ISSUE THREAD

**Issue by weyert** [coollabsio/coolify#3229]
### Description

When you are doing a preview deployment of `Dockerfile` the `COOLIFY_*` environment variables are not known.

Vercel from example expose these variables both in `production` and `preview` builds, see:
https://vercel.com/docs/projects/environment-variables/system-environment-variables

### Minimal Reproduction (if possible, example repository)

http://github.com/weyert/quote-of-the-day

If you try to do a preview deployment of this the `COOLIFY_FQDN` will be undefined in `next.config.js` or when its building the page and calls `getBirthOfDay`:

```
#16 24.45 Generating static pages (0/4) ...  
[2024-Aug-26 16:00:43.984940]

[COMMAND] docker exec sw8sg0kog8s0wwgcocw84ssg bash -c 'bash /artifacts/build.sh'
[OUTPUT] #16 25.01 API_HOST: undefined #16 25.01 COOLIFY_FQDN: undefined #16 25.01 NEXT_PUBLIC_SOURCE_COMMIT: undefined #16 25.01 API_HOST: undefined #16 25.01 COOLIFY_FQDN: undefined #16 25.01 NEXT_PUBLIC_SOURCE_COMMIT: undefined 
```

### Exception or Error

No errors

### Version

4.0.0-beta.323

### Cloud?

- [ ] Yes
- [X] No

**Comment by pkellner** [comment]
I just ran into this same issue I believe. You can not set the env variables to be available in developer view, but, you can select them individually to be available during the build by turning off developer view and then on each line item there is a checkbox to select making it available.

I was just about to make an issue with a suggestion for how to fix that and make it more clear to "people like us" who don't just know that.

**Comment by peaklabs-dev** [comment]
@pkellner What would you suggest to improve the UX, so that it is more clear?

**Comment by pkellner** [comment]
I was thinking in the dev screen where you paste in the environment variables, add a checkbox below that saying “ export all variables at build”, and default that to checked.  Then, when unchecked, unhide another text input area that lets you put in a comma or semicolon separated list of env variables to expose in build. 

I realize that exposing all will create a verbose docker command with lots of args, but I think it will better follow the principle of “least surprise”.

**Comment by weyert** [comment]
I don't think you can select for the built-in `COOLIFY_*` variables?

**Comment by pkellner** [comment]
Also, I like the “bug” tag better because as is, if you input your env values in dev mode (like I’m guessing every dev will do), you’ll never know how to expose them at build time as there is not even a hint.  

Adding a * comment in the UI would IMHO make this an improvement, but without, definitely a bug.

**Comment by Br1tBreaker** [comment]
Ey, bruv, sounds like you're having a bit of a mare with your Vercel deployments.  Variables not playing ball during previews, innit?  Classic Dockerfile shenanigans.

Let's sort this out.  First things first, double-check those environment variables in your Vercel project settings. Make sure they're set up for both production and preview environments, just like the docs say.

Next, peep your next.config.js. Are you trying to access the COOLIFY_* variables directly there? Might need to tweak your logic a bit. Try using process.env.COOLIFY_FQDN instead, mate.

If that doesn't do the trick, try a hard refresh or clear your Vercel cache.  Sometimes those deployments get a bit sticky.

Still no joy? Then it's time to get our hands dirty. Check your build logs in detail.  Look for any errors or warnings related to the COOLIFY_* variables. They might be trying to tell you something.

And if all else fails, don't be afraid to hit up the Vercel support crew. They're usually pretty sound and can help you get to the bottom of it.

Keep me posted, yeah?

**Comment by weyert** [comment]
Not sure, why you are start talking about Vercel while I am talking about Coolify. 

I am trying to say that as far as I can see `--build-arg COOLIFY_FQDN=$COOLIFY_FQDN` or similar is not happening when building a docker image.  Only get set when running the image. Maybe I am not following the code.

**Comment by ja3nyc** [comment]
> Not sure, why you are start talking about Vercel and contacting Vercel support while I am talking about Coolify. 
> 
> 
> 
> I am trying to say that as far as I can see `--build-arg COOLIFY_FQDN=$COOLIFY_FQDN` or similar is not happening when building a docker image.  Only get set when running the image. Maybe I am not following the code.

I think it's a bot 😂

**Comment by Br1tBreaker** [comment]
Alright, bruv, my bad.  Got my wires crossed there for a sec. Coolify, not Vercel, innit?  My apologies.

So, you're saying the COOLIFY_FQDN isn't making it into your Docker image during the build, yeah? That's a right pain in the arse.

Let's have a butcher's at your Dockerfile then. Are you definitely using the --build-arg flag correctly when you're building the image? Double-check the syntax, mate.

Also, make sure you're actually referencing the COOLIFY_FQDN build arg somewhere inside your Dockerfile.  If it's just floating around in there, it's not gonna do much good.

Another thing to consider is the order of your build steps. Are you trying to use the COOLIFY_FQDN before it's actually been set? Dockerfiles can be a bit finicky with that sort of thing.

If you're still scratching your head, try printing out the environment variables during your build process.  Chuck in a cheeky ENV instruction or an echo command to see what's actually going on in there.

And if all else fails, don't be shy about digging into the Coolify docs or community forums. Someone's bound to have bumped into this before.

We'll crack this, bruv. Just keep at it.

**Comment by andrasbacsai** [comment]
In the next version all COOLIFY related environment variables will be available during build time, except for docker compose based application. For those it is a bit complex.

**Comment by weyert** [comment]
Awesome that's amazingly quick. Thank you
