### ISSUE TITLE
Make on-demand sFTP for all services

### ISSUE THREAD

**Issue by andrasbacsai** [coollabsio/coolify#323]

**Comment by rallisf1** [comment]
I am manually using https://github.com/atmoz/sftp and just mount the same volume as my project if it helps.

**Comment by andrasbacsai** [comment]
Yeah, I'm using that for Wordpress in Coolify, just need to port it to other things, like services. Thanks for the suggestion! 🙂

**Comment by LittleBigFrog** [comment]
How to set up https://github.com/atmoz/sftp for coolify? Could you point me in right direction?

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
