### ISSUE TITLE
[Bug]: Server is not reachable, Error: root@host.docker.internal: Permission denied (publickey,password)

### ISSUE THREAD

**Issue by rujorgensen** [coollabsio/coolify#3243]
### Description

I'm installing Coolify on a home PC using the auto-install script [`curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash`
](https://coolify.io/docs/installation), but I'm running into a lot of issues when trying to connect a server (localhost). I've tried double checking the SSH-keys, but nothing seems wrong there (I don't know alot about SSH-connection/keys though).
![image](https://github.com/user-attachments/assets/1912df9c-d3e0-4981-b27c-d2038e8b0c0e)

A few minor oddities that I thought is worth mentioning is:
1. When I later try to [uninstall Coolify](https://coolify.io/docs/uninstall), and stop the running containers, I get an error about a service that is not running called "coolify-proxy"
`Error response from daemon: No such container: coolify-proxy`
2. When running the install script I have to add "sudo" like so `curl -fsSL https://cdn.coollabs.io/coolify/install.sh | **sudo** bash`
3. (**It just appeared to me that the IP given there was my global IP, and I don't have ports open right now, so I guess this is not important**) When the installation completes with the message below, I get a timeout in my browser when using the given IP. I am, however, able to connect to the coolify instance using the IP of the PC on my network, in this case http://192.168.8.3:8000/ 

```
Congratulations! Your Coolify instance is ready to use.

Please visit http://<ip>:8000 to get started.
```

My Docker version is "27.2.0, build 3ab4256"

**Update**
I get exactly the same results on my second home PC running Ubuntu 24.04.1 LTS, as described above.

### Minimal Reproduction

curl -fsSL https://cdn.coollabs.io/coolify/install.sh | sudo bash, then go to ip-of-pc-on-local-network:8000, and try to connect to the server on localhost.

### Exception or Error

```Server is not reachable.
... root@host.docker.internal: Permission denied (publickey,password).```

Later:
`Error response from daemon: No such container: coolify-proxy`

### Version

v4.0.0-beta.323

### Cloud?

- [ ] Yes
- [X] No

**Comment by rujorgensen** [comment]
BTW. The SSH-server on the PC seems to be running fine, as I regularly connect to the PC from another home PC.

**Comment by peaklabs-dev** [comment]
Do you have a Password set on the SSH key?

**Comment by rujorgensen** [comment]
Hi @peaklabs-dev, thanks for your response!

> And is your home PC Linux based?

Yes, the PC is running CuteFishOS. `cat /etc/os-release` gives me PRETTY_NAME="Ubuntu 22.04.3 LTS"
> And do you allow port 22 in ufw or simmilar?

I don't know a lot about SSH or networking, but I guess it's all setup fine, as I'm able to establish a regular SSH connection from my main home PC, to the one in question. If theres anyway you can suggest for me to check it, I'd be happy to.

**Comment by peaklabs-dev** [comment]
Some points:
- Technically the OS you are using is not supported. It seems to work though because it is like Ubuntu.
- _When running the install script I have to add "sudo" like so curl -fsSL https://cdn.coollabs.io/coolify/install.sh | **sudo** bash_ --> As you are adding sudo you are probably not using root so you need to change the username in the UI. So please change the username in the UI and try again

**Comment by rujorgensen** [comment]
> Technically the OS you are using is not supported. It seems to work though because it is like Ubuntu.

OK, gotcha 👍. I did try it out on my other home PC though, which is running a "stock" Ubuntu 24.04.1 LTS just installed today, with exactly the same issues.

>  As you are adding sudo you are probably not using root so you need to change the username in the UI. So please change the username in the UI and try again

If I understand you correctly, I ran `whoami` on the Coolify PC, and got "rj", then added that as the user in the Coolify UI, but I got kind of same issue unfortunately :/.
![image](https://github.com/user-attachments/assets/8d149932-7739-4fa4-beec-6522034e62d1)

>run this command to check if you have a firewall enabled

`sudo ufw status` gives me "Status: inactive", how does that look?

**Comment by peaklabs-dev** [comment]
Thank you for checking.
The ufw is inactive so disabled (wiche is good for now).

As you are using rj, and not root as the user you should follow the docs here: https://coolify.io/docs/knowledge-base/server/non-root-user. Add your user to the sudoers file. This is not the most secure way, but it will be improved in the future. Let me know if that resolves your issue.

**Comment by rujorgensen** [comment]
@peaklabs-dev that worked, thanks a lot 🥳!

I'd prefer not using the "rj" user and do it by the book, so I might look into how to do that some day.

I just want to add that I had some issues while bringing up the server (that I guess is related to the user too?). I solved it temporarily by modifying ownership of "/data/coolify" with `sudo chmod -R 777 /data/coolify` just to get going.
![image](https://github.com/user-attachments/assets/26fe00b1-7ed2-4e1a-a01d-8f8b2238f14d)

Thanks a lot for your help, please feel free to claim the reward ⭐.

**Comment by peaklabs-dev** [comment]
@rujorgensen Great to hear that I could help.

Feel free to upvote the feature request here: https://github.com/coollabsio/coolify/discussions/1759

Yes, at the moment just using `root` would be your best bet.

As this issue did not include a PR with algroa, the reward/bounty system does not allow claiming. If you want feel free to sponser me on my Github: https://github.com/sponsors/peaklabs-dev and remove the bounty from the issue.

**Comment by Dell-it** [comment]
Maybe it will be useful to someone: I received such an error, because on my Armbian system, by default, the "PubkeyAuthentication" parameter was disabled in "/etc/ssh/sshd_config". I think it's worth adding this check to the documentation.

But otherwise, coolify works great on Armbian. Thx!

![image](https://github.com/user-attachments/assets/257a8bf4-d765-4cb4-8b08-b29a25bae922)
