### ISSUE TITLE
[Bug]: Scheduled Tasks not ordered

### ISSUE THREAD

**Issue by johnpccd** [coollabsio/coolify#3245]
### Description

![image](https://github.com/user-attachments/assets/8a3637a5-f084-48c9-bfdf-0f17bbdea016)

### Minimal Reproduction (if possible, example repository)

Set up a scheduled task that runs daily.. in the report, the runs are not sorted by date

### Version

4.0.0.323

### Cloud?

- [ ] Yes
- [ ] No

**Comment by Vahor** [comment]
Will be fixed in next release: https://github.com/coollabsio/coolify/pull/3186

**Comment by Vahor** [comment]
Well, it's ordered but in the wrong order.
![image](https://github.com/user-attachments/assets/fc3c5d02-0c13-4d68-a661-63c62bbcdffc)

most recent is at the bottom of the page
