### ISSUE TITLE
Build logs should save branch name that was used during the build instead of showing the current branch

### ISSUE THREAD

**Issue by italodeandra** [coollabsio/coolify#325]
I created an app and used the branch `main`.

But then I changed the branch to `debug`, so I looked at the build logs and saw that the name of the branch on the log was also updated.

![image](https://user-images.githubusercontent.com/19225266/162462176-ca6464f1-4cbe-4844-b386-32e13763fbbe.png)

Those should all be `main` and only the next build should show `debug`.

**Comment by andrasbacsai** [comment]
It will be fixed in the next version. Old build logs will show the wrong branch, but the new ones will be correct.
