### ISSUE TITLE
[Bug]: Posthog web container error "exec: /compose/start: Permission denied"

### ISSUE THREAD

**Issue by tconroy** [coollabsio/coolify#3257]
### Description

When setting up a fresh Posthog resource using the preconfigured services, the `web` container appears to be caught in an infinite restart loop with a permissions error:
```
2024-08-30T02:12:26.015995111Z /usr/local/bin/docker-entrypoint.sh: 101: exec: /compose/start: Permission denied
```

### Minimal Reproduction (if possible, example repository)

create project -> prod environment -> +new resource -> Posthog -> start. All containers except web start successfully. Web throws error repeatedly. 

### Exception or Error

2024-08-30T02:12:26.015995111Z /usr/local/bin/docker-entrypoint.sh: 101: exec: /compose/start: Permission denied

### Version

v4.0.0-beta.323

### Cloud?

- [ ] Yes
- [X] No

**Comment by tconroy** [comment]
Seem to have found a workaround.

Edit the docker-compose to change:
```
web:
  image: 'posthog/posthog:latest'
  command: /compose/start
```

to be
```
web:
  image: 'posthog/posthog:latest'
  command: sh -c "chmod +x /compose/start && /compose/start"
```

**Comment by Yoda-Soda** [comment]
> Seem to have found a workaround.
> 
> Edit the docker-compose to change:
> 
> ```
> web:
>   image: 'posthog/posthog:latest'
>   command: /compose/start
> ```
> 
> to be
> 
> ```
> web:
>   image: 'posthog/posthog:latest'
>   command: sh -c "chmod +x /compose/start && /compose/start"
> ```
Thank you this sorted it out for me.

**Comment by peaklabs-dev** [comment]
I just tried the template again and I can not find this error in the logs for the web container anymore, so I believe this new command is not necessary anymore and I will close this issue.
