### ISSUE TITLE
[Bug]: Can not connect to a server

### ISSUE THREAD

**Issue by kirapwn** [coollabsio/coolify#3258]
### Description

When trying to add a server with long hostname it fails to run.

### Minimal Reproduction (if possible, example repository)

Add a server eg. EC2 with a long name.

### Exception or Error

```
Error: unix_listener: path "/var/www/html/storage/app/ssh/mux/ec2-IP_EDITEDeu-central-1.compute.amazonaws.com_22_ubuntu.YVAtivQ2O1QWw2FM" too long for Unix domain socket
```

### Version

v4.0.0-beta.323

### Cloud?

- [X] Yes
- [ ] No

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.
