### ISSUE TITLE
[Bug]: Development server. Server not reachable

### ISSUE THREAD

**Issue by felixrydberg** [coollabsio/coolify#3272]
### Description

Locahost server is marked as Not Reachable aswell as Services showing a The underlaying server has problems

![image](https://github.com/user-attachments/assets/3fc1241b-810e-43ca-ad38-f41a8ed57e68)
![image](https://github.com/user-attachments/assets/1f51c0d3-3576-4ebe-9e04-4f97fae9dac9)

### Minimal Reproduction (if possible, example repository)

I forked the repo to [here](https://github.com/felixrydberg/coolify).

### Exception or Error

![image](https://github.com/user-attachments/assets/c8a49862-7e08-4263-8790-e035c4f596a8)
![image](https://github.com/user-attachments/assets/b452b7d4-2b52-4df2-86a6-e452943c6a8f)

### Version

v4.0.0-beta.324

### Cloud?

- [ ] Yes
- [X] No

**Comment by felixrydberg** [comment]
A note about this is that some people have been posting about this in a thread aswell in Discord. Not sure what version they are running: https://discord.com/channels/459365938081431553/1275944468394147892

**Comment by felixrydberg** [comment]
I set this up on my other machine that is running Ubuntu server and the performance is way better. This might just be an issue with my WSL install then. Will continue digging into it

**Comment by cjsewell** [comment]
v4.0.0-beta.325 has fixed this for me, I believe its related to https://github.com/coollabsio/coolify/pull/3069

**Comment by peaklabs-dev** [comment]
@felixrydberg Is this fixed for you as well? And by the way, I rewrote the contributing guide if that might help you: https://github.com/coollabsio/coolify/blob/main/CONTRIBUTING.md
