### ISSUE TITLE
[Bug]: Supabase is not able to create buckets / show buckets

### ISSUE THREAD

**Issue by mwolf1989** [coollabsio/coolify#3274]
### Description

All Supabase Services seems to start but from the supabase studio it is no possible to list or create buckets:

<img width="243" alt="image" src="https://github.com/user-attachments/assets/70a6c52e-5d5b-4052-b034-c9e992d2671a">

<img width="347" alt="image" src="https://github.com/user-attachments/assets/f5571b95-953f-4cdb-a796-31360a029ac0">

### Minimal Reproduction (if possible, example repository)

Ressources -> new - supabase -> deploy 

### Exception or Error

Kong API:
Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
2024-08-31T14:12:36.817294037Z 172.23.0.15 - - [31/Aug/2024:14:12:36 +0000] "GET /api/storage/default/buckets HTTP/1.1" 500 45 

### Version

v4.0.0-beta.323

### Cloud?

- [ ] Yes
- [X] No

**Comment by theodufort** [comment]
Check the the logs for both minio containers (minio/minio and minio/mc) your cpu needs to support x64-v2 instructions otherwise you need to specify the image in your Dockerfile to a v1 image with v1 tags.

**Comment by peaklabs-dev** [comment]
We have updated and refactored the Supabase template quite a bit for the next update, could you please retest the [new compose file](https://github.com/coollabsio/coolify/blob/next/templates/compose/supabase.yaml) and let me know if this is still an issue.
