### ISSUE TITLE
[Bug]: cURL error 6: Could not resolve host: cdn.coollabs.io

### ISSUE THREAD

**Issue by EmilzonJ** [coollabsio/coolify#3275]
### Description

The platform show this error in any moment and many times.

### Minimal Reproduction (if possible, example repository)

The platform show this error in any moment and many times.

### Exception or Error

cURL error 6: Could not resolve host: cdn.coollabs.io (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://cdn.coollabs.io/coolify/versions.json

### Version

v4.0.0-beta.323

### Cloud?

- [ ] Yes
- [X] No

**Comment by peaklabs-dev** [comment]
Do yoy have your firewall setup correctely? https://coolify.io/docs/knowledge-base/server/firewall. Also do yoy allow all outgoing connection?

**Comment by ddean6232** [comment]
All ports all protocols open on both ingress and egress.... now what?
I am on an Oracle Cloud free tier machine.  What did I miss?

**Comment by ddean6232** [comment]
Tailscale is the problem.  Disabled tailscale and all worked.  Opened only 8000, 6001, 6002 all good.
