### ISSUE TITLE
[Bug]: Appwrite template doesn't work properly

### ISSUE THREAD

**Issue by donnutdev** [coollabsio/coolify#3278]
### Description

When using the appwrite template provided by coolify, at the start of the docker compose file
```xml
- _APP_DB_USER=$SERVICE_USER_MARIADB
- _APP_DB_PASS=$SERVICE_PASSWORD_MARIADB
- _APP_DB_ROOT_PASS=$SERVICE_PASSWORD_MARIADBROOT
```
These appear to have no effect, because when running the env command after starting the app, it shows that these variables have no value.

### Minimal Reproduction (if possible, example repository)

This is present in the default template

### Exception or Error

The error message just says that a password is not specified in the appwrite-mariadb service. My fix for this was just to set the actual `_APP_DB_USER`, `_APP_DB_PASS` and `_APP_DB_ROOT_PASS` to the same value as the service variables.

### Version

v4.0.0-beta.323

### Cloud?

- [ ] Yes
- [x] No

**Comment by jawwaonline** [comment]
I upgraded to  [v4.0.0-beta.327] and i was able to install appwrite without changing the values.

Then i upgraded to [v4.0.0-beta.329] and tried to reinstall appwrite but appwrite could not connect to db
I also tried reassigning the above mentioned values with no success. 

Therefore i downgraded to  v4.0.0-beta.327 for now.

**Comment by vvinhas** [comment]
I'm facing the same issue

**Comment by vvinhas** [comment]
It's working now after updating my instance to [v4.0.0-beta.335](https://github.com/coollabsio/coolify/releases/tag/v4.0.0-beta.335)
