### ISSUE TITLE
Add portainer service

### ISSUE THREAD

**Issue by Soneji** [coollabsio/coolify#328]
- info: https://www.portainer.io
- install: https://docs.portainer.io/v/ce-2.11/start/install/agent/docker/linux

**Comment by compgeniuses** [comment]
a containe rwithin a container, that handels containers, cool.

@Soneji   Kindly Add and Vote for this request here: https://feedback.coolify.io/

**Comment by andrasbacsai** [comment]
Closing this one if favor of: https://feedback.coolify.io/posts/63/service-portainer
