### ISSUE TITLE
[Bug]: Proxy: "Port 80 is in use." on remote server 

### ISSUE THREAD

**Issue by EmilEmilchen** [coollabsio/coolify#3281]
### Description

When trying to start the Traefik Proxy on one of my remote servers I get an error: "Port 80 is in use.", makes sense (somewhat anyway). The problem:
```
root@local-srv1:~# lsof -i -P -n | grep 80    
root@local-srv1:~# 
```

### Minimal Reproduction (if possible, example repository)

Install Coolify and add a remote server, then try start the proxy on the remote server.

### Exception or Error

In the GUI:
```
Error
Port 80 is in use.
You must stop the process using this port.
Docs: https://coolify.io/docs
Discord: https://coollabs.io/discord
```
From the GUI (logs section) (useless):
```
Error response from daemon: No such container: coolify-proxy
```

### Version

v4.0.0-beta.323

### Cloud?

- [ ] Yes
- [X] No

**Comment by moshetanzer** [comment]
Check if your storage isn’t full?

**Comment by EmilEmilchen** [comment]
Definitely not:
```
root@local-srv1:~# df -h
Filesystem                        Size  Used Avail Use% Mounted on
/dev/mapper/pve-vm--105--disk--0   47G  4.3G   41G  10% /
```

**Comment by harryvince** [comment]
Might sound silly but have you checked that you aren't already running something on port 80?

**Comment by djsisson** [comment]
@EmilEmilchen you need to use sudo lsof, on its own you won't see processes that the executing user cant see.

**Comment by EmilEmilchen** [comment]
> @EmilEmilchen you need to use sudo lsof, on its own you won't see processes that the executing user cant see.

I ran the command as root without sudo, note that I'm logged in with root.

**Comment by EmilEmilchen** [comment]
> Might sound silly but have you checked that you aren't already running something on port 80?

That's what the `lsof` in my first code block in the question is for.

**Comment by djsisson** [comment]
@EmilEmilchen sorry youre right i missed that

can you run docker ps, is there a restarting container?

**Comment by EmilEmilchen** [comment]
It works now! I'm not 100% sure what I did that fixed it but I think the most likely option is, that clicking "Revalidate Server" under Servers > General > Revalidate Server did the trick.
