### ISSUE TITLE
[Bug]: Chaskiq template does not seem to work properly

### ISSUE THREAD

**Issue by alepouna** [coollabsio/coolify#3284]
### Description

I tried to use the provided Chaskiq integration which was added with #2939 (and in #3058) however the service does not seem to work. With a standard server and resource setup, when trying to access the default generated URL I get a 404 not found (from the proxy) and when changing the URL to a custom one, the Sidekiq service fails to start. 

### Minimal Reproduction (if possible, example repository)

Setup a Coolify instance, setup a server w/ Traefik proxy, setup a project and a resource that uses the Chaskiq integration.

### Version

v4.0.0-beta.324

### Cloud?

- [ ] Yes
- [X] No

**Comment by alepouna** [comment]
Probing @Kaotic since you introduced this service, perhaps you have some info missing. 

To maintainers: It seems like a quite few of the templates do not have proper documentation in the https://coolify.io/docs/resources/services/index page. I strongly recommend to include some requirement to have documentation included for templates, especially if they require additional configure (as I assume this template probably needs, but there is literally almost no information about it)

**Comment by Neyunse** [comment]
Chaskiq is still crashing and has not been fixed yet.

**Comment by peaklabs-dev** [comment]
This issue should be resolved in the latest version. If you're still experiencing this issue, please reopen or create a new issue with updated details.
