### ISSUE TITLE
[Bug]: Deployments using the Static build pack failing

### ISSUE THREAD

**Issue by leglock** [coollabsio/coolify#3293]
### Description

When I attempt to deploy a static site project using the Static build pack, I get a deployment error of "Call to a member function push() on null".

Through trial and error, I did find that I am able to successfully deploy it if I switch to the Nixpacks build pack and check off the static site option.

### Minimal Reproduction (if possible, example repository)

1. Add new project
2. Select public repository resource, using https://github.com/w3cj/banana
3. Change build pack to Static, click continue
4. Deploy

### Exception or Error

[2024-Sep-03 06:23:32.476112] Starting deployment of w3cj/banana:main to localhost.
[2024-Sep-03 06:23:32.731425] Preparing container with helper image: ghcr.io/coollabsio/coolify-helper:latest.
[2024-Sep-03 06:23:34.643270] Image not found (hkwkcokgok4ck48o0ockscko:b6a09cef27baa45c7eee73a0fabf6bfc77dd6b8c). Building new image.
[2024-Sep-03 06:23:34.649025] ----------------------------------------
[2024-Sep-03 06:23:34.653134] Importing w3cj/banana:main (commit sha HEAD) to /artifacts/ewg4ck8g0c4gs0kcc40cg84w.
**[2024-Sep-03 06:23:38.456066] Oops something is not okay, are you okay? 😢**

**[2024-Sep-03 06:23:38.460884] Call to a member function push() on null**

**[2024-Sep-03 06:23:38.468697] Deployment failed. Removing the new version of your application.**

### Version

v4.0.0-beta.325

### Cloud?

- [ ] Yes
- [X] No

**Comment by pipegalera** [comment]
Same problem using the same tutorial. Check the "Debug Logs". In my case it cannot create. the docker image - I tried with several simple static websites. 

I think its related to issue #3277 (https://github.com/coollabsio/coolify/issues/3277)

**Comment by leglock** [comment]
@pipegalera here is what my debug log shows. I'm not sure exactly what command it was trying to perform when it got the error; the last one the log shows has an output, which I'm interpreting as it succeeded.

```text
[2024-Sep-04 01:33:01.316263] Starting deployment of w3cj/banana:main to localhost.
[2024-Sep-04 01:33:01.594363] Preparing container with helper image: ghcr.io/coollabsio/coolify-helper:latest.
[2024-Sep-04 01:33:01.759605]

[COMMAND] docker rm -f kwsc40o4os8ckw8w0wso4okg
[OUTPUT]
Error response from daemon: No such container: kwsc40o4os8ckw8w0wso4okg

[2024-Sep-04 01:33:02.000742]

[COMMAND] docker run -d --network coolify --name kwsc40o4os8ckw8w0wso4okg --rm -v /var/run/docker.sock:/var/run/docker.sock ghcr.io/coollabsio/coolify-helper:latest
[OUTPUT]
1add07fe71d921fffe43a4080962609d474ded95db8288bfa0fbb27d465cae4d

[2024-Sep-04 01:33:03.215395]

[COMMAND] docker exec kwsc40o4os8ckw8w0wso4okg bash -c 'GIT_SSH_COMMAND="ssh -o ConnectTimeout=30 -p 22 -o Port=22 -o LogLevel=ERROR -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" git ls-remote https://github.com/w3cj/banana main'
[OUTPUT]
b6a09cef27baa45c7eee73a0fabf6bfc77dd6b8c refs/heads/main

[2024-Sep-04 01:33:03.441262] Image not found (rkgooo84sk0c0oo4c0gcwssg:b6a09cef27baa45c7eee73a0fabf6bfc77dd6b8c). Building new image.
[2024-Sep-04 01:33:03.447293] ----------------------------------------
[2024-Sep-04 01:33:03.452514] Importing w3cj/banana:main (commit sha HEAD) to /artifacts/kwsc40o4os8ckw8w0wso4okg.
[2024-Sep-04 01:33:03.732427]

[COMMAND] docker exec kwsc40o4os8ckw8w0wso4okg bash -c 'git clone -b "main" https://github.com/w3cj/banana /artifacts/kwsc40o4os8ckw8w0wso4okg && cd /artifacts/kwsc40o4os8ckw8w0wso4okg && sed -i "s#git@\(.*\):#https://\1/#g" /artifacts/kwsc40o4os8ckw8w0wso4okg/.gitmodules || true && cd /artifacts/kwsc40o4os8ckw8w0wso4okg && GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" git submodule update --init --recursive && cd /artifacts/kwsc40o4os8ckw8w0wso4okg && GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" git lfs pull'
[OUTPUT]
Cloning into '/artifacts/kwsc40o4os8ckw8w0wso4okg'...

[2024-Sep-04 01:33:04.164201]

[COMMAND] docker exec kwsc40o4os8ckw8w0wso4okg bash -c 'git clone -b "main" https://github.com/w3cj/banana /artifacts/kwsc40o4os8ckw8w0wso4okg && cd /artifacts/kwsc40o4os8ckw8w0wso4okg && sed -i "s#git@\(.*\):#https://\1/#g" /artifacts/kwsc40o4os8ckw8w0wso4okg/.gitmodules || true && cd /artifacts/kwsc40o4os8ckw8w0wso4okg && GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" git submodule update --init --recursive && cd /artifacts/kwsc40o4os8ckw8w0wso4okg && GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" git lfs pull'
[OUTPUT]
sed: /artifacts/kwsc40o4os8ckw8w0wso4okg/.gitmodules: No such file or directory

[2024-Sep-04 01:33:04.990124]

[COMMAND] docker exec kwsc40o4os8ckw8w0wso4okg bash -c 'cd /artifacts/kwsc40o4os8ckw8w0wso4okg && git log -1 b6a09cef27baa45c7eee73a0fabf6bfc77dd6b8c --pretty=%B'
[OUTPUT]
chore: initial commit

[2024-Sep-04 01:33:07.356326] Oops something is not okay, are you okay? 😢

[2024-Sep-04 01:33:07.361506] Call to a member function push() on null

[2024-Sep-04 01:33:07.370152] Deployment failed. Removing the new version of your application.
```

**Comment by JuanxCursed** [comment]
Same issue here, but not following that tuto, custom docker-compose file with Nixpacks

It started happening on version `v4.0.0-beta.325` 

```
[2024-Sep-04 01:16:49.633208] failed to read /artifacts/xxx/.env: line 6: unexpected character "/" in variable name
```
The weird part is that there isn't a `/` character on this variable (both on generated .env at the server or my own env lines)



I've deleted all my env variables, but I'm still getting the "same error"

```
GTM_ID=
NUXT_PUBLIC_METAPIXEL_DEFAULT_ID=
```

I noticed that the error changed when I changed the resource name as well, `Leads / Anamnese` to `Leads`


`[2024-Sep-04 01:36:45.721585] failed to read /artifacts/xxx/.env: line 6: key cannot contain a space`

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.

**Comment by andrasbacsai** [comment]
Let me know if this is not fixed.

**Comment by K-M-Code** [comment]
Hi thanks for the update, Tested it with multiple static site open repos and its working now. on 329 release, the same ones which wern't working on 325 release.
