### ISSUE TITLE
Support SSL/HTTPS

### ISSUE THREAD

**Issue by hit2hat** [coollabsio/coolify#33]
Hello!

Add please support of SSL/HTTPS certs. With auto re-new and get for demand (for example, when user create new deployment with domain, which don't get cert before)

Thx for product

**Comment by andrasbacsai** [comment]
Hey,

Let's Encrypt SSL certificates are automatically created after you deployed an application and auto-renewed before they expiries.

Is this what you would like to have? If yes, it's already implemented. 😄

**Comment by NewtonTrendy** [comment]
The caddy admin panel is not HTTPS and there is no obvious option to enable it.

**Comment by Wenish** [comment]
yes where do i enable https for the admin panel of coolify?

**Comment by borsTiHD** [comment]
Looking for the same answer.
How can I access the webinterface over https and maybe block http completly?
Thanks in advanced. :)

**Comment by lil5** [comment]
1. `Settings` -> `General` -> `Instance's Domain`
2. Input a https://<domain>.com
3. Save
4. Login from https://<domain>.com on the default port

**Comment by darklajid** [comment]
Related to the questions in this ticket: While the comment above explains how to enable TLS (awesome!), it is still unclear if there's a way to disable http / port 8000 for the admin interface?

**Comment by yatochka-dev** [comment]
> 1. `Settings` -> `General` -> `Instance's Domain`
> 2. Input a https://<domain>.com
> 3. Save
> 4. Login from https://<domain>.com on the default port

How do I create a dns record for this too? What type and what ipv4 do I provide?

**Comment by oyed** [comment]
> > 1. `Settings` -> `General` -> `Instance's Domain`
> > 2. Input a https://.com
> > 3. Save
> > 4. Login from https://.com on the default port
> 
> How do I create a dns record for this too? What type and what ipv4 do I provide?

Exactly the same as any other site/service in coolify - an `A` record pointing to the IP of your server

**Comment by yatochka-dev** [comment]
> > > 1. `Settings` -> `General` -> `Instance's Domain`
> > > 2. Input a https://.com
> > > 3. Save
> > > 4. Login from https://.com on the default port
> > 
> > 
> > How do I create a dns record for this too? What type and what ipv4 do I provide?
> 
> Exactly the same as any other site/service in coolify - an `A` record pointing to the IP of your server

I did it, but coolify still throws an error, maybe I should put something in `DNS Servers`?
![image](https://github.com/coollabsio/coolify/assets/93011550/bdd11be1-d593-41cb-bdfc-ee055f447848)

**Comment by yatochka-dev** [comment]
> > > 1. `Settings` -> `General` -> `Instance's Domain`
> > > 2. Input a https://.com
> > > 3. Save
> > > 4. Login from https://.com on the default port
> > 
> > 
> > How do I create a dns record for this too? What type and what ipv4 do I provide?
> 
> Exactly the same as any other site/service in coolify - an `A` record pointing to the IP of your server



> > > 1. `Settings` -> `General` -> `Instance's Domain`
> > > 2. Input a https://.com
> > > 3. Save
> > > 4. Login from https://.com on the default port
> > 
> > 
> > How do I create a dns record for this too? What type and what ipv4 do I provide?
> 
> Exactly the same as any other site/service in coolify - an `A` record pointing to the IP of your server

Thank you, I didn't even have that concept in my head then.

**Comment by yatochka-dev** [comment]
> @oyed @yatochka-dev don't forget to add the matching AAAA record 
> 
> ```
> AAAA <vps ipv6>
> A <vps ipv4>
> ```

It already works, I don't know what does that do

**Comment by lil5** [comment]
AAAA is the domain record for your ipv6 address

Without it your server won't be accessible to ipv6 only clients. 

https://lmddgtfy.net/?q=what%20is%20ipv6

**Comment by danielqba** [comment]
Still no way to disable admin panel over HTTP. Anyone has any solution?

**Comment by icebearlabs** [comment]
I have direct an A record from one of my domains to the Coolify server via coolify.<domain>.com and I added the domain under settings as https://coolify.<domain>.com

Still the browser tells me it's unsafe, when coming over https. 

How can I fix that?

**Comment by omerzirh** [comment]
@icebearlabs 

Did you find a solution on this?

**Comment by mj-dcb** [comment]
@icebearlabs @omerzirh you only have to set up the Instance's Domain via Settings -> Configuration. Make sure you enabled port 443 in your firewall rule you will be blocked otherwise. Then access the instance domain via https (do not add a port to the URL). I'm running v4.0.0-beta.323

**Comment by mj-dcb** [comment]
I have opened an issue that should clarify this https://github.com/coollabsio/coolify/pull/3092

**Comment by mj-dcb** [comment]
> Still no way to disable admin panel over HTTP. Anyone has any solution? Also, shouldn't HTTPS be enabled by default? Even with the IP and a self-signed cert?

It's not easy to enable HTTPs by default, I mean, you have to set up Coolify and that's usually done via port 80 initially.

**Comment by andrerpena** [comment]
You say `Settings -> Configuration` but I can't find `Settings` from `https://app.coolify.io/`

**Comment by lil5** [comment]
> You say `Settings -> Configuration` but I can't find `Settings` from `https://app.coolify.io/`.
> 
> I like Coolify very much so far, but HTTPS is not intuitive :).
> 
> 
> 
> EDIT: It's because `Settings` doesn't exist in the Cloud version. But I'm still to find where to set up HTTPS for the apps I'm serving from Coolify

That's a different issue than this one, but here goes:
1. ensure your application has a health check that returns healthy
2. The http response of / in you app needs to return a 200 status code for letsencrypt 
3. In the configuration of your app you need to add (assuming internally it listens to port 0.0.0.0:8080) "https://mydomain:8080" this will make https://mydomain requests proxy to http://mycontainer:8080
4. Your domain (or subdomain) should have A & AAAA records to your server, IIRC in cloud that would not be the cloud IP but your vps the built containers get pushed to to run.
