### ISSUE TITLE
[Bug]: The generated Redis URI is missing the user "default"

### ISSUE THREAD

**Issue by hnykda** [coollabsio/coolify#3317]
### Description

The displayed Redis URL - both internal and external are missing the `default` user specifier at the beginning.

![image](https://github.com/user-attachments/assets/e0636ca2-050b-483b-b550-24623c50e804)

### Minimal Reproduction (if possible, example repository)

Start a [v4.0.0-beta.323](https://github.com/coollabsio/coolify/releases/tag/v4.0.0-beta.323), deploy default redis without any conf.

### Version

v4.0.0-beta.323

### Cloud?

- [ ] Yes
- [X] No

**Comment by stefanofusai** [comment]
Just encountered the same issue, your report saved me lots of headaches :)

**Comment by peaklabs-dev** [comment]
This is not yet implemented, it will be available with this PR: https://github.com/coollabsio/coolify/pull/3184

**Comment by nnti3n** [comment]
What is the correct user. I tried `default` but not work

**Comment by hnykda** [comment]
Unless you changed something, it should be `default`. For me `https://default:pwd...` works just fine

**Comment by peaklabs-dev** [comment]
This has been implemented and will be available in an upcoming release. Thank you for your patience.
