### ISSUE TITLE
[Bug]: Update envs for a service

### ISSUE THREAD

**Issue by rkcreation** [coollabsio/coolify#3318]
### Description

I would like to update env variable with an API request.

I add a token (which works with deploy endpoint) and try to use it with this call : 

```bash
curl --location --request PATCH 'https://DOMAIN/api/v1/applications/UUID/envs' \
--header 'Content-Type: application/json' \
--header 'Authorization: ••••••' \
--data '{
    "key": "ENV_NAME",
    "value": "ENV_VALUE"
}'
```

I've got a 404 not found response.

When I try to request /applications, the which I seek is not returned. I try to update env vars for a Docker Compose application.

### Minimal Reproduction (if possible, example repository)

Create a Docker Compose application.

Try to find it with /applications endpoint

### Version

v4.0.0-beta.329

### Cloud?

- [ ] Yes
- [X] No

**Comment by andrasbacsai** [comment]
Pure Docker Compose based applications are services, as it could contain more than one applications/databases. The naming convention is not the best here. Later on I will update this, so everything will be a service. 

The services (one-click or pure docker compose based, so no git) does not have `/env...` endpoints. That is still missing.

**Comment by andrasbacsai** [comment]
If someone would like to add those endpoints (fairly simple, just need to copy from `/applications`) before I do, feel free to tell me here. :)

**Comment by galer7** [comment]
@andrasbacsai I can take it

**Comment by afunctional** [comment]
Hi! Is there something more i can do it for this issue? i've seen @galer7 PR and if i can contribute i'm interesting in the `good first issue` :)

**Comment by peaklabs-dev** [comment]
@andrasbacsai I believe this has been implemented. If not please reopen.

**Comment by Ibrvheem** [comment]
Has this issue been fixed? Still get a `404` when i try to update an env using `/application/${uuid}/envs`

**Comment by peaklabs-dev** [comment]
@Ibrvheem This issue was a feature request for a new API endpoint, if you have issues with this endpoint please open a new issue.
