### ISSUE TITLE
[Bug]: Nixpacks change version / config file not working

### ISSUE THREAD

**Issue by Flowko** [coollabsio/coolify#3324]
### Description

im currently facing issues deploying my monorepo, because im using the latest version of pnpm and `catalog:` which is not supported on the old version of nixpacks, just recently nixpacks added support for pnpm v9, i have `"packageManager": "pnpm@9.9.0",` and node engine set to 20, but the deployment always seems to use :
```
╔═══════════════════ Nixpacks v1.24.1 ══════════════════╗
║ setup │ nodejs_20, pnpm-8_x, openssl, curl, wget ║
║───────────────────────────────────────────────────────║
║ install │ pnpm install ║
║───────────────────────────────────────────────────────║
║ build │ pnpm build:next ║
║───────────────────────────────────────────────────────║
║ start │ pnpm start:next ║
╚═══════════════════════════════════════════════════════╝
```

i've also added a `nixpacks.toml` file in the parent folder, but coolify doesnt seem to be taking that into consideration when building the app:

```
buildImage = 'ghcr.io/railwayapp/nixpacks:ubuntu-1725321821'

[phases.install]
cmds = ["npm install -g corepack", "corepack enable", "corepack prepare pnpm@9.9.0 --activate", "pnpm install"]
```

would be greate to be able to change the nixpacks version to use the latest one

### Minimal Reproduction (if possible, example repository)

use `"packageManager": "pnpm@9.9.0",` in ur monorepo package.json file and the `catalog:` feature as well with some packages.

### Version

v4.0.0-beta.329

**Comment by Flowko** [comment]
@andrasbacsai is there a way to upgrade the nixpacks version ? im stuck here, i even had to test [Dokploy](https://dokploy.com/) just to make sure that is not the config, and it seems to deploy just fine there with that nixpacks config file, any ideas why its not using the config file i have inside of coolify ?

**Comment by peaklabs-dev** [comment]
@Flowko Nixpacks will be updated with the next version. Please wait for it to be released soon. And could you then please retest?

**Comment by Flowko** [comment]
ofc, thank you

**Comment by devhe4d** [comment]
my app deployment keep failing because of Nixpack issue, any way to at least get it work for now?

**Comment by LUK3D** [comment]
I'm stuck with the same issue. My app kepps restarting itself some some reasong  and the only log I get is `/bin/bash: -c: option requires an argument`

**Comment by andrasbacsai** [comment]
@devhe4d You have the same issue? Or some different?

@LUK3D That sounds like a different one. Do you have a start command set?
