### ISSUE TITLE
Getoutline service

### ISSUE THREAD

**Issue by andrasbacsai** [coollabsio/coolify#333]
https://app.getoutline.com/share/770a97da-13e5-401e-9f8a-37949c19f97e/doc/docker-7pfeLP5a8t

**Comment by compgeniuses** [comment]
@andrasbacsai   Kindly Add and Vote for this request here: https://feedback.coolify.io/

**Comment by andrasbacsai** [comment]
Closing this one in favor of: https://feedback.coolify.io/posts/58/service-getoutline
