### ISSUE TITLE
[Bug]: Upgrading coolify version causes scheduled database backups to fail

### ISSUE THREAD

**Issue by steventsvetkov** [coollabsio/coolify#3355]
### Description

After upgrading the coolify version, scheduled database backup start failing. It looks like it's unable to pull the `coolify-helper` image from ghcr and retries to do so at an impressive polling rate of `271.469µs`, quickly hitting the github API rate limit?

This is fixed by triggering a manual backup, after which scheduled backups start working as expected. Note that I have only one database running on my VPS, I'm not sure how it would behave with more than one. I've recently started using Coolify and I've upgraded twice so far, this issue appeared both times.

### Minimal Reproduction (if possible, example repository)

1. Create a new project and a stage environment for it.
1. Create a MongoDB database in stage with public access enabled.
2. Configure S3 storage using R2 Cloudflare
3. Setup automatic backups to trigger every hour and upload to S3
4. Upgrade the Coolify version using the UI
5. Database backups start failing
6. Trigger a manual backup to fix this issue.

### Exception or Error

Unable to find image 'ghcr.io/coollabsio/coolify-helper:latest' locally
docker: Error response from daemon: toomanyrequests: retry-after: 271.469µs, allowed: 44000/minute.
See 'docker run --help'.

DatabaseBackupJob failed with: Unable to find image 'ghcr.io/coollabsio/coolify-helper:latest' locally
latest: Pulling from coollabsio/coolify-helper
3c854c8cbf46: Pulling fs layer
d2aac0aefc71: Pulling fs layer
f9c396f433c8: Pulling fs layer
a9b023bc0a40: Pulling fs layer
74b8f2dbaf15: Pulling fs layer
4f4fb700ef54: Pulling fs layer
616e93ebdc58: Pulling fs layer
4f4fb700ef54: Waiting
616e93ebdc58: Waiting
a9b023bc0a40: Waiting
docker: error pulling image configuration: download failed after attempts=1: toomanyrequests: retry-after: 1.296341ms, allowed: 44000/minute.
See 'docker run --help'.

### Version

329

### Cloud?

- [ ] Yes
- [X] No

**Comment by peaklabs-dev** [comment]
This is fixed. Just waiting for andras to release the new version. https://github.com/coollabsio/coolify/pull/3353

**Comment by andrasbacsai** [comment]
Released a new version with this fix. Can you please update and let us know if it still occurs?

**Comment by steventsvetkov** [comment]
After updating, it failed again, this time by logging the following error twice

```
Failed to pull helper image: Error response from daemon: toomanyrequests: retry-after: 367.879µs, allowed: 44000/minute

Failed to pull helper image: Error response from daemon: toomanyrequests: retry-after: 367.879µs, allowed: 44000/minute
```

I "fixed" it once again by triggering a manual backup, after which scheduled backups work again. I'll post an update next time I upgrade coolify's version or if this occurs again in another context.

**Comment by peaklabs-dev** [comment]
@steventsvetkov That is a different error then the one I fixed whiche was this one.
```
DatabaseBackupJob failed with: Unable to find image 'ghcr.io/coollabsio/coolify-helper:latest' locally
```
I guess this needs more testing.

**Comment by peaklabs-dev** [comment]
Just found out that a simmilar rate limiting issue was already reported here: https://github.com/coollabsio/coolify/issues/2930

**Comment by steventsvetkov** [comment]
I also noticed that the same issue occurs when the `Force Docker Cleanup` option is turned on for the server that the database is on, which I guess is kind of expected, but I'm adding it here for the sake of completeness.

**Comment by andrasbacsai** [comment]
I have made a few improvements in the upcoming version. The helper image won't be pruned by Coolify's cleanup process, so it will be downloaded once.

Also the default cleanup schedule will be changed to run at midnight, not every 10 minutes (which is a bit agressive).

**Comment by dickwolff** [comment]
@andrasbacsai Would that not cause an issue when the backup is also run at midnight? Or will this be resolved by not pruning the helper image?

**Comment by steventsvetkov** [comment]
Could changing the cleanup schedule to once a day create possible disk space issues? Or is this only for the `Force Docker Cleanup` option - the cleanup will still run once the configured threshold % is reached, whenever that is?

**Comment by schliesser** [comment]
Heyho. having the same issue with the coolify scheduled updates which are timed around midnight. 
Manual execution works fine every time.
Version: 331
![image](https://github.com/user-attachments/assets/2a77920d-500d-48c3-b366-37383b2375c3)

**Comment by steventsvetkov** [comment]
I started getting the following error from the scheduled backups at around 7 AM UTC today, while still being on version 331. ```PullHelperImageJob failed with: Error response from daemon: toomanyrequests: retry-after: 1.257538ms, allowed: 44000/minute``` Probably something changed in the ghcr around that time?

After upgrading to 332, the error continues to log every time a scheduled backup runs.

Both on 331 and 332, the scheduled backups seem to run successfully produce a tar, even though there's an error logged. Manual backups work normally. I disabled `Force Docker Cleanup` a few days ago and still haven't turned it on, disk cleanup has not ran recently either.

**Comment by dickwolff** [comment]
I also had this warning from this morning 09:00 until 13:00. Between 13:00 and 14:00 I updated Coolify to 332 and the error did not come at 14:00. My backup schedule is at midnight, so I'm not sure if the error will appear in about 10 hours time..

**Comment by peaklabs-dev** [comment]
Please move dicussion to this new issue: https://github.com/coollabsio/coolify/issues/3395 (as this was a different issue)

**Comment by schliesser** [comment]
@peaklabs-dev I can confirm that this was fixed with 332 for my instance 🎉
