### ISSUE TITLE
cloudflare support

### ISSUE THREAD

**Issue by NovaStream2030** [coollabsio/coolify#34]
Hi, I tried to install coolify on a server proxied through cloudflare, but A record check prevents me from doing it. Will there be a fix for this in the future?

P.S. Good luck with development.

**Comment by andrasbacsai** [comment]
Yeah, I will try to fix it soon. With Cloudflare in front of your apps could get a ton of loads off from your server's shoulders, so it's a must-have!

**Comment by andrasbacsai** [comment]
Ok, I figured out a way. It works with my instance so that it will land soon in the codebase. 🎉

**Comment by andrasbacsai** [comment]
I've added Cloudflare support to the installation script. Please check and let me know if it's still not working!

**Comment by NovaStream2030** [comment]
Wow, it works!

**Comment by NovaStream2030** [comment]
I was in a hurry

![image](https://user-images.githubusercontent.com/21084913/115428613-c3aba980-a22c-11eb-95fd-2294bbc6cc7d.png)

**Comment by andrasbacsai** [comment]
Yes, that is a common problem with a reverse proxy behind Cloudflare. 

You need to set the `SSL/TLS Encryption` to `Full` or `Full(strict)` in your Cloudflare configuration.

Explanation here:
https://stackoverflow.com/questions/43645907/s3-and-cloudflare-flexible-ssl-handshakes

**Comment by NovaStream2030** [comment]
Thanks, everything works fine
