### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by chz** [coollabsio/coolify#340]
Reason: failed to create rwlayer: mkdir /var/lib/docker/overlay2/eb859c0d2f87114475bf0ecf3cf82b334ec131bd0d87508838639ffc067fbcb5/diff: no space left on device

How clear old docker images. i Think coolify must override old images

**Comment by chz** [comment]
I used command it fixed:

`
docker image prune -a --filter "until=24h"
`

But i think it must but automatically. @andrasbacsai

**Comment by andrasbacsai** [comment]
There is already a cron running that cleans up some parts of docker resources, but I set it a bit more "aggressive" in the next version. :)

**Comment by chz** [comment]
Thanks 👍🏼

**Comment by zek** [comment]
I see this error message too often. I'm not sure if this issue has been resolved

**Comment by fabianbru** [comment]
I am running into the same issue, my develop server was running full and manual cleanup with the "cleanup storage" button just gave me some MB of free storage. It's just a very small server with 20GB. (yes, I am under the minimum requirements of coolify, so it's in fact my own fault 😅)

My investigation on the server showed that there are many unused images of older coolify versions and older application commits laying around:
```
$ docker images

REPOSITORY                      TAG       IMAGE ID       CREATED        SIZE
clbwqepfj0000jv8nd1abcdef       9ab7897   8a248c93caa7   13 hours ago   1.19GB
clbwqepfj0000jv8nd1abcdef       2f1ae2d   6b0b99c7383a   14 hours ago   1.19GB
coollabsio/coolify              3.12.14   80e0415e2e26   2 days ago     1.19GB
coollabsio/coolify              3.12.13   f9c7a3e88e52   3 days ago     1.19GB
coollabsio/coolify              3.12.12   4f96c4cb11d0   5 days ago     1.19GB
coollabsio/coolify              3.12.11   d44389a964c6   6 days ago     1.19GB
clbwqepfj0000jv8nd1abcdef       5c19780   b8f1ac9b569c   8 days ago     1.19GB
clbwqepfj0000jv8nd1abcdef       009e23d   b49641a486de   8 days ago     1.2GB
clbwqepfj0000jv8nd1abcdef       6ae7040   39fd7fc91ce5   8 days ago     1.2GB
coollabsio/coolify              3.12.10   75c9c931925d   11 days ago    1.19GB
coollabsio/coolify              3.12.9    b3571743ed32   11 days ago    1.44GB
clbwqepfj0000jv8nd1abcdef       c5183a1   f66c72da286e   13 days ago    1.2GB
cl392mfk346517znxlqabcdef       d32adda   b08844338958   3 weeks ago    1.06GB
clbwqepfj0000jv8nd1abcdef       db22c7a   f74a11f8b5fd   3 weeks ago    1.19GB
clbwqepfj0000jv8nd1abcdef       4ce1337   b624b8334e16   3 weeks ago    1.19GB
clbwqepfj0000jv8nd1abcdef       da7f931   b8827b7b10e1   3 weeks ago    1.19GB
coollabsio/coolify              3.12.8    0e6a9def4825   3 weeks ago    1.43GB
clbwqepfj0000jv8nd1abcdef       92a9b2b   780d5d852dfe   3 weeks ago    1.19GB
coollabsio/coolify              3.12.6    d1cf87e64e41   3 weeks ago    1.43GB
clbwqepfj0000jv8nd1abcdef       d974cd4   d8af9b1358d1   3 weeks ago    1.19GB
clbwqepfj0000jv8nd1abcdef       ba361a0   60f3a8248e84   3 weeks ago    1.19GB
coollabsio/coolify-fluent-bit   1.0.0     5b5fe48a8623   2 months ago   66.8MB
<none>                          <none>    22c6901de2be   8 months ago   102MB

$ docker ps

CONTAINER ID   IMAGE                                 COMMAND                  CREATED        STATUS        PORTS                                                                      NAMES
896fdf146304   clbwqepfj0000jv8nd1abcdef:9ab7897     "docker-entrypoint.s…"   13 hours ago   Up 13 hours   8080/tcp                                                                   clbwqepfj0000jv8nd1abcdef
7275cef22526   coollabsio/coolify:3.12.14            "docker-entrypoint.s…"   2 days ago     Up 2 days     0.0.0.0:3000->3000/tcp, :::3000->3000/tcp                                  coolify
bca0aa26ff2b   coollabsio/coolify-fluent-bit:1.0.0   "/fluent-bit/bin/flu…"   2 days ago     Up 2 days     2020/tcp                                                                   coolify-fluentbit
c1ebb304cec4   cl392mfk346517znxlqabcdef:d32adda     "docker-entrypoint.s…"   3 weeks ago    Up 3 weeks    8080/tcp                                                                   cl392mfk346517znxlqabcdef
ad7f071ba758   22c6901de2be                          "/entrypoint.sh --en…"   7 months ago   Up 7 months   0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   coolify-proxy
```

So I cleaned them with:
**Attention:** this will remove the possibility to revert an application to an older commit! ⚠️ 
```
$ docker image prune -a

...
Total reclaimed space: 7.582GB
```

But two questions I was wondering:
1. why are there so many old coolify images around? shouldn't they be removed automatically?
2. is there a way to only allow a specific number of old application versions to revert to? or disable this completely (for develop servers)?

Like mentioned above, my disk space is under the required value, so perhaps this is my own fault. On the other hand would it be cool to have a cleanup logic that will clean up more images instead of running full, with the risk, that there is no fallback image.
Nevertheless, I am very happy with coolify and don't want to miss it, thanks! 👍

**Comment by chz** [comment]
There is already a cron running that cleans up some parts of docker resources, but I set it a bit more "aggressive" in the next version. :)

@andrasbacsai not work correctly

**Comment by chz** [comment]
Please check

**Comment by chz** [comment]
Im already done this with manually clickc "cleanup storage"

**Comment by Geczy** [comment]
the coolify cron doesnt seem to be running to clear up storage for me, why do i have to manually click cleanup?

**Comment by TryAndErr0r** [comment]
I had an issue where even the cleanup didnt work for me :( 

found this command `docker volume rm $(docker volume ls -qf dangling=true)` that removed a bunch of volumes and now my storage is free again :).

I am using docker-compose for my setup. 

Realy appreciate this project!

**Comment by hugocxl** [comment]
Same here. After less than 1 month of use almost reaching 95% out of 80GB of storage. 
Cleaning up as @fabianbru suggested => `Total reclaimed space: 54.25GB`

@andrasbacsai is this something on our side that we could prevent? Thanks for your time.

**Comment by saeedesmaili** [comment]
Same here. Ran the command after getting "low space" alert on my server, `Total reclaimed space: 5.736GB`.

**Comment by peaklabs-dev** [comment]
Activate force cleanup in the settings. Just updating to the latest version should fix that.

**Comment by namdien177** [comment]
Where is the force clean option? I remember seeing it somewhere but now I cannot find it anymore.

Also, the build cache is the one that takes the most diskspace for me. So to remove it, I have to use
``` sh
docker buildx prune --all
# and / or
docker builder prune --all
```

**Comment by Geczy** [comment]
i had to upgrade to 200gb storage space and don't have this issue anymore lol

slowly increasing again though, from 16% to 22% in 1.5 months

![image](https://github.com/user-attachments/assets/784947d3-0ad2-4b80-9ea0-9a6807267250)

![image](https://github.com/user-attachments/assets/0a380b68-b5c1-4daf-844c-b1974f34fb78)

**Comment by peaklabs-dev** [comment]
It is located under Servers and then Settings. You can set the frequency of the cleanup to run daily or once a week or something simmilar.
<img width="1362" alt="image" src="https://github.com/user-attachments/assets/ebe0afa4-3f5d-4f54-b11d-4c270e8f59b9">

**Comment by namdien177** [comment]
> It is located under Servers and then Settings. You can set the frequency of the cleanup to run daily or once a week or something simmilar. <img alt="image" width="1362" src="https://private-user-images.githubusercontent.com/122374094/369700455-ebe0afa4-3f5d-4f54-b11d-4c270e8f59b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwMjE0MDEsIm5iZiI6MTcyNzAyMTEwMSwicGF0aCI6Ii8xMjIzNzQwOTQvMzY5NzAwNDU1LWViZTBhZmE0LTNmNWQtNGY1NC1iMTFkLTRjMjcwZThmNTliOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMlQxNjA1MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYmVmYjc2Zjg0Zjc4NGEyZjQ1MzIwODVjMjY5MmRkZjM4ZTk4ZjFmOTAzYmIzZmIzY2E4YjUxOWUzYmViYTI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.pEL1e4znj_DkJ4JjkvswDV1f36XvUIcNJZQLoolOR9I">

I remember we had a button to "Force Clean" or something like that before, right? anyway, thanks for the help.

**Comment by peaklabs-dev** [comment]
No, there was never a button, but since you mention it, that would be a nice addition to add. Will add that.

**Comment by peaklabs-dev** [comment]
@namdien177 The button to manually clean up will be added in one of the next versions via this PR https://github.com/coollabsio/coolify/pull/3545.

**Comment by peaklabs-dev** [comment]
@TryAndErr0r I also added an optional option to delete unused volumes during cleanup. 

I will lock this issue so we do not have to dig into already closed issues in the future. If there are bugs, open a new [Issue](https://github.com/coollabsio/coolify/discussions), if you have more feature suggestions or improvements, open a [GitHub discussion](https://github.com/coollabsio/coolify/discussions).
