### ISSUE TITLE
[Bug]: PHP Fatal error:  Uncaught PDOException: SQLSTATE[08006] [7] could not translate host name "postgres" to address: Temporary failure in name resolution

### ISSUE THREAD

**Issue by radud** [coollabsio/coolify#3401]
### Description

Since yesterday I cannot access the Coolify admin panel. In the docker logs I get this error:

2024/09/12 05:57:29 [error] 144#144: *244358 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[08006] [7] could not translate host name "postgres" to address: Temporary failure in name resolution in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:65
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(65): PDO->__construct()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(83): Illuminate\Database\Connectors\Connector->createPdoConnection()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(48): Illuminate\Database\Connectors\Connector->tryAgainIfCausedByLostConnection()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/PostgresConnector.php(35): Illuminate\Database\Connectors\Connector->createConnection()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(185): Illuminate\Database\Con...; PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[08006] [7] could not translate host name "postgres" to address: Temporary failure in name resolution in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:65
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(65): PDO->__construct()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(83): Illuminate\Database\Connectors\Connector->createPdoConnection()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(48): Illuminate\Database\Connectors\Connector->tryAgainIfCausedByLostConnection()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/PostgresConnector.php(35): Illuminate\Database\Connectors\Connector->createConnection()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors

These are my coolify containers running:
CONTAINER ID   IMAGE                                              COMMAND                  CREATED        STATUS                  PORTS                                                              NAMES
3a5f5f2656e1   postgres:15-alpine                                 "docker-entrypoint.s…"   7 days ago     Created                                                                                    coolify-db
aad73ce1bdef   quay.io/soketi/soketi:1.6-16-alpine                "node /app/bin/serve…"   7 days ago     Created                                                                                    coolify-realtime
1992cbba487b   redis:alpine                                       "docker-entrypoint.s…"   7 days ago     Created                                                                                    coolify-redis
dcef0b039584   ghcr.io/coollabsio/coolify:4.0.0-beta.325          "/init"                  9 days ago     Up 9 days (unhealthy)   443/tcp, 8000/tcp, 9000/tcp, 0.0.0.0:8000->80/tcp                  coolify
e6c28311bf75   traefik:v2.10                                      "/entrypoint.sh --pi…"   2 months ago   Up 2 months (healthy)   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:8080->8080/tcp   coolify-proxy

Anyone facing the same issue? 

### Minimal Reproduction (if possible, example repository)

I don't know how to reproduce. I suspect it is after latest update. 
Can provide credential to the affected server

### Exception or Error

2024/09/12 05:57:29 [error] 144#144: *244358 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[08006] [7] could not translate host name "postgres" to address: Temporary failure in name resolution in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:65
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(65): PDO->__construct()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(83): Illuminate\Database\Connectors\Connector->createPdoConnection()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(48): Illuminate\Database\Connectors\Connector->tryAgainIfCausedByLostConnection()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/PostgresConnector.php(35): Illuminate\Database\Connectors\Connector->createConnection()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(185): Illuminate\Database\Con...; PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[08006] [7] could not translate host name "postgres" to address: Temporary failure in name resolution in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:65
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(65): PDO->__construct()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(83): Illuminate\Database\Connectors\Connector->createPdoConnection()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(48): Illuminate\Database\Connectors\Connector->tryAgainIfCausedByLostConnection()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/PostgresConnector.php(35): Illuminate\Database\Connectors\Connector->createConnection()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors

### Version

4.0.0-beta.325

### Cloud?

- [ ] Yes
- [X] No

**Comment by halimb** [comment]
Same here, since 33 hours ago

```
CONTAINER ID   IMAGE                                                               COMMAND                  CREATED        STATUS                   PORTS                                                                                                                 NAMES
c3fb01c21cc8   postgres:15-alpine                                                  "docker-entrypoint.s…"   33 hours ago   Created                                                                                                                                        coolify-db
b495c46b22f4   redis:alpine                                                        "docker-entrypoint.s…"   33 hours ago   Created                                                                                                                                        coolify-redis
1c4735b57119   quay.io/soketi/soketi:1.6-16-alpine                                 "node /app/bin/serve…"   33 hours ago   Created                                                                                                                                        coolify-realtime

```

**Comment by sneko** [comment]
@andrasbacsai I don't know if it's related to @halimb but I faced this too after an upgrade from `v4.0.0-beta.332` to `v4.0.0-beta.334`.

_Note aside: when upgrading, there is a risk of clicking 2 times. The button has no lock while performing the `/update` request, I don't know if there is a lock on the backend side but I guess it could mess with some files._

**Comment by andrasbacsai** [comment]
Hmm. I will investigate, but to quickly fix this issue, execute the installation script on your server. That will restart your Coolify instance.

`curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash`


> _Note aside: when upgrading, there is a risk of clicking 2 times. The button has no lock while performing the `/update` request, I don't know if there is a lock on the backend side but I guess it could mess with some files._

It is handled on the backend on the current page load, but if you refresh the page and try again, it is not. So I will fix it
