### ISSUE TITLE
[Bug]: Prevent double update 

### ISSUE THREAD

**Issue by andrasbacsai** [coollabsio/coolify#3407]
### Description

If you click on the manual update and refresh the window, you can click it again. 

- Should be a database entry that saves the inprogress state, set it to true.
- On Coolify start (init script) should set it to false.

### Minimal Reproduction (if possible, example repository)

Just as I said.

### Version

latest

### Cloud?

- [ ] Yes
- [X] No

**Comment by peaklabs-dev** [comment]
Dicussion: https://github.com/coollabsio/coolify/discussions/3687
