### ISSUE TITLE
[Bug]: Updating gives Error response from daemon: Head "https://ghcr.io/v2/coollabsio/coolify-helper/manifests/1.0.1": denied: denied.

### ISSUE THREAD

**Issue by SGiumelli** [coollabsio/coolify#3412]
### Description

Updating from the server with `curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash`

docker: Error response from daemon: Head "https://ghcr.io/v2/coollabsio/coolify-helper/manifests/1.0.1": denied: denied.

### Minimal Reproduction (if possible, example repository)

connect to VPS :
run `curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash`

### Exception or Error

```
Welcome to Coolify v4 beta installer!
This script will install everything for you.
Source code: https://github.com/coollabsio/coolify/blob/main/scripts/install.sh

-------------
OS: ubuntu 22.04
Coolify version: 4.0.0-beta.335
Helper version: 1.0.1
-------------
Installing required packages...
OpenSSH server is installed.
OpenSSH server is installed.
PermitRootLogin is enabled.
-------------
Check Docker Configuration...
Docker configuration is up to date.
-------------
Downloading required files from CDN...
File exists: /data/coolify/source/.env
Copying .env to .env-20240912-155341
Updating .env with new values (if necessary)...
Unable to find image 'ghcr.io/coollabsio/coolify-helper:1.0.1' locally
docker: Error response from daemon: Head "https://ghcr.io/v2/coollabsio/coolify-helper/manifests/1.0.1": denied: denied.
```

### Version

4.0.0-beta.331

### Cloud?

- [ ] Yes
- [X] No

**Comment by scflode** [comment]
I have the same exact issue. Couldn't update via UI then ssh'd into the server and ran the given command. Does anyone have any hints what might be the issue here?

**Comment by scflode** [comment]
```
...
9. Installing Coolify (4.0.0-beta.355)
 - It could take a while based on your server's performance, network speed, stars, etc.
 - Please wait.
 - Until then, here's a joke for you:

A programmer puts two glasses on his bedside table before going to sleep.
A full one, in case he gets thirsty, and an empty one, in case he doesn't.

Unable to find image 'ghcr.io/coollabsio/coolify-helper:1.0.2' locally
docker: Error response from daemon: Head "https://ghcr.io/v2/coollabsio/coolify-helper/manifests/1.0.2": denied: denied.
See 'docker run --help'.
```
with debug
```
+ echo -e '9. Installing Coolify (4.0.0-beta.355)'
9. Installing Coolify (4.0.0-beta.355)
+ echo -e ' - It could take a while based on your server'\''s performance, network speed, stars, etc.'
 - It could take a while based on your server's performance, network speed, stars, etc.
+ echo -e ' - Please wait.'
 - Please wait.
+ getAJoke
++ curl -s --max-time 2 'https://v2.jokeapi.dev/joke/Programming?blacklistFlags=nsfw,religious,political,racist,sexist,explicit&format=txt&type=single'
+ JOKES='There are only 10 kinds of people in this world: those who know binary and those who don'\''t.'
+ '[' 'There are only 10 kinds of people in this world: those who know binary and those who don'\''t.' '!=' '' ']'
+ echo -e ' - Until then, here'\''s a joke for you:\n'
 - Until then, here's a joke for you:

+ echo -e 'There are only 10 kinds of people in this world: those who know binary and those who don'\''t.\n'
There are only 10 kinds of people in this world: those who know binary and those who don't.

+ bash /data/coolify/source/upgrade.sh 4.0.0-beta.355 1.0.2
Unable to find image 'ghcr.io/coollabsio/coolify-helper:1.0.2' locally
docker: Error response from daemon: Head "https://ghcr.io/v2/coollabsio/coolify-helper/manifests/1.0.2": denied: denied.
See 'docker run --help'.
```

**Comment by peaklabs-dev** [comment]
Can you please check a few things for me:
1. Do you have ufw and/or a firewall set to block outgoing connections to port 443?
```bash
ping -c 4 ghcr.io
```
2. Are you logged in to ghcr on your server? if so, can you log out and try again?

**Comment by scflode** [comment]
First off: Thanks for the quick reply.

For the check list:

1. Ping works OK
2. That seems to have been the cause. I wasn't logged in anymore. I'm wondering if it was necessary in the past for the general installation. I just can recall to have to setup a PAT for the deployment (image building) on Coolify. Was there a change or just a gap in my memory?

**Comment by scflode** [comment]
A possible improvement via CLI could be to check if authenticated to the registry if this is a requirement and either promt to login or give an error message to tell to authenticate to the GH registry in order to install. Maybe I forgot about that but a PAT can expire and the error message is a bit confusing if you forgot about the registry authentication.

**Comment by peaklabs-dev** [comment]
The point is you should NOT need to login it should just work, no idea yet on why it is not working for you.

**Comment by scflode** [comment]
I have the suspicion that because I use the GH registry for deployment builds and this PAT did expire that the login was stale. I can test whether an explicit logout works tomorrow.

**Comment by peaklabs-dev** [comment]
Yes I think the issue is if your PAT has expired you will get this error, the fix is to logout or renew your PAT, I will think of a way I can add this to the docs but for now we cannot do anything else. In the future, docker image management including repository accounts will be handled in Coolify instead of the server, which will fix this. Tracked via this feature request: https://github.com/coollabsio/coolify/issues/2499

**Comment by SGiumelli** [comment]
Yes, this is it ! Thank you !

**Comment by peaklabs-dev** [comment]
I have updated the documentation with the details that will resolve this issue. It will be available soon.
