### ISSUE TITLE
[Bug]: coolify.io not updated for some time?

### ISSUE THREAD

**Issue by drubb** [coollabsio/coolify#3439]
### Description

While we're currently at v4.0.0-beta.335, coolify.io dashboard still shows v4.0.0-beta.323
Haven't there been updates for some time?

![image](https://github.com/user-attachments/assets/edae2015-23e5-4a76-ad30-8c059bc06a68)

### Minimal Reproduction (if possible, example repository)

Check the current version displayed in the upper left corner.

### Version

v4.0.0-beta.323

### Cloud?

- [X] Yes
- [ ] No

**Comment by peaklabs-dev** [comment]
This is intended. Read more about it here: https://github.com/coollabsio/coolify/blob/main/RELEASE.md
