### ISSUE TITLE
[Bug]: Error on postgres backup

### ISSUE THREAD

**Issue by klawdyo** [coollabsio/coolify#3448]
### Description

![image](https://github.com/user-attachments/assets/6775fd5f-ddfe-4d1d-aec0-44c143b662e6)
![image](https://github.com/user-attachments/assets/ce71cacd-06fc-4b2e-b739-0a2dc9fc86d0)

I don't know what is this!!

### Minimal Reproduction (if possible, example repository)

I'm just trying to backup a PostgreSQL database and it's giving this message and failing. The other backups worked in the previous days.

What can I do to prevent this error from happening?

### Version

v4.0.0-beta.335

### Cloud?

- [ ] Yes
- [X] No

**Comment by klawdyo** [comment]
![image](https://github.com/user-attachments/assets/3bcb3e00-c2b7-451f-883e-0db5b6fe2c7e)

**Comment by fabieu** [comment]
I am experiencing this issue as well. I am using `v4.0.0-beta.335`. 
This is only the case if the option `S3 Enabled` is ticked. Local backups are working as intended.

**Comment by Hexacker** [comment]
I have faced the same issue with the same version, the only solution works was downgrading to version 333
There is a new release that fixes it I think.

**Comment by fabieu** [comment]
> I have faced the same issue with the same version, the only solution works was downgrading to version 333 There is a new release that fixes it I think.

You are correct: https://github.com/coollabsio/coolify/releases/tag/v4.0.0-beta.336 reverts the database backup changes.

**Comment by Hexacker** [comment]
Have you upgraded to that version, does it really fixes it?

**Comment by fabieu** [comment]
> Have you upgraded to that version, does it really fixes it?

Yes it does, but the version `v4.0.0-beta.336`,  which is currently in the nightly release, has some other issues. So I do not recommend updating right now.

**Comment by Hexacker** [comment]
Issues like, could you mention some?

**Comment by klawdyo** [comment]
> I am experiencing this issue as well. I am using `v4.0.0-beta.335`. 
> The error occurs only if the option `S3 Enabled` is ticked. Local backups are working as intended.

In my case, only this service is experiencing an error. The error also seems to be related to a duplicate port or the Coolify Proxy itself. The problem is that there is no duplicate port. If I change the port, it will say that the new port is also duplicated. It is some bug in the Coolify health check. I just don't understand why this is only happening with this service.

**Comment by klawdyo** [comment]
Updated to v4.0.0-beta.338. Postgresql backups working.

However, mysql backups are not working.
When I force the backup, it shows a message saying that the backup has been queued, but it does not show this backup in progress in the list.
I accessed S3 now and noticed that my database has not been backed up since September 8th.

**Comment by klawdyo** [comment]
https://github.com/user-attachments/assets/a374cf99-ac73-4787-9428-d5c55f817066
