### ISSUE TITLE
[Bug]: Plausible

### ISSUE THREAD

**Issue by jln13x** [coollabsio/coolify#3455]
### Description

Couldnt get Plausible to work and rooted the problem down to `SERVICE_BASE64_64_PLAUSIBLE` environment variable. 

We are referencing this variable from `SECRET_KEY_BASE` - which is expected to be atleast 64 bytes long but generated variable in `SERVICE_BASE64_64_PLAUSIBLE` was only 32 bytes long for me. Couldn't find where this variable gets generated. 

I fixed it for now by generating a 64 byte string `openssl rand -base64 64` by myself and pasting it as the value for `SERVICE_BASE64_64_PLAUSIBLE`

### Minimal Reproduction (if possible, example repository)

Follow the docs https://coolify.io/docs/services/plausible

### Exception or Error
Logs from Plausible Container
```
** (ArgumentError) cookie store expects conn.secret_key_base to be at least 64 bytes
```

### Version

335

### Cloud?

- [ ] Yes
- [X] No

**Comment by diogox** [comment]
Same here. Fixed it the same way.

**Comment by dreadedhamish** [comment]
Old issue that was marked as fixed but wasn't/
https://github.com/coollabsio/coolify/issues/1449

**Comment by AndreiHudovich** [comment]
I just faced the same issue, fixed it with OP's `openssl rand -base64 64`. Thanks, man!

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.
