### ISSUE TITLE
[Bug]: S3 Backups on secondary server broken "No such container: coolify"

### ISSUE THREAD

**Issue by delassiter** [coollabsio/coolify#3458]
### Error Message and Logs

```
Error response from daemon: No such container: coolify
``` 

### Steps to Reproduce

1. Install a new server (next to your main Coolify server)
2. Add a MariaDB instance to new server
3. Schedule Backups for MariaDB instance with S3 enabled
4. Click "Backup now" or wait for Backup Job to be executed

### Coolify Version

v4.0.0-beta.335

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04.1 LTS

### Additional Information

Problems with backups started occuring a couple of versions back. This issue started with v4.0.0-beta.334, I think.

**Comment by peaklabs-dev** [comment]
This has been fixed, version will be released tomorrow.

**Comment by delassiter** [comment]
Thanks for the quick response and for fixing the bug! Also thank you for your amazing work!
