### ISSUE TITLE
[Bug]: logto

### ISSUE THREAD

**Issue by moshetanzer** [coollabsio/coolify#3461]
### Error Message and Logs

Admin_endpoint and endpoint not set defaulting to empty string

### Steps to Reproduce

Install logto using one click solution on v 335

### Coolify Version

335

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu latest

### Additional Information

No link to access dashboard because of this.

**Comment by Yousema** [comment]
I had a similar problem.
I add LOGTO_ENDPOINT and LOGTO_ADMIN_ENDPOINT to the Environment Variables and redeploy. 
Problem "fixed"!

**Comment by peaklabs-dev** [comment]
This issue has been fixed in the latest version.
