### ISSUE TITLE
[Bug]: Unable to access Terminal (code 500)

### ISSUE THREAD

**Issue by alexzvn** [coollabsio/coolify#3462]
### Error Message and Logs

![image](https://github.com/user-attachments/assets/15c512b6-8a85-47d6-8bcc-38a380958bb2)

### Steps to Reproduce

1. Update to `v4.0.0-beta.337`
2. Visit `Dashboard` > `Terminal`

### Coolify Version

v4.0.0-beta.337

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.
