### ISSUE TITLE
[Bug]: terminal keeps disconnecting

### ISSUE THREAD

**Issue by isaacfink** [coollabsio/coolify#3465]
### Error Message and Logs

I get a popup saying 
```
Connection to terminal lost, please refresh the page.
```
It keeps popping up like every 500ms or so

### Steps to Reproduce

Not sure, it happened as soon as I upgraded to v4.0.0-beta.338

### Coolify Version

v4.0.0-beta.338

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

ubuntu 24.04

### Additional Information

Full out put of `cat /etc/os-release`

```
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```

**Comment by diogox** [comment]
I'm not able to connect to the terminal. Get that error every time I click `Connect`

**Comment by andrasbacsai** [comment]
Please update to v340, and let me know if it still exists.

If it still exists, please let me know how do you host your Coolify instance (normally, through Cloudflare Tunnels, etc).

**Comment by isaacfink** [comment]
Still doesn't work, different error though, when I click connect nothing happens and I see this in the console
```
VM790:137 WebSocket is already in CLOSING or CLOSED state.
```

**Comment by LEstradioto** [comment]
Can someone access Coolify server and executes a docker command to get terminal logs? 
run `docker logs coolify-realtime`
that would be helpful to debug this, thanks!

**Comment by nathanialhenniges** [comment]
> Please update to v340, and let me know if it still exists.
> 
> If it still exists, please let me know how do you host your Coolify instance (normally, through Cloudflare Tunnels, etc).

am having the same issue and am using Cloudflare Tunnels

**Comment by isaacfink** [comment]
I upgraded to v340 and it's still happening

**Comment by isaacfink** [comment]
347 works fine
