### ISSUE TITLE
[Bug]: failed to solve: process "/bin/bash -ol pipefail -c bun run build"

### ISSUE THREAD

**Issue by theodufort** [coollabsio/coolify#3485]
### Error Message and Logs

2024-Sep-18 15:23:20.895737
Starting deployment of theodufort/book-journey:main to localhost.
2024-Sep-18 15:23:21.151757
Preparing container with helper image: ghcr.io/coollabsio/coolify-helper:1.0.1.
2024-Sep-18 15:23:21.286657
docker rm -f vw4kwkgkc4gg404s8s48sk48
2024-Sep-18 15:23:21.286657
Error response from daemon: No such container: vw4kwkgkc4gg404s8s48sk48
2024-Sep-18 15:23:21.537257
docker run -d --network coolify --name vw4kwkgkc4gg404s8s48sk48 --rm -v /var/run/docker.sock:/var/run/docker.sock ghcr.io/coollabsio/coolify-helper:1.0.1
2024-Sep-18 15:23:21.537257
067834bdd7e8663410deac0616447e4edc635840093cf55e736c8f2d5e390ba5
2024-Sep-18 15:23:23.754337
docker exec vw4kwkgkc4gg404s8s48sk48 bash -c 'GIT_SSH_COMMAND="ssh -o ConnectTimeout=30 -p 22 -o Port=22 -o LogLevel=ERROR -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" git ls-remote [https://x-access-token:<REDACTED>@github.com/theodufort/book-journey.git](https://x-access-token:%3CREDACTED%3E@github.com/theodufort/book-journey.git) main'
2024-Sep-18 15:23:23.754337
0d2ea2b8a33d45d9ed10212e9870ae7a5ba381dd	refs/heads/main
2024-Sep-18 15:23:23.939578
Image not found (d0ccok8kg8404ogw88sskowc:0d2ea2b8a33d45d9ed10212e9870ae7a5ba381dd). Building new image.
2024-Sep-18 15:23:24.320552
----------------------------------------
2024-Sep-18 15:23:24.323792
Importing theodufort/book-journey:main (commit sha HEAD) to /artifacts/vw4kwkgkc4gg404s8s48sk48.
2024-Sep-18 15:23:24.576484
docker exec vw4kwkgkc4gg404s8s48sk48 bash -c 'git clone -b "main" [https://x-access-token:<REDACTED>@github.com/theodufort/book-journey.git](https://x-access-token:%3CREDACTED%3E@github.com/theodufort/book-journey.git) /artifacts/vw4kwkgkc4gg404s8s48sk48 && cd /artifacts/vw4kwkgkc4gg404s8s48sk48 && GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" git submodule update --init --recursive && cd /artifacts/vw4kwkgkc4gg404s8s48sk48 && GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" git lfs pull'
2024-Sep-18 15:23:24.576484
Cloning into '/artifacts/vw4kwkgkc4gg404s8s48sk48'...
2024-Sep-18 15:23:29.076334
docker exec vw4kwkgkc4gg404s8s48sk48 bash -c 'cd /artifacts/vw4kwkgkc4gg404s8s48sk48 && git log -1 0d2ea2b8a33d45d9ed10212e9870ae7a5ba381dd --pretty=%B'
2024-Sep-18 15:23:29.076334
add ci
2024-Sep-18 15:23:29.328303
Generating nixpacks configuration with: nixpacks plan -f toml  /artifacts/vw4kwkgkc4gg404s8s48sk48
2024-Sep-18 15:23:29.749528
docker exec vw4kwkgkc4gg404s8s48sk48 bash -c 'nixpacks plan -f toml  /artifacts/vw4kwkgkc4gg404s8s48sk48'
2024-Sep-18 15:23:29.749528
providers = []
2024-Sep-18 15:23:29.749528
buildImage = 'ghcr.io/railwayapp/nixpacks:ubuntu-1725321821'
2024-Sep-18 15:23:29.749528
2024-Sep-18 15:23:29.749528
[variables]
2024-Sep-18 15:23:29.749528
CI = 'true'
2024-Sep-18 15:23:29.749528
NIXPACKS_METADATA = 'node'
2024-Sep-18 15:23:29.749528
NODE_ENV = 'production'
2024-Sep-18 15:23:29.749528
NPM_CONFIG_PRODUCTION = 'false'
2024-Sep-18 15:23:29.749528
[phases.build]
2024-Sep-18 15:23:29.749528
dependsOn = ['install']
2024-Sep-18 15:23:29.749528
cmds = ['bun run build']
2024-Sep-18 15:23:29.749528
cacheDirectories = [
2024-Sep-18 15:23:29.749528
    '.next/cache',
2024-Sep-18 15:23:29.749528
    'node_modules/.cache',
2024-Sep-18 15:23:29.749528
]
2024-Sep-18 15:23:29.749528
2024-Sep-18 15:23:29.749528
[phases.install]
2024-Sep-18 15:23:29.749528
dependsOn = ['setup']
2024-Sep-18 15:23:29.749528
cmds = ['npm ci']
2024-Sep-18 15:23:29.749528
cacheDirectories = ['/root/.bun']
2024-Sep-18 15:23:29.749528
paths = ['/app/node_modules/.bin']
2024-Sep-18 15:23:29.749528
2024-Sep-18 15:23:29.749528
[phases.setup]
2024-Sep-18 15:23:29.749528
nixPkgs = [
2024-Sep-18 15:23:29.749528
    'nodejs_18',
2024-Sep-18 15:23:29.749528
    'bun',
2024-Sep-18 15:23:29.749528
]
2024-Sep-18 15:23:29.749528
nixOverlays = ['https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz']
2024-Sep-18 15:23:29.749528
nixpkgsArchive = 'e05605ec414618eab4a7a6aea8b38f6fbbcc8f08'
2024-Sep-18 15:23:29.749528
2024-Sep-18 15:23:29.749528
[start]
2024-Sep-18 15:23:29.749528
cmd = 'bun run start'
2024-Sep-18 15:23:30.020703
docker exec vw4kwkgkc4gg404s8s48sk48 bash -c 'nixpacks detect /artifacts/vw4kwkgkc4gg404s8s48sk48'
2024-Sep-18 15:23:30.020703
node
2024-Sep-18 15:23:30.029436
Found application type: node.
2024-Sep-18 15:23:30.032229
If you need further customization, please check the documentation of Nixpacks: https://nixpacks.com/docs/providers/node
2024-Sep-18 15:23:30.041006
Final Nixpacks plan: {
2024-Sep-18 15:23:30.041006
    "providers": [],
2024-Sep-18 15:23:30.041006
    "buildImage": "ghcr.io\/railwayapp\/nixpacks:ubuntu-1725321821",
2024-Sep-18 15:23:30.041006
    "variables": {
2024-Sep-18 15:23:30.041006
        "SOURCE_COMMIT": "0d2ea2b8a33d45d9ed10212e9870ae7a5ba381dd",
2024-Sep-18 15:23:30.041006
        "CI": "true",
2024-Sep-18 15:23:30.041006
        "NIXPACKS_METADATA": "node",
2024-Sep-18 15:23:30.041006
        "NODE_ENV": "production",
2024-Sep-18 15:23:30.041006
        "NPM_CONFIG_PRODUCTION": "false"
2024-Sep-18 15:23:30.041006
    },
2024-Sep-18 15:23:30.041006
    "phases": {
2024-Sep-18 15:23:30.041006
        "build": {
2024-Sep-18 15:23:30.041006
            "dependsOn": [
2024-Sep-18 15:23:30.041006
                "install"
2024-Sep-18 15:23:30.041006
            ],
2024-Sep-18 15:23:30.041006
            "cmds": [
2024-Sep-18 15:23:30.041006
                "bun run build"
2024-Sep-18 15:23:30.041006
            ],
2024-Sep-18 15:23:30.041006
            "cacheDirectories": [
2024-Sep-18 15:23:30.041006
                ".next\/cache",
2024-Sep-18 15:23:30.041006
                "node_modules\/.cache"
2024-Sep-18 15:23:30.041006
            ]
2024-Sep-18 15:23:30.041006
        },
2024-Sep-18 15:23:30.041006
        "install": {
2024-Sep-18 15:23:30.041006
            "dependsOn": [
2024-Sep-18 15:23:30.041006
                "setup"
2024-Sep-18 15:23:30.041006
            ],
2024-Sep-18 15:23:30.041006
            "cmds": [
2024-Sep-18 15:23:30.041006
                "npm ci"
2024-Sep-18 15:23:30.041006
            ],
2024-Sep-18 15:23:30.041006
            "cacheDirectories": [
2024-Sep-18 15:23:30.041006
                "\/root\/.bun"
2024-Sep-18 15:23:30.041006
            ],
2024-Sep-18 15:23:30.041006
            "paths": [
2024-Sep-18 15:23:30.041006
                "\/app\/node_modules\/.bin"
2024-Sep-18 15:23:30.041006
            ]
2024-Sep-18 15:23:30.041006
        },
2024-Sep-18 15:23:30.041006
        "setup": {
2024-Sep-18 15:23:30.041006
            "nixPkgs": [
2024-Sep-18 15:23:30.041006
                "nodejs_18",
2024-Sep-18 15:23:30.041006
                "bun"
2024-Sep-18 15:23:30.041006
            ],
2024-Sep-18 15:23:30.041006
            "nixOverlays": [
2024-Sep-18 15:23:30.041006
                "https:\/\/github.com\/railwayapp\/nix-npm-overlay\/archive\/main.tar.gz"
2024-Sep-18 15:23:30.041006
            ],
2024-Sep-18 15:23:30.041006
            "nixpkgsArchive": "e05605ec414618eab4a7a6aea8b38f6fbbcc8f08",
2024-Sep-18 15:23:30.041006
            "aptPkgs": [
2024-Sep-18 15:23:30.041006
                "curl",
2024-Sep-18 15:23:30.041006
                "wget"
2024-Sep-18 15:23:30.041006
            ]
2024-Sep-18 15:23:30.041006
        }
2024-Sep-18 15:23:30.041006
    },
2024-Sep-18 15:23:30.041006
    "start": {
2024-Sep-18 15:23:30.041006
        "cmd": "bun run start"
2024-Sep-18 15:23:30.041006
    }
2024-Sep-18 15:23:30.041006
}
2024-Sep-18 15:23:30.926737
----------------------------------------
2024-Sep-18 15:23:30.935754
Building docker image started.
2024-Sep-18 15:23:30.938758
To check the current progress, click on Show Debug Logs.
2024-Sep-18 15:23:31.476034
docker exec vw4kwkgkc4gg404s8s48sk48 bash -c 'nixpacks build -c /artifacts/thegameplan.json --cache-key 'd0ccok8kg8404ogw88sskowc' --no-error-without-start -n d0ccok8kg8404ogw88sskowc:0d2ea2b8a33d45d9ed10212e9870ae7a5ba381dd /artifacts/vw4kwkgkc4gg404s8s48sk48 -o /artifacts/vw4kwkgkc4gg404s8s48sk48'
2024-Sep-18 15:23:31.476034
2024-Sep-18 15:23:31.476034
╔════════════ Nixpacks v1.28.0 ═══════════╗
2024-Sep-18 15:23:31.476034
║ setup      │ nodejs_18, bun, curl, wget ║
2024-Sep-18 15:23:31.476034
║─────────────────────────────────────────║
2024-Sep-18 15:23:31.476034
║ install    │ npm ci                     ║
2024-Sep-18 15:23:31.476034
║─────────────────────────────────────────║
2024-Sep-18 15:23:31.476034
║ build      │ bun run build              ║
2024-Sep-18 15:23:31.476034
║─────────────────────────────────────────║
2024-Sep-18 15:23:31.476034
║ start      │ bun run start              ║
2024-Sep-18 15:23:31.476034
╚═════════════════════════════════════════╝
2024-Sep-18 15:23:31.480072
Saved output to:
2024-Sep-18 15:23:31.480072
  /artifacts/vw4kwkgkc4gg404s8s48sk48
2024-Sep-18 15:23:31.851180
docker exec vw4kwkgkc4gg404s8s48sk48 bash -c 'cat /artifacts/build.sh'
2024-Sep-18 15:23:31.851180
docker build --add-host coolify:172.18.0.5 --add-host coolify-db:172.18.0.2 --add-host coolify-realtime:172.18.0.4 --add-host coolify-redis:172.18.0.3 --network host -f /artifacts/vw4kwkgkc4gg404s8s48sk48/.nixpacks/Dockerfile --build-arg SOURCE_COMMIT="0d2ea2b8a33d45d9ed10212e9870ae7a5ba381dd" --build-arg 'COOLIFY_URL=https://d0ccok8kg8404ogw88sskowc.techworkshop.ca'/ --build-arg 'COOLIFY_FQDN=d0ccok8kg8404ogw88sskowc.techworkshop.ca' --build-arg 'COOLIFY_BRANCH="main"' --build-arg 'COOLIFY_CONTAINER_NAME="d0ccok8kg8404ogw88sskowc-152319632732"' --build-arg 'COOLIFY_APP_NAME="theodufort/book-journey:main-d0ccok8kg8404ogw88sskowc"' --build-arg 'COOLIFY_SERVER_IP="host.docker.internal"' --build-arg 'COOLIFY_ENVIRONMENT_NAME="production"' --build-arg 'COOLIFY_PROJECT_NAME="MyBookQuest"' --progress plain -t d0ccok8kg8404ogw88sskowc:0d2ea2b8a33d45d9ed10212e9870ae7a5ba381dd /artifacts/vw4kwkgkc4gg404s8s48sk48
2024-Sep-18 15:23:32.832563
docker exec vw4kwkgkc4gg404s8s48sk48 bash -c 'bash /artifacts/build.sh'
2024-Sep-18 15:23:32.832563
#0 building with "default" instance using docker driver
2024-Sep-18 15:23:32.832563
2024-Sep-18 15:23:32.832563
#1 [internal] load build definition from Dockerfile
2024-Sep-18 15:23:33.017407
#1 transferring dockerfile: 1.21kB done
2024-Sep-18 15:23:33.017407
#1 DONE 0.0s
2024-Sep-18 15:23:33.017407
2024-Sep-18 15:23:33.017407
#2 [internal] load metadata for ghcr.io/railwayapp/nixpacks:ubuntu-1725321821
2024-Sep-18 15:23:33.541154
#2 DONE 0.7s
2024-Sep-18 15:23:33.686225
#3 [internal] load .dockerignore
2024-Sep-18 15:23:33.686225
#3 transferring context: 2B done
2024-Sep-18 15:23:33.686225
#3 DONE 0.0s
2024-Sep-18 15:23:33.686225
2024-Sep-18 15:23:33.686225
#4 [stage-0  1/11] FROM ghcr.io/railwayapp/nixpacks:ubuntu-1725321821@sha256:0cec4cb236c32e6bc58b896fff852f629a7abad4e4f059840d96f0869b4be2fd
2024-Sep-18 15:23:33.686225
#4 DONE 0.0s
2024-Sep-18 15:23:33.686225
2024-Sep-18 15:23:33.686225
#5 [internal] load build context
2024-Sep-18 15:23:34.341825
#5 transferring context: 46.14MB 0.8s done
2024-Sep-18 15:23:34.522832
#5 DONE 0.8s
2024-Sep-18 15:23:34.522832
2024-Sep-18 15:23:34.522832
#6 [stage-0  2/11] WORKDIR /app/
2024-Sep-18 15:23:34.522832
#6 CACHED
2024-Sep-18 15:23:34.522832
2024-Sep-18 15:23:34.522832
#7 [stage-0  3/11] COPY .nixpacks/nixpkgs-e05605ec414618eab4a7a6aea8b38f6fbbcc8f08.nix .nixpacks/nixpkgs-e05605ec414618eab4a7a6aea8b38f6fbbcc8f08.nix
2024-Sep-18 15:23:34.522832
#7 CACHED
2024-Sep-18 15:23:34.522832
2024-Sep-18 15:23:34.522832
#8 [stage-0  4/11] RUN nix-env -if .nixpacks/nixpkgs-e05605ec414618eab4a7a6aea8b38f6fbbcc8f08.nix && nix-collect-garbage -d
2024-Sep-18 15:23:34.522832
#8 CACHED
2024-Sep-18 15:23:34.522832
2024-Sep-18 15:23:34.522832
#9 [stage-0  5/11] RUN sudo apt-get update && sudo apt-get install -y --no-install-recommends curl wget
2024-Sep-18 15:23:34.522832
#9 CACHED
2024-Sep-18 15:23:34.522832
2024-Sep-18 15:23:34.522832
#10 [stage-0  6/11] COPY . /app/.
2024-Sep-18 15:23:35.097779
#10 DONE 0.7s
2024-Sep-18 15:23:35.261342
#11 [stage-0  7/11] RUN --mount=type=cache,id=d0ccok8kg8404ogw88sskowc-/root/bun,target=/root/.bun npm ci
2024-Sep-18 15:24:44.101078
#11 68.95 
2024-Sep-18 15:24:44.101078
#11 68.95 added 1069 packages, and audited 1070 packages in 1m
2024-Sep-18 15:24:44.101078
#11 68.95 
2024-Sep-18 15:24:44.101078
#11 68.95 293 packages are looking for funding
2024-Sep-18 15:24:44.101078
#11 68.95   run `npm fund` for details
2024-Sep-18 15:24:44.259003
#11 68.99 
2024-Sep-18 15:24:44.259003
#11 68.99 6 vulnerabilities (2 moderate, 4 high)
2024-Sep-18 15:24:44.259003
#11 68.99 
2024-Sep-18 15:24:44.259003
#11 68.99 To address all issues, run:
2024-Sep-18 15:24:44.259003
#11 68.99   npm audit fix
2024-Sep-18 15:24:44.259003
#11 68.99 
2024-Sep-18 15:24:44.259003
#11 68.99 Run `npm audit` for details.
2024-Sep-18 15:24:44.259003
#11 68.99 npm notice 
2024-Sep-18 15:24:44.259003
#11 69.00 npm notice New minor version of npm available! 10.5.0 -> 10.8.3
2024-Sep-18 15:24:44.259003
#11 69.00 npm notice Changelog: <[https://github.com/npm/cli/releases/tag/v10.8.3>](https://github.com/npm/cli/releases/tag/v10.8.3%3E)
2024-Sep-18 15:24:44.259003
#11 69.00 npm notice Run `npm install -g npm@10.8.3` to update!
2024-Sep-18 15:24:44.259003
#11 69.00 npm notice
2024-Sep-18 15:24:44.336534
#11 DONE 69.2s
2024-Sep-18 15:24:44.503719
2024-Sep-18 15:24:44.510776
#12 [stage-0  8/11] COPY . /app/.
2024-Sep-18 15:24:45.763711
#12 DONE 1.4s
2024-Sep-18 15:24:45.918543
#13 [stage-0  9/11] RUN --mount=type=cache,id=d0ccok8kg8404ogw88sskowc-next/cache,target=/app/.next/cache --mount=type=cache,id=d0ccok8kg8404ogw88sskowc-node_modules/cache,target=/app/node_modules/.cache bun run build
2024-Sep-18 15:24:46.568295
#13 ERROR: process "/bin/bash -ol pipefail -c bun run build" did not complete successfully: exit code: 132
2024-Sep-18 15:24:46.725267
------
2024-Sep-18 15:24:46.725267
 > [stage-0  9/11] RUN --mount=type=cache,id=d0ccok8kg8404ogw88sskowc-next/cache,target=/app/.next/cache --mount=type=cache,id=d0ccok8kg8404ogw88sskowc-node_modules/cache,target=/app/node_modules/.cache bun run build:
2024-Sep-18 15:24:46.725267
------
2024-Sep-18 15:24:46.745482
Dockerfile:24
2024-Sep-18 15:24:46.745482
--------------------
2024-Sep-18 15:24:46.745482
  22 |     # build phase
2024-Sep-18 15:24:46.745482
  23 |     COPY . /app/.
2024-Sep-18 15:24:46.745482
  24 | >>> RUN --mount=type=cache,id=d0ccok8kg8404ogw88sskowc-next/cache,target=/app/.next/cache --mount=type=cache,id=d0ccok8kg8404ogw88sskowc-node_modules/cache,target=/app/node_modules/.cache bun run build
2024-Sep-18 15:24:46.745482
  25 |     
2024-Sep-18 15:24:46.745482
  26 |     
2024-Sep-18 15:24:46.745482
--------------------
2024-Sep-18 15:24:46.745482
ERROR: failed to solve: process "/bin/bash -ol pipefail -c bun run build" did not complete successfully: exit code: 132
2024-Sep-18 15:24:46.922011
Oops something is not okay, are you okay? 😢
2024-Sep-18 15:24:46.927083
#0 building with "default" instance using docker driver
2024-Sep-18 15:24:46.927083
2024-Sep-18 15:24:46.927083
#1 [internal] load build definition from Dockerfile
2024-Sep-18 15:24:46.927083
#1 transferring dockerfile: 1.21kB done
2024-Sep-18 15:24:46.927083
#1 DONE 0.0s
2024-Sep-18 15:24:46.927083
2024-Sep-18 15:24:46.927083
#2 [internal] load metadata for ghcr.io/railwayapp/nixpacks:ubuntu-1725321821
2024-Sep-18 15:24:46.927083
#2 DONE 0.7s
2024-Sep-18 15:24:46.927083
2024-Sep-18 15:24:46.927083
#3 [internal] load .dockerignore
2024-Sep-18 15:24:46.927083
#3 transferring context: 2B done
2024-Sep-18 15:24:46.927083
#3 DONE 0.0s
2024-Sep-18 15:24:46.927083
2024-Sep-18 15:24:46.927083
#4 [stage-0  1/11] FROM ghcr.io/railwayapp/nixpacks:ubuntu-1725321821@sha256:0cec4cb236c32e6bc58b896fff852f629a7abad4e4f059840d96f0869b4be2fd
2024-Sep-18 15:24:46.927083
#4 DONE 0.0s
2024-Sep-18 15:24:46.927083
2024-Sep-18 15:24:46.927083
#5 [internal] load build context
2024-Sep-18 15:24:46.927083
#5 transferring context: 46.14MB 0.8s done
2024-Sep-18 15:24:46.927083
#5 DONE 0.8s
2024-Sep-18 15:24:46.927083
2024-Sep-18 15:24:46.927083
#6 [stage-0  2/11] WORKDIR /app/
2024-Sep-18 15:24:46.927083
#6 CACHED
2024-Sep-18 15:24:46.927083
2024-Sep-18 15:24:46.927083
#7 [stage-0  3/11] COPY .nixpacks/nixpkgs-e05605ec414618eab4a7a6aea8b38f6fbbcc8f08.nix .nixpacks/nixpkgs-e05605ec414618eab4a7a6aea8b38f6fbbcc8f08.nix
2024-Sep-18 15:24:46.927083
#7 CACHED
2024-Sep-18 15:24:46.927083
2024-Sep-18 15:24:46.927083
#8 [stage-0  4/11] RUN nix-env -if .nixpacks/nixpkgs-e05605ec414618eab4a7a6aea8b38f6fbbcc8f08.nix && nix-collect-garbage -d
2024-Sep-18 15:24:46.927083
#8 CACHED
2024-Sep-18 15:24:46.927083
2024-Sep-18 15:24:46.927083
#9 [stage-0  5/11] RUN sudo apt-get update && sudo apt-get install -y --no-install-recommends curl wget
2024-Sep-18 15:24:46.927083
#9 CACHED
2024-Sep-18 15:24:46.927083
2024-Sep-18 15:24:46.927083
#10 [stage-0  6/11] COPY . /app/.
2024-Sep-18 15:24:46.927083
#10 DONE 0.7s
2024-Sep-18 15:24:46.927083
2024-Sep-18 15:24:46.927083
#11 [stage-0  7/11] RUN --mount=type=cache,id=d0ccok8kg8404ogw88sskowc-/root/bun,target=/root/.bun npm ci
2024-Sep-18 15:24:46.927083
#11 68.95 
2024-Sep-18 15:24:46.927083
#11 68.95 added 1069 packages, and audited 1070 packages in 1m
2024-Sep-18 15:24:46.927083
#11 68.95 
2024-Sep-18 15:24:46.927083
#11 68.95 293 packages are looking for funding
2024-Sep-18 15:24:46.927083
#11 68.95   run `npm fund` for details
2024-Sep-18 15:24:46.927083
#11 68.99 
2024-Sep-18 15:24:46.927083
#11 68.99 6 vulnerabilities (2 moderate, 4 high)
2024-Sep-18 15:24:46.927083
#11 68.99 
2024-Sep-18 15:24:46.927083
#11 68.99 To address all issues, run:
2024-Sep-18 15:24:46.927083
#11 68.99   npm audit fix
2024-Sep-18 15:24:46.927083
#11 68.99 
2024-Sep-18 15:24:46.927083
#11 68.99 Run `npm audit` for details.
2024-Sep-18 15:24:46.927083
#11 68.99 npm notice 
2024-Sep-18 15:24:46.927083
#11 69.00 npm notice New minor version of npm available! 10.5.0 -> 10.8.3
2024-Sep-18 15:24:46.927083
#11 69.00 npm notice Changelog: <[https://github.com/npm/cli/releases/tag/v10.8.3>](https://github.com/npm/cli/releases/tag/v10.8.3%3E)
2024-Sep-18 15:24:46.927083
#11 69.00 npm notice Run `npm install -g npm@10.8.3` to update!
2024-Sep-18 15:24:46.927083
#11 69.00 npm notice 
2024-Sep-18 15:24:46.927083
#11 DONE 69.2s
2024-Sep-18 15:24:46.927083
2024-Sep-18 15:24:46.927083
#12 [stage-0  8/11] COPY . /app/.
2024-Sep-18 15:24:46.927083
#12 DONE 1.4s
2024-Sep-18 15:24:46.927083
2024-Sep-18 15:24:46.927083
#13 [stage-0  9/11] RUN --mount=type=cache,id=d0ccok8kg8404ogw88sskowc-next/cache,target=/app/.next/cache --mount=type=cache,id=d0ccok8kg8404ogw88sskowc-node_modules/cache,target=/app/node_modules/.cache bun run build
2024-Sep-18 15:24:46.927083
#13 ERROR: process "/bin/bash -ol pipefail -c bun run build" did not complete successfully: exit code: 132
2024-Sep-18 15:24:46.927083
------
2024-Sep-18 15:24:46.927083
 > [stage-0  9/11] RUN --mount=type=cache,id=d0ccok8kg8404ogw88sskowc-next/cache,target=/app/.next/cache --mount=type=cache,id=d0ccok8kg8404ogw88sskowc-node_modules/cache,target=/app/node_modules/.cache bun run build:
2024-Sep-18 15:24:46.927083
------
2024-Sep-18 15:24:46.927083
Dockerfile:24
2024-Sep-18 15:24:46.927083
--------------------
2024-Sep-18 15:24:46.927083
  22 |     # build phase
2024-Sep-18 15:24:46.927083
  23 |     COPY . /app/.
2024-Sep-18 15:24:46.927083
  24 | >>> RUN --mount=type=cache,id=d0ccok8kg8404ogw88sskowc-next/cache,target=/app/.next/cache --mount=type=cache,id=d0ccok8kg8404ogw88sskowc-node_modules/cache,target=/app/node_modules/.cache bun run build
2024-Sep-18 15:24:46.927083
  25 |     
2024-Sep-18 15:24:46.927083
  26 |     
2024-Sep-18 15:24:46.927083
--------------------
2024-Sep-18 15:24:46.927083
ERROR: failed to solve: process "/bin/bash -ol pipefail -c bun run build" did not complete successfully: exit code: 132
2024-Sep-18 15:24:46.932590
Deployment failed. Removing the new version of your application.

### Steps to Reproduce

1. Create new project
2. Use Github apps
3. Use NextJS14 with app router
4.

### Coolify Version

v4.0.0-beta.341

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04

**Comment by djsisson** [comment]
try using a dockerfile for bun

the issue is probably with nixpacks + bun

**Comment by lolopook** [comment]
I have the same error how do we try bun with a Dockerfile?

**Comment by alexvdvalk** [comment]
Try adding:
`"module": "src/index.ts",`

into your package.json.
