### ISSUE TITLE
[Bug]: Validate Server & Install Docker Engine - ERROR: Unsupported distribution 'almalinux'

### ISSUE THREAD

**Issue by codelabyz** [coollabsio/coolify#3486]
### Error Message and Logs

Installing Prerequisites...
Installing Docker Engine...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 24599    0 24599    0     0   147k      0 --:--:-- --:--:-- --:--:--  147k
# Executing docker install script, commit: e5543d473431b782227f8908005543bb4389b8de

ERROR: Unsupported distribution 'almalinux'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 21596  100 21596    0     0   245k      0 --:--:-- --:--:-- --:--:--  245k
# Executing docker install script, commit: 0d6f72e671ba87f7aa4c6991646a1a5b9f9dae84

ERROR: Unsupported distribution 'almalinux'

Docker Engine could not be installed. Please install Docker manually before continuing: [documentation](https://docs.docker.com/engine/install/#server).

After installing Docker manually on the target system, we get this instead:

Installing Prerequisites...
Installing Docker Engine...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 24599    0 24599    0     0   103k      0 --:--:-- --:--:-- --:--:--  103k
# Executing docker install script, commit: e5543d473431b782227f8908005543bb4389b8de
Warning: the "docker" command appears to already exist on this system.

If you already have Docker installed, this script can cause trouble, which is
why we're displaying this warning and provide the opportunity to cancel the
installation.

If you installed the current Docker package using this script and are using it
again to update Docker, you can safely ignore this message.

You may press Ctrl+C now to abort this script.
+ sleep 20

ERROR: Unsupported distribution 'almalinux'

It loops then fails to complete. 

The solution is to have Docker already installed and the docker systemd service started on the target server. 

AlmaLinux is noted as supported here: https://coolify.io/docs/installation

### Steps to Reproduce

1. Load a new installation on AlmaLinux9. This is successful
2. On a second VM, attempt to Validate Server & Install Docker Engine on a supported (according to https://coolify.io/docs/installation) AlmaLinux9 VM 
3. The process fails with logs above.
4. Solve by having the Docker engine installed and started on the target VM

### Coolify Version

Latest

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

AlmaLinux9 

### Additional Information

Fixed by having Docker already running on the target supported system

**Comment by peaklabs-dev** [comment]
Please upgrade to the latest version of v4 and retest if this issue persists as we made a lot of chagnes. If it does, kindly reopen this issue or create a new updated issue.
