### ISSUE TITLE
[Bug]: Scheduled Backups Settings are not saved (setup missing after refresh)

### ISSUE THREAD

**Issue by carlonoelle** [coollabsio/coolify#3493]
### Error Message and Logs

My scheduled backups settings are not persisting. I set them up, daily schedule and upload to s3 storage, save and start an instant backup which works.
Now if i refresh, or update coolify the scheduled backup settings are missing, like they werent saved correctly, and thus my backups are not getting created.
I don't know exactly when they went missing, but it happend multiple times now, so i think its not only while updating coolify, but also either when refreshing the browser/cache, or maybe when coolify restarts?

### Steps to Reproduce

1. Create a Service with a postgres database
2. Setup a scheduled backup (i used 0 0 * * * as schedule)
4. i used upload to s3, but without it didnt work too
5. Save and refresh, sometimes it persisted, other times not

### Coolify Version

v4.0.0-beta.341

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04.1 LTS

**Comment by JeanWLC** [comment]
@carlonoelle I'm having a similar issue. It seems the save button on the backup page doesn't work properly. 
Workaround: set all other backup options and then check or uncheck the "Backup Enabled" checkbox. This saves the page for me. Then enable again if you unchecked.

**Comment by carlonoelle** [comment]
Hey @JeanWLC, tried that, looked back into it after half an hour and the backup settings are gone again...

**Comment by carlonoelle** [comment]
Updated to newest beta 364 and trying again now

**Comment by Cristy94** [comment]
I just updated to the latest version (360) and I now noticed all my scheduled backup settings were deleted. I had to re-create all my backups.

**Comment by peaklabs-dev** [comment]
I am unable to reproduce this issue, please upgrade to the latest version of Coolify v4 and try again, and if this is still an issue, feel free to reopen this issue or create a new one.
