### ISSUE TITLE
GitHub's authorization doesn't work on mobile

### ISSUE THREAD

**Issue by mrqiz** [coollabsio/coolify#35]
So, I'm trying to authorize in Coolify with my GitHub account in Chrome, but GitHub just redirects to sign in page, and it doesn't work.

https://user-images.githubusercontent.com/49580687/115279176-09924000-a14f-11eb-9149-b22e49e538f1.mp4

**Comment by andrasbacsai** [comment]
Hey,

Are you trying to log in for the first time? If not, are you trying with the same GitHub user you are registered? 

After the first successful login, Coolify restricts the registration, so others cannot register, just if you allow it in the `Settings` menu.

**Comment by mrqiz** [comment]
> Hey,
> 
> Are you trying to log in for the first time? If not, are you trying with the same GitHub user you are registered?
> 
> After the first successful login, Coolify restricts the registration, so others cannot register, just if you allow it in the `Settings` menu.

Yes, I'm trying to login for the first time.

**Comment by andrasbacsai** [comment]
I'm modified things regarding Github Auth, could you please update/reinstall Coolify and try again?

**Comment by andrasbacsai** [comment]
Due to inactivity, I'm closing this issue. However, if the problem persists, please reopen the issue. Thanks!
