### ISSUE TITLE
Docker installed with snap

### ISSUE THREAD

**Issue by Gakamine** [coollabsio/coolify#350]
Hello!

I ran into an issues where the install script was not working because I had no "/etc/docker/daemon.json" file.
I was able to solve it by changing the lines mentioning this file by replacing it with "/var/snap/docker/current/config/daemon.json" since my Docker package was installed using snap.

Would be cool to make the script detect if Docker was installed with APT or Snap.
Thanks!
(I might work on this if I have the time tho)

**Comment by andrasbacsai** [comment]
The latest installation script handles Snap installations as well.
