### ISSUE TITLE
[Bug]: Installation failed

### ISSUE THREAD

**Issue by nhCoder** [coollabsio/coolify#3510]
### Error Message and Logs

E: Failed to fetch https://mirror.hetzner.com/ubuntu-ports/packages/dists/focal-updates/universe/i18n/Translation-en.xz  File has unexpected size (294888 != 295192). Mirror sync in progress? [IP: 2a01:4ff:ff00::3:3 443]
   Hashes of expected file:
    - Filesize:295192 [weak]
    - SHA256:e7f5b83c2f39962fad6b597021e84c1512f2381354a9b64273179e8072515402
    - SHA1:7184a97a3ed7ef3b7cad1cf86ca71fc5887fc240 [weak]
    - MD5Sum:f7b1b16c5ea6eb6305cf59b921c29c9d [weak]
   Release file created at: Thu, 19 Sep 2024 15:13:31 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.

### Steps to Reproduce

On Executing installation script `curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash`

### Coolify Version

4.0.0-beta.341

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 20.04.6 LTS

**Comment by andrasbacsai** [comment]
It looks like a Hetzner repository error, not related to Coolify. Please try again a bit later.

**Comment by nhCoder** [comment]
True, the error was from Hetzener repository. Its working now.
