### ISSUE TITLE
[Bug]: Docker Compose deploy from Private Repo throws Permission denied error

### ISSUE THREAD

**Issue by JensUweB** [coollabsio/coolify#3517]
### Error Message and Logs

We're trying to deploy one of our private repositories (gitlab.com team) via a self-hosted Coolify instance (running in the Hetzner Cloud). Most of our applications require a custom Dockerfile or docker-compose file to run optimally. Our websites & web apps are mostly build based on node.js (like in this case), therefore we want to use an Nginx container to improve static file handling.

Connecting the private repo with Coolify is in general no problem. Deploying with the "Dockerfile" Build Pack and setting the Dockerfile path to `/docker/Dockerfile` works as expected. The Container gets build and is up & running.

But when I switch the Build Pack to "Docker Compose", enter the compose file path `/docker/docker-compose.yml` and hit "Save" I get the following error message:

> Cloning into '.'...
> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

Switching back to "Dockerfile" Build Pack and hitting save & deploy and it works again. Same branch in both cases.

This error is very frustrating and I hope someone can help us to solve this. Thanks a lot, loving your work so far!

### Steps to Reproduce

1. Fork my [example repository](https://github.com/JensUweB/coolify-docker-compose-bug)
2. Make your forked repo private
3. Add new Application to Coolify with "Private Repository (with deploy key)" option
4. Set Build Pack to "Docker Compose", set Docker Compose Location to `/docker/docker-compose.yaml` & hit save.
5. Success (or rather error 😄 )!

### Example Repository URL

https://github.com/JensUweB/coolify-docker-compose-bug

### Coolify Version

v4.0.0-beta.341

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04

### Additional Information

Please keep in mind that we normally use GitLab for all our repositories, therefore the "Private Repository (with deploy key)" option.

**Comment by jomoflash** [comment]
Similar issue I am experiencing here, I later discovered that an identity option is missing in the `git ls-remote <repo> main` command as compared against others that were successful. The version I'm running is `v4.0.0-beta.345`

![image](https://github.com/user-attachments/assets/1b5a17d9-43d9-4a6c-96fb-7ff46fdd6ebc)

**Comment by jomoflash** [comment]
@JensUweB I Don't know if you later found a workaround, I was able get successful deploy with deploy keys directly added on projects or repositories. Discovered any key added directly to user account doesn't work or fails deploy... Can't tell if this is deliberate by design. ✅

**Comment by JensUweB** [comment]
> @JensUweB I Don't know if you later found a workaround, I was able get successful deploy with deploy keys directly added on projects or repositories. Discovered any key added directly to user account doesn't work or fails deploy... Can't tell if this is deliberate by design. ✅

I will test this later & post an update here. Thanks for your reply.

**Comment by peaklabs-dev** [comment]
We added a fix for this in one of the last updates, so please upgrade to the latest version and then deploy key should work again.

**Comment by mrcloudbook** [comment]
We are facing same issue using latest version
<img width="372" alt="Screenshot 2024-09-29 at 6 00 03 PM" src="https://github.com/user-attachments/assets/5eb2ddd9-55f3-414d-a485-2c2475eeaa33">

**Comment by JensUweB** [comment]
@peaklabs-dev I just tested it with Version `v4.0.0-beta.347` and it works now. Thanks for the fix!

**Comment by mrcloudbook** [comment]
```
Cloning into '.'...
Permission denied, please try again.
Permission denied, please try again.
git@git.cloud.com: Permission denied (publickey,password).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

worked yesterday and facing same issue today
