### ISSUE TITLE
[Bug]: Error response from daemon: all predefined address pools have been fully subnetted

### ISSUE THREAD

**Issue by candlep** [coollabsio/coolify#3529]
### Error Message and Logs

I am trying to deploy a PocketBase service but keep getting the error shown below.
```
Creating Docker network.
Error response from daemon: all predefined address pools have been fully subnetted
```

### Steps to Reproduce

Try deploying the one-click PocketBase service

### Coolify Version

v4.0.0-beta.341

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04

**Comment by candlep** [comment]
FIX: Edit your `etc/docker/daemon.json` to

```
 {
  "log-level": "warn",
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "10m",
    "max-file": "5"
  },
  "default-address-pools": [
    {
      "base" : "172.16.0.0/12",
      "size" : 24
    }
  ]
}
```

**Comment by peaklabs-dev** [comment]
Just got this too when deploying a ton of stuff in dev. We need a fix or a way for the user to add more predefined addresses.
