### ISSUE TITLE
[Bug]:v4.0.0-beta.341 won't take environment variable in consideration when (re)deploying

### ISSUE THREAD

**Issue by Drillan767** [coollabsio/coolify#3532]
### Error Message and Logs

N/A

### Steps to Reproduce

A bit of context, I already had Coolify version v4.0.0-beta.329. I had a mariadb server up, some environment variable, and a Directus project setup with a docker-compose configuration.

1. Update Coolify to v4.0.0-beta.341
2. Setup a project with environment variable
3. (Re)deploy the project
4. Run `printenv `in the docker container
5. Notice how the custom environment variable aren't listed

I downgraded back to v4.0.0-beta.331 and it works again. I can't tell if this problem exists only in 341 but I lack time to test them all.

### Coolify Version

4.0.0-beta.341

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Debian 12

**Comment by nuxwin** [comment]
@andrasbacsai See also https://github.com/coollabsio/coolify/issues/3534

I do think it is the same problem... This bug look important to me. No reaction on your side yet.

**Comment by andrasbacsai** [comment]
I tried to reproduce it like:
- On v331, created a mariadb with a `test=test` env variable.
- Migrated to v341, redeployed mariadb.
- `test=test` still available on the redeployed mariadb.

What am I doing wrong?

Can you please show me screenshots of the Coolify's UI (Environment variable) and the `printenv` output?
