### ISSUE TITLE
[Bug]: Bad Gateway when add new resource

### ISSUE THREAD

**Issue by mohammedmoulla** [coollabsio/coolify#3533]
### Error Message and Logs

I was able to add multiple resources (using private Repository and Dockerfile) 
but suddenly I can't do that again 

a black screen shows with an error message in browser console : 
"Failed to load resource: the server responded with a status of 502 ()"

also I upgraded to latest version and the same problem 

![image](https://github.com/user-attachments/assets/4c858692-d95c-468e-b020-86d7ef2b7762)

![image](https://github.com/user-attachments/assets/31564693-4a39-421b-b035-cc14aafbe1a9)

![image](https://github.com/user-attachments/assets/74f8e505-b32b-4365-9526-2709cb4cbca0)

### Steps to Reproduce

1. open Projects in menu
2. select any project
3. press +New to add new Resource
4. select Private Repository (with deploy key) or any other resource

### Coolify Version

v4.0.0-beta.341

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04

### Additional Information

there is enough RAM and disk space and docker is working 
all existing resources are working fine but I can't add new ones

**Comment by LoidAir** [comment]
same issue

version: v4.0.0-beta.360

**Comment by mohammedmoulla** [comment]
after a while the problem solved by itself (without any modifications)
maybe there is some process working in background
it's strange
