### ISSUE TITLE
[Bug]: dragonfly terminal return (error) NOAUTH Authentication required.

### ISSUE THREAD

**Issue by user03497803549** [coollabsio/coolify#3541]
### Error Message and Logs

in dragonfly terminal using redis-cli i got error "(error) NOAUTH Authentication required."

### Steps to Reproduce

1. Open dragonfly instance
2. Open terminal
3. Type redis-cli
4. Type in cli anything, for example 'keys *'
5. Got error "(error) NOAUTH Authentication required."

### Coolify Version

v4.0.0-beta.341

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04

**Comment by LEstradioto** [comment]
This is a redis authentication problem. Dragonfly depends on it, you should add the redis password to authenticate. run this redis-cli command on the container

`redis-cli -a $(echo $REDIS_PASSWORD)`

or look for the password in here:
![image](https://github.com/user-attachments/assets/7179d52d-d3fc-4e50-a9b1-6bed77e428b9)
