### ISSUE TITLE
[Bug]: no configuration file provided: not found

### ISSUE THREAD

**Issue by a0m0rajab** [coollabsio/coolify#3549]
### Error Message and Logs

I am getting the next message "Help! "no configuration file provided: not found" when I am trying to set a proxy on a remote server.

### Steps to Reproduce

1. connect a remote server with non-root-user
2. validate the server

### Coolify Version

v4.0.0-beta.341

### Are you using Coolify Cloud?

No (self-hosted)

**Comment by YoussefZayed** [comment]
Same issue for me

**Comment by a0m0rajab** [comment]
I solved this issue by reinstalling Docker, the previous version were installed by snap and had a different configuration and permissions. When I used the installation guide from docker it worked as expected.

**Comment by YoussefZayed** [comment]
@a0m0rajab It worked, I reinstalled docker using the docker site (not snap) and it worked. Much appreciated.

**Comment by a0m0rajab** [comment]
For future reference here is the related links that helped me: 
- https://github.com/danny-avila/LibreChat/discussions/2754
- https://stackoverflow.com/questions/53304396/docker-compose-cant-find-suitable-file-even-though-it-exists/69684470#69684470
- https://www.reddit.com/r/docker/comments/1asybp9/help_no_configuration_file_provided_not_found/

**Comment by peaklabs-dev** [comment]
Docker installed via snap is not supported by Coolify and to make it clearer I have added a warning to the install docs which will be available soon.
