### ISSUE TITLE
[Bug]: ERR_SSL_UNRECOGNIZED_NAME_ALERT

### ISSUE THREAD

**Issue by henriqueArrazao** [coollabsio/coolify#3552]
### Error Message and Logs

I had a project, created around 2 months ago, the ERR_SSL_UNRECOGNIZED_NAME_ALERT was happening for the projects I had, even for the Coolify UI, I could only access directly through the IP address. So I reset everything, installed the Coolify and etc, but the same problem persists...

### Steps to Reproduce

Create a normal project following this tutorial video:
https://www.youtube.com/watch?v=ZZ1lnw8D3Qo&ab_channel=developedbyed

### Coolify Version

v4.0.0-beta.341

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04.1 LTS

**Comment by peaklabs-dev** [comment]
Could you please provide me with the proxy logs so I can better debug this issue?
