### ISSUE TITLE
Create pagination : Large "Application Logs" 

### ISSUE THREAD

**Issue by andrasbacsai** [coollabsio/coolify#356]
### Discussed in https://github.com/coollabsio/coolify/discussions/332

<div type='discussions-op-text'>

<sup>Originally posted by **andreas-arkulpa** April 11, 2022</sup>
Hi @andrasbacsai,

first of all thanks for the amazing tool! I really like coolify.

We have an application which produces a large amount of application logs.
When we want to take a look at the application logs in the coolify dashboard the application crashes. If there is no parameter "since" added to the query it will load all logs sine timestamp 0.

You can see the params here: https://docs.docker.com/engine/api/v1.37/#operation/ContainerLogs

https://github.com/coollabsio/coolify/blob/2971e142698b6f871065ca7ccd02be032adc0bde/src/routes/applications/%5Bid%5D/logs/index.json.ts#L25

Can you think about adding pagination for loading the logs? Maybe it is also an idea to add the "tail" parameter to only load the last x log entries?

You can also tell me where to add the pagination so I can help you with that.</div>

**Comment by andreas-arkulpa** [comment]
Thank you very much for your help!
