### ISSUE TITLE
[Bug]: Redeploy with key not working after update to 343

### ISSUE THREAD

**Issue by diogo24m** [coollabsio/coolify#3580]
### Error Message and Logs

2024-Sep-26 10:41:40.493622 Starting deployment of git@bitbucket.org:xxxx/api.git:master to Localhost.
2024-Sep-26 10:41:40.677772 Preparing container with helper image: ghcr.io/coollabsio/coolify-helper:1.0.1.
2024-Sep-26 10:41:40.771385 docker rm -f k0g04w8kgsocww888wkskw4g
2024-Sep-26 10:41:40.771385 Error response from daemon: No such container: k0g04w8kgsocww888wkskw4g
2024-Sep-26 10:41:40.878593 docker run -d --network coolify --name k0g04w8kgsocww888wkskw4g --rm -v /var/run/docker.sock:/var/run/docker.sock ghcr.io/coollabsio/coolify-helper:1.0.1
2024-Sep-26 10:41:40.878593 79f815f588a682046f41d139c57617a1a398cda5342db5db3a72fa9653da5734
2024-Sep-26 10:41:41.945198 docker exec k0g04w8kgsocww888wkskw4g bash -c 'GIT_SSH_COMMAND="ssh -o ConnectTimeout=30 -p 22 -o Port=22 -o LogLevel=ERROR -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" git ls-remote git@bitbucket.org:xxxx/api.git master'
2024-Sep-26 10:41:41.945198 git@bitbucket.org: Permission denied (publickey).
2024-Sep-26 10:41:41.948479 fatal: Could not read from remote repository.
2024-Sep-26 10:41:41.948479
2024-Sep-26 10:41:41.948479 Please make sure you have the correct access rights
2024-Sep-26 10:41:41.948479 and the repository exists.
2024-Sep-26 10:41:42.003446 Oops something is not okay, are you okay? 😢
2024-Sep-26 10:41:42.005791 git@bitbucket.org: Permission denied (publickey).
2024-Sep-26 10:41:42.005791 fatal: Could not read from remote repository.
2024-Sep-26 10:41:42.005791
2024-Sep-26 10:41:42.005791 Please make sure you have the correct access rights
2024-Sep-26 10:41:42.005791 and the repository exists.
2024-Sep-26 10:41:42.007829 Deployment failed. Removing the new version of your application.

### Steps to Reproduce

1. Updated from coolify v4.0.0 341 to 343
2. Tried to redeploy App with key (worked before update)
3. Also tried generating another key

### Coolify Version

v4.0.0 343

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Debian 12

**Comment by andrasbacsai** [comment]
Please update your instance, it has been already fixed in the latest version (sorry about it).
