### ISSUE TITLE
Coolify on AWS (community example)

### ISSUE THREAD

**Issue by youfoundron** [coollabsio/coolify#359]
I've built an example repo for how to deploy your own Coolify instance on AWS using Terraform.

Feel free to link it in docs if you see fit!

My repo: https://github.com/youfoundron/coolify-aws

**Comment by andrasbacsai** [comment]
Wow, thank you! I will add it to the docs!

**Comment by shash7** [comment]
Hey @youfoundron have you got a guide for a pure ec2 implementation?
