### ISSUE TITLE
[Bug]: Trying to load a docker compose git resource that has no main branch (but master) fails

### ISSUE THREAD

**Issue by CryptoVaraan** [coollabsio/coolify#3592]
### Error Message and Logs

Pop up message appears:
Cloning into '.'...
fatal: Remote branch main not found in upstream origin

### Steps to Reproduce

1. Add resource using public repository
2. Click check repository
3. Click continue
4.

### Example Repository URL

https://github.com/mailcow/mailcow-dockerized

### Coolify Version

v4.0.0-beta.345

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04.1 LTS

**Comment by peaklabs-dev** [comment]
This is not a Coolify issue, the Mailcow remote branch is called `master`, not main, so the error message is correct: it cannot find `main` because you need to change the branch name to `master`.

**Comment by CryptoVaraan** [comment]
The default branch can be called main OR master. My point is that the import function ASSUMES the existence of a branch called main. The text also says that you can change the branch AFTER the import, but you don't get that far when it works like this. Maybe there is a way to find out what the default branch is called?

**Comment by djsisson** [comment]
add /tree/master onto the end of the url
