### ISSUE TITLE
[Bug]: PHP error when tried to download the dump file at Scheduled Backups

### ISSUE THREAD

**Issue by atistrcsn** [coollabsio/coolify#3595]
### Error Message and Logs

```
{
  "message": "League\\Flysystem\\PhpseclibV3\\SftpConnectionProvider::__construct(): Argument #6 ($port) must be of type int, string given, called in /var/www/html/vendor/league/flysystem-sftp-v3/SftpConnectionProvider.php on line 158"
}
```

### Steps to Reproduce

1. setup a scheduled backup 
2. create a backup from pg database
3. click Download button to download dump file
4. above PHP error in new browser window

### Coolify Version

v4.0.0-beta.345

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22

**Comment by peaklabs-dev** [comment]
I am unable to reproduce this issue, please upgrade to the latest version of Coolify v4 and try again, and if this is still an issue, feel free to reopen this issue or create a new one.
