### ISSUE TITLE
[Bug]: version `GLIBC_2.38' not found (required by /nix/store/...)

### ISSUE THREAD

**Issue by a0m0rajab** [coollabsio/coolify#3601]
I am getting this error message whenever I try ot run next project on turborepo
### Error Message and Logs

 packages/ayasofyazilim-ui prepare: /app/packages/ayasofyazilim-ui/node_modules/.bin/../node/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /nix/store/c6r62m84hywf4i6qq1h28f13zv38yqyp-gcc-13.3.0-lib/lib/libstdc++.so.6)

### Steps to Reproduce

1. use turbo repo with next

related: https://github.com/coollabsio/coolify/issues/2550

### Coolify Version

v4.0.0-beta.341

### Are you using Coolify Cloud?

No (self-hosted)

**Comment by djsisson** [comment]
you will need to add packages to your nixpacks.toml if the default ones do not work

or switch to using a dockerfile

**Comment by a0m0rajab** [comment]
I switched to using dockerfile but did not have luck with that, I got another issue with this error: 

https://github.com/coollabsio/coolify/issues/3605 

As for the `nixpacks.toml`, I just realised that I can change that now; I think I might explore this as well. 

To add more context to this issue, I used this with a Monorepo using Turborepo. Looking at this example: 

https://github.com/coollabsio/coolify-examples/tree/33a1f0e30758e5764ca012baefee7754e7f1843b/turbo-nextjs

it says it's enough to just set the pack as nixpacks, yet after further exploring and @djsisson suggestion, I think there is a need to add extra nixpacks.toml file here like the laravel example. 

https://github.com/coollabsio/coolify-examples/tree/33a1f0e30758e5764ca012baefee7754e7f1843b/laravel

**Comment by zaini** [comment]
Running into similar issues:

I am using `"puppeteer": "^23.6.1"` in my Nextjs project and getting these errors:

```
/root/.cache/puppeteer/chrome/linux-130.0.6723.69/chrome-linux64/chrome: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.36' not found (required by /nix/store/g5dj80arfsy8lvkda22dgkcqmyqa126w-util-linux-minimal-2.39.4-lib/lib/libmount.so.1)
/root/.cache/puppeteer/chrome/linux-130.0.6723.69/chrome-linux64/chrome: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /nix/store/g5dj80arfsy8lvkda22dgkcqmyqa126w-util-linux-minimal-2.39.4-lib/lib/libmount.so.1)
/root/.cache/puppeteer/chrome/linux-130.0.6723.69/chrome-linux64/chrome: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /nix/store/g5dj80arfsy8lvkda22dgkcqmyqa126w-util-linux-minimal-2.39.4-lib/lib/libblkid.so.1)
/root/.cache/puppeteer/chrome/linux-130.0.6723.69/chrome-linux64/chrome: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /nix/store/g5dj80arfsy8lvkda22dgkcqmyqa126w-util-linux-minimal-2.39.4-lib/lib/libuuid.so.1)


TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at Interface.onClose (/app/node_modules/@puppeteer/browsers/lib/cjs/launch.js:312:24)
    at Interface.emit (node:events:529:35)
    at Interface.close (node:internal/readline/interface:534:10)
    at Socket.onend (node:internal/readline/interface:260:10)
    at Socket.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1400:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  digest: '1312161570'
}
```

**Comment by djsisson** [comment]
@zaini the images used by nixpacks are not up to date (not much we can do), if you require a newer version of glibc you have to use a dockerfile

**Comment by peaklabs-dev** [comment]
Since we have no control over the Nixpacks repository, we cannot influence this, so the only option is to use a custom Dockerfile see this issue to track when Nixpacks get updated https://github.com/railwayapp/nixpacks/issues/1205.
