### ISSUE TITLE
[Bug]: Error relocating /app/node_modules/.pnpm/node@20.17.0/node_modules/node/bin/node: fcntl64: symbol not found

### ISSUE THREAD

**Issue by a0m0rajab** [coollabsio/coolify#3605]
### Error Message and Logs

I am trying to run a turborepo project with docker file, the docker file works locally but when I use coolify I got the error in the title.

### Steps to Reproduce

1. try to run a turborepo with docker

### Coolify Version

v4.0.0-beta.341

### Are you using Coolify Cloud?

No (self-hosted)

**Comment by a0m0rajab** [comment]
I got this issue since I was using node:alpine for the docker file, which did not include the full packages: 

Here is more details about it: 

https://stackoverflow.com/questions/52083380/in-docker-image-names-what-is-the-difference-between-alpine-jessie-stretch-an
https://github.com/nodejs/docker-node/tree/58c3b39e5948f82c594395857193cd97d01c690e?tab=readme-ov-file#nodealpine

Switching to node:bullseye fixed the issue (yes, the image size is larger, but it's not an issue for me now)

**Comment by peaklabs-dev** [comment]
As this issue is fix I am closing this.
