### ISSUE TITLE
[Bug]: Page not loading

### ISSUE THREAD

**Issue by SpuriousGer** [coollabsio/coolify#3627]
### Error Message and Logs

![image](https://github.com/user-attachments/assets/f8bae12b-5663-48dd-b559-65d3630469fb)
This is how the screen looks like.

It should be loading the resources.

### Steps to Reproduce

1. Go to projects --> environment
2. The resources should load but they dont

### Coolify Version

v4.0.0-beta.347

### Are you using Coolify Cloud?

No (self-hosted)

### Additional Information

I updated from beta.340 to beta.347

**Comment by TheSuperfluousMan** [comment]
Yes, the same thing is happening to me - the resources load at first but when you try to click on any of them they immediately disappear. It's only started happening since I upgraded yesterday.

**Comment by andrasbacsai** [comment]
The input box is prefilled with some data from your password manager, no? If you delete everything from the input box, it should work.

Am I right?

**Comment by TheSuperfluousMan** [comment]
You are correct - silly me for not noticing (I thought the email listing was a new feature of some sort...)

**Comment by moshetanzer** [comment]
@andrasbacsai and @TheSuperfluousMan this is not a feature - but a bug and should be fixed asap as mentioned also here https://github.com/coollabsio/coolify/issues/3640

**Comment by peaklabs-dev** [comment]
This bug has been fixed so I will close this issue.
