### ISSUE TITLE
coolify server cant access after update

### ISSUE THREAD

**Issue by qhoirulanwar** [coollabsio/coolify#363]
### coolify server cant access after update
how to solve this ?
hos to start coolify server?

thx all, help me

**Comment by qhoirulanwar** [comment]
i solve this with re run coolify command
wget -q https://get.coollabs.io/coolify/install.sh -O install.sh; sudo bash ./install.sh

without replace coolify .env configuration

**Comment by andrasbacsai** [comment]
Hm. It is hard to debug if you have already solved it, so that I will close this issue. If it happens again, let me know!
