### ISSUE TITLE
[Bug]: Manual update fails on Hetzner Arm64

### ISSUE THREAD

**Issue by pjarnfelt** [coollabsio/coolify#3633]
### Error Message and Logs

 Failed to fetch https://mirror.hetzner.com/ubuntu/packages/dists/noble-updates/main/binary-arm64/Packages  404  Not Found [IP: 2a01:4ff:ff00::3:3 443]

### Steps to Reproduce

1. Create a Hetzner ubuntu container
2. install Coolify
3. try to run `curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash` to update

### Coolify Version

v4.0.0-beta.318

### Are you using Coolify Cloud?

No (self-hosted)

### Additional Information
<img width="1302" alt="Screenshot 2024-09-29 at 17 16 02" src="https://github.com/user-attachments/assets/1cf689aa-846e-4c03-893c-c86832b28c89">

I tried both with and without adding a version to the upgrade command:
`curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash`

**Comment by jacorpski** [comment]
Probably not a Coolify issue but rather an issue at Hetzner with their mirrors for packages. If you try again later it probably will work

**Comment by andrasbacsai** [comment]
This is not related to Coolify.
