### ISSUE TITLE
[Bug]: Dashes "-" are not supported in variable names.

### ISSUE THREAD

**Issue by ggpepp41** [coollabsio/coolify#3639]
### Error Message and Logs

Saved configuration files to /data/coolify/services/vc8sc0csk4socccc0o0sgsw4.
Creating Docker network.
Starting service.
Pulling images.
failed to read /data/coolify/services/vc8sc0csk4socccc0o0sgsw4/.env: line 9: unexpected character "-" in variable name "ENTE_INTERNAL_HARDCODED-OTT_LOCAL-DOMAIN-SUFFIX=...."

### Steps to Reproduce

1. Create a variable with a dash "-" in it through the UI. 
2. Deploy the stack.

### Coolify Version

v4.0.0-beta.347

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04

### Additional Information

Environment Variables that are static in the docker compose do not cause the error.

**Comment by andrasbacsai** [comment]
As I know dashes not allowed in env variables: https://stackoverflow.com/a/36992531

**Comment by peaklabs-dev** [comment]
Dashes are generally not recommended/ not supported in environment variables, so we will not allow dashes. Please stick to underscores and all caps (and numbers) to avoid problems.

**Comment by nank1ro** [comment]
@peaklabs-dev this is a blocker for the Ente.io service, which uses the `ENTE_INTERNAL_HARDCODED-OTT_LOCAL-DOMAIN-SUFFIX` environment variable. Should we fork it to change the environment variable names?
