### ISSUE TITLE
[Bug]: When autocomplete wtih a password manager the password while deleteting a resource it close the modal

### ISSUE THREAD

**Issue by Nuxnuxx** [coollabsio/coolify#3641]
### Error Message and Logs

No error log

### Steps to Reproduce

1. Use a password manager (for my personal usage it is bitwarden)
2. create a resource
3. try to delete it and the moment you need to fill the password use your password manager to autocomplete

### Coolify Version

v4.0.0-beta.347

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04

### Additional Information

It is a minor issue but would enjoy to try to fix it

**Comment by andrasbacsai** [comment]
Added `autocomplet='off'` to all inputs where it does not makes sense. Releasing the fix in the next version.

**Comment by fmendez** [comment]
This issue remains in version v4.0.0-beta.349:

### Demo:


https://github.com/user-attachments/assets/0b087f4b-e38e-423e-af44-9723c0b95537


The moment you select the correct credentials to be filled, the modal window gets dismissed and the action you were trying to do (in this case deleting a resource) cancelled.

### Steps to Reproduce

1- Use a password manager
2- create a resource
3- try to delete it and the moment you need to fill the password use your password manager to autocomplete

### Example Repository URL
No response

### Coolify Version
v4.0.0-beta.349

### Are you using Coolify Cloud?
Yes
