### ISSUE TITLE
[Bug]: DOCKER COMPOSE STACK   CONTAINERS CANNOT  BE ACCESSED USING THE COOLIFY TERMINAL IN THE RESOURCE

### ISSUE THREAD

**Issue by lewismunene020** [coollabsio/coolify#3642]
### Error Message and Logs

When you access a docker container deployed   via   docker compose stack you  get this error 

![image](https://github.com/user-attachments/assets/dd0f59cd-dfca-4bcc-bb45-8344973a0376)

Deploying Via Normal DockerFile However Works Effectively 

### Steps to Reproduce

1. Deploy  a docker compose  file  via  github  
2.Try accessing the  docker container via coolify terminal.You  get the  error indicated in the above  image
3.The  error  might   be  something to  do with  the  terminal service
Below is  the  error  indicated

![Screenshot from 2024-09-29 19-42-32](https://github.com/user-attachments/assets/a2dea86e-bf6b-44d4-b037-c6f24bdc53b5)

### Coolify Version

v4.0.0-beta.347

### Are you using Coolify Cloud?

No (self-hosted)

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.
