### ISSUE TITLE
[Bug]: Backup crashing due to an sql error 

### ISSUE THREAD

**Issue by lorenzpfei** [coollabsio/coolify#3652]
### Error Message and Logs

DatabaseBackupJob failed with: SQLSTATE[42703]: Undefined column: 7 ERROR:  column "status" of relation "scheduled_database_backups" does not exist
LINE 1: update "scheduled_database_backups" set "status" = $1, "upda...
                                                ^ (Connection: pgsql, SQL: update "scheduled_database_backups" set "status" = failed, "updated_at" = 2024-10-01 07:13:08 where "id" = 0)

### Steps to Reproduce

1. Add a new S3 Storage
2. Go to Settings -> Scheduled Backup -> check S3 Enabled -> Backup now
3. Get the error message (for me in telegram)

Even when I uncheck S3 it crashes so this does not seem to be the problem. I'm on the newest version. Is there the possibility I have to run some migrations again?

### Coolify Version

v4.0.0-beta.347

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Debian GNU/Linux 12 (bookworm)

### Additional Information

I've hosted supabase, appwrite and a nextjs application. Everything besides the backup works fine. At first I had the previous coolify version. After upgrading to the newest version, the error isn't gone yet. but changed from

> DatabaseBackupJob failed with: Attempt to read property "id" on null

to the error I've provided

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.

**Comment by lorenzpfei** [comment]
@andrasbacsai  Thank you very much! Is there an estimated release date?
