### ISSUE TITLE
hard to understand reverse logs 

### ISSUE THREAD

**Issue by vasani-arpit** [coollabsio/coolify#366]
I am on version 2.5.0. I noticed that logs are being reversed in this version. Can this be a setting at application leval because I can't make sense of the object I logged in reverse. take a look at this. 

![image](https://user-images.githubusercontent.com/6497827/164430718-00d93d5d-ede8-4163-a7f1-fb3510fa8552.png)

It is hard to understand the printed object when it is in reverse. 

If we can put a switch in configuration on whether to reverse log or not then I think it would be nice to have. 

It is not troubling, It is doing this it's job but this is something nice to have. Currently I am sshing into the server and seeing the logs using `docker logs` command

**Comment by dgc1980** [comment]
after upgrading to 2.5.0, I agree reverse logging is not an understandable option as it makes things much harder to read and understand. at least make this an optional change for people.

**Comment by andrasbacsai** [comment]
Yeah, it was a good idea in the first place, but it could be hard to read for sure. I'll revert it in the next version.

**Comment by andrasbacsai** [comment]
Closed by #369
