### ISSUE TITLE
[Bug]: Invoice Ninja is not in the services list

### ISSUE THREAD

**Issue by Deveopix** [coollabsio/coolify#3662]
### Error Message and Logs

Invoice Ninja (https://coolify.io/docs/services/invoice-ninja) can not be found in the services list.

![image](https://github.com/user-attachments/assets/47fe43cb-7fd2-4e9e-b9f0-132acc0c1917)
![image](https://github.com/user-attachments/assets/c3faf1f7-0b51-4495-8682-c42235fc0458)

### Steps to Reproduce

1. Select a Project
2. Add a resource
3. Invoice Ninja can't be found in the services list

### Coolify Version

v4.0.0-beta.347

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Debian GNU/Linux 12 (bookworm)

**Comment by Skeyelab** [comment]
@peaklabs-dev @andrasbacsai - it seems the invoice ninja install is not working.  I cannot save any invoices.

**Comment by peaklabs-dev** [comment]
@Skeyelab Please open a new issue for this.
