### ISSUE TITLE
[Bug]: Docker compose: HTML templates not updating on redeploy/restart

### ISSUE THREAD

**Issue by mtkgeek** [coollabsio/coolify#3667]
### Error Message and Logs

I don't know if this is a FastApi specific thing but after deploying my app via github, subsequent updates to the HTML templates are not reflected. Changes in Python files work though. Restarting/redeploying without cache, clearing browser cache, etc nothing works. It's only seen in docker compose where you have multiple containers.

### Steps to Reproduce

1. Deploy a  3 simple Fastapi app with templates using docker compose
2. Make changes to any HTML file in the templates folder
3. Redeploy or restart your project on coolify

### Coolify Version

v4.0.0-beta.349

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04

**Comment by djsisson** [comment]
can you paste your compose

are you using volume mounts? they might be overriding whats inside the containers

**Comment by djsisson** [comment]
in your dockerfiles are you copying the files you need into the container?

what is supposed to be in the /code folder in each container

**Comment by mtkgeek** [comment]
Removing the volumes fixed the issue., thanks.
