### ISSUE TITLE
[Bug]: Backup not working

### ISSUE THREAD

**Issue by lorenzpfei** [coollabsio/coolify#3668]
### Error Message and Logs

Yesterday, I've posted this issue: https://github.com/coollabsio/coolify/issues/3652

After updating to [v4.0.0-beta.349](https://github.com/coollabsio/coolify/releases/tag/v4.0.0-beta.349)

I unfortunately now get the error 

> DatabaseBackupJob failed with: Typed property App\Jobs\DatabaseBackupJob::$database must not be accessed before initialization

### Steps to Reproduce

1. Add a new S3 Storage
2. Go to Settings -> Scheduled Backup -> check S3 Enabled -> Backup now
3. Get the error message (for me in telegram)

### Coolify Version

v4.0.0-beta.349

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Debian GNU/Linux 12 (bookworm)

**Comment by andrasbacsai** [comment]
I made some additional fixes in the next version, but I could not reproduce the issue on my side.
