### ISSUE TITLE
[Bug]: proxy does not work

### ISSUE THREAD

**Issue by a0m0rajab** [coollabsio/coolify#3669]
### Error Message and Logs

I am getting the next error on the pages: 
404 

and this error in traefik: 

"error: port is missing"

I did have a normal docker compose file yet 

### Steps to Reproduce

1. use docker compose file without any extra data
2. run the server with traefik
4.
5.

### Coolify Version

v4.0.0-beta.347

### Are you using Coolify Cloud?

No (self-hosted)

**Comment by peaklabs-dev** [comment]
Could you please provide more detailed reproduction steps for this issue and a sample compose file? This will help us investigate and resolve the issue.
