### ISSUE TITLE
bug? multiple github accounts weird behavior

### ISSUE THREAD

**Issue by jdbrice** [coollabsio/coolify#367]
I created an instance with account A as the owner/admin.
Then I added a different account (account B) under a new team.
Each account was signed into different (personal) github accounts.
However, when I log into account B and try to add an application, the dropdown gives me the list of repos from account A's github.

As a check I went to the github tab and clicked "Change Github App Settings" - and it does opens the correct github account settings page for that user. I am using v2.5.0 

Has anyone else run into this? I am even using two different browsers for the two different logins to avoid any cookie sharing. Let me know if there are some logs etc. that could help

**Comment by andrasbacsai** [comment]
Nice catch! I forgot to clean up tokens in team switching. 

The next version will cover this fix!

**Comment by andrasbacsai** [comment]
Closed by #369
