### ISSUE TITLE
[Bug]:  swtiching proxy makes UI dissappear

### ISSUE THREAD

**Issue by a0m0rajab** [coollabsio/coolify#3670]
### Error Message and Logs

when I switch proxy from caddy to traefik or vice versa, the proxy ui disappears. 
it would be great to keep it. 

### Steps to Reproduce

1. self host the project
2. set the proxy as traefik
3. switch the proxy to caddy
4.

### Coolify Version

v4.0.0-beta.347

### Are you using Coolify Cloud?

No (self-hosted)

**Comment by peaklabs-dev** [comment]
This issue should be resolved in the latest version as we changed the proxy selection a bit. If you're still experiencing this issue, please reopen or create a new issue with updated details.
