### ISSUE TITLE
[Bug]: Unable to find Image

### ISSUE THREAD

**Issue by sikc231** [coollabsio/coolify#3675]
### Error Message and Logs

![image](https://github.com/user-attachments/assets/41c6d479-e436-4f0c-8046-6cba08018389)
Running Rasbian OS
ARM64
Rasberry PI 5

should be no problems..

### Steps to Reproduce

Installing curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash

### Coolify Version

Latest

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Rasbian OS

**Comment by sikc231** [comment]
last step is failing: 
docker compose --env-file /data/coolify/source/.env -f /data/coolify/source/docker-compose.yml -f /data/coolify/source/docker-compose.prod.yml up -d --pull always --remove-orphans --force-recreate

**Comment by sikc231** [comment]
@andrasbacsai 
Hi! Sorry to annoy, perhaps you could help here? :)

**Comment by peaklabs-dev** [comment]
Can you please show me the output of
```bash
uname -m
```

**Comment by sikc231** [comment]
![image](https://github.com/user-attachments/assets/a32b8ba7-6b19-4af0-abbe-3ae2260221b1)
@peaklabs-dev hi! here you go
It is ARM64 which is supported by coolify

**Comment by peaklabs-dev** [comment]
Thank you I will investigate and fix it.

**Comment by sikc231** [comment]
@peaklabs-dev thank you so much!
Is there any estimations when this fix could be in prod?

**Comment by sikc231** [comment]
@peaklabs-dev if you will need any help when it comes to testing or else. let me know

**Comment by peaklabs-dev** [comment]
I have two ideas where the problem could come from, so I need your help to verify my theories.
1. Could you please run the following command and give me the output:
- Let us see if we can get the helper image manually by using the following command:
```bash
docker pull ghcr.io/coollabsio/coolify-helper:1.0.1
```
- If the above command does not work, please let me know and try again with this command:
```bash
docker pull ghcr.io/coollabsio/coolify-helper:1.0.1@sha256:3ca159771d0bb4e1f55df7d9e92544c421cd83d80f916f0500f20fe81c131393
```
2. Could you please run the Coolify install with verbose logging and show me the error Output (maybe we can get more details), I think the problem comes from the `upgrade.sh` script which is also used during installation, so this would help.
```bash
curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash -x
```
-> I am pretty sure I know how to fix it, but just to be sure.

**Comment by sikc231** [comment]
![image](https://github.com/user-attachments/assets/82a8c12a-8dd9-4471-84f7-535bb89864fc)
Hi @peaklabs-dev 
That's the error im getting now.

**Comment by peaklabs-dev** [comment]
Thanks, I search for a loooot of hours and found out raspian OS is just stupid. It is just a thing I need to add to the docs probably. Will finish this up tomorrow and let you now how I decide to so it. The point is I do not think going into the future 32bit aupport makes sense but I have to think about it.

**Comment by artificialguybr** [comment]
A similar error with Oracle ARM64.


   _____            _ _  __
  / ____|          | (_)/ _|
 | |     ___   ___ | |_| |_ _   _
 | |    / _ \ / _ \| | |  _| | | |
 | |___| (_) | (_) | | | | | |_| |
  \_____\___/ \___/|_|_|_|  \__, |
                             __/ |
                            |___/

Welcome to Coolify Installer!
This script will install everything for you. Sit back and relax.
Source code: https://github.com/coollabsio/coolify/blob/main/scripts/install.sh

---------------------------------------------
| Operating System  | ubuntu 22.04
| Docker            | 26.0
| Coolify           | 4.0.0-beta.355
| Helper            | 1.0.1
| Realtime          | 1.0.3
---------------------------------------------

1. Installing required packages (curl, wget, git, jq). 
W: https://download.docker.com/linux/ubuntu/dists/focal/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
2. Check OpenSSH server configuration. 
 - OpenSSH server is installed.
 - SSH PermitRootLogin is enabled.
3. Check Docker Installation. 
 - Docker is installed.
4. Check Docker Configuration. 
 - Docker configuration is up to date.
5. Download required files from CDN. 
6. Make backup of .env to .env-20241006-003519
7. Propagating .env with new values - if necessary.
8. Checking for SSH key for localhost access.
 - Generating SSH key.
/data/coolify/ssh/keys/id.root@host.docker.internal already exists.
Overwrite (y/n)? y
9. Installing Coolify (4.0.0-beta.355)
 - It could take a while based on your server's performance, network speed, stars, etc.
 - Please wait.
 - Until then, here's a joke for you:

Knock knock.
Who's there?
Recursion.
Recursion who?
Knock knock.

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested. 

It was working before. (Some months ago)

**Comment by sikc231** [comment]
Hi @peaklabs-dev 
docker pull [ghcr.io/coollabsio/coolify-helper:1.0.1@sha256:3ca159771d0bb4e1f55df7d9e92544c421cd83d80f916f0500f20fe81c131393](http://ghcr.io/coollabsio/coolify-helper:1.0.1@sha256:3ca159771d0bb4e1f55df7d9e92544c421cd83d80f916f0500f20fe81c131393)

this command seems to pull successfully.
If possible I prefer not to reinstall my rasbian OS.

Now its seems that it fails at pulling redis and postgres
![image](https://github.com/user-attachments/assets/328dd737-c44a-4c97-884f-673aa9927a9b)

**Comment by sikc231** [comment]
Some new error when trying to start coolify manually with 
![image](https://github.com/user-attachments/assets/e71a2b39-66c7-4981-894f-52838577ff6f)

![image](https://github.com/user-attachments/assets/9c8cdc3d-c1c3-4919-840f-12d0d713cf75)

**Comment by peaklabs-dev** [comment]
@sikc231 Question on how you initially set up your PI:
1. You bougth the PI
2. you booted the pi and did upgrades and updates via apt
3. you installed Coolify via the installer
Am I correct or did you manually go to the website and install the 64-bit version of the pi OS?

**Comment by peaklabs-dev** [comment]
@artificialguybr and @sikc231 Can you please show me the output of these commands (again):
```bash
uname -m
```

and 
```
docker info | grep Architecture
```

**Comment by artificialguybr** [comment]
> @artificialguybr and @sikc231 Can you please show me the output of these commands (again):
> 
> ```shell
> uname -m
> ```
> 
> and
> 
> ```
> docker info | grep Architecture
> ```

This started about 14 hours ago. The bug happens in a Next JS app deployment
aarch64
 Architecture: aarch64

I don't know if it's related, but another nextjs project that deployed correctly used Comfy Helper 1.0.0 and it worked

**Comment by peaklabs-dev** [comment]
@artificialguybr Can you try gain now I made a small change?

**Comment by artificialguybr** [comment]
> @artificialguybr Can you try again now I made a small change?

Restarted, redeploy, redeploy without cache. All with same error.

**Comment by peaklabs-dev** [comment]
@artificialguybr I think your error is ressource related and not installer related maybe your nextjs ressource does not have an arm image, could you open a new issue for your problem so we can solve this better as this issue is probably pi related and different from yours. Thank you very much.

**Comment by artificialguybr** [comment]
> @artificialguybr I think your error is ressource related and not installer related maybe your nextjs ressource does not have an arm image, could you open a new issue for your problem so we can solve this better as this issue is probably pi related and different from yours. Thank you very much.

Done. Thanks. https://github.com/coollabsio/coolify/issues/3745

**Comment by sikc231** [comment]
@peaklabs-dev hi, here you go
![image](https://github.com/user-attachments/assets/36a7287a-21c9-493e-a70c-87400d999aab)

**Comment by peaklabs-dev** [comment]
- @sikc231 Can you please answer this as well https://github.com/coollabsio/coolify/issues/3675#issuecomment-2395443439
- I have to wait for an answer to the Raspberry PI GitHub on this [issue] (https://github.com/raspberrypi/linux/issues/5402#issuecomment-2395442892). 
- I will also order my own PI 5 and test it on my own and see if I can cook up a fix, as my pi will only arrive sometime next week I will have to put this on hold until it arrives I hope for your understanding and thank you for your help in resolving this.

**Comment by sikc231** [comment]
> @sikc231 Question on how you initially set up your PI:
> 
> 1. You bougth the PI
> 2. you booted the pi and did upgrades and updates via apt
> 3. you installed Coolify via the installer
>    Am I correct or did you manually go to the website and install the 64-bit version of the pi OS?

HI.
I do not remember the steps I took as it was 10 months ago.
I believe PI came with the sim card with already existing image of it. But not sure about it.
I have PI 5 which has quad-core 64-bit Arm Cortex-A76 processor, meaning the output of uname -m is correct (aarch64)

**Comment by peaklabs-dev** [comment]
Thank you. The reason why I ask all this is because PIs ship with 32bit OS version by default most of the time and and upgrade changed it to 64bit which does not really work that well (see here https://github.com/raspberrypi/linux/issues/5402), so I am unsure if this issue is even Coolfiy related as we do provide and ARM64 image which is compatible with linux/arm/v8 64-bit. I will have to wait for a response from the pi team and my own pi to resolve this.

**Comment by peaklabs-dev** [comment]
@sikc231 Can you please show me the output of the following command:
```bash
getconf LONG_BIT
```

**Comment by sikc231** [comment]
@peaklabs-dev 
![image](https://github.com/user-attachments/assets/6a6d8654-03f5-49b2-b3c3-daac0675be0b)

**Comment by peaklabs-dev** [comment]
And we got it, finally :). This is because your `userspace architecture` is still 32-bit, so Coolify will not work as it only supports 64-bit. You are running into this [issue](https://github.com/raspberrypi/linux/issues/5402). I will ask if you can do anything other than just a fresh clean install of the 64-bit OS, as that would be the best option for you to fix this, but you mentioned that you do not want to do that.

**Comment by sikc231** [comment]
@peaklabs-dev thanks! you are awesome!
For people that will run in similar error:
check if your kernel is 64 bit by using command: getconf LONG_BIT
**if it says 32bit, coolify won't work**
I reinstalled my rasberry pi 5 with Rasbian OS 64bit and installation went successfully

**Comment by peaklabs-dev** [comment]
I have now also updated the documentation with a guide on how to install the 64-bit version of the OS, which solves this problem with a Guide.
