### ISSUE TITLE
[Bug]: Deployment is duplicated for every github push 

### ISSUE THREAD

**Issue by fmendez** [coollabsio/coolify#3677]
### Error Message and Logs

Every time I try to deploy new changes, I get 2 deployment attempts at once. After first, I thought it was a UI issue and it was showing the same process twice, but they have different outcomes (e.g one fails while the other works). This seems to put extra strain on the server since the entire process of compiling resources it happening twice for every attempt:

Note: In case is relevant, these were Dockerized projects. 

Examples:

![Screenshot 2024-10-02 at 4 39 08 AM](https://github.com/user-attachments/assets/9dd76741-3289-4593-8ae7-0da0c0f0f238)

![Screenshot 2024-10-02 at 4 35 08 AM](https://github.com/user-attachments/assets/b4cb4c29-4282-49c6-90e1-cd173360334d)

![Screenshot 2024-10-02 at 4 33 38 AM](https://github.com/user-attachments/assets/8ced22eb-f928-4251-9b27-40cc113c05da)

### Steps to Reproduce

1. Deploy via any Dockerized project.
2. Check the Deployment section 

### Coolify Version

v4.0.0-beta.349

### Are you using Coolify Cloud?

Yes (Coolify Cloud)

**Comment by fcpauldiaz** [comment]
this can happen if you have multiple Sources for the same repo

**Comment by fmendez** [comment]
I see the bug more clearly now. It is not having multiple Source for the same repo that's the issue, but just having multiple Sources attached to Github period. I had a leftover Source configured from a few months ago when I was first testing Coolify. That Source was no longer pointing to any repository but still was triggering a secondary deployment. Now that I remove it, the deployment triggers only one:

![image](https://github.com/user-attachments/assets/95bbbaab-7545-4b5e-8bf6-59e7c33d5f8b)

Thanks for the hint @fcpauldiaz, I'll go ahead and close this.
