### ISSUE TITLE
throwing error during switching team  

### ISSUE THREAD

**Issue by MIShuvro** [coollabsio/coolify#368]
<img width="1778" alt="Screenshot 2022-04-22 at 12 51 04 PM" src="https://user-images.githubusercontent.com/33565583/164620131-5db6f860-94b6-4387-b9d9-612010e8a307.png">

**Comment by vasani-arpit** [comment]
Can you add the steps ? What did you do which lead you to this error?

**Comment by andrasbacsai** [comment]
Please let me know if the new version still has this issue! If yes, please reopen the ticket!
