### ISSUE TITLE
[Bug]: Backup not working | connect: cannot assign requested address

### ISSUE THREAD

**Issue by Hexacker** [coollabsio/coolify#3686]
### Error Message and Logs

I have setup the DB backup to be on CloudFlare R2, it was working until I upgraded to v4.0.0-beta.349 and v4.0.0-beta.350. I'm getting this error:

> mc: <ERROR> Unable to initialize new alias from the provided credentials. Get "https://CLOUDFLARE-R2-LINK/probe-bsign-12birz1zdcqsil54zjl1kfa0v9cvvi/?location=": dial tcp [2a06:98c1:58::ec]:443: connect: cannot assign requested address.

### Steps to Reproduce

1. Set up R2
2. Set up DB/Project auto backup
3. Back up the DB/Project

### Coolify Version

v4.0.0-beta.350

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Alpine Linux

**Comment by andrasbacsai** [comment]
This looks like a connection error to R2 on IPv6.

Can you please downgrade to the previous version where it worked and check if it working there?

**Comment by Hexacker** [comment]
It works on version v4.0.0-beta.348

**Comment by Hexacker** [comment]
I migrated to the latest version, here is the full error:

> mc: <ERROR> Failed to copy `/data/coolify/backups/databases/root-team-0/postgres-db-ss8c0swo0o4c0gs4ww08kkos/pg-dump-workleen-1728691202.dmp`. SigV2 authorization is not supported. Please use SigV4 instead.

**Comment by peaklabs-dev** [comment]
@Hexacker We have upgraded a lot of packages in the latest version, is this error still happening for you?

**Comment by peaklabs-dev** [comment]
Glad it works now. I will close this issue then.
