### ISSUE TITLE
[Bug]: Create Application endpoints returning 500

### ISSUE THREAD

**Issue by doiska** [coollabsio/coolify#3692]
### Error Message and Logs

Any Create Application endpoint is returning 500 after the beta.348 update.

```Error: Indirect modification of overloaded property App\Models\Application::$settings has no effect```

```
<p class="font-mono font-semibold text-red-500 text-7xl">500</p>
<h1 class="mt-4 font-bold tracking-tight dark:text-white">Something is not okay, are you okay?</h1>
<p class="text-base leading-7 text-neutral-300">There has been an error, we are working on it.
</p>
<code class="mt-6 text-xs text-left text-red-500">Error: Indirect modification of overloaded property App\Models\Application::$settings has no effect
</code>
```

Just upgraded to 350 and the error persists.

### Steps to Reproduce

1. Call ```/applications/private-github-app``` with any valid payload.
```
{
    "name": "--",
    "project_uuid": "c8csc8ooc0sk08ogkgs8wgog",
    "server_uuid": "p4owcs8",
    "destination_uuid": "0",
    "environment_name": "production",
    "github_app_uuid": "--",
    "git_repository": "--",
    "git_branch": "main",
    "ports_exposes": "3000",
    "build_pack": "nixpacks",
}
```

Had to replace some things, but I've been using this payload since beta.347.

### Coolify Version

v4.0.0-beta.349, v4.0.0-beta.350

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

20.04.6 LTS (Focal Fossa)

### Additional Information

I suspect that is around those lines, because 348 introduced a refactor of instanceSettings: https://github.com/coollabsio/coolify/blob/main/app/Http/Controllers/Api/ApplicationsController.php#L747

![image](https://github.com/user-attachments/assets/19fe1ae7-b544-44c3-a1ff-11f95a9ed060)

Thank you.

**Comment by andrasbacsai** [comment]
Can you please check with v351?

**Comment by doiska** [comment]
Damn you're fast. It's working, thank you!!
