### ISSUE TITLE
[Bug]: coolify-proxy doesn't start if port 80 is in use, even when not configured to use that port

### ISSUE THREAD

**Issue by Morpheus0x** [coollabsio/coolify#3693]
### Error Message and Logs

When restarting coolify-proxy from the web UI the following error is shown:
```
Error
Port 80 is in use.
You must stop the process using this port.
Docs: https://coolify.io/docs
Discord: https://coollabs.io/discord
```
This is odd since the chosen exposed ports in the docker-compose.yml ([docker-compose.yml.txt](https://github.com/user-attachments/files/17244859/docker-compose.yml.txt)) file for coolify-proxy does not use port 80

### Steps to Reproduce

1. Start the server, coolify starts with docker normally. 
2. Go to the Server Settings for the Proxy in the web UI or edit the file `/data/coolify/proxy/docker-compose.yml`. Change the host ports from 80 to 5080 and 443 to 5443 
3. Restart coolify-proxy, which works without issue. All hosted applications can now be reached on port 5080 & 5443
4. Looking at `netstat -tulpen`, no application should use port 80 or 443 ([netstat_before_nginx.txt](https://github.com/user-attachments/files/17244875/netstat_before_nginx.txt))
5. Have an application use port 80, for example nginx ([netstat_nginx_started.txt](https://github.com/user-attachments/files/17244876/netstat_nginx_started.txt))
6. Restarting coolify-proxy via the docker command works `docker restart coolify-proxy`
7. However, when restarting the proxy via the web UI, the error above is thrown. It appears that there are some hardcoded checks for port 80 in the coolify application

### Coolify Version

v4.0.0-beta.350

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Rocky Linux 9.4

### Additional Information

Since my VM doesn't have a public IP address and is behind a firewall, I decided not to use the default 80 and 443 port for the coolify-proxy container, instead I used 5080 and 5443.
For Port 80 and 443 I use a locally installed nginx which is used to proxy port 8000, 6001 and 6002 for the management UI. I did this to not expose the management UI to the internet. Instead, it is only reachable via my internal network on the LAN IP of the VM.

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version.

**Comment by Morpheus0x** [comment]
Awesome, thanks for the incredibly quick turnaround time to fix this! I just updated and tested this and it works!
