### ISSUE TITLE
[Bug]: No Autofill for user passwords after beta 349

### ISSUE THREAD

**Issue by alepouna** [coollabsio/coolify#3698]
### Error Message and Logs

N/A

### Steps to Reproduce

1. Perform any action that requires confirmation with user password

### Coolify Version

v4.0.0-beta.349

### Are you using Coolify Cloud?

No (self-hosted)

### Additional Information

Probably relevant release: https://github.com/coollabsio/coolify/releases/tag/v4.0.0-beta.349

Recommend to just add an autofill password field on the input for better UX with password managers 👌

**Comment by peaklabs-dev** [comment]
A fix for this issue has been implemented and will be available in an upcoming release. Thank you for your patience.
