### ISSUE TITLE
[Bug]: Service Settings inaccessible

### ISSUE THREAD

**Issue by GottZ** [coollabsio/coolify#3700]
### Error Message and Logs

Error: Call to a member function isBackupSolutionAvailable() on null (View: /var/www/html/resources/views/livewire/project/service/index.blade.php)

### Steps to Reproduce

1. Install beta 349
2. update to beta 351
3. deploy a random docker-compose project
4. click settings on one of the services deployed from the compose file
   ![image](https://github.com/user-attachments/assets/567fa332-bf33-4e29-b6bc-54069ec1d736)
5. see a 500 error referring to
   ```
   Error: Call to a member function isBackupSolutionAvailable() on null (View: /var/www/html/resources/views/livewire/project/service/index.blade.php)
   ```
   ![image](https://github.com/user-attachments/assets/8e16c1ac-6f41-429e-9878-4e93ab376a7e)

### Coolify Version

v4.0.0-beta.351

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Arch Linux

### Additional Information

I assume it relates to [this](https://github.com/coollabsio/coolify/commit/bb6cb8edc92c37cbaae82c2024468f0d7775d49c) commit in some way.

**Comment by andrasbacsai** [comment]
This will be fixed in the upcoming version - releasing in a few mins.
