### ISSUE TITLE
[Bug]: Autocomplete with email address

### ISSUE THREAD

**Issue by stuckinsnow** [coollabsio/coolify#3732]
### Error Message and Logs

Similar to a previous bug that was fixed, an email address populates the "Chat ID" field for Telegram notifications. This is also present with OAuth settings. 

### Steps to Reproduce

1. Click "Notifications"
2. Click "Telegram"
3. Wait a second, and the "Chat ID" will populate with your email address.
4. Navigate to "settings", click "OAuth" and the same bug is present. 

### Coolify Version

latest

### Are you using Coolify Cloud?

No (self-hosted)

**Comment by peaklabs-dev** [comment]
A fix for this issue has been implemented and will be available in an upcoming release. Thank you for your patience.
