### ISSUE TITLE
[Bug]: proxy log not work

### ISSUE THREAD

**Issue by mredodos** [coollabsio/coolify#3739]
### Error Message and Logs

![image](https://github.com/user-attachments/assets/689104dd-6c7e-4de7-82b2-19aca96462bd)

proxy log not show info after refresh or stream

### Steps to Reproduce

1. Got to proxy in server 
2. click on refresh or active stream

### Coolify Version

v4.0.0-beta.355

### Are you using Coolify Cloud?

Yes (Coolify Cloud)

**Comment by andrasbacsai** [comment]
Can you please check if the actual container has logs? Because if it does not have, then this is normal.

**Comment by mredodos** [comment]
i dont know but after few try it seems works

**Comment by peaklabs-dev** [comment]
Glad to see that it works now. I will close this issue then.
