### ISSUE TITLE
[Bug]:  Problems with deploying NextJS app. ARM64

### ISSUE THREAD

**Issue by artificialguybr** [coollabsio/coolify#3745]
### Error Message and Logs

2024-Oct-06 03:51:00.208076
Starting deployment of artificialguybr/s-jdisc:teste-servidor to localhost.
2024-Oct-06 03:51:00.412828
Preparing container with helper image: ghcr.io/coollabsio/coolify-helper:1.0.1.
2024-Oct-06 03:51:00.534039
docker rm -f f0kc4kwk844osggg4o4k8gc8
2024-Oct-06 03:51:00.534039
Error response from daemon: No such container: f0kc4kwk844osggg4o4k8gc8
2024-Oct-06 03:51:00.684907
docker run -d --network coolify --name f0kc4kwk844osggg4o4k8gc8 --rm -v /var/run/docker.sock:/var/run/docker.sock ghcr.io/coollabsio/coolify-helper:1.0.1
2024-Oct-06 03:51:00.684907
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
2024-Oct-06 03:51:00.687541
2920bda13a26ddb9111f77ca9a803ddadd04469be3472dcaa803af81335df5dc
2024-Oct-06 03:51:00.985504
docker exec f0kc4kwk844osggg4o4k8gc8 bash -c 'mkdir -p /artifacts/f0kc4kwk844osggg4o4k8gc8'
2024-Oct-06 03:51:00.985504
Error response from daemon: No such container: f0kc4kwk844osggg4o4k8gc8
2024-Oct-06 03:51:01.034425
Oops something is not okay, are you okay? 😢
2024-Oct-06 03:51:01.036997
Error response from daemon: No such container: f0kc4kwk844osggg4o4k8gc8
2024-Oct-06 03:51:01.039549
Deployment failed. Removing the new version of your application.

### Steps to Reproduce

1.Try deploying a NextJS app.
2.This error will happen

### Coolify Version

v4.0.0-beta.355

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04

### Additional Information

This repository worked correctly. It stopped deploying 14~15 hours ago. 17:11:52 on Saturday, October 5th, 2024. Los Angeles time.

Other Next repositories work when using Comfy Helper 1.0.0

**Comment by artificialguybr** [comment]
Context: This repository was working normally until about 15 hours ago. There were some visual changes to the project's CSS and a new deployment was attempted. However, this error started appearing immediately. I created a new branch up to the date of the commit prior to this one, but the error is still appearing. There have been no structural changes to the Next project other than components + css. Another, more basic Next.js project works. One of the differences I noticed is that it uses Comfy Helper 1.0.0, when the repository that have problems is using 1.0.1. I don't know if it's related. It's being deployed with Nixpacks, all standard.

**Comment by peaklabs-dev** [comment]
Can you please manually remove the helper image on the server and then try to re-deploy (maybe something was broken with the image (the manifest probably).
1. remove the helper image manually
```bash
docker rmi ghcr.io/coollabsio/coolify-helper:1.0.1
```
2. re-deploy

-> I can not reproduce the error on my end on ARM64 (dev machine) with the example repository: https://github.com/coollabsio/coolify-examples/tree/main/nextjs/ssr.

**Comment by artificialguybr** [comment]
Fixed. Thanks!
