### ISSUE TITLE
[Bug]: Deleted project still visible in server resources

### ISSUE THREAD

**Issue by KaelWD** [coollabsio/coolify#3747]
### Error Message and Logs

![image](https://github.com/user-attachments/assets/0d71d33d-76ad-4a97-a5a6-26fc720dc190)

### Steps to Reproduce

1. Create a docker compose project (without git) from https://github.com/Swetrix/selfhosting/blob/main/docker-compose.yml
2. Delete the project without stopping or deleting any resources first

### Coolify Version

v4.0.0-beta.355

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04

### Additional Information

Looks the same as #1937

**Comment by shiv122** [comment]
try triggering docker cleanup and then delete it. it works sometimes.
Server> select server > general > setting > Force Docker Cleanup

![image](https://github.com/user-attachments/assets/8a1d0a09-faad-4dae-a8b4-099091a0fb45)

**Comment by KaelWD** [comment]
I already tried that. I also can't see it in `docker images` or `docker ps -a`.

**Comment by shiv122** [comment]
yes I'm having same issue , it worked with one, but when you delete the container manually cleanup doesn't work.

**Comment by iustin05** [comment]
Same for me, sometimes containers remain on disk..

**Comment by KaelWD** [comment]
Idk what happened but it's gone now.

**Comment by peaklabs-dev** [comment]
I cannot reproduce. If a project has a resource, you cannot delete it and you get this error: `Environment has defined resources, please delete them first.`

**Comment by peaklabs-dev** [comment]
I cannot reproduce. If a project has a resource, you cannot delete it and you get this error: `Environment has defined resources, please delete them first.` Can you help me with more detailed steps on how you managed to delete the project in the first place?

**Comment by KaelWD** [comment]
I don't know, I never got that warning for some reason.

**Comment by KaelWD** [comment]
Yeah it still happens with 360. 

- Create a project
- Add a "docker compose empty" resource and paste in https://github.com/Swetrix/selfhosting/blob/main/docker-compose.yml
- Go back to the project root using the breadcrumbs
- Click "delete project" and confirm

No error appears, and there is an entry under server -> resources that has no associated project and links to nowhere.

**Comment by KaelWD** [comment]
What is the difference between services and applications? DeleteProject only checks for applications: https://github.com/coollabsio/coolify/blob/dfd218ec064790d214bc57d3d9b3840f35b6a379/app/Livewire/Project/DeleteProject.php#L30-L32

**Comment by KaelWD** [comment]
Deleting an environment does all this instead:

https://github.com/coollabsio/coolify/blob/2d3a6a4528cc9e077a5b6c63f7f691f2155ee214/app/Models/Environment.php#L37-L49

**Comment by peaklabs-dev** [comment]
Thanks for the details, I can now reproduce it and have fixed this and will PR after some testing.

**Comment by ohkimur** [comment]
@peaklabs-dev This is still happening. If you go to the dashboard and click on a project, then click delete, it will delete the project but not it's resources.

**Comment by peaklabs-dev** [comment]
@ohkimur yes because the new version is not out yet.

**Comment by ohkimur** [comment]
@peaklabs-dev Oh, I see. Thanks for letting me know!
