### ISSUE TITLE
[Bug]: Running containers after project has been deleted

### ISSUE THREAD

**Issue by weewoo-meow** [coollabsio/coolify#3753]
### Error Message and Logs

When I add several services like Appwrite or Supabase in my project, run them and then delete the containing project without stopping the containers, the containers still run and I can see them in the Terminal selection and when I run "docker container ls".

### Steps to Reproduce

1. Create project
2. Add Supabase
3. Run Supabase
4. Delete project while Supabase is running
5. Check Terminal container selection dropdown menu.

### Coolify Version

v4.0.0-beta.355

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04

**Comment by mattmarcin** [comment]
Noticed this issue as well. Is there a way to fix this if you already deleted the project?

**Comment by weewoo-meow** [comment]
I just went into the terminal, stopped and deleted the affecting containers. You just need to know which ones are the right ones.

**Comment by dsbilling** [comment]
I got the same issue, there should be some validation that everything within a project has to be deleted first.

**Comment by mika-subrequest** [comment]
Hello, I am still experiencing an issue with the [v4.0.0-beta.367] cloud app. I’m using a custom Docker Compose setup, and the app_container continues running even after I deleted the project
