### ISSUE TITLE
Database: MS SQL Server

### ISSUE THREAD

**Issue by vasani-arpit** [coollabsio/coolify#379]
Support for Microsoft SQL Server as database service. 

Here is a command to spin up the container
```bash
sudo docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=<YourStrong@Passw0rd>" \
   -p 1433:1433 --name sql1 --hostname sql1 \
   -d mcr.microsoft.com/mssql/server:2019-latest
```

**Comment by andrasbacsai** [comment]
Closing this one in favor of: https://feedback.coolify.io/posts/62/database-mssql
