### ISSUE TITLE
[Bug]: PullHelperImageJob failed with: cURL error 7: Couldn't connect to server

### ISSUE THREAD

**Issue by Jonathan-Asher** [coollabsio/coolify#3791]
### Error Message and Logs

PullHelperImageJob failed with: cURL error 7: Couldn't connect to server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://cdn.coollabs.io/coolify/versions.json

### Steps to Reproduce

I can’t determine what caused this error; it suddenly started appearing with Telegram notifications every few hours, at the start of every hour

### Coolify Version

v4.0.0-beta.347

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04 LTS

**Comment by blasdfaa** [comment]
Same problem with `cURL error 28: SSL connection timeout`

**Comment by peaklabs-dev** [comment]
This was probably just a temporary ghrc issue. If this error occurs again, feel free to reopen or create a new issue.
