### ISSUE TITLE
[Bug]: Cannot select server for new resource

### ISSUE THREAD

**Issue by ppulwey** [coollabsio/coolify#3792]
### Error Message and Logs

After upgrading to beta.356 I wanted to add a new resource to a Project. After selecting the resource type, I get the Server selection page. Here, the 3rd and the 5th option is not clickable. I renamed a server so that the order of the servers changed. Still the 3th and 5th option are not selectable. So this seems not to be related to the server itself.
<img width="1529" alt="Screenshot 2024-10-08 at 16 09 40" src="https://github.com/user-attachments/assets/34c1e340-d73d-468b-8ed4-37c8b5da2f1f">

### Steps to Reproduce

1. Select or create new project
2. Click "Add resource" to any environment
3. Select a resource
4. In the server selection page, the 3th and 5th options are not available

### Coolify Version

v.4.0.0-beta.356

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04

**Comment by audis-labs** [comment]
Updating to 4.0.0-beta.357 has resolved this issue for me.

**Comment by ppulwey** [comment]
> Updating to 4.0.0-beta.357 has resolved this issue for me.

Funny that the fix came out 1 hour after my bug report ;)
