### ISSUE TITLE
[Bug]: Can't reuse domain on new service after a resource with a service with the same domain has been deleted from an unreachable server

### ISSUE THREAD

**Issue by alxhu-dev** [coollabsio/coolify#3793]
### Error Message and Logs

`Error: SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "service_applications_fqdn_unique" DETAIL: Key (fqdn)=(https://example.org:9980) already exists. (Connection: pgsql, SQL: update "service_applications" set "fqdn" = https://example.org:9980, "image" = collabora/code, "updated_at" = 2024-10-08 14:14:38 where "id" = 57)`

### Steps to Reproduce

1. Create a server
2. Add a resource
3. Add a domain to a service in the resource
4. Deploy
5. Shut down the server
6. Remove resource from the server while the server is shut down
7. Create a resource (on another server)
8. Try to add the same to domain to a service in the resource

### Coolify Version

v4.0.0-beta.356

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Debian 12

**Comment by peaklabs-dev** [comment]
This issue has been fixed in the latest version.
