### ISSUE TITLE
[Bug]: Deleting a Directory Mount deletes all underlying data too

### ISSUE THREAD

**Issue by snibbo71** [coollabsio/coolify#3795]
### Error Message and Logs

N/A

### Steps to Reproduce

1. Create a directory mount pointing to a folder with existing data on the server
2. Determine that although your Source path is correct, the destination path is incorrect
3. Delete what you think is just a directory mount
4. Read the various 'Are you sure' and 'This is not reversible' messages and do what it says.
5. Not realise that those messages refer to all your data in the Source directory being deleted, not just the mount itself.
6. Restore from backup because it all got deleted :)

### Coolify Version

v4.0.0-beta.356

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Debian 12

### Additional Information

I was expecting it would remove a directory mount, leaving the underlying structure there, especially since the data existed before I mounted it into the container. Even though I read all the 'Are you sure' messages because it was not how I expected it to work (perhaps I know too much Docker?) I got caught out.

The "Are you sure" message isn't clear that it's going to delete all your underlying data off the filesystem - and should probably be an option anyway because if you do like I did and mess up the destination of the mount you only want to delete the mount itself, to 'reposition it' within the container.

**Comment by brandnewx** [comment]
Devs should double check whenever there's a piece of code that deletes a whole directory.

**Comment by peaklabs-dev** [comment]
This is the intended behavior, and you can disable it by unchecking the checkbox that was added in a recent update. Currently, we do not prevent the deletion of any directories, but we will in the future: https://github.com/coollabsio/coolify/discussions/4010.
