### ISSUE TITLE
[Bug]: Server Error when setting a domain already in use on another service

### ISSUE THREAD

**Issue by diogo24m** [coollabsio/coolify#3804]
### Error Message and Logs

500

Something is not okay, are you okay?
There has been an error, we are working on it.

Error: SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "service_applications_fqdn_unique" DETAIL: Key (fqdn)=(https://mc.systems4you.pt) already exists. (Connection: pgsql, SQL: update "service_applications" set "fqdn" = https://mc.systems4you.pt, "updated_at" = 2024-10-08 22:11:35 where "id" = 64)

### Steps to Reproduce

1. Set a domain already in use on another service

### Coolify Version

v4.0.0-beta.355

### Are you using Coolify Cloud?

No (self-hosted)

**Comment by adith-suhas-sv** [comment]
I'm also facing this issue. Even after deleting a service that used the same domain, attempting to use the domain again results in the same error

**Comment by djsisson** [comment]
there is also an issue here, where if you add a FQDN and then delete it, the entry in the table is set as an empty string and not null

therefore next time you try and remove a FQDN you cant as there is already another entry set as an empty string and the constraint on the table is unique values only.

the quick solution is to remove the constraint and then just let the user decide what to do, if you have same entry twice you will just get error in proxy logs, or at least save empty values as null and not an empty string

**Comment by andrasbacsai** [comment]
> there is also an issue here, where if you add a FQDN and then delete it, the entry in the table is set as an empty string and not null
> 
> therefore next time you try and remove a FQDN you cant as there is already another entry set as an empty string and the constraint on the table is unique values only.
> 
> the quick solution is to remove the constraint and then just let the user decide what to do, if you have same entry twice you will just get error in proxy logs, or at least save empty values as null and not an empty string

As I checked, if you delete an application or service, the fqdn is set to null, and not empty. But I will remove the constraint, as it is checked on application level.
