### ISSUE TITLE
[Bug]: Coolify v4.0.0-beta.355 container terminal clipboard issue

### ISSUE THREAD

**Issue by Saboor-Hakimi** [coollabsio/coolify#3807]
### Error Message and Logs

In coolify [v4.0.0-beta.355](https://github.com/coollabsio/coolify/releases/tag/v4.0.0-beta.355) when i try to pase the content of my clipboard in a terminal for the container it pastes it twice!
![image](https://github.com/user-attachments/assets/14e1de45-9c19-4f2f-91fe-2078d895b61d)

### Steps to Reproduce

N/A

### Coolify Version

v4.0.0-beta.355

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24

**Comment by djsisson** [comment]
i can confirm

**Comment by LEstradioto** [comment]
Sorry for that, fixed above! Thanks for checking
