### ISSUE TITLE
Dockerhub Image as a source

### ISSUE THREAD

**Issue by mntolia** [coollabsio/coolify#381]
A dockerhub Image as a source would be awesome. We can install anything from dockerhub then.

Thanks for the application btw :)

**Comment by c43721** [comment]
https://docs.docker.com/docker-hub/webhooks/#create-webhooks

I was looking into this, and I'm really not sure how to go about adding this to coolify. By definition I could just define a URL similar to the github/gitlab integration, have it do the logic for the webhook and post back with whatever status. I'm worried about the security of this (seems like they just make you provide a URL and that's it?)

@andrasbacsai Any thoughts on this? I think it would be really odd on the frontend as you wouldn't (more like shouldn't) define a service, but rather have a webhook define a service for you? Any ideas on how you would want this created?

**Comment by StitiFatah** [comment]
That's possible with Caprover and Dokku, nice option to have to be able to quickly deploy most open source software out there

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
