### ISSUE TITLE
[Bug]: High CPU Usage After Coolify Update - Supabase Instance Issue

### ISSUE THREAD

**Issue by drumst0ck** [coollabsio/coolify#3839]
### Error Message and Logs

After updating Coolify to the latest version, I noticed that my CPU usage skyrocketed to 600%. I spent a lot of time investigating the cause, and I discovered that the issue was related to an instance of Supabase I had running. When I disable the Supabase instance, the CPU usage drops down to 40%.

I primarily use Supabase just for image storage, and I have a lot of data stored there that I can’t afford to lose.

I even tried restoring a backup from Hetzner, but the problem persists. Has anyone else encountered similar issues with Supabase affecting CPU performance, or does anyone have suggestions for optimizing the setup without losing data?
<img width="905" alt="image" src="https://github.com/user-attachments/assets/152a017f-134c-48b4-bf2d-ca4c14644e1a">

### Steps to Reproduce

1.Install supabase service
2.Update coolify
3.
4.

### Coolify Version

v4.0.0-beta.357

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu

**Comment by djsisson** [comment]
check journalctl -u docker.service -S "15 minutes ago"
you might have a corrupt docker log

**Comment by drumst0ck** [comment]
Thank you very much for your response. After reviewing the logs, I have found this log repeated many times. I have tried cleaning the logs without success. The container referenced in the log is the Coolify container.

`Oct 10 14:56:46 ubuntu-8gb-nbg1-3 dockerd[822]: time="2024-10-10T14:56:46.179650262Z" level=error msg="Error streaming logs: invalid character '\\x00' looking for beginning of value" container=4e3ccd9328dc8abc403d329355182dc50b092bb152026f644a6`

**Comment by djsisson** [comment]
cd /var/lib/docker/containers/ && for log in $(grep -lP '\x00' ./*/*json.log*); do sed -i '/\x00/ d' "$log"; done

**Comment by drumst0ck** [comment]
Thank you for your prompt response. I have done what you suggested and executed the command, but after restarting Docker, the CPU goes back to 600% and I still see the same error after running check journalctl -u docker.service -S "15 minutes ago".

**Comment by djsisson** [comment]
@drumst0ck stop docker, and just delete the json log files then

**Comment by drumst0ck** [comment]
Solved, thank you so much! I never would have solved it without your help :)
