### ISSUE TITLE
Service:  coturn

### ISSUE THREAD

**Issue by Yurgeman** [coollabsio/coolify#384]
Coturn - Free open source implementation of TURN and STUN Server

[coturn docker](https://github.com/coturn/coturn/tree/master/docker)

**Comment by compgeniuses** [comment]
@Yurgeman i am curious about this request, for most application making use of cotrun, on the same server, adding coturn is as simple as yum install coturn or apt-get install cotrun. why doe sit require to be added into here: 
Also Kindly Add and Vote for this request here: https://feedback.coolify.io/

**Comment by andrasbacsai** [comment]
Closing this issue as services / features are tracked [here](https://feedback.coolify.io). This request has been added to our feedback tool!
