### ISSUE TITLE
[Bug]: docker-compose.override.yaml are ignored

### ISSUE THREAD

**Issue by chymian** [coollabsio/coolify#3841]
### Error Message and Logs

as the title says, the compose override files, which are more and more common part of configuration, are ignored by coolify.

apps like librechat.ai would need it for further configurations. https://www.librechat.ai/docs/configuration/docker_override.
on the other hand, it would come in very handy to modify git based default docker-compose.yaml files, i.e. to manipulate volumes, etc.
this part I tried to configure, but the new, local dir-based volumes do not get reflected in either the "Storage" tab, nor in docker inspect from the running container.
hence it looks like the override file is getting completly ignored?

coolify 4.0.0-beta.355

### Steps to Reproduce

1. install any git based docker-compose app
2. try to override the values in the original compose files by creating a `docker-compose.override.yaml`
3. nothing happens. override file gets ignored
4. i.e. make volumes persitent
5. start manually from shell does work…

### Example Repository URL

https://www.librechat.ai/docs/configuration/docker_override

### Coolify Version

4.0.0-beta.355

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

debian 12 & 13

**Comment by peaklabs-dev** [comment]
This is more of an new feature request as this has not yet been implemented, so I am moving this to a [GitHub discussion](https://github.com/coollabsio/coolify/discussions/4339).
