### ISSUE TITLE
[Bug]: Backup Tab not working

### ISSUE THREAD

**Issue by lorenzpfei** [coollabsio/coolify#3859]
### Error Message and Logs

![image](https://github.com/user-attachments/assets/bdd6dcfe-6ad7-4a25-8513-ced92bae4763)

After this issue I now get this error: https://github.com/coollabsio/coolify/issues/3691. For me backups still not working. Thanks for fixing! :)

It would be very nice if I cloud close the issue myself if it is resolved because I have opened 3 issues regarding backups now because it haven't worked for me yet. Thanks

### Steps to Reproduce

1. Go to Settings
2. Navigate to Backup

### Coolify Version

v4.0.0-beta.358

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Debian GNU/Linux 12 (bookworm)

**Comment by peaklabs-dev** [comment]
I am unable to reproduce this issue, please upgrade to the latest version of Coolify v4 and try again, and if this is still an issue, feel free to reopen this issue or create a new one.
