### ISSUE TITLE
Supertokens

### ISSUE THREAD

**Issue by andrasbacsai** [coollabsio/coolify#386]
https://supertokens.com/use-oss

**Comment by compgeniuses** [comment]
@andrasbacsai i know its your projects, i am only trying to keep the issues page clean.
  Kindly Add and Vote for this request here: https://feedback.coolify.io/
But that is a cool app, seems there are many cool open source projects out there.

**Comment by andrasbacsai** [comment]
Closing this issue as services / features are tracked [here](https://feedback.coolify.io). This request has been added to our feedback tool!
