### ISSUE TITLE
[Bug]: Error when using SSH key to deploy from Gitea Private Repo

### ISSUE THREAD

**Issue by JojokCreator** [coollabsio/coolify#3866]
### Error Message and Logs

I'm having the an issue when using Gitea and trying to deploy from a private repo. Works fine with Github.

-Generate SSH key pair in Coolify's Key & Token management.
-Copy public key to Gitea repository's Deploy Keys.
-Create new project in Coolify, entering Git repository URL and required details.
-Deploy
-Attempt to clone repository, resulting in SSH authentication failure.

Error message.
```bash
Starting deployment of git@gitea-fhghghf88g.5.223.42.241.sslip.io:fhhg/hhgf.git:main to localhost.
Preparing container with helper image: ghcr.io/coollabsio/coolify-helper:1.0.2.
Oops something is not okay, are you okay? 😢
Permission denied, please try again.
Permission denied, please try again.
git@gitea-fhghghf88g.5.223.42.241.sslip.io:Permission denied (publickey,password).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
Deployment failed. Removing the new version of your application.
```

### Steps to Reproduce

1. Generate SSH key pair in Coolify's Key & Token management.
2. Copy public key to Gitea repository's Deploy Keys.
3. Create new project in Coolify, entering Git repository URL and required details.
4. Deploy
5. Attempt to clone repository, resulting in SSH authentication failure.

### Coolify Version

v4.0.0-beta.355

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Debian GNU/Linux 12 (bookworm)

**Comment by djsisson** [comment]
that looks like it failed to pull teh helper from ghcr
can u first try docker logout ghcr.io

**Comment by JojokCreator** [comment]
Thanks, I think i just fixed it. The port Gitea was using was missing from the ssh url.

What I did.

Under "Service Stack," click "Edit Compose File" and see what port Gitea is listening on. Mine is 22222.

You'll need to add that port to your Gitea SSH URL. Something like this:

`git@gitea-gccgasdds4sdsd.3.444.232.32.sslip.io:22222/user/repo`
