### ISSUE TITLE
[Bug]: Can not create a private gitlab resource 

### ISSUE THREAD

**Issue by plosson** [coollabsio/coolify#3884]
### Error Message and Logs

I can not deploy any public or private Git repositories through a Deploy Key.

### Steps to Reproduce

1. Create a key in Keys & Tokens 
2. Create a project, add a resource of type : "Private Repository with deploy key" 
3. Keys are listed, click on it .. 
4. Nothing happens .. 

It's not possible to go to the next screen 

### Coolify Version

v4.0.0-beta.359

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04.1 LTS

**Comment by andrasbacsai** [comment]
Please update to v360 it is fixed there.
