### ISSUE TITLE
[Bug]: Caddy handle_path label doesn't strip the path

### ISSUE THREAD

**Issue by impromp02** [coollabsio/coolify#3895]
### Error Message and Logs

According to the caddy documentation the `handle_path` directive should strip the path and `handle` directive should keep the path when reverse proxying request to containers but in my case it's working the reverse. I replaced the handle_path  labels with handle labels and it working fine. Isn't is opposite of what the Caddy documentation says? Or am I missing something. 

### Background
I've backend application deployed at the `/api` path as in `www.example.com/api`. I'm using the original container labels. Here is the snippet:

```
caddy_0.encode=zstd gzip  
caddy_0.handle_path.0_reverse_proxy={{upstreams 3000}}   
caddy_0.handle_path=/api/*  
caddy_0.header=-Server  
```

I already have /api path prefixed on my backend. Since the the path from proxy was not getting stripped off I had to use /api/api/[controller] to get to the APIs. 

### Steps to Reproduce

1. I'm using spring boot deployed at my domain at /api path
2. I'm leaving the container labels untouched

### Coolify Version

v4.0.0-beta.355

### Are you using Coolify Cloud?

No (self-hosted)

**Comment by peaklabs-dev** [comment]
This should be fixed in the next update as soon as it is released, please retest this.
