### ISSUE TITLE
[Bug]: ERR_TOO_MANY_REDIRECTS using Custom HTTPS Domain with WordPress Service

### ISSUE THREAD

**Issue by MikeWhalenIII** [coollabsio/coolify#3903]
### Error Message and Logs

I created a fresh service using the Wordpress Without Database template and I assigned a custom domain name to the service using HTTPS.

After configuring the fresh install and connecting it to my MySQL database, I updated the **WordPress Address (URL)** under **Settings -> General** from HTTP to HTTPS. When you attempt to access the wp-admin page, you are presented with an **ERR_TOO_MANY_REDIRECTS** error. 

The rest of the site works except for the admin panel, which is odd. I am using Cloudflare and set the encryption mode to Full (strict) with no luck.

### Steps to Reproduce

1. Create a new WordPress service using a custom HTTPS domain name.
2. Once the site comes online and you log into the wp-admin portal, the WordPress Address (URL) under Settings > General is set to use the HTTP custom domain and not HTTPS.	
3. Update the WordPress Address (URL)	 to the HTTPS address and click save.
4. The page will reload, and ERR_TOO_MANY_REDIRECTS will show.
WordPress

### Coolify Version

v4.0.0-beta.360

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04

**Comment by MikeWhalenIII** [comment]
I believe I found a solution to this issue by adding the following to the top of my `wp-config.php` file.

```/**
 * Handle SSL reverse proxy
 */
if ($_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https')
    $_SERVER['HTTPS']='on';

if (isset($_SERVER['HTTP_X_FORWARDED_HOST'])) {
    $_SERVER['HTTP_HOST'] = $_SERVER['HTTP_X_FORWARDED_HOST'];
}
```

_Source: https://github.com/docker-library/wordpress/issues/412#issuecomment-623530572_

**Comment by peaklabs-dev** [comment]
You are most likely running into this issue: https://coolify.io/docs/knowledge-base/faq#too-many-redirections

**Comment by twhite96** [comment]
> You are most likely running into this issue: https://coolify.io/docs/knowledge-base/faq#too-many-redirections

I have it set to Full, same thing is happening. The docs aren't very clear.

**Comment by MikeWhalenIII** [comment]
> > You are most likely running into this issue: https://coolify.io/docs/knowledge-base/faq#too-many-redirections
> 
> I have it set to Full, same thing is happening. The docs aren't very clear.

Yeah, that did not work for me either. The only thing that worked was the solution that I posted above.

https://github.com/coollabsio/coolify/issues/3903#issuecomment-2408801588
