### ISSUE TITLE
[Bug]: Getting Welcome to nginx! on deployment

### ISSUE THREAD

**Issue by AlejandroSanchez90** [coollabsio/coolify#3904]
### Error Message and Logs

Im trying to deploy a nextjs app, first time it worked good, i changed some names here and there and suddenly my deployment start showing Welcome to nginx! home screen, after a long trial and error i deleted this deployment to deploy a new one, but this one still shows the Welcome to nginx!

this is the setting of the deployment
![image](https://github.com/user-attachments/assets/af905ed6-bfd5-4f66-adaf-ed83f68d197f)

### Steps to Reproduce

1. load a next repo using github app
2. fill env variables and deploy

### Coolify Version

v4.0.0-beta.360

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu

**Comment by AlejandroSanchez90** [comment]
if i deploy without changinganything else but the domain name and build/start commands, then it works, so the bug should be around changing name or toggling static site option, this is the config that works
![image](https://github.com/user-attachments/assets/652581c7-2dac-4973-b82b-f1d92a28e106)

**Comment by djsisson** [comment]
in your first image you had picked static site

**Comment by AlejandroSanchez90** [comment]
In the docs it say to pick static site for a nextjs app

**Comment by djsisson** [comment]
@AlejandroSanchez90 if it has no ssr, you can use static, but you would need to set publish directory to /out not /

**Comment by AlejandroSanchez90** [comment]
Got it thanks!
