### ISSUE TITLE
[Bug]: Custom FluentBit Configuration input required even when not enable 

### ISSUE THREAD

**Issue by Nuxnuxx** [coollabsio/coolify#3909]
### Error Message and Logs

![image](https://github.com/user-attachments/assets/265fec3a-0b12-4dfc-a71b-89fe78f4017e)
as you can see i use axiom but i still need to make Custom FluentBitConfiguration not empty event if i have not enabled it
if not i can't save
### Steps to Reproduce

1. 
2.
3.
4.

### Coolify Version

v4.0.0-beta.360

### Are you using Coolify Cloud?

No (self-hosted)

**Comment by peaklabs-dev** [comment]
This issue should be resolved in the latest version. If you're still experiencing this issue, please reopen or create a new issue with updated details.
