### ISSUE TITLE
[Bug]: TOO MANY REDIRECTS after updating Coolify (Instance domain)

### ISSUE THREAD

**Issue by leedia-tech** [coollabsio/coolify#3911]
### Error Message and Logs

Hi,

I recently updated my Coolify instance to the latest available version. However, immediately after the update, the domain https://coolify.domain.com stopped working and started showing the error “TOO MANY REDIRECTS”.

I’m using Cloudflare, and the SSL/TLS settings are set to Full. This configuration was working perfectly before the update, but now it’s causing issues after the upgrade.

Any suggestions on what might be causing this or how to fix it would be greatly appreciated.

Thanks!

### Steps to Reproduce

-

### Coolify Version

v4.0.0-beta.360

### Are you using Coolify Cloud?

No (self-hosted)

**Comment by Code-DJ** [comment]
You need to set it to Full (Strict) not Full if you have SSL between Cloudflare and your Coolify server.

**Comment by mrcloudbook** [comment]
Open Cloudflare Dashboard

- Select Your Domain
- On Left side Panel --> Click on SSL/TLS --> Opens Overview
- On SSL/TLS encryption --> configure
- Click Radio Box to Full ( Strict ) --> Save 
- Redeploy

**Comment by leedia-tech** [comment]
Hi, thank you all, but that wasn’t the issue. Full (Strict) is not necessary, only Full is. The only difference between Full and Full Strict is that the origin certificate validity is checked.

The issue appeared right after the update and disappeared on its own after a few hours. I have no idea what could have caused it. I didn’t change anything, neither the Coolify configuration nor Cloudflare.
