### ISSUE TITLE
[Bug]: Mailpit template should expose smtp port

### ISSUE THREAD

**Issue by affanshahid** [coollabsio/coolify#3936]
### Error Message and Logs

The mailpit template exports the web dashboard port but not the actual smtp port (1025). i.e It's missing a:
```yml
    ports:
      - "1025:1025"
```

### Steps to Reproduce

1. Add mailpit as a service
2. Try to connect to it using telnet

### Coolify Version

v4.0.0-beta.360

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04.1 LTS

**Comment by faqndo97** [comment]
I deployed the service yesterday, and I can confirm this is a problem.
