### ISSUE TITLE
[Bug]: /bin/bash: -c: option requires an argument (turborepo with nixpack)

### ISSUE THREAD

**Issue by tlenclos** [coollabsio/coolify#3939]
### Error Message and Logs

/bin/bash: -c: option requires an argument
/bin/bash: -c: option requires an argument
/bin/bash: -c: option requires an argument

### Steps to Reproduce

1. We plugged our turborepo with a next.js app
2. build with Nixpack is successfull
3. app restart in loop with these logs

### Example Repository URL

Working on it

### Coolify Version

v4.0.0-beta.360

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Debian GNU/Linux 10 (buster)

### Additional Information

I'll try to setup an example to make this sure this is not related to our setup.
It seems people were having the same issue but it got closed https://github.com/coollabsio/coolify/issues/2579.

Thanks a lot for this amazing piece of software and building in public 🙏

**Comment by peaklabs-dev** [comment]
Can you please provide us with a sample repository so that we can resolve this issue.

**Comment by isaackoz** [comment]
`/bin/bash: -c: option requires an argument` is caused if you have your setup configured incorrectly. By default Nixpacks will try to automatically decide what to do. In your case, [Nixpacks will do the following](https://nixpacks.com/docs/providers/node#build). You can either configure your environment by setting `NIXPACKS_TURBO_APP_NAME `, or you can use your own install/build/start commands in Coolify.  For example, you could do:

- Install Command: `npm install`
- Build Command: `npx turbo build --filter=frontend`
- Start Command: `npx turbo start:prod --filter=frontend`

which would fix your problem (assuming your turbo config is setup correctly).



I ran into a similar issue when deploying a SvelteKit application. To fix it, I used the following commands:
- Install Command: `npm install`
- Build Command: `npm run build`
- Start Command: `node -r dotenv/config build`

(don't forget to use adapter-node)
```js
import adapter from '@sveltejs/adapter-node';
import { vitePreprocess } from '@sveltejs/vite-plugin-svelte';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	preprocess: vitePreprocess(),

	kit: {
		adapter: adapter()
	}
};

export default config;
```
