### ISSUE TITLE
[Bug]: Supabase deployment failing through Coolify (Analytics Container keeps crashing)

### ISSUE THREAD

**Issue by mystycs** [coollabsio/coolify#3992]
### Error Message and Logs

Just installed a fresh version of coolify.

I am going through Coolify to setup supabase. I deployed it but it seems that analytics keeps crashing. I am on the latest version of coolify (
v4.0.0-beta.360) just installed yesterday. It just never boots up the analytics container and fails.

I saw there was a supabase/coolify issue recently with postgres_hostname but that seems resolved in this issue. 

It seems like the analytics container just keeps trying to start but keeps failing over and over. So i can never actually access or start supabase.

Deploy Log for Coolifty/Supabase

` 5046425d6ca7 Extracting [==================================================>]  982.8kB/982.8kB
 5046425d6ca7 Extracting [==================================================>]  982.8kB/982.8kB
 5046425d6ca7 Pull complete 
 0ba94043a671 Extracting [==================================================>]  4.865kB/4.865kB
 0ba94043a671 Extracting [==================================================>]  4.865kB/4.865kB
 0ba94043a671 Pull complete 
 supabase-db Pulled 
Starting containers.
 Volume "lw8skcoskc8oosk0w80ww8s4_supabase-db-data"  Creating
 Volume "lw8skcoskc8oosk0w80ww8s4_supabase-db-data"  Created
 Volume "lw8skcoskc8oosk0w80ww8s4_supabase-db-config"  Creating
 Volume "lw8skcoskc8oosk0w80ww8s4_supabase-db-config"  Created
 Container imgproxy-lw8skcoskc8oosk0w80ww8s4  Creating
 Container supabase-vector-lw8skcoskc8oosk0w80ww8s4  Creating
 Container supabase-minio-lw8skcoskc8oosk0w80ww8s4  Creating
 Container supabase-minio-lw8skcoskc8oosk0w80ww8s4  Created
 Container minio-createbucket-lw8skcoskc8oosk0w80ww8s4  Creating
 Container supabase-vector-lw8skcoskc8oosk0w80ww8s4  Created
 Container supabase-db-lw8skcoskc8oosk0w80ww8s4  Creating
 Container imgproxy-lw8skcoskc8oosk0w80ww8s4  Created
 Container minio-createbucket-lw8skcoskc8oosk0w80ww8s4  Created
 Container supabase-db-lw8skcoskc8oosk0w80ww8s4  Created
 Container supabase-analytics-lw8skcoskc8oosk0w80ww8s4  Creating
 Container supabase-analytics-lw8skcoskc8oosk0w80ww8s4  Created
 Container supabase-kong-lw8skcoskc8oosk0w80ww8s4  Creating
 Container realtime-dev-lw8skcoskc8oosk0w80ww8s4  Creating
 Container supabase-edge-functions-lw8skcoskc8oosk0w80ww8s4  Creating
 Container supabase-studio-lw8skcoskc8oosk0w80ww8s4  Creating
 Container supabase-auth-lw8skcoskc8oosk0w80ww8s4  Creating
 Container supabase-rest-lw8skcoskc8oosk0w80ww8s4  Creating
 Container supabase-meta-lw8skcoskc8oosk0w80ww8s4  Creating
 Container supabase-edge-functions-lw8skcoskc8oosk0w80ww8s4  Created
 Container supabase-kong-lw8skcoskc8oosk0w80ww8s4  Created
 Container realtime-dev-lw8skcoskc8oosk0w80ww8s4  Created
 Container supabase-studio-lw8skcoskc8oosk0w80ww8s4  Created
 Container supabase-auth-lw8skcoskc8oosk0w80ww8s4  Created
 Container supabase-rest-lw8skcoskc8oosk0w80ww8s4  Created
 Container supabase-storage-lw8skcoskc8oosk0w80ww8s4  Creating
 Container supabase-meta-lw8skcoskc8oosk0w80ww8s4  Created
 Container supabase-storage-lw8skcoskc8oosk0w80ww8s4  Created
 Container supabase-minio-lw8skcoskc8oosk0w80ww8s4  Starting
 Container imgproxy-lw8skcoskc8oosk0w80ww8s4  Starting
 Container supabase-vector-lw8skcoskc8oosk0w80ww8s4  Starting
 Container supabase-vector-lw8skcoskc8oosk0w80ww8s4  Started
 Container supabase-vector-lw8skcoskc8oosk0w80ww8s4  Waiting
 Container supabase-minio-lw8skcoskc8oosk0w80ww8s4  Started
 Container supabase-minio-lw8skcoskc8oosk0w80ww8s4  Waiting
 Container imgproxy-lw8skcoskc8oosk0w80ww8s4  Started
 Container supabase-vector-lw8skcoskc8oosk0w80ww8s4  Healthy
 Container supabase-db-lw8skcoskc8oosk0w80ww8s4  Starting
 Container supabase-db-lw8skcoskc8oosk0w80ww8s4  Started
 Container supabase-db-lw8skcoskc8oosk0w80ww8s4  Waiting
 Container supabase-minio-lw8skcoskc8oosk0w80ww8s4  Healthy
 Container minio-createbucket-lw8skcoskc8oosk0w80ww8s4  Starting
 Container minio-createbucket-lw8skcoskc8oosk0w80ww8s4  Started
 Container supabase-db-lw8skcoskc8oosk0w80ww8s4  Healthy
 Container supabase-analytics-lw8skcoskc8oosk0w80ww8s4  Starting
 Container supabase-analytics-lw8skcoskc8oosk0w80ww8s4  Started
 Container supabase-db-lw8skcoskc8oosk0w80ww8s4  Waiting
 Container supabase-analytics-lw8skcoskc8oosk0w80ww8s4  Waiting
 Container supabase-analytics-lw8skcoskc8oosk0w80ww8s4  Waiting
 Container supabase-analytics-lw8skcoskc8oosk0w80ww8s4  Waiting
 Container supabase-db-lw8skcoskc8oosk0w80ww8s4  Waiting
 Container supabase-analytics-lw8skcoskc8oosk0w80ww8s4  Waiting
 Container supabase-analytics-lw8skcoskc8oosk0w80ww8s4  Waiting
 Container supabase-db-lw8skcoskc8oosk0w80ww8s4  Waiting
 Container supabase-db-lw8skcoskc8oosk0w80ww8s4  Waiting
 Container supabase-analytics-lw8skcoskc8oosk0w80ww8s4  Waiting
 Container supabase-analytics-lw8skcoskc8oosk0w80ww8s4  Waiting
 Container supabase-db-lw8skcoskc8oosk0w80ww8s4  Healthy
 Container supabase-db-lw8skcoskc8oosk0w80ww8s4  Healthy
 Container supabase-db-lw8skcoskc8oosk0w80ww8s4  Healthy
 Container supabase-db-lw8skcoskc8oosk0w80ww8s4  Healthy
 Container supabase-analytics-lw8skcoskc8oosk0w80ww8s4  Error
 Container supabase-analytics-lw8skcoskc8oosk0w80ww8s4  Error
 Container supabase-analytics-lw8skcoskc8oosk0w80ww8s4  Error
 Container supabase-analytics-lw8skcoskc8oosk0w80ww8s4  Error
 Container supabase-analytics-lw8skcoskc8oosk0w80ww8s4  Error
 Container supabase-analytics-lw8skcoskc8oosk0w80ww8s4  Error
 Container supabase-analytics-lw8skcoskc8oosk0w80ww8s4  Error
dependency failed to start: container supabase-analytics-lw8skcoskc8oosk0w80ww8s4 is unhealthy`

Supabase Analytics Logs

`2024-10-23T19:40:26.638385959Z LOGFLARE_NODE_HOST is: 127.0.0.1
2024-10-23T19:40:29.472701178Z Killed
2024-10-23T19:40:34.743637852Z Killed
2024-10-23T19:40:36.459308043Z LOGFLARE_NODE_HOST is: 127.0.0.1
2024-10-23T19:40:39.029837414Z Killed
2024-10-23T19:40:42.039039219Z Killed
2024-10-23T19:40:44.046144495Z LOGFLARE_NODE_HOST is: 127.0.0.1
2024-10-23T19:40:46.541428206Z Killed
2024-10-23T19:40:49.330150027Z Killed
2024-10-23T19:40:50.929840914Z LOGFLARE_NODE_HOST is: 127.0.0.1
2024-10-23T19:40:54.210337956Z Killed
2024-10-23T19:41:01.140608462Z Killed
2024-10-23T19:41:03.021179651Z LOGFLARE_NODE_HOST is: 127.0.0.1
2024-10-23T19:41:05.740813883Z Killed
2024-10-23T19:41:09.338323946Z Killed
2024-10-23T19:41:10.548374742Z LOGFLARE_NODE_HOST is: 127.0.0.1
2024-10-23T19:41:13.095717906Z Killed
2024-10-23T19:41:16.121446298Z Killed
2024-10-23T19:41:17.558302918Z LOGFLARE_NODE_HOST is: 127.0.0.1
2024-10-23T19:41:20.025675061Z Killed
2024-10-23T19:41:22.784183774Z Killed
2024-10-23T19:41:24.435617403Z LOGFLARE_NODE_HOST is: 127.0.0.1
2024-10-23T19:41:29.247149443Z Killed
2024-10-23T19:41:33.101973725Z Killed
2024-10-23T19:41:35.720481149Z LOGFLARE_NODE_HOST is: 127.0.0.1
2024-10-23T19:41:38.102131388Z Killed
2024-10-23T19:41:40.876948972Z Killed`

![Image](https://github.com/user-attachments/assets/22fa7d13-9510-4bb5-8666-eae46445f02c)

### Steps to Reproduce

1. Go to add new resource for project
2. Select Supabase in bottom service list
3. Press Deploy
4. Fail

### Coolify Version

v4.0.0-beta.360

### Are you using Coolify Cloud?

Yes (Coolify Cloud)

### Operating System and Version (self-hosted)

Ubuntu 24.10 x64

**Comment by fubits1** [comment]
@mystycs Supabase added a new database `_supabase` for analytics which broke existing deployments.

To fix this you need to:

Option A:

- temporarily change the compose file to an older working version ([this one from August worked for me](https://github.com/coollabsio/coolify/blob/991c215a10b8e06ba80cbe4e0cd1d77bc438aee0/templates/compose/supabase.yaml)) and re-deploy
- then create the new, additional db `_supabase`and create two schema ([as suggested here](https://github.com/supabase/cli/issues/2737#issuecomment-2401514097))

Then you can re-apply the current template / compose file and redeploy and all should be fine again.

Option B:

- if you have made your Postgres publicly available, you can connect to the DB directly via connection string and create the DB and the schema without rolling back to an older template / compose file.

FYI @peaklabs-dev - this might apply to other users with "legacy" Supabase deployments (before the DB was changed to `_supabase` so maybe this comment is helpful as a reference

**Comment by peaklabs-dev** [comment]
Please use the guide in the comment above or just use the new updated template and the analytics should work.
