### ISSUE TITLE
GitHub app name should be dashified

### ISSUE THREAD

**Issue by lgastler** [coollabsio/coolify#4]
I just went through the complete installation process it all worked great. 👍🏽

I only encountered one tiny error, when naming my GitHub app I gave it a name with a space (f.e. app name). GitHub dashifies the app name, that's why the link to Configure on GitHub on the New Application page results in a 404.

Can be easily solved by simply dashifying the app name.

Here's a simple example inside the `Configuration.svelte`component.
[Fork example](https://github.com/lgastler/coolify/blob/d9dd509fa0f00e4cd52a610504617673064ca0a4/src/components/Application/Configuration/Configuration.svelte)

"github.com/apps/app name/installations/new" -> "github.com/apps/app-name/installations/new"

Greetings from Germany 👋
Lennart

**Comment by andrasbacsai** [comment]
Wow, thanks! Nice catch!

**Comment by andrasbacsai** [comment]
I tweaked it a bit because I do not need to convert camelCase to camel-case. Thanks for the report again.

**Comment by lgastler** [comment]
Great, just tried the automatic update worked flawlessly. 👍🏽

What is the best way to send you further feedback? Open issues, Twitter, etc. ?

**Comment by andrasbacsai** [comment]
Atm, open issues would be the best.
