### ISSUE TITLE
Add jit mode to tailwind

### ISSUE THREAD

**Issue by potros** [coollabsio/coolify#40]
it will be a very good improvement if you added tailwind jit mode

docs link => https://tailwindcss.com/docs/just-in-time-mode

it will save some space and the ui will be faster and smaller

**Comment by andrasbacsai** [comment]
Yeah, I would like to change to jit in the near future. Thanks for the suggestion!

**Comment by andrasbacsai** [comment]
The near future is here after I merge #44.

**Comment by andrasbacsai** [comment]
I've merged it, so it's based on Tailwind JIT! 👍🏻  Thanks for the suggestion!
