### ISSUE TITLE
[Bug]: Issues with Server-Sent Events (SSE) and WebSocket Connections on Coolify with Traefik

### ISSUE THREAD

**Issue by philippilievski** [coollabsio/coolify#4002]
### Error Message and Logs

I'm experiencing persistent issues with setting up Server-Sent Events (SSE) and WebSocket connections in my application, which is deployed using Coolify. Here's an overview of the problem:

My application uses Vue 3 on the frontend and NestJS on the backend.
Initially, I was using WebSockets for real-time communication but ran into issues with production deployment (Coolify + Traefik).
I switched to SSE as an alternative for real-time updates, but I'm encountering similar issues with SSE on Coolify.

WebSocket Issues:

In production (Coolify + Traefik), WebSockets do not work as expected.
Locally, using Docker Compose without Nginx, WebSockets work fine.
I believe the issue might be related to Traefik's routing or configuration, as I see errors in Traefik logs indicating it's unable to find the frontend container’s IP address.
SSE Issues:

After switching from WebSockets to SSE, I'm still facing problems.
In production, SSE connections seem unreliable or break frequently. Logs show that Traefik might be interfering with the proper handling of SSE connections.
On top of that, SSE works fine in my local Docker Compose environment, which suggests that something in the Coolify setup (likely Traefik) is causing the problem.
Coolify Setup:

I'm using Coolify's auto-generated Docker Compose setup with Traefik for routing.
Ports (6001, 3001, 8000, 443, and 22) are open, and I've confirmed that Soketi runs on port 6001.
Traefik logs show the error unable to find IP address for frontend service, and I suspect this is the cause of the issues.

### Steps to Reproduce

1. Deploy an application with WebSocket or SSE connections using Coolify with Traefik as the proxy.
2. Observe the behavior: WebSockets/SSE fail or are unreliable in production, while they work perfectly in a local Docker Compose environment.

### Coolify Version

v4.0.0-beta.360

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04.1 LTS

**Comment by Fronix** [comment]
This is a traefik issue which has to do with headers, not sure if this is something coolify should care about since you can modify traefik settings yourself.

**Comment by djsisson** [comment]
@philippilievski are the 2 containers in the same docker network, how and where are you connecting from

**Comment by philippilievski** [comment]
> This is a traefik issue which has to do with headers, not sure if this is something coolify should care about since you can modify traefik settings yourself.

Hey, thanks for the heads up! I’ve been thinking the issue could be related to Traefik headers, but I’m not entirely sure what exactly I need to tweak. I’ve tried modifying a few Traefik settings without much luck so far. To be honest i thought this should work with coolify out of the box!

If you have any specific advice on which headers I should look into or change to get SSE or WebSockets working, I’d really appreciate it.

**Comment by philippilievski** [comment]
> [@philippilievski](https://github.com/philippilievski) are the 2 containers in the same docker network, how and where are you connecting from

Yes, both containers are on the same Docker network. I’m connecting from my frontend to the backend via API and WebSocket/SSE endpoints.

**Comment by djsisson** [comment]
@philippilievski OK and what url are you using

It needs to be wss://backend-api:port

Where backend-api is just the service name
There is no need to even go through traefik a direct connection is best here.

**Comment by philippilievski** [comment]
> [@philippilievski](https://github.com/philippilievski) OK and what url are you using
> 
> It needs to be ws://backend-api:port
> 
> Where backend-api is just the service name and port is the port inside the container.
> 
> There is no need to even go through traefik a direct connection is best here.

Thank you for your response.
I actually tried using the service name (ws://backend:3001) as you suggested, but that approach works only for internal communication within the Docker network (like between containers). The issue I’m running into is with client-side WebSocket connections from the browser. Since the frontend is served over HTTPS, the browser enforces secure connections, so I have to use wss:// for WebSockets and https:// for API requests. This requires routing through Traefik to handle the SSL termination in production.

Do you have any recommendations for making this setup work smoothly with Traefik? Or any ideas for SSL handling that could help avoid these mixed content issues?

Sorry I am quite lost here...

**Comment by djsisson** [comment]
@philippilievski if you require both methods, then you need to use 2 different urls, 1 for internal and 1 for public
The internal being just the container name, and public being the FQDN

traefik handles websockets without needing to change anything, what error are you getting client side

**Comment by SaeedSheikhi** [comment]
Hello,

I resolved my issue by turning OFF Gzip compression in the advanced settings.

Hope this helps!

**Comment by philippilievski** [comment]
> Hello,
> 
> I resolved my issue by turning OFF Gzip compression in the advanced settings.
> 
> Hope this helps!
Thank you for your help. Will try it asap.
How did you come to this conclusion?

**Comment by SaeedSheikhi** [comment]
> > Hello,
> > I resolved my issue by turning OFF Gzip compression in the advanced settings.
> > Hope this helps!
> 
> Thank you for your help. Will try it asap. How did you come to this conclusion?

While searching on the Cloudflare forums, discovered that the issue might be related to the proxy configuration, possibly NGINX or Traefik.

**Comment by philippilievski** [comment]
This actually solved the issue.
I will close this thread now :)

**Comment by trungtin** [comment]
where is the options for turning off gzip compression? I can't find it in the advanced settings? setting service label with
```yaml
labels:
  - "traefik.http.middlewares.gzip.compress.enabled=false"
```
didn't resolve the issue

**Comment by eduwass** [comment]
FWIW, I just found this issue and wanted to chime in.

This happened to me recently, and I think it's related: https://github.com/adonisjs/transmit/issues/31

Romain's proposed solution was this:

> update your Traefik configuration to use the [excludedcontenttypes setting](https://doc.traefik.io/traefik/middlewares/http/compress/#excludedcontenttypes) so that `text/event-stream` is not compressed

So effectively you only turn off gzip for streams, which should be better than turning it off entirely.
