### ISSUE TITLE
[Bug]: Supabase /project/default/api Error on load

### ISSUE THREAD

**Issue by LazerJesus** [coollabsio/coolify#4003]
### Error Message and Logs

When visiting the api page, the UI gets stuck on the Supabase loading animation.

The network shows a failed request:

GET /api/projects/default/api/rest
Response Code 500 Internal Server Error  
Respose Body {"error":{}}

### Steps to Reproduce

1. Fresh Install of Coolify
2. Fresh install of Supabase
3. visit the supabase / api page
4. wait.

### Coolify Version

v4.0.0-beta.360

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04

**Comment by djsisson** [comment]
@LazerJesus what is value of supabase_url env in studio section

change it to ```http://supabase-kong:8000``` if it isnt that already

**Comment by LazerJesus** [comment]
@djsisson 
i am not totally clear what you mean with >studio section<

In the coolify UI > Projects > supabase > Environment Variables - is no variable 'supabase_url' 
only 'API_EXTERNAL_URL' which is set to 'http://supabase-kong:8000' 

on the vpn that runs the supabase service > /data/coolify/services/:id/docker-compose.yml > supabase-studio > environment - has supabase_url, which is set to the real url. supabase.mydomain.com in this case.
      SUPABASE_URL: '${SERVICE_FQDN_SUPABASEKONG}'
      SUPABASE_PUBLIC_URL: '${SERVICE_FQDN_SUPABASEKONG}'

**Comment by djsisson** [comment]
@LazerJesus change only this one in the compose:
SUPABASE_URL: '${SERVICE_FQDN_SUPABASEKONG}'

on project page - edit compose then change to what i posted above
```http://supabase-kong:8000```
save and redeploy

note: this template is also out of date there is a newer one waiting to be merged

**Comment by LazerJesus** [comment]
@djsisson 
i have question in this regard, which i posted alread here: https://github.com/coollabsio/coolify/issues/3297#issuecomment-2434873455


> when does coolify write these docker-compose files? are they written once when i instantiate the service from the coolify UI, or are they written at any other point? how reliable a fix is it to go into the filesystem and manually overwrite config managed by coolify? are there hidden caches or something?

**Comment by peaklabs-dev** [comment]
If you want to test it out now you can add a new compose based deployment with the following compose file: https://github.com/coollabsio/coolify/blob/next/templates/compose/supabase.yaml and then I think this issue should be fixed.
