### ISSUE TITLE
[Bug]: Plane Service not working

### ISSUE THREAD

**Issue by venkadeshshiva** [coollabsio/coolify#4008]
### Error Message and Logs

![Image](https://github.com/user-attachments/assets/45674136-baa9-4ed2-a864-86ecfc85e888)

Plane service not working. proxy showing some error. 

### Steps to Reproduce

1. Install Plane service 
2. check the "Proxy" container log. 
3.
4.

### Coolify Version

v4.0.0-beta.360

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu Linux 24.04.1

**Comment by djsisson** [comment]
@venkadeshshiva there is a new template waiting to be merged that fixes this

**Comment by luckydonald** [comment]
More specifically: #3878
