### ISSUE TITLE
[Bug]: Restart causes a redeploy

### ISSUE THREAD

**Issue by Alt-iOS** [coollabsio/coolify#4018]
### Error Message and Logs

Theres no error message as such

### Steps to Reproduce

1. Create a github app
2. Deploy a github app with dockerfile
3. Restart app
4. Get a redeploy instead of a restart

### Coolify Version

v4.0.0-beta.360

### Are you using Coolify Cloud?

No (self-hosted)

**Comment by Alt-iOS** [comment]
I realize, modifying the labels, is a modification of the docker container image, thus it decides to rebuild

**Comment by theDanielJLewis** [comment]
This frustrates me, too. If I click "restart," all I want it to do is restart—profound, I know.

This could be because of a locked up process, or maybe changing an environment variable (that doesn't require a rebuild).
