### ISSUE TITLE
[Bug]: Cannot add new environment variables to One click deployed Directus service

### ISSUE THREAD

**Issue by lttr** [coollabsio/coolify#4024]
### Error Message and Logs

Any environment variables added to a Directus service, that was installed using one-click deploy, does not seem to be applied. I'm restarting the service using the Restart button after any change on Environment variables page.

### Steps to Reproduce

1. New project
2. New resource
3. Pick Directus (the simple one, without Postgres)
4. Start the service
5. Directus dashboard is available
6. Add environment variable on the service configuration page
7. Restart the service
8. The environment variable is not present (can't see it by using the `env` command in the Terminal tab, can't see the effect the environment variable was supposed to do in the Directus service)

### Coolify Version

v4.0.0-beta.360 

### Are you using Coolify Cloud?

Yes (Coolify Cloud)

### Additional Information

I wanted to configure Content security policy for Directus service. First I thought I have the env var in wrong format, however it seems I'm not the only one, who has this problem according to this Github issue: https://github.com/directus/directus/issues/21548

**Comment by djsisson** [comment]
@lttr you need to add the env var to the compose file in the environment section. Adding it just to the env tab doesn't auto make it available within any containers you have to be explicit and say what each service needs.

**Comment by lttr** [comment]
@djsisson Oh thanks, you have saved my day!

I have completely missed the Edit Compose File button. Now it works for me, so I'm closing this issue.

Here is a specific example for anyone who might find this:

I have now an environment variable like this on the Environment Variables screen:

Name: MY_VARIABLE
Value: example.com

And I have added a line under `environment` key in the Docker compose file like this:

```
     - MY_VARIABLE=$MY_VARIABLE
```

And after restarting the service, it works as expected.
