### ISSUE TITLE
[Bug]: Cloudflare tunnels option unavailable on localhost

### ISSUE THREAD

**Issue by brrock** [coollabsio/coolify#4028]
### Error Message and Logs

None

### Steps to Reproduce

1. View server options on localhost server
2.
3.
4.

### Coolify Version

V4.0.0-beta-360

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Debian bookworm 12.7

### Additional Information

I don’t know if this is a bug, I run coolify on my RPI 4 and have local ssh access. I want to have ability to generate a domain powered by cloudflare tunnels automatically. I can’t do port forwarding.

**Comment by djsisson** [comment]
@brrock not sure what your issue is here:

create cf tunnel
point your domains/wildcard to the tunnel

in coolify
add cf tunnel template and add cf token to env variables
set wildcard domain to be your apex domain

**Comment by brrock** [comment]
Could this be added to docs?

**Comment by brrock** [comment]
And does it work when I click generate domain in coolify

**Comment by djsisson** [comment]
@brrock if you have added a wildcard tunnel + dns entry, as well as set your wildcard domain in coolify, then yes any url you generate would just automatically work

**Comment by brrock** [comment]
Thanks so much appreciate
