### ISSUE TITLE
[Bug]: DNS probe failed

### ISSUE THREAD

**Issue by brrock** [coollabsio/coolify#4033]
### Error Message and Logs

DNS probe failed - brave browser

### Steps to Reproduce

1. Make a wildcard cloudflare tunnels
2. Set the wildcard and main domain in settings 
3.
4.

### Coolify Version

Latest 

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Debian 12.7

### Additional Information

This is on a rpi 4, cloudflared integration and  cli

**Comment by peaklabs-dev** [comment]
This is most likely an issue with DNS caching or DNS records, or configuration issues on your end. If this is still a problem, or if it happens again, feel free to use the reopen or create a new issue.
