### ISSUE TITLE
[Bug]: InvoiceNinja login issues

### ISSUE THREAD

**Issue by candlep** [coollabsio/coolify#4044]
### Error Message and Logs

The invoice ninja resource doesn't work when you try to login.

### Steps to Reproduce

1. Create a new invoice ninja resource
2. change the email and password
3. restart the service
4. try to login with new credentials
5.  "These credentials do not match our records" error

### Coolify Version

v4.0.0-beta.360

### Are you using Coolify Cloud?

No (self-hosted)

**Comment by peaklabs-dev** [comment]
This issue has been fixed in the latest version.
