### ISSUE TITLE
Deployment image and Base image not working for NuxtJS applications. Only work for Nodejs

### ISSUE THREAD

**Issue by chz** [coollabsio/coolify#405]
Create application with nuxtjs not working

**Logs:**
```
19:44:01.054  GitHub importer started.
19:44:01.299  Cloning chz/avando:master branch.
19:44:04.326  Building image started.
19:44:05.023  Step 1/8 : FROM null
19:44:06.754  Failed to deploy!
19:44:06.757  Reason: pull access denied for null, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

```

**Reason:** 
Deployment image and Base image not working for NuxtJS applications. Only work for Nodejs:

<img width="900" alt="Screenshot 2022-05-03 at 23 43 49" src="https://user-images.githubusercontent.com/3233370/166554270-b0fe623b-29fa-486c-be19-034993862709.png">

**Comment by chz** [comment]
also i cant select build images nodejs: 
<img width="900" alt="Screenshot 2022-05-03 at 23 43 49" src="https://user-images.githubusercontent.com/3233370/166554270-b0fe623b-29fa-486c-be19-034993862709.png">

**Comment by chz** [comment]
Both Deployment image and Build image empty

**Comment by chz** [comment]
Btw if i choose nodejs either nuxtjs it will work. I think it will be defined nodejs version for some type of services also not only for nodejs

**Comment by andrasbacsai** [comment]
Ah, found the issue. The new version is on its way. Closed by #406

**Comment by andrasbacsai** [comment]
Released.

**Comment by chz** [comment]
> Released. Let me know if it still does not work after update.

Work like a charm 🚀
