### ISSUE TITLE
[Bug]: Whenever I attempt to start any Docker Compose project, the server crashes. This issue persists across multiple providers.

### ISSUE THREAD

**Issue by abdulsaheel** [coollabsio/coolify#4057]
### Error Message and Logs

![Image](https://github.com/user-attachments/assets/6db4684b-785a-42f1-b57b-a994b8247652)
Whenever I attempt to start any Docker Compose project, the server crashes. This issue persists across multiple instances

## 1. Update Coolify

Update Coolify to version **v4.0.0-beta.36**:

- [release page](https://github.com/coollabsio/coolify/releases/tag/v4.0.0-beta.36) 

## 2. Create a Project in a Private GitHub Repository

1. Create a private repository on GitHub.
2. Set up a project using Docker-Compose in the repository.

## 3. Start the Application

Attempt to start the application. You may encounter the following error:

```
Error: sudo: /etc/sudo.conf is owned by uid 1000, should be 0
```

---

### Coolify Version

v4.0.0-beta.360

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04

**Comment by beejaz** [comment]
It seems your server setup could be wrong, are you running coolify as root user or regular user? What happens if you write any `sudo` command in the terminal? Do you get the same error?

**Comment by abdulsaheel** [comment]
Hey Thanks for the reply,

After investigating further, I found that the issue was caused by Docker Compose accessing files under the `/etc/` directory for storage mounting. This access led to conflicts, resulting in the error:

```
sudo: /etc/sudo.conf is owned by uid 1000, should be 0
```

To resolve this, I adjusted the mounts to avoid directly mapping sensitive files from `/etc/` into the container. If other users encounter this issue, a good workaround is to:
- Avoid direct mounts to system directories like `/etc/`, or copy necessary files to a user-accessible location outside of `/etc/`.
- Alternatively, consider using Docker-managed volumes or `tmpfs` mounts to avoid permission conflicts with root-owned files.

Hope this helps clarify the root cause and assists others in troubleshooting similar issues. Let me know if you need any more details!

---
