### ISSUE TITLE
[Bug]: link broken to Docker docs on resources

### ISSUE THREAD

**Issue by RayBB** [coollabsio/coolify#4079]
### Error Message and Logs

https://coolify.io/docs/applications/#resource-limits

It says:
> By default, the container won’t have any resource limits. You can set the limits here. For more details, read the [Docker documentation](https://docs.docker.com/compose/compose-file/compose-file-v2/#cpu_count-cpu_percent-cpu_shares-cpu_period-cpu_quota-cpus-cpuset-domainname-hostname-ipc-mac_address-mem_limit-memswap_limit-mem_swappiness-mem_reservation-oom_kill_disable-oom_score_adj-privileged-read_only-shm_size-stdin_open-tty-user-working_dir).

That link is broken now. 
Also it would be nice to add a small example for ease of use like how to limit cpu or ram.

The link should probably be: https://docs.docker.com/reference/compose-file/deploy/#resources

**Comment by peaklabs-dev** [comment]
Thanks for reporting, wrong repo though, but I fixed it.
