### ISSUE TITLE
[Bug]: docker-compose.yml not recognized. .yaml required

### ISSUE THREAD

**Issue by Nubebuster** [coollabsio/coolify#4098]
### Error Message and Logs

The error message specifies
>Docker Compose file not found at: /docker-compose.yaml<br><br>Check if you used the right extension (.yaml or .yml) in the compose file name.

when there is a docker-compose.yml present it fails to recognize it. Renaming the file to docker-compose.yaml solves the issue. But the error message implies that .yml is acceptable. Either we need to change the message or detect .yml as well.

### Steps to Reproduce

1. Have docker-compose.yml
2. Not recognized
3. Open issue on github

### Coolify Version

v4.0.0-beta.360

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24

**Comment by peaklabs-dev** [comment]
You just need to change the file extension to `yml` in Coolify and it will work. ![Image](https://github.com/user-attachments/assets/01376f87-af6e-4349-b0e7-96fa452d4841)
