### ISSUE TITLE
How to configure apps?

### ISSUE THREAD

**Issue by DDDASHXD** [coollabsio/coolify#410]
I've just yesterday installed coolify for the first time, and so far it is absolutely amazing. Not having create nginx reverse proxies and just import from github is amazing, and something i've been looking for for some time now. I just have one problem. I would like to setup my own Ghost blog, which at first worked just as easy as enabling the serivce. But there is a problem in the config somewhere, that makes it so that users aren't able to subscribe to the newsletter. I have setup mailgun. I saw a post on the official ghost forum, that i just had to disable secure_connection in the config file, but i have absolutely no idea where Coolify saves the config for ghost. If someone could help, it would be greatly appriciated.

// Best regards,
Sebastian Skov.

**Comment by spencerflagg** [comment]
+1 - I'm also interested in this. Seems like the major use-case for Ghost is the newsletter functionality, and I haven't yet seen an example of someone getting the full Ghost newsletter experience hosting on Coolify.

**Comment by DDDASHXD** [comment]
):

**Comment by jugglingjsons** [comment]
@DDDASHXD We've managed to find a solution for it, you can how onto discord - I can help there, but in short :

In general there are two mailer credentials for ghost cms:
1. you set in the app for the newsletter itself
2. you set in smtp setting for singular target emails, exactly like you asked smtp settings
You need to set extra parameters as secrets for the ghost container in the secrets section in top right I believe 

Take a look at the docs for the container coolify is running -> https://github.com/bitnami/bitnami-docker-ghost/blob/master/README.md#smtp-configuration-using-a-gmail-account

You have likely set the config in the app - that is for newsletter only, so for bulk emails. The singular target emails use nodemailer, and use smtp settings.

I hope that helps!

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
