### ISSUE TITLE
[Bug]: Internal Server Error

### ISSUE THREAD

**Issue by devamaz** [coollabsio/coolify#4105]
### Error Message and Logs

> ranse-frontend@0.1.0 start /app
> next start

- ready started server on 0.0.0.0:3330, url: http://localhost:3330
- info Loaded env from /app/.env
Error: connect ECONNREFUSED 127.0.0.1:45265
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 45265
}

### Steps to Reproduce

1. Use Nixpacks to deploy Nextjs application

### Coolify Version

v4.0.0-beta.360

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04

**Comment by REllwood** [comment]
Getting this exact issue as well

**Comment by peaklabs-dev** [comment]
This is pretty hard to debug without seeing the repo you want to deploy, can you please provide a small URL.
