### ISSUE TITLE
[Bug]: Login to all IPs

### ISSUE THREAD

**Issue by Bishwarup-Das** [coollabsio/coolify#4113]
### Error Message and Logs

When I have added specific IP in the Settings->Configurations->Allowed IPs. I can get logged in from any network. The specific IP is not working.

### Steps to Reproduce

1.
2.
3.
4.

### Coolify Version

v4.0.0-beta.360

### Are you using Coolify Cloud?

No (self-hosted)

**Comment by Bishwarup-Das** [comment]
@andrasbacsai please assist me in this issue

**Comment by djsisson** [comment]
@Bishwarup-Das if you hover over the question mark, you will see it is allowed IPs to use the api, it has no effect on the website, for that you can modify traefik if you wish

**Comment by Bishwarup-Das** [comment]
> [@Bishwarup-Das](https://github.com/Bishwarup-Das) if you hover over the question mark, you will see it is allowed IPs to use the api, it has no effect on the website, for that you can modify traefik if you wish

I mean to say that i want to login to coolify for a specific IP

**Comment by 94836615** [comment]
> > [@Bishwarup-Das](https://github.com/Bishwarup-Das) if you hover over the question mark, you will see it is allowed IPs to use the api, it has no effect on the website, for that you can modify traefik if you wish
> 
> I mean to say that i want to login to coolify from a specific IP

Maybe an option to adjust your firewall then? 😃

**Comment by peaklabs-dev** [comment]
This is more of an new feature request as this has not yet been implemented, please move dicussion to this discussion https://github.com/coollabsio/coolify/discussions/4272
