### ISSUE TITLE
[Bug]: telegram notifications not working

### ISSUE THREAD

**Issue by apperside** [coollabsio/coolify#4116]
### Error Message and Logs

I am trying to make telegram notifications work, but it seem there is no way.
I have both a working bot token and chat id, I am sure the data is correct because if I open with the browser a link like this

https://api.telegram.org/bot<my-bot-token>/sendMessage?chat_id=<my-chat-id>&text=test123§

the message is properly sent, but if I click on "send test notification" on coolify I see a success toast notification but I don not receive nothing.

### Steps to Reproduce

1. From coolify dashboard, Go to notifications -> telegram
2. add bot token and chat id
3. click "send test notification"

### Coolify Version

v4.0.0-beta.360

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.0.4

**Comment by jonm01** [comment]
I am facing the same issue

**Comment by issam-seghir** [comment]
I'm experiencing the same problem. I created a bot using BotFather and added it to a private group. I copied the bot token and the chat ID, then sent a test notification, but I didn't receive anything. 

The same issue is occurring with email notifications as well!

**Comment by bisvillallai** [comment]
Same here with self-hosted v4.0.0-beta.375

**Comment by issam-seghir** [comment]
upgrade to self-hosted v4.0.0-beta.377 
and email / telegram test notification still not working !!

**Comment by peaklabs-dev** [comment]
They are working. Are you on localhost or on a Cloud VPS?

**Comment by issam-seghir** [comment]
> They are working. Are you on localhost or on a Cloud VPS?

on hostinger VPS

**Comment by issam-seghir** [comment]
> Can you re-setup both channels with our new update docs as it should work fine: https://coolify.io/docs/knowledge-base/notifications/

![gif](https://i.imgur.com/O9ktUYB.gif)

**Comment by issam-seghir** [comment]
> Can you re-setup both channels with our new update docs as it should work fine: https://coolify.io/docs/knowledge-base/notifications/

Thank you, I realized I needed to make my bot an admin. Everything is working now.
