### ISSUE TITLE
[Bug]: Browserless Magic

### ISSUE THREAD

**Issue by ARHAEEM** [coollabsio/coolify#4125]
### Error Message and Logs

I've noticed a few issues with the browserless template that need addressing:
![Image](https://github.com/user-attachments/assets/72c773c9-0288-47a9-8488-edac1e315974)

The variable is displaying its name instead of its value. 🔍
Debug features and API seem to be encountering network/proxy problems. It might be a port configuration issue, like 3000:3000. ⚙️
The secret isn't generating a random password, or there's no initial input prompt. 🔑

Thanks!

### Steps to Reproduce

1. install coolify
2. run template "Browserless"
3. check env section
4. read first message.

### Example Repository URL

https://github.com/browserless/browserless

### Coolify Version

v4.0.0-beta.360

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04.4 LTS

**Comment by jmsx** [comment]
Same for me in django test.
![Image](https://github.com/user-attachments/assets/1f3e8ebd-d59f-4982-be5e-49a743a6a046)
https://github.com/jmsx/django-coolify

**Comment by jmsx** [comment]
@peaklabs-dev I'm testing after upgrading to 368 but it still doesn't work with this docker compose:
https://github.com/jmsx/django-coolify/blob/main/docker-compose.yml

**Comment by peaklabs-dev** [comment]
Are you using GitHub as a source, if so, this is not yet supported. You will need to use the compose deploy type. Also the magic will be refactored and get more clearer names soon.

**Comment by jmsx** [comment]
@peaklabs-dev OK sorry, I didn't know that. Yes, I'm using ‘Public Repository’.

**Comment by peaklabs-dev** [comment]
@jmsx All good, it should work I agree. I am refactoring all the code and also adding working magic to git via this PR https://github.com/coollabsio/coolify/pull/4127 - will take some time as it is a huge change. Also for the future, please open a separate issue, you can link to this one if you want, but it is hard to keep up if there are multiple issues in one.
