### ISSUE TITLE
[Bug]: Docker version wrongly set as valid when validating new server

### ISSUE THREAD

**Issue by easilok** [coollabsio/coolify#4128]
![Image](https://github.com/user-attachments/assets/fae60fd5-53f8-44d1-ae7a-2ff7293d0535)
### Error Message and Logs

When trying to add an external server to coolify,  I got the error `Docker Engine version is not 22+. Please install Docker manually before continuing: [documentation](https://docs.docker.com/engine/install/#server).` with only the `Proxy started` step as failed.

The server I'm trying to add is an already running that I previously had, which is running Debian and docker version 23.0.4 which, at first look, should work as expected. 

After some investigation on the code, I found that  docker version check is done with the `docker version --format json` command, which seems to only be available on docker 23.0.5 (I tested to see when it was available to provide better feedback). Here are details of the server in question:

```bash
user@server:~$ docker version
Client: Docker Engine - Community
 Version:           23.0.4
 API version:       1.42
 Go version:        go1.19.8
 Git commit:        f480fb1
 Built:             Fri Apr 14 10:32:17 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.4
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.8
  Git commit:       cbce331
  Built:            Fri Apr 14 10:32:17 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.20
  GitCommit:        2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc:
  Version:          1.1.5
  GitCommit:        v1.1.5-0-gf19387a
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
user@server:~$ docker version --format json
json
```

So, although I don't consider this a big issue as docker should be updated, it seems that feedback from the docker version check is not being properly displayed, as this should have caused a failure in that step. 

The docker version also seems to be required above 23.0.4 and not only above 22 as the error message indicates, which maybe it would be easier to just lock it to above version 23 at this point?

### Steps to Reproduce

1. Install coolify service.
2. Setup another server that has a docker installation of version less that 23.0.5. 
3. When trying to validate this new server, 'docker version' check should pass and fail the 'proxy started' check with error message that "docker 22+" is required.  

### Coolify Version

v4.0.0-beta.360

### Are you using Coolify Cloud?

No (self-hosted)

**Comment by easilok** [comment]
Hello guys,

As I reported in the issue, I already found the issue on code and fixed it. I've been trying to start contributing to open-source projects for some time (I'm a developer) and I really like what you are doing here. Honestly it seems to be a great opportunity to start contributing, so I would like to make a PR to fix this one on my own and maybe contribute for other issues if possible.

I'll create a PR for this anyway and we can talk from there with time.

**Comment by peaklabs-dev** [comment]
Sounds great, contributors are always welcome, honestly it would probably be good to just say that it requires Docker 25+ or so at the moment we use 26 in the install script.

**Comment by easilok** [comment]
> Sounds great, contributors are always welcome, honestly it would probably be good to just say that it requires Docker 25+ or so at the moment we use 26 in the install script.

Sounds good to me. I'll make the change with that version. 

I'll try to present something soon then. 

Thanks for your answer.

**Comment by peaklabs-dev** [comment]
It changed it to min version 24, which should be sufficient (do not want to force use to have to use the latest one 26/ 27).
