### ISSUE TITLE
[Bug]: API Tokens view filtered by user and not by team

### ISSUE THREAD

**Issue by seb-L8L** [coollabsio/coolify#4135]
### Error Message and Logs

Admin view : Keys and Tokens > API tokens

It is said "Tokens are created with the current team as scope.", however the list of issued tokens only displays those created by the current user. Tokens issued by other users for the same team are not listed.

### Steps to Reproduce

1. create two users, members of the same team
2. user # 1 creates a new API token
3. user # 2 creates a new API token
4. each user can only see the API token he/she created and not the other one

### Coolify Version

v4.0.0-beta.360

### Are you using Coolify Cloud?

Yes (Coolify Cloud)

**Comment by peaklabs-dev** [comment]
Yes, having the current team as a scope means that you can only access resources in that team. It is not a token that has access to everything. And also it is normal that you only see your tokens, the other thing would not really be a good thing from a security perspective.

**Comment by seb-L8L** [comment]
@peaklabs-dev 
I completely understand the "team scope".
However, I don't quite get the "a user can only see his/her own tokens" ; where is the security issue for there is no sensitive information displayed?
Listing all team's tokens may give enough information for other team members that certain keys already exist (by their given names) and not (re)generate them... which is what we experienced! :)
