### ISSUE TITLE
[Bug]: Docker Compose doesn't pull latest codebase

### ISSUE THREAD

**Issue by andrija29** [coollabsio/coolify#4145]
### Error Message and Logs

Deployment process is not using latest codebase if Docker Compose is in use. It works if Dockerfile is used. Not even force deploy with clear cache works.

### Steps to Reproduce

1. Create resource with Docker Compose
2. Initial deployment will use latest code
3. Push new changes to the codebase
4. New deployment will trigger and pass, but codebase will be old one

### Coolify Version

v4.0.0-beta.360

### Are you using Coolify Cloud?

Yes (Coolify Cloud)

### Additional Information

If Dockerfile is being used then everything works fine, new codebase is being used in new deployment. If Docker Compose is being used, old codebase is in use.

**Comment by djsisson** [comment]
@andrija29 can you link your compose please, are you using volume mounts in the compose?

if this is just an image in the compose, then it will just reuse the same tag thats in the local registry if its there, so you need to add a pull_policy to the compose or add force=true to webhookurl

**Comment by djsisson** [comment]
@andrija29 youre overwriting your container with a volume mount, remove it its not needed

**Comment by andrija29** [comment]
> [@andrija29](https://github.com/andrija29) youre overwriting your container with a volume mount, remove it its not needed

This was the issue. Thank you!
