### ISSUE TITLE
[Bug]: Installation script does EUID check after trying to create rootfs directories

### ISSUE THREAD

**Issue by Bilge** [coollabsio/coolify#4152]
### Error Message and Logs

```
$ curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash
mkdir: cannot create directory ‘/data’: Permission denied
mkdir: cannot create directory ‘/data’: Permission denied
mkdir: cannot create directory ‘/data’: Permission denied
mkdir: cannot create directory ‘/data’: Permission denied
mkdir: cannot create directory ‘/data’: Permission denied
mkdir: cannot create directory ‘/data’: Permission denied
mkdir: cannot create directory ‘/data’: Permission denied
mkdir: cannot create directory ‘/data’: Permission denied
mkdir: cannot create directory ‘/data’: Permission denied
curl: (23) Failed writing body (952 != 10156)
```

### Steps to Reproduce

1. curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash

### Coolify Version

Doesn't even install lol

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 20.04.3 LTS

### Additional Information

The script actually does a [EUID check](https://github.com/coollabsio/coolify/blob/main/scripts/install.sh#L86-L89) later on, after it has already tried doing operations that require being root (namely: `mkdir`), which is pretty dumb.

**Comment by itunza** [comment]
curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash
mkdir: cannot create directory ‘/data’: Permission denied
mkdir: cannot create directory ‘/data’: Permission denied
mkdir: cannot create directory ‘/data’: Permission denied
mkdir: cannot create directory ‘/data’: Permission denied
mkdir: cannot create directory ‘/data’: Permission denied
mkdir: cannot create directory ‘/data’: Permission denied
mkdir: cannot create directory ‘/data’: Permission denied
mkdir: cannot create directory ‘/data’: Permission denied
mkdir: cannot create directory ‘/data’: Permission denied

**Comment by itunza** [comment]
having the same issue, fresh ubuntu 22.04 install mkdir: cannot create directory ‘/data’: Permission denied

**Comment by Bilge** [comment]
You have to run `curl -fsSL https://cdn.coollabs.io/coolify/install.sh | sudo bash`.

**Comment by itunza** [comment]
i think we have to run it as a sudo user
