### ISSUE TITLE
[Bug]: Windmill does not see any of its workers

### ISSUE THREAD

**Issue by Bilge** [coollabsio/coolify#4158]
### Error Message and Logs

Windmill onboarding never completes because it launches a job that no worker ever picks up because there are no workers defined.

### Steps to Reproduce

1. Deploy Windmill.
2. Try to complete HTTP onboarding process.
3. You can't.

### Coolify Version

v4.0.0-beta.360

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 20.04.3 LTS

### Additional Information

Using some tricks we can bypass the onboarding and see no workers are defined.

![Image](https://github.com/user-attachments/assets/c849850c-4e31-469d-a1a0-161e48ccaa42)

This job will wait for an executor indefinitely (it is 02:43 at the time of this writing).

![Image](https://github.com/user-attachments/assets/adcb302e-47b8-447c-8d53-903986b2ea92)

**Comment by peaklabs-dev** [comment]
This will be fixed in the next version. You can manually use the new compose file from this link for now: https://github.com/coollabsio/coolify/blob/next/templates/compose/windmill.yaml

**Comment by Bilge** [comment]
That config causes Windmill Server to fail to even connect to the database any more:

>2024-11-07T12:04:23.661421503Z Error: Connecting to database: error returned from database: password authentication failed for user "HlHmdyUk4cWNvPno"
