### ISSUE TITLE
[Bug] Navigation bar on laptop screens

### ISSUE THREAD

**Issue by vasani-arpit** [coollabsio/coolify#417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In normal laptop screen size nav bar is going out of the screen. Thus, User is unable to see last two options (Settings and logout) in nav bar

#### Screenshot

![image](https://user-images.githubusercontent.com/6497827/167426076-cf733844-82af-4243-9bef-f647d3d4a079.png)

#### My Device (mydevice.io)

![image](https://user-images.githubusercontent.com/6497827/167426215-3ea98f04-1d19-4239-9ad4-38a50876879d.png)

full screenshot.  https://i.imgur.com/BQIzmJY.png

### Steps To Reproduce

1. Login into coolify
2. change your screen resolution to 768x1366px
3. Notice the left navbar

### Possible fixes

Make nav bar content scrolling and hide scrollbar using css. 

### Version

2.6.3

**Comment by andrasbacsai** [comment]
I slightly modified the navbar to be visible on the screen + have a scrollbar on smaller screens. It will be released soon.
