### ISSUE TITLE
Wordpress Support

### ISSUE THREAD

**Issue by wottpal** [coollabsio/coolify#42]
Hey thanks for this awesome project. What I always needed without knowing..

I would like to deploy my business app (next.js) side-by-side with my landing-page (wordpress). I think it would give this project a real boost if you add support for wordpress-installations, too :) I think it only needs to be the initial setup (Core + DB) and maybe some basic configurations but nothing more in-depth.

Regards from Germany!

**Comment by wottpal** [comment]
I guess you can take a lot of inspiration from here https://www.easywp.com (by Namecheap).

**Comment by andrasbacsai** [comment]
Hey! I really like the idea of a one-click WordPress installation! Thanks for the suggestion. I will implement it soon, that's sure!

**Comment by andrasbacsai** [comment]
I'm closing this one as I've added Wordpress to our [roadmap](https://github.com/coollabsio/coolify/projects/1). Thanks for the suggestion!

**Comment by andrasbacsai** [comment]
It will be available in the next release!

**Comment by andrasbacsai** [comment]
Landed with #65 🎉

**Comment by wottpal** [comment]
very nice :) looking forward to try it out
thanks andras!
