### ISSUE TITLE
[Bug]: Horizontal scrollbar on dashboard

### ISSUE THREAD

**Issue by aidendotgg** [coollabsio/coolify#4208]
Horizontal scrollbar in full width layout

![Image](https://github.com/user-attachments/assets/d8592e45-2078-4ebd-8a37-1f3eab1ba325)

### Steps to Reproduce

1. go to dashboard
2. see that there is a horizontal scrollbar

### Coolify Version

v4.0.0-beta.364

### Are you using Coolify Cloud?

No (self-hosted)

**Comment by peaklabs-dev** [comment]
I can not reproduce this what browser and OS are you using?
