### ISSUE TITLE
[Feature]: Delete old docker containers / node_modules

### ISSUE THREAD

**Issue by samihanine** [coollabsio/coolify#422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Each time we build a node application, a new docker container is created, with a new node_modules folder. The old containers are kept.

Also when we delete an application, its containers are not deleted either.

As a result, it takes a lot of space in the local disk. So it would be a good idea to give the **_possibility_** to delete the old containers.

### Why should this be worked on?

Nodes_modules and consequently docker containers use a lot of storage. For servers with little storage space, it would be vital to allow deleting old containers from the coolify dashboard.

**Comment by andrasbacsai** [comment]
I think this is fixed now with v3 and the new scheduler. Could you please review it?

Coolify has a job to clean up docker stuff periodically or manually from the dashboard.

**Comment by samihanine** [comment]
Hello, it does work. Indeed, the button on the homepage delete the excess storage. 

Thank you for your wonderful work !
