### ISSUE TITLE
[Bug]: Installation fails silently on 4. Check Docker Configuration

### ISSUE THREAD

**Issue by melang982** [coollabsio/coolify#4230]
### Error Message and Logs

```
1. Installing required packages (curl, wget, git, jq). 
2. Check OpenSSH server configuration. 
 - OpenSSH server is installed.
 - SSH PermitRootLogin is enabled.
3. Check Docker Installation. 
 - Docker is installed.
4. Check Docker Configuration. 
```
Doesn't print anything after that and quits.
UPD: If after that I run the script again, it installs fine. Tried it two times - always quits on 4. Check Docker Configuration on the first installation and installs OK on the second attempt.

I'm using a clean VPS with Ubuntu 22.04 LTS + Docker from my hosting provider. The reason why I chose that image instead of a pure Ubuntu 22.04 is that my hosting provider uses MTU 1450 and not 1500 and that causes issues such as https://github.com/coollabsio/coolify/issues/2345, so I wanted the server to have a minimal Docker config for MTU 1450 before installing Coolify. Here's the daemon.json as it was (I didn't run a single command on that machine, it's how it was from the start):

```/etc/docker/daemon.json
{
  "mtu": 1450
}
```

During Coolify installation, installation script changes that to:
```
{
  "mtu": 1450,
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "10m",
    "max-file": "3"
  },
  "default-address-pools": [
    {
      "base": "10.0.0.0/8",
      "size": 24
    }
  ]
}
```
But fails somewhere after that, without printing the error.

What I would like is to be able to install Coolify on a machine that already has Docker installed and a daemon.json, or to specify MTU somewhere during the installation or after it, without reinstalling Coolify. If I change daemon.json after the installation and restart docker service, it only affects one network out of many that Coolify uses, and doesn't fix the network issues.

### Steps to Reproduce

1. Order a VPS with Ubuntu 22.04 LTS + Docker on a hosting provider with MTU 1450 (Hetzner? not sure, I use a different one)
2. Check that /etc/docker/daemon.json is not empty
3. Try to install Coolify using the standard command

### Coolify Version

4.0.0-beta.364

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04

**Comment by mrxsal** [comment]
Also for me it exits without message, but on a clean install of Hetzner Ubuntu 20.04 server (without Docker installed).
Final output:
```
 - Docker is not installed. Installing Docker. It may take a while.
 - Until then, here's a joke for you:

The glass is neither half-full nor half-empty, the glass is twice as big as it needs to be.

```

**Comment by mattstein** [comment]
Same behavior attempting to update a server (UI and CLI installer) running Ubuntu 24.04.1 and Coolify 4.0.0-beta.360.

The CLI installer kept exiting at different points in the install process, and eventually it paused and succeeded after I ran it ten or so times. 😅

**Comment by andrasbacsai** [comment]
Can you please execute the installation command like:

`curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash -x`

It will show the debug output.

**Comment by mattstein** [comment]
My installation completes now since the version is up to date—but if I see the problem again I’ll run the installer with debug info and report back!

**Comment by andrasbacsai** [comment]
I will close this issue. Please reopen if the problem occurs again and attach the installation script with debug logs.

`curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash -x` 

Thank you! :)
