### ISSUE TITLE
[Enhancement]: Confirmation Settings background stays black for Light Mode

### ISSUE THREAD

**Issue by majnioui** [coollabsio/coolify#4235]
### Request Type

Improvement

### Description

Hi;

This is a small adjustment, the **Confirmation Settings** background stays black when switching the color setting to Light mode which prevents it from being seen correctly  as you can see in the screenshot below

![Image](https://github.com/user-attachments/assets/24b32293-a755-4936-b25f-a5d909265b20)

**Comment by peaklabs-dev** [comment]
Duplicate of #4216
