### ISSUE TITLE
[Feature]: Use the latest Alpine Docker version v3.16

### ISSUE THREAD

**Issue by Theofilos-Chamalis** [coollabsio/coolify#429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The latest version of Alpine was released a couple of days ago: https://www.alpinelinux.org/posts/Alpine-3.16.0-released.html .

### Why should this be worked on?

It would be nice to use the lates version v3.16 for any docker containers used as this would provide potential performance & security improvements as well as appropriate toolings updates.

**Comment by andrasbacsai** [comment]
The next version will be based on 3.16.
