### ISSUE TITLE
Dear developer

### ISSUE THREAD

**Issue by gitbeiji** [coollabsio/coolify#430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When I used the demo, I found that the resources can be created at will and will not be destroyed when the account is withdrawn. I am very optimistic about this project and hope to optimize it here in the demo. After all, opening permissions is a good thing, but it may be bad for your server. There is a threat of partial resource usage

### Why should this be worked on?

bug or bug

**Comment by vasani-arpit** [comment]
@gitbeiji Can you explain steps and parts where you think there is an unexpected result. 

I create and delete services, databases and apps all the time and containers get deleted/stopped after I delete that service, db or app from coolify.

**Comment by andrasbacsai** [comment]
The demo instance is for people playing and trying out Coolify, but nothing more. 
Based on the usage, I reinstall it once a week (sometimes once a day). This reinstall wipes everything.

This is not a managed cloud version of Coolify, just a playground for everyone.
