### ISSUE TITLE
[Bug]: Changing instance domain causes error 500: Call to undefined function ray()

### ISSUE THREAD

**Issue by pshemek** [coollabsio/coolify#4300]
### Error Message and Logs

Error: Call to undefined function ray() 

### Steps to Reproduce

1. Install Coolify on VPS and point the domain's A record srv.example.com to the IP address
2. Login via IP:8000 and change the instance domain to https://srv.example.com
3. Access the panel at https://srv.example.com - it works
4. Change your mind and point vps.example.com to the IP address
5. Try to change the instance domain to https://vps.example.com
6. You get the error "Call to undefined function ray()" and the new setting is not saved (the result is the same when the instance domain change is performed via IP:8000 panel as well)

### Coolify Version

v4.0.0-beta.368

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04

**Comment by peaklabs-dev** [comment]
@ahmedrowaihi  You have to upgrade to 369 where the fix was added.
