### ISSUE TITLE
[Bug]: Server errors when creating and editing the Posthog service

### ISSUE THREAD

**Issue by pshemek** [coollabsio/coolify#4308]
### Error Message and Logs

When adding a Posthog resource from the template:
`Error: Attempt to read property "value" on null`

When viewing an (incomplete, I guess) service from the project:
`Error: Attempt to read property "value" on null (View: /var/www/html/resources/views/livewire/project/service/navbar.blade.php) (View: /var/www/html/resources/views/livewire/project/service/navbar.blade.php)`

### Steps to Reproduce

1. Create a new project and try to add resource "Posthog"
2. It produces the error message _Attempt to read property "value" on null_ 
3. Posthog service - apparently corrupted - appears within the project, so try to delete it.
4. However you cannot enter into it because the attempt produces an error: _Attempt to read property "value" on null (View: /var/www/html/resources/views/livewire/project/service/navbar.blade.php) (View: /var/www/html/resources/views/livewire/project/service/navbar.blade.php)_ 

### Coolify Version

v4.0.0-beta.369

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04

### Additional Information

I'm new and I'm playing with different services so I'd be glad to clean up after myself but I can't. :)

**Comment by peaklabs-dev** [comment]
A fix for this issue has been implemented and will be available in an upcoming release. Thank you for your patience.
