### ISSUE TITLE
Separating the API from the UI

### ISSUE THREAD

**Issue by andrasbacsai** [coollabsio/coolify#431]
In the past week, I started to work to separate the API from the UI. That is why I did not release a new version.

There are several advantages of the new architecture.

We can make more advanced features like WebSocket, GraphQL, integrate 3rd party things, token-based auth (instead of session-based), manage your instance with a CLI, etc.

I already figured out an excellent monorepo structure that has super DX.

**Comment by vasani-arpit** [comment]
n8n and directus both are using monorepo arch and both have CLI of their own.

**Comment by andrasbacsai** [comment]
I'm testing 3.0.0 on our [demo ](https://demo.coolify.io) server with lots of projects.🤞🚀
