### ISSUE TITLE
[Bug]: SMTP server setup with no tls issue

### ISSUE THREAD

**Issue by heiniha** [coollabsio/coolify#4311]
### Error Message and Logs

Leaving the envryption field empty does not work for coolify to send the mail without starttls.
Our mailserver always receives requests including starttls.
Would like the option to choose not to use starttls, or if that already exist, then how can I configure it inside the Coolify settings menu -> transactional email -> SMTP server?

### Steps to Reproduce

1. Configure smtp server settings without encryption set
2. Test send email
3. Coolify marks it as sent successfully
4. Mail server denies request with starttls

### Coolify Version

v4.0.0-beta.369

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04

**Comment by peaklabs-dev** [comment]
@heiniha you can set it to TLS or STARTTLS.

@pshemek This will be fixed in one of the next version and is a different issues.

**Comment by heiniha** [comment]
@peaklabs-dev well, if running in own hosted environment and having a mailrelay available, but only on port 25 (smtp) and using a anonymous solution, so basically no user or password needed and also no tls or starttls needed or possible, then coolify says the email was sent successfully, but in the mail server log I see it still tries starttls.

Basically I would have thought that a no-tls option would be correct, and perhaps a checkbox for enabling anonymous account solution.

Many companies run like this to quickly scale their environments.

**Comment by peaklabs-dev** [comment]
So you want to use SMTP with no username and password and over port 25 (so no TLS). And then you want no encryption to be used and even with port 25 Coolify still uses encryption right? Am I getting this right? I am not sure this is a good idea though because it is highly insecure no encryption and no username and password.

**Comment by heiniha** [comment]
Well I understand it is insecure, but when running self hosted and managing own network, we are able to limit its accessibility into where the traffic flows, hence we're using smtp port 25 relay, without user/pass and no tls support.

If I choose to not set anything in the encryption field, I still see it using starttls on mailserver and no-tls in the field is the same, still see starttls on mailserver.

**Comment by heiniha** [comment]
Hi,

Thanks this is working now in the latest 380 release 😃
