### ISSUE TITLE
[Feature]: Don't ignore filled in field if user is registering

### ISSUE THREAD

**Issue by joeinnes** [coollabsio/coolify#432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently, when a new user wants to register, they arrive at the login screen, which has one button for 'login' and one for 'register'. However, despite the presentation, the 'register' button is not linked to the form above, and redirects to a blank registration form. This means that anything the user has entered has to be re-entered.

This feature would persist the email address and password entered on the log in form.

### Why should this be worked on?

Users may be frustrated having to retype their email and password when registering. Minor quality of life improvement, low impact, but might be a nice UX enhancement.

**Comment by andrasbacsai** [comment]
This is already implemented. 👍
