### ISSUE TITLE
[Bug]: Supabase imgproxy transform does not work

### ISSUE THREAD

**Issue by gigor** [coollabsio/coolify#4384]
### Error Message and Logs

The image transformation does not work due to wrong variable name in the docker compose.

Right now docker compose includes variable 

```
supabase-storage:
    environment:
      - IMAGE_TRANSFORMATION_ENABLED=true
```

It should be 
```
supabase-storage:
    environment:
      - ENABLE_IMAGE_TRANSFORMATION=true
```

According to the [supabase docs](https://supabase.com/docs/guides/storage/serving/image-transformations#storage-api-configuration).

### Steps to Reproduce

1. Launch a supabase service
2. Add an image to a public bucket
3. Try resizing image with parameters like so `[your_supabase_domain]/storage/v1/render/image/public/[bucket_name]/[image_path]?width=110&height=100&resize=cover
4. no profit

### Coolify Version

 v4.0.0-beta.360

### Are you using Coolify Cloud?

No (self-hosted)

**Comment by djsisson** [comment]
@gigor thats a good spot
