### ISSUE TITLE
[Bug]: Error building a Docker Compose of a git

### ISSUE THREAD

**Issue by guillempuche** [coollabsio/coolify#4397]
### Error Message and Logs

I cannot build a Docker Compose.

![Image](https://github.com/user-attachments/assets/78290268-1a6a-4925-961a-31f3ce854244)

### Steps to Reproduce

1. Create a resource with this git public repo https://github.com/guillempuche/selfhost_fullstack_in_vps that has multiple Docker Compose services 
2. Select `Docker compose`
3. Location `services/powersync`. The location already have a file `docker-compose.yaml`
4. Click "Save" and get the error

### Example Repository URL

https://github.com/guillempuche/selfhost_fullstack_in_vps/tree/main/services/powersync

### Coolify Version

v4.0.0-beta.372

### Are you using Coolify Cloud?

Yes (Coolify Cloud)

### Operating System and Version (self-hosted)

Ubuntu 20.04.6 LTS

### Additional Information

I tested the same with a private repo using GitHub Apps https://github.com/coollabsio/coolify/issues/4348. I had the same success.

**Comment by guillempuche** [comment]
I cannot deploy the public git to my Hetzner VPS. 

![Image](https://github.com/user-attachments/assets/52f119df-fcc3-41bb-9d6d-c4ad5a5f4626)

![Image](https://github.com/user-attachments/assets/a80ffbc8-b346-4f02-a8de-306f5b96e0b9)

It looks like Coolify is connected to VPS correctly:
![Image](https://github.com/user-attachments/assets/0f6072c7-9c0c-47c1-a602-864efb43a4df)

**Comment by guillempuche** [comment]
What else can I check?

**Comment by djsisson** [comment]
@guillempuche what version are you on, i just tested this too, first selecting /services/powersync before continuing, and also changing after picking nixpacks, it works both times, not sure what else to say

**Comment by guillempuche** [comment]
I'm using Coolify Cloud v4.0.0-beta.373. I suppose it updates automatically, right?

![Image](https://github.com/user-attachments/assets/0a398cd8-5117-413c-9a2a-264c4b02bfaf)

**Comment by djsisson** [comment]
@guillempuche you are adding a / to the end after powersync right ??

**Comment by guillempuche** [comment]
@djsisson, I don't.

This is the config:
![Image](https://github.com/user-attachments/assets/0b34b5d7-5f15-4856-a499-7e88e875bbf8)

**Comment by djsisson** [comment]
@guillempuche ok it doesn't work if you dont, so thats the bug, (add one to the end and press enter

**Comment by guillempuche** [comment]
I did this:

1. Replace `/services/powersync` for `/services/powersync/`
2. Press Enter
3. Coolify complains with the same error message as I posted in the issue
	![Image](https://github.com/user-attachments/assets/b110dc45-f8f4-4305-9a5f-0688b0492dee)

4. Coolify puts back `/services/powersync`

**Comment by guillempuche** [comment]
@peaklabs-dev , for reproducing it, what else do you need from me?

**Comment by peaklabs-dev** [comment]
I still cannot reproduce it no matter what I do / no / or private repo/public repo it does not matter it works for me every time. Please create a new application and try again maybe it is just this one instance that is not working.

**Comment by guillempuche** [comment]
@peaklabs-dev , I deleted the project (and resources) and create it again using the public repo. I got the same error...

![Image](https://github.com/user-attachments/assets/a176f6aa-f382-429d-8c68-ef7145c107d9)

What else can I try?

**Comment by peaklabs-dev** [comment]
Are you using the cloud version? or self-hosted?

I will let Andras know, maybe he has an idea.

**Comment by guillempuche** [comment]
@peaklabs-dev, the cloud version

**Comment by andrasbacsai** [comment]
> [@peaklabs-dev](https://github.com/peaklabs-dev) , I deleted the project (and resources) and create it again using the public repo. I got the same error...
> 
> ![Image](https://github.com/user-attachments/assets/a176f6aa-f382-429d-8c68-ef7145c107d9)
> 
> What else can I try?

Hey. Here you set `supertokens` as a base dir, but there is no such base dir.
![Image](https://github.com/user-attachments/assets/ecb6f2c8-2bc3-403c-8102-b4f5b87bce6a)


But on the other path `(powersync)` is fine, and I can reproduce the issue with your server. I am investigating if the problem is with the git version (or something else).

**Comment by guillempuche** [comment]
Super @andrasbacsai !

These are the services:
<img src="https://github.com/user-attachments/assets/b567675a-7fb5-49b8-b9b9-82bfa83c65cc" alt="Image" width="300">

**Comment by andrasbacsai** [comment]
Found it. 

The process of checking out only that file from git with `cone` (`git sparse-checkout init --cone`) is [added on a newer version](https://github.com/git/git/blob/master/Documentation/RelNotes/2.34.0.txt#L52) of git. So that's why it is not working.

I will add a fix for this.

**Comment by guillempuche** [comment]
Ohhh wonderful!

**Comment by andrasbacsai** [comment]
> Ohhh wonderful!
> 
> [@andrasbacsai](https://github.com/andrasbacsai) , how others don't have this problem if they're using the cloud version?

It is in the cloud and self-hosted version as well, as it is related to the git version installed on your server, so everyone is affected who are using old git.

**Comment by guillempuche** [comment]
You're saying I always should update my self git version in the VPS? Or will Coolify Cloud do it or warn me in the dashboard?

**Comment by andrasbacsai** [comment]
> You're saying I always should update my git in the VPS? Or will Coolify Cloud do it or warn me in the dashboard?

At the moment, Coolify does not update your server, but soon it will notify you (or even automate the update process), so yes. You should keep it updated for now.

**Comment by guillempuche** [comment]
Sounds very promising Andras! Thanks for the fix 🙏

PS: I'm promoting Coolify in local-first world https://www.powersync.com/blog/powersync-update-november-2024. Yesterday, that open-source project, PowerSync, released a guide for self-hosting in Coolify https://docs.powersync.com/integration-guides/coolify. I also adviced them on Discord to add my workflow (git) and solving this issue will help.
