### ISSUE TITLE
[Bug]: Can't connect to database during Dockerfile buildtime

### ISSUE THREAD

**Issue by vendramini** [coollabsio/coolify#4404]
### Error Message and Logs

Hello there!

I'm using new Prisma TypedSQL feature, which relies on an active database connection to generate its types: https://www.prisma.io/docs/orm/prisma-client/using-raw-sql/typedsql

When running it, it says that the database isn't running - however it is, my app is live, I'm able to connect through MySQL Workbench, etc.
```
2024-Nov-26 15:05:27.207981
 > [nextjs  8/10] RUN npx prisma generate --sql:
2024-Nov-26 15:05:27.207981
6.964 Error: Errors while reading sql files:
2024-Nov-26 15:05:27.207981
6.964 
2024-Nov-26 15:05:27.207981
6.964 In prisma/sql/getBestSellingProductsByPeriod.sql:
2024-Nov-26 15:05:27.207981
6.964 Error: P1001
2024-Nov-26 15:05:27.207981
6.964 
2024-Nov-26 15:05:27.207981
6.964 Can't reach database server at `x.y.z.w:5432`
2024-Nov-26 15:05:27.207981
6.964 
2024-Nov-26 15:05:27.207981
6.964 Please make sure your database server is running at `x.y.z.w:5432`.
```
I've tried using both internal URL from Coolify and the public database URL, neither of them work. The database is also hosted on the same coolify instance.

### Steps to Reproduce

1. Enable https://www.prisma.io/docs/orm/prisma-client/using-raw-sql/typedsql on Prisma schema.
2. run `npx prisma generate --sql` during Dockerfile build time.
3. It needs connection to database, which fails.
4.

### Coolify Version

v4.0.0-beta.372

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Alpine 3.20.3

**Comment by vendramini** [comment]
When you say "mapped to host" you mean this?
![Image](https://github.com/user-attachments/assets/cb039647-30e6-4b4c-a096-8f8a4d959d94)

It's allowed to connect to predefined networks and it doesn't work if I try to connect with internal URL.

**Comment by djsisson** [comment]
@vendramini no that just means its in the coolify network , but your host doesnt know about those hostnames hence the error

you would need to add port mappings to teh host or add the ip/hostname to your /etc/hosts file on the host

or run it in post deployment

**Comment by vendramini** [comment]
I couldn't make it work during build time, not even with database IP. But it does work on post deployment. Not the solution that I wanted but I need to move forward :P

Ty for the tip :)
