### ISSUE TITLE
[Bug]: Sanitize build commands

### ISSUE THREAD

**Issue by lamualfa** [coollabsio/coolify#4410]
### Error Message and Logs

**Deployment Logs**

```
docker exec isgkkc48s0wc00ss0sgosw4w bash -c 'nixpacks plan -f toml  --build-cmd "echo 'Skip building'" /artifacts/isgkkc48s0wc00ss0sgosw4w/frontend'
building" /artifacts/isgkkc48s0wc00ss0sgosw4w/frontend: -c: line 1: unexpected EOF while looking for matching `"'
Oops something is not okay, are you okay? 😢
building" /artifacts/isgkkc48s0wc00ss0sgosw4w/frontend: -c: line 1: unexpected EOF while looking for matching `"'
Deployment failed. Removing the new version of your application.
```

### Steps to Reproduce

1. Create a new project
2. Setup the project
3. Set the **Build command** to any command contains a string, `echo 'Skip building'`
4. Deploy

### Coolify Version

v4.0.0-beta.373

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04

**Comment by peaklabs-dev** [comment]
Why would you ever set a build command to something like this, the build will fail anyway so I do not get the issues here?
