### ISSUE TITLE
[Bug]: proxy ui elements disapper

### ISSUE THREAD

**Issue by mounta11n** [coollabsio/coolify#4422]
### Error Message and Logs

basically if you you want to switch or disable the proxy, after clicking on "Switch Proxy", the UI elements to choose one of the three options appear very short and immediately disapper. you have to click on "Proxy" again to make the ui elements appear (now they persist).

here is what I get from firefox console:

```
Uncaught Snapshot missing on Livewire component with id: cRi49DFn3dDpfwgoYaYv [component.js:23:71](https://***.***.**/js/component.js)
    Xt component.js:23
    os store.js:7
    ja lifecycle.js:63
    he module.esm.js:1241
    ie module.esm.js:807
    forEach self-hosted:157
    ie module.esm.js:807
    Oe module.esm.js:723
    ie module.esm.js:805
    Bl module.esm.js:605
    ie module.esm.js:804
    ql module.esm.js:749
    Gr module.esm.js:251
    forEach self-hosted:157
    Gr module.esm.js:251
    (Async: MutationCallback)
    <anonym> module.esm.js:148
    <anonym> index.js:53
```

I have two different versions on my servers and this bug can be found on both of them (beta 370 and beta 373)

### Steps to Reproduce

1. On Side Panel - > Servers
2. Choose your server
3. Click on the "Stop Proxy" button in the upper right area
4. Confirm Stop Proxy in the Pop-Up window
5. Click on the "Proxy" tab (between "Configuration".. and .."Ressources")
6. Click on the "Switch Proxy" button

### Coolify Version

v4.0.0.-beta.373

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04.1 LTS

**Comment by peaklabs-dev** [comment]
This issue should be resolved in the latest version. If you're still experiencing this issue, please reopen or create a new issue with updated details.
