### ISSUE TITLE
[Bug]: Container process running on host machine

### ISSUE THREAD

**Issue by gradinarot** [coollabsio/coolify#4425]
### Error Message and Logs

It looks like the nodejs app that I have also runs as a process on the host machine. Did I misconfig the server somehow? 

![Image](https://github.com/user-attachments/assets/acf90572-e384-465a-806c-fa583da684bd)

### Steps to Reproduce

1.Not sure how to reproduce this.
2.
3.
4.

### Coolify Version

v4.0.0-beta.373

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24

**Comment by peaklabs-dev** [comment]
It runs as a container on your host machine, you can see it when you run `docker ps` and it looks normal, it is probably docker and your various containers you see here. As long as you deployed it through the Coolify UI it should be fine.

**Comment by gradinarot** [comment]
The problem is that I see the actual process running on the host machine, I know that its suppose to run in a container
