### ISSUE TITLE
[Bug]: Could not read from remote repository

### ISSUE THREAD

**Issue by titouanmathis** [coollabsio/coolify#443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After upgrading to v2.9.0, applications from GitLab can not be cloned due to a missing public SSH key.

Build logs: 

```
07:12:00.526  GitLab importer started.
07:12:00.748  Cloning group/test-nuxt:master branch.
07:12:01.917  Failed to deploy!
07:12:01.924  Reason: Error: Command failed: GIT_SSH_COMMAND='ssh -o StrictHostKeyChecking=no' git clone --recursive --jobs 3 -q -b master git@gitlab.com:group/test-nuxt.git --config core.sshCommand="ssh -q -i /tmp/build-sources/group/test-nuxt/id.rsa -o StrictHostKeyChecking=no" /tmp/build-sources/group/test-nuxt/cl3v93egx00000np2drcu9dck/ && cd /tmp/build-sources/group/test-nuxt/cl3v93egx00000np2drcu9dck/ && GIT_SSH_COMMAND='ssh -o StrictHostKeyChecking=no' git lfs pull && cd .. 
Warning: Permanently added 'gitlab.com' (ED25519) to the list of known hosts.

git@gitlab.com: Permission denied (publickey).

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

The SSH key registered in GitLab is the same as the one available from the endpoint `/applications/{applicationId}/configuration/sshkey.json`.

I did not find any logs helping me identify the origin of the bug. I would be glad to send a PR if you have any pointers on how to debug this issue.

### Steps To Reproduce

On a privately deployed version of Coolify upgraded from 2.8.x to 2.9.x, rebuild and deploy an existing application. 

### Version

2.9.3

**Comment by andrasbacsai** [comment]
Thanks for the issue! 

I'm reverting to my last change for the git cloning process. 

The new version will be available [soon](https://github.com/coollabsio/coolify/actions).
