### ISSUE TITLE
[Bug]: private image requiring 'docker login' even after a successful login on the server

### ISSUE THREAD

**Issue by 1hachem** [coollabsio/coolify#4432]
### Error Message and Logs

even after login on the server to docker hub I keep getting the error :
```
Error pull access denied for hachem/hyko-backend, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```
when trying to deploy a private docker image resource

### Steps to Reproduce

1.setup a docker image resource with a private image on dockerhub
2.login on the coolify server with your creds 
3.try to deploy the resource

### Coolify Version

v4.0.0-beta.373

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04.4 LTS

**Comment by djsisson** [comment]
@1hachem can u run docker pull hachem/hyko-backend in terminal

**Comment by 1hachem** [comment]
yes works just fine pulling the image from the server where coolify is hosted

**Comment by djsisson** [comment]
@1hachem can you show full deployment logs
