### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by renedavalos** [coollabsio/coolify#4435]
### Error Message and Logs

Auto deploy fails when i create the application with the API (applications/private-github-app)

### Steps to Reproduce

1.Create (Private - GH App)... POST... https://my.domain.com/api/v1/applications/private-github-app
 body:{
           project_uuid,
           server_uuid,
           environment_name,
           github_app_uuid,
           git_repository,
           git_branch,
           ports_exposes, 
           build_pack,
           name,
           domains
}

2.Create Env..  POST... https://my.domain.com/api/v1/applications/{APPLICATION_ID}/envs

3.Deploy... POST ... https://my.domain.com/api/v1/applications/{APPLICATION_ID}/start

The application is created and everything seems to work fine.. but when I commit and publish the changes in Git.. the application created with the API never detects that commit and does not do an Auto Deploy.

If I add the application manually, everything works fine..

Am I omitting any parameter so that the Webhook works normally?

### Coolify Version

v4.0.0-beta.373

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04

**Comment by peaklabs-dev** [comment]
Thanks for the report we will track resolution in this issue https://github.com/coollabsio/coolify/issues/4557
