### ISSUE TITLE
[Bug]: Docker deployment fails to run with flag -f

### ISSUE THREAD

**Issue by ProjectBay** [coollabsio/coolify#4447]
### Error Message and Logs

Coolify docker deployment always fails, because command uses -f flag
```bash
Starting postgresql-database-x0ww0cs04cssgkwss4so0ogc.
Pulling postgres:16-alpine image.
unknown shorthand flag: 'f' in -f
See 'docker --help'.

Usage:  docker [OPTIONS] COMMAND

A self-sufficient runtime for containers

Common Commands:
  run         Create and run a new container from an image
  exec        Execute a command in a running container
  ps          List containers
...
```

### Steps to Reproduce

1. Start a coolify server
2. Deploy a docker image

### Coolify Version

v4.0.0-beta.373

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04.3 LTS

**Comment by djsisson** [comment]
@ProjectBay can you run ``` docker compose version```

**Comment by ProjectBay** [comment]
> [@ProjectBay](https://github.com/ProjectBay) can you run ` docker compose version`

It runs:
```bash 
docker-compose --version
docker-compose version 1.29.2, build 5becea4c
```

**Comment by djsisson** [comment]
@ProjectBay run apt update / upgrade assuming docker is in your apt source lists

docker version is ~27 and compose version is ~ 2.29

**Comment by ProjectBay** [comment]
> [@ProjectBay](https://github.com/ProjectBay) run apt update / upgrade assuming docker is in your apt source lists
> 
> docker version is ~27 and compose version is ~ 2.29

Ok it worked thank you!
• I made sure docker was int apt source list
• reinstalled docker and docker compose
• reinstalled coolify

Now it works!
Thank you very much! :)
