### ISSUE TITLE
[Bug]: Unable to run a project using .NET 9

### ISSUE THREAD

**Issue by portal7** [coollabsio/coolify#4450]
### Error Message and Logs

When deploying a .NET 9 application using Coolify, the runtime environment seems to default to .NET 6 instead of .NET 9. Locally, the application runs as expected with .NET 9, but the issue arises during deployment.

**Expected Result:**
The application should run with .NET 9 as its runtime environment.

**Actual Result:**
The application runs with .NET 6 instead of .NET 9 but does not deploy.

Additional Information:
**Locally, the application runs with .NET 9 without any issues.**

Coolify's documentation does not mention .NET 9 support explicitly.
Dockerfile content (if applicable):

``` Dockerfile
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
```
...
**Questions/Support Needed:**
Does Coolify currently support .NET 9?
If not, is there a workaround to force .NET 9 runtime?

Additonal Information:
![Image](https://github.com/user-attachments/assets/a418590d-c5a4-4c2a-bd84-e9a40546c890)

### Steps to Reproduce

1. Steps to Reproduce:
2. Create a .NET 9 Application:
3. Ensure you are using .NET 9 SDK locally.
4. Build and run the application to confirm it uses .NET 9.
5. Prepare Coolify Deployment:
 
6. Set up a new project in Coolify.
7. Use the Docker image for .NET 9 in the Dockerfile or ensure the environment supports .NET 9.
8. Deploy the Application:
 
9. Deploy the application via Coolify.
10. Access the deployed instance to verify the runtime version.
11. Check the Runtime Version:

12. Use a command like dotnet --info in the deployed environment or inspect the application logs for the runtime version.

### Example Repository URL

No

### Coolify Version

v4.0.0-beta.373

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04.5 LTS

**Comment by peaklabs-dev** [comment]
With a dockerfile any package also .NET 9 should be possible. Can you please show me your dockerfile.

**Comment by djsisson** [comment]
@portal7 the above log looks like you picked nixpacks not Dockerfile as your deployment method

**Comment by portal7** [comment]
> [@portal7](https://github.com/portal7) the above log looks like you picked nixpacks not Dockerfile as your deployment method

This is because my dockerfile **is inside an internal** folder like “/src/MyProject.API/Dockerfile”, so from there it is difficult.

**Another thing I have also tried** is to use a docker compose file (docker-compose.yaml) **but it fails to authenticate against Gitlab.com** and responds that I am not authorized (at this point, I do not know what I should do so I can use my access token and user in order to connect to the registry of gitlab.com).

**Comment by portal7** [comment]
> With a dockerfile any package also .NET 9 should be possible. Can you please show me your full dockerfile.

Sure, here it is (I have changed the name of my project to “MyProject” for obvious reasons, but it is not important the name for the case in question)



``` Dockerfile
# See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

# This stage is used when running from VS in fast mode (Default for Debug configuration)
FROM mcr.microsoft.com/dotnet/aspnet:9.0-bookworm-slim AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081


# This stage is used to build the service project
FROM mcr.microsoft.com/dotnet/sdk:9.0-bookworm-slim AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["src/MyProject.API/MyProject.API.csproj", "src/MyProject.API/"]
COPY ["src/MyProject.Application/MyProject.Application.csproj", "src/MyProject.Application/"]
COPY ["src/MyProject.Services/MyProject.Services/MyProject.Services.csproj", "src/MyProject.Services/MyProject.Services/"]
COPY ["src/MyProject.Contracts/MyProject.Contracts/MyProject.Contracts.csproj", "src/MyProject.Contracts/MyProject.Contracts/"]
COPY ["src/MyProject.Domain/MyProject.Domain.csproj", "src/MyProject.Domain/"]
RUN dotnet restore "./src/MyProject.API/MyProject.API.csproj"
COPY . .
WORKDIR "/src/src/MyProject.API"
RUN dotnet build "./MyProject.API.csproj" -c $BUILD_CONFIGURATION -o /app/build

# This stage is used to publish the service project to be copied to the final stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./MyProject.API.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# This stage is used in production or when running from VS in regular mode (Default when not using the Debug configuration)
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MyProject.API.dll"]
```

**Comment by portal7** [comment]
> [@portal7](https://github.com/portal7) without having your repo i cant tell you what you need to enter, if you want to use an image thats in a private registry, you need to run docker login registryurl in the terminal on where this is building nad provide the username /token



well, by making it run in my vps 
```docker login registry.gitlab.com``` 
(*and between us, a bunch of steps to make it not use stored insecure credentials*) I managed to make it download my api docker image 

Thanks in advance for the help!
