### ISSUE TITLE
[Bug]: Twenty Webhooks Do Not Work

### ISSUE THREAD

**Issue by jqwez** [coollabsio/coolify#4475]
### Error Message and Logs

Newer versions of Twenty's 1-click Docker deploy use a "worker" container that is missing from the Coolify template. This "worker" container is responsible for communicating various jobs including the Twenty Webhooks feature. 

### Steps to Reproduce

1. Deploy Twenty template on Coolify Resource Page
2. Attempt to establish a webhook in the app.

### Example Repository URL

 https://github.com/coollabsio/coolify/blob/main/templates/compose/twenty.yaml

### Coolify Version

v4.0.0-beta.373

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04.5 LTS

### Additional Information

This issue was discussed and resolved as a Twenty facing issue but it turns out that it's a matter of updating the template.
https://github.com/twentyhq/twenty/issues/8694

I intend to submit a pull request to fix this issue. In the meantime, folk can refer to my response in the twenty issue thread if they wish to troubleshoot.

**Comment by peaklabs-dev** [comment]
We will track resolution of this bug here https://github.com/coollabsio/coolify/issues/4538
