### ISSUE TITLE
[Bug]: Cron jobs run failed

### ISSUE THREAD

**Issue by HeinKoZin** [coollabsio/coolify#4477]
### Error Message and Logs

Cron job run failed

### Steps to Reproduce

1. I deployed laravel
2. And then I set Scheduled Tasks
3. Tasks run failed
 
![Image](https://github.com/user-attachments/assets/000ef881-d135-4ab3-b067-cbc000d0c655)

### Coolify Version

v4.0.0-beta.373

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04.5 LTS

**Comment by peaklabs-dev** [comment]
Can you please set your container name in the container name field and try again?

**Comment by HeinKoZin** [comment]
Thanks @peaklabs-dev. I works fine now.
