### ISSUE TITLE
[Bug]: Maybe issue with release ?

### ISSUE THREAD

**Issue by mr47** [coollabsio/coolify#4481]
### Error Message and Logs

I seen couple releases already but https://cdn.coollabs.io/coolify/versions.json is still on v4.0.0-beta.373, is it ok ?

### Steps to Reproduce

1. Try to run update

### Coolify Version

v4.0.0-beta.373

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Debian GNU/Linux 12 (bookworm)

**Comment by peaklabs-dev** [comment]
Yes this is completely normal see https://github.com/coollabsio/coolify/blob/main/RELEASE.md for more details.
