### ISSUE TITLE
[Bug]: custom path for Plausible Analytics issue

### ISSUE THREAD

**Issue by LittleBigFrog** [coollabsio/coolify#450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I change script name in configuration to new name, like pl.js, script is still plausible.js.
Tried with new instance and restarting old instance

### Steps To Reproduce

Create a plausible service
update script name parameter
check that https://yourdoamin/js/plausible.js returns a script and https://yourdoamin/js/newscriptname.js doesn't

### Version

2.9.6

**Comment by andrasbacsai** [comment]
Ah, I found the issue and will be fixed in the next version!

**Comment by andrasbacsai** [comment]
It is fixed in 2.9.7. It will be available [soon](https://github.com/coollabsio/coolify/actions/runs/2468043026).
