### ISSUE TITLE
[Bug]: Healthchecks require shell inside the container

### ISSUE THREAD

**Issue by Guergeiro** [coollabsio/coolify#4503]
### Error Message and Logs

```
[{"Start":"2024-12-06T23:10:35.587498737Z","End":"2024-12-06T23:10:35.734113239Z","ExitCode":-1,"Output":"OCI runtime exec failed: exec failed: unable to start container process: exec: \"/bin/sh\": stat /bin/sh: no such file or directory: unknown"}]
```

### Steps to Reproduce

1. Deploy a container that is based on [Distroless](https://github.com/GoogleContainerTools/distroless)
2. Activate healthcheck
3. Redeploy

### Coolify Version

v4.0.0-beta.375

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04

### Additional Information

Maybe healthchecks should be done by another component that is not dependent on the deployed container.

**Comment by peaklabs-dev** [comment]
Healthcheck packages should always be included in the container. If your container does not have a shell, which makes perfect sense, consider using alternative healthcheck approaches like http, tcp, and so on.
