### ISSUE TITLE
[Bug]: Scheduled tasks not executing on schedule

### ISSUE THREAD

**Issue by MasterPuffin** [coollabsio/coolify#4515]
### Error Message and Logs

All scheduled tasks are not running at the supposed time. Manually starting works however.

### Steps to Reproduce

1. Add scheduled task
2. Set run to `* * * * *`

### Coolify Version

v4.0.0-beta.373

### Are you using Coolify Cloud?

No (self-hosted)

**Comment by pencilcheck** [comment]
yea, scheduled tasks was working for a couple weeks but then suddenly they all stopped. Not sure what is going on as there is no log
