### ISSUE TITLE
[Bug]: Deployment Discord notifications are not sent anymore in v4.0.0-beta.376

### ISSUE THREAD

**Issue by marwie** [coollabsio/coolify#4522]
### Error Message and Logs

No errors

### Steps to Reproduce

1. Update to v4.0.0-beta.376
2. Deploy application that previously logged to discord
3. Note that after deployment is done no notification is sent
4. Test notifications are sent successfully (webhook config works and all events are ticked)

### Coolify Version

v4.0.0-beta.376

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04 LTS

**Comment by peaklabs-dev** [comment]
This is intended and will be fixed in the next version

**Comment by marwie** [comment]
Do you have additional infos as to why? I didnt see it mentioned in the changelog, did I overlook it?

**Comment by peaklabs-dev** [comment]
No, only success notifications were disabled because a lot of users complained about spam because they got a lot of success notifications and as there was no setting (there will be one soon) we had to disable it temporarily.
