### ISSUE TITLE
[Feature]: phpMyAdmin as Services

### ISSUE THREAD

**Issue by jareer12** [coollabsio/coolify#461]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I was checking out the services tab in coolidy but I couldn't find phpMyAdmin. Is it possible to add phpMyAdmin as services?

### Why should this be worked on?

phpMyAdmin is a really popular tool used by a ton of SQL devs.

**Comment by andrasbacsai** [comment]
PHPMyAdmin is on the [list](https://feedback.coolify.io/posts/42/service-phpmyadmin). It will be added. Thanks for the request!
