### ISSUE TITLE
[Bug]: Gitlab (Self-Hosted) Importer >> Failed to deploy

### ISSUE THREAD

**Issue by KoCoder** [coollabsio/coolify#462]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

When I try to build a new Version of a Project in Collify, using a selfhosted instance of Gitlab and a selfhosted & private instance of Coolify, coolify responds with the following Error. I think, this problem is caused, because I don't use the well known port for ssh. The port I use is (7999).
```
Reason: Error: Command failed: git clone -q -b main git@{gitlabinstanceurl}:{groupid}/{project} --config core.sshCommand="ssh -q -i /tmp/build-sources/{groudid}/{project}/id.rsa -o StrictHostKeyChecking=no" /tmp/build-sources/{groupid}/{project}/cl4fvmx5y00040os0135odvum/ && cd /tmp/build-sources/{groupid}/{project}/cl4fvmx5y00040os0135odvum/ && git submodule update --init --recursive && git lfs pull && cd .. 
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```  
I'd have expected that the project would automaticly deply 

### Steps To Reproduce

1. Go to Applications
2. Add new Application
3. Use Gitlab to authenticate.
4. Select Group, Project, Branch
5. Recieve the error, because my gitlab instance ssh port listens to port 7999, because 22 is already occupied!

### Version

2.9.8

**Comment by KoCoder** [comment]
### Note:
I've change the ssh port for gitlab and now it works.
Even though, I'd appreciate an opportunity, to choose a custom ssh Port.

**Comment by andrasbacsai** [comment]
Thanks for the request! 

Added the possibility to change the port of your custom GitLab / GitHub instance when you define a new source.
![image](https://user-images.githubusercontent.com/5845193/178449718-e36de93d-2ff2-4c15-92b7-7720e6a25ae4.png)
