### ISSUE TITLE
[Bug]: Tried different SMTP services and still cannot receive transactional emails

### ISSUE THREAD

**Issue by pshemek** [coollabsio/coolify#4621]
### Error Message and Logs

Whatever I do, I cannot get transactional emails via SMTP to work even on fresh install on Hetzner.
I also don't know where the logs, if any, are located to see what is happening.

### Steps to Reproduce

1. Spin up a new server (tried CAX21 and CPX11) on Hetzner
2. Clean install Coolify
3. Go to Transactional Email settings and set up SMTP, i.e.:
smtp.resend.com
resend
587
TLS
4. Send test email and check if it is received.

NOTE: It's all about SMTP; emails via Resend API do work

### Coolify Version

v4.0.0-beta.379

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04

### Additional Information

1. On the other hand, when I installed Uptime Kuma, it sends well via the same SMTP.
2. I also have a similar setup on other VPS with Dokploy and notifications with the same SMTP do work there. (Different server provider than Hetzner although uses Hetzner under the hood)

EDIT: 587 SSL do work. Only 587 TLS doesn't. Kudos to @Drunkenpilot for the tip.

**Comment by Fma965** [comment]
I had this issue with mailgun when using TLS despite working elsewhere, i changed it to SSL and it worked despite other applications using TLS.

**Comment by pshemek** [comment]
Unfortunately, Hetzner blocks outgoing 465 for fresh accounts so I'll have to wait.
However, would be great if 587 worked...

**Comment by nettags** [comment]
Same problem: 587 TLS does not work since the (automatic) update to v4.0.0-beta.379. Also using Hetzner, but transactional emails worked fine before the update.

**Comment by Drunkenpilot** [comment]
> Same problem: 587 TLS does not work since the (automatic) update to v4.0.0-beta.379. Also using Hetzner, but transactional emails worked fine before the update.

Have you already try 587 with SSL ? Before  v4.0.0-beta.379, we use Mailjet SMTP with 587 + TLS. After the update we can only made it worked by using Brevo with 587 + SSL.

**Comment by Fma965** [comment]
now that you mention this, this is exactly what I had to do, I was slightly wrong on my earlier post

**Comment by nettags** [comment]
> > Same problem: 587 TLS does not work since the (automatic) update to v4.0.0-beta.379. Also using Hetzner, but transactional emails worked fine before the update.
> 
> Have you already try 587 with SSL ? Before v4.0.0-beta.379, we use Mailjet SMTP with 587 + TLS. After the update we can only made it worked by using Brevo with 587 + SSL.

Yes, 587 + SSL is working, 587 + TLS not anymore. Thanks for the hint!

**Comment by peaklabs-dev** [comment]
A fix for this issue has been implemented and will be available in an upcoming release. Thank you for your patience.

**Comment by shadowoff09** [comment]
So we have to wait for the 4.0.0 stable release to have a fix?

**Comment by peaklabs-dev** [comment]
No the fix is live in v4.0.0-beta.380
