### ISSUE TITLE
[Bug]: Connection could not be established with host "ssl://smtp-relay.brevo.com:587": stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages: error:0A00010B:SSL routines::wrong version number.

### ISSUE THREAD

**Issue by nathanialhenniges** [coollabsio/coolify#4634]
### Error Message and Logs

When resend is disabled it still would have the key in the field which it should be cleared if it's disabled. 

### Steps to Reproduce

1. Add resend API key , save , and enable.
2.  Try to remove or disable resend it will still have the API key there when it should be gone
3. For when your switching back to SMTP
4.

### Coolify Version

v4.0.0-beta.379

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04 LTS

### Additional Information

UI/Database Bug

**Comment by nathanialhenniges** [comment]
Switched off resend as it was failing for some reason and I think I may know why.  

```
EmailChannel error: Connection could not be established with host "ssl://smtp-relay.brevo.com:587": stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:
error:0A00010B:SSL routines::wrong version number. Failed to send email
```

even when it's set to TLS which brevo should be good when I set it to SSL it works maybe something happen recently that broke emails.

**Comment by peaklabs-dev** [comment]
For now, if you disable something by unchecking the checkbox, the data is kept since you could also quickly disable it for debugging, so I think it should not be cleared - it is stored in the DB. 

The second bug you got is because 587 should be using StartTLS and not TLS/SSL, I have fixed that issue in the next release.
