### ISSUE TITLE
[Bug]: Any user can remove all Coolify accounts from the Admin View of its personal team

### ISSUE THREAD

**Issue by TuberculeP** [coollabsio/coolify#4648]
### Error Message and Logs

Admin View from any team seems to be global to all users, so any user from its personal team can remove any other user from coolify database

The best option here is to display admin view only for the Root team

### Steps to Reproduce

1. Connect as Root
2. Invite new user to Coolify
3. New user joins, his own team is created
4. From user account, move to Teams > Admin View
5. User can remove Root from database

### Coolify Version

v4.0.0-beta.379

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04

**Comment by peaklabs-dev** [comment]
See my comment on discord: https://discord.com/channels/459365938081431553/1311626147947352076/1320767917545226322
