### ISSUE TITLE
[Bug]: ERR_CRYPTO_INVALID_KEYLEN

### ISSUE THREAD

**Issue by gregfr** [coollabsio/coolify#466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Greetings
It's my first try at evaluating Coolify.
After starting, the logs shows this:

```
Running seed command `node prisma/seed.cjs` ...

RangeError: Invalid key length

    at Cipheriv.createCipherBase (node:internal/crypto/cipher:116:19)

    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:135:3)

    at new Cipheriv (node:internal/crypto/cipher:243:3)

    at Object.createCipheriv (node:crypto:138:10)

    at encrypt (/app/prisma/seed.cjs:136:25)

    at main (/app/prisma/seed.cjs:32:20)

    at processTicksAndRejections (node:internal/process/task_queues:96:5) {

  code: 'ERR_CRYPTO_INVALID_KEYLEN'

}


An error occured while running the seed command:

Error: Command failed with exit code 1: node prisma/seed.cjs

 ELIFECYCLE  Command failed with exit code 1.
```

### Steps To Reproduce

Run Coolify according to this page: https://docs.coollabs.io/coolify/installation

```
docker run -tid --env-file .env -v /var/run/docker.sock:/var/run/docker.sock -v coolify-db-sqlite coollabsio/coolify:latest /bin/sh -c "env | grep COOLIFY > .env && docker compose up -d --force-recreate"
```

### Version

2.9.10

**Comment by gregfr** [comment]
I just found out I'm using docker 19 instead of the required docker 20 ; I'll update

**Comment by gregfr** [comment]
Tried on a completely different host with Docker 20.10.17, exact same behavior.

**Comment by gregfr** [comment]
So the direct docker command doesn't work, but the root script does.

**Comment by dungsil** [comment]
In my case, I worked with 32 letters of `COOLIFY_SECRET_KEY`.

**Comment by andrasbacsai** [comment]
I think that is not a problem with the docker version or the script. 
Please review how long your `COOLIFY_SECRET_KEY` is. It should be 32 letters long, as suggested by @dungsil (Thanks!)

**Comment by gregfr** [comment]
OK silly me, it was empty in the sample file, so I assume it would be generated... maybe it could be clearer in the doc and in the error message?

Closing now, thanks for your help!

**Comment by v4ld3rr4m4** [comment]
> I think that is not a problem with the docker version or the script. Please review how long your `COOLIFY_SECRET_KEY` is. It should be 32 letters long, as suggested by @dungsil (Thanks!)

Please  sorry , what really means this?   I fill  -> COOLIFY_SECRET_KEY=mysecretkeytryinglongas32charsxx      ? but not work for me
