### ISSUE TITLE
[Bug]: creating an app from gitlab gives "Ooops, something is not okay, are you okay?"

### ISSUE THREAD

**Issue by gregfr** [coollabsio/coolify#467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Greetings
I've just installed Coolify on a new Docker host and configured Gitlab access.
When creating an app, I can see and select the repository, project and branch, but when I click "save" I get
`Ooops, something is not okay, are you okay?`.

`docker log -f coolify` gives nothing...

Is there some log I can access to find the error?

Thanks in advance

Regards

### Steps To Reproduce

Install Coolify with the root script
Configure Gitlab access
Try to create an app

### Version

2.9.10

**Comment by gregfr** [comment]
Note: I'm connecting with an IP address, so I have no cert (don't know if it's relevant).
BTW it would be good to provide a way to skip Traefik as many people would have their own reverse proxy already installed.

**Comment by gregfr** [comment]
Is there a log I can look into?

**Comment by andrasbacsai** [comment]
Do you use self-hosted GitLab instance or the hosted one (Gitlab.com)?

Can you check in the network tab which request fails?

**Comment by andrasbacsai** [comment]
Due to inactivity, I'm closing this issue. However, if the problem persists, please reopen the issue. Thanks!

**Comment by gregfr** [comment]
Sorry github don't send me notifications anymore :(

I'm using Gitlab.com  ; the network tab you're refering to is the browser's? if yes, this request is red:

Request URL: https://gitlab.com/api/v4/projects/xxxx/hooks
Request Method: POST
Status Code: 422

**Comment by gregfr** [comment]
Maybe it's because I'm using a private IP? can I run Coolify on a private network?
