### ISSUE TITLE
Install script not working

### ISSUE THREAD

**Issue by rphenriques** [coollabsio/coolify#47]
Installation breaks after asking for Let's encrypt email address with message:

```
Error: Cannot query your public address against whoami.akamai.net. Please report the problem on Github!
    at getAddresses (/snapshot/coolify/index.js)
    at expressInstallation (/snapshot/coolify/index.js)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async coolifyMe (/snapshot/coolify/index.js)
```

Using ubuntu 20.04 fresh install

**Comment by andrasbacsai** [comment]
It looks like your server does not have a public address. Strange.

If you run `dig @ns1-1.akamaitech.net ANY whoami.akamai.net +short` manually, what is the output?

**Comment by rphenriques** [comment]
Thanks. 

Running `dig @ns1-1.akamaitech.net ANY whoami.akamai.net +short` does not produce any output:

```
rph@coolify:~$ dig @ns1-1.akamaitech.net ANY whoami.akamai.net +short
rph@coolify:~$ 
```

**Comment by andrasbacsai** [comment]
But I suppose you have a public IP address, right?

**Comment by rphenriques** [comment]
Hi, yes.

If I do `wget -qO- http://ipecho.net/plain | xargs echo` (for example), I get the correct IP address.

**Comment by andrasbacsai** [comment]
Thanks for the example! I will slightly modify the installation script.

**Comment by andrasbacsai** [comment]
I've modified the installation script a bit. Could you please check again? If it's still not working, please reopen this ticket. 

Thanks in advance.

**Comment by funkybunch** [comment]
Having a few issues with the install script.  If I don't opt for the github plugin (installation stalls if I do) then I get this on the installation page:
```
Command: curl -s http://ipecho.net/plain failed
```
<img width="589" alt="Screen Shot 2022-02-08 at 12 04 30 AM" src="https://user-images.githubusercontent.com/6365836/152921704-ff44ed84-2a6b-457d-8b1b-98d9cff9019f.png">
