### ISSUE TITLE
[Bug]: Port mappings not created for Docker buildpack

### ISSUE THREAD

**Issue by kkuriata** [coollabsio/coolify#483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

`Docker` buildpack does not respect `Port` entry. It does not create any port mappings in created Docker container. Once I add the mapping manually, then my app works fine.

### Steps To Reproduce

1. Create new app using Docker buildpack.
2. Host any app on any custom port.
3. Build the app.
4. Check created container's port mappings (nothing created).

### Version

3.0.3

**Comment by andrasbacsai** [comment]
I will add the `Exposed port` field to Docker build pack, so you can create the port mapping you need. 

Available in v3.1.0.

![image](https://user-images.githubusercontent.com/5845193/178439358-c05fface-bb98-41d3-a918-6bddf35422ec.png)
