### ISSUE TITLE
[Bug]: Reset password error

### ISSUE THREAD

**Issue by execreate** [coollabsio/coolify#489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Cannot reset password of a user in coolify. The error in the console says:
```json
{
    "status": 500,
    "message": "Argument where of type UserWhereUniqueInput needs at least one argument.\n"
}
```

### Steps To Reproduce

1. Go to IAM in coolify UI
2. Click reset password on any user

### Version

3.1.0

**Comment by andrasbacsai** [comment]
Will be fixed in v3.1.1!
