### ISSUE TITLE
[Feature]:  Adjust Buttons 

### ISSUE THREAD

**Issue by yhoungdev** [coollabsio/coolify#493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

#### Call to Action buttons tool small

**** Buttons like Login, Registeration and others are too small and tiny. 
**** Paddings should be added to it 

### Why should this be worked on?

People with Eye problem will find it difficult to use it 
Adding spacing inside it will make it look cool

**Comment by andrasbacsai** [comment]
I've made them bigger all over the application! 😃
