### ISSUE TITLE
[Feature]: Please include a mail server

### ISSUE THREAD

**Issue by Stargate-project** [coollabsio/coolify#496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I need a mail server for coolify to store emails for projects ( info@mywebsite.com )

please consider two options:

https://github.com/docker-mailserver/docker-mailserver

or 

https://github.com/Mailu/Mailu

### Why should this be worked on?

need a solution to store emails that connect to a domain
do you make it easy to add email to a domain name?

**Comment by poberbeck** [comment]
I also would love to see this feature!

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
