### ISSUE TITLE
[Feature]: Limit Ram/CPU/Disk usage per user

### ISSUE THREAD

**Issue by BelieveInBunny** [coollabsio/coolify#497]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Hello,
I want to know if there is a way we can limit resources usage per user.
I am planning to get a big server for free-to-use access to everyone but for that, I want to limit resources usage so everyone will be happy.

Thanks

### Why should this be worked on?

lot of poeple wants it (I think so) and this will help alot to manage resources nicely

**Comment by vasani-arpit** [comment]
Yes. I think it is possible as per https://docs.docker.com/config/containers/resource_constraints/

@andrasbacsai This is nice to have. can put it along with other configs.

**Comment by BelieveInBunny** [comment]
Docker looks kind of difficult to setup to me, I wish there was more easy way. I will try using docker and see if it is possible for me to do it :)

thank you very much

**Comment by BelieveInBunny** [comment]
thank you very much!

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
