### ISSUE TITLE
[Feature]: Multiple Cluster for one app

### ISSUE THREAD

**Issue by NefiteTifall** [coollabsio/coolify#498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I need to be able to create clusters for applications and a system like a load balancer on Coolify. 
Is it possible ?

### Why should this be worked on?

Need a solution to create clusters and distribute the load. It's better when you need to process a lot of data,

**Comment by andrasbacsai** [comment]
At the moment it is not possible, but... I'm currently working on a feature called remote docker engine that will allow you to add more than one server to a single coolify instance. This is the first step towards your request.

**Comment by dualizeo** [comment]
Hi, will load balancing be a feature? sorry to ask 😅

**Comment by andrasbacsai** [comment]
This will be added to v4.

I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
