### ISSUE TITLE
Video Demo in Safari

### ISSUE THREAD

**Issue by dikaio** [coollabsio/coolify#50]
Just wanted to give you a heads up, the video has some weird playback in Safari. It's the first time I've seen something like that but could be due to the webm format in Safari (Version 14.1.1 (16611.2.7.1.4)).

Anyhow awesome project 👍 

<img width="1245" alt="Screen Shot 2021-05-27 at 12 31 08 PM" src="https://user-images.githubusercontent.com/869535/119886723-1e998600-bee8-11eb-8bc2-aff2a6ac1bf3.png">

**Comment by andrasbacsai** [comment]
I've recorded a new video with a different backup format (webm and mp4). 

Could you please check if it works now? If not, please reopen this issue!

**Comment by dikaio** [comment]
It's workign @andrasbacsai 👍
