### ISSUE TITLE
[Bug]: Teams invite error message should read "Registered user not found "

### ISSUE THREAD

**Issue by jesperordrup** [coollabsio/coolify#502]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to add a new member to team I get an "unknown error"

### Steps To Reproduce

I open team page
I fill in the email
I click on send invitation

I get unknown error. 

![image](https://user-images.githubusercontent.com/3120151/179929903-7dab2d0c-b8cb-4a6a-af35-79e3bce1d19a.png)

The error should read 

Registered user not found (or something)

### Version

3.12

**Comment by andrasbacsai** [comment]
Already fixed.
