### ISSUE TITLE
[Bug]: High memory/cpu usage

### ISSUE THREAD

**Issue by echopico** [coollabsio/coolify#509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Env：
Ubuntu 20.04: 2 CPU, 4GB RAM, 40 GB SSD
Ubuntu 22.04: 2 CPU, 8GB RAM, 40 GB SSD

After a few hours of running only the coolify service, the CPU and memory usage is super high, causing the system to frozen or crash. ssh can't even login.

### Steps To Reproduce

Just run as docs said:

`wget -q https://get.coollabs.io/coolify/install.sh -O install.sh; sudo bash ./install.sh -f`

### Version

3.1.3

**Comment by andrasbacsai** [comment]
I'm trying to reproduce it, but I never noticed such a thing. 

If you still have it running, could you please check the container logs and paste it here if there are errors?

**Comment by echopico** [comment]
Thanks for reply
**This is logs from container:**


🌱  The seed command has been executed.
Coolify's API is listening on 0.0.0.0:3000

> coolify-api@ start /app
> NODE_ENV=production npx -y prisma migrate deploy && npx prisma generate && npx prisma db seed && node index.js

Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "prod.db" at "file:../db/prod.db"

35 migrations found in prisma/migrations


No pending migrations to apply.
Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (3.15.2 | binary) to ./node_modules/.pnpm/@prisma+client@3.15.2_prisma@3.15.2/node_modules/@prisma/client in 577ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```

warn Versions of prisma@4.1.0 and @prisma/client@3.15.2 don't match.
This might lead to unexpected behavior.
Please make sure they have the same version.
Running seed command `node prisma/seed.js` ...

**Comment by itswadesh** [comment]
After installing today's update I am facing the same issue. Before it was fine. My site has 0 traffic still the Memory and CPU consumption is increasing and finally crashing in 1-2 hrs.

**Comment by andrasbacsai** [comment]
Can you please check when the memory consumption is high, which container is using it? ‘docker stats’ output would be a good start to investigate.

**Comment by itswadesh** [comment]
![image](https://user-images.githubusercontent.com/1191896/184273672-74b11dec-55c2-435b-95cf-6b44c31479ec.png)

**Comment by andrasbacsai** [comment]
Could you please show me the `docker top coolify` command output as well?

I think Prisma Engine is causing high memory usage - as always. I added a fix for that in the upcoming version.

**Comment by echopico** [comment]
For `docker stats`
<img width="946" alt="image" src="https://user-images.githubusercontent.com/108854592/184315714-6c9829c5-28ba-4a07-b96d-25b9fd122815.png">

For `docker top coolify`
<img width="1676" alt="image" src="https://user-images.githubusercontent.com/108854592/184315596-02f8e360-e492-473e-ba74-5ee30192d594.png">

As the runtime increases, the CPU and memory resources will be consumed for about 10 hours.

**Comment by andrasbacsai** [comment]
Yeah, just as I thought. Thanks!

**Comment by echopico** [comment]
OK, Great job, thanks for reply!

**Comment by ps73** [comment]
I still have this issue. The coolify container is using something between 60 and 80% of cpu. 
![image](https://github.com/coollabsio/coolify/assets/17291660/3cc7b5b9-9dbf-4462-b326-274c3e0097da)
![image](https://github.com/coollabsio/coolify/assets/17291660/609d18fb-517e-4c14-907f-77e7516c9aee)
