### ISSUE TITLE
[Feature]: Drupal sites

### ISSUE THREAD

**Issue by Stargate-project** [coollabsio/coolify#510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Build and deploy Drupal sites using a modern Jamstack approach

### Why should this be worked on?

integrate Drupal similar to  nellify https://www.netlify.com/with/drupal/

**Comment by shashikanth171** [comment]
Something similar to https://cloud.wodby.com/stacks/drupal9/overview would be great

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
