### ISSUE TITLE
[Bug]: Can't update node version

### ISSUE THREAD

**Issue by cstrnt** [coollabsio/coolify#511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When changing the node version in coolify it always goes back to node:lts		

### Steps To Reproduce

Have a node application
go to its settings
change node version
save
reload
-> Node version back to node:lts

### Version

3.1.3

**Comment by andrasbacsai** [comment]
Oh, I can confirm it. It will be fixed in the next version!

**Comment by abteilung** [comment]
I've got this on 3.7.0 as well as on 3.8.0.

**Comment by andrasbacsai** [comment]
The latest version fixed it! Let me know if not!
