### ISSUE TITLE
[Bug]: After Install cyberpanel , coolify can't run on port 3000!!

### ISSUE THREAD

**Issue by bugbounted2022** [coollabsio/coolify#512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when I'm install cyberpanel , coolify currently installed before cyberpanel can't access on port 3000!!
please test it & you see my problem in action
I'm also bypass redis install on cyberpanel install structure but also the same error .
cyber panel usage ports is :
TCP: 8090 for CyberPanel
TCP: 80, TCP: 443 and UDP: 443 for webserver
TCP: 21 and TCP: 40110-40210 for FTP
TCP: 25, TCP: 587, TCP: 465, TCP: 110, TCP: 143 and TCP: 993 for mail service
TCP: 53 and UDP: 53 for DNS service
please help me why cyberpanel & coolify have conflict .
waiting for your response
finest regards

### Steps To Reproduce

idk

### Version

latest

**Comment by andrasbacsai** [comment]
Hey, Coolify uses port 3000 by default, but Coolify proxy uses 80 & 443. Ifcthe proxy cannot be started, you can only reach Coolify over IP address with port, not with the domain.
