### ISSUE TITLE
[Feature]: Support creation of on-demand TLS certificate with major DNS providers

### ISSUE THREAD

**Issue by tiero** [coollabsio/coolify#513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Implement major SDK/APIs to add DNS record automatically when user creates an application from dashboard

### Why should this be worked on?

Currently, for each application running, the user must create a DNS record that points to the running instance. This could be automated using the API provided by major DNS providers such as Cloudflare, GoDaddy etc... to perform adding records programmatically

**Comment by tiero** [comment]
I think this is a superset of this issue
https://github.com/coollabsio/coolify/issues/300

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
