### ISSUE TITLE
[Feature]: Add openfaas as service

### ISSUE THREAD

**Issue by tiero** [coollabsio/coolify#515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

There are many open-source competitors for cloud functions, it seems the two most stable are either OpenFaaS or OpenWhisk, favoring the first being bit more easy to use.

### Why should this be worked on?

Like Minio, we can replicate the two most famous primitives of cloud providers, besides file storage/S3, also lambda/cloud functions.

**Comment by vasani-arpit** [comment]
Service request should be created here https://feedback.coolify.io/

Github issue is for bugs inside coolify.
