### ISSUE TITLE
[Feature]: Citus - Hyperscale

### ISSUE THREAD

**Issue by Yurgeman** [coollabsio/coolify#518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

[Citus - Hyperscale  docker install](https://docs.citusdata.com/en/v11.0/installation/single_node_docker.html#single-node-docker)

### Why should this be worked on?

[Citus - Hyperscale  docker install](https://docs.citusdata.com/en/v11.0/installation/single_node_docker.html#single-node-docker)

### **Citus** = Postgres At Any Scale

Citus is an open source extension to Postgres that gives you the superpower of distributed tables. Because Citus is an extension, you can leverage the Postgres features, tooling, and ecosystem you love. And in Citus 11, you can now query from any node—plus we’ve open sourced the few remaining Citus Enterprise features. With Citus, you can scale from a single node to a distributed cluster, giving you all the greatness of Postgres—at any scale.

[www.citusdata.com](https://www.citusdata.com)

**Comment by andrasbacsai** [comment]
Added to [feedback](https://feedback.coolify.io/posts/98/database-citus) site!
