### ISSUE TITLE
[Bug]: Not able to login /signup ghost

### ISSUE THREAD

**Issue by scshiv29-dev** [coollabsio/coolify#519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Not able to login as admin or create new account in ghost 

### Steps To Reproduce

1.Create Ghost instance
2.visit it
3. Try logging in through admin or try creating new account.

### Version

3.1.13

**Comment by andrasbacsai** [comment]
I tried to reproduce it, but with the default Ghost settings (what Coolify sets automatically), I cannot.

Did you try to login with the credentials found in the `Ghost` section in Coolify? Did you use the `[your_ghost_domain]/ghost` endpoint?

**Comment by andrasbacsai** [comment]
Due to inactivity, I'm closing this issue. However, if the problem persists, please reopen the issue. Thanks!
