### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by cstrnt** [coollabsio/coolify#521]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Emitter (https://emitter.io/) is a service that allows for easy real-time communication. This is especially handy if you're working serverless where WebSockets are unavailable.

### Why should this be worked on?

It's a service that has been around for some quite and would bring me (and others as well) a huge benefit when working on projects. An integration with coolify would feel really fitting

**Comment by vasani-arpit** [comment]
Service request are being managed here https://feedback.coolify.io/posts/92/service-emitter
Github issues is just for bugs in coolify.
