### ISSUE TITLE
[Bug]: Fider makes the SMTP username all lowercase after saving the configuration

### ISSUE THREAD

**Issue by tiero** [coollabsio/coolify#523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I create a Fider service, it makes the SMTP username all lowercase after saving the configuration. If you use AWS SES you most likely have an username all capital case.

## Workaround

After saving, Override `EMAIL_SMTP_USERNAME` env variable of Fider with your username and only then  start your service

### Steps To Reproduce

1. Create a Fider service
2. Type SMTP credentials
3. Save
4. Would not work sending emails

### Version

3.1.4

**Comment by andrasbacsai** [comment]
Found the issue! Will be fixed in the next version!
