### ISSUE TITLE
[Feature]: Add HestiaCP to services

### ISSUE THREAD

**Issue by dm94** [coollabsio/coolify#525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

This panel could be added  https://github.com/hestiacp/hestiacp/

### Why should this be worked on?

It is a panel very focused on webs, with its multiple php system, email, etc.
Implementing this panel or its functions would be very interesting.

**Comment by andrasbacsai** [comment]
Added [here](https://feedback.coolify.io/posts/99/service-hestiacp), so I'm closing this.
