### ISSUE TITLE
[Bug]: Coolify removes all the stopped containers and unused images

### ISSUE THREAD

**Issue by kkuriata** [coollabsio/coolify#526]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I recently noticed that some of my containers started disappearing. I made an investigation and it looks like Coolify removes everything that is stopped or gets an error (before it restarts). It got rid of about 10 containers that I had temporarily stopped. So annoying, because it is not possible to use Coolify together with other things on Docker.

I use Docker on Synology (DSM7) - maybe this is the issue.

### Steps To Reproduce

1. Create some random containers and stop them.
2. Wait a little bit (not sure the amount of time, but max 5-10 minutes) or restart Docker.
3. Stopped containers and unused images are gone.

### Version

3.1.4

**Comment by andrasbacsai** [comment]
Oh, nice! Thanks for the notice. I do not think of this yet. It will be fixed in the next version (v3.2.1).

**Comment by planecore** [comment]
Hi! Sorry to hijack this issue, but how did you install Coolify on Synology?

**Comment by jimblue** [comment]
> Hi! Sorry to hijack this issue, but how did you install Coolify on Synology?

@kkuriata ☝🏼 can you give us some hit please 🙂 ?
