### ISSUE TITLE
[Bug]: network coolify-infra not found

### ISSUE THREAD

**Issue by wallaceosmar** [coollabsio/coolify#530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Enabling proxy throw a error if network coolify-infra not exists in the remote.
Error response from daemon: network coolify-infra not found.

### Steps To Reproduce

1. Create a new machine and install docker
2. Add as new destination
3. Enable proxy

### Version

3.2.1

**Comment by andrasbacsai** [comment]
Nice catch! v3.2.2 fixes the issue (will be release in a few minutes).

**Comment by andrasbacsai** [comment]
Released. You unfortunately need to delete the destination and add a new one. Let me know if it does not work after that.
