### ISSUE TITLE
[Bug]: Set it public not working

### ISSUE THREAD

**Issue by wallaceosmar** [coollabsio/coolify#535]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The moment you click in Set it public nothing happens.

### Steps To Reproduce

1. Go to databases
2. Select a running or create a new database
3. Start running the database if is not running
4. Set it public

### Version

3.3.2

**Comment by andrasbacsai** [comment]
I introduced this error in the previous release. Fixing in the next one.
