### ISSUE TITLE
[Bug]: Pulling Coolify latest image not working on ipv6 server

### ISSUE THREAD

**Issue by carstenjaksch** [coollabsio/coolify#539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Trying to install Coolify on a server with ipv6 only. Found the issue #120 for that, but I get another error related to Docker:

Running following command ...

```bash
wget -q https://get.coollabs.io/coolify/install.sh -O install.sh; sudo bash ./install.sh -f
```

... throws the following error ...

```bash
Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp 44.207.96.114:443: connect: network is unreachable
```

I tried using a dummy image:

```bash
docker pull hello-world
```

This gives the same error. I added the ipv6-version according to [this article](https://www.docker.com/blog/beta-ipv6-support-on-docker-hub-registry/):

```bash
docker pull registry.ipv6.docker.com/library/hello-world
```

That works.

### Steps To Reproduce

1. Start an ipv6-only cloud server on Hetzner with the official `docker-ce` image: https://www.hetzner.com/cloud
2. SSH into it: `ssh root@ipv6` (replace `::/64` with `::1` in the ip, according to [this guide](https://docs.hetzner.com/cloud/servers/getting-started/connecting-to-the-server/))
3. Try to install Coolify, you will get the error from Docker.

### Version

latest

**Comment by carstenjaksch** [comment]
I can confirm now, that lines 312 and 314 need to be adjusted in order to install Coolify on an ipv6 host:

```bash
echo "Pulling Coolify latest image ($VERSION)."
sudo docker pull -q registry.ipv6.docker.com/coollabsio/coolify:$VERSION > /dev/null
echo "Starting Coolify."
cd ~/coolify && sudo docker run -tid --env-file $COOLIFY_CONF_FOUND -v /var/run/docker.sock:/var/run/docker.sock -v coolify-db-sqlite registry.ipv6.docker.com/coollabsio/coolify:$VERSION /bin/sh -c "env | grep COOLIFY > .env && docker compose up -d --force-recreate" > /dev/null
```

However, I cannot reach the UI.

1. After installation, the ip address is empty: `Please visit http://:3000 to get started.`
2. Trying to reach the admin area from the browser does not work that way: `http://[ipv6]:3000`

Is Coolify even reachable with an ipv6 address or do I need a domain?

**Comment by carstenjaksch** [comment]
Should have done that earlier, but I had a look in `docker ps` and well ... The pulled Docker container is not starting on the ipv6 host. I added an ipv4 address and all works fine.

Maybe networking issues? I see some ipv4 address pools in the install script.

**Comment by andrasbacsai** [comment]
Due to inactivity, I'm closing this issue. However, if the problem persists, please reopen the issue. Thanks!
