### ISSUE TITLE
[Bug]: 3.6.0 requires exposed port by default

### ISSUE THREAD

**Issue by stevetoza** [coollabsio/coolify#548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I add a new app github app  - the validation requires to add an exposed port

### Steps To Reproduce

Applications > Add > Fill out the details leave exposed port blank and press save 

### Version

3.6.0

**Comment by andrasbacsai** [comment]
The latest release v3.7.0, have the fix! Sorry about that!
