### ISSUE TITLE
[Feature]: Support Debian servers

### ISSUE THREAD

**Issue by xeruf** [coollabsio/coolify#550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Support Debian in the installer, it shouldn't need much changing.

### Why should this be worked on?

Debian is the de-facto standard server operating system since it is lighter on resources.

**Comment by Stargate-project** [comment]
this is needed ASAP

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
