### ISSUE TITLE
[Feature]: Flutter web builds

### ISSUE THREAD

**Issue by bliyscom** [coollabsio/coolify#551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Hi, with the current growth rate of the flutter framework, it would be nice to have automatic flutter web builds with ci/cd. I personally use flutter and appwrite for many high profile projects and since you've added appwrite which i love so much. It would be amazing to bring in flutter as well. The perfect trio. Coolify, appwrite and flutter. Sorry, thanks.

### Why should this be worked on?

Flutter is growing very fast.
More and more developers are using it.
Needless to list all it's great features which you might already know.

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
