### ISSUE TITLE
[Bug]: Always used port

### ISSUE THREAD

**Issue by LorisChennebault** [coollabsio/coolify#552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I modify the port exposed on an application, whatever the port entered I have the message: "Port xxxx is already in use".

### Steps To Reproduce

1. Go to an application
2. Modify the field "Exposed Port"
3. See the alert

### Version

3.7.0

**Comment by andrasbacsai** [comment]
I found the issue. Will be fixed in the next version!
