### ISSUE TITLE
[Bug]: Bulk add secrets trims MongoDB URI

### ISSUE THREAD

**Issue by gshudhanshu** [coollabsio/coolify#553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to Bulk add secrets, it trims MongoDB URI. To fix it I need to update the URI again.

This is the URI
mongodb+srv://shudhanshu:<password>@cluster0.aaaaaaa.mongodb.net/aaaaaaaaaaa-22?retryWrites=true&w=majority

It trims the URI like below
mongodb+srv://shudhanshu:<password>@cluster0.aaaaaaa.mongodb.net/aaaaaaaaaaa-22?retryWrites

Please when you get time have a look on this issue
Thank you!

### Steps To Reproduce

1) Create new NodeJS app
2) Connect GitHub repo
3) add Bulk secrets

### Version

3.7.0

**Comment by vasani-arpit** [comment]
Faced the same issue yesterday. Couldn't figure out why app is unable to connect to db. while DB was public itself and was being accessed from all other clients.

**Comment by andrasbacsai** [comment]
Thanks for the issue! It will be fixed in the next version!

**Comment by gshudhanshu** [comment]
Thank you sir!
