### ISSUE TITLE
[Bug]: Infinity Queued Build

### ISSUE THREAD

**Issue by kaname-png** [coollabsio/coolify#556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I don't know why this happens but sometimes the build process stays queued forever, and being the only queued process pending.

![image](https://user-images.githubusercontent.com/56084970/186232478-b601d488-c663-441f-915f-ef21f4673a16.png)

### Steps To Reproduce

1. Create an app
2. Start App
3. See how the build process enters an infinite queue

### Version

3.8.0

**Comment by vasani-arpit** [comment]
@andrasbacsai This happened to me once but I believe this will be hard to reproduce. In my case I pushed a commit which jump started the queue.

**Comment by execreate** [comment]
I believe I found a way to reproduce this issue with v3.8.1:
1. Start a build
2. Wait for ~5 seconds and cancel the build 
3. Schedule another build
4. Result: the build is queued, but never run. All subsequent builds are queued and never run too.

**Comment by andrasbacsai** [comment]
Thanks for the reproduction. 

I found the issue and figured out an excellent way to fix it and rethink the queue system. 

A fix is coming soon.

**Comment by andrasbacsai** [comment]
Released the fix in v3.8.2! Let me know if it still does not work!

**Comment by fupicat** [comment]
Unfortunately happened to me in the current version. :( Installed Coolify today. I tried completely uninstalling and reinstalling Coolify many times, but can't get any more builds to work. It seems like only the first build goes through, and then all other builds get stuck in queue. Cancelling or forcing deploy does nothing to help either.

![image](https://github.com/coollabsio/coolify/assets/36973337/b0353080-faf3-4615-b80f-83e1d8e5afdf)

I was trying to deploy [this SSR Astro app](https://github.com/fupicat/cbrptaeleicoes) as a test, through the Github app method, while running Coolify on an OrangePi 3 LTS (2GB RAM, 128GB storage) that runs Armbian 23.11.1. Would be happy to do more tests or provide more information if needed.
