### ISSUE TITLE
Make Editable Secrets Key (ENV)

### ISSUE THREAD

**Issue by Yurgeman** [coollabsio/coolify#56]
Sometimes there are a large number of keys. In this case, its meaning is not very clear. 
You have to delete and create a new one.

It would be more convenient to show the key value or make it possible to edit it

For example as here

![https://carabi-docs.storage.yandexcloud.net/Snimok_ekrana_2021_06_07_v_10_29_58_3589f0980d.png](https://carabi-docs.storage.yandexcloud.net/Snimok_ekrana_2021_06_07_v_10_29_58_3589f0980d.png)

or here

![https://carabi-docs.storage.yandexcloud.net/Snimok_ekrana_2021_06_07_v_10_29_29_eeeb271b30.png](https://carabi-docs.storage.yandexcloud.net/Snimok_ekrana_2021_06_07_v_10_29_29_eeeb271b30.png)

**Comment by andrasbacsai** [comment]
Not so hard to implement, so I will add it to the roadmap. Thanks for the suggestion!

**Comment by andrasbacsai** [comment]
I've implemented it in `v2.0.16`.
