### ISSUE TITLE
[Bug]: Glitchtip service email configuration not saved

### ISSUE THREAD

**Issue by execreate** [coollabsio/coolify#560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The "Save" button on the Glitchtip service configuration page does not save the Email settings

### Steps To Reproduce

1. Create a Glitchtip service
2. Edit Email settings on service configuration page
3. Click "Save" button on top
4. Reload the page
5. Check the Email settings

### Version

3.8.1

**Comment by Yurgeman** [comment]
also a problem

**Comment by andrasbacsai** [comment]
It will be fixed in the next version.
