### ISSUE TITLE
[Feature]: Add Dragonfly datastore

### ISSUE THREAD

**Issue by jub0t** [coollabsio/coolify#561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

"Dragonfly is a modern in-memory datastore, fully compatible with Redis and Memcached APIs. Dragonfly implements novel algorithms and data structures on top of a multi-threaded, shared-nothing architecture. As a result, Dragonfly reaches x25 performance compared to Redis and supports millions of QPS on a single instance." - [dragonfly](https://github.com/dragonflydb/dragonfly)

### Why should this be worked on?

Dragonfly is a popular datastore.

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
