### ISSUE TITLE
[Feature]: AlmaLinux 9 support

### ISSUE THREAD

**Issue by emirefek** [coollabsio/coolify#562]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

AlmaLinux is a CentOS Linux replacement for upstream RHEL base. AlmaLinux is backed by CloudLinux Inc. I think it'll be good to have RHEL support in this awesome repo. Because of CentOS foundation decided to kill "CentOS Linux" and create "CentOS Stream". Forks like AlmaLinux poped up and AlmaLinux is the the one which gets most donation and backings from industry.

### Why should this be worked on?

Because I like RHEL based distros more then Debian based distros. Pretty sure I'm not the only one. It feels like every thing works 
 nicer then Debian ones. AlmaLinux is a drop-in replacement for most people who are already using CentOS 7 or CentOS 8 it has strong community. I think it'll be great to see AlmaLinux support in this "Coolify" project.

**Comment by vasani-arpit** [comment]
I think only change we would have will be in initial setup script. Other than that rest of the things are on docker so that part should work as it is.

**Comment by MichalisDBA** [comment]
Yes been waiting for this. We use only AlmaLinux, now that CentOS gone to CentOS Stream. Hope you make it compatible with AlmaLinux too.

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
