### ISSUE TITLE
[Bug]: AARCH64/ARM64 Platform webdevops problem.

### ISSUE THREAD

**Issue by emirefek** [coollabsio/coolify#564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

While using React app I can't get the app working. I'm not sure what causes this problem but I think, webdevops packages are the problem. Because while I browsing their dockerhub page all their packages are only for AMD64 platform. When I run deploy command the NodeJS successfully builds React app then docker fails with command below:

FYI: Deploying normal NodeJS application works just find so I thought there is specific problem with webdevops container. Also deploying "Static" buildpack fails too. So I thought webdevops definitely problem on AARCH64

```
2022-08-26T09:38:24.509838569Z exec /entrypoint: exec format error
2022-08-26T09:38:24.969612788Z exec /entrypoint: exec format error
2022-08-26T09:38:25.497760174Z exec /entrypoint: exec format error
2022-08-26T09:38:26.218003816Z exec /entrypoint: exec format error
2022-08-26T09:38:27.350213893Z exec /entrypoint: exec format error
2022-08-26T09:38:29.267758508Z exec /entrypoint: exec format error
2022-08-26T09:38:32.822486012Z exec /entrypoint: exec format error
2022-08-26T09:38:39.545162233Z exec /entrypoint: exec format error
2022-08-26T09:38:52.657861176Z exec /entrypoint: exec format error
2022-08-26T09:39:18.574391134Z exec /entrypoint: exec format error
2022-08-26T09:40:10.077726698Z exec /entrypoint: exec format error
```

### Steps To Reproduce

1. Get and AARCH64/ARM64 server with Ubuntu 22.04 minimal installed. I got it from Oracle Free Tier.
2. use some random React App created with **create-react-app** script.
3. Sync it with cloud git service, I did with Github.
4. After linking repo with **Coolify** create new application in **Coolify** frontend.
5. During application creation process, select "React" as buildpack.
6. Used default settings, except FQDN and enabled DEBUG Logs. Then clicked Deploy button.
7. Build log completes without any errors.
8. Then application should give error, error pasted above. It's giving them repeatedly then shutdowns docker container.

### Version

3.8.1

**Comment by emirefek** [comment]
the webdevops team really don't wanna add ARM support to their containers. It'll be good to have official nginx container option while installing. Is "**Coolify**" team ok with these kinda changes on source?

**Comment by emirefek** [comment]
@andrasbacsai @vasani-arpit , fellow developers I really didn't understand why you are really did not make any comment on this issue, these webdevops docker containers really broking the features of you project. Please respond me and let's fix it together.

**Comment by vasani-arpit** [comment]
Our attention is divided into all the open tasks and PRs. While working some, others might get less of an attention from our side. 

Here are the next steps IMO:

a) If you need to use coolify immediately install it on shared/dedicated intel vCPU as that is tested and working properly for us
b) Make an PR. If you are able to find the issue then make a PR with the code change Andras will make sure it will get merged in upcoming version

**Comment by juanmarti81** [comment]
Is there any reason you can't change the image beng used from webdevops? those are the ones that are not working. I've reviewed their github and it's not likely they will add arm.

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
