### ISSUE TITLE
[Bug]: Secrets in Python Apps

### ISSUE THREAD

**Issue by mtgomes** [coollabsio/coolify#566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the application builds it gets the SQLALCHEMY_DATABASE_URL secret and tried to use it but I get an error:
`2022-08-26T15:27:54.424898255Z sqlalchemy.exc.ArgumentError: Could not parse rfc1738 URL from string '{"iv":"65daeebdcab0cad9<truncated>","content":"c4a8bca57f<truncated>"}'`
The community indicates that this error is due to the Connection String being invalid but I don't get why I get the JSON and not the "actual" string from the secrets.
Is there an issue with the secrets? I the code with my environment variables and it works fine.
Is there anything I can do.

FYI, today's (2022-08-26) update solved the deployments get stuck, but when it builds I'm getting the error.

### Steps To Reproduce

1. Setup a Secret
2. Read it in the python code using os.getenv("SQLALCHEMY_DATABASE_URL")
3. Error.

### Version

3.8.2

**Comment by andrasbacsai** [comment]
Next version will fix this. Sorry about it!
