### ISSUE TITLE
[Bug]: Environment variables do not work

### ISSUE THREAD

**Issue by ChikoShidori** [coollabsio/coolify#567]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I updated to the new version (`v3.8.2`) the environments just stopped working.
![image](https://user-images.githubusercontent.com/53100578/186943577-c76edd5f-dc14-4ea7-8cee-d5355336abe2.png)
![Q7tQMsWbiP](https://user-images.githubusercontent.com/53100578/186941588-0ede2188-b146-4d64-b2e2-c179f56a168a.png)
![image](https://user-images.githubusercontent.com/53100578/186941669-0f6c9c2b-3906-4fe4-b37c-b1ad127d5431.png)

### Steps To Reproduce

1. Create a new application
2. Set your environment variables
3. Run your application
4. See how the environment variables do not work

### Version

3.8.2

**Comment by andrasbacsai** [comment]
Next version will fix this! Sorry about it!
