### ISSUE TITLE
Not able to deploy

### ISSUE THREAD

**Issue by hrichiksite** [coollabsio/coolify#57]
Hi all,
I am facing a problem deploying coolify on ec2.

![image](https://user-images.githubusercontent.com/57860916/121001938-6bfbda00-c7a9-11eb-8c90-aef197198044.png)

help would be appreciated :)

**Comment by hrichiksite** [comment]
@andrasbacsai can you please check this? I have tried with 3 different VMs, all running Ubuntu 20.03 LTS, in azure, aws, and my home (pi4)

**Comment by hrichiksite** [comment]
Is it for everyone or just me?

**Comment by andrasbacsai** [comment]
Probably everyone. 😢

**Comment by hrichiksite** [comment]
```:( ```

when will things get fixed? I was excited to try coolify

**Comment by andrasbacsai** [comment]
Fixed in #51! You can give it a try now!

**Comment by andrasbacsai** [comment]
I'm closing this after we talked on Telegram. I will test `t2.micro` if it's capable of using it for Coolify.
