### ISSUE TITLE
[Feature]: Configure subpath

### ISSUE THREAD

**Issue by krsilas** [coollabsio/coolify#573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

It would be great if you could set the traefik path prefix for a specific application to run multiple apps on the same domain.
For example to add a blog under /blog/* to an existing configured website.

### Why should this be worked on?

Currently I don't see a way to add this manually without configuring a proxy in the main app.

**Comment by mabdullahabid** [comment]
You could run NGINX in a separate container and use a custom configuration there to route to other containers as you see fit? Not sure if it would be wise to put NGINX in front of TRAEFIK but might still work.

**Comment by andrasbacsai** [comment]
This could be achieved easily with Traefik. I will add it to one of the upcoming versions with [this](https://feedback.coolify.io/posts/95/map-multiple-ports-to-different-path) on.

**Comment by andrasbacsai** [comment]
It is available in v4.

I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
