### ISSUE TITLE
[Bug]:  Update button is not changing release

### ISSUE THREAD

**Issue by hdbham** [coollabsio/coolify#575]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Clicking the update button doesn't seem to rebuild app.
I tried reinstalling with wget and -r tag  also and I am still showing build 3.8.1 and the button remains despite notifs saying "update was reachable" and restart occuring.

### Steps To Reproduce

1. Run in local docker on Ubuntu
2. navigate to ip running instance
3. authenticate
4. click update

### Version

3.8.1

**Comment by andrasbacsai** [comment]
Can you please do a reinstall by executing `wget -q https://get.coollabs.io/coolify/install.sh -O install.sh; sudo bash ./install.sh -f
`?

Please also check what version of the image the script is trying to pull (it writes to the console).

**Comment by andrasbacsai** [comment]
Due to inactivity, I'm closing this issue. However, if the problem persists, please reopen the issue. Thanks!
