### ISSUE TITLE
[Bug]: Gitlab Source is created but not listed 

### ISSUE THREAD

**Issue by MrWazaby** [coollabsio/coolify#577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I tested coolify two weeks ago and didn't had this issue. So I think this is a recent bug.

It's happening on a fresh install. 

### Steps To Reproduce

1. Fresh install of coolify with only one user and one group
2. Go to GitSources
3. Add new GitSource
4. Select GitLab
5. Fill everything 
6. Save 
7. https://coolify.domain.tld/sources/{id} is working 
8. https://coolify.domain.tld/sources shows "No git sources found"
9. Trying to recreate the GitSource fail with "OAuthID already configured in Coolify."

### Version

v3.8.5

**Comment by andrasbacsai** [comment]
It will be fixed in the next version!
