### ISSUE TITLE
Coolify CLI

### ISSUE THREAD

**Issue by nikitakoschelenko** [coollabsio/coolify#58]
Start, stop, get current status and other via Coolify CLI. For example:
```
$ coolify start
[INFO] Starting Coolify...
[INFO] Coolify successfulity started at admin.example.com!

$ coolify start
[INFO] Starting Coolify...
[ERROR] Coolify already started!

$ coolify stop
[INFO] Stopping Coolify...
[INFO] Shutting down all app containers...
[INFO] Good buy!

$ coolify status
[INFO] Coolify already started at admin.example.com. Now running 2 apps and 1 database.
```

**Comment by ItzNeviKat** [comment]
> Great idea, but I do not see the benefit of a CLI. Why do you think it will be the benefit of a CLI tool like this?

Via this tool you can easily start and stop Coolify, which is now quite problematic.

**Comment by andrasbacsai** [comment]
Why do you would like to start/stop Coolify? If you don't stop it by hand, it should start automatically on server restart, for example.

I would like to understand the use-case a bit better.

**Comment by inluxc** [comment]
I could help you with this, build it in go, if you want.

**Comment by badlanguage** [comment]
> Why do you would like to start/stop Coolify? If you don't stop it by hand, it should start automatically on server restart, for example.
> 
> I would like to understand the use-case a bit better.

I would believe that it is useful when deploying Coolify locally for staging environments; beyond this even in production there may be use cases where there cases over port overlaps between multiple applications and a restart of Coolify may be necessary.

**Comment by warengonzaga** [comment]
I can see the benefits of having a CLI for this project. Having to rely on dashboard, it is more resource saver if we use CLI to control things using CLI like for example, deploying a new application or services using the CLI only. Which is in my opinion much faster to do it via dashboard.

Based on my experience with the dashboard, when I create a new local docker it just hangs, no info or pop-ups that the docker has been set up. So having a CLI would be more beneficial for some CLI users.

**Comment by themodernpk** [comment]
I absolutely agree with @warengonzaga, take the example of [Vercel CLI](https://vercel.com/docs/cli) , I can deploy apps at my will directly from my local terminal.

**Comment by andrasbacsai** [comment]
CLI for v4 is in progress.

I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
