### ISSUE TITLE
[Feature]: armv7 support

### ISSUE THREAD

**Issue by Mateleo** [coollabsio/coolify#580]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

armv7 support

### Why should this be worked on?

I'm currently running a Raspberry Pi 4 with a 32bits OS. Is there any way to install coolify on it ?

**Comment by andrasbacsai** [comment]
I think the only thing that prevents this is [Prisma](https://prisma.io). I’m compiling the new Prisma engine once a month to ARM, because they do not provide such binaries.

**Comment by Mateleo** [comment]
I see ! Thank you for the reply

**Comment by tjazsilovsek** [comment]
Is there any official way to use it on raspberry?
