### ISSUE TITLE
[Bug]: Automatic deployment is not working after update

### ISSUE THREAD

**Issue by gshudhanshu** [coollabsio/coolify#585]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hello Sir,
The automatic deployment stopped working after updating the coolify.
When you get time please check it

Thank you!

### Steps To Reproduce

Create a app using git repo
Enable automatic deployment
Commit the change in git repo

### Version

3.8.9

**Comment by andrasbacsai** [comment]
Can you please go to your `Git App` and verify that the webhooks are sent to your Coolify instance?

You can open your GitHub or GitLab by going to the `Sources` menu in Coolify and clicking on the `Change GitHub/GitLab App Settings`.

**Comment by andrasbacsai** [comment]
Due to inactivity, I'm closing this issue. However, if the problem persists, please reopen the issue. Thanks!
