### ISSUE TITLE
[Bug]: subfolder path issue with Python (Django)

### ISSUE THREAD

**Issue by Mateleo** [coollabsio/coolify#586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to build a django application, in a subfolder (/backend), I got this :
`[11:04:39.731] #8 [4/6] COPY ./backend//requirements.txt ./`

I sould not see a double slash but a single /

### Steps To Reproduce

Setup a django project with a custom subfolder as main directory
Then have a requirements.txt inside

### Version

3.8.9

**Comment by Mateleo** [comment]
I did my own research. There is indeed the creation of a double slash linked to the requirements.txt in the python.ts file.

However, the problem seems to go deeper. It is related to the generated dockerfile. It does not take into account the sub-folder, and generates an error.

To be sure I compiled my own dockerfile for my Django project. And this time the requirements.txt was taken into account

**Comment by andrasbacsai** [comment]
Due to inactivity, I'm closing this issue. However, if the problem persists, please reopen the issue. Thanks!
