### ISSUE TITLE
[Feature]: Rollback to specific commit

### ISSUE THREAD

**Issue by ThallesP** [coollabsio/coolify#589]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Ability to rollback to a specific commit if something isn't working right or to just experiment previous code version of the application.

### Why should this be worked on?

I've had a problem with one of my application features where it wasn't working and I didn't have the time to fix it right now so I wanted to remove it, but found no way in the Coolify dashboard to rollback to a previous commit.

**Comment by jamesbruice** [comment]
+1

**Comment by thrzl** [comment]
i'd also love to see this, i'd appreciate it hugely. this is currently the only issue i have at all with coolify, everything else is wonderful!

**Comment by ThallesP** [comment]
Feature got merged! 🎉
