### ISSUE TITLE
[Feature]: 2FA Login

### ISSUE THREAD

**Issue by dm94** [coollabsio/coolify#591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Have the option of requiring an OTP code to connect to the panel.

### Why should this be worked on?

It would greatly improve security

**Comment by vasani-arpit** [comment]
You mean 2FA?

**Comment by dm94** [comment]
Yes

**Comment by themarkwill** [comment]
@vasani-arpit  @andrasbacsai  
Hey! I can work on that if no one is working on it already! 👍

**Comment by rinshadka** [comment]
> @vasani-arpit @andrasbacsai Hey! I can work on that if no one is working on it already! 👍

@themarkwill  did u able to start working on it

**Comment by andrasbacsai** [comment]
It is available on v4.

I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
