### ISSUE TITLE
[Bug]: There is no php 8.1 Support ?

### ISSUE THREAD

**Issue by ilikewebsite** [coollabsio/coolify#593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In laravel 9 with certen dependencies, php 8.1 requied, It's not there, It's not usable, Please give option to add it or Please add support of multiple versions in laravel application.

### Steps To Reproduce

Laravel Application

### Version

3.9.0

**Comment by andrasbacsai** [comment]
Add PHP 8.1 to the next version!
