### ISSUE TITLE
[Bug]: Automatic MR preview is broken 

### ISSUE THREAD

**Issue by MrWazaby** [coollabsio/coolify#595]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The webhooks from Gitlab are failing on `Merge request events`. 

The error in the webhook is the folowing :  
````
{"status":500,"message":"Argument pullmergeRequestId: Got invalid value 18 on prisma.createOneBuild. Provided Int, expected String or Null.\n"}
````

18 is the Gitlab iid for the Merge request. 

### Steps To Reproduce

1. Create an app from Gitlab
2. Enable the MR preview 
3. Create a MR in Gitlab
4. Check the webhook logs in Gitlab

### Version

v3.9.0

**Comment by andrasbacsai** [comment]
v3.9.2 will fix this!
