### ISSUE TITLE
[Bug]: Plausible faills to start

### ISSUE THREAD

**Issue by garth** [coollabsio/coolify#597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

try to start plausible for the first time:

Command failed: DOCKER_BUILDKIT=1 DOCKER_HOST="unix:///var/run/docker.sock" docker compose -f /tmp/build-sources/plausibleanalytics/cl7qhouqs10079e1mc0990d7am/docker-compose.yaml pull service "cl7qhouqs10079e1mc0990d7am-postgresql" refers to undefined volume cl7qhqf4k10864e1mcvndmp8e3-postgresql-data: invalid compose project 

I have a postgres db installed and started already.

### Steps To Reproduce

click start icon

### Version

3.9.1

**Comment by andrasbacsai** [comment]
The next version will fix it!
