### ISSUE TITLE
[Bug]: GlitchTip service cannot send email

### ISSUE THREAD

**Issue by keizie** [coollabsio/coolify#599]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

GlitchTip logs `ValueError: EMAIL_USE_TLS/EMAIL_USE_SSL are mutually exclusive, so only set one of those settings to True.` if sending email tried.

```shell
$ docker exec -ti 56e530843797 /bin/bash
$ export | grep EMAIL
declare -x EMAIL_USE_SSL="false"
declare -x EMAIL_USE_TLS="true"
```

It should be `True` or `False` in python.

```python
$ python
>>> a="true"
>>> b="false"
>>> print('y') if a and b else print('n');
y
>>> b=False
>>> print('y') if a and b else print('n');
n
>>> b=True
>>> print('y') if a and b else print('n');
y
```

`startGlitchTipService` should convert `true` or `false` string into `True` or `False` primitive.

https://github.com/coollabsio/coolify/blob/d3a1bbc3d0a7e93f821f4cbe801310e341fae5dc/apps/api/src/lib/services/handlers.ts#L1982-L1983

### Steps To Reproduce

1. Create GlitchTip service
2. login
3. Add notification email address
4. Send confirmation email fails
5. See log in coolify
6. `ValueError: EMAIL_USE_TLS/EMAIL_USE_SSL are mutually exclusive, so only set one of those settings to True.`

### Version

3.9.3

**Comment by andrasbacsai** [comment]
Nice catch! Fixing in the next version!

**Comment by keizie** [comment]
```
$ docker ps | grep glit | grep start | awk '{print $1}' | xargs -I"{}" -o docker exec -ti {} /bin/bash -c 'printenv | grep EMAIL_USE'
EMAIL_USE_TLS=True
EMAIL_USE_SSL=False
```
does not work

```
$ docker ps | grep glit | grep start | awk '{print $1}' | xargs -I"{}" -o docker exec -ti {} /bin/bash -c 'printenv | grep EMAIL_USE'
EMAIL_USE_TLS=1
EMAIL_USE_SSL=0
```
(set by Secrets) not work too

https://glitchtip.com/documentation/install `docker-compose.sample.yml` file set EMAIL_URL.
So EMAIL_URL also tried but still failed.
I suspect that EMAIL_USE_TLS and EMAIL_USE_SSL remains after overwrite by EMAIL_URL.
(https://gitlab.com/glitchtip/glitchtip-backend/-/blob/master/glitchtip/settings.py#L541)

**Comment by href** [comment]
I don't know if I'm reading this right, but I think you could either use `None` instead of `False`, or unset the variable that is false: https://sourcegraph.com/github.com/django/django/-/blob/django/core/mail/backends/smtp.py?L36-49#tab=references

I think this issue should be re-opened, from what I can tell you can't configure GlitchTip to use e-mail at this point.

**Comment by href** [comment]
@andrasbacsai may I ask you to re-open the issue? I can also create a new one. I can reproduce this quite easily:

1. Create a new GlichTip instance.
2. Configure e-mail (any combination of flags will fail, whether on or off).
3. Login using the generated user/password.
4. Change the user's e-mail address (this triggers a confirmation e-mail that fails).

I think GlichTip is especially good if it sends alerts about things that go wrong, without it, it is
 a lot less useful.

My guess is that it's not a problem of the variable format (`1`, `True`, `None`), but that the variable exists in the first place. It should likely be unset if it is meant to be off.

**Comment by andrasbacsai** [comment]
The latest template based GlitchTip works now.

**Comment by href** [comment]
I assume this has not been released yet? I tried a new instance in 3.11.9, and I still get the following error:

```
2022-11-16T07:03:16.148142494Z ValueError: EMAIL_USE_TLS/EMAIL_USE_SSL are mutually exclusive, so only set one of those settings to True. 
```

Maybe someone else can confirm, to ensure I'm not doing something wrong.

**Comment by andrasbacsai** [comment]
Unfortunately, You probably need to recreate GlitchTip service, because a lot of things changed with that. The differences between the hardcoded and template based are huge.

**Comment by ljnsn** [comment]
Is this supposed to be solved? I still get the same error on 3.12.31. EMAIL_USE_TLS is "enabled" and EMAIL_USE_SSL is "disabled" in the config.

**Comment by martijnmichel** [comment]
we also get the same problem on latest coolify

**Comment by martijnmichel** [comment]
@andrasbacsai please reopen the issue.

**Comment by codesalatdev** [comment]
Without looking much into it, https://github.com/coollabsio/coolify/blob/v3/apps/api/src/lib/services/serviceFields.ts#L627 is a duplication of the SSL setting when it should probably say TLS.

**Comment by martijnmichel** [comment]
> Without looking much into it, https://github.com/coollabsio/coolify/blob/v3/apps/api/src/lib/services/serviceFields.ts#L627 is a duplication of the SSL setting when it should probably say TLS.

ive created a PR updating the specified line: https://github.com/coollabsio/coolify/pull/1147

**Comment by grstreten** [comment]
Can confirm this issue is still reproducible in [v3.12.37](https://github.com/coollabsio/coolify/releases/tag/v3.12.37)
