### ISSUE TITLE
[Bug]: Databases couldn't be turned public

### ISSUE THREAD

**Issue by carvalholeo** [coollabsio/coolify#600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to turn a database public, Coolify (Treafik, I guess) assigns the same port for every database (in my case, it's port 9000).

Now, there's a Postgres database attached to this port, and I'm not able to access any other database. For some reason, there's only one Destination/Network that I can create databases and turn databases public (and connect them from my computer). Every other  Destination don't open DBMS public ports.

I don't know when this issue has started neither it's be related with #535.

### Steps To Reproduce

1. Go to Databases
2. Create a new relational database
3. Start the server and turn it in public mode. It should work
4. Repeat steps 1-3. But now, it shouldn't work

### Version

3.9.3

**Comment by andrasbacsai** [comment]
Found and fixed the issue in the next version.
