### ISSUE TITLE
[Feature]: allow more general configuration of the docker engine

### ISSUE THREAD

**Issue by w4tsn** [coollabsio/coolify#605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Hey there :wave: 

I think Coolify does not have to bother with the docker engine / socket configuration variables. This is an environment / host thing which should be configured outside of Coolify and should not be it's concern.

### Why should this be worked on?

Because A) I think this is a low hanging fruit and B) e.g. currently I can't provide a simple TCP socket connection which would be possible if Coolify would not override the DOCKER_HOST env variable through code. The way it's currently implemented interferes with common docker configuration and reduces the feature-set of the docker CLI.

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
