### ISSUE TITLE
[Bug]: MR Previews not showing in the Previews Section

### ISSUE THREAD

**Issue by FrinkMan** [coollabsio/coolify#608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I commit changes to an active merge request, a build is executed for the merge request, but nothing appears under the previews pane. See below screenshots.

![image](https://user-images.githubusercontent.com/43939360/189174911-6d081a65-b05e-4601-970e-9bcd250eaa15.png)
![image](https://user-images.githubusercontent.com/43939360/189175019-45ea9e7e-20c9-47bd-a7ef-ec92259cb610.png)

### Steps To Reproduce

1. Create an application with GitLab as a source (self-hosted instance in my case)
2. Choose the appropriate options for the application (NodeJS in my case)
3. Deploy the application, and verify that visiting it works (it does for me)
4. Create another branch, start a merge request and push a commit to the merge request

Coolify will build the merge request, but it won't place it in the previews pane.

### Version

3.10.0

**Comment by andrasbacsai** [comment]
I think I know what’s going on. The PR builds failed to start and that is why is not shown. 

I will fix / improve it.
