### ISSUE TITLE
github auth fails with error (intermediate value).body.filter is not a function

### ISSUE THREAD

**Issue by jdbrice** [coollabsio/coolify#61]
All install steps proceed successfully. Then site is visible. 
After clicking the "login with github" button, the github auth dialog pops up, after entering user/pass I get the error:
```
{"error":"(intermediate value).body.filter is not a function"}
```

As far as I can tell I setup the github app correctly (with secrets and keys etc.)
From then on the "login with github" button immediately goes to that error and the coolify app never proceeds.

**Comment by andrasbacsai** [comment]
It looks like there is an error getting your email address from GitHub API. 

Can you please double-check if the Github App you configured has `read-only` access to `Email Addresses` under the `User permissions` section?

**Comment by andrasbacsai** [comment]
I faced the same issue in case of I reinstalled Coolify without deleting the database persistent volume. Did you do something similar, maybe?

**Comment by andrasbacsai** [comment]
Due to inactivity, I'm closing this issue. However, if the problem persists, please reopen the issue. Thanks!

**Comment by loic-roux-404** [comment]
I have the same issue, look like the email thing doesn't fix.

I'm trying to delete db data volume and retry login when i get more network speed.

**Comment by loic-roux-404** [comment]
```json
{"error":"{\"status\":401,\"body\":{\"message\":\"Requires authentication\",\"documentation_url\":\"https://docs.github.com/rest/reference/users#list-email-addresses-for-the-authenticated-user\"}}"}
```

Work ok on postman with Bearer header, it can do the job as a solution, i can open a PR if you want
