### ISSUE TITLE
[Bug]: "latest" Umami uses outdated package URL

### ISSUE THREAD

**Issue by jonahgoldwastaken** [coollabsio/coolify#613]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I set up an Umami service, I expect it to download the latest version from the package URL. After looking around a bit I found out they stopped releasing new versions at ghcr.io/mikecao/umami and instead started releasing at ghcr.io/umami-software/umami. Could this new URL be added? Thanks!

### Steps To Reproduce

1. Add a Umami service.
2. Start it.
3. Log in to service.
4. Look at version number in bottom left (should state 1.33.1) - You'll also probably notice the update notification at the top of the screen.

### Version

3.10.1

**Comment by Stargate-project** [comment]
To get the latest features, simply do a pull, install any new dependencies, and rebuild:

```
git pull
yarn install
yarn build
```

maybe these commands can be added to the settings page

**Comment by jonahgoldwastaken** [comment]
@Stargate-project a little bit below those commands it tells you how to update the docker container, which is what is being used inside of Coolify. I'd much rather prefer the versioning system Coolify already has in place instead of jerry-rigging my own solution and having to reset everything when something goes wrong

**Comment by andrasbacsai** [comment]
It looks like umami changed the repository of their docker image. In the latest version, v3.10.2, I fixed it.
If you stop/start it, it will pull the latest version.
