### ISSUE TITLE
[Feature request] Ability to access with just IP

### ISSUE THREAD

**Issue by xialvjun** [coollabsio/coolify#62]
Sometimes we use things like coolify in local area network rather the public network.

So we don't need a domain name and https.

But now domain name and https is required to install coolify.

**Comment by andrasbacsai** [comment]
It is available in the new (v2) version.

A fresh installation is required as v2 is not compatible with v1.

**Comment by andrasbacsai** [comment]
Coolify is usable without a domain name, just do not set it in the settings menu. 

But for applications/services, you must set domain and DNS entry (in advance).
