### ISSUE TITLE
[Bug]: Minio API URL is not correctly configured

### ISSUE THREAD

**Issue by narduin** [coollabsio/coolify#627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi,

upon installing minio, I set the console url to `https://console.domain.tld` and the API url to `https://api.domain.tld`
When I try to login from the console gui, I get this error: `S3 API Requests must be made to API port.`

Looking at the logs inside coolify I see that the API's URL is wrong:
```log
MinIO Object Storage Server
Console: https://console.domain.tld 
API: https://console.domain.tld 
Status: 1 Online, 0 Offline. 
Documentation: https://docs.min.io
```

It seems like the API url setting is not properly passed during the install process.

### Steps To Reproduce

1. add new minio service
2. set console and api url
3. start the service
4. try to connect from the console url

### Version

3.10.4

**Comment by andrasbacsai** [comment]
The next version will fix this!
