### ISSUE TITLE
[Bug]: Changing PHP Version

### ISSUE THREAD

**Issue by ilikewebsite** [coollabsio/coolify#629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Toggle PHP Version, 
As per last request you guys updated php version till 8.2,  But there is issue when deploying it's just automatally selecting v8.2 only not able to toggle. 

I found this in Laravel, Havn't checked for any other.
Please look into it.

Thanks

### Steps To Reproduce

Select Create Application
Select Laravel 

### Version

Latest

**Comment by andrasbacsai** [comment]
It will be fixed in the next version!
