### ISSUE TITLE
[Feature]: Use Coolify as a reverse proxy

### ISSUE THREAD

**Issue by poberbeck** [coollabsio/coolify#631]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

A service witch provides the ability to create a reverse proxy for an application running on the server but is **not** managed by Coolify.

### Why should this be worked on?

If this feature exists, it would be easy to run applications or services witch are currently not supported by Coolify.

**Comment by jamesbruice** [comment]
this would be great to run a mail server alongside

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.
Also, this feature is avaiable in v4.

Thanks for your understanding.
