### ISSUE TITLE
[Feature]: Health endpoint check

### ISSUE THREAD

**Issue by tygore587** [coollabsio/coolify#633]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I just searched old issues and there is a similar issue with #289 which is not tagged as `[Feature]`. So i wanted to create it again :) 

I wanted to configure some health endpoint which automatically restarts the application if the applicaton doesn't return a `200` anymore.

### Why should this be worked on?

It will be useful if for some reason an application looses connection to the database or something and reports a non healthy condition.

Also it could also result in another feature, where you can check while deploying if an application is ready before stopping the old container. I had some containers which takes like 2-3 minutes to start before the endpoints are available.

**Comment by andrasbacsai** [comment]
It is available in v4.

I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
