### ISSUE TITLE
[Feature]: Custom reverse proxy configuration per app

### ISSUE THREAD

**Issue by Dolu89** [coollabsio/coolify#636]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

On app installation (pre configured app, docker, from git, ...), having the possibility to customize reverse proxy configuration

### Why should this be worked on?

Some apps could require a custom configuration on the reverse proxy, like distributing SSL on demand (i'm using this with caddy today https://caddyserver.com/docs/caddyfile/directives/tls#on_demand, I don't know the similar configuration on traefik yet)

**Comment by koch-crsd** [comment]
@andrasbacsai any information/feedback on this? IF and when will it be possible to change proxy configurations on app-level? 

Is there a current workaround for example on how I can add a "X-REAL-IP" or "X-FORWARDED-FOR" header for one of my apps? Cause I would need that for express ip restrictions....

Thanks much for your valued feedback! :)

**Comment by andrasbacsai** [comment]
This will be supported in v4 soon.


I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
