### ISSUE TITLE
[Bug]: Gitlab (self-hosted) source 

### ISSUE THREAD

**Issue by ChechaValerii** [coollabsio/coolify#638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When Git Sources is Gitlab (self-hosted), list of projects is empty. 

Configuration:
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/11835320/192476484-c41bc82f-8958-466d-9825-5e27ccb2ef5c.png">

Select repository page:
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/11835320/192476598-2e8e292d-1a19-4f39-9036-7439f660447b.png">

### Steps To Reproduce

1. Go to Dashboard.
2. Click Create Application
3. Click Git App -> GitLab
4. Select a Repository is empty page

### Version

3.10.8

**Comment by andrasbacsai** [comment]
Found the issue! Next version will have a fix for this.

**Comment by andrasbacsai** [comment]
Could you please check if it's working with the new version?

**Comment by ChechaValerii** [comment]
@andrasbacsai Work good! Thank you!
