### ISSUE TITLE
[ui/ux]: Icons in left sidebar have disappeared

### ISSUE THREAD

**Issue by juanmiguelguerrero** [coollabsio/coolify#639]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

In the demo, I don't see the icons that used to appear in the sidebar... (Applications, Services, Databases, Git Sources and Destinations)

Now everything is more confusing with a dashboard that mixes everything up. 

The idea of the search engine and status filters is very good. But removing these icons makes everything less intuitive.

### Why should this be worked on?

Return to the interface we had until now with the icons.

**Comment by andrasbacsai** [comment]
The reason I cleaned up the sidebar is to make space for other things coming to Coolify.

I've added a new bar on top of the search input field. It will make a similar feeling as before.

What do you think?


![image](https://user-images.githubusercontent.com/5845193/192711016-9b5dadfc-6bf3-410a-b208-6153d98cd8ea.png)
![image](https://user-images.githubusercontent.com/5845193/192711390-70fa1bed-d5ab-4b3d-bddd-a42646577ea5.png)
![image](https://user-images.githubusercontent.com/5845193/192711439-71fa062c-022f-408e-b1ba-7393d9dafba4.png)
