### ISSUE TITLE
[Bug]: Loading app from git repo with uppercase letters does not work

### ISSUE THREAD

**Issue by apaudel96** [coollabsio/coolify#644]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Pretty self explanatory,
When creating an app from github, the url is turned to lower case.
It seems github urls are case sensitive and so does not work.

### Steps To Reproduce

Add an application.
Load a repo which has capital letters in the url.
App fails to deploy because url has been turned to lower case.

### Version

3.10.7

**Comment by andrasbacsai** [comment]
Can you please give an example? I tried with one of my repositories (https://github.com/coollabsio/nodejs-examplE), but it is imported well.

**Comment by apaudel96** [comment]
I'm sorry, it looks the case sensitive is an issue with branches only.
For example: the main branch for
[https://github.com/apaudel96/test-fastapi-tasks/tree/DemoBranch](https://github.com/apaudel96/test-fastapi-tasks/)
works fine, but the branch
[https://github.com/apaudel96/test-fastapi-tasks/tree/DemoBranch](https://github.com/apaudel96/test-fastapi-tasks/tree/DemoBranch)
does not work.

**Comment by andrasbacsai** [comment]
Forgot to update this, but it has been fixed.
