### ISSUE TITLE
[ui/ux]: AIM, Accounts pagination  

### ISSUE THREAD

**Issue by ChechaValerii** [coollabsio/coolify#646]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Implement pagination inside AIM -> Account list.
I have invited 29 account and thats seems ugly, maybe will be good implement search and pagination for this list? 
The same at Team Members.

### Why should this be worked on?

My team can be more then 100 peoples, and I think thats will be hard to manage it...

**Comment by andrasbacsai** [comment]
Great point! That part was changed ages ago. I will prioritize it!

Raw draft in progress version:
![image](https://user-images.githubusercontent.com/5845193/193048801-bb08791b-e987-4725-b649-eccad6d57bec.png)

**Comment by andrasbacsai** [comment]
It is released in the latest version.
