### ISSUE TITLE
[Feature]: MongoDB Replica set

### ISSUE THREAD

**Issue by nodeteamdev** [coollabsio/coolify#649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Could you implement option for RUN MongoDB in Replica Set mode? 

### Why should this be worked on?

MongoDB support ACID (transaction) operations but only in replica set mode. [MongoDB transactions](https://www.mongodb.com/docs/manual/core/transactions/)

**Comment by cbillinis** [comment]
I am also interested in this as it will allow it to work with prisma

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
