### ISSUE TITLE
[Feature]: Team Secrets

### ISSUE THREAD

**Issue by harshzalavadiya** [coollabsio/coolify#650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently Secrets are only per application it will be nice to have team/environment based secrets as well

### Why should this be worked on?

This are especially useful when you have shared secret among full environment for example artifactory credentials for java applications / private package from npm etc. or shared secret decryption token / database url etc.

**Comment by arunrdd** [comment]
As it might take time to implement this, in the meantime it would be great to have the ability to export secrets of an application as a `.env` file. This will make it easy to copy the secrets from one app to other if they have lots of common env variables.

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
