### ISSUE TITLE
[Bug]: Unable to setup on Ubuntu 22.04 LTS (ARM)

### ISSUE THREAD

**Issue by harshzalavadiya** [coollabsio/coolify#651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I tried setting up coolify on ubuntu 22.04 LTS on macbook pro m1 (ARM) using [multipass](https://multipass.run/).

auto docker installation setup failed since multipass can also auto setup docker I went with that and then followed installation instructions but below error comes when I run `docker logs <coolify_image_name>` 

```
ubuntu@primary:~$ docker logs dreamy_borg
unknown shorthand flag: 'd' in -d
See 'docker --help'.

Usage:  docker [OPTIONS] COMMAND

A self-sufficient runtime for containers

[clipped irrelevent help command output]

Invalid Plugins:
  compose     failed to fetch metadata: fork/exec /root/.docker/cli-plugins/docker-compose: exec format error

Run 'docker COMMAND --help' for more information on a command.
```

also it will be helpful if there's documentation on how to setup local development instance :)

### Steps To Reproduce

1. Install multipass (works anywhere macOS, linux etc.)
2. launch multipass docker instance `multipass launch docker --cpus 4 --disk 40G --mem 8G --name primary`
3. do `multipass shell` and try to run coolify install script
4. says application started successfully but docker image does not start

```
ubuntu@primary:~$ docker ps -a
CONTAINER ID   IMAGE                        COMMAND                  CREATED          STATUS                        PORTS     NAMES
0b31a27bb035   coollabsio/coolify:3.10.13   "docker-entrypoint.s…"   53 minutes ago   Exited (125) 53 minutes ago             dreamy_borg
```

### Version

3.10.13

**Comment by Rurik19** [comment]
same error on ubuntu 23.04 ARM

here error text

`docker: Error response from daemon: error creating aufs mount to /var/lib/docker/aufs/mnt/5a88d500fb1732565eeb32d83a9f568d937ea05ab327af67b02e8068d67c57d5-init: mount target=/var/lib/docker/aufs/mnt/5a88d500fb1732565eeb32d83a9f568d937ea05ab327af67b02e8068d67c57d5-init data=br:/var/lib/docker/aufs/diff/5a88d500fb1732565eeb32d83a9f568d937ea05ab327af67b02e8068d67c57d5-init=rw:/var/lib/docker/aufs/diff/9eb889ae2685d05b65472a4662d41c11a94d52a3824298ee526344534b6404f5=ro+wh:/var/lib/docker/aufs/diff/36a011aeb8833f50c9aed76eb19743b9a3e6614ba22774c797d89e733e36e8b9=ro+wh:/var/lib/docker/aufs/diff/d90a83ea8cf4741d2df89784c839136b4e0478d7fda1a9b68370b4541d9812c9=ro+wh:/var/lib/docker/aufs/diff/0d5ac2dc2e824dc5ce1d6c7c7281bda11d4c0d4acc71d4bcbadc528c49280bd1=ro+wh:/var/lib/docker/aufs/diff/1f3ef137b5f86ef5f06398981a41fd46b8b85614afc9f012a8f8ce1672d34177=ro+wh:/var/lib/docker/aufs/diff/072866359d9bd733696ec26c77bc2fec58f358d3729d3d70eae0566ce364790a=ro+wh:/var/lib/docker/aufs/diff/f932d5a6eebb502327b8bff7911c0d82ea12078e21d896c4d45a7d2be325b96c=ro+wh:/var/lib/docker/aufs/diff/369952ef13940f736feddf02a15ca58bc9a8c8d3fd710561b4f28a1dc3e50968=ro+wh:/var/lib/docker/aufs/diff/2bf5bd0ac813e4f54a9540e10f537df73a1cb9f1ea57ed2cf700b841902d7e6f=ro+wh:/var/lib/docker/aufs/diff/47a291c7eb5797aa549e7c0dd3cd55653482e055eac3c964edcd32b5c1eb171b=ro+wh:/var/lib/docker/aufs/diff/50f48311a01ff4046ff646cbc9a7713d4522c30f76fc28e7944b4d87925ffb0f=ro+wh:/var/lib/docker/aufs/diff/0c8fe33ecdeb21074cd07c8bb6ac258a55347069eec159dc7ada069574496dc9=ro+wh:/var/lib/docker/aufs/diff/f5c616a670c19579677c8e6d46f2824dac0767785da71f4cad28cc11f080e14a=ro+wh:/var/lib/docker/aufs/diff/59d6e638df538d8d944364e5dc894c9d91471dcbe3f8c379cd6ea1ad254ae121=ro+wh:/var/lib/docker/aufs/diff/6abb741624e979943cf7cf1867783c3b2b93d6222cc96a35324ad785ae12c504=ro+wh:/var/lib/docker/aufs/diff/b76b0830a1c8fc87618e4e9d610be42e73eeda18faf42c269008199b179a30fb=ro+wh:/var/lib/docker/aufs/diff/bf200666062995aa7b0e3c8ae3541f016d54b11eaebcb4b4c1e2e0ebbcb74c08=ro+wh:/var/lib/docker/aufs/diff/c810312c8595498ae6c1fa7a0c535f71d7c2bcb2fc868cd608969dc62c186c05=ro+wh:/var/lib/docker/aufs/diff/dedb36438235de52423e17121a25fa90d94d727bfeb2741837d99f3fa92a7503=ro+wh:/var/lib/docker/aufs/diff/e83749adc391638e9a293c2dce812efe39da3afd40b42709f9d8a1421ff959b1=ro+wh:/var/lib/docker/aufs/diff/57844bdabf4da6c395a666e8d870fc66abb276ee5462a3045ed9dcb17d5c766e=ro+wh:/var/lib/docker/aufs/diff/268be4ba858deeeb12e5bec92187acf9ae14df91674d1dfdaf18b89e7a211794=ro+wh:/var/lib/docker/aufs/diff/e45167129a77683ea015341595c74507e34ffd1bbc3996855a92a36acf46f1f6=ro+wh:/var/lib/docker/aufs/diff/7fb1ee5931fc5c887275c790b42971a211d71d53b95eb7e33f66186c987f6dd1=ro+wh:/var/lib/docker/aufs/diff/58fc30277d93f10466a6cd7d219ed965e033f4eea45043cbee4ff996596968da=ro+wh:/var/lib/docker/aufs/diff/73cea82cba0db80d44c2870e2485328d9865b8d96c514e2c0b8eec36500bf486=ro+wh:/var/lib/docker/aufs/diff/24ae1d002d5cb15650edb19c087597184a5debcd856e2fb95d9f3af4af1c3f04=ro+wh,dio,xino=/dev/shm/aufs.xino: invalid argument.
See 'docker run --help'.
install.sh exited unexpectedly with status: 125`

**Comment by andrasbacsai** [comment]
Due to inactivity, I'm closing this issue. However, if the problem persists, please reopen the issue. Thanks!
