### ISSUE TITLE
[Bug]: Meilisearch data persistence

### ISSUE THREAD

**Issue by c43721** [coollabsio/coolify#652]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

When trying to persist data between restarts (such as that new 0.29 release from meili 🚀🚀) it does not keep the data that I have entered.

![image](https://user-images.githubusercontent.com/55610086/193706584-fd52cc6a-20e7-46cc-ae8e-cd32c16a8cdc.png)

On the docs, it would appear otherwise- the data should by default be persisted. Trying to configure Meili to a custom mount + add it in the storage layer doesn't appear to work either.

### Steps To Reproduce

Create a new Meilisearch service
Give it a URL, and (importantly) set the environment to `development` (MEILI_ENV=development)
Go to the URL and see that you have no Indexes created
![image](https://user-images.githubusercontent.com/55610086/193706865-748dd520-85c9-4674-9646-aa873221ce99.png)

POST to `/indexes` with some index body, you can use
```json
{
  "uid": "testssss",
  "primaryKey": "id"
}
```
Refresh dashboard, see the index is created
Restart meili. Notice the data is lost (no index is appearing)

### Version

3.10.13

**Comment by andrasbacsai** [comment]
Uh, it looks like they changed the path of the data. It was `/data.ms`, but now it is `/meili_data/data.ms`. That is bad. 

I'm fixing this in the next version.
