### ISSUE TITLE
[Bug]: Automatic Deployment not working

### ISSUE THREAD

**Issue by dondonjang** [coollabsio/coolify#659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

recently Automatic Deployment is not working

![스크린샷 2022-10-05 오후 10 26 10](https://user-images.githubusercontent.com/46506126/194073155-8cfda3ca-3bf1-4a01-be08-c55231240b84.png)
![스크린샷 2022-10-05 오후 10 26 19](https://user-images.githubusercontent.com/46506126/194073166-ca8760cd-ee06-47a8-b1c6-cb71bb73d28a.png)

### Steps To Reproduce

merged in github
build is no build

### Version

v3.10.14

**Comment by andrasbacsai** [comment]
GitHub Webhooks are down.

![image](https://user-images.githubusercontent.com/5845193/194074261-7852fc6c-1b0c-4e68-80e1-92df73075992.png)

**Comment by dondonjang** [comment]
ok... i will retest on working web hook...
I changed github apps
