### ISSUE TITLE
[Bug]: Dockerfile deployment not showing errors

### ISSUE THREAD

**Issue by Fronix** [coollabsio/coolify#660]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After updating to v3.10.14 dockerfile deployment logs seems to have been broken. I had configured the base directory wrong, which did not show up, which made me to believe that it was a Coolify problem.

![image](https://user-images.githubusercontent.com/631180/194075883-ad0a35a2-fcd3-49dc-bc54-10211b93358c.png)

### Steps To Reproduce

1. Setup application using a Dockerfile with incorrect basedirectory
2. Try building the application
3. Build fails with no errors clear errors to what went wrong

### Version

3.10.14

**Comment by andrasbacsai** [comment]
It has been fixed.


Due to inactivity, I'm closing this issue. However, if the problem persists, please reopen the issue. Thanks!
