### ISSUE TITLE
[Bug]: Verify Remote Docker Engine

### ISSUE THREAD

**Issue by bluryar** [coollabsio/coolify#665]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://github.com/coollabsio/coolify/blob/ef40f7349e04c631fb932117438f91a82cad0aec/apps/api/src/routes/api/v1/destinations/handlers.ts#L207

As shown above, I don't think there is anything here that should be getting the port settings.

When I call `POST /api/v1/destinations/xxxx/verify`, I get:
````
{
    "status": 500,
    "message": "Command failed: DOCKER_HOST=ssh://bluryar@xxx docker network ls --filter 'name=cl8xcjfy2000037675pw1kntd' --no-trunc --format \"{{json .}}\"\nerror during connect : Get \"http://docker.example.com/v1.24/networks?filters=xxxxadad\": command [ssh -l bluryar -- xxx docker system dial-stdio] has exited with exit status 255, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=ssh: connect to host localhost port 9000: Cannot assign requested address\r\n\n"
}
````

In addition, I can't even create the Remote Docker Engine normally, because the web front end of the control panel passes the port parameter type into a string, and reports an error:
````
message
:
"Argument remotePort: Got invalid value '22111' on prisma.createOneDestinationDocker. Provided String, expected Int or Null.\n"
status
:
500
````

The problem I think is that the program assumes that the port is 22.

Combining these two problems: I think the problem here is that the server does not handle the case of parameters other than port 22, and the front end does not handle the case that when the user enters a non-default value, the parameter type becomes a string because of the text input box

### Steps To Reproduce

1. go to Dashboard
2. click `create new resource`, select `Destination`
3. click `remote docker`
4. [the first error] feel free to add a remote server with a username other than root and a port number other than 22.

1. use `postman` to resend the correct request to *the first error*
2. [the seconrd error] than try to verify remote docker on the dashbord.

### Version

3.10.14

**Comment by vasani-arpit** [comment]
+1
getting the same issue on my side as well. The problem is error message changes after first try 😢

**Comment by loagencydev** [comment]
any updates on the matter?

**Comment by bluryar** [comment]
> any updates on the matter?
> 
> 有什么新消息吗？

[v3.11.0](https://github.com/coollabsio/coolify/releases/tag/v3.11.0)

It should be fixed. I'll test it again when I'm free.
