### ISSUE TITLE
[Bug]: database url invalid and weird

### ISSUE THREAD

**Issue by mrhappyma** [coollabsio/coolify#667]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

My postgreSQL connection string is displaying as postgresql://...@**nope**:9001/...

I hope this is good as far as an example goes lol

### Steps To Reproduce

- go to postreSQL thing
- scroll down
- see funky connection string

### Version

3.10.14

**Comment by andrasbacsai** [comment]
Fixed in the latest version.
