### ISSUE TITLE
[Feature]: Terminal?

### ISSUE THREAD

**Issue by aghasemi** [coollabsio/coolify#670]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Hi. Is there a way to open a terminal in Coolify UI for the same machine on which Coolify is running?

### Why should this be worked on?

It can be helpful in various debugging situations, creating SSH key pairs, and in general convenience for not having to go outside the browser when Coolify UI is open already.

**Comment by punnerud** [comment]
I have found two different ways to solve it:

1.  [attach local standard input, output, and error streams to a running container](https://docs.docker.com/engine/reference/commandline/attach/)
2. Docker is not normally shipped with ssh, so if have to be added as part of the build build process

With alternative 1 there could be a prompt at first within Coolify, and later added ssh support to bridge them.
Alternative 2 is a more native way to solve it and more secure, but do change the build.

If alternative 2 is done, why should there be a support for adding other scripts to the build process of Docker? So the first version could just be support for custom build scripts, where ssh is one possibility.

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
