### ISSUE TITLE
[Bug]: Cannot see any application logs for periodic job

### ISSUE THREAD

**Issue by aghasemi** [coollabsio/coolify#671]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi,

I am running a simple periodic job (_Bot_ as per Coolify UI) which uses Python's APScheduler to run a function every 30 minutes and print CPU and memory usage. The problem is I cannot see any printed outputs in Application Logs, although Build succeeds, and I know for a fact that the code is actually running (from other functions there that call HTTP endpoints). 

Is there anything that I need to check? Something I missed?

### Steps To Reproduce

Currently using `python:3.7-bullseye` image:

```python

from apscheduler.schedulers.blocking import BlockingScheduler
import requests
import psutil

sched = BlockingScheduler(timezone="Europe/Paris")

@sched.scheduled_job('interval', minutes=30)
def timed_job_Xm():    
    print(f'CPU: {[100.0-_.idle for _ in psutil.cpu_times_percent(interval=1, percpu=True)]} Mem: {psutil.virtual_memory().percent}')

print('Starting')
sched.start()
```

### Version

3.10.14

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
