### ISSUE TITLE
[Feature]: remove the block width restriction

### ISSUE THREAD

**Issue by Yurgeman** [coollabsio/coolify#672]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### It's inconvenient to watch the log on a big screen

![Снимок экрана 2022-10-09 в 22 37 37](https://user-images.githubusercontent.com/7249668/194776848-1b6ee41e-ca54-4a0a-a732-3a193f0c454c.png)

you can also set a fixed size of the navigation block, otherwise it will look cumbersome

![Снимок экрана 2022-10-09 в 22 39 05](https://user-images.githubusercontent.com/7249668/194776850-59f5bed0-1cf3-44e9-9580-d002307c1ba4.png)

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
