### ISSUE TITLE
[Feature]: InfluxDB as a Database option

### ISSUE THREAD

**Issue by whitesidest** [coollabsio/coolify#673]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I was thrilled to see the addition of Grafana to the list of available services, thank you for that.  I would love to see the option to also have InfluxDB (or Prometheus) to be able to feed data into Grafana.

### Why should this be worked on?

Grafana works well with InfluxDB and Prometheus and it would be so helpful to have the option for my project.

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
