### ISSUE TITLE
[Feature]: Add Keycloak as a Service

### ISSUE THREAD

**Issue by ksmithdev** [coollabsio/coolify#676]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Keycloak is an open-source identity provider that supports single sign-on, identity brokerage, and user management. 

Per the description on the site:
> Add authentication to applications and secure services with minimum effort. No need to deal with storing users or authenticating users. Keycloak provides user federation, strong authentication, user management, fine-grained authorization, and more.

### Why should this be worked on?

There are several requests for some sort of identity provider service that can be deployed quickly with coolify. Having the ability to deploy keycloak would satisfy this need and provide a centralized authentication services to other deployed application.

**Comment by Stargate-project** [comment]
please dont add keykloak there is a much better and popular solution (Authelia) https://github.com/authelia/authelia

**Comment by ksmithdev** [comment]
The more the marrier I always say. Keycloak worked great for my use case since I could manage everything directly on the deployment site.

**Comment by Stargate-project** [comment]
Keycloak just seems to have lots lots issues and its developed in java vs authenlia being developed in Go, much more stable

**Comment by ksmithdev** [comment]
This ... seems like the weirdest place to try and hash out old pointless language flame wars?

As for stability, what issues have you experienced? I've been running it from testing to prod without even a hiccup with a couple of my personal projects now. Keycloak is an 8 year old product that gets regular releases and is sponsored by Red Hat. It checks all the boxes for what would make an acceptable service and fills a gap I thought coolify might like. This is an open source project though so, like me, you can put together a PR to implement Authelia.
