### ISSUE TITLE
[Bug]: DNS-Setting invalid

### ISSUE THREAD

**Issue by degoya** [coollabsio/coolify#679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when i try to set the FQDN i think i have a problem with letsencrypt, the DNS is pointing to the server but i only get a selfsigned cert when i turn off the DNS check in the settings.

![grafik](https://user-images.githubusercontent.com/3515182/195404713-0000a612-e03c-4382-a9f0-8733f728d28e.png)

the request causes a 500 error

![grafik](https://user-images.githubusercontent.com/3515182/195413632-f6bba89c-fd63-4c49-9be0-5039b296f41e.png)

are there any special DNS settings that need to be done? in my case for a subdomain?

is there a way to have logs to see what happens with the LE cert?

### Steps To Reproduce

freshly installed coolify on hetzner cloud.
when i have installed the 3.10.15 version and set up the FQDN and save with DNS-Check and SSL-Cert on.
used 

`wget -q https://get.coollabs.io/coolify/install.sh -O install.sh; sudo bash ./install.sh`

### Version

3.10.15

**Comment by vasani-arpit** [comment]
Did you added the A record pointing to this IP in your provider (CloudFlare/goDaddy/Namecheap) ?

**Comment by degoya** [comment]
@vasani-arpit yes, it's setup normaly. like i've setup all the other Domains in the DNS with the DNS A-Record pointing to the coolify Server. 
btw. i've setup a service with a subdomain, with this service the LE Cert is working but not with the mail Coolify FQDN, but i need this to get it connected to my gitlab server.

**Comment by vasani-arpit** [comment]
I don't have a much experience with custom Certs. @andrasbacsai Can you take a look?

**Comment by degoya** [comment]
@vasani-arpit yes, it's setup normaly. like i've setup all the other Domains in the DNS with the DNS A-Record pointing to the coolify Server. 
btw. i've setup a service with a subdomain, with this service the LE Cert is working but not with the mail Coolify FQDN, but i need this to get it connected to my gitlab server.

**Comment by LeonHeidelbach** [comment]
I have the same issue here. We are trying to use coolify as a deployment plattform for experimental software at our faculty and the DNS gets properly resolved to our machine's IP. I also added our University's DNS server to the custom DNS servers list, but whenever I try to set then FQDN I also only get the error "DNS settings for <out_domain> is invalid, click to recheck.". Is there new info on what might be the issue?

**Comment by degoya** [comment]
any solution for this problem? i'd like to use coolify but i'm not able to get the Domain with LE Cert.

**Comment by andrasbacsai** [comment]
I'm trying to reproduce it, but on a newly installed server + a new top-level domain, it works.

To check the logs of LE, you can check coolify-proxy container with `docker logs -n 100 -f coolify-proxy` command and see what's going on.

**Comment by degoya** [comment]
@andrasbacsai i've executed the command on the coolify host and got the following result

```
time="2022-10-27T15:13:15Z" level=error msg="Unable to obtain ACME certificate for domains \"coolify.xxxxxxx.de,www.coolify.xxxxxxx.de\": unable to generate a
certificate for the domains [coolify.xxxxxxx.de www.coolify.xxxxxxx.de]: error: one or more domains had a problem:\n[www.coolify.xxxxxxx.de] acme: error: 400
:: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for www.coolify.xxxxxxx.de - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for www.coolify.xxxxxxx.de - check that a DNS record exists for this domain\n" rule="(Host(`coolify.xxxxxxx.de`) || Host(`www.coolify.xxxxxxx.de`)) && PathPrefix(`/`)" providerName=letsencrypt.acme ACME CA="https://acme-v02.api.letsencrypt.org/directory" routerName=coolify-secure@http
time="2022-10-27T15:13:17Z" level=error msg="Provider connection error cannot fetch configuration data: Get \"http://coolify:3000/webhooks/traefik/main.json\": dial tcp: lookup coolify on 127.0.0.11:53: no such host, retrying in 634.469623ms" providerName=http
time="2022-10-27T15:13:23Z" level=error msg="Provider connection error cannot fetch configuration data: Get \"http://coolify:3000/webhooks/traefik/main.json\": dial tcp 172.16.0.3:3000: connect: connection refused, retrying in 1.034253849s" providerName=http
time="2022-10-27T15:13:29Z" level=error msg="Provider connection error cannot fetch configuration data: Get \"http://coolify:3000/webhooks/traefik/main.json\": dial tcp 172.16.0.3:3000: connect: connection refused, retrying in 809.323285ms" providerName=http
time="2022-11-02T21:31:38Z" level=error msg="Error while Peeking first byte: read tcp 000.16.16.2:80->000.85.94.217:1425: read: connection timed out"
```

**Comment by andrasbacsai** [comment]
It looks like the `www.coolify.xxxxxx.de` is not set in DNS. Could you please double check?

**Comment by degoya** [comment]
@andrasbacsai ok, i've added the www. to the DNS, 
now i don't get an Error when adding the Domain but when i try to open the domain via https://coolify.xxxx.de:3000 i get an Error in the Browser SSL_ERROR_RX_RECORD_TOO_LONG

**Comment by degoya** [comment]
any solution for this problem? i'd like to use coolify but i'm not able to get the Domain with LE Cert.

**Comment by calvinlang** [comment]
I'm having a similar issue with a fresh install 
<img width="662" alt="Screen Shot 2022-12-03 at 12 10 33 PM" src="https://user-images.githubusercontent.com/14323034/205422058-3415eba2-9ed2-4859-bced-17c94e8388f3.png">

**Comment by Morpheus0x** [comment]
I had the exact same issue, and I suspect that this isn't a bug with coolify at all.

My suspected reason for these errors is, that the Let's Encrypt server has a "slow" DNS server. If you create a new record, it might work instantly for you because you are using a good DNS server locally. But the Let's Encrypt API seems to use a DNS server with heavy caching and therefore doesn't pickup the new A records instantly.

I would recommend to everyone to wait a couple of hours until the A records have fully propagated to all DNS Servers before, adding the domain to coolify.
