### ISSUE TITLE
[Bug]: Error when tried to update Coolify

### ISSUE THREAD

**Issue by ivangsm** [coollabsio/coolify#683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have enabled the auto update feature and everything worked fine, since the release of version 3.10.16, I'm started getting a Bad Gateway message when I tried to access to my Coolify instance. 

I reboot the server, and I was able to enter the dashboard, so, I deactivate the auto update feature and tried to update manually but happens the same thing, I'm getting an error and I need to reboot the server to be able to access the dashboard in the 3.10.15 version.

### Steps To Reproduce

![2022-10-13 22 43 47](https://user-images.githubusercontent.com/10017231/195757611-19ed87b2-78d3-46ea-aebf-11316f61855f.jpg)
![2022-10-13 22 43 58](https://user-images.githubusercontent.com/10017231/195757614-9027ec6a-3c53-4d0e-ab6f-a93d58543ca6.jpg)
![2022-10-13 22 44 03](https://user-images.githubusercontent.com/10017231/195757616-cfce3cc4-3f3a-499c-8cfd-a4c11354ca3d.jpg)
![2022-10-13 22 44 07](https://user-images.githubusercontent.com/10017231/195757617-cfb5c47d-bc71-4533-b473-472041af3485.jpg)

### Version

3.10.15

**Comment by vasani-arpit** [comment]
@ivangsm Can you provide your server config vCPU and RAM? sometimes the new process is too heavy for server to spin up.

**Comment by ivangsm** [comment]
> @ivangsm Can you provide your server config vCPU and RAM? sometimes the new process is too heavy for server to spin up.

Sure @vasani-arpit the server has:

4 vCPU Ampere 1
24 GB RAM 2.3 GB Used
200 GB SSD 18 GB Used

**Comment by Alexnortung** [comment]
@ivangsm what was your solution?
