### ISSUE TITLE
[Bug]: Preview Deployment push stops main app

### ISSUE THREAD

**Issue by bstst** [coollabsio/coolify#684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I have Preview Deployments enabled and I push a commit to the pull request branch, the app on the `main` branch is being stopped and I need to re-deploy it, and I also see this in the Builds section:

<img width="306" alt="image" src="https://user-images.githubusercontent.com/412859/195830519-05f640c7-dd4c-46fe-98e7-ac8034786f40.png">

Even though the log ends with this message, meaning to visible errors in there:

```
[11:36:21.899] Deployment started.
```

The actual Preview Deployment feature works, I just need to re-deploy my main app every time.

I am working on a `Deno` buildpack if that makes a difference.

### Steps To Reproduce

Enable Preview Deployments;
Create a Pull Request;
Push a new commit to the pull request branch;
The main app is stopped;

### Version

3.10.16

**Comment by andrasbacsai** [comment]
I think this is already solved.
