### ISSUE TITLE
[Bug]:appwrite storage file upload not working 

### ISSUE THREAD

**Issue by scshiv29-dev** [coollabsio/coolify#685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when clicking and adding a new file to bucket in appwrite it says failed
![image](https://user-images.githubusercontent.com/68141773/196027217-65f7e092-884f-45ab-9545-5be8b10e4fcc.png)

### Steps To Reproduce

1. go to coolify console 
2. create a appwrite instance
3. create a project and then create a bucket
4. then try adding a new file 

### Version

3.10.16

**Comment by stnguyen90** [comment]
There may be some problems with the antivirus scanning at the moment. It might be best to include:

```
_APP_STORAGE_ANTIVIRUS=disabled
```

in the environment variables for Appwrite's `appwrite` container.

Reference:

1. [docker-compose.yml](https://appwrite.io/install/compose) file
2. [.env](https://appwrite.io/install/env) file

**Comment by scshiv29-dev** [comment]
@andrasbacsai could you make these changes?

**Comment by andrasbacsai** [comment]
The latest template based appwrite has disabled antivirus by default.
