### ISSUE TITLE
[Bug]: Huge performance issue since the last upgrade

### ISSUE THREAD

**Issue by loagencydev** [coollabsio/coolify#686]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Since the last version update to `v3.10.16`, we're facing strange performance issues, specifically during the build process.
![image](https://user-images.githubusercontent.com/81680545/196141544-a20c2acd-d961-4c18-b25a-4ad4faddd7d4.png)

### Steps To Reproduce

Just upgrade to the latest version

### Version

3.10.16

**Comment by loagencydev** [comment]
For now, I need to scale up the server. Anyway, had to shut down to rescale
![image](https://user-images.githubusercontent.com/81680545/196143991-ad92d2f2-4056-4573-89d3-77f1d83e8352.png)

**Comment by andrasbacsai** [comment]
Is this still persists? If yes, could you please give me an example repository, so I can check it?

Please reopen this issue if needed.
