### ISSUE TITLE
Does not work with monorepo workflow

### ISSUE THREAD

**Issue by loicttn** [coollabsio/coolify#69]
Hi, first of all thanks for the great work behind coolify !

I am trying to deploy 2 react frontends and a node backend, which are all in the same repository (with a file structure like this: services/front1 services/front2 services/backend). I want to deploy all those services whenever I merge a PR to the main branch.

The thing is I cannot create multiple applications with the same branch and the same repository on the coolify dashboard (latest version) and when I try to create multiple applications with the same repository but not the same branch I get a 404 error on the newly created application.

Am I doing something wrong here ? Is coolify supporting - or planning to support - monorepo workflow like this ?

**Comment by andrasbacsai** [comment]
Hey, thanks! Yeah, I've placed that limitation (same branch, same repository), because I was unsure of the exact use case. 

Your use case is possible with Coolify, if I disable that restriction. The only restriction will be there could not be two applications with the same domain. 

I will add it to the next release!

**Comment by andrasbacsai** [comment]
I'm rewriting parts of the application to better support monorepos. Most of the work is done, but I need to test a lot of things. 🧪

**Comment by loicttn** [comment]
thanks, looking forward to this !

**Comment by beaussan** [comment]
Any update on this? I plan to migrate all my project to a single monorepo but coolify is the limiting factor since I won't be able to deploy them to it

**Comment by beaussan** [comment]
Ok so I look thought all of the changelog and it seems it's no longer an issue ? https://github.com/coollabsio/coolify/releases/tag/v3.9.0 I'll try it and edit the message accordingly

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
