### ISSUE TITLE
[Feature]: Database import / export

### ISSUE THREAD

**Issue by Tienisto** [coollabsio/coolify#690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

There should be a button to easily import / export database data.

### Why should this be worked on?

We are migrating from dokku and there is a command called `dokku postgres:import` to import existing data.
We could not find this feature in the UI yet and there is no documentation regarding this topic.

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
