### ISSUE TITLE
[Feature]: Deploy from image docker

### ISSUE THREAD

**Issue by themarkwill** [coollabsio/coolify#692]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

currently my build is done directly by github actions, I already need this for the api, which I host on google cloud run, but I would like to use the same image and deploy the bot.

### Why should this be worked on?

currently my build is done directly by github actions, I already need this for the api, which I host on google cloud run, but I would like to use the same image and deploy the bot.

**Comment by jamesbruice** [comment]
+1

**Comment by satvikpendem** [comment]
Same here, I want to compile my heavy app locally, push it to an image, then have the VPS pull from it, so that I don't need to have a compilation server and deployment server be the same thing.

**Comment by mmm8955405** [comment]
Months passed. How to deploy Docker

**Comment by themarkwill** [comment]
> Months passed. How to deploy Docker

Now is possible you implement from direct a image docker, using a Docker File on deploy, now you don't need of a Github Project.

Steps:
1. Go to create Application
2. Set here your image
![CleanShot 2022-12-30 at 8 19 02](https://user-images.githubusercontent.com/34342635/210064847-45fa5904-7ed2-4414-bdfe-4ec8a314db82.png)
Ex:
```
FROM wordpress:php8.2-fpm
```

**Comment by satvikpendem** [comment]
This shouldn't be closed, a Dockerfile is not the same s a Docker _image_. Personally I'm still waiting on Docker image support.

**Comment by mmm8955405** [comment]
> > Months passed. How to deploy Docker
> 
> Now is possible you implement from direct a image docker, using a Docker File on deploy, now you don't need of a Github Project.
> 
> Steps:
> 
> 1. Go to create Application
> 2. Set here your image
>    ![CleanShot 2022-12-30 at 8 19 02](https://user-images.githubusercontent.com/34342635/210064847-45fa5904-7ed2-4414-bdfe-4ec8a314db82.png)
>    Ex:
> 
> ```
> FROM wordpress:php8.2-fpm
> ```

I even think you don't know technology at all! It supports gitea as the git data source. You just install gitea as a service, and then close the bug. Then deploy from the docker. You just add the docker file and close the bug! Are you front-end developers suffering from mental illness?
