### ISSUE TITLE
[Feature]: Integrate Login Cloudflare Zero Trust

### ISSUE THREAD

**Issue by themarkwill** [coollabsio/coolify#693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

A way to be able to login integrated with other platforms

### Why should this be worked on?

In my organization we use Cloudflare Zero Trust to login to all the services we use, our interns use a direct login with their token, in some others SAML is used. Could we discuss more about it?

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
