### ISSUE TITLE
[Bug]: Minio APi url not work

### ISSUE THREAD

**Issue by Yurgeman** [coollabsio/coolify#694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The service itself is installed without problems. But when you try to log in to the console, it displays a message: 
```post "https://apiUrl.ltd": dial tcp MyIp:443: i/o timeout```

![photo_2022-10-21 15 06 39](https://user-images.githubusercontent.com/7249668/197192593-b8acaf00-1772-4bbb-a51a-f286d7a97a7f.jpeg)
![photo_2022-10-21 15 06 43](https://user-images.githubusercontent.com/7249668/197192601-9d5f3f08-416a-4238-ac4b-e5b0c291b68c.jpeg)
![photo_2022-10-21 15 06 44](https://user-images.githubusercontent.com/7249668/197192602-ce60a43d-3de8-4d90-abd7-e28514badeb0.jpeg)

### Steps To Reproduce

install the service on ubuntu 20.4
install the domain for the console and for the api

### Version

v3.10.16

**Comment by Yurgeman** [comment]
maybe this is due to the new release minio RELEASE.2022-10-20T00-55-09Z, released yesterday

**Comment by andrasbacsai** [comment]
I will check it!

**Comment by andrasbacsai** [comment]
I could not reproduce it. Some parts were changed since then. Could you please recheck and let me know if it still persists? If yes, please reopen this issue.

Thanks!
