### ISSUE TITLE
[Bug]: Unable to create automatic deployment on docker-compose application with github hooks

### ISSUE THREAD

**Issue by Wojciechowski-Marcin** [coollabsio/coolify#697]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi, I tried to configure automatic deployment of my github application, but nothing seems to be happening on new commits.
The application is set up to develop branch (different from default branch), the webhook is being sent to http://<IP>:3000/webhooks/github/events, coolify is running on <IP>:3000

### Steps To Reproduce

1. Create docker-compose application
2. Create github source
3. Change to correct IP address in webhooks
4. Make a commit

### Version

3.10.16

**Comment by andrasbacsai** [comment]
If you create a github source, the IP address is automatically filled.

Why did you change to a `correct IP address`?

**Comment by grstreten** [comment]
Interestingly I think I'm running in to the same issue. Totally stock setup; getting the response `{"status":500,"message":"Application not configured."}` from Coolify in the GitHub webhook logs. Just a standard Docker build pack for me.

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
