### ISSUE TITLE
Available for PHP

### ISSUE THREAD

**Issue by Wulfheart** [coollabsio/coolify#7]
Is it also possible to use it with PHP?

**Comment by fruitl00p** [comment]
@Wulfheart have you looked at Dokku? which gives you the heroku experience without the GUI and support php (and others)

**Comment by andrasbacsai** [comment]
I will love to support PHP! That will be the first language which I will add soon.

**Comment by Wulfheart** [comment]
My ideal use case for that would be to effortlessly deploy Laravel applications on my server.

**Comment by andrasbacsai** [comment]
Yesterday, I tested simple PHP deployments. It works. 🙂

Laravel is the next level. I need to read some docs about it, as I never used it.

**Comment by Wulfheart** [comment]
I am happy to answer all of your questions you may have about Laravel.

**Comment by andrasbacsai** [comment]
I've added basic PHP support in v1.0.3. Laravel is coming a bit later.

**Comment by tertek** [comment]
Laravel Deployment is pretty essy with [Deployer](https://deployer.org).
