### ISSUE TITLE
[Question] How to connect to MongoDB from outside?

### ISSUE THREAD

**Issue by ItzNeviKat** [coollabsio/coolify#70]
Hello there!
I created an instance of MongoDB in Coolify admin, but cannot to connect to it from outside. How I can allow to connect to MongoDB's port from outside?

**Comment by andrasbacsai** [comment]
Hey,

Unfortunately, it's not possible atm. I was testing in before, but the reverse proxy that Coolify uses (Traefik) does not like to do it.
It's on my table, but not sure when can I solve it, if Traefik does not support it.

**Comment by inluxc** [comment]
Traefik does support TCP routers

https://doc.traefik.io/traefik/routing/providers/consul-catalog/#tcp

**Comment by andrasbacsai** [comment]
Wow, thanks! I will check it this week!

**Comment by andrasbacsai** [comment]
In the new version (v2) this is implemented.

A fresh installation is required as v2 is not compatible with v1.

**Comment by shareef945** [comment]
is there anything in particular i need to do to enable this? i'm not able to connect from coolify but i can connect from all over providers including my local machine. 

MongoServerError: bad auth : authentication failed
    at Connection.onMessage

**Comment by Ttommeke** [comment]
I'm having the same question. I have setup wildcard domain names and https works out of the box for all other services.

Ps: Coolify is an amazing product! ❤️

**Comment by Ttommeke** [comment]
In the logs i can see: 
`{"code":141,"codeName":"SSLHandshakeFailed","errmsg":"SSL handshake received but server is started without SSL support"},"remote":"172.18.0.8:58066","connectionId":65}}`

**Comment by jocubeit** [comment]
Not working for me either.

Error: cannot connect to MongoDB. Details: Authentication failed.

**Comment by shareef945** [comment]
@jocubeit its an issue with encoding special characters. So if you have any special characters in your password you may need to add additional symbols for the password to be considered valid.

**Comment by jocubeit** [comment]
> @jocubeit its an issue with encoding special characters. So if you have any special characters in your password you may need to add additional symbols for the password to be considered valid.

There are no special characters in the password. I'm using the standalone docker one-click installer in Coolify, and I suspect the special $SERVICE_PASSWORD_64 environment variable is used to generate a random 64 char password (even though I can't see the script or compose file that spins up an instance).

**Comment by super-karan** [comment]
i am having same problam authentaction faielld in mongo db compass

**Comment by backspacevenkat** [comment]
Is this working? I am trying for a long time but this is failing.
