### ISSUE TITLE
[Bug]: When I Stop the Database change Public Port

### ISSUE THREAD

**Issue by themarkwill** [coollabsio/coolify#702]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

On all time with I had stop the database, and restart, the port is changed for next incremental, but is the same database.

### Steps To Reproduce

1. Create a databse
2. Set public port, in this case is selected a port
3. Stop this database
4. Restart database
5. Set public port again, and the port is changed

### Version

3.10.16

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
