### ISSUE TITLE
[Bug]: mariaDB not supported in newer Ghost versions

### ISSUE THREAD

**Issue by curiousigor** [coollabsio/coolify#704]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

As per their [documentation](https://ghost.org/docs/faq/supported-databases/), Ghost 5+ requires MySQL 8+ to run.

The config when setting Ghost up as a service in Coolify now deploys and sets up MariaDB. This means that it would require a migration to MySQL for already deployed services. 

The steps to do a migration are written here: https://forum.ghost.org/t/how-to-migrate-from-mariadb-10-to-mysql-8/29575

The interface also shows a warning:
<img width="590" alt="Screenshot 2022-11-02 at 13 10 49" src="https://user-images.githubusercontent.com/2616170/199486690-2f78775c-d418-429b-899f-99edd5eacbb9.png">

### Steps To Reproduce

1. Deploy Ghost from services
2. Open the Ghost admin panel
3. Observe the warning under Settings > About Ghost

### Version

3.10.16

**Comment by andrasbacsai** [comment]
It is fixed with the new community based templates.
