### ISSUE TITLE
[Bug]: Ghost service login not working

### ISSUE THREAD

**Issue by surenrao** [coollabsio/coolify#706]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

lets say my domain in example.com

This is a two part bug which happened yesterday (11/04/22)
1) For ghost, if i use FQDN = "https://blog.example.com" and deploy, then login gets busted due to cors error, since its making a request to https://**www**.example.com. If i change FQDN to "https://www.example.com" then it at least sign up popup shows up.

2) I am not able to login to the ghost admin panel. In the Login prompt when i try to use "Ghost Default Email Address" shown in Ghost configuration, i get error "No member exists with this e-mail address. Please sign up first." Sign up also fails with error "Failed to send magic link email" i think its because  i didnt configure smtp anywhere. not sure where to do that?

Note: i installed nocodb and appwriter and was able to register and login fine

### Steps To Reproduce

Just deploy Ghost service to any subdomain other than "www" for 1st part.

2nd part not able to login or sign up once ghost is live

### Version

latest

**Comment by andrasbacsai** [comment]
The latest Ghost version does not allow MariaDB as a database. 

I’ve changed this while added the template based services. Could you please make a new Ghost service and test if it happens again?

**Comment by surenrao** [comment]
I tried again, The app is not able to connect to db.

2022-11-17T00:56:53.414831078Z Error: connect ECONNREFUSED 172.XX.XX.XX:3306
2022-11-17T00:56:53.414829515Z
2022-11-17T00:56:53.414827752Z ----------------------------------------
2022-11-17T00:56:53.414826138Z
2022-11-17T00:56:53.414824436Z ECONNREFUSED
2022-11-17T00:56:53.414822562Z Error Code:
2022-11-17T00:56:53.414820939Z
2022-11-17T00:56:53.414819016Z 500
2022-11-17T00:56:53.414817102Z Error ID:
2022-11-17T00:56:53.414815258Z
2022-11-17T00:56:53.414813375Z "Unknown database error"

**Comment by surenrao** [comment]
I think it maybe due to mysql 8? Since i can get it running as a Database too. however when i do v5.7 db runs fine

**Comment by scshiv29-dev** [comment]
@andrasbacsai  i ran into the same issue the thing is ghost sends a magic link for login/signup but to configure it u need to manually go into the containers bash and add the values and restart it. I was able to add the values but i cant restart the container without deleting the changes. is there a way to just restart the current service?

**Comment by mvkvc** [comment]
I am having the same issue when deploying Ghost with a DB it runs but nothing happens when I try to sign up

**Comment by scshiv29-dev** [comment]
so i found a way actually @jenishngl  @mvkvc  what you can do after starting a ghost instance from the coolify dashboard is to log into your server and go the bash terminal of the ghost docker container and then there you can change the mail server config . [here](https://forum.ghost.org/t/how-to-setup-basic-smtp-for-ghost/29166)

**Comment by jenishngl** [comment]
> so i found a way actually @jenishngl @mvkvc what you can do after starting a ghost instance from the coolify dashboard is to log into your server and go the bash terminal of the ghost docker container and then there you can change the mail server config . [here](https://forum.ghost.org/t/how-to-setup-basic-smtp-for-ghost/29166)

Cool. I found a much simpler option via the Configuration tab in UI itself. Update the below and acopy it into the configuration tab and we are good. Try it

```
mail__transport=SMTP
mail__options__host=mail.test.in
mail__options__port=25
mail__options__auth__user=test
mail__options__auth__pass=test
mail__from=test@mail.test.in
```

<img width="1156" alt="image" src="https://github.com/coollabsio/coolify/assets/9320926/76aee773-e852-4f6a-bf2f-1fdb1face93d">

**Comment by scshiv29-dev** [comment]
did not know this thanks ,anyways i stopped using coolify just this month thanks for later

**Comment by jenishngl** [comment]
> did not know this thanks ,anyways i stopped using coolify just this month thanks for later 

I just started using it few days back. May I know the reason for stopping or you found anything better?

**Comment by scshiv29-dev** [comment]
@jenishngl  i stopped because i did not need it anymore actually.
