### ISSUE TITLE
[Bug]: Application logs do not work

### ISSUE THREAD

**Issue by snimshchikov** [coollabsio/coolify#707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Frontend sends request to domain/api/v1/applications/(id)/logs/(id)-bot?since=0
Response:
{"logs": [], "noContainer": true}

If I delete "-bot" from url and send the same request, I get a correct response

### Steps To Reproduce

Don't know. I created my first containers and they were working fine, but then something broke and now every app I create have no logs
Os: ubuntu 22.04.1

### Version

3.10.16

**Comment by snimshchikov** [comment]
Ok, I got what's wrong. My github repo has a docker-compose.yml file in it (with a "bot" service). When I start a python app in coolify, app logs search for (id)-(app-name) and find nothing. And that's the issue

Workaround: delete docker-compose file or choose a nonstandart name for it

**Comment by andrasbacsai** [comment]
Are you using `Docker Compose` buildpack or the python one?

**Comment by 4u-service** [comment]
python buildpack (but I also have a docker-compose file and it automatically parses info from it even when I use python)
btw, I tested other buildpacks, they have the same issue

**Comment by snimshchikov** [comment]
I am using python buildpack (but I also have a docker-compose file and it automatically parses info from it even when I use python)
btw, I tested other buildpacks, they have the same issue

**Comment by andrasbacsai** [comment]
Can you please check if `coolify-fluentbit` container is running on your system? `docker ps -a | grep -i coolify-fluentbit`
