### ISSUE TITLE
[Feature request] Gitlab support

### ISSUE THREAD

**Issue by ruslankonev** [coollabsio/coolify#71]
Hi! At first, thanks for this cool project. 
But my question is – it is possible to implement Gitlab support?

**Comment by andrasbacsai** [comment]
Hey, Thanks! 🙂 Yeah, GitLab has similar Webhooks as GitHub, so yep, it's possible. Thanks for the suggestion!

**Comment by badlanguage** [comment]
> Hey, Thanks! 🙂 Yeah, GitLab has similar Webhooks as GitHub, so yep, it's possible. Thanks for the suggestion!

Be sure to consider self hosted gitlab installations and not just gitlab.com, as Gitlab has a wider community using the self hosted version (all with the same API).

**Comment by spencerflagg** [comment]
UPVOTED. I'm interested in integrating with a self-hosted Gitea instance, which I believe is a fork of GitLab.

Just one step away from a purely self-hosted solution. Exciting! :tada:

**Comment by andrasbacsai** [comment]
Implemented in v2 🎉  A fresh installation is required as v2 is not compatible with v1.
