### ISSUE TITLE
[Feature]: LEMP STACK

### ISSUE THREAD

**Issue by rafalohaki** [coollabsio/coolify#729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Lemp stack
Nginx, MySQL, PHP installed on alpine

### Why should this be worked on?

its great to have some playground done in few clicks

**Comment by andrasbacsai** [comment]
Not sure what this feature will achieve. Coolify is not about installing software on a server, but simplifying the build & deploy process of applications, databases or OSS services.

You can start a MySQL server with a few clicks and deploy any PHP applications as well.

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
