### ISSUE TITLE
[Bug]: Cant set a custom port for UMAMI service

### ISSUE THREAD

**Issue by barshag** [coollabsio/coolify#731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I set port, it create an exception, then it force me to use port 3000 (which reserverd for coolify)

### Steps To Reproduce

Make new service
change port

### Version

3.11.7

**Comment by andrasbacsai** [comment]
v3.11.8 does have a fix for this. Could you please try again with that version?

**Comment by barshag** [comment]
Thanks for the answer. is there any easy way to install the fix?

**Comment by andrasbacsai** [comment]
You would see a pink button on the left side of your screen. Click on it. (If you are from mobile, you need to open the menu on the top left corner)

**Comment by barshag** [comment]
It worked. Thanks :)

BTW- is there a way to update the services also (moving to a new version of
UMAMI?)

Thanks!!!

**Comment by andrasbacsai** [comment]
If you stop the service, you can select a newer `version/tag` in the configurations. If the new version is missing, let me know.
