### ISSUE TITLE
[Bug]: VaultWarden service does not use secrets

### ISSUE THREAD

**Issue by lgastler** [coollabsio/coolify#734]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The VaultWarden Service does not load secrets defined inside Coolify. I've tried f.e. to set ADMIN_TOKEN or SIGNUPS_ALLOWED and they are not loaded accordingly. The logs show: `[INFO] No .env file found.`

### Steps To Reproduce

1. Create new VaultWarden Service
2. Set ADMIN_TOKEN in Secrets
3. Deploy service
4. Try to access `/admin` page

### Version

3.11.10

**Comment by andrasbacsai** [comment]
Is this still an issue?
