### ISSUE TITLE
[Feature]: Add Groups to to the variables in the templates

### ISSUE THREAD

**Issue by inluxc** [coollabsio/coolify#737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Has we have big projects with lots of environment variables that can be used, we need to group them for a better layout and help to filter.

`
variables:
  - id: $$config__app_influxdb_host
    name: _APP_INFLUXDB_HOST
    label: _APP_INFLUXDB_HOST
    group: InfluxDB
    defaultValue: $$id-influxdb
    description: ''
`

So we can have same thing like this, as an accordion.

![Coolify_env_groups](https://user-images.githubusercontent.com/584683/202866436-b5ed679d-8822-4fe3-bd13-4dace4e9a961.png)

### Why should this be worked on?

This will help us to better control large environment variables like in: [Directus](https://docs.directus.io/self-hosted/config-options.html#configuration-files)

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
