### ISSUE TITLE
[Feature]: When using templates, allow "Read Only" env variables to be overwritten by manually set secrets

### ISSUE THREAD

**Issue by McPizza0** [coollabsio/coolify#740]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

For templates: Ensure variables set in SECRETS take precedence over non-editable template variables

### Why should this be worked on?

Some templates have ENV variables that are not editable by the user (See Appwrite _APP_DOMAIN as example)

We should allow the user to overwrite these variables by setting them in the Secrets.

When building the container, first load the pre-set config, then overwrite with any manually set secrets

This will enable users to set manual custom config that would otherwise be locked by non editable env variables

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
