### ISSUE TITLE
[Feature]: dependent services

### ISSUE THREAD

**Issue by mrhappyma** [coollabsio/coolify#749]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

A way to make one application wait to start until another app is ready

For example having an application that depends on a database hosted on coolify wait to be started until it's database is ready

### Why should this be worked on?

Currently, applications that depend on databases may start up before their database is ready. This causes them to crash. There should be an easy to way to wait for the database to start first.

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
