### ISSUE TITLE
Background / Cron jobs

### ISSUE THREAD

**Issue by badlanguage** [coollabsio/coolify#75]
**Description**

It would be nice if it was possible to create cron jobs on the fly, these could be run one time or every X period (similar to a cron job); this allows for many new types of services to be created; i.e. a catalogue update or marketing mail every day, week or month. the possibilities are endless and I believe it falls in the scope of Coolify to allow for such trivial functionality without having to do extra work.

**Comment by andrasbacsai** [comment]
Cron jobs were in scope, initially, but I'm thinking of creating a separate service for it that you can install in Coolify with one click. So it won't be part of Coolify but could be installed as, for example, Plausible Analytics.

From the user's point of view, it's the same, but it's a bit cleaner IMO from the developer's point of view.

What do you think of this?

**Comment by badlanguage** [comment]
I think it would be best to have it deeply integrated as a first party service rather than an addon, since it is coming directly from you and as you say it is in the scope, and it is more of a functionality rather than an app / service.

**Comment by badlanguage** [comment]
Just a quick thought, if ( #45 ) is to be accepted, integrating cron jobs would be fairly straight forward via the K8s API (https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/).

**Comment by Soneji** [comment]
> Cron jobs were in scope, initially, but I'm thinking of creating a separate service for it that you can install in Coolify with one click. So it won't be part of Coolify but could be installed as, for example, Plausible Analytics.
> 
> From the user's point of view, it's the same, but it's a bit cleaner IMO from the developer's point of view.
> 
> What do you think of this?

Hi @andrasbacsai 

I'd love to help develop a cron service, and I think it would be good to have it as a separate part, easily enabled with one click. Would you be able to point me in the direction of any resources to help create a service or projects for existing services

**Comment by badlanguage** [comment]
@andrasbacsai Just noticed (https://github.com/coollabsio/coolify/projects/1#card-63415453), is the plan to still use Agenda for v2? If you are planning to K8s integration background jobs can easily be achieved via the Kubernetes API (https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/)

**Comment by Flexicon** [comment]
Big bump on this one.

If we could get a service, that would allow anything as basic as just running tasks on a schedule similarly to both [Dokku](https://dokku.com/docs/processes/scheduled-cron-tasks/) and [Heroku](https://devcenter.heroku.com/articles/scheduler) then that would be fantastic.

**Comment by jugglingjsons** [comment]
I am not sure if I am misunderstanding the use cases here but you can both schedule workflows to run in n8n.io and run crontab in docker container currently.
https://docs.n8n.io/courses/level-one/chapter-5/chapter-5.7/

I agree it would be nice to use regular cron as well, but have you guys considered if there are alternatives? Unless you are talking about server related stuff / admin stuff that needs access to the instance it can be done fairly easily with custom docker application.

**Comment by Flexicon** [comment]
@jugglingjsons so I haven't looked into n8n.io before this, so thank you I'll take a look.

That said, my specific use case is exactly as what the Heroku and Dokku platforms offer as I've linked above. That is to say I need to run a specific action on my application at a given time schedule. This could be anything from running my application with a different argument, or in a Rails-like environment running things like rake tasks.

Would that be something I would be able to achieve with n8n.io ? I'm pretty sure the answer is no, but I'd love to be proven wrong.

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
