### ISSUE TITLE
[Bug]: Missing IP address at generated connection url

### ISSUE THREAD

**Issue by mimamghozalie** [coollabsio/coolify#751]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Description

missing public ip at generated connection string

![image](https://user-images.githubusercontent.com/12178712/204076629-a5b29b66-351b-48ad-a2f6-93359871068f.png)

### Steps To Reproduce

1. create database
2. select redis
3. select redis version
4. start application
5. Feature enable Set it public

### Version

3.11.13

**Comment by snimshchikov** [comment]
connection urls are broken, not only in redis

1. I often get none instead of host (and nevera correct external host)
2. internal and external connection urls are mixed together
