### ISSUE TITLE
[Bug]: Application degraded

### ISSUE THREAD

**Issue by Saceone** [coollabsio/coolify#752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I've been using the demo to see how coolify works and have deployed some apps and services.
Worked fine during my tests.
The next day I see "DEGRADED" in all of them but no error is shown in the Build or Application logs.
I haven't seen anything in the documentation regarding these HEALTHY or DEGRADED tags.
I haven't seen anything in the documentation regarding alive time of demo applications.

### Steps To Reproduce

1. Register to the demo version
2. Deploy a project
3. Wait for it to degrade

### Version

3.11.13

**Comment by simonorzel26** [comment]
Have you tried restarting the application? I have had this problem too but after a restart it isn't 'degraded'.  Seems to be just outdated versioning from the coolify auto update
