### ISSUE TITLE
[Bug]: Unable to update my docker-compose file

### ISSUE THREAD

**Issue by chikof** [coollabsio/coolify#754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I click on the "Reload Docker Compose File" button, I get an error which is "Bad credentials" (btw my project is private so it needs the authorization token which is null as I can see in the request headers.
![](https://chiko.rapedmy.dog/1dRE6z2NWd.png?key=gqV1icD0r3hdiy)

### Steps To Reproduce

1. Create an application with a docker-compose file.
2. Click the button "Reload Docker Compose File".

### Version

3.11.13

**Comment by ChikoShidori** [comment]
And It needs a Bearer token, I guess.
https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28#get-repository-content

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
