### ISSUE TITLE
[Bug]:  NocoDB service does not allow external database connections despite correct configuration

### ISSUE THREAD

**Issue by gavinrozzi** [coollabsio/coolify#755]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The nocoDB service does not appear to be honoring the environment variable to allow external database connections ("Disable External Database" in coolify UI).

The default service configuration sets this environment variable to 0 by default, which should allow nocoDB to connect to external databases. 

I read in the nocoDB documentation [here](https://docs.nocodb.com/getting-started/installation#environment-variables) that it will disable all external database connections if NC_CONNECT_TO_EXTERNAL_DB_DISABLED is set to a non-empty string.  

I'm wondering if the configuration of the environment variables in coolify could possibly be triggering this. Thanks in advance for your help with this and for all of your hard work on coolify!

### Steps To Reproduce

1. Create a new nocoDB service using the default configuration.
2. Log in to the nocoDB service as the superuser
3. Attempt to create a new project by connecting to an external database (the dropdown menu will not appear)

### Version

3.11.13

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
