### ISSUE TITLE
[Bug]: volume content doesn't get updated when the content on github changes

### ISSUE THREAD

**Issue by oberbayer** [coollabsio/coolify#756]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Sorry, this is my very first bug report ever. I think it could be a bug, but I'm not an expert... 
I have a Directus installation on a nodejs container. Extensions for Directus can be locally installed by uploading their files to /extensions. So in Coolify I define /extensions as a volume. The contents of /extensions on GitHub get uploaded correctly into the /extensions volume on build and are correctly recognized by Directus.
However, if I update the extension file on GitHub, the app is rebuilt, but the file is not updated on the volume.

What I expected: The new version of the extension to be loaded from GitHub and updated on the volume.

### Steps To Reproduce

1. Open a folder on GitHub and place a file in it.
2. In a nodejs app, define a volume with the folder's name.
3. Build the app - the file should be found in the volume.
4. Update the file on GitHub and rebuild the app - the file is not updated, but remains the old version.

### Version

3.10.16

**Comment by andrasbacsai** [comment]
Hey, thanks for reporting the problem.

1. Can you please update your Coolify instance to the latest version? I see you are using an older one.
2. If you set a persistent volume to be at `/extensions`, it will be mounted under `/app/extensions` as `/app` is the base directory for your applications in your current version of Coolify. If you update it, it will be `/extensions` and not `/app/extensions` as it was changed recently. Please show me your configuration here or on Discord (DM or in a channel).
