### ISSUE TITLE
[Bug]: A new build does not stop a running build

### ISSUE THREAD

**Issue by JonathanDoelan** [coollabsio/coolify#757]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Use case: I am changing a lot of stuff in a CMS in a short period of time. This triggers a new build each time. So when the first build is finished, the job should be done, but then the builds in the queue will start, even if it’s already done. Or in other words: A new build does not stop a running build.

### Steps To Reproduce

…

### Version

3.11.3

**Comment by JonathanDoelan** [comment]
Alternatively we could replace the next queued build as long as the running build has not finished. This could be an easier solution?

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
