### ISSUE TITLE
[Feature]: Enable url rewriting

### ISSUE THREAD

**Issue by JonathanDoelan** [coollabsio/coolify#758]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

There are some apps where we need specific url rewriting. For example in NuxtJS every request that does not match should point to `200.html`. Or maybe I just need any other mechanism like that. It only works with a Dockerfile but not with `Coolify Specific Build Packs` or the `Static Build Pack`.

### Why should this be worked on?

It is a basic feature that a lot of websites need.

**Comment by zmilan** [comment]
Is this the same issue as, for example, removing ```www``` part of url? Like redirecting from ```https://www.mydomain.com``` to ```https://mydomain.com```

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
