### ISSUE TITLE
Support for RockyLinux

### ISSUE THREAD

**Issue by badlanguage** [coollabsio/coolify#76]
**Background**

Rocky Linux is a complete OSS and enterprise ready operating system; functioning as a down stream build to CentOS. It has gained alot of popularity over the last few months.

**Description**

While it is not essential; it would be nice to see Coolify support Rocky, and not necessarily replace Ubuntu - when it comes to Linux Distros alot of users have preferences and when it comes to enterprises, they have strict policies - it would be nice to see Coolify allowing for a larger variety of support allowing for more users and organisations to make use of the project.

**Comment by andrasbacsai** [comment]
Wow! I never heard of Rocky Linux in my 10 years of Linux system administration career, so thanks for letting me know! 😀

I definitely would like to support such a thing!

**Comment by badlanguage** [comment]
RockyLinux has only recently been released (a beta was hosted since April I believe) but more information can be found on: https://rockylinux.org/

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
