### ISSUE TITLE
[Bug]: When i click on wordpress services then 500 erro 

### ISSUE THREAD

**Issue by kashifdesigns** [coollabsio/coolify#761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![service](https://user-images.githubusercontent.com/892354/205511033-03a9f33b-6e86-4c05-9275-b3561e8602cb.png)

### Steps To Reproduce

1. Go to Dashboard
2. click on wordpress site 

### Version

3.11.13

**Comment by kashifdesigns** [comment]
And how can i remove this service?

**Comment by andrasbacsai** [comment]
I will add some fixes to prevent that nasty 500 and the possibility of deleting any resources from the dashboard in the next version.
