### ISSUE TITLE
[Feature]: Change data type for remote port number from INT to 8 byte integer

### ISSUE THREAD

**Issue by kirill-dev-pro** [coollabsio/coolify#762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When you try to save remote destination connection with port number higher than 4096 it produce db save error

### Why should this be worked on?

Currently, you can't set port number for remote connections higher than 4096 because of prisma db data type. This number needs to be increased

**Comment by andrasbacsai** [comment]
I think the problem is not with the data type. SQLite's INTEGER data type is a maximum of 8 bytes. The problem is how Coolify saves it. I fixed it in the next version.
