### ISSUE TITLE
[Feature]: Delete git source

### ISSUE THREAD

**Issue by Saceone** [coollabsio/coolify#765]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Delete action should be available for git sources

### Why should this be worked on?

Let's say you migrate your repositories to another git account or something, just like the apps, services, etc, there should be an option for deleting git sources.

**Comment by gerhardriener** [comment]
I support this request, apparently this is only a problem for users below admin level. For admin accounts, deletion of git sources is possible.

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
