### ISSUE TITLE
[Feature]: Upload code files / tarball

### ISSUE THREAD

**Issue by SaadBazaz** [coollabsio/coolify#767]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

It'd be great if we could directly upload our code files on the web GUI, and have it built via:
- Docker-compose
- Simple nodejs configuration, python configuration, etc
- and all the other supported techniques.

Like CapRover, code could be uploaded through a .zip or a tarball, or even directly like in GitHub (that'd be cool). Here's an example of CapRover:

<img width="1093" alt="Screenshot 2022-12-08 at 10 57 49 AM" src="https://user-images.githubusercontent.com/51885228/206368947-a44f6ce7-aaef-42aa-b13a-adfe688df113.png">

### Why should this be worked on?

For very small teams without a custom domain/static IP, and no way for a local Git Source, this is a lifesaver for quick testing.

**Comment by BLACK4585** [comment]
//bump
Would love to see that!

**Comment by andrasbacsai** [comment]
This will be a feature of v4.

I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
