### ISSUE TITLE
[Feature]: Appwrite backup/restore

### ISSUE THREAD

**Issue by Saceone** [coollabsio/coolify#768]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Appwrite service should allow to backup and restore data. 

### Why should this be worked on?

According to docs https://appwrite.io/docs/production#backups in order to backup or restore we need to run some docker commands on the storage volumes and perform a dump on the mariadb database. This is recommended even before migrating, which is actually allowed in Coolify.

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
