### ISSUE TITLE
[Feature]: Add More than 1 secrets in api

### ISSUE THREAD

**Issue by themarkwill** [coollabsio/coolify#769]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I had creating a integration for implante the intra on terraform.
But in this case, I miss the one api for create many secrets in one time.

This is posible?

### Why should this be worked on?

For the api has support to add many secretes on one time, and not need request the api a lot of times.

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
