### ISSUE TITLE
Multi tenancy

### ISSUE THREAD

**Issue by badlanguage** [coollabsio/coolify#77]
**Background**
The current platform allows for one single "namespace" / "project"; however this should be extended to allow for multiple projects with their own collection of apps / services (see - #75). Additionally the concept of Organisations could be introduced (teams, if you will) - allowing for multiple users to view and manage these resources, with a roles system. 

**Use case**
There are multiple use cases, but one that stands out the most is allowing for the orchestration of multiple projects from one Coolify instance, such as in an enterprise environment where multiple teams need access to different resources or perhaps a "production/staging" environment separate.

**Notes**
- Please consider how this would work with the proposed API feature request (#74) as this would mean additional endpoints would have to be implemented.
- Please consider how this would work with (#45) as a project could be the equivalent of a "namespace" on kubernetes; a single service mesh tool like Istio could be used for scaling across multiple clusters via Kubernetes, among other overlaps i.e. roles, where necessary - impacting the implementation of this feature.

**Comment by andrasbacsai** [comment]
It's partly - if not entirely - implemented in v2.

You could have separation by teams on the UI and docker network on the docker/server levels.

Environments like prod/staging would be implemented later, but it needs to be figured out how. 😄

**Comment by robertorubioguardia** [comment]
Hi @andrasbacsai Loving Coolify.

One detail: If I have registration closed, I cannot invite new members to teams. From a management point of view, I would like to create my teams (as I am the server admin) and then invite people to specific teams.

Is that possible?

**Comment by andrasbacsai** [comment]
> Hi @andrasbacsai Loving Coolify.
> 
> One detail: If I have registration closed, I cannot invite new members to teams. From a management point of view, I would like to create my teams (as I am the server admin) and then invite people to specific teams.
> 
> Is that possible?

Thanks! Yes, it will be possible if I add [SMTP integration](https://github.com/coollabsio/coolify/issues/181).

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
