### ISSUE TITLE
[Feature]: Plausible script rename

### ISSUE THREAD

**Issue by njts** [coollabsio/coolify#774]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

In previous versions of Coolify, I have been able to change the script name of plausible (plausible.js). I just installed the latest version of Coolify, but I couldn't find this feature. How can I change the script name in the new version?

### Why should this be worked on?

It was a good feature.

**Comment by simonorzel26** [comment]
The api still has this feature but maybe there was a reason for taking it out of the client.

https://github.com/coollabsio/coolify/blob/adf82c04ad4f92eff0522b864430c8b99c4893c8/apps/api/src/lib.ts#L444-L457

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
