### ISSUE TITLE
[Bug]: Updates doesn't work

### ISSUE THREAD

**Issue by chz** [coollabsio/coolify#777]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

My version is: v3.11.13 but there is currently v3.12 bu my coolify don't want update. 

### Steps To Reproduce

I can't see update icon

### Version

3.11.13

**Comment by themarkwill** [comment]
@chz In real this not is a problem, the Release is in 3 parts.
1. First is created release here, on GitHub, and build package.
2. The @andrasbacsai need test the final version
3. Add on static file of updates https://github.com/coollabsio/get.coollabs.io/blob/main/static/versions.json -> this is when you get the shiny button (or your instance gets autoupdated)

When have a version here, and not in version, normally if has anything pending.

**Comment by chz** [comment]
Oh :( Sorry mu bad. I didn't know about that process

> @chz In real this not is a problem, the Release is in 3 parts.
> 
> 1. First is created release here, on GitHub, and build package.
> 2. The @andrasbacsai need test the final version
> 3. Add on static file of updates https://github.com/coollabsio/get.coollabs.io/blob/main/static/versions.json -> this is when you get the shiny button (or your instance gets autoupdated)
> 
> When have a version here, and not in version, normally if has anything pending.

Oh :( Sorry my bad. I didn't know about that process

**Comment by andrasbacsai** [comment]
@themarkwill is right. You can now update to 3.12.1 😄
