### ISSUE TITLE
[Bug]: "Auto update enabled?" didn't preserve state.

### ISSUE THREAD

**Issue by chz** [coollabsio/coolify#778]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I switch auto update enabled to ON but after restart coolify it's back to OFF

### Steps To Reproduce

I switch auto update enabled to ON but after restart coolify it's back to OFF

### Version

3.11.13

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
