### ISSUE TITLE
[Feature]: Add ability to modify traefik config

### ISSUE THREAD

**Issue by snimshchikov** [coollabsio/coolify#779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add support for custom traefik dinamic config (via file)

### Why should this be worked on?

It can be implemented without visual interface (just few lines of code) and will allow to add custom params on the fly

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
