### ISSUE TITLE
[Feature]: Track last selected team and automatically select it again on login

### ISSUE THREAD

**Issue by rayzr522** [coollabsio/coolify#787]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

when dealing with multiple teams, I find that I am always reverted back to my own team when logging in to Coolify rather than whatever team I had last selected. it would be preferable if the last team I was on was tracked either in a cookie or in the db so it could be automatically selected when i log in next. presumably would also need another quick check to make sure I still have access to my last selected team

### Why should this be worked on?

would be a pretty big UX improvement -- ik it sounds minor, but at work we have everything under a shared team and since the token cookie has an expiry of Session, this means I'm _constantly_ having to re-select the shared team every single time i log in. it's a pretty frustrating UX and one that should be trivial to resolve, so could be a quick win

**Comment by andrasbacsai** [comment]
This is how it works in v4.

I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
