### ISSUE TITLE
[Bug]: Laravel 9 Yarn Command Issue

### ISSUE THREAD

**Issue by wildangunawan** [coollabsio/coolify#788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Laravel, starting from version 9, no longer using Laravel Mix to compile frontend things. Laravel moved to Vite for this.

Therefore, `yarn production` during image building won't work since they're no longer have that command.
![image](https://user-images.githubusercontent.com/35158077/207555439-dc8d32c0-da42-4e76-9e25-992656640b28.png)

To solve this issue, I think it's simply to change [this line](https://github.com/coollabsio/coolify/blob/main/apps/api/src/lib/buildPacks/common.ts#L801) from `yarn production` to `yarn build`. But that will create new issue for devs that haven't moved to Vite yet. Probably adding configuration for user to select either Vite (`yarn build` instead) or Mix (`yarn production`)?

**For other developers that run to this issue**

This issue can be solved easily by adding "production" script in your `package.json` file.
![image](https://user-images.githubusercontent.com/35158077/207555771-dfcd864c-29d9-48c5-a505-f1791d1e2b53.png)

### Steps To Reproduce

1. Create a new Laravel version 9 application
2. Run in Coolify
3. Failing at step 5/5

### Version

3.12.1

**Comment by wildangunawan** [comment]
Also I think it's not only that. Since they moved from Webpack+Mix to Vite, the config file also changed.

![image](https://user-images.githubusercontent.com/35158077/207558055-a71a40ea-366d-484c-9d21-41f275667754.png)

should be changed to `COPY *.json *.config.js /app/` (or something like that) as well.

**Comment by MichaelNZ85** [comment]
I'm having a similar problem deploying Laravel (both with and without a frontend). Here is the error message:

```
[00:17:00.908] #9 20.09 yarn run v1.22.19
[00:17:00.919] #9 20.12 $ vite build
[00:17:01.192] #9 20.44 vite v3.2.5 building for production...
[00:17:01.328] #9 20.58 ✓ 0 modules transformed.
[00:17:01.414] #9 20.58 Could not resolve entry module (index.html).
[00:17:01.445] #9 20.59 error during build:
[00:17:01.458] #9 20.59 Error: Could not resolve entry module (index.html).
[00:17:01.468] #9 20.59     at error (file:///app/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
[00:17:01.486] #9 20.59     at ModuleLoader.loadEntryModule (file:///app/node_modules/rollup/dist/es/shared/rollup.js:22175:20)
[00:17:01.492] #9 20.59     at async Promise.all (index 0)
[00:17:01.498] #9 20.63 error Command failed with exit code 1.
[00:17:01.504] #9 20.63 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[00:17:01.511] #9 ERROR: executor failed running [/bin/sh -c yarn install && yarn production]: exit code: 1
[00:17:01.556] ------
[00:17:01.569] > [5/5] RUN yarn install && yarn production:
[00:17:01.582] ------
[00:17:01.598] executor failed running [/bin/sh -c yarn install && yarn production]: exit code: 1
```

**Comment by wildangunawan** [comment]
Yep, that's, I suspect, because the Dockerfile didn't copy the config files (vite.config.js, postcss.config.js, and tailwind.config.js). Hence returned an error.

I tried running `vite build` on local and all good though.

**Comment by MichaelNZ85** [comment]
What needs to be done to fix this?

**Comment by zhinea** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Example public repository
> _No response_
> 
> ### Description
> Laravel, starting from version 9, no longer using Laravel Mix to compile frontend things. Laravel moved to Vite for this.
> 
> Therefore, `yarn production` during image building won't work since they're no longer have that command. ![image](https://user-images.githubusercontent.com/35158077/207555439-dc8d32c0-da42-4e76-9e25-992656640b28.png)
> 
> To solve this issue, I think it's simply to change [this line](https://github.com/coollabsio/coolify/blob/main/apps/api/src/lib/buildPacks/common.ts#L801) from `yarn production` to `yarn build`. But that will create new issue for devs that haven't moved to Vite yet. Probably adding configuration for user to select either Vite (`yarn build` instead) or Mix (`yarn production`)?
> 
> **For other developers that run to this issue**
> 
> This issue can be solved easily by adding "production" script in your `package.json` file. ![image](https://user-images.githubusercontent.com/35158077/207555771-dfcd864c-29d9-48c5-a505-f1791d1e2b53.png)
> 
> ### Steps To Reproduce
> 1. Create a new Laravel version 9 application
> 2. Run in Coolify
> 3. Failing at step 5/5
> 
> ### Version
> 3.12.1

you solved this?

**Comment by MichaelNZ85** [comment]
Simply adding `"production": "vite build"` to my `package.json` file didn't work. Still got the same error.

**Comment by wildangunawan** [comment]
> Simply adding `"production": "vite build"` to my `package.json` file didn't work. Still got the same error.

Yeah I alr reported another issue with the Dockerfile [here](https://github.com/coollabsio/coolify/issues/788#issuecomment-1350720353) and [this](https://github.com/coollabsio/coolify/issues/788#issuecomment-1351609313) (in fact that is my reply to your comment).

What can be done now? Best bet is to create your own Dockerfile, but I'm too lazy to make one lol. I already opened another issue (#789) to add feature to edit Coolify's Dockerfile template.

For now (since I also don't understand the source code of Coolify), either make our own Dockerfile (feel free to share here) or wait until Coolify team respond and solve the issue.

**Comment by MichaelNZ85** [comment]
If someone could make a Dockerfile and share it here, that would be great. I'm not familiar enough with Docker to do it myself.

**Comment by wallaceosmar** [comment]
Not for ARM
```
FROM node:18-slim as build
WORKDIR /app

COPY *.json *.js /app/
COPY resources /app/resources
RUN npm install && npm run build

# Production build
FROM webdevops/php-nginx:8.2-alpine
ENV WEB_DOCUMENT_ROOT=/app/public
WORKDIR /app
COPY --chown=application:application composer.* ./
COPY --chown=application:application database/ database/
RUN composer install --ignore-platform-reqs --no-interaction --no-plugins --no-scripts --prefer-dist

COPY --chown=application:application . ./
COPY --from=build /app/public/build /app/public/build

RUN php artisan optimize
RUN php artisan config:clear
```

**Comment by c0demon** [comment]
I'm here with a question that might be related, sorry, I know close to nothing about Laravel. My build of [https://github.com/mitchy-crypto/cryptosite.git](url) fails because "composer not found", I can see Composer is a package download on Ubuntu but am I supposed to trigger it somehow with these yarn finesses or is the problem even deeper?

**Comment by MichaelNZ85** [comment]
What's the latest with this?

**Comment by MichaelNZ85** [comment]
Any update?

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
