### ISSUE TITLE
[Feature]: Edit Coolify's Dockerfile template

### ISSUE THREAD

**Issue by wildangunawan** [coollabsio/coolify#789]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add a feature to edit Dockerfile from existing Coolify's applications template.

This can be simply a text editor where we can custom the Dockerfile for that template, before/after the build.

### Why should this be worked on?

I'm currently working on a Laravel project that I wanted to publish with Coolify. Currently, since Laravel made changes from Laravel Mix to Vite, I need to adjust some command in the Dockerfile. I also already address this issue in #788.

I also deployed a NodeJS application today that needed some package to be installed before compiling. Currently I'm using "Install command" to install all of the package needed. I stacked three command there. What if someone have a lot of command to be ran first hahaha.

If we can edit the Dockerfile on our own, we can use the template given by Coolify team and adjust it to our own use case. The template is very generic, hence it's probably work 90% but in the other 10% we kinda need some adjustment ;)

**Comment by MichaelNZ85** [comment]
I agree, this sounds like a great idea!

**Comment by simonorzel26** [comment]
Similar request [here](https://github.com/coollabsio/coolify/issues/873)

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
