### ISSUE TITLE
[RFC] Switching to TypeORM from Mongoose

### ISSUE THREAD

**Issue by badlanguage** [coollabsio/coolify#79]
Currently, Coolify relies on Mongoose (and MongoDB) to store relevant data to the application; while this functions as intended with MongoDB being very popular choice among enterprises - it however is by no means the `defacto` choice, usually many enterprises rely on SAP Hana, MySQL, Oracle, Postgres etc. the current choice of mongodb makes sense when one understands the scope of the project, but as Coolify matures, a more flexible ORM tool is required, one that interacts with many databases, such as TypeORM, which supports all listed databases (and alot more). This allows for true flexibility with a myriad of choices for databases.

While many may think that this is rare, one such instance is my own company - we use ArangoDB and Postgres exclusively as that is what we have our DBAs experienced with, it would make it a hassle for us to opt to use MongoDB (in production), likely increasing our costs and complexity of our team and stack. When considering enterprises, this does pose a huge problem for companies that would like to choose Coolify but bottlenecked by the choice of stack.

I believe this a right time to discuss this and perhaps even action this due to the work being rapidly progressed on ( #74  ) that allows for alot more flexibility out of the box, with minimal work.

**Comment by badlanguage** [comment]
Adding a little more context, WRT to the default setup: the project could (and should) still default to MongoDB with the installation process (in the form of Docker images); however with either ENV Variables or a configuration file, one can select which database Coolify should use, meaning minimal changes are needed for the setup.

**Comment by andrasbacsai** [comment]
By default, the new version of Coolify uses SQLite as the database itself is so simple. But maybe I will consider having an option to use it with MySQL or PostgreSQL.

I am closing this RFC for now. Thanks for your ideas!
