### ISSUE TITLE
[Bug]: Container won't be  removed  if  the service were deleted from dashboard 

### ISSUE THREAD

**Issue by baiyunlqy** [coollabsio/coolify#791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

Container won't be  removed  if  the service were deleted from dashboard 

### Steps To Reproduce

1. create service 
2. remove the service from dashboard
3. ssh to computer, the service still exists

### Version

v3.12.1

**Comment by zhinea** [comment]
same issue here

**Comment by simonorzel26** [comment]
**[Related](https://github.com/coollabsio/coolify/issues/865)**

**Comment by andrasbacsai** [comment]
I found the issue and shipping a fix soon!
