### ISSUE TITLE
[Bug]: Submodules are not cloned properly

### ISSUE THREAD

**Issue by chikof** [coollabsio/coolify#795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to deploy my app **which requires submodules** I get the following error
![image](https://user-images.githubusercontent.com/53100578/208321861-120bf419-fae6-471b-8b3a-007519388315.png)

### Steps To Reproduce

1. Create an application using submodules (both have to be private)
2. Try to deploy it
3. See the error in the build logs

### Version

3.12.1

**Comment by vncnt-mb** [comment]
Same problem here (v3.12.10)

I have a private repository (via an organization) with 2 private submodules.

The main error is : 
> could not read Username for 'https://github.com': No such device or address

The @ChikoShidori's screenshot is very similar to my situation

Or, Is it possible to create an option capable of ignoring submodules of a project? This will still allow us to launch the build (the subs just allow me to launch cypress tests, so not necessary)

Thanks ! :)

**Comment by themodernpk** [comment]
I am also facing similar issue

**Comment by a-c-m** [comment]
Seems like there is code somewhere to support submodules - https://github.com/search?q=repo%3Acoollabsio%2Fcoolify%20submodule&type=code

But not totally sure how to enable it.

**Comment by chikof** [comment]
> Seems like there is code somewhere to support submodules - https://github.com/search?q=repo%3Acoollabsio%2Fcoolify%20submodule&type=code
> 
> But not totally sure how to enable it.

That's v4, this issue was created for v3
