### ISSUE TITLE
[Bug]: v3.12.2 update breaks Docker builds

### ISSUE THREAD

**Issue by whitesidest** [coollabsio/coolify#799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

After upgrading to the v3.12.2 update this morning, further deploys to my Docker images cause a build failure.  Rolling back to the last Coolify version fixed it immediately (after another deploy to get things  up again)..

The error in the logs is: 'unexpected character "'" in variable name'.

### Steps To Reproduce

Upgrade to latest version of Coolify.
Deploy a Docker image.

### Version

3.12.2

**Comment by andrasbacsai** [comment]
Sorry about it. I will fix this soon.

**Comment by whitesidest** [comment]
No worries at all.  It took less than a moment to fix and only impacted a hobby project.

**Comment by andrasbacsai** [comment]
Could you please check with `v3.12.3`?

**Comment by whitesidest** [comment]
It works!  Thank you so much for your time.  I appreciate your work and the product you have made.

**Comment by whitesidest** [comment]
It appears I spoke too soon. The build works but the environment variables are not getting picked up.  As if they are not accessible to the app.
