### ISSUE TITLE
[Bug]: Old tags when trying to make a service update

### ISSUE THREAD

**Issue by mkilinskidev** [coollabsio/coolify#805]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

I am using the n8n service and would like to do an upgrade to the newest version. While a container is stopped, on the tag lists there are only old tags.

BTW. The newest n8n version is 0.209.0 but when I'm creating a new service, coolify automatically prompt the 0.207.0 version.

![image](https://user-images.githubusercontent.com/13047961/209087508-5d7a9b80-feda-4c3e-b2a1-61b75dced675.png)

### Steps To Reproduce

Create a new service and try to select version 0.20x.0

### Version

3.12.4

**Comment by andrasbacsai** [comment]
Will fix this in the next version!

**Comment by andrasbacsai** [comment]
I've updated the script that generates the tags so that the new tags will be available in 10 minutes on your instance. Let me know if it is still not working.

**Comment by Auran0s** [comment]
Hi! we now have access to the most recent tags, but not to the latest one from 2 days ago.
![image](https://user-images.githubusercontent.com/55290351/211844807-a5c215fa-8a74-472e-8703-64cee21249bf.png)

**Comment by mkilinskidev** [comment]
Have you updated the tag list once or wrote a code to refresh tag's list every time? Because as @Auran0s said, there aren't the newest tags on the list. The same issue is f.ex. in Appsmith application. 
![image](https://user-images.githubusercontent.com/13047961/212461005-578369fe-6857-4d60-a90f-a862def1f7ab.png)
![image](https://user-images.githubusercontent.com/13047961/212461027-7219e88e-d606-4b22-aaa6-825532843e5d.png)

**Comment by mkilinskidev** [comment]
@andrasbacsai can you please refer to the question above? Currently, the newest version of n8n is 0.211.2 but in the Coolify there is 0.210.1. Same with appsmith - the newest is 1.9.3 but in the Coolify is 1.9.1

**Comment by qwertyuu** [comment]
@andrasbacsai I think we should reopen the issue, I have the same problem as everyone here. The versions that are available for n8n through coolify stop at 0.210.1 but 0.212 exists in the n8n repository. 

I would like my coolify to be able to fetch its own tags and not be dependent on a json file that is in coolify. I would also like coolify to be able to fetch newer tags without needing to update coolify itself!

Thanks

**Comment by mkilinskidev** [comment]
@andrasbacsai are you there? Could you check above conversation?
