### ISSUE TITLE
[Bug]: When i config with "bla bla" (have ") is error say Unexpected string in JSON at position 301

### ISSUE THREAD

**Issue by itorz7** [coollabsio/coolify#808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

When i edit Service and config with ""
![image](https://user-images.githubusercontent.com/30155968/209214609-e326dce5-c743-4374-8852-f68861a4d326.png)
and error with
![image](https://user-images.githubusercontent.com/30155968/209214715-31775d5e-9cb9-4095-a56e-9811e11ac6c2.png)

### Steps To Reproduce

1. Go to some service
2. Edit config
3. use ""

### Version

3.12.4

**Comment by itorz7** [comment]
and why "Disable External Database" is not working

i try run with 
"docker run -d --name nocodb \
-v "$(pwd)"/nocodb:/usr/app/data/ \
-p 8080:8080 \
nocodb/nocodb:latest"
that worked, idk it error at nocodb or coolify template T_T
![image](https://user-images.githubusercontent.com/30155968/209215781-c63c5d3b-1262-4393-a7cd-6bf0cc48c404.png)

![image](https://user-images.githubusercontent.com/30155968/209215768-1002311d-a968-412f-9c8a-48befb75ec04.png)

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
