### ISSUE TITLE
[Bug] Auto-fill not working

### ISSUE THREAD

**Issue by mjpikat** [coollabsio/coolify#810]
Windows 11, Firefox browser, by using iCloud Keychain autofill getting the following error:
`Cannot read properties of undefined (reading 'toLowerCase')`

**Comment by Tiagofv** [comment]
We need more information here. Where are you facing the problem?
Please attach screenshots and more details.

**Comment by mjpikat** [comment]
> e

Hi Tiago, no worries, I will make you some screenshots in a while.
I am facing the problem on the login screen and it pops up on top when I try autofill.

**Comment by mjpikat** [comment]
> We need more information here. Where are you facing the problem? Please attach screenshots and more details.

![image](https://user-images.githubusercontent.com/8924515/209665953-d1f3e5f0-9893-44de-8b89-b10ba175ac87.png)

**Comment by mjpikat** [comment]
Also worth mentioning this issue does not happen with in-built password manager/autofill.
The browser is Google Chrome, version 108.0.5359.125

**Comment by carvalholeo** [comment]
For other hand, I can see a similar problem on my iPhone.

I use Bitwarden as my password manager and in general, Microsoft Edge as my main browser. When I try to make login by mobile device, I find the following error:

'Email and password are required'

To do a login, I need to backspace the last password character and then type manually again, so I can be able to login.

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
