### ISSUE TITLE
[Feature]: Crash Logs when container exists / closes

### ISSUE THREAD

**Issue by SaadBazaz** [coollabsio/coolify#812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I don't know if this is a Docker thing or a Coolify thing, but sometimes my containers are closing unexpectedly / crashing, and I'd like to debug the issue from the logs.

![image](https://user-images.githubusercontent.com/51885228/209662129-41eabfce-1044-4d79-a982-6b6945caf8b5.png)

Maybe a button called "See old logs" or something might be useful here.

Also, is there an autoredeploy / restart function in Coolify?

### Why should this be worked on?

 It's important to learn why things aren't working.

**Comment by andrasbacsai** [comment]
This part needs to improve for sure. Are you using Docker Compose buildpack?

**Comment by SaadBazaz** [comment]
> This part needs to improve for sure. Are you using Docker Compose buildpack?

Yes, mostly. Also some node build packs.
