### ISSUE TITLE
[Bug]: plausible configuration features are not valid

### ISSUE THREAD

**Issue by jesperordrup** [coollabsio/coolify#815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

When I try to configure plausible for registration, the only options are disable and enable. Disable Registration should have 3 possible values

```
true
false
invite_only
```

![image](https://user-images.githubusercontent.com/3120151/209981294-ca4af031-8f88-4a79-9999-61a53fd811f7.png)

**Futher info:**
https://github.com/plausible/analytics/pull/1841#issuecomment-1354976378

### Steps To Reproduce

1. stop plausible service (v1.5.1)
2. go to config
3. Find `Disable registration` and see if you can find `invite_only`

![image](https://user-images.githubusercontent.com/3120151/209981961-ca58c133-2960-4f25-83e4-63e99346dc1a.png)

Ekstra: 

I hope that the fields in UI will get some tlc. Its not easy to understand what the end result of disabling a "disable " field. 

Suggestion

```
Authentication:                 enable/disable
(disable_authentication)

Registration :                  enable/disable/invite_only
(disable_registration)
```

### Version

3.12.8

**Comment by andrasbacsai** [comment]
I'm adding this feature to the next release!
