### ISSUE TITLE
[Bug]: Environment Variables with $ dollar sign

### ISSUE THREAD

**Issue by bassra** [coollabsio/coolify#820]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi, 

First of all i am thankful to the Dev team for producing such a great application.

Currently i am facing an issue with environmental variables. if an environmental variable has a "$" dollar sign, coolify only passes the part of variable which is before $ sign. I have tested  it on a python application with DockerFile file.

for example: 
`secret = dsfla83hkh$ksdhc`

coolify will only set dsfla83hkh value to secret.

Regards

Sami

### Steps To Reproduce

A python app having a environmental variable/secret with $ dollar sign.

### Version

v3.12.8

**Comment by carvalholeo** [comment]
Hey, I had the same problem and the logs said to put a second dollar sign, so the first is ignored as a system environment variable. Could you test if this solves your problem, as a workaround?

**Comment by bassra** [comment]
> 

Hey @carvalholeo , it works. thanks.

**Comment by andrasbacsai** [comment]
I will add a fix to the new version, so you do not need to add double `$` signs.
