### ISSUE TITLE
[Feature]: Need to share docker endpoints between user and team

### ISSUE THREAD

**Issue by polawich** [coollabsio/coolify#821]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

in this case , we tried to add remote docker endpoint by admin user. we add multiple users to server for allowing users run their own application. We could reuse the remote docker endpoint that has been already added by the admin user but at moment we cannot do that. the only way and solution the user must add the dedicated remote endpoint by individually.

### Why should this be worked on?

it would be better if we can manage the permission of endpoints that share with user and team

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
