### ISSUE TITLE
[Feature]: Need more configuration on user permission metrix

### ISSUE THREAD

**Issue by polawich** [coollabsio/coolify#822]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

at moment, We cannot customize the permission for user and team. in examples,
- all users that register themselves can see Service, Databases, Git Sources,  Destination
- in some case, some user or team are not allowed to use Databases and we need to limit by permission

### Why should this be worked on?

to fine grain the permission of user and groups for security control
- we need to limit the permission to non-root user

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
