### ISSUE TITLE
[Bug]: Remote docker engine fails when user is not root

### ISSUE THREAD

**Issue by murdockq** [coollabsio/coolify#823]
## Is there an existing issue for this?
I have searched the existing issues

## Steps To Reproduce
Setup a new remote docker engine using a non-root user

## Version
v3.12.8

## Description
I setup a new instance on ec2 using the Amazon Linux 2 which has a user name of ec2-user.

Then when I configured the ssh to remote into and use the ec2-user name it fails to run these commands since they require root privileges to execute:

`Error while verifying remote docker engine`
https://github.com/coollabsio/coolify/blob/adf82c04ad4f92eff0522b864430c8b99c4893c8/apps/api/src/routes/api/v1/destinations/handlers.ts#L254

https://github.com/coollabsio/coolify/blob/adf82c04ad4f92eff0522b864430c8b99c4893c8/apps/api/src/routes/api/v1/destinations/handlers.ts#L245:L255

I didn't figure out which commands failed but seeing as how /etc/docker/ is owned by root on my instance and the systemctl all requires sudo to run, they both would fail. 

The easiest solution would be to add sudo to the commands so that they have proper privileges to run, but I'm not sure all the areas this problem might persist.

**Comment by kevindesousa** [comment]
same here

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
