### ISSUE TITLE
[Bug]: Install fails on a fresh Ubuntu 20.04.4 server

### ISSUE THREAD

**Issue by faierbol** [coollabsio/coolify#826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

Running:
```
wget -q https://get.coollabs.io/coolify/install.sh \
-O install.sh; sudo bash ./install.sh
```
i get:
`no such file or directory `

### Steps To Reproduce

deploy a fresh Ubuntu 20.04.4 server with firewall disabled and try to install coolify as in the documentation by running 

wget -q https://get.coollabs.io/coolify/install.sh \-O install.sh; sudo bash ./install.sh

### Version

latest

**Comment by faierbol** [comment]
deployed debian 11, same error occurs :(

**Comment by faierbol** [comment]
is there anything that i am missing?

**Comment by faierbol** [comment]
any help on this!

**Comment by andrasbacsai** [comment]
I tried both operating systems, and both worked well. Can you please paste the full log here? And also paste the debug logs by executing the same script with the `-d` flag. 

`wget -q https://get.coollabs.io/coolify/install.sh -O install.sh; sudo bash ./install.sh -d`

**Comment by faierbol** [comment]
![image](https://user-images.githubusercontent.com/6561107/211292135-3ac9e19b-9482-4654-98c0-0eedb3748046.png)

**Comment by faierbol** [comment]
this is what i get

**Comment by faierbol** [comment]
no firewall is enabled, wget is working

**Comment by faierbol** [comment]
total mystery :). deployed a fresh new ubuntu vm and it worked

**Comment by andrasbacsai** [comment]
> ![image](https://user-images.githubusercontent.com/6561107/211292135-3ac9e19b-9482-4654-98c0-0eedb3748046.png)

After `https` there is a `;` not a `:`.
