### ISSUE TITLE
[Bug]: Fresh Umami service, cannot login

### ISSUE THREAD

**Issue by danbburg** [coollabsio/coolify#827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

NA

### Description

Try to spin up a completely default Umami instance. Service starts fine and is healthy. 
Cannot login with admin + <ADMIN_PASSWORD> from secrets OR admin + umami (umami docs)

receive "Incorrect username/password." error message

I checked umami docs and found that default user/pass is admin/umami but that does not work. In the coolify config tab I see the initial admin password box (also in the secrets tab I see the ADMIN_PASSWORD) but this also does not work. 

I expect the <ADMIN_PASSWORD> in secrets to work with the username "admin"

Maybe this is not a bug and I missed some info, but I also don't see anything in coolify docs (umami service just links to their GitHub repo)
Thanks in advance!

### Steps To Reproduce

Coolify version 3.12.8
1. Create New Resource -> Service -> Umami
2. Configuration page:
- Set FQDN
- leave version / tag at default: "postgresql-v1.39.5"
3. Save
4. Deploy
5. go to resource
6. enter credentials "admin" / <ADMIN_PASSWORD>

### Version

3.12.8

**Comment by TheTeaCup** [comment]
I am having the same issue ^^

**Comment by andrasbacsai** [comment]
I fixed the problem, it will be added to the next release.
