### ISSUE TITLE
[Feature]: Passthrough coolify app settings as secret

### ISSUE THREAD

**Issue by wallaceosmar** [coollabsio/coolify#828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I am having problem with multiple preview because the url used in the app come from the secret and broke any other preview if not change the secret
```
BASE_URL=https://example.com
BASE_URL_API="${BASE_URL}/api"
```
if we have access to some settings like the fqdn
```
BASE_URL=${COOLIFY_FQDN}
BASE_URL_API="${COOLIFY_FQDN}/api"
```

### Why should this be worked on?

Should be good to have this feature to make more easy to change the url of the preview app

**Comment by a-c-m** [comment]
Related to https://github.com/coollabsio/coolify/issues/1016 ?
