### ISSUE TITLE
[Bug]: No local images to revert to

### ISSUE THREAD

**Issue by 0xStrobe** [coollabsio/coolify#830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

No local images are saved automatically, so the Revert tab is always empty. I'm not sure if there's anything extra that I needed to do to enable this feature. Maybe I have accidentally activated automatic cleanups in Coolify somewhere?

### Steps To Reproduce

1. Deploy a Node.js app via GitHub
2. Push code to GitHub to trigger automatic deployment
3. Wait for new build to be deployed
4. Go to the Revert tab
5. No pervious builds can be found

### Version

3.12.5

**Comment by andrasbacsai** [comment]
This is already fixed in 3.12.10, if not, please reopen the issue! Thanks!
