### ISSUE TITLE
[Bug]: Cannot open the web app running on a remote docker engine

### ISSUE THREAD

**Issue by aghasemi** [coollabsio/coolify#833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

Hello,

I am trying to host a web application using Coolify on a "remote" docker engine. I however either get 404 or "Invalid certificate" on the target URL. Is there some extra step required compared to the local docker engine? I couldn't find anything on the documentation. There is already a bot running on the remote docker without issues, and the  "custom proxy" is disabled.

Thanks a lot

P.S. In both cases (404 and Invalid Certificate) the URL is correctly resolved and pinging works. By the way, I just saw that the custom proxy has been enabled (automatically?). I have tried setting the address in my DNS record to both the IP of the machine where Coolify is running and the IP of the remote Docker machine (which one id the right way?). Also, does enabling the custom proxy on remote machine make a difference?

### Steps To Reproduce

- Try to deploy a web application on a remote docker engine

### Version

3.12.8 (also had this on earlier version, as old as 3.10.* as far as I remember)

**Comment by MyWay** [comment]
Same

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
