### ISSUE TITLE
[Feature]: Modifying and exporting secrets in text format + a central secrets file

### ISSUE THREAD

**Issue by aghasemi** [coollabsio/coolify#835]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Hi,

Currently, we need to enter and modify secrets manually and per deployment. We can also _import_ them from a `.env` file, but then again we can only modify them in UI input fields, not as the text `.env` file anymore.

What I suggest is to be able to not only import but also modify and export secrets, all in the `.env` format in a text area instead of multiple text boxes.

Even better would be to have a _central_ secrets file for the whole Coolify, from which we can then import individual secrets per project/deployment. That central secrets file can be synchronised with a Git repository as well.

### Why should this be worked on?

It will make it more convenient and robust to work with and maintain secrets.

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.

**Comment by andrasbacsai** [comment]
It will be added to v4.
