### ISSUE TITLE
[Feature]: Laravel Queues & Scheduler(CRON) Support

### ISSUE THREAD

**Issue by zek** [coollabsio/coolify#839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

We need Laravel Queues & Scheduler(CRON) support for production deployments of Laravel applications.

### Why should this be worked on?

Laravel queues (see https://laravel.com/docs/9.x/queues) and scheduler (https://laravel.com/docs/9.x/scheduling) are used in almost every application. Without supporting these features laravel deployments will not be production ready.

**Comment by zek** [comment]
To overcome this problem, we need to create 2 more applications with a custom docker file (which requires maintaining 3 env files in total)

- For laravel queues https://github.com/renoki-co/laravel-docker-base/blob/master/Dockerfile.worker
- Any docker crontab image such as https://github.com/willfarrell/docker-crontab

**Comment by faierbol** [comment]
Hi, anyone can share a production ready docker-compose.yml example which includes the laravel queues and scheduling?

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.

**Comment by victorlap** [comment]
I've opened a new discussion for this feature request https://github.com/coollabsio/coolify/discussions/2468
