### ISSUE TITLE
[Bug]: Cannot delete application with previews

### ISSUE THREAD

**Issue by zek** [coollabsio/coolify#846]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

When deleting an application which has previews.

It gives following error.

```
"\nInvalid `prisma.application.deleteMany()` invocation:\n\n\nForeign key constraint failed on the field: `foreign key`"
```

### Steps To Reproduce

1. Create an application
2. Enable PR/MR previews feature
3. Create a PR and preview.
4. Try to delete application

### Version

3.12.10

**Comment by andrasbacsai** [comment]
Nice catch! I will add a fix to the next version!
