### ISSUE TITLE
[Bug]:  Docker buildpack with docker-compose breaking Logs

### ISSUE THREAD

**Issue by Aviortheking** [coollabsio/coolify#848]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

https://github.com/Aviortheking/test_coolify

### Description

When You add a Docker buildpack the logs are inacessible because the log part think it is a docker-compose application.

### Steps To Reproduce

1. create application with the repo above
2. launch the application
3. Try to see the logs for the docker image

### Version

3.12.10

**Comment by andrasbacsai** [comment]
I tried to reproduce it, but your example repository has an empty docker-compose file. I fixed a few issues because this case (empty compose) is not handled - will be added to the next release.

If I use `Docker` buildpack, it works perfectly.
