### ISSUE TITLE
[Bug]: cleanupUnconfiguredApplications removes docker-compose applications

### ISSUE THREAD

**Issue by zek** [coollabsio/coolify#850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

When I clean unconfigured applications it also deletes running `docker-compose` applications.

Also after a while, docker-compose applications looks like "not configured" in the interface.

<img width="404" alt="image" src="https://user-images.githubusercontent.com/3463291/212482905-57c35e7a-e0ad-49ad-97b9-7c798d171abf.png">

### Steps To Reproduce

1. create a docker-compose application

### Version

3.12.10

**Comment by andrasbacsai** [comment]
Fixing this in the next version.
