### ISSUE TITLE
[Bug]:  Domain in showing 404 error

### ISSUE THREAD

**Issue by mohitkumawat310** [coollabsio/coolify#851]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

When I deploy a node js application on a domain using node js on the latest version of coolify my domain shows a 404 error.

### Steps To Reproduce

Go to create an application
Select auto-detected node js image after github selection
add all the details including domain details
save and deploy
deploy will be successful but app will not be accessible on latest domain

### Version

3.12.1

**Comment by simonorzel26** [comment]
Could be DNS settings or application routing, need more info

**Comment by mohitkumawat310** [comment]
No it wasn't related to dns I checked that. It was probably the application
routing. And also after that i downgraded to the below version and coolify
got crashed. Installed it again

**Comment by mohitkumawat310** [comment]
Okay got some more info about this
Actually, this issue came after updating to Version 3.12.4

**Comment by mohanyadav** [comment]
Existing server stopped working after upgrading. Giving a 404 page when visiting the link

**Comment by mohitkumawat310** [comment]
> Existing server stopped working after upgrading. Giving a 404 page when visiting the link

Downgrade to version 3.12.3 from settings
and redeploy the app

**Comment by mohanyadav** [comment]
> > Existing server stopped working after upgrading. Giving a 404 page when visiting the link
> 
> Downgrade to version 3.12.3 from settings and redeploy the app

I am unable to access the coolify dashboard. I self hosted it on AWS and while running docker ps -a it shows as exited.
![image](https://user-images.githubusercontent.com/11350400/217018148-6e7d7173-3707-42fa-a974-366c2c7a6e67.png)

I tried running docker run image-name and it is showing this error
![image](https://user-images.githubusercontent.com/11350400/217017920-4ba3d9a5-29f0-495b-8a1e-3e9c6d08dc71.png)

**Comment by mohitkumawat310** [comment]
> > > Existing server stopped working after upgrading. Giving a 404 page when visiting the link
> > 
> > 
> > Downgrade to version 3.12.3 from settings and redeploy the app
> 
> I am unable to access the coolify dashboard. I self hosted it on AWS and while running docker ps -a it shows as exited. ![image](https://user-images.githubusercontent.com/11350400/217018148-6e7d7173-3707-42fa-a974-366c2c7a6e67.png)
> 
> I tried running docker run image-name and it is showing this error ![image](https://user-images.githubusercontent.com/11350400/217017920-4ba3d9a5-29f0-495b-8a1e-3e9c6d08dc71.png)

See the manual [Installation guide](https://docs.coollabs.io/coolify/installation) 

And edit environment variables

**Comment by mohanyadav** [comment]
> > > > Existing server stopped working after upgrading. Giving a 404 page when visiting the link
> > > 
> > > 
> > > Downgrade to version 3.12.3 from settings and redeploy the app
> > 
> > I am unable to access the coolify dashboard. I self hosted it on AWS and while running docker ps -a it shows as exited. ![image](https://user-images.githubusercontent.com/11350400/217018148-6e7d7173-3707-42fa-a974-366c2c7a6e67.png)
> > 
> > I tried running docker run image-name and it is showing this error ![image](https://user-images.githubusercontent.com/11350400/217017920-4ba3d9a5-29f0-495b-8a1e-3e9c6d08dc71.png)
> 
> See the manual [Installation guide](https://docs.coollabs.io/coolify/installation) 
> 
> And edit environment variables 


Thanks.The issue was with my domain provider and not with coolify
