### ISSUE TITLE
[Feature]: Add SOURCE_COMMIT and SOURCE_BRANCH ENV variables

### ISSUE THREAD

**Issue by zek** [coollabsio/coolify#854]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Adding build-time or runtime-variables such as SOURCE_COMMIT, SOURCE_BRANCH, SOURCE_PRMR_ID.

### Why should this be worked on?

I see that there's such a SOURCE_COMMIT build arg in:
https://github.com/coollabsio/coolify/blob/main/apps/api/src/lib/buildPacks/common.ts#L707

It didn't work for docker-compose builds I believe it's for Dockerfile builds. 
I belive if we make these variables it will be easier to manage versioning easily track errors for each release.

For example in sentry we can set `SENTRY_RELEASE` env variable so each error assigned to a spesific release. If we expose these env or build variables it will be easy to set `SENTRY_RELEASE` env variable.

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/3463291/212656541-7df991e2-7673-49f5-9cc4-1fc5d222b593.png">

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
