### ISSUE TITLE
[Bug]: Deleted or hidden PostgreSQL databases

### ISSUE THREAD

**Issue by ivangsm** [coollabsio/coolify#865]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

Days ago, I stopped many PostgreSQL instances, updated the Coolify instance and now when I started the instances, there's no data in any database, I think that instead of use the existing data volume Coolify creates a new one and started a DB from zero.

I have six instances, but when I list the volumes related to Postgres, there are more than double, there's a way that I can recover the instances with the old data or recover the data itself?

I think the data that was changed is the **Host** in general configuration, but is a non-editable field.

### Steps To Reproduce

I've not tried to reproduce the issue

### Version

3.12.13

**Comment by simonorzel26** [comment]
I also have an instance of a ghost PostgreSQL db running on my machine.  Can confirm

**Comment by simonorzel26** [comment]
[Possible Fix](https://github.com/coollabsio/coolify/issues/869)

**Comment by andrasbacsai** [comment]
I found the issue and shipping a fix soon!

**Comment by ivangsm** [comment]
Hi @andrasbacsai with this fix I'll be able to use my old volumes with my data instead of the empty new ones?
