### ISSUE TITLE
[Bug]: All apps died automatically 

### ISSUE THREAD

**Issue by scshiv29-dev** [coollabsio/coolify#875]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

![image](https://user-images.githubusercontent.com/68141773/213798518-5f1a5cf8-cb67-4bcb-b076-302de1d1f51f.png)
 getting this issue in ghost 
and 
![image](https://user-images.githubusercontent.com/68141773/213798636-7710da27-b9dd-4338-af15-370f5266515b.png)
 this in plausible analytics they stopped working automatically were working yesterday 

### Steps To Reproduce

really dont know what caused it

### Version

3.12.16

**Comment by kevmille** [comment]
I had the same issue with Plausible today. I had to Stop then Deploy again. It is working again.
