### ISSUE TITLE
[Bug]: Gitlab Integration Can't List Personal Repository

### ISSUE THREAD

**Issue by raniaamina** [coollabsio/coolify#878]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I try to integrate gitlab account into coolify, all organization and group repos are listed when i try to create new apps, but not for personal repository.

What i expect is, when i connect gitlab account to Coolify, all repository will listed, including personal repos (both private or public repos)

### Steps To Reproduce

1. Add git sorce
2. Choose gitlab, and do as written in docs
3. After all connected, add new apps from gitlab
4. Check listed repos

### Version

3.12.17

**Comment by BaNkIck** [comment]
I can confirm this happens to me too. Exact same issue. I can see my groups but not my personal projects. Since the "New application page" requires selecting a group first, there is no way to choose a personal project on the second dropdown.

**Comment by jloewe** [comment]
I've looked into this and the code already accounts for personal repositories.
The only thing that is missing is adding the username to the groups list.

This could be done by adding the following code after this line: https://github.com/coollabsio/coolify/blob/main/apps/ui/src/routes/applications/%5Bid%5D/configuration/_GitlabRepositories.svelte#L58

```ts
groups.push({
  full_name: username,
  name: username
});
```

I tried it out locally in the devcontainer and it worked fine.
