### ISSUE TITLE
[Feature]: Central build log for all builds either running or queued globally

### ISSUE THREAD

**Issue by Flexicon** [coollabsio/coolify#880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

It would be nice to have a single place to see all builds that are currently running on my Coolify server.

### Why should this be worked on?

Right now, in order to see which applications are currently running have builds queued, I need to click through each individual application and their corresponding builds tab.

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
