### ISSUE TITLE
[Bug]: No SSL cert for non-www domain for Docker Compose stack

### ISSUE THREAD

**Issue by cruonline** [coollabsio/coolify#881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

When using docker compose stack and having domain set with a www subdomain
ex.:
www.domain.com

When entering https://domain.com, before the redirect can trigger, I receive an SSL error
NET::ERR_CERT_AUTHORITY_INVALID

certificate is 
Subject: TRAEFIK DEFAULT CERT
Issuer: TRAEFIK DEFAULT CERT

looks like non-www cert is not generated, but there is no option to enable it for docker compose stack.

### Steps To Reproduce

1. create app with docker compose stack
2. setup domain with www subdomain
3. deploy
4. enter non-www url
5. grind your teeth ;-)

### Version

3.12.17 (also previously on 3.12.2)

**Comment by dissy123** [comment]
I also get the TRAEFIK DEFAULT CERT when publishing a new project, old projects are working and the certificate is also on the traefik instance in "/etc/traefik/acme/acme.json" but there is no new cert for the new site.

**Comment by dissy123** [comment]
My Problem today was that there was a CAA Entry on DNS. 

If there is a CAA Entry on the DNS than you also have to set the one for Letsencrypt.org also.
Otherwise you won't get a SSL Certificate from LetsEncrypt. https://letsencrypt.org/docs/caa/

CAA 0 issue „letsencrypt.org"

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
