### ISSUE TITLE
[Bug]: latest tags are missing 

### ISSUE THREAD

**Issue by TetrisIQ** [coollabsio/coolify#885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

The tags latest tags are missing if you create a new Instance.   
Services I checked (also checked if there is the latest tag on DockerHub):
- UptimeKuma 
- Whoogle
- Appsmith
- Appwrite
- Gitea  

So I assume it's the case for all services. 

### Steps To Reproduce

1. Create a new Service 
2. Try to use the latest tag 

### Version

v3.12.19

**Comment by Auran0s** [comment]
Refere to this #805

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
