### ISSUE TITLE
[Bug]: Persistent Volumes not working after deploy, restart needed

### ISSUE THREAD

**Issue by lgastler** [coollabsio/coolify#895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

https://github.com/lgastler/coolify-restart-env

### Description

When using persistent volumes, the persistent volume is inaccessible after a new deployment, either via git or by doing a force deploy. It seems an empty volume is handed, once the application is running again simply restarting it re-enables the access to the saved data on the persistent volume. 

Therefore, the workaround for now is to just restart your application manually after each deployment, since the saved data is accessible. 

### Steps To Reproduce

1. Deploy the NodeJS app from the example [repo](https://github.com/lgastler/coolify-restart-env)
2. Start the application
3. See the logs for the array of timestamps, after each deploy, there should be only one entry.
4. If you restart the app, then new entries are added.

### Version

3.12.17

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
