### ISSUE TITLE
[Feature]: Bulk editing of secrets

### ISSUE THREAD

**Issue by joeltargett** [coollabsio/coolify#897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

We have the ability to add secrets in batch from an .env, but it would be fantastic to also be able edit them in bulk format too inside a large textarea (through a toggle switch perhaps).

This is a standard feature in most PaaS providers like DigitalOcean App Platform, Caprover, Railway etc.

![image](https://user-images.githubusercontent.com/4231643/215718022-17c51134-a008-4643-9e9c-137692627b01.png)

![image](https://user-images.githubusercontent.com/4231643/215718624-50cd1be2-3682-4530-a5c1-e41cb3605e09.png)

### Why should this be worked on?

I have multiple versions of Coolify running on different servers, and trying to migrate apps between them (or other PaaS providers) when there are sometimes over 30 or 40 secrets each can be very time consuming.

A single, bulk, secrets list option makes it much simpler to perform a copy & paste migration - or for backup purposes.

Thanks for the great product!

**Comment by taoyuan** [comment]
I have been troubled by this issue for a while. It became tedious to manually copy each variable when deploying an application multiple times. So, I took matters into my own hands and wrote a [Tampermonkey script](https://github.com/taoyuan/coolify-monkey). I added two buttons on the Secrets page: "Toggle Secrets Visibility" and "Fetch Secrets."

![image](https://github.com/coollabsio/coolify/assets/4882922/e16e9f76-a3dd-460e-a2cf-ac2819a8c0d2)

**Comment by joeltargett** [comment]
What a time saver. Thanks!!

**Comment by taoyuan** [comment]
You're welcome! I'm glad to hear that it saved you time. 😊

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
