### ISSUE TITLE
[Bug]: Exposed Port 

### ISSUE THREAD

**Issue by ArdinDokht** [coollabsio/coolify#898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

Dear Andras Bacsai,

I hope this message finds you well. I wanted to bring to your attention an issue I've encountered while using the Coolify.

The exposed port specified in the Dockerfile is not working as expected. I'm unable to access the application running inside the container through the specified port. I got this error in some services too like "MinIO" .

 Here's a screenshot of the error I encountered:

![Screenshot 2023-02-01 131746](https://user-images.githubusercontent.com/64200985/216012916-358dcd2f-f524-4f75-b248-def9bbbafa41.png)
![Screenshot 2023-02-01 132309](https://user-images.githubusercontent.com/64200985/216012923-62c005c1-0dd0-40ce-b905-5d7ba3628387.png)
![Screenshot 2023-02-01 133217](https://user-images.githubusercontent.com/64200985/216012935-c73b40e2-dd52-4c36-89a2-dc23f2629145.png)

I've tried to resolve the issue on my own, but I wasn't able to find a solution. I would be grateful if you could help me with this.

Thank you for your time and assistance with this matter. I look forward to hearing back from you soon.

Best regards,
Ardin

### Steps To Reproduce

...

### Version

v3.12.17

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
