### ISSUE TITLE
[Feature]: download secrets

### ISSUE THREAD

**Issue by Corentin7301** [coollabsio/coolify#900]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add button to copy or download .env file includes environnements variables.

### Why should this be worked on?

It would allow to copy the variables in another project easily and quickly (I think of a Node.js instance containing many environment variables for example).
It would reverse the flow of "Past .env file".

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
