### ISSUE TITLE
[Bug]: Install not Working with docker 23.0.0

### ISSUE THREAD

**Issue by bitdoze** [coollabsio/coolify#901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

I am trying to install coolify but it fails with latest docker release:

+ sh -c docker version
Client: Docker Engine - Community
 Version:           23.0.0
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        e92dd87
 Built:             Wed Feb  1 17:47:51 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.0
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       d7573ab
  Built:            Wed Feb  1 17:47:51 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.16
  GitCommit:        31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

I get Docker version less than 20.10, please update it to at least to 20.10
./install.sh exited unexpectedly with status: 1

The problem is from the version that has 3 numbers now and looks like the script conditions are not ok.

### Steps To Reproduce

install coolify

### Version

3.0

**Comment by muhannad0** [comment]
there's an open PR https://github.com/coollabsio/get.coollabs.io/pull/11 that fixes this issue.

until that's merged, you can update the condition directly on the `install.sh` file and proceed with the installation.
```
# Comment out the following
#if [ "$SERVER_VERSION_MAJOR" -ge "$DOCKER_MAJOR" ] &&
#     [ "$SERVER_VERSION_MINOR" -ge "$DOCKER_MINOR" ]; then

# Update to new condition check 
 if [[ "$SERVER_VERSION_MAJOR" -gt "$DOCKER_MAJOR" || ( "$SERVER_VERSION_MAJOR" -eq "$DOCKER_MAJOR" && "$SERVER_VERSION_MINOR" -ge "$DOCKER_MINOR" ) ]]; then
     DOCKER_VERSION_OK="ok"
 fi
 ```

**Comment by paulocoutinhox** [comment]
I have the same problem :(

**Comment by paulocoutinhox** [comment]
@bitdoze copy the full modified file below and replace inside install.sh downloaded file:
https://raw.githubusercontent.com/coollabsio/get.coollabs.io/024a3734f1a32af158433a5bcf6002bf52381e37/static/coolify/install.sh

**Comment by hansipete** [comment]
helped me for installing it. thank you!
