### ISSUE TITLE
[Bug]: Persistent volume not working in Docker?

### ISSUE THREAD

**Issue by cramervincent** [coollabsio/coolify#904]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

Not sure if this is a bug or that I am doing something wrong but I have a Fastapi application deployed to docker, the Fastapi application uses a sqllite database stored in folder db (db/database.db).

I added "db/" to persistent volume but after each redeploy al my previous saved data is gone. This goed for manual redeploys aswell as for Github webhook deploys.

I allso changed te persistent volume to "db/database.db" with the same result.

### Steps To Reproduce

1. Deploy a Fastapi application using a sqlite db to docker
2. Add the db to the persisten volume
3. Add new entries to the db
4. Redeploy the application

### Version

2.5.2

**Comment by marlon360** [comment]
Where is your "db" folder?

When it is in the same folder as the application data, you have to use "/app/db".
If not try "/db".

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
