### ISSUE TITLE
[Bug]: MySQL can't connect with root user only with simple user

### ISSUE THREAD

**Issue by paulocoutinhox** [coollabsio/coolify#906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

n/a

### Description

When i start an MySQL server i can connect with "user" but not with "root user".

I put the same password on both users.

There is something special that i need for root user?

### Steps To Reproduce

n/a

### Version

3.12.18

**Comment by felixalguzman** [comment]
I have the same problem, is there a way to update the root password inside the container ?

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
