### ISSUE TITLE
[Bug]: Database fields are not editable

### ISSUE THREAD

**Issue by paulocoutinhox** [coollabsio/coolify#907]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

n/a

### Description

When i try create a new mysql, postgree or mariadb databases, all fields are not editable:

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/395096/217622355-3a56bfbf-77f7-4441-8a8c-a4fcb8f79a9b.png">

Only the password and only when i start:

<img width="1114" alt="image" src="https://user-images.githubusercontent.com/395096/217622701-f993c693-fe36-4404-87d6-a287bfe1fb32.png">

### Steps To Reproduce

1. Create a new database
2. Try edit it settings

### Version

3.12.18

**Comment by scshiv29-dev** [comment]
can i get assigned to this issue ? @paulocoutinhox  @andrasbacsai ?
Here are the proposed changes:

1. make sure almost all fields are editable
2. make sure they are editable when the database is stopped, some fields are not editable at all and some are editable while the database is running 
3. have appropriate prompt for all

**Comment by paulocoutinhox** [comment]
I found another problem that change "root user" while it is running throw error.

**Comment by scshiv29-dev** [comment]
@paulocoutinhox it is working for me maybe update your instance
