### ISSUE TITLE
[Bug]: Disk full error on Demo website

### ISSUE THREAD

**Issue by stefandevo** [coollabsio/coolify#910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When you try to register in the demo environment through the website, an error appears, saying disk full.

### Steps To Reproduce

Goto
[Register ](https://demo.coolify.io/register)
Create a new user.
Error.

### Version

demo

**Comment by r-arteaga** [comment]
2 months later, still disk full, cannot register
