### ISSUE TITLE
[Bug]: Auto update not happen 

### ISSUE THREAD

**Issue by paulocoutinhox** [coollabsio/coolify#911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

n/a

### Description

Hi,

I check auto-update some days ago but it don't happen.

<img width="1224" alt="image" src="https://user-images.githubusercontent.com/395096/217829744-6f2b53e2-69c5-4bf5-a611-df8cdff96a29.png">

It still on 3.12.17.

How to update manually?

### Steps To Reproduce

n/a

### Version

3.12.17

**Comment by paulocoutinhox** [comment]
The json has old version:

https://get.coollabs.io/versions.json

```
{
  "coolify": {
    "main": {
      "version": "3.12.17"
    }
  }
}
```

**Comment by hacknug** [comment]
The version has been bumped but still isn't using the latest released version from GitHub:

```
{
  "coolify": {
    "main": {
      "version": "3.12.33"
    }
  }
}

```

Is it because latest hasn't been tested enough and we're trying to avoid users having issues with the secret key again or is it something else unrelated?

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
