### ISSUE TITLE
[Feature]: Build notifications (Slack, Discord, Email, etc)

### ISSUE THREAD

**Issue by dotellie** [coollabsio/coolify#912]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

It would be great to have build notifications for when a build has successfully passed and been deployed or alternatively of course when it fails.

My main use would be Slack, but services like Discord and Email would also be nice to have.

### Why should this be worked on?

Would be nice as I find myself going to the dashboard sometimes just to monitor a specific build while I could just have been notified about it through Slack or something similar.

**Comment by scshiv29-dev** [comment]
are you working on this or may I take this ? @andrasbacsai

**Comment by andrasbacsai** [comment]
It is available in v4.

I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
