### ISSUE TITLE
[Bug]: All secrets are broken after reinstall coolify

### ISSUE THREAD

**Issue by paulocoutinhox** [coollabsio/coolify#913]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

n/a

### Description

Hi,

After reinstall with install script, all secrets values are broken. See:

<img width="902" alt="image" src="https://user-images.githubusercontent.com/395096/217907339-00f4eb76-3e6a-4a47-979a-46854597965b.png">

### Steps To Reproduce

1. Install Coolify
2. Install any app with secrets
3. Reinstall coolify with install script
4. Open secrets section

### Version

3.12.17

**Comment by andrasbacsai** [comment]
Related to [this](https://github.com/coollabsio/coolify/issues/1148).
