### ISSUE TITLE
[Bug]: All database password fields are broken after reinstall coolify

### ISSUE THREAD

**Issue by paulocoutinhox** [coollabsio/coolify#914]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

n/a

### Description

Hi,

After reinstall Coolify with install.sh script all database fields that is password are broken. See:

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/395096/217910913-5a5344fa-42b6-4ade-944d-c226e7902d22.png">

### Steps To Reproduce

1. Create mysql database
2. Reinstall Coolify with install script
3. Open and see the database password field

### Version

3.12.17

**Comment by crabsnap** [comment]
Also encountering this issue, any updates on how to fix this?

**Comment by andrasbacsai** [comment]
Most probably your COOLIFY_SECRET_KEY is wrong in your ~/coolify/.env file. 

Can you please [contact me](https://docs.coollabs.io/contact)? I can help you fix the problem.

**Comment by paulocoutinhox** [comment]
Yes, it was wrong. I delete all and recreate it. Thanks.
