### ISSUE TITLE
[Feature]: Volume mapping

### ISSUE THREAD

**Issue by paulocoutinhox** [coollabsio/coolify#915]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Hi,

I want in my application (https://github.com/paulocoutinhox/pyaa) map sqlite database from "/app/db" to my server folder "/company/apps/pyaa/db".

But it is not possible today.

Can you add fields with from/to (or something like this) to be added as volume mapping when build/start/run docker?

Example:
![image](https://user-images.githubusercontent.com/395096/217946397-0835631f-320d-4858-a0b5-80fd22d0cce3.png)

Thanks.

### Why should this be worked on?

n/a

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
