### ISSUE TITLE
[Feature]: Copy button on volume name

### ISSUE THREAD

**Issue by paulocoutinhox** [coollabsio/coolify#917]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Hi,

Can you add copy button on volume name? Example:

![image](https://user-images.githubusercontent.com/395096/217945791-df576d87-a687-424f-ad54-38d2a0494ed9.png)

### Why should this be worked on?

n/a

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
