### ISSUE TITLE
[Feature]: Password Auth for Projects

### ISSUE THREAD

**Issue by mikestreety** [coollabsio/coolify#918]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add/allow projects to have a simple auth screen requiring a password to get to the content

### Why should this be worked on?

I want to use Coolify to host some project related documentation - nothing on it is _top secret_ but I would like a way to discourage opportunists or if the docs are accidentally linked somewhere (and to stop search engines/AI from obtaining the info)

Netlify has a similar thing (I'm imagining something like "Basic password protection" [explained in their docs](https://docs.netlify.com/visitor-access/site-protection/)) and it would be awesome it Coolify had something similar.

The IDEAL scenario is being able to optionally specify a username (to add to the obscurity) but the option to just have a password too, for simple gatekeeping.

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
