### ISSUE TITLE
[Bug]: Image tag back to first if i type inexistent tag

### ISSUE THREAD

**Issue by paulocoutinhox** [coollabsio/coolify#920]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

n/a

### Description

Hi,

I have a Pocketbase version "0.12.2" running, because i type the tag name manually, instead of select one, since take too much time to update all services tags in git to after update my machine and select the correct version.

<img width="177" alt="image" src="https://user-images.githubusercontent.com/395096/218251764-bf0e764a-0578-4a06-b572-5f12dcc2cc0a.png">

But while it running in version "0.12.2", the Coolify panel show first option: "0.11.0":

<img width="722" alt="image" src="https://user-images.githubusercontent.com/395096/218251722-89d87ef7-81d6-4ae1-9653-75df685c2579.png">

Im afraid to press save and it save tag "0.11.0".

There is a support for custom type in tag or it is a bug?

Thanks.

### Steps To Reproduce

1. Create a service of Pocketbase
2. Type latest version instead select one (ex: 0.12.2): <img width="1080" alt="image" src="https://user-images.githubusercontent.com/395096/218251857-6391f17e-4e8c-41eb-8e6e-bd5310ea6056.png">
3. Save and deploy
4. Enter on created pocketbase again: <img width="638" alt="image" src="https://user-images.githubusercontent.com/395096/218251904-f1a07c2b-a0d9-42e6-a49e-368037bd17c1.png">

### Version

3.12.18

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
