### ISSUE TITLE
[Bug]: Persistent Volume changes on restart when using non-docker buildpack

### ISSUE THREAD

**Issue by marlon360** [coollabsio/coolify#921]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I want to deploy a NextJS app with persistent volumes.

I add the persistent volume "/uploads".

After the deployment everything works.

Restarting the application:

Now the persistent volume is at "/app/uploads".

I found in the restart script, that "/app" will be added to all volumes when the buildpack is not "docker". What's the reason for this?
https://github.com/coollabsio/coolify/blob/23bfc119d9ffa76eccf7b6acac05ba8240c59f4d/apps/api/src/routes/api/v1/applications/handlers.ts#L641-L646

### Steps To Reproduce

1. Deploy NextJS app
2. add persistent volume
3. restart app

### Version

3.12.17

**Comment by andrasbacsai** [comment]
This issue is fixed.
