### ISSUE TITLE
[Bug]: Setting 'WP Config Extra' with @ini_set values breaks Wordpress Service

### ISSUE THREAD

**Issue by grstreten** [coollabsio/coolify#925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

When I set @ini_set values in WP Config Extra, such as:

```
@ini_set( 'upload_max_filesize' , '128M' );
@ini_set( 'post_max_size', '128M');
@ini_set( 'memory_limit', '256M' );
@ini_set( 'max_execution_time', '300' );
@ini_set( 'max_input_time', '300' );
```

and press save, I get an error `Unexpected token in JSON at position 462`, and upon reloading the configuration pane for the service see the following:

```
Could not load https://[my-domain]/services/cle5kpfug000rl99bbj8l1fn3 h@https://[my-domain]/_app/immutable/chunks/common-b9fe1e97.js:1:1239
asyncFunctionResume@[native code]
@[native code]
promiseReactionJobWithoutPromise@[native code]
promiseReactionJob@[native code]
```

### Steps To Reproduce

1. Create a Wordpress Service (with MySQL)
2. Configure any settings
3. Add a `@ini_set` item to WP Extra Config
4. Press save

### Version

3.12.18

**Comment by andrasbacsai** [comment]
Next version will fix the issue!

**Comment by grstreten** [comment]
Unfortunately still broken I'm afraid! I've just tested with the above and got the very same error.

**Comment by renolation** [comment]
i just wanna increase max upload file size, and dont know how to do it? by config it not work. sftp not work also

**Comment by muhammedaksam** [comment]
Hi there @andrasbacsai, this might not be working as intended.
