### ISSUE TITLE
[Bug]: WordPress with MySQL service fails - MySQL container won't start

### ISSUE THREAD

**Issue by MichaelNZ85** [coollabsio/coolify#929]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to create a new Wordpress (MySQL) service, the MySQL container fails to start. Examining the logs shows this error message:
```
2023-02-16T10:59:00.768912017Z exec /opt/bitnami/scripts/mysql/entrypoint.sh: exec format error 
```
As a result, the WordPress service failes with a page showing 'Error establishing a database connection'.

### Steps To Reproduce

1. Create a new WordPress (MySQL) service witt a URL that is pointing to your server's IP.
3. Visit the URL.
4. You should be presented with a page that says 'Error establishing a database connection'.

### Version

3.2.17

**Comment by djvicio** [comment]
I have exactly the same error and the same steps to reproduce them.

**Comment by andrasbacsai** [comment]
You are on arm based server, right?

**Comment by djvicio** [comment]
Right, OCI ARM

**Comment by andrasbacsai** [comment]
I found the issue. It will be fixed in the next version!

**Comment by MichaelNZ85** [comment]
Hi, I just tried deploying a WordPress service and I'm still getting exactly the same error.

**Comment by MichaelNZ85** [comment]
Thanks. How do I update Coolify so I can use this?
