### ISSUE TITLE
the web interface of the Minio service runs on an arbitrary port. The page doesn't open.

### ISSUE THREAD

**Issue by Yurgeman** [coollabsio/coolify#93]
coolify was installed on a new ubuntu vps ,

![Снимок экрана 2021-10-12 в 22 39 07](https://user-images.githubusercontent.com/7249668/137019687-711c8157-5c78-4e67-8481-7beba1afbab0.png)

coolify was installed on a new ubuntu vps. integration with github has been set up

Immediately after that, the minio service was installed. the installation was successful, but an error occurred when trying to go to the application url http://storage.myapp.ru:43697/:

![Снимок экрана 2021-10-12 в 22 36 29](https://user-images.githubusercontent.com/7249668/137018287-6cf51d41-753a-43bb-9e52-0507b65440fa.png)

the service is created on an arbitrary port and the web interface is unavailable

**Comment by Yurgeman** [comment]
This problem is solved by downgrading the Minio version, approximately to the July release. it uses the previous version of Minio browser. Recent releases use a Minio console, which requires 2 separate ports

**Comment by andrasbacsai** [comment]
It has been solved in v2. 

Please upgrade it to v2! A fresh installation is required as v2 is not compatible with v1.
