### ISSUE TITLE
[Bug]: HTTP-01 TLS challenge directory blocked by Coolify

### ISSUE THREAD

**Issue by usr3** [coollabsio/coolify#933]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Example public repository

N/A

### Description

When a docker container tries to request for a TLS certificate by placing a file at `.well-known/acme-challenge/<TOKEN>`, the path is unreachable through Coolify even though the FQDN is not **https**. This prevents the acme server from validating the challenge. Some use cases for this include mailservers like [Mailu](https://github.com/Mailu/Mailu) which need TLS for sending email.

### Steps To Reproduce

1. Create an application with Docker/Docker Compose buildpack.
2. The docker container should expose a file at the path `.well-known/acme-challenge/<TOKEN>`.
3. Deploy the container.
4. Try to access `http://<hostname>/.well-known/acme-challenge/<TOKEN>`.

### Version

3.12.17

**Comment by muellercornelius** [comment]
Stumbled upon this one. I havent had the time to look deeper in it but I am trying to send mails with pocketbase and I configured my own SMTP Server which requires TLS... And it is not working. Could that be related?

**Comment by usr3** [comment]
> Stumbled upon this one. I havent had the time to look deeper in it but I am trying to send mails with pocketbase and I configured my own SMTP Server which requires TLS... And it is not working. Could that be related?

I guess unless you're running your own SMTP server behind Coolify, it shouldn't be an issue. For Pocketbase you can just run it with it's `--http` flag since Coolify will generate a certificate automatically.

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
