### ISSUE TITLE
[Feature]: Ansible role to automate Coolify tasks

### ISSUE THREAD

**Issue by beepsoft** [coollabsio/coolify#934]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

It would be great if there was an Ansible role for automating various Coolify tasks, like installing Coolify itself to a VPS and then adding git sources, new applications, services, etc.

### Why should this be worked on?

 This feature would allow reproducing Coolify installations automatically. Now, when I create a new VM I have to manually install Coolify and do all the configurations to have the same set of apps and services up and running.

With Ansible it would be possible to make Coolify "packages": a set of apps and services installed together using Ansible.

For this to work it may also be nice to have an official documentation of the Coolify API via Swagger/OpenAPI (maybe via https://github.com/fastify/fastify-swagger), which the Ansible role could be using.

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
