### ISSUE TITLE
[Bug]: Failed To Authorize Gitlab Repo When Creating an Apps

### ISSUE THREAD

**Issue by raniaamina** [coollabsio/coolify#936]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi, i try to add new apps through Gitlab repository, but after click authorize button on pop up window, i got this error. I had follow this step https://docs.coollabs.io/coolify/sources for add git source for gitlab.

![gambar](https://user-images.githubusercontent.com/22146607/220160327-0b2fb537-3d5b-434c-949b-5b0c6fac2228.png)

### Steps To Reproduce

1. Add new git source by following this step https://docs.coollabs.io/coolify/sources
2. Create new apps from gitlab source
3. Authorize pop up when appear

### Version

3.12.20

**Comment by Procuria** [comment]
Same problem here but with a 'strange' twist.
Authorization against GitLab SaaS. OAuth app is _group_ based.  
Using the GitLab source works for around 6 hours.
After that we see the error described above.

**Comment by andrasbacsai** [comment]
Is this still an issue?

**Comment by danvick** [comment]
Hi,
This is still a problem for me. I've tried different solutions but still after clicking "Authorize" on Gitlab I still get the error.

I also have tried different versions of Coolify.

Right now I'm on v3.12.36
