### ISSUE TITLE
[Feature]: Start paused app instead of redeploying

### ISSUE THREAD

**Issue by MartinKavik** [coollabsio/coolify#938]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When I pause an app I can't restart it again. Only the `Deploy` button is available. I would like to just click new button `Start`.

### Why should this be worked on?

Sometimes I have to wait ~20min until the build is complete even though I haven't changed any settings that would need rebuilding the app. 
It could be, for instance, really painful when the app is degraded and I can't just restart it.

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
