### ISSUE TITLE
[Bug]: WordPress/MySQL service: User specified in config not created in MySQL - have to use root instead

### ISSUE THREAD

**Issue by MichaelNZ85** [coollabsio/coolify#939]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Example public repository

coolify

### Description

The WordPress/MySQL service does not work with the user that is specified in the config. 

When running the WordPress initial setup (after choosing the language), using the values specified in the Coolify config (and the MYSQL_USER_PASSWORD secret) do not work:

![firefox_TAPYW1z7UK](https://user-images.githubusercontent.com/15241383/220256504-b5f1576c-7315-4978-b140-cad071b17704.png)

The MySQL container logs contains the following:

```
2023-02-21T05:18:10.447387995Z 2023-02-21 05:18:10+00:00 [Warn] [Entrypoint]: MYSQL_PASSWORD specified, but missing MYSQL_USER; MYSQL_PASSWORD will be ignored 
```

I was able to get the WordPress app running by using the MySQL root user and password, but this is not ideal.

### Steps To Reproduce

1. Create a WordPress/MySQL service.
2. Go to the URL you specified in step 1 and select your language.
3. Enter the details from the Coolify config page for your app into the WordPress database details page.
4. You should get a database connection error.

5. Go back and set the username to 'root' and the password to the value of 'MYSQL_ROOT_PASSWORD' in the secrets section of the config.
6. WordPress should install and work as normal

### Version

3.12.20

**Comment by andrasbacsai** [comment]
Found the issue, next version will have the fix!

**Comment by andrasbacsai** [comment]
Released a new version, let me know if it still happening!
