### ISSUE TITLE
[Feature]: Golang Applications

### ISSUE THREAD

**Issue by jareer12** [coollabsio/coolify#940]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Is Golang app support coming anytime soon?

### Why should this be worked on?

I want to deploy my golang projects on coolify.

**Comment by kazzkiq** [comment]
@jareer12 you can easily achieve this by creating a Dockerfile in your project root, building your Go program, and then running it.

Example: If I have a project with a `main.go` file that exposes port `3000`, this is how the Dockerfile would look like:

```dockerfile
# Dockerfile

FROM golang:alpine

WORKDIR /app

COPY . .

RUN go build -o server .

EXPOSE 3000

CMD ["./server"]
```

Now you commit this file, and simply choose "Docker" on the "Select a Build Pack" step.
<img width="1235" alt="Screenshot 2023-04-27 at 02 20 49" src="https://user-images.githubusercontent.com/1953194/234766388-7f4f2fe3-425c-4ba2-81b8-fce13e7ca935.png">
