### ISSUE TITLE
[Bug]: PostgreSQL database recreates every time 

### ISSUE THREAD

**Issue by michalwarda** [coollabsio/coolify#941]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I create a new PostgreSQL database it works  ok. After a while let's say I stop the instance and start it again. 

The volume that has the data persisted from previous container mounts at `/var/lib/postgresql` but also after few seconds another volume is created (without any labels) and mounts at `/var/lib/postgresql/data` which overrides the data I guess.

Because of that each time you stop and start a container data is "lost".

Similar thing happens with Plausible service though it does not even mount the volume after restart. It just creates a new one and overrides data.

### Steps To Reproduce

1. Create a new PostgreSQL database
2. Add something to it
3. Stop it
4. Start it

A new volume is created and mounted and all data that was added in step 2 is lost. 

1. Create a Plausible Service
2. Add something to it
3. Stop it
4. Start it

A new volume is created and mounted and all data that was added in step 2 is lost.

### Version

3.12.20

**Comment by andrasbacsai** [comment]
Found the issue, next version will have the fix!

**Comment by andrasbacsai** [comment]
Released a new version, let me know if it still happening!
