### ISSUE TITLE
[Feature]: Make container hostnames available in the Docker host

### ISSUE THREAD

**Issue by MartinKavik** [coollabsio/coolify#942]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Make container hostnames available from the Docker host.

It means you can, for instance, log in through SSH into your server where Coolify is installed and then connect to a Postgres container directly through the container's host name (e.g. `cld*******************ejf`).

It could be done by automatically synchronizing running Docker containers with the host's `/etc/hosts` file. Like this script: https://gitlab.com/jarylc/docker-hosts-sync

See also related question on the Coolify Discord: https://discord.com/channels/459365938081431553/1077307563957301338

### Why should this be worked on?

The feature allows you to access your containers through SSH tunnels instead of making them public or instead of trying to get their temporary IP manually. It's very useful for connecting tools like Postgres administrators (e.g. DBeaver) from a developer's local machine to the server.

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
