### ISSUE TITLE
[Feature]: App name visible on all app detail pages

### ISSUE THREAD

**Issue by MartinKavik** [coollabsio/coolify#944]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add the app name to UI (to header or menu or page content) so the name is visible while the user is browsing through app details settings (e.g. Configuration, Secrets, etc.).

Also the name of services could be emphasised as well in a similar fashion.

### Why should this be worked on?

When I'm, for instance, updating secrets for multiple apps at once (in multiple opened browser tabs) then I'm afraid I'll accidentally edit the wrong instance and brake the production app. The same apply when I return to work and I'm not sure what app I was configurating.

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
