### ISSUE TITLE
[Feature]: Show app internal/Docker host in UI

### ISSUE THREAD

**Issue by MartinKavik** [coollabsio/coolify#946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

It would be nice to see internal/Docker host associated to app containers in the app details (e.g. in the Configuration page of the selected app).
It could be read-only just like the Postgres service `host` is in the service Configurations. 

### Why should this be worked on?

Currently, the only way to get the container `host` is to copy it from the URL when you are on the app detail page. It's not intuitive and I wouldn't guess it works. 

My use-case: This `host` is the only way I can properly connect my Rust app to FusionAuth (both hosted in Coolify).

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
