### ISSUE TITLE
[Feature]: Graceful shutdown

### ISSUE THREAD

**Issue by MartinKavik** [coollabsio/coolify#947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Coolify should wait until app containers are shut down gracefully.

Shut down may be initiated by new deployment or just by a Coolify user clicking on the pause/restart button, etc. So it would be needed to handle all such cases.

I think the feature is a bit related to Build hooks (https://github.com/coollabsio/coolify/issues/265), Health checks (https://github.com/coollabsio/coolify/issues/633) and probably also Dependent services (https://github.com/coollabsio/coolify/issues/749).

### Why should this be worked on?

My current and probably also the most common use-case is to wait until a (worker) app stops processing new tasks from a queue and new user requests and finishes the running ones.

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
