### ISSUE TITLE
[Bug]: Instillation not happening

### ISSUE THREAD

**Issue by ARR4NN** [coollabsio/coolify#948]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

I run the install command from the docs and it happens and i get the `Please visit http://MYIP:3000 to get started.`
Visiting this page displays nothing.

Docker version 20.10.21, build baeda1f

### Steps To Reproduce

Use the install command

### Version

2.5.2

**Comment by carvalholeo** [comment]
Hi!

Does this IP is in your local machine or is it in a cloud, as AWS or Azure? Does ths installer log some error?

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
