### ISSUE TITLE
Error on first login

### ISSUE THREAD

**Issue by spencerflagg** [coollabsio/coolify#95]
Apologies if I'm missing some crucial step.

I'm working on a new Ubuntu 20.04 Linode, ran this script...
```
/bin/bash -c "$(curl -fsSL https://get.coollabs.io/coolify/install.sh)"
```
Opened the installer at :8080, entered my domaiin, my email, and declined GitHub integration.

Install seemed to work fine. When I hit coolify.my.domain I get prompted for a username/password.
(It's not entirely clear what these credentials are, or if i need to set them up in the terminal or what. I left GitHub integration unchecked, so it shouldn't be related to that.)

Either way, regardless of the un/pw combo I enter, I get the following this error  in a popup on the page:
```
SyntaxError: Unexpected token O in JSON at position 0
```

Seems like maybe there's a user list somewhere that's empty, so the JSON isn't getting parsed properly? 
Not sure how to proceed. 😬

Thanks in advance for your time!

**Comment by hrichiksite** [comment]
The login errors happen with me too. Its because the GitHub API is returning nothing/undefined or the MongoDB is not yet turned on.

**Comment by spencerflagg** [comment]
SOLUTION

**Comment by hrichiksite** [comment]
Great, maybe you can close the issue now.

**Comment by andrasbacsai** [comment]
I'm closing this as v1 is deprecated, and v2 has a different authentication method.
