### ISSUE TITLE
Install coolify as an image dockerfile

### ISSUE THREAD

**Issue by mmm8955405** [coollabsio/coolify#953]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Install coolify as an image dockerfile。 Instead of using scripts

### Why should this be worked on?

Applicable to different environments. And convenient

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
