### ISSUE TITLE
[Bug]: Broken Revert

### ISSUE THREAD

**Issue by MartinKavik** [coollabsio/coolify#954]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1. Reverted application returns "404 page not found" so I assume there is a broken Coolify routing configuration.

2. Also there is a related UI problem - when you Stop the application the "Currently used" text is still visible although after the refresh (F5) the text is replaced with the button "Revert Now". I assume the text should be replaced immediately after the click on the Stop button. 

3. And perhaps another related bug - 8 images are offered me on the Revert page even though 3 images are set in Coolify Settings ("Number of Docker Images kept locally").

### Steps To Reproduce

1. Stop a healthy application. In my case it's a Rust app deployed with a custom Dockerfile and accessible on "https:://xxx".
2. Click "Revert Now" button in the app details on the first / the newest image. If you see the text "Currently Used" then refresh the browser tab.
3. Notice the flash message "Revert Successful".
4. Go to the application URL.
5. Notice the text "404 page not found" instead of the expected app content.
6. Restart won't fix it, you have to click Force Redeploy to make the app work again.

### Version

v3.12.21

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
