### ISSUE TITLE
[Feature]: Add PocketBase

### ISSUE THREAD

**Issue by miguelgargallo** [coollabsio/coolify#958]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add PocketBase support!

### Why should this be worked on?

PocketBase is perfect standalone database for fast hackathon and b2b small projects

**Comment by miguelgargallo** [comment]
I discovered the tool a day ago, my apologies, this is integrated yet amazing!

**Comment by jesperordrup** [comment]
is this available as a service? Its not mentioned in docs?

**Comment by maietta** [comment]
@jesperordrup, Yes, Pocketbase is included in the list of templates.
