### ISSUE TITLE
[Feature]: Add Tauri with SvelteKit app Support

### ISSUE THREAD

**Issue by miguelgargallo** [coollabsio/coolify#959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add Tauri with SvelteKit app Support

### Why should this be worked on?

SvelteKit with tauri-src is a perfect way to deploy and develop apps! it's trending and fast! You are doing an amazing project!

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
