### ISSUE TITLE
Multiple domain

### ISSUE THREAD

**Issue by italodeandra** [coollabsio/coolify#96]
It would be really nice if we could add multiple domains instead of just one.

**Comment by italodeandra** [comment]
Or at least I should be able to change the domain. Why is the domain field locked after the app is deployed?

**Comment by itsezc** [comment]
@andrasbacsai this should be flagged for v2

**Comment by italodeandra** [comment]
@itsezc A small question about this enterprise-ready v2...

Is it going to be paid/freemium?

**Comment by itsezc** [comment]
(I am not associated with this project in an official capacity) It is OSS, the development branch should be available on: https://github.com/coollabsio/coolify/tree/v2 and I would recommend joining the [Discord community](https://discord.gg/xhBCC7eGKw) for direct communication with the development team.

**Comment by andrasbacsai** [comment]
> @itsezc A small question about this enterprise-ready v2...
> 
> Is it going to be paid/freemium?

It will stay totally free and open-source! 

I'm just adding these features (and refactoring the codebase) to have more use cases for Coolify. Not just for hobbyists but for enterprises.

**Comment by andrasbacsai** [comment]
V2 is released, with an option to define domain at runtime instead of installation time!

**Comment by italodeandra** [comment]
Hey @andrasbacsai,

Did you also add the feature of multiple domains?

**Comment by andrasbacsai** [comment]
Oh, no. Reopening.

**Comment by code-K** [comment]
Hi @andrasbacsai, any news on the progress for this? So having the possibility to proxy multiple domains for an application or service? Thanks :)

**Comment by spencerflagg** [comment]
Multiple domains would really get me out of a bind right now. :grin:

**Comment by masterbater** [comment]
Is it possible all fields with URL (FQDN) can be supplied a value like https://coolify.com;https://coolify.dev;https://coolify.dev
Semi colon separated urls and traefik will generate all ssl.
This is a must especially with SAAS setup.

**Comment by Scitz0** [comment]
+1 on this, being able to have multiple URLs (FQDN) for the same app would be gold.

**Comment by da411d** [comment]
I need domain-catchall feature🙌

**Comment by code-K** [comment]
Hey @andrasbacsai, any possibility that this could be implemented, even still in V3? Or if it will be supported in V4, when will this be ready so I could migrate from V3 to V4.... Thanks much for feedback on this! :)

**Comment by vikasOren** [comment]
Hey, I have a coolify app running on subdomain1.mydomain.com.
I have created another CNAME record subdomain2.mydomain.com and it points to subdomain1.mydomain.com.
I sit supported in coolify??

**Comment by andrasbacsai** [comment]
It is available in v4.

I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.

**Comment by Geczy** [comment]
for v3 folks like me, you can now do this with my pr at https://github.com/coollabsio/coolify/pull/1505
