### ISSUE TITLE
[Bug]: traefik pegging 100%+ CPU

### ISSUE THREAD

**Issue by amark** [coollabsio/coolify#960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

server with large concurrent traffic

### Description

When I run NodeJS naked, I get about 150K concurrent users out of this machine (I have to edit ulimits & stuff)

I now have coolify on it (awesome awesome! Thanks so much) but I only get ~30K concurrent users.

I've tracked it down to perhaps/maybe that it is traefik is pegging the CPU at 100%+ & 4GB+ of RAM

I'm really dumb/bad at load balancer & docker stuff (why I've just run NodeJS naked in the past), is there perhaps some sort of system/kernel tuning that traefik doesn't do, or docker is just hogging resources with its virtualization?

Note: The large traffic going to the 1 app *seems* to be causing the other app on the same machine to not behave/perform very well. Which makes sense, but then is there anyway to get traefik or something to virtualize the apps across multiple running machines, to maintain isolation from busier apps?

Thanks so much. Loving coolify! You're a hero.

### Steps To Reproduce

I can give you access to my server. Note: This is not commercial, just open source. Trying to make things scale well for devs in my community.

### Version

3.12.17

**Comment by andrasbacsai** [comment]
I will take a look into this!

**Comment by deployn** [comment]
I also have a similar problem. I couldn't access my coolify instance (3.12.30) today. Treafik has an issue with a ssl certificate and all projects, even coolify itself, becomes inaccessible. The only temporary solution was to restart the server. 4 hours later, same problem, restart again.

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
