### ISSUE TITLE
[Bug]: Docker Compose deployment fails with build commands

### ISSUE THREAD

**Issue by b-per** [coollabsio/coolify#963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

https://github.com/dagster-io/dagster/blob/master/examples/deploy_docker/docker-compose.yml

### Description

I have tried the Docker Compose deployment of the previous repo/path.

This docker-compose contains some `build` commands:

```
  docker_example_user_code:
    build:
      context: .
      dockerfile: ./Dockerfile_user_code
    container_name: docker_example_user_code
    image: docker_example_user_code_image
```

When trying to deploy it in Coolify I get the following errors. It looks like Coolify tries to retrieve the images that should be built and, as expected, doesn't fund them.

I think that we might need to trigger a `docker compose build` before the `docker compose pull`. 
I don't know if we'd need `--ignore-buildable` as well for [`docker compose pull`](https://docs.docker.com/engine/reference/commandline/compose_pull/)

```
[18:08:46.893] Debug logging is disabled. Enable it above if necessary!
[18:08:46.901] Cloning dagster-io/dagster:master...
[18:09:28.428] Configuration changed
[18:09:30.779] Command failed with exit code 18: docker compose --project-directory /tmp/build-sources/dagster-io/dagster/clepxmeaj038l9sl8f7kzbrze -f /tmp/build-sources/dagster-io/dagster/clepxmeaj038l9sl8f7kzbrze/examples/deploy_docker/docker-compose.yml pull
docker_example_dagit Skipped 
docker_example_daemon Skipped 
docker_example_user_code Pulling 
docker_example_postgresql Pulling 
docker_example_user_code Error 
docker_example_postgresql Error 
WARNING: Some service image(s) must be built from source by running:
    docker compose build %s docker_example_user_code
Error response from daemon: pull access denied for docker_example_user_code_image, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
[18:09:30.782] Command failed with exit code 18: docker compose --project-directory /tmp/build-sources/dagster-io/dagster/clepxmeaj038l9sl8f7kzbrze -f /tmp/build-sources/dagster-io/dagster/clepxmeaj038l9sl8f7kzbrze/examples/deploy_docker/docker-compose.yml pull
docker_example_dagit Skipped 
docker_example_daemon Skipped 
docker_example_user_code Pulling 
docker_example_postgresql Pulling 
docker_example_user_code Error 
docker_example_postgresql Error 
WARNING: Some service image(s) must be built from source by running:
    docker compose build %s docker_example_user_code
Error response from daemon: pull access denied for docker_example_user_code_image, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

### Steps To Reproduce

See above

### Version

3.12.21

**Comment by andrasbacsai** [comment]
`docker_example_user_code_image` is a non existing image. The compose file you linked is a wrong one.

**Comment by b-per** [comment]
Hi Andras.

I actually think that this could be fixed and that the issue could be reopened.

According to [this SO page](https://stackoverflow.com/questions/34316047/difference-between-image-and-build-within-docker-compose), docker compose allows having both a `build` and an `image` value set. In that case, the `build` command will create an image with the name of `image`.

I think that updating this code 

https://github.com/coollabsio/coolify/blob/884524c448604e24b3eb651824977e75d9fd6d04/apps/api/src/lib/buildPacks/compose.ts#L129

and adding `--ignore-buildable` at the end would work.

**Comment by preslavrachev** [comment]
Has this been resolved for Coolify v3?

**Comment by peaklabs-dev** [comment]
Please update to the latest v4 version and recheck if this issue persist?
