### ISSUE TITLE
[Bug]: COolify won't start or run after docker-ce-5:23.0.1-1~debian.11~bullseye update

### ISSUE THREAD

**Issue by Hybes** [coollabsio/coolify#964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

Docker updates prevent coolify running

### Steps To Reproduce

Update:
Package:                                    Old Version:                 New Version:                                       Size:  
  containerd.io                               1.6.16-1                     1.6.18-1                                         28.2 MB  
  docker-ce                                   5:20.10.23~3-0~debian-bulls  5:23.0.1-1~debian.11~bullse                      21.9 MB  
                                              eye                          ye                                                        
  docker-ce-cli                               5:20.10.23~3-0~debian-bulls  5:23.0.1-1~debian.11~bullse                      13.2 MB  
                                              eye                          ye                                                        
  docker-ce-rootless-extras                   5:20.10.23~3-0~debian-bulls  5:23.0.1-1~debian.11~bullse                       8.8 MB  
                                              eye                          ye                                                        
  docker-compose-plugin                       2.15.1-1~debian.11~bullseye  2.16.0-1~debian.11~bullseye                      10.2 MB

and it all breaks.

### Version

latest

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
