### ISSUE TITLE
[Bug]: New update 3.12.22 MIME type error on main.jsx (React)

### ISSUE THREAD

**Issue by mezuny** [coollabsio/coolify#966]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

When updating from 3.12.21 to 3.12.22, upon trying to use my React app again, I started getting errors that (in console) state:

Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.

### Steps To Reproduce

1. Spin up a React instance (In this case; Vite + React)
2. Try to visit the front-end for your React app
3. Get a white screen with the following error in your console:
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.

### Version

3.12.22

**Comment by andrasbacsai** [comment]
Fixing it soon!
