### ISSUE TITLE
[Bug]: An error occurred during authenticating with GitLab. 

### ISSUE THREAD

**Issue by nekic** [coollabsio/coolify#967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

When i create application from gitlab source, An error occurred during authenticating with GitLab. may be request gitlab user info api was wrong!

![image](https://user-images.githubusercontent.com/9676277/222745603-1136cf42-a695-4cc6-9808-f20bd1a003aa.png)

### Steps To Reproduce

1. (in Coolify) In Git Sources, add a new GitLab source.
2. In a new browser tab, navigate to your GitLab instance and find the UI to add a new application.
3. (in GitLab) Enter the Callback URL as https://coolify.yourdomain.com/webhooks/gitlab.
4. (in GitLab) check the following scopes: api, read_repository, email.
5. (in GitLab) Save the application and copy the Application ID .
6. (in Coolify) In your new source, paste the Application ID.
7. (in GitLab) In the newly created application, copy the Secret.
8. (in Coolify) Paste the Secret.
9. (in Coolify) Enter the OAuth ID. It will be the located at the end of the url of your GitLab application: https://yourgitlabdomain.com/oauth/applications/123456.
10. (in Coolify) Hit save.
(in Coolify) In Applications add a new application with GitLab as the source.
11. If you're still logged into GitLab, an authorization popup will appear. Click authorize.

### Version

3.12.22

**Comment by andrasbacsai** [comment]
Is this still an issue?
