### ISSUE TITLE
PR Deployment log button's "external link" should redirect to PR link instead of prod link

### ISSUE THREAD

**Issue by italodeandra** [coollabsio/coolify#97]
The button mentioned:

![image](https://user-images.githubusercontent.com/19225266/141775618-bfbedb26-42a6-4458-818b-67c3f75dcafd.png)

If you open the deployment of a PR, it will show the link from prod. I had to go to the Settings to discover the actual link for the PR.

**Comment by andrasbacsai** [comment]
Hey @italodeandra ,

It has been solved in v2. Please upgrade to v2 (new installation is needed as v2 is not compatible with v1).
