### ISSUE TITLE
Reference build status in global service list alongside with current deployment status

### ISSUE THREAD

**Issue by BOTKooper** [coollabsio/coolify#970]
_Originally posted by @MartinKavik in https://github.com/coollabsio/coolify/issues/294#issuecomment-1453968340_

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
