### ISSUE TITLE
[Bug]: Grammatical error on login page

### ISSUE THREAD

**Issue by dillfrescott** [coollabsio/coolify#971]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Example public repository

coolify

### Description

![Screenshot 2023-03-03 231729](https://user-images.githubusercontent.com/56714680/222875297-4493d66a-da38-485c-a317-1c8409ee6804.png)

Shouldn't it be `Making self-hosting simple.`? Made is past tense and coolify is still making the self hosting simple, hence present tense `making`.

### Steps To Reproduce

n/a

### Version

n/a

**Comment by dillfrescott** [comment]
Optionally: `Self-hosting made simple.` would also make sense

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
