### ISSUE TITLE
[Bug]: Static & Svelte Build Pack don't respect Publish Directory

### ISSUE THREAD

**Issue by henk23** [coollabsio/coolify#972]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

Possibly related to https://github.com/coollabsio/coolify/issues/470

So far affected:

- Svelte Build Pack
- Static Build Pack

Not sure if I'm doing something wrong here, using deployment image webdevops/nginx:alpine.
Looks like Nginx sets the location to `/app` instead of `/app/dist`.

I also tried using a different deployment image, but getting the same result for webdevops/apache:alpine.

Needed to manually `docker exec -it` into the container, fix nginx.conf file and restart nginx, then it works.

I guess this is the responsible commit: https://github.com/coollabsio/coolify/commit/6f15cc2dbcc1b6d888cb8942278b8a274152cef1

### Steps To Reproduce

1. Create an application, pointing to a GitLab repo containing a simple Svelte project
2. Choose Svelte Build Pack (also happens with Static Build Pack)
3. Choose 'dist' as the Publish Directory (since this is the default output dir for Svelte)
4. Deploy
5. Deployment is carried out successfully, you can reach index.html but the browser tries to load App.svelte file.

### Version

3.12.22

**Comment by andrasbacsai** [comment]
Fixing it soon!
