### ISSUE TITLE
[Feature]: Use the source/repo name as Name instead of using a random generated name.

### ISSUE THREAD

**Issue by annihilatorrrr** [coollabsio/coolify#974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When we create new application, the coolify should use the repo name as the Name of the application rather using a random generated name.

### Why should this be worked on?

I felt this will be better to identify the running application and will help to remember much.

`Sorry for my bad English btw.`

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
