### ISSUE TITLE
[Bug]: Internal Server Error when activating HTTP/2 protocol

### ISSUE THREAD

**Issue by henk23** [coollabsio/coolify#976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

When activating HTTP/2 protocol on a Static Application, the website will say "Internal Server Error"

This is in the logs:

```
[my-ip] - - [04/Mar/2023:18:50:23 +0000] "\x16\x03\x01\x01\x1E\x01\x00\x01\x1A\x03\x03\xBFr\x9Dqg~H\xDA\x08\xF15\xB1#\xC2\xB6\xAA@\x1C\xF6I\xA7l\xC8\x94\xE7\xE9\x14\xAF\xDBy" 400 157 "-" "-" "-"
```

Looks like trying to answer a TLS handshake with a non-TLS server?

Works fine for non-http2.

### Steps To Reproduce

1. Deploy a static website with HTTP/2 option activated
2. Visit the website

### Version

3.12.25

**Comment by henk23** [comment]
Okay. Seems like traefik already has a HTTP2 resonse.
When setting isHttp2 of the Application to true, it will need to have tls enabled, which is only needed when it is is exposed directly via a port, I guess?

I wish this was documented somewhere. Apart from that, this ticket can be closed. :)

**Comment by ChronSyn** [comment]
Thanks for pointing this out.

I was wondering why previews were working but the main deployment was throwing the error. It'd be nice for the issues to be fixed, but as projects will still function without HTTP2, I'd expect it's not critical to fix.

**Comment by matthewblott** [comment]
> 

What does this mean in practice, i.e. what steps do I need to take to enable HTTP 2 for static websites aside from enabling the 'Enable HTTP/2 protocol?' radio button?

**Comment by henk23** [comment]
No need to do anything. Coolify already takes care of http2 out-of-the-box.

Look at the response header of your static site. It will say 'HTTP/2 200 OK'.

The 'Enable http2' button is (I guess?) for special use-cases, like when you use your own reverse-proxy and take care of certificates yourself or something like that.

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
