### ISSUE TITLE
[Bug]: volume.split is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by alyssonbruno** [coollabsio/coolify#977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

Using Docker Compose with volumes this error is raised:
**volume.split is not a function or its return value is not iterable**
If a change volumes in Docker compose the error it's did not raise, but Docker compose fail.

the Docker compose file, with volumes, run fine in terminal.

### Steps To Reproduce

1. Using a application with Docker Compose like this one: https://hub.docker.com/r/felddy/foundryvtt
2. Deploy app

### Version

3.12.0 to 3.12.24

**Comment by andrasbacsai** [comment]
I will have a fix for this in the next version!

**Comment by McPizza0** [comment]
Just came across this, glad to see a fix is planned

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
