### ISSUE TITLE
[Bug]: Fresh install.sh fail - unable to apply apparmor profile

### ISSUE THREAD

**Issue by McPizza0** [coollabsio/coolify#978]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

When I try to run the install script on a fresh vps (Debian 11.5)
It exits with the following error:
```
Installing Coolify.
Pulling Coolify latest image (3.12.25).
Starting Coolify.
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: unable to apply apparmor profile: apparmor failed to apply profile: write /proc/self/attr/apparmor/exec: no such file or directory: unknown.
./install.sh exited unexpectedly with status: 127
```

### Steps To Reproduce

1. New debian vps
2. run install via `wget -q https://get.coollabs.io/coolify/install.sh \ -O install.sh; sudo bash ./install.sh`

### Version

3.12.25

**Comment by McPizza0** [comment]
Seems to be an issue with Debian 11

This fixed the issue:
```
sudo apt-get purge apparmor apparmor-profiles apparmor-utils

sudo apt-get install apparmor-utils apparmor-profiles apparmor-profiles-extra vim-addon-manager

reboot
```

Maybe a check can be added to the install script to ensure apparmor is installed in the system

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
