### ISSUE TITLE
[Bug]: Coolify demo fails in Safari MacOS

### ISSUE THREAD

**Issue by m-thomson** [coollabsio/coolify#979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

I was eager to try Coolify but nothing happens when clicking the "Let's get started" button in Safari on MacOS. Kind of ironic.

I tried Safari 16.3 and Safari Technology Preview release 164 with the same result.

Everything worked as expected on Chrome.

### Steps To Reproduce

Use Safari to register and use the demo. Nothing happens when clicking "Let's get started" so it's impossible to ummm.... "get started"

 NB: I'm not sure if the same problem occurs on Safari mobile

### Version

demo

**Comment by zanami** [comment]
Safari 16.3 (18614.4.6.1.6)
Console > TypeError: undefined is not an object (evaluating 'searchInput.focus')

**Comment by m-thomson** [comment]
I'm having the same problem and am seeing the same console error as @zanami

**Comment by m-thomson** [comment]
@andrasbacsai Please consider stating up front that your app is limited to a single browser engine, so as to not waste people’s time. Cheers.

**Comment by andrasbacsai** [comment]
v3 is already deprecated. The issue is still persist?
