### ISSUE TITLE
Monitoring

### ISSUE THREAD

**Issue by italodeandra** [coollabsio/coolify#98]
This could be an internal implementation or at least the addition of an external monitoring service. I have no preference, I just want to be able to see how the machine and apps are doing.

**Comment by itsezc** [comment]
@italodeandra would external APM service such as Datadog or Zabbix be suitable for your feature request? I was thinking of this earlier, the implementation would have to consider different environments (Docker, Swarm and Kubernetes).

[Zabbix](https://www.zabbix.com/integrations/kubernetes) is a personal favourite of mine.

**Comment by italodeandra** [comment]
@itsezc Currently, Coolify is just docker-based, right? So I'm not sure if I understand your concern about different environments.

But to answer your question, I only have experience with Grafana, but I have no strong preference. Like I mentioned, I'm just interested on usual stuff like CPU, Memory and Bandwidth usage.

**Comment by itsezc** [comment]
@italodeandra At this moment Coolify is targeting just Docker but for v2 there will be other target environments, i.e. Kubernetes and Docker is most likely not going to be used in most K8s instances, it could be containerd, cri-io etc. so I guess some level of abstraction is necessary to work with say a single host Docker based Coolify instance compared to a Kubernetes cluster with potentially millions of containers deployed via Coolify.

Kubernetes does support logging & monitoring of resource usage out of the box at pod level including bandwidth usage (both in real time and periodically - say over a hour, day or month) integration with Grafana or Zabbix will be very straightfoward as Kubernetes has first class support by both of these tools.

For docker, we would need to use the [Docker stats API](https://docs.docker.com/engine/api/v1.37/#operation/ContainerExport)

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
