### ISSUE TITLE
[Feature]: Deployment type docker image

### ISSUE THREAD

**Issue by hmontazeri** [coollabsio/coolify#984]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Basically, that would means I can build my images on GH actions and push them to GHCR.io and just trigger the deployments via webhook to the latest version. 

### Why should this be worked on?

CPU Spikes on server. While docker is building the new image, CPU spikes happen on the build server, which is the app runner server, at the same time. This makes apps laggy. 

Example: those spikes are builds.
<img width="797" alt="image" src="https://user-images.githubusercontent.com/1557035/224477068-327e109f-eb1e-4086-9a79-487a4baa3632.png">

**Comment by andrasbacsai** [comment]
Similar flow will be supported in v4.

I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
