### ISSUE TITLE
[Bug]: Cannot fetch/curl another service/application via public hostname/IP

### ISSUE THREAD

**Issue by henk23** [coollabsio/coolify#989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

I run two node.js applications with coolify on a host with public IP 12.34.56.78.

They are reachable via `https://app1.mydomain.com` and `https://app2.mydomain.com` respectively.

Trying to `fetch('https://app2.mydomain.com')` from inside App1 will fail with a timeout.
I also tried to `curl -v https://app2.mydomain.com` from within App1 container.
The result: 
```
*   Trying 12.34.56.78:443...
* connect to 12.34.56.78 port 443 failed: Connection timed out
```

So DNS seems to work fine, but it fails to reach the host via its public IP.

Requesting by container name and port `curl http://cleuetgep000oru9c6i5lgq3n:3000` works fine.

Is this an issue with coolify or a general docker or traefik problem? Can it be mitigated somehow?

### Steps To Reproduce

1. Create two services/applications inside coolify
2. `docker exec -it` into one of the services
3. Try to `curl` the other service by its public URL

### Version

3.12.27

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
