### ISSUE TITLE
Show app (repository) name somewhere

### ISSUE THREAD

**Issue by italodeandra** [coollabsio/coolify#99]
Currently I have no idea which app is open. Not even on the URL because it's using the autogenerated slug.

![image](https://user-images.githubusercontent.com/19225266/141776551-c3696412-c47b-4e14-ad28-cb1ec23d1144.png)

**Comment by andrasbacsai** [comment]
Hey @italodeandra,

Version 2 has links to your apps everywhere (maybe too much). 

Please upgrade it to v2 (manual reinstallation is needed, as I changed the whole architecture of the application, they are not compatible)!
