### ISSUE TITLE
[Bug/Security]: Static buildpack exposing git config

### ISSUE THREAD

**Issue by pygillier** [coollabsio/coolify#990]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When deploying a website using the static buildpack from a git repository, the `.git`folder is also exposed and browsable. 
Also, git `config` file in workspace contains access tokens. 

### Steps To Reproduce

1. Create a new application using the static buildpack from a git repository
2. Deploy the application
3. Access the application over the browser and add `/.git/config`to url. 
4. Access git config file.

### Version

3.12.27

**Comment by pygillier** [comment]
Hi @andrasbacsai I've upgraded to 3.12.29 and tried to redeploy my app, `.git` folder is still browsable (also happening on PHP buildpack, must be happening on all packs)

**Comment by andrasbacsai** [comment]
Ah, found the issue. Fixing in the next version.

**Comment by andrasbacsai** [comment]
The new version is out. Let me know if it's working now!
