### ISSUE TITLE
[Bug]: Coolify not working after upgrade

### ISSUE THREAD

**Issue by zek** [coollabsio/coolify#994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

TypeError: Cannot destructure property 'id' of '(intermediate value)' as it is null.
    at checkFluentBit (/app/index.js:371:15)
    at async Timeout._onTimeout (/app/index.js:141:7)
TypeError: Cannot destructure property 'id' of '(intermediate value)' as it is null.
    at checkFluentBit (/app/index.js:371:15)
    at async Timeout._onTimeout (/app/index.js:141:7)

### Steps To Reproduce

Upgrade from [v3.12.27](https://github.com/coollabsio/coolify/releases/tag/v3.12.27) to 3.12.28

### Version

3.12.28

**Comment by zek** [comment]
I checked all docker containers and I see that the problem is in the upgrade process. 
My docker container still uses old version.

> e44b60dde942   coollabsio/coolify:3.12.27                 "docker-entrypoint.s…"   8 days ago          Exited (137) 58 seconds ago                                                                                                  coolify

**Comment by andrasbacsai** [comment]
If you try to restart Coolify with `wget -q https://get.coollabs.io/coolify/install.sh -O install.sh; sudo bash ./install.sh -r`, will it fix it?

**Comment by timeswind** [comment]
Same problem here, after upgrade my own reverse proxy showed "Bad Gateway". After check the docker containers, the coolify web server on public port 3000 is not start, can't access the web dashboard, but the hosted services are running healthy.

**Comment by andrasbacsai** [comment]
Try to install Coolify again (not restarting) with `wget -q https://get.coollabs.io/coolify/install.sh -O install.sh; sudo bash ./install.sh` should solve the problem. 

If not, I will happily fix it by connecting your server. But for that please write me on Discord / Telegram with the server details.

**Comment by timeswind** [comment]
> Try to install Coolify again (not restarting) with `wget -q https://get.coollabs.io/coolify/install.sh -O install.sh; sudo bash ./install.sh` should solve the problem.
> 
> If not, I will happily fix your server. But for that please write me on Discord / Telegram with the server details and credentials.

It works, reinstall with both docker and coolify config override following the instruction with the script. Thank you!

**Comment by andrasbacsai** [comment]
> > Try to install Coolify again (not restarting) with `wget -q https://get.coollabs.io/coolify/install.sh -O install.sh; sudo bash ./install.sh` should solve the problem.
> 
> > 
> 
> > If not, I will happily fix your server. But for that please write me on Discord / Telegram with the server details and credentials.
> 
> 
> 
> It works, reinstall with both docker and coolify config override following the instruction with the script. Thank you!

Great! It is a weird issue caused by switching from DockerHub to ghcr.io. It happens to 1% of the users, so replicating it is near impossible.🥲

**Comment by artworx** [comment]
I had a weird issue with the upgrade from 3.12.27:
- the UI was showing this error: `Command failed with exit code 1: docker pull coollabsio/coolify:3.12.29\nError response from daemon: manifest for coollabsio/coolify:3.12.29 not found: manifest unknown: manifest unknown`
- running the latest version of `install.sh` showed no error but failed to upgrade to a newer version. 

In my case, the error was due to having `TAG=3.10.11` in my .env file. Removing it allowed me to upgrade successfully.
