### ISSUE TITLE
[Bug]: Unable to change Lavalink service port

### ISSUE THREAD

**Issue by chikof** [coollabsio/coolify#995]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

When I try to change the exposed port, it does not work as it should.

### Steps To Reproduce

1. Create a Lavalink service.
2. Change the exposed port and save.
3. Try to deploy

### Version

3.12.28

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
