### ISSUE TITLE
[Feature]: disable TLS 1.0 and TLS 1.1

### ISSUE THREAD

**Issue by agdolla** [coollabsio/coolify#997]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Please make TLS 1.0 and TLS 1.1 either off by default or allow to disable if from the dashboard.

### Why should this be worked on?

TLS 1.0 and TLS 1.1 are obsolete and unsafe.

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
