### ISSUE TITLE
[Feature]: please support  linux/s390x

### ISSUE THREAD

**Issue by herycp** [coollabsio/coolify#998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

from source i can build but i cant run it 

### Why should this be worked on?

provide support to more devices

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
